### ISSUE TITLE
Cannot build lite for iOS

### ISSUE THREAD

**Issue by bylowerik** [tensorflow/tensorflow#102864]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.20.0

### Custom code

No

### OS platform and distribution

MacOS 26.0.1

### Python version

3.11

### Bazel version

7.4.1.

### GCC/compiler version

clang 17.0.0

### Current behavior?

Running `.configure` and select `y`for configuring for iOS and then trying to build with this command:

```
bazel build --config=ios --cpu=ios_arm64 -c opt --cxxopt=--std=c++17 \
  //tensorflow/lite/ios:TensorFlowLiteC_framework
```

gives the following error:

```
/Users/name/Code/Git/tensorflow/tensorflow/lite/core/c/BUILD:355:38: Compiling tensorflow/lite/core/c/common.cc failed: (Aborted): wrapped_clang_pp failed: error executing CppCompile command (from target //tensorflow/lite/core/c:common) bazel-out/darwin_x86_64-opt-exec-ST-4a37db3abddb/bin/external/local_config_apple_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign ... (remaining 45 arguments skipped)
dyld[9495]: missing LC_UUID load command in /private/var/tmp/_bazel_name/e9b99aa5e7fc3acc8b3389554a922f98/execroot/org_tensorflow/bazel-out/darwin_x86_64-opt-exec-ST-4a37db3abddb/bin/external/local_config_apple_cc/wrapped_clang_pp
dyld[9495]: missing LC_UUID load command
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
```

The closes I have found is this: https://github.com/bazelbuild/bazel/issues/27026

Seems to be bazel related, but tensorflow requires `7.4.1`.

### Standalone code to reproduce the issue

```shell
git clone git@github.com:tensorflow/tensorflow.git
cd tensorflow
git checkout v2.20.0
./configure (-y for iOS)
bazel build --config=ios --cpu=ios_arm64 -c opt --cxxopt=--std=c++17 \                   
  //tensorflow/lite/ios:TensorFlowLiteC_framework
```

### Relevant log output

```shell
bazel build --config=ios_fat -c opt --cxxopt=--std=c++17 \                   
  //tensorflow/lite/ios:TensorFlowLiteC_framework
INFO: Reading 'startup' options from /Users/name/Code/Git/tensorflow/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=156
INFO: Reading rc options for 'build' from /Users/erikbylow/Code/Git/tensorflow/.bazelrc:
  Inherited 'common' options: --announce_rc --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility --noenable_bzlmod --noincompatible_enable_cc_toolchain_resolution --noincompatible_enable_android_toolchain_resolution --experimental_repo_remote_exec --java_runtime_version=remotejdk_21
INFO: Reading rc options for 'build' from /Users/name/Code/Git/tensorflow/.bazelrc:
  'build' options: --repo_env=ML_WHEEL_TYPE=snapshot --repo_env=ML_WHEEL_BUILD_DATE= --repo_env=ML_WHEEL_VERSION_SUFFIX= --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --repo_env=USE_PYWRAP_RULES=True --copt=-DGRPC_BAZEL_BUILD --host_copt=-DGRPC_BAZEL_BUILD --action_env=GRPC_BAZEL_RUNTIME=1 --repo_env=PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb --action_env=PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb --repo_env=RULES_PYTHON_ENABLE_PYSTAR=0 --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --host_features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --@rules_python//python/config_settings:precompile=force_disabled
INFO: Reading rc options for 'build' from /Users/erikbylow/Code/Git/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/Users/name/miniconda3/envs/p11/bin/python3 --action_env PYTHON_LIB_PATH=/Users/name/miniconda3/envs/p11/lib/python3.11/site-packages --python_path=/Users/name/miniconda3/envs/p11/bin/python3
INFO: Found applicable config definition build:short_logs in file /Users/name/Code/Git/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/name/Code/Git/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:ios_fat in file /Users/erikbylow/Code/Git/tensorflow/.bazelrc: --config=ios --ios_multi_cpus=arm64,x86_64
INFO: Found applicable config definition build:ios in file /Users/name/Code/Git/tensorflow/.bazelrc: --apple_platform_type=ios --copt=-fembed-bitcode --copt=-Wno-c++11-narrowing --config=apple-toolchain --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --define=with_xla_support=false
INFO: Found applicable config definition build:apple-toolchain in file /Users/name/Code/Git/tensorflow/.bazelrc: --apple_crosstool_top=@local_config_apple_cc//:toolchain --crosstool_top=@local_config_apple_cc//:toolchain --host_crosstool_top=@local_config_apple_cc//:toolchain
INFO: Analyzed target //tensorflow/lite/ios:TensorFlowLiteC_framework (0 packages loaded, 0 targets configured).
ERROR: /Users/name/Code/Git/tensorflow/tensorflow/lite/kernels/BUILD:461:11: Compiling tensorflow/lite/kernels/rng_util.cc failed: (Aborted): wrapped_clang_pp failed: error executing CppCompile command (from target //tensorflow/lite/kernels:rng_util) bazel-out/darwin_x86_64-opt-exec-ST-4a37db3abddb/bin/external/local_config_apple_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign ... (remaining 44 arguments skipped)
dyld[9493]: missing LC_UUID load command in /private/var/tmp/_bazel_name/e9b99aa5e7fc3acc8b3389554a922f98/execroot/org_tensorflow/bazel-out/darwin_x86_64-opt-exec-ST-4a37db3abddb/bin/external/local_config_apple_cc/wrapped_clang_pp
dyld[9493]: missing LC_UUID load command
ERROR: /Users/name/Code/Git/tensorflow/tensorflow/lite/core/c/BUILD:355:38: Compiling tensorflow/lite/core/c/common.cc failed: (Aborted): wrapped_clang_pp failed: error executing CppCompile command (from target //tensorflow/lite/core/c:common) bazel-out/darwin_x86_64-opt-exec-ST-4a37db3abddb/bin/external/local_config_apple_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign ... (remaining 45 arguments skipped)
dyld[9495]: missing LC_UUID load command in /private/var/tmp/_bazel_erikbylow/e9b99aa5e7fc3acc8b3389554a922f98/execroot/org_tensorflow/bazel-out/darwin_x86_64-opt-exec-ST-4a37db3abddb/bin/external/local_config_apple_cc/wrapped_clang_pp
dyld[9495]: missing LC_UUID load command
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.307s, Critical Path: 0.27s
INFO: 9 processes: 9 internal.
ERROR: Build did NOT complete successfully
```

**Comment by adamjstewart** [comment]
I also got the same error message on macOS Tahoe. I'm not building lite or for iOS, I'm just building the core version for macOS. Possibly related to https://github.com/bazelbuild/bazel/issues/27026.

**Comment by bylowerik** [comment]
Any updates about this?

**Comment by adamjstewart** [comment]
Possible duplicate of #100434

**Comment by bylowerik** [comment]
From what I can see the long-term solution is to update to bazel 8.4.2:

https://github.com/bazelbuild/bazel/releases/tag/8.4.2
"* Fixed a compatibility issue with macOS Tahoe. (https://github.com/bazelbuild/bazel/pull/27014)"
https://github.com/bazelbuild/bazel/pull/27014

But there are breaking changes between bazel 7 and bazel 8.

**Comment by adamjstewart** [comment]
Bazel 7.7 also added support for macOS Tahoe, but I tried this and still encountered the same error: https://github.com/bazelbuild/bazel/releases/tag/7.7.0

**Comment by aravindmurali22** [comment]
Hi @bylowerik ,

Thank you for the detailed report. The core TensorFlow Lite project has formally transitioned to [LiteRT](https://github.com/google-ai-edge/LiteRT), which is now the exclusive home for all active development. Please attempt to reproduce this issue using the [latest LiteRT build](https://github.com/google-ai-edge/LiteRT/releases/tag/v2.0.3); if the issue persists, kindly notify us so we can migrate this discussion, otherwise please feel free to close this thread. Going forward, all new reports must be created in the [LiteRT repository](https://github.com/google-ai-edge/LiteRT/issues/new). If you are unable to migrate from the legacy version, please share your specific blockers. For more details, please refer to the [TensorFlow Lite is now LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/) blog and the [Migrate to LiteRT from TensorFlow Lite](https://ai.google.dev/edge/litert/migration) documentation.

**Comment by bylowerik** [comment]
https://github.com/google-ai-edge/LiteRT/issues/4727

**Comment by adamjstewart** [comment]
Likely the same fix as https://github.com/tensorflow/tensorflow/pull/104948

**Comment by aravindmurali22** [comment]
Hi @bylowerik , thank you for the message. Since this issue is now being tracked in the LiteRT repository, I’ll go ahead and close this one to keep things organized. Thanks!
