### ISSUE TITLE
slim.conv2d Error: Input has undefined `axis` dimension.

### ISSUE THREAD

**Issue by sleepfin** [tensorflow/tensorflow#10389]
Here is my code:
```
import tensorflow as tf
slim = tf.contrib.slim
data_format='NCHW'

input = tf.placeholder(dtype=tf.float32, shape=[2, 4, None, None])
with slim.arg_scope([slim.batch_norm], data_format=data_format):
    net = slim.conv2d(input, 4, kernel_size=3, stride=1, padding='SAME', rate=2,
                      data_format=data_format, normalizer_fn=slim.batch_norm)
```

Here is the logs:
```
Traceback (most recent call last):
  File "/home/zzy/workspace/tf-models/mind_slim/examples/test.py", line 9, in <module>
    net = slim.conv2d(input, 4, kernel_size=3, stride=1, padding='SAME', rate=2, data_format=data_format, normalizer_fn=slim.batch_norm)
  File "/home/zzy/anaconda2/envs/tf-gpu-py27-source/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/zzy/anaconda2/envs/tf-gpu-py27-source/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 927, in convolution
    outputs = normalizer_fn(outputs, **normalizer_params)
  File "/home/zzy/anaconda2/envs/tf-gpu-py27-source/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/zzy/anaconda2/envs/tf-gpu-py27-source/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 528, in batch_norm
    outputs = layer.apply(inputs, training=is_training)
  File "/home/zzy/anaconda2/envs/tf-gpu-py27-source/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 320, in apply
    return self.__call__(inputs, **kwargs)
  File "/home/zzy/anaconda2/envs/tf-gpu-py27-source/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 286, in __call__
    self.build(input_shapes[0])
  File "/home/zzy/anaconda2/envs/tf-gpu-py27-source/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 118, in build
    input_shape)
ValueError: ('Input has undefined `axis` dimension. Input shape: ', TensorShape([Dimension(2), Dimension(None), Dimension(None), Dimension(None)]))
```

When I change the rate to 1
Or I change the data_format to 'NHWC' and input to [2, None, None, 4]
It works without any error.
My tensorflow version: 1.1

**Comment by asimshankar** [comment]
Thanks for the report.

I haven't traced how, but it seems that things are fixed in the release candidate for the next release (version 1.2.0-rc1). Could you give that a spin?

**Comment by sleepfin** [comment]
@asimshankar 
I've tried on version 1.2.0-rc1, and the error still remains.

**Comment by sleepfin** [comment]
@asimshankar @aselle Has anyone looked into this issue?

**Comment by asimshankar** [comment]
@sguada : Could you take a look?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by sguada** [comment]
Not sure why that happens, can you try the following to verify the shape information is propagated.


```
import tensorflow as tf
slim = tf.contrib.slim
data_format='NCHW'

input = tf.placeholder(dtype=tf.float32, shape=[2, 4, None, None])
net = slim.conv2d(input, 4, kernel_size=3, stride=1, padding='SAME', rate=2, data_format=data_format)
print(net.shape)
```

If the shape is not well defined the problem then try:

```
input = tf.placeholder(dtype=tf.float32, shape=[2, 4, None, None])
net = tf.layers.convolution2d(input, 4, kernel_size=3, stride=1, padding='SAME', rate=2, data_format='channels_first')
print(net.shape)
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
