### ISSUE TITLE
TF API r1.2 Keras TimeDistributed wrapper error

### ISSUE THREAD

**Issue by NatLun091238** [tensorflow/tensorflow#11135]
import tensorflow.contrib.keras as K
model = K.models.Sequential()
model.add(K.layers.LSTM(150, batch_input_shape=(batch_size, n_in, encoded_length), stateful=True))
model.add(K.layers.RepeatVector(n_out))
model.add(K.layers.LSTM(150, return_sequences=True, stateful=True))
model.add(K.layers.TimeDistributed(K.layers.Dense(encoded_length, activation='softmax')))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

AttributeError: module 'tensorflow.contrib.keras.api.keras.layers' has no attribute 'TimeDistributed'

Is there way to avoid that error?

System info:
---------
Windows 10
TensorFlow r1.2
Python 3.6
Miniconda3
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by skye** [comment]
@fchollet

**Comment by fchollet** [comment]
`TimeDistributed` is available in `tf.contrib.keras.layers`: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/keras/api/keras/layers/__init__.py#L141

Can someone verify that this does in fact not work with the latest version? If it doesn't work, can someone who understands API exports in TF advise on what is wrong...

**Comment by NatLun091238** [comment]
It works perfectly alright in Python 3.5 and TF (version 1.0.1) and Keras 2.0.1

**Comment by WYF-Learning** [comment]
I have the same problem in TF r1.2 and Python 3.5. If I try to use tf.contrib.keras.layers.TimeDistributed, the same error happens. But if I add the code
`from tensorflow.contrib.keras.python.keras.layers.wrappers import TimeDistributed`
I can use TimeDistributed.

When I use TimeDistributed, I meet another trouble.
`from tensorflow.contrib.keras import layers as KL`
`x = KL.Input(batch_shape=[1,5,64,64,3])`
`y = TimeDistributed(KL.Conv2D(16, kernel_size=[3,3], padding='same', activation='relu'))(x)`

Then an error happen
TypeError: rnn() got an unexpected keyword argument 'input_length'

If the Input layer have batch_shape=[None,5,64,64,3] or just shape=[5,64,64,3], the error will not happen. But I just want to use a stateful ConvLSTM2D layer after conv frames in each time step, so the batch size is neccesery. I don't know how to deal with this problem.

**Comment by droidicus** [comment]
With TF v1.2.1 I have to use:
```
from tensorflow.contrib.keras.python.keras.layers.wrappers import TimeDistributed
```

@fchollet It looks like the import did not make it into the latest release, but is in master: https://github.com/tensorflow/tensorflow/blob/v1.2.1/tensorflow/contrib/keras/api/keras/layers/__init__.py

**Comment by NatLun091238** [comment]
Unfortunately, using suggested:
from tensorflow.contrib.keras.python.keras.layers.wrappers import TimeDistributed

Perfectly alright working in older version code gives, the following error message:

  File "C:\Users\natlun\AppData\Local\Continuum\Miniconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\keras\python\keras\layers\wrappers.py", line 194, in call
    unroll=False)

TypeError: rnn() got an unexpected keyword argument 'input_length'

**Comment by skye** [comment]
@martinwicke it looks like something is wrong with the imports/sealing

**Comment by martinwicke** [comment]
Looks like this is resolved on master.

**Comment by ASvyatkovskiy** [comment]
I am still getting this error in 1.3.0, using example by @WYF-Learning: [1]

I have compared the argument list of `rnn` in `keras.backend.tensorflow_backend` https://github.com/fchollet/keras/blob/7c7d73530c1ab1b47f9fb5f0612ec13fef1a26c6/keras/backend/tensorflow_backend.py#L2316

and in `tensorflow/contrib/keras/python/keras/backend.py` https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/keras/python/keras/backend.py#L2471

the latter does not have `input_length`, which in Keras is marked as not relevant for Tensorflow backend,
but it still present in the call to `rnn` in the `tensorflow/contrib/keras/python/keras/layers/wrappers` https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/keras/python/keras/layers/wrappers.py#L203

commenting it out fixes it:

```python
      _, outputs, _ = K.rnn(
          step,
          inputs,
          initial_states=[],
          #input_length=input_shape[1],
          unroll=False)
      y = outputs
    else:
```

[1]
```bash
$ python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.3.0'
>>> 
>>> from tensorflow.contrib.keras.python.keras.layers.wrappers import TimeDistributed
>>> from tensorflow.contrib.keras import layers as KL
>>> x = KL.Input(batch_shape=[1,5,64,64,3])
>>> y = TimeDistributed(KL.Conv2D(16, kernel_size=[3,3], padding='same', activation='relu'))(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexeys/.local/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/engine/topology.py", line 396, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/home/alexeys/.local/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/alexeys/.local/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/layers/wrappers.py", line 208, in call
    unroll=False)
TypeError: rnn() got an unexpected keyword argument 'input_length'
```
