### ISSUE TITLE
Memory Overhead/Leak in Android lib

### ISSUE THREAD

**Issue by faifai21** [tensorflow/tensorflow#11334]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Nexus 6p, Android v7.1.2
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:  1.2.0-rc2
- **Python version**: 2.7.10
- **Bazel version (if compiling from source)**: 0.4.5-homebrew
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**:
- **Exact command to reproduce**: 
-- Selective Headers: ` bazel build -c opt --copt="-DSELECTIVE_REGISTRATION" --copt="-DSUPPORT_SELECTIVE_REGISTRATION" //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a `
-- Added `tensorflow/core/kernels/random_shuffle_queue_op.cc` and `tensorflow/core/kernels/random_shuffle_op.cc` to `tf_op_files.txt` file
-- Removed unused nodes: `bazel build tensorflow/tools/graph_transforms:transform_graph
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=model.pb \
--out_graph=optimized_model.pb \
--inputs='input' \
--outputs='output' \
--transforms='
  strip_unused_nodes(type=float, shape="1,299,299,3")'`

### Describe the problem
The Tensorflow Android library is using a lot more memory than I expected. It almost seems like it's maintaining a reference to all input arrays, as memory usage balloons the longer the model is used. 
Here is an example of the memory usage with feed/run/fetch commented out (source code below):

![no_tensorflow](https://user-images.githubusercontent.com/4616968/27930636-3342a548-624c-11e7-91ed-3f4f56b7cf5f.png)

Here is the same timeframe, with the only difference being that feed/run/fetch is enabled:

![tensorflow](https://user-images.githubusercontent.com/4616968/27930738-954e125e-624c-11e7-82f2-cc21e67bc5d3.png)

Memory usage is over three times worse. The longer I leave the model running, the more memory usage increases (it eventually gets to 110 mb).

The below method is being called at a rate of 4.419011933 per sec (i.e. it's processing 4.412 input arrays per second), where each input array is of size 96\*96\*3 (27648).

This is being run on a Nexus 6p, running stock 7.1.2. The model is a conv net with inception, batch norm and dropout, trained using tensorflow slim. 

### Source code / logs
Commented out:
```java
public float[] runInference(float[] pixels) {
        assertRightSize(pixels);
        final float[] outputArray = new float[128];
        // Simulate some sort of output
        Arrays.fill(outputArray, new Random().nextInt(1000)/new Random().nextFloat());
//     inferenceInterface.feed("phase_train", new bool[]{false});
//     inferenceInterface.feed("input", pixels, 1, 96, 96, 3);
//     inferenceInterface.run(new String[]{"output"});
        // Copy the output Tensor back into the output array.
//     inferenceInterface.fetch("output", outputArray);

        return outputArray;
    }
```
Enabled:

```java
public float[] runInference(float[] pixels) {
        assertRightSize(pixels);
        final float[] outputArray = new float[128];
        inferenceInterface.feed("phase_train", new bool[]{false});
        inferenceInterface.feed("input", pixels, 1, 96, 96, 3);
        inferenceInterface.run(new String[]{"output"});
        // Copy the output Tensor back into the output array.
        inferenceInterface.fetch("output", outputArray);

        return outputArray;
    }
```

where `float[] pixels` is a float array of size `27648`, denoting the pixels in an image of size 96x96.

The custom code is an update to the InferenceInterface to accept boolean types during feeding: 

```java
public void feed(String inputName, boolean[] src, long... dims) {
        byte[] b = new byte[src.length];
        for (int i = 0; i < src.length; ++i) {
            b[i] = (byte) (src[i] ? 1 : 0);
        }
        addFeed(inputName, Tensor.create(DataType.BOOL, dims, ByteBuffer.wrap(b)));
    }
```

Please let me know if there's any other information I can provide.

**Comment by cy89** [comment]
It looks to me like there's a related discussion about the overheads of feed/run/fetch in #8712. Does any of that help?

**Comment by faifai21** [comment]
@cy89 thanks for the response. I read that issue before posting mine and it was related. Unfortunately, the discussion turned towards timing and performance as opposed to memory allocation.

**Comment by cy89** [comment]
Makes sense. @petewarden, are there perhaps any updates about our Android TF ecosystem and its memory usage behavior?

**Comment by andrewharp** [comment]
@faifai21 Thanks for the detailed report! Are you able to determine exactly how much the memory use increases per inference pass? If you change the size of your input array, does the rate of increase vary proportionally? I'm just curious if something else in the run() call could be allocating memory that never gets cleaned up.

@asimshankar Any idea why this might be happening, given that closeFetches() and closeFeeds() are both guaranteed to be called every invocation of TensorFlowInferenceInterface.run()?

**Comment by asimshankar** [comment]
There was a leak in 1.2.0-rc0 and prior versions,
 fixed by https://github.com/tensorflow/tensorflow/commit/8304e197ea9eeb617f224a1ba0cc4068596098d1

@faifai21 : Since you're building from source, could you confirm that your build includes the commit mentioned above?

**Comment by faifai21** [comment]
@asimshankar I just checked and that commit is included in the build. I can try rebuilding from the latest release and see if the issue goes away. 

> Are you able to determine exactly how much the memory use increases per inference pass?

@andrewharp I'll get you that information first thing tomorrow morning.

**Comment by faifai21** [comment]
@asimshankar I pulled in the latest master and built against commit 
https://github.com/tensorflow/tensorflow/commit/99a38ffd9d77c55ca6d0c373c6d4b72686284ac5. The memory leak is still occurring though.

@andrewharp It seems like memory is increasing by ~0.1 MB per inference pass, which makes sense as each input array is around 110kb. As well, increasing the size of the input array does cause the memory leak to increase:

- With an input array of 96\*96\*3, each input array was 110kb. Memory usage was increasing at ~0.5 mb per sec. With 4.41 inputs processed per sec, it can be inferred that memory was increasing by ~0.11 mb per run.
- With an input array of 120\*120\*3, each input array was 172kb. Memory usage was increasing at 0.7 mb per sec. Since input size was increased, we were processing slightly less inputs per sec than before. Assuming we were processing 4.1 inputs per sec now, we can infer that each run increased memory by ~0.17mb.

I was unable to increase input size by anymore, as that caused BufferOverflow exceptions with FloatBuffer as the input array was copied over when creating the Tensor.

**Comment by faifai21** [comment]
I also tried decreasing the size of the input array to 30\*30\*3, which resulted in each input having a size of 10kb. The memory leak was still present, but it was much less apparent. As expected though, memory usage increased by ~0.01 mb per run.

**Comment by rhythm9229** [comment]
@andrewharp We are also experiencing the same issue with tensorflow library on android. The memory keeps on increasing as the number of inference runs keep on increasing. This is leading to lot of out of memory errors in our application. 
We tried creating a new TensorFlowInferenceInterface after every inference but even that did not solve the problem. It looks like a memory leak in tensorflow c++ library.

**Comment by faifai21** [comment]
> We tried creating a new TensorFlowInferenceInterface after every inference but even that did not solve the problem.

I tried the same thing, and can confirm that the memory leak was still there.

**Comment by faifai21** [comment]
@andrewharp @asimshankar any updates on this?

**Comment by faifai21** [comment]
We've also found this issue in our iOS tensorflow library (also built from source), which makes sense, given that the memory leak seems to be in C/C++ code.

**Comment by Mr-Grieves** [comment]
Experiencing the same problem as above: lots of memory leakage due to the feeding operation.

While I'm sure I'm missing a lot of intricacies here, the source seems obvious to me. Each call to feed is allocating new memory for each tensor (float tensor in my case):
`addFeed(inputName, Tensor.**create**(dims, FloatBuffer.wrap(src))); `

Is there no way to overwrite the data in the existing FloatBuffer after the initial feed call? (instead of allocating space for an entirely new Tensor each time?) Would that not solve the memory leak we are experiencing?

**Comment by asimshankar** [comment]
@faifai21 : No updates yet unfortunately. Since you have this in C++ land as well, perhaps you could come up with a small C++ snippet that demonstrates this - and it might make it easier to trace any problems by running the sample on a desktop/laptop instead of a mobile device.

@Mr-Grieves : I'm not following. During every call to `feed` a new `Tensor` is created, but it is released with a call to [`closeFeeds()`](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/android/java/org/tensorflow/contrib/android/TensorFlowInferenceInterface.java#L157) on every call to `run()`.  Are you experiencing "leaks" or is it that total memory usage is higher than you'd want (and waits for a garbage collection cycle to come down)?

**Comment by Mr-Grieves** [comment]
@asimshankar: The latter. I'm new to Java and still not totally comfortable with the idea of leaving objects around to be cleaned up by the GC... My app runs as desired initially, but slows down over time, and eventually grinds to a halt. I initially thought this issue was being caused by a memory leak, but perhaps the memory management is running as it should and the cause of the slowdown lies somewhere else... 

I've attached a screenshot of my Memory and CPU monitors. GC events are being triggered every 10s or so, with 99% of the allocations occurring during the `addFeed(inputName, Tensor.create(dims, FloatBuffer.wrap(src)));`.

If the memory is not the problem, my issue is most likely CPU related, in which case I am posting in the wrong thread.

![memorytrace](https://user-images.githubusercontent.com/19175336/28688053-6c3455d4-72c5-11e7-981e-114d0cdf3d3d.png)

**Comment by andrewharp** [comment]
@Mr-Grieves It could be thermal throttling slowing down the CPU frequency after sustained load. I'm not sure if you can view this in Android Studio, but you could try [printing the frequency](https://stackoverflow.com/questions/3021054/how-to-read-cpu-frequency-on-android-device) manually via adb.

**Comment by faifai21** [comment]
@asimshankar Thanks for the response. I've spoken to our iOS engineers a few more times and it seems like the memory leak does not actually happen in iOS land. This seems to be an issue on Android only, perhaps in the JNI methods?

**Comment by faifai21** [comment]
@asimshankar @andrewharp This memory leak is blocking us from shipping tensorflow on Android. Are there any updates for this? Is there anything I can do to help? I tried looking through the source code to find the memory leak, but I'm not well versed in c/c++.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by drpngx** [comment]
Sorry this fell through the cracks. Is that still a problem with the latest versions?

Our current recommended platform for mobile is tflite, maybe that fits your needs better?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by drpngx** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by deepaksuresh** [comment]
@drpngx  I'm facing the exact same issue on version `1.5.0`. As I keep performing inference on an Android device the memory consumed by the app keeps increasing.

No. of Inference runs     |  Memory usage
-------------------------- | ------------------
1                                     |     5.7 Mb
15                                   |     206 Mb
20                                   |     242 Mb
25                                   |     757 Mb
30                                   |     922 Mb

Is there a fix for this issue?

**Comment by asimshankar** [comment]
@deepaksuresh : There isn't any known fixes. Could you file a new issue with the details, particularly if there are any instructions to reproduce the problem? Can you share the model perhaps?

**Comment by deepaksuresh** [comment]
@asimshankar I'm running the model from a `.pb` file. It is 70 Mb, how can I share it with you?
