### ISSUE TITLE
0.7.0 pip packages are not named properly (error: is not a supported wheel on this platform).  [Will be fixed in next binary release]

### ISSUE THREAD

**Issue by terrybroad** [tensorflow/tensorflow#1142]
My os is ubuntu 14.04
My python version is 2.7.6

Following the instructions for installing with pip I am getting this error:

> $ sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.0-py2-none-linux_x86_64.whl
> tensorflow-0.7.0-py2-none-linux_x86_64.whl is not a supported wheel on this platform.
> Storing debug log for failure in /home/terence/.pip/pip.log

It works fine installing older releases of tensorflow with pip but not this one.

**Comment by HellMood** [comment]
I had the same issues while trying to install tensor flow 0.70 GPU for python3 (pip3). For whatever reason, it was just the FILENAME which was wrong. It has to be in a special format to be legal. You can check yourself by following the instructions [here](http://stackoverflow.com/questions/28107123/cannot-install-numpy-from-wheel-format) which tupels of tags are legal for your machine. In my case the command

*"sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.0-py3-none-linux_x86_64.whl"*

produced the exact error message you got above. However, when i downloaded the file myself and renamed it to "tensorflow-0.7.0-**cp34**-none-linux_x86_64.whl", then executed the command again with changed filename, it worked =)

**Comment by jendap** [comment]
@terrybroad do you have 64 bit ubuntu or 32? (run `uname -a`)

@HellMood thanks for a workaround. I have to try it myself. We have intentionally used this name so that people with py35 don't have to rename it. It installs fine on 14.04 with py3 but we have not tried 15.10 yet.

**Comment by gmathur** [comment]
I am seeing the same issue with Python 2.7.x on Ubuntu 14.04 LTS

**Comment by hannes-brt** [comment]
I can confirm this: I had to change `py2` to `cp27` in the filename after which it installed.

**Comment by kronos-cm** [comment]
Exact same issue as @terrybroad on Ubuntu 14.04 (64 bit) with Python 2.7

**Comment by terrybroad** [comment]
Cheers @HellMood and @hannes-brt downloading it and changing `py2` to `cp27` worked for me.

@jendap I have 64 bit ubuntu installed.

**Comment by Hassan-Baker** [comment]
I have the same issue, it did not solved by any of theses solution. Here is the log.

```
HTTP error 404 while getting https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.0-cp27-none-linux_x86_64.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 547, in unpack_http_url
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found

```

**Comment by MarkWissler** [comment]
Same issue happening for me on Ubuntu 14.04 LTS and python 2.7

**Comment by ahaque** [comment]
Same issue on Ubuntu 14.04 x64 Python 2.7 using commit 3ff0f0d17b4eec946a2874da0cf896776c01a80a

**Comment by amolchanov86** [comment]
Same issue on both CPU and GPU with Ubuntu 14.04 64x
_tensorflow-0.7.0-py2-none-linux_x86_64.whl is not a supported wheel on this platform.
Storing debug log for failure in /home/artem/.pip/pip.log_

**Comment by newtrack4** [comment]
Same issue on Ubuntu 14.04 x64 Python 2.7 and using GPU, downloading locally and renaming .whl file doesn't help, Tensorflow.6.0 worked fine. I did upgrade to Cuda7.5 and cudnn4  first.

**Comment by vrv** [comment]
(We will build the proper wheels for 0.7.1)

**Comment by vrv** [comment]
Ok, we built a few new wheels for 0.7.1 (see https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/g3doc/get_started/os_setup.md) -- before we announce more widely we'd like to make sure it's working well for the people here who have had issues -- let us know if you still have problems with these new wheels.

We have not yet built a version for all python, just the ones in standard installations.

**Comment by sridhar912** [comment]
Hello vrv,
I had a similar issue stated above with python 2.7.6 and cpu setup. But i ran the new wheel 0.7.1 and it worked for me.

**Comment by ahaque** [comment]
@vrv I can confirm that 0.7.1 works on Ubuntu 14.04 x86_64 with Python 2.7.6. Thanks!

**Comment by sebdi** [comment]
@vrv I also can confirm that the new wheel works for my Ubuntu 14.04 x86_64

**Comment by Hassan-Baker** [comment]
@vrv  I confirm that it work. Thanks.

**Comment by mtb2718** [comment]
Had the same issue.. this fixed it @vrv. Thanks!

**Comment by steindekker** [comment]
I am getting this error: ' tensorflow-0.7.1-cp34-none-linux_x86_64.whl is not a supported wheel on this platform.'

I have installed version 0.7.0 without any problems. 

Python: 3.5.0+
Ubuntu 15.10 x64

**Comment by mhejrati** [comment]
Had the same issue and it is fixed with the new build, thanks @vrv

**Comment by newtrack4** [comment]
The new  7.1 wheel installs properly and runs the mnist convolutional example just fine.
Using Ubuntu 14.04 x64, Python 2.7 using GPU, Cuda7.5 and cudnn4.

**Comment by kYroL01** [comment]
Now it works ! I suggest you to create a link to https://github.com/tensorflow/tensorflow/blob/r0.7/tensorflow/g3doc/get_started/os_setup.md
in the installation section of the site. It could be easy for users with the same problem.

Thanks

**Comment by lukaszbk** [comment]
@vrv, the new 0.7.1 works for me on Ubuntu 14.04 x64. Both with Python 2.7 and 3.4 using GPU, Cuda7.5 and cudnn4.

**Comment by sunil-at-gh** [comment]
Problem installing on Mac OSX 10.10 with Python 3.4:
```
$ sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp35-none-any.whl
Password:
tensorflow-0.7.1-cp35-none-any.whl is not a supported wheel on this platform.
Storing debug log for failure in /Users/Sunil/.pip/pip.log
```

And here is the pip.log:
```
/usr/local/bin/pip3 run on Wed Feb 24 23:29:18 2016
tensorflow-0.7.1-cp35-none-any.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/req.py", line 167, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
pip.exceptions.UnsupportedWheel: tensorflow-0.7.1-cp35-none-any.whl is not a supported wheel on this platform.
```

Was earlier able to install from mac/tensorflow-0.6.0-py3-none-any.whl

**Comment by sunil-at-gh** [comment]
Downloading and renaming the file s.t. "cp35" -> "cp34" appears to work.

**Comment by bernardoct** [comment]
@vrv The wheel 0.7.1 worked for me on Ubuntu 14.04 x86_64 with Python 2.7.6. Thanks!

**Comment by maxwbuckley** [comment]
@vrv  The new wheel 0.7.1 fixed this problem for me also.

I too am using Ubuntu 14.04 x86_64 with Python 2.7.6

Thanks for the fix.

**Comment by j-towns** [comment]
Are you planning to fix this for Python 3.3 and 3.5 (which you claim to support)?

**Comment by vrv** [comment]
We do support python 3.3 and 3.5 in that TensorFlow does work with them when compiled from sources.

However, since I suspect you mean provide pre-built pip wheels for 3.3 and 3.5 -- that is indeed what we would like to do, but we have not gotten around to yet.

**Comment by j-towns** [comment]
> However, since I suspect you mean provide pre-built pip wheels for 3.3 and 3.5 -- that is indeed what we would like to do, but we have not gotten around to yet.

Would be greatly appreciated if you could do this, I need to test a project which uses TensorFlow on Travis CI and don't want to have to build TensorFlow for each Python version every time I test.

**Comment by codingyourlife** [comment]
I have Ubuntu 14.04 LTS 64bit and wanted to install tensorflow-0.7.1-cp34-none-linux_x86_64.whl and had the same error. This is what woked for me:
```
sudo apt-get install python3-setuptools -y && sudo easy_install3 pip -y && sudo apt-get install python 3.5-dev -y && sudo apt-get install python3.4-dev -y
sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp34-none-linux_x86_64.whl
```

**Comment by wallflower1** [comment]
I have Ubuntu 14.04 LTS x86_64 with Python3.5 and it is giving me the same error for build 0.7.1, downloading and changing the filename is no help. What else can I try?

**Comment by codingyourlife** [comment]
you need python 3.4. v3.5 is not yet supported. read 1 post above what did the trick for me.

**Comment by fu9ar** [comment]
I'm getting the same error for build 0.7.1 as well.

**Comment by vrv** [comment]
Closing, I think we fixed (some) of these issues in 0.8.0

**Comment by tobegit3hub** [comment]
I have the similar problem with Python 3.5 and it works with Python 3.4 😃

**Comment by Jx-b** [comment]
@vrv I still get the same issue trying to install version 0.8.0 with python 2.7.11 on OS X 10.11.5 
`$ pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.8.0-py2-none-any.whl
tensorflow-0.8.0-py2-none-any.whl is not a supported wheel on this platform.`

**Comment by jendap** [comment]
@tobegit3hub yes, that does not work. Python 3.5 will be part of net release. In the meanwhile you can try nightly build - http://ci.tensorflow.org/view/Nightly/job/nightly-python35-linux-cpu/

**Comment by cyriltw** [comment]
@Jx-b you are not alone. Using OS X 10.11.5 and having the same issue.

**Comment by tobegit3hub** [comment]
Thanks @jendap and all contributors 🎉

**Comment by plsuarez** [comment]
i can not install tensorflow on windows 8 64bits?
i got this error
is not a supported wheel on this platform

**Comment by double-flower** [comment]
my python version is 2.7.6, the Linux version is Ubuntu 14.04.5 LTS. When I installed tensorflow 0.7.1, i got the following error:
**/usr/bin/pip run on Mon Mar 13 09:30:39 2017
tensorflow-0.7.1-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 168, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
UnsupportedWheel: tensorflow-0.7.1-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.**
I do not know how to result the problem.
