### ISSUE TITLE
no such package '@local_config_cuda//cuda'

### ISSUE THREAD

**Issue by alex-taffe** [tensorflow/tensorflow#11859]
Please go to Stack Overflow for help and support:

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

No

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Linux — Ubuntu Server 16.04 LTS

Linux PowerEdge-R810 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **TensorFlow installed from (source or binary)**:

Source

- **TensorFlow version (use command below)**:

master, r1.3, r1.2.1

- **Python version**: 

2.7

- **Bazel version (if compiling from source)**:

Build label: 0.5.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 28 08:34:59 2017 (1501230899)
Build timestamp: 1501230899
Build timestamp as int: 1501230899

- **CUDA/cuDNN version**:

CUDA 8, cuDNN 6

- **GPU model and memory**:

GTX 1080, 8gb

- **Exact command to reproduce**:

`./configure;bazel build -c opt —config=cuda //tensorflow/tools/pip_package:build_pip_package`

-**Premade script**:
```
alex@PowerEdge-R810:~$ sh tf_env_collect.sh 
Collecting system information...
tf_env_collect.sh: 39: [: Linux: unexpected operator
tf_env_collect.sh: 41: [: Linux: unexpected operator
Traceback (most recent call last):
  File "/tmp/check_tf.py", line 1, in <module>
    import tensorflow as tf;
ImportError: No module named tensorflow
Wrote environment to tf_env.txt. You can review the contents of that file.
and use it to populate the fields in the github issue template.

cat tf_env.txt

alex@PowerEdge-R810:~$ cat tf_env.txt

== cat /etc/issue ===============================================
Linux PowerEdge-R810 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== uname -a =====================================================
Linux PowerEdge-R810 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.11.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow

== env ==========================================================
LD_LIBRARY_PATH /usr/local/cuda-8.0/lib64
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Fri Jul 28 18:12:37 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.59                 Driver Version: 384.59                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:0E:00.0 Off |                  N/A |
| 37%   32C    P0    32W / 180W |      0MiB /  8105MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-8.0/lib64/libcudart_static.a
/usr/local/cuda-8.0/lib64/libcudart.so.8.0.61
/usr/local/cuda-8.0/doc/man/man7/libcudart.7
/usr/local/cuda-8.0/doc/man/man7/libcudart.so.7
```

### Describe the problem

I am trying to compile tensorflow from source. When I run the above command, the bazel build fails. This is the configuration I used as well as the error. It seems like some other people had this issue but the threads were for much older versions and none of the solutions fixed it: 

```
Please specify the location of python. [Default is /usr/bin/python]: 
Found possible Python library paths:
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: 
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]: y
Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [y/N]: 
No Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: 
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: 
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL support? [y/N]: y
OpenCL support will be enabled for TensorFlow.

Please specify which C++ compiler should be used as the host C++ compiler. [Default is /usr/bin/g++]: 
Please specify which C compiler should be used as the host C compiler. [Default is /usr/bin/gcc]: 
Please specify the location where ComputeCpp for SYCL 1.2 is installed. [Default is /usr/local/computecpp]: 
Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 8.0]: 
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
"Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]: 
Please specify the location where cuDNN 6 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 6.1]
Do you want to use clang as CUDA compiler? [y/N]: 
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Do you wish to build TensorFlow with MPI support? [y/N]: 
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.
Configuration finished
...............
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/alex/tensorflow/third_party/gpus/cuda_configure.bzl", line 1039
		_create_local_cuda_repository(repository_ctx)
	File "/home/alex/tensorflow/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/home/alex/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/home/alex/tensorflow/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)
depsets cannot contain mutable items
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/alex/tensorflow/third_party/gpus/cuda_configure.bzl", line 1039
		_create_local_cuda_repository(repository_ctx)
	File "/home/alex/tensorflow/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/home/alex/tensorflow/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/home/alex/tensorflow/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)
depsets cannot contain mutable items
INFO: Elapsed time: 13.663s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

**Comment by reedwm** [comment]
@jrvb Can you take a look? This is similar to #9435, but the error message is a bit different.

**Comment by Helique** [comment]
I have been having this same problem for the last day. I have installed the latest version of bazel (0.5.3). I previously got a build working, but then uninstalled it. When I went back to reinstall, I encountered this error. Two days ago I also was able to get this working on docker, but now it also does not work in docker.

#Environment Data
```
== cat /etc/issue ===============================================
Linux learningOne 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.2 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== uname -a =====================================================
Linux learningOne 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.11.0)
protobuf (3.3.0)
tensorflow-tensorboard (1.3.1)

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
ImportError: No module named pywrap_tensorflow_internal


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

== env ==========================================================
LD_LIBRARY_PATH /home/david/torch/install/lib:/home/david/torch/install/lib::/usr/local/cuda/lib64
DYLD_LIBRARY_PATH /home/david/torch/install/lib:/home/david/torch/install/lib:

== nvidia-smi ===================================================
Fri Jul 28 16:46:56 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.22                 Driver Version: 381.22                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 0000:01:00.0      On |                  N/A |
| 23%   39C    P8    19W / 250W |    886MiB / 11172MiB |     14%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1077    G   /usr/lib/xorg/Xorg                             485MiB |
|    0      2144    G   compiz                                         239MiB |
|    0      2445    G   /proc/self/exe                                 114MiB |
|    0      9261    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    44MiB |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-8.0/lib64/libcudart_static.a
/usr/local/cuda-8.0/lib64/libcudart.so.8.0.61
/usr/local/cuda-8.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-8.0/doc/man/man7/libcudart.7
```

#Bazel Build Version
```

Build label: 0.5.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 28 08:34:59 2017 (1501230899)
Build timestamp: 1501230899
Build timestamp as int: 1501230899
```

#Error Message

```
david@learningOne:~/realtf$ bazel build --config=opt --config=cuda --explain=result.txt --verbose_failures //tensorflow/tools/pip_package:build_pip_package

ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/david/realtf/third_party/gpus/cuda_configure.bzl", line 1039
		_create_local_cuda_repository(repository_ctx)
	File "/home/david/realtf/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/home/david/realtf/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/home/david/realtf/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)
depsets cannot contain mutable items
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/david/realtf/third_party/gpus/cuda_configure.bzl", line 1039
		_create_local_cuda_repository(repository_ctx)
	File "/home/david/realtf/third_party/gpus/cuda_configure.bzl", line 976, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/home/david/realtf/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/home/david/realtf/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)
depsets cannot contain mutable items
INFO: Elapsed time: 0.561s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

**Comment by jeroenherczeg** [comment]
I have the setup and problem as @Helique.

**Comment by wentaol** [comment]
Rolling bazel back to 0.5.2 seems to fix the problem

**Comment by jeroenherczeg** [comment]
@wentaol How do you rollback to 5.2?

**Comment by wentaol** [comment]
`sudo apt-get purge bazel `
followed by installation from 0.5.2 binaries 
https://docs.bazel.build/versions/master/install-ubuntu.html

**Comment by jeroenherczeg** [comment]
@wentaol Thank you, i have downgraded to 0.5.2 and `bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`seems to be running.

**Comment by ExonRen** [comment]
Same problem and thanks @wentaol . Btw it is weird that bazel doesn't provide old versions in `apt-cache` once upgraded and rollback has to be done via binary installer.

**Comment by alex-taffe** [comment]
Yep bazel 0.5.2 fixed the problem for me as well, very strange

**Comment by StatML** [comment]
I met the same problem. Rolling back to bazel 0.5.2 does not help >_<

**Comment by eLvErDe** [comment]
I had the "depsets cannot contain mutable items" error, rolling back from bazel 0.5.3 to 0.5.2 fixed it.

It's still not building properly (honestly what's wrong with all this bazel crap ?!?!) but that first error is gone.

Regards, Adam.

**Comment by StatML** [comment]
Hi guys, this issue had been fixed. We do not need to roll back bazel now! :)

**Comment by reedwm** [comment]
Closing since this issue is fixed.

**Comment by Mistobaan** [comment]
this problem still exist in bazel 5.3 and 5.4. If you build for the 1.2.1 branch. Going back to 5.2 fixed the problem.

**Comment by reedwm** [comment]
My machine updated Bazel to 0.6.0 today and now I have the problem. Reverting to 0.5.4 fixed the issue.

/CC @gunan can you comment on why updating Bazel seems to temporarily break TensorFlow and what is done to fix the issue when it breaks?

**Comment by gunan** [comment]
I have no context on the issue. Could you provide full repro instructions?
You may want to use a clean docker container to reproduce the problem, then I can work on that to see what is going on.

**Comment by reedwm** [comment]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: Master, commit 4270c4a00bb90d97418df5b0e9b6b3e148a72a1e
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.6.0
- **CUDA/cuDNN version**: Cuda 8, cuDNN 6
- **GPU model and memory**: GTX 1080 8 GB
- **Exact command to reproduce**:

```
bazel build -c opt —config=cuda //tensorflow/tools/pip_package:build_pip_package
```

### Describe the problem
When I run the above command with Bazel 0.6.0 after running `./configure` with GPU support, I get the error
```
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/usr/local/google/home/reedwm/tensorflows/tensorflow2/third_party/gpus/cuda_configure.bzl", line 1042
		_create_local_cuda_repository(repository_ctx)
	File "/usr/local/google/home/reedwm/tensorflows/tensorflow2/third_party/gpus/cuda_configure.bzl", line 975, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/usr/local/google/home/reedwm/tensorflows/tensorflow2/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/usr/local/google/home/reedwm/tensorflows/tensorflow2/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/usr/local/google/home/reedwm/tensorflows/tensorflow2/third_party/gpus/cuda_configure.bzl", line 1042
		_create_local_cuda_repository(repository_ctx)
	File "/usr/local/google/home/reedwm/tensorflows/tensorflow2/third_party/gpus/cuda_configure.bzl", line 975, in _create_local_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/usr/local/google/home/reedwm/tensorflows/tensorflow2/third_party/gpus/cuda_configure.bzl", line 145, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/usr/local/google/home/reedwm/tensorflows/tensorflow2/third_party/gpus/cuda_configure.bzl", line 120, in get_cxx_inc_directories
		set(includes_cpp)
The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
```
The issue does not occur with Bazel 0.5.4

**Comment by gunan** [comment]
@vladmos Any ideas?

**Comment by vladmos** [comment]
It's a planned incompatible change in Bazel. `set` is deprecated and was removed by default from Bazel starting with 0.6. You can use the flag from the error message to temporarily use `set` in .bzl files, but the flag will be removed at some point too (probably at Bazel 0.8), so it's recommended to fix the .bzl files.

**Comment by vladmos** [comment]
The initial issue has nothing to do with that, the `set` deprecation starts with Bazel 0.6 which was released today.

We have Tensorflow on our CI and we tried to clean up everything before the release but it looks like we don't run some targets that reproduce the issue. //cc @damienmg

**Comment by damienmg** [comment]
We do not run all the config of TensorFlow, that's why we do ask for a full run of TF CI with Bazel RC. Seems like even that have missed them

**Comment by skjensen** [comment]
I solved the issue by editing line 120 in tensorflow/third_party/gpus/cuda_configure.bzl 
I changed set to depset as recommended in error output.

**Comment by gunan** [comment]
@vladmos sent a Pr to fix this in master. Closing this issue.
Please let us know if you still see issues in master.
For the release branch, using bazel versions older than 0.6.0 is recommended.

**Comment by RichLogan** [comment]
I was just having the same and just wanted to comment and confirm that updating to `master` immediately fixed it with no other changes needed :+1:

**Comment by jerrin92** [comment]
I am facing this issue with bazel 0.11.1 on r1.7

`
tf-latest.img:~/tensorflow> bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"
............
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/root/tensorflow/third_party/gpus/cuda_configure.bzl", line 1142
		_create_local_cuda_repository(repository_ctx)
	File "/root/tensorflow/third_party/gpus/cuda_configure.bzl", line 1001, in _create_local_cuda_repository
		_find_nvvm_libdevice_dir(repository_ctx, cuda_config)
	File "/root/tensorflow/third_party/gpus/cuda_configure.bzl", line 724, in _find_nvvm_libdevice_dir
		auto_configure_fail(("Cannot find libdevice.10.bc un...))
	File "/root/tensorflow/third_party/gpus/cuda_configure.bzl", line 210, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))
`

**Comment by reedwm** [comment]
@jerrin92 can you file a new issue? I think you are encountering a different error since you have the error message "Cuda Configuration Error".

**Comment by ghltshubh** [comment]
@jerrin92 @gunan Any idea about this error?

**Comment by ghltshubh** [comment]
https://github.com/tensorflow/tensorflow/issues/22400

**Comment by scutzhe** [comment]
> Rolling bazel back to 0.5.2 seems to fix the problem
sure? 0.5.2 has released

**Comment by kavita-moholkar** [comment]
> Hi guys, I just found that this issue had been fixed. We do not need to roll back bazel now! :)

please send solution

**Comment by LenaGer** [comment]
fixed it creating new environment variable : 'BAZEL_SH' value: 'C:\msys64\usr\bin\bash.exe'

**Comment by kavita-moholkar** [comment]
Done

**Comment by redradist** [comment]
gunan I have faced with the same error during the building tensorflow v2.3.0 ...
```console
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
        _create_local_cuda_repository(<1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
        _get_cuda_config(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
        find_cuda_config(repository_ctx, <2 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
        _exec_find_cuda_config(<3 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
        execute(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
        fail(<1 more arguments>)
Repository command failed
script.py:124: DeprecationWarning: invalid escape sequence \d
  match = re.match("#define %s +(\d+)" % name, line)
script.py:260: DeprecationWarning: invalid escape sequence \d
  pattern = "Cuda compilation tools, release \d+\.\d+, V(\d+\.\d+\.\d+)"
script.py:553: DeprecationWarning: invalid escape sequence \w
  match = re.match("^(/[^/ ]*)+/lib/\w+-linux-gnu/?$", os.environ[env_name])
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-10.2/include/cuda.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda/include/cublas_api.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn_version.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
        _create_local_cuda_repository(<1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
        _get_cuda_config(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
        find_cuda_config(repository_ctx, <2 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
        _exec_find_cuda_config(<3 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
        execute(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
        fail(<1 more arguments>)
Repository command failed
script.py:124: DeprecationWarning: invalid escape sequence \d
  match = re.match("#define %s +(\d+)" % name, line)
script.py:260: DeprecationWarning: invalid escape sequence \d
  pattern = "Cuda compilation tools, release \d+\.\d+, V(\d+\.\d+\.\d+)"
script.py:553: DeprecationWarning: invalid escape sequence \w
  match = re.match("^(/[^/ ]*)+/lib/\w+-linux-gnu/?$", os.environ[env_name])
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-10.2/include/cuda.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda/include/cublas_api.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn_version.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
INFO: Elapsed time: 8.508s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```
