### ISSUE TITLE
tf.estimator.inputs.numpy_input_fn does not accept dict as labels.

### ISSUE THREAD

**Issue by DeckerCHAN** [tensorflow/tensorflow#12610]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win10 x64
- **TensorFlow installed from (source or binary)**: pip install
- **TensorFlow version (use command below)**: r1.3
- **Python version**:  3.5 amd 64
- **Bazel version (if compiling from source)**: Used binary
- **CUDA/cuDNN version**: CUDA 8.0 + CuDNN 6.0
- **GPU model and memory**:  GeForce GTX 1070 8.00GiB

According to the ```tf.estimator.Estimator``` [document](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator), estimator accept dict as labels input. However, when I creating a ```tf.estimator.inputs.numpy_input_fn``` as:
```python
train_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"x": samples.astype(np.float32)},
    y={'go_action': np.full(samples.shape[0], 1), 'operation': ops.astype(np.float32)},
    batch_size=100,
    num_epochs=None,
    shuffle=True)
``` 

then feed it to ```estimator``` like:
```python
action_estimator.train(
    input_fn=train_input_fn,
    steps=20000,
    hooks=[logging_hook])

```

it throw me an error:
```
Traceback (most recent call last):
  File "G:/Python/onmyoji-hacker/primary/cnnopnet.py", line 120, in <module>
    hooks=[logging_hook])
  File "C:\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "C:\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 628, in _train_model
    input_fn, model_fn_lib.ModeKeys.TRAIN)
  File "C:\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 499, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "C:\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 585, in _call_input_fn
    return input_fn(**kwargs)
  File "C:\Python\Python35\lib\site-packages\tensorflow\python\estimator\inputs\numpy_io.py", line 109, in input_fn
    if len(set(v.shape[0] for v in ordered_dict_x.values())) != 1:
  File "C:\Python\Python35\lib\site-packages\tensorflow\python\estimator\inputs\numpy_io.py", line 109, in <genexpr>
    if len(set(v.shape[0] for v in ordered_dict_x.values())) != 1:
AttributeError: 'dict' object has no attribute 'shape'

```

**Comment by terrylewis60** [comment]
Stop sending me shit cracker the shit all y'all send me is shit and not
what I request cracker all you do is fill up my memory now stop patty
packerwood and forward the message to the other crackers

**Comment by facaiy** [comment]
Hi, @DeckerCHAN . [numpy_input_fn](https://www.tensorflow.org/api_docs/python/tf/estimator/inputs/numpy_input_fn) API: `y: numpy array object. None if absent.`. It confirms that `y` cannot be a dictionary. 

So if I understand correctly, the issue is a feature request, right? I can work on it, however, I don't know whether tensorflower approve it. 

By the way, perhaps `pandas_input_fn` needs handle DataFrame for y as well.

**Comment by DeckerCHAN** [comment]
@facaiy Thank you for the reply!

Yes, this is about a feature. I am working on a model seems like: 
![this](https://i.stack.imgur.com/gxxo0.png)

In fact, the model is more complex than that due to the model is used to simulate game operation. Classification is responsible for decide whether it is good time for action. Then the regression will give the details about the action. It contains a combination of CNN and RNN.

So that, when I'm training the model, I have to let model know whether I am training the classification or regression since I had a proper loss function. I'm wondering if we can feed feature with dict, why we can not feed dict as labels as well.

**Comment by facaiy** [comment]
Sounds reasonable! I'll open a PR next week. However, you have to wait for next release even though the PR is accepted.

**Comment by facaiy** [comment]
@DeckerCHAN Don't close the issue until it's resolved or rejected by tensorflower. So, reopen it please.

**Comment by carlthome** [comment]
Status on this? It's a huge limitation of the tf.estimator API that labels can only be a tensor, IMO. It would be a lot nicer to have named tensors in the case of multi-headed output.

**Comment by facaiy** [comment]
Yes, I think the issue has been resolved.

**Comment by carlthome** [comment]
I assume it's still a problem for the corresponding Pandas input_fn though, right? And similarly throughout the docs there is a very strong assumption that the output of an estimator will always be a single tensor of labels (which is not the case for a multitude of common models).

Overall, it's strange that `features` can be multi-headed while `labels` cannot, and I think it should be changed to match for example how Keras does it where `Model(inputs, outputs)` takes dicts, lists or single tensors.

**Comment by facaiy** [comment]
Yes, I think pandas_input_fn is unchanged. And would you like to make a contribution?

**Comment by carlthome** [comment]
No, I fear we'll just run into problems further down the line when deploying to Serving and the like.

Maybe the author of the Estimator API could clarify if it's supposed to only be used for predicting a one/multi-hot vector or if it's intended for more general usage of any models with a fit/predict workflow.

My particular use case at the moment is a stateful RNN with one sequence as input and two sequences as output (meaning I also input the previous RNN states, to work over several minibatches during inference).

**Comment by facaiy** [comment]
Hi, @carlthome. I don't have any experience on multi-lable problem, hence the problem is beyond my scope. However, I really appreciate your feedback, and I believe your worry should be reasonable.

Since the issue is a feature request, perhaps it could be better to open a new issue for you and take a further discussion for Estimator API there. By the way, you might be interested in #1351.

**Comment by facaiy** [comment]
Hi, @DeckerCHAN. Because the PR has been merged, could you close the issue? Thanks.

**Comment by yongtang** [comment]
Close the issue as the PR has been merged. Thanks!
