### ISSUE TITLE
Bazel & cmake compilations for Windows are completely broken

### ISSUE THREAD

**Issue by zyavrik** [tensorflow/tensorflow#12978]
Can't compile tensorflow revision 1.3 using Bazel (revision of the last successful nightly build using cmake). Error is the following:

```
ERROR: C:/tensorflow-1.3rc1/tensorflow/stream_executor/BUILD:39:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed (Exit 2): cl.exe failed: error executing command
  cd C:/msys64/tmp/_bazel_dmitry/ehgyfc-k/execroot/org_tensorflow
  SET CUDA_COMPUTE_CAPABILITIE=None
    SET CUDA_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0
    SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;
    SET NO_WHOLE_ARCHIVE_OPTION=1
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\usr\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl;C:\WINDOWS\system32
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/Dmitry/AppData/Local/Programs/Python/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Users/Dmitry/AppData/Local/Programs/Python/Python36/lib/site-packages
    SET TEMP=C:\Users\Dmitry\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2
    SET TF_CUDA_VERSION=8.0
    SET TF_CUDNN_VERSION=6
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL=0
    SET TMP=C:\Users\Dmitry\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 -march=native -march=native /nologo /I. /Ibazel-out/msvc_x64-py3-opt/genfiles /Iexternal/bazel_tools /Ibazel-out/msvc_x64-py3-opt/genfiles/external/bazel_tools /Iexternal/protobuf /Ibazel-out/msvc_x64-py3-opt/genfiles/external/protobuf /Iexternal/eigen_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/msvc_x64-py3-opt/genfiles/external/local_config_sycl /Iexternal/gif_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/gif_archive /Iexternal/jpeg /Ibazel-out/msvc_x64-py3-opt/genfiles/external/jpeg /Iexternal/com_googlesource_code_re2 /Ibazel-out/msvc_x64-py3-opt/genfiles/external/com_googlesource_code_re2 /Iexternal/farmhash_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/farmhash_archive /Iexternal/fft2d /Ibazel-out/msvc_x64-py3-opt/genfiles/external/fft2d /Iexternal/highwayhash /Ibazel-out/msvc_x64-py3-opt/genfiles/external/highwayhash /Iexternal/png_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/png_archive /Iexternal/zlib_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/zlib_archive /Iexternal/snappy /Ibazel-out/msvc_x64-py3-opt/genfiles/external/snappy /Iexternal/local_config_cuda /Ibazel-out/msvc_x64-py3-opt/genfiles/external/local_config_cuda /Iexternal/bazel_tools/tools/cpp/gcc3 /Iexternal/protobuf/src /Ibazel-out/msvc_x64-py3-opt/genfiles/external/protobuf/src /Iexternal/eigen_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/eigen_archive /Iexternal/gif_archive/lib /Ibazel-out/msvc_x64-py3-opt/genfiles/external/gif_archive/lib /Iexternal/gif_archive/windows /Ibazel-out/msvc_x64-py3-opt/genfiles/external/gif_archive/windows /Iexternal/farmhash_archive/src /Ibazel-out/msvc_x64-py3-opt/genfiles/external/farmhash_archive/src /Iexternal/png_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/png_archive /Iexternal/zlib_archive /Ibazel-out/msvc_x64-py3-opt/genfiles/external/zlib_archive /Iexternal/local_config_cuda/cuda /Ibazel-out/msvc_x64-py3-opt/genfiles/external/local_config_cuda/cuda /Iexternal/local_config_cuda/cuda/cuda/include /Ibazel-out/msvc_x64-py3-opt/genfiles/external/local_config_cuda/cuda/cuda/include /showIncludes /DEIGEN_MPL2_ONLY /DSNAPPY /MT /O2 /c tensorflow/stream_executor/cuda/cuda_gpu_executor.cc /Fobazel-out/msvc_x64-py3-opt/bin/tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_gpu_executor.o.
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(274): error C2589: 'constant': illegal token on right side of '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(274): error C2059: syntax error: '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(289): error C2589: 'constant': illegal token on right side of '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(289): error C2059: syntax error: '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(372): error C2589: 'constant': illegal token on right side of '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(372): error C2059: syntax error: '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(620): error C2589: 'constant': illegal token on right side of '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(620): error C2059: syntax error: '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(639): error C2589: 'constant': illegal token on right side of '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(639): error C2059: syntax error: '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(666): error C2589: 'constant': illegal token on right side of '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(666): error C2059: syntax error: '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(680): error C2589: 'constant': illegal token on right side of '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(680): error C2059: syntax error: '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(694): error C2589: 'constant': illegal token on right side of '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(694): error C2059: syntax error: '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(708): error C2589: 'constant': illegal token on right side of '::'
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc(708): error C2059: syntax error: '::'
cl : Command line warning D9002 : ignoring unknown option '-march=native'
cl : Command line warning D9002 : ignoring unknown option '-march=native'
____Building complete.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
____Elapsed time: 216.281s, Critical Path: 141.66s
```

If you try to compile master revision then compilation even won't start with the error:

```
ERROR: C:/tensorflow/tensorflow/core/kernels/BUILD:1932:1: C++ compilation of rule '//tensorflow/core/kernels:resize_bilinear_op_gpu' failed (Exit 2).
.\tensorflow/core/util/cuda_kernel_helper.h(359): error C3861: 'atomicAdd': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(360): error C3861: 'atomicAdd': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(361): error C3861: 'atomicAdd': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(362): error C3861: 'atomicAdd': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(365): error C3861: 'atomicMax': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(366): error C3861: 'atomicMax': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(378): error C3861: 'max': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(378): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(394): error C3861: '__longlong_as_double': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(394): error C3861: '__double_as_longlong': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(393): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(399): error C3861: '__longlong_as_double': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(445): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(462): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(498): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(507): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(516): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(527): error C3861: '__int_as_float': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(527): error C3861: '__float_as_int': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(526): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(529): error C3861: '__int_as_float': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(538): error C3861: '__longlong_as_double': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(538): error C3861: '__double_as_longlong': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(537): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(540): error C3861: '__longlong_as_double': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(548): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(557): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(566): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(577): error C3861: '__int_as_float': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(577): error C3861: '__float_as_int': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(576): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(579): error C3861: '__int_as_float': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(588): error C3861: '__longlong_as_double': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(588): error C3861: '__double_as_longlong': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(587): error C3861: 'atomicCAS': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(590): error C3861: '__longlong_as_double': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(617): error C2065: 'warpSize': undeclared identifier
.\tensorflow/core/util/cuda_kernel_helper.h(619): error C2059: syntax error: 'volatile'
.\tensorflow/core/util/cuda_kernel_helper.h(620): error C3861: '__shfl': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(621): error C3861: '__shfl': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(622): error C2059: syntax error: 'volatile'
.\tensorflow/core/util/cuda_kernel_helper.h(637): error C2065: 'warpSize': undeclared identifier
.\tensorflow/core/util/cuda_kernel_helper.h(639): error C2059: syntax error: 'volatile'
.\tensorflow/core/util/cuda_kernel_helper.h(640): error C3861: '__shfl_up': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(641): error C3861: '__shfl_up': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(642): error C2059: syntax error: 'volatile'
.\tensorflow/core/util/cuda_kernel_helper.h(657): error C2065: 'warpSize': undeclared identifier
.\tensorflow/core/util/cuda_kernel_helper.h(659): error C2059: syntax error: 'volatile'
.\tensorflow/core/util/cuda_kernel_helper.h(660): error C3861: '__shfl_down': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(661): error C3861: '__shfl_down': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(662): error C2059: syntax error: 'volatile'
.\tensorflow/core/util/cuda_kernel_helper.h(677): error C2065: 'warpSize': undeclared identifier
.\tensorflow/core/util/cuda_kernel_helper.h(679): error C2059: syntax error: 'volatile'
.\tensorflow/core/util/cuda_kernel_helper.h(680): error C3861: '__shfl_xor': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(681): error C3861: '__shfl_xor': identifier not found
.\tensorflow/core/util/cuda_kernel_helper.h(682): error C2059: syntax error: 'volatile'
cl : Command line warning D9002 : ignoring unknown option '-march=native'
cl : Command line warning D9002 : ignoring unknown option '-march=native'
cl : Command line warning D9002 : ignoring unknown option '-x'
cl : Command line warning D9002 : ignoring unknown option '-nvcc_options=relaxed-constexpr'
cl : Command line warning D9002 : ignoring unknown option '-nvcc_options=ftz=true'
cl : Command line warning D9024 : unrecognized source file type 'cuda', object file assumed
cl : Command line warning D9027 : source file 'cuda' ignored
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 3817.327s, Critical Path: 143.61s
```

I'll be glad to help to fix the issues. But I absolutely has no idea what's going on here. Can anybody help to fix Windows compilation please? Currently here is no build for Windows with AVX, AVX2 support in the whole world!

**Comment by andrewharp** [comment]
The atomicAdd errors at least might be due to a missing -latomic flag in the linkopts of the relevant binary. Maybe something got added to the bazel builds and left out of cmake?

**Comment by snnn** [comment]
What's your bazel version?  You may need to turn on wrappers.
Please take a look at the last comments in 
https://github.com/bazelbuild/bazel/issues/2075

**Comment by zyavrik** [comment]
Version: bazel-0.5.4-windows-x86_64.

**Comment by snnn** [comment]
Hi @zyavrik ,

Please set USE_MSVC_WRAPPER=1

e.g. 
```
bazel --output_base C:\t build --action_env=USE_MSVC_WRAPPER=1 //tensorflow/tools/pip_package:build_pip_package
```

**Comment by zyavrik** [comment]
**snnn**, thanks for help! It helped with the described error in 1.3 revision. But then another error appeared:

```
____Loading package: @pcre//
____Loading package: tensorflow/contrib/saved_model
____Found 1 target...
____Building...
____[0 / 6] Creating source manifest for //tensorflow/tools/pip_package:build_pip_package
____[13 / 205] Writing file tensorflow/python/tools/saved_model_cli.zip-2.params
____[16 / 214] Writing file external/snappy/libsnappy.a-2.params [for host]
____[20 / 244] Writing file tensorflow/python/gen_sparse_ops_py_wrappers_cc.exe-2.params [for host]
____[34 / 481] Writing file external/jpeg/libjpeg.a-2.params [for host]
____From Compiling tensorflow/core/lib/hash/crc32c_accelerate.cc [for host]:
usage: cl [ option... ] filename... [ /link linkoption... ]
Warning: Unmatched arguments: -msse3
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

ERROR: C:/tensorflow-r1.3/tensorflow/core/BUILD:1350:1: output 'tensorflow/core/_objs/lib_hash_crc32c_accelerate_internal/tensorflow/core/lib/hash/crc32c_accelerate.o' was not created.
ERROR: C:/tensorflow-r1.3/tensorflow/core/BUILD:1350:1: not all outputs were created or valid.
____Building complete.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
____Elapsed time: 3629.194s, Critical Path: 0.29s
```

I just run it again and got another error (why???):

`
Dmitry@Desktop MINGW64 /c/tensorflow-r1.3
$ bazel.exe build --config=opt --config=win-cuda --action_env=USE_MSVC_WRAPPER=1 //tensorflow/tools/pip_package:build_pip_package --verbose_failures
____Loading complete.  Analyzing...
____Found 1 target...
____Building...
____[1 / 40] Executing genrule @gif_archive//:windows_unistd_h [for host]
____[19 / 162] Creating source manifest for //tensorflow/python:gen_training_ops_py_wrappers_cc [for host]
____[24 / 274] Expanding template tensorflow/python/tools/freeze_graph.cmd
____[25 / 280] Writing file tensorflow/core/liblinalg_ops_op_lib.lo-2.params [for host]
____[37 / 305] Creating source manifest for //tensorflow/python:gen_random_ops_py_wrappers_cc [for host]
____[41 / 312] Executing genrule //third_party/py/numpy:dummy
____[41 / 315] Expanding template external/jpeg/jconfigint_win.h
____[44 / 318] Writing file tensorflow/python/tools/freeze_graph.zip-2.params
____[56 / 347] Creating source manifest for //tensorflow/python:gen_state_ops_py_wrappers_cc [for host]
____[59 / 353] Expanding template tensorflow/python/debug/offline_analyzer.cmd
____[61 / 357] Writing file tensorflow/core/libuser_ops_op_lib.lo-2.params [for host]
____[64 / 364] Executing genrule @local_config_cuda//cuda:cuda-extras
____[70 / 389] Writing file tensorflow/core/libparsing_ops_op_lib.lo-2.params [for host]
____[77 / 405] Writing file tensorflow/core/liblogging_ops_op_lib.lo-2.params [for host]
____[96 / 451] Writing file tensorflow/cc/ops/random_ops_gen_cc.exe-2.params [for host]
____[101 / 474] Writing file tensorflow/cc/ops/data_flow_ops_gen_cc.exe-2.params [for host]
____[110 / 492] Creating source manifest for //tensorflow/cc:ops/linalg_ops_gen_cc [for host]
____[112 / 510] Writing file external/swig/swig.exe-2.params [for host]
____[125 / 592] Compiling external/pcre/pcre_config.c [for host]
____From Compiling external/pcre/pcre_globals.c [for host]:
usage: cl [ option... ] filename... [ /link linkoption... ]
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

ERROR: C:/msys64/tmp/_bazel_dmitry/lla8twkh/external/pcre/BUILD.bazel:5:1: output 'external/pcre/_objs/pcre/external/pcre/pcre_globals.o' was not created.
ERROR: C:/msys64/tmp/_bazel_dmitry/lla8twkh/external/pcre/BUILD.bazel:5:1: not all outputs were created or valid.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
____Elapsed time: 8.557s, Critical Path: 2.01s
`

One more try - and error is different again. What's going on here?

`
Dmitry@Desktop MINGW64 /c/tensorflow-r1.3
$ bazel.exe build --config=opt --config=win-cuda --action_env=USE_MSVC_WRAPPER=1 //tensorflow/tools/pip_package:build_pip_package --verbose_failures
____Loading complete.  Analyzing...
____Found 1 target...
____Building...
____[1 / 296] Compiling external/pcre/pcre_version.c [for host]
____From Compiling external/swig/Source/Preprocessor/cpp.c [for host]:
usage: cl [ option... ] filename... [ /link linkoption... ]
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

____From Compiling external/pcre/pcre_get.c [for host]:
usage: cl [ option... ] filename... [ /link linkoption... ]
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

____From Compiling external/swig/Source/Swig/naming.c [for host]:
usage: cl [ option... ] filename... [ /link linkoption... ]
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

ERROR: C:/msys64/tmp/_bazel_dmitry/lla8twkh/external/pcre/BUILD.bazel:5:1: output 'external/pcre/_objs/pcre/external/pcre/pcre_get.o' was not created.
ERROR: C:/msys64/tmp/_bazel_dmitry/lla8twkh/external/swig/BUILD.bazel:5:1: output 'external/swig/_objs/swig/external/swig/Source/Preprocessor/cpp.o' was not created.
ERROR: C:/msys64/tmp/_bazel_dmitry/lla8twkh/external/pcre/BUILD.bazel:5:1: not all outputs were created or valid.
ERROR: C:/msys64/tmp/_bazel_dmitry/lla8twkh/external/swig/BUILD.bazel:5:1: output 'external/swig/_objs/swig/external/swig/Source/Swig/naming.o' was not created.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
____Elapsed time: 2.194s, Critical Path: 0.62s
`

And so on... Each time different error!

**Comment by snnn** [comment]
You get different error for different runs because: there are many errors, not only one.  This is very like invoking gmake with "-j".

Please add " --verbose_failures" to your build command,  so we can see more logs.

BTW, the code under r1.3 branch is not compilable right now, because of the sha256sum issue.

**Comment by zyavrik** [comment]
I fixed sga256sum issue. The errors are different. I'll be able to provide more details later.

**Comment by phg1024** [comment]
Just FYI, I've successfully compile v1.3 with CMake + Visual Studio 2015 + CUDA 8 + CUDNN 6.1 on Windows 10. Had to include various hacks to fix several compilation error related to Eigen and CUDA though 😒  But at least it works now 😄  Feel free to ask me about issues you run into if you are compiling with similar set up.

I follow this post to get started, but it doesn't show how to fix the errors I got.
https://joe-antognini.github.io/machine-learning/build-windows-tf
This post is also very helpful for the next step if you want to build a standalone application:
https://joe-antognini.github.io/machine-learning/windows-tf-project

**Comment by zyavrik** [comment]
@phg1024, can you please describe your hacks? I'm going to try to compile it tomorrow.

**Comment by phg1024** [comment]
@zyavrik These are the changes I can find in the code: https://github.com/phg1024/tensorflow/commit/291f29533a510797f64e1f646b38aeea62238389

There are also some configuration changes about the VS project settings to resolve undefined symbols in the linking stage. You can follow take a look at https://joe-antognini.github.io/machine-learning/windows-tf-project to get some sense about how to resolve those.

**Comment by zyavrik** [comment]
Can anybody crate pull request for those fixes?

**Comment by phg1024** [comment]
@zyavrik Did those fixes work for you? They need to be cleaned up for a pull request though. I don't have much time to do that right now...

**Comment by zyavrik** [comment]
@phg1024, your fixes in code helped with some errors. Now I get the following errors:

```
"C:\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default target) (3) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\tf_core_gpu_kernels.vcxproj" (default target) (129) ->
(CustomBuild target) ->
  C:/tensorflow/tensorflow/core/kernels/bias_op_gpu.cu.cc(178): error : identifier "__syncwarp" is undefined [C:\tensor
flow\tensorflow\contrib\cmake\build\tf_core_gpu_kernels.vcxproj]
  C:/tensorflow/tensorflow/core/kernels/bias_op_gpu.cu.cc(178): error : identifier "__syncwarp" is undefined [C:\tensor
flow\tensorflow\contrib\cmake\build\tf_core_gpu_kernels.vcxproj]
  C:/tensorflow/tensorflow/core/kernels/bias_op_gpu.cu.cc(178): error : identifier "__syncwarp" is undefined [C:\tensor
flow\tensorflow\contrib\cmake\build\tf_core_gpu_kernels.vcxproj]
```
Also I don't understand yet how "Building a standalone C++ Tensorflow program on Windows" hints can help to build python package.

**Comment by phg1024** [comment]
When you use cmake to config the project, did you enable GPU? `__syncwarp` should be defined in `tensorflow/tensorflow/core/util/cuda_kernel_helper.h` already.

For the windows related post, you can get some idea about how to resolve undefined symbols issues if you ever want to build a c++ program using the compiled tensorflow library. It won't help you much if you only need to use the python API.

**Comment by zyavrik** [comment]
Yes, I did. My cmake command:

```
cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^
More? -DSWIG_EXECUTABLE=C:/swigwin/swig.exe ^
More? -DPYTHON_EXECUTABLE=C:/Users/Dmitry/AppData/Local/Programs/Python/Python36/python.exe ^
More? -DPYTHON_LIBRARIES=C:/Users/Dmitry/AppData/Local/Programs/Python/Python36/libs/python36.lib ^
More? -Dtensorflow_ENABLE_GPU=ON ^
More? -DCUDNN_HOME="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0"

```

**Comment by phg1024** [comment]
Looks like `C:/tensorflow/tensorflow/core/kernels/bias_op_gpu.cu.cc` didn't include `tensorflow/tensorflow/core/util/cuda_kernel_helper.h`? Did you check if `tensorflow/tensorflow/core/util/cuda_kernel_helper.h` has `__syncwarp` defined?

**Comment by zyavrik** [comment]
No, `__syncwarp` is not defined in `cuda_kernel_helper.h` in the master revision.

**Comment by zyavrik** [comment]
I incorrectly merged your changes to the repository. The same files were changed recently. Thanks for your help!

**Comment by zyavrik** [comment]
Correctly applied fixes on the master revision: [tensorflow-patch.zip](https://github.com/tensorflow/tensorflow/files/1309489/tensorflow-patch.zip)

**Comment by zyavrik** [comment]
Still get errors :(
```

"C:\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj" (default target) (3) ->
(Link target) ->
  maxpooling_op.obj : error LNK2001: unresolved external symbol "public: bool __cdecl tensorflow::functor::MaxPoolForwa
rdWithOptionalArgmax<struct Eigen::QInt8>::operator()(struct Eigen::QInt8 const *,int,int,int,int,int,int,int,int,int,i
nt,int,int,struct Eigen::QInt8 *,__int64 *,struct Eigen::GpuDevice const &)" (??R?$MaxPoolForwardWithOptionalArgmax@UQI
nt8@Eigen@@@functor@tensorflow@@QEAA_NPEBUQInt8@Eigen@@HHHHHHHHHHHHPEAU34@PEA_JAEBUGpuDevice@4@@Z) [C:\tensorflow\tenso
rflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]
  C:\tensorflow\tensorflow\contrib\cmake\build\Release\pywrap_tensorflow_internal.dll : fatal error LNK1120: 1 unresolv
ed externals [C:\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow_internal.vcxproj]

```

**Comment by phg1024** [comment]
I fixed this error in https://github.com/phg1024/tensorflow/commit/291f29533a510797f64e1f646b38aeea62238389

You need to explicitly instantiate it
```
template struct MaxPoolForwardWithOptionalArgmax<Eigen::QInt8>;
```
Then you can just compile this very file in Visual studio and see if you get other errors. If not, go ahead and do the linking stage only.

**Comment by zyavrik** [comment]
Sorry for my mistake again! But still can't compile it... :(

```
"C:\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\tf_extension_ops.vcxproj" (default target) (130) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\_gru_ops.vcxproj" (default target) (220) ->
(Link target) ->
  blas_gemm.obj : error LNK2019: unresolved external symbol "void __cdecl nsync::nsync_mu_rlock(struct nsync::nsync_mu_
s_ *)" (?nsync_mu_rlock@nsync@@YAXPEAUnsync_mu_s_@1@@Z) referenced in function "public: void __cdecl tensorflow::functo
r::TensorCuBlasGemm<float>::operator()(class tensorflow::OpKernelContext *,bool,bool,unsigned __int64,unsigned __int64,
unsigned __int64,float,float const *,int,float const *,int,float,float *,int)" (??R?$TensorCuBlasGemm@M@functor@tensorf
low@@QEAAXPEAVOpKernelContext@2@_N1_K22MPEBMH3HMPEAMH@Z) [C:\tensorflow\tensorflow\contrib\cmake\build\_gru_ops.vcxproj
]
  blas_gemm.obj : error LNK2019: unresolved external symbol "void __cdecl nsync::nsync_mu_runlock(struct nsync::nsync_m
u_s_ *)" (?nsync_mu_runlock@nsync@@YAXPEAUnsync_mu_s_@1@@Z) referenced in function "public: void __cdecl tensorflow::fu
nctor::TensorCuBlasGemm<float>::operator()(class tensorflow::OpKernelContext *,bool,bool,unsigned __int64,unsigned __in
t64,unsigned __int64,float,float const *,int,float const *,int,float,float *,int)" (??R?$TensorCuBlasGemm@M@functor@ten
sorflow@@QEAAXPEAVOpKernelContext@2@_N1_K22MPEBMH3HMPEAMH@Z) [C:\tensorflow\tensorflow\contrib\cmake\build\_gru_ops.vcx
proj]
  C:\tensorflow\tensorflow\contrib\cmake\build\Release\_gru_ops.dll : fatal error LNK1120: 2 unresolved externals [C:\t
ensorflow\tensorflow\contrib\cmake\build\_gru_ops.vcxproj]


"C:\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\tf_extension_ops.vcxproj" (default target) (130) ->
"C:\tensorflow\tensorflow\contrib\cmake\build\_lstm_ops.vcxproj" (default target) (221) ->
  blas_gemm.obj : error LNK2019: unresolved external symbol "void __cdecl nsync::nsync_mu_rlock(struct nsync::nsync_mu_
s_ *)" (?nsync_mu_rlock@nsync@@YAXPEAUnsync_mu_s_@1@@Z) referenced in function "public: void __cdecl tensorflow::functo
r::TensorCuBlasGemm<float>::operator()(class tensorflow::OpKernelContext *,bool,bool,unsigned __int64,unsigned __int64,
unsigned __int64,float,float const *,int,float const *,int,float,float *,int)" (??R?$TensorCuBlasGemm@M@functor@tensorf
low@@QEAAXPEAVOpKernelContext@2@_N1_K22MPEBMH3HMPEAMH@Z) [C:\tensorflow\tensorflow\contrib\cmake\build\_lstm_ops.vcxpro
j]
  blas_gemm.obj : error LNK2019: unresolved external symbol "void __cdecl nsync::nsync_mu_runlock(struct nsync::nsync_m
u_s_ *)" (?nsync_mu_runlock@nsync@@YAXPEAUnsync_mu_s_@1@@Z) referenced in function "public: void __cdecl tensorflow::fu
nctor::TensorCuBlasGemm<float>::operator()(class tensorflow::OpKernelContext *,bool,bool,unsigned __int64,unsigned __in
t64,unsigned __int64,float,float const *,int,float const *,int,float,float *,int)" (??R?$TensorCuBlasGemm@M@functor@ten
sorflow@@QEAAXPEAVOpKernelContext@2@_N1_K22MPEBMH3HMPEAMH@Z) [C:\tensorflow\tensorflow\contrib\cmake\build\_lstm_ops.vc
xproj]
  C:\tensorflow\tensorflow\contrib\cmake\build\Release\_lstm_ops.dll : fatal error LNK1120: 2 unresolved externals [C:\
tensorflow\tensorflow\contrib\cmake\build\_lstm_ops.vcxproj]
```

**Comment by zyavrik** [comment]
`nsync_mu_rlock` is used in `tensorflow/core/platform/default/mutex.h` but never declared in the project. It looks like it's from the following project: https://github.com/google/nsync/blob/master/public/nsync_mu.h

**Comment by zyavrik** [comment]
Similar issue on Linux: https://github.com/tensorflow/tensorflow/issues/12810

**Comment by phg1024** [comment]
It's one of the external dependencies. Try to find nsync under `cmake\build\external` and also the `cmake\build\nsync`. You should be able to find compiled `.lib` files and header files. Link them to the library you were trying to compile.

**Comment by zyavrik** [comment]
You are right - .h file and nsync.lib are there. But how can I link them? Sorry, I'm not C++ programmer, just trying to recompile tensorflow with AVX and AVX2 support to use with Pyhton...

**Comment by zyavrik** [comment]
Does anybody has success to compile tensorflow with GPU support for Windows?

**Comment by snnn** [comment]
Hi @zyavrik

Sure. I do it every day. For TF 1.3 release, you don't need any patch to make it work (except the sha256sum). Master branch often breaks.  But, you'd better use Python 3.5 instead, as the support for Python 3.6 is relatively new.

**Comment by zyavrik** [comment]
It's impossible to build 1.3 release on CPU with AVX512 support because of different errors.

**Comment by snnn** [comment]
Hi @zyavrik

Then you may disable it first.  TF can only pass the tests while AVX is disabled, so I choose to not enable AVX.

**Comment by zyavrik** [comment]
The only one reason to compile it is to enable AVX, AVX2 support...

**Comment by snnn** [comment]
I don't think "Bazel & cmake compilations for Windows are completely broken" is true. Maybe it lacks something for you, but it is not completely broken. TF has a large userbase on Windows. If the build system is completely broken,  how can they use it? Google has a philosophy that every build should be reproducible.   You can get known how google build TF from http://ci.tensorflow.org/.  These build scripts are maintained in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build 

Please describe your problem precisely: which is broken, under what kind of situation? So the others can help you. In the same time, if you know where the problem is and you can fix it, contributions are welcomed.

**Comment by zyavrik** [comment]
Master revision doesn't work at all - both with bazel and cmake. Errors were provided. Revision 1.3 doesn't work on CPU with AVX512 support (even when AVX512 isn't used).

**Comment by aselle** [comment]
@gunan, could you look at what could be done to streamline/fix this to work out of the box?

**Comment by gunan** [comment]
We are sorry about the negative experience you have been seeing.
Bazel support out of the box on windows is still WIP. I will recommend using cmake build for all users on windows. We are hoping early in 2018 we will be able to declare out of the box bazel support working.
In the meantime, I recommend sticking with the build scripts @snnn pointed out.

AVX, AVX2 support we have are weak, and AVX512 support is definitely missing. That is because we did not have the cycles, and we had other priorities. We are sorry about the inconvenience. But in case you would like to contribute fixes to these, I am happy to accept your Pull Requests. After all, TF is an open source project for all of us to improve.

Windows has been a difficult platform to support for us because our primary platform is almost always linux, and the build systems and compilers we need to use are very different on two platforms. We hope to be able to triage most of the reported issues, but unfortunately we have limited bandwidth.

**Comment by snnn** [comment]
My personal view: I always perfer to use bazel than cmake for building tensorflow on Windows, because it can do incremental build very well.  At this time, bazel on Windows works well except it can't build the custom ops under tf.contrib, thus all stuffs under tf.contrib are missing.  We won't get it until https://github.com/bazelbuild/bazel/issues/1920 is fixed.  I wish bazel team could put more resources on this issue. After that, we can deprecate cmake and unify the build systems, reduce the extra maintain cost.  The more build systems we have, the harder to add a new file in tensorflow.

**Comment by gunan** [comment]
This has been fixed. but we still need to tidy up our bazel build.
I will close this issue as the main problem here is fixed.

**Comment by meteorcloudy** [comment]
@snnn I think you would be interested in https://github.com/meteorcloudy/tensorflow/commits/fix_contrib_with_cc_import

I can now use Bazel@HEAD to build tensorflow on Windows with `//tensorflow/contrib/...` enabled.

The fix requires a new rule, `cc_import`, that will come out with Bazel 0.10.0, so I'll send to PR to fix tensorflow/contrib/... after 0.10,0 is released.

**Comment by snnn** [comment]
@meteorcloudy That's awesome! Thank you!

**Comment by gunan** [comment]
@meteorcloudy would that also enable custom op support on windows?
Once that is tackled, our official builds on windows will be converted to bazel.

**Comment by snnn** [comment]
@gunan , Yes, exactly as what you said. Now they are working Bazel 0.9.0, and Bazel 0.10.0 will be released in later Jan.

**Comment by meteorcloudy** [comment]
@snnn is absolutely correct!

**Comment by chnlior** [comment]
Is the **MKL** option on ./configure working on windows too (using bazel)?
I know it is working well on linux, but I am trying to compile tensorflow-cpu with **MKL** on windows and the contrib/cmake does not support it.

**Comment by gunan** [comment]
No.
MKL only works on linux right now/

**Comment by GCChen97** [comment]
Hi @zyavrik ,have you solved this problem?This problem also confused me a lot.

**Comment by stevenwong** [comment]
For anyone stumbling on this while googling `ignoring unknown option '-march=native'`, the issue is because `march=native` is a `gcc` flag. I've got my TF+GPU 1.14 to build in Windows by using `/arch:AVX2`. See [MSVC docs](https://docs.microsoft.com/en-us/cpp/build/reference/arch-x64?view=vs-2019)
