### ISSUE TITLE
Multiple bugs in dynamic_rnn

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#1306]
I know this feature remains alpha and unsupported, but I've run into a number of various bugs so I thought it may be worth reporting.

Just a simple RNN with a simple loss function + optimizer doesn't work. Take this code snippet for example:

```
num_stepss = [34, 20, 44, 18]
inputs = tf.constant(npr.rand(50, 4, 20).astype('float32'))
cell = tf.nn.rnn_cell.LSTMCell(num_units=100, 
                               input_size=20, 
                               initializer=tf.constant_initializer(0.05),
                               use_peepholes=True,
                               cell_clip=None)
outputs, _ = tf.nn.dynamic_rnn(cell=cell, inputs=inputs, sequence_length=num_stepss, dtype=tf.float32, time_major=True)
loss = tf.reduce_sum(outputs)
trainer = tf.train.GradientDescentOptimizer(0.01).minimize(loss)
```

This fails with the following error: 

`ValueError: Shapes () and (120, 400) must have the same rank`

A slightly fancier version of the above that encloses it within scope `'my_scope'` using `tf.variable_scope` gives the following error: 

`ValueError: Expected op/tensor name to start with gradients, got: my_scope/gradients/my_scope/Sum_grad/Tile:0`

I've run into other issues as well, but I don't yet know if they're related to the above or they're distinct bugs.

**Comment by ebrevdo** [comment]
The shape bug should be fixed at HEAD

**Comment by alquraishi** [comment]
Yes you are right after compiling with the latest version the shape has gone away. The scope problem is still there however.

**Comment by nryant** [comment]
Regarding scope issues, it appears that the ``TensorArray`` instances created in ``dynamic_rnn`` always have the same value for ``tensor_array_name``, which causes issues if you try to use ``dynamic_rnn`` multiple times in the same graph; for instance, when building a bidirectional RNN.

**Comment by ebrevdo** [comment]
We have another commit in the works to fix the second problem.

**Comment by underspirit** [comment]
@alquraishi I'd like to ask a question if I may. In your example, the batch size is 4(static), and num_stepss also is a static vector with length 4. But if I have another batch with different num_stepss [14, 30, 24, 17] (Which I mean every batch has different num_stepss...), how could I use the dynamic_rnn model?

**Comment by girving** [comment]
@ebrevdo: Assigning to you if something is in the works.

**Comment by ebrevdo** [comment]
alquraishi: can you provide a list of things still broken at head of master branch?

**Comment by alquraishi** [comment]
@ebrevdo sorry I didn't see that this was still open. I'm using dynamic_rnn with no problems. I will close.
