### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Dringite** [tensorflow/tensorflow#1334]
Ubuntu 14, master branch pull minutes ago.

ERROR: /home/ggg/000/tensorflow/tensorflow/core/kernels/BUILD:712:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:depthwise_conv_op':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/depthwise_conv_op.cc':
  '/home/ggg/000/tensorflow/tensorflow/core/common_runtime/device.h'
  '/home/ggg/000/tensorflow/tensorflow/core/graph/graph.h'
  '/home/ggg/000/tensorflow/tensorflow/core/graph/edgeset.h'
  '/home/ggg/000/tensorflow/tensorflow/core/graph/types.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build

**Comment by kbrems** [comment]
I have the same issue as well as a similar one, depending on which parallel bazel task completes first:

ERROR: /home/karenbre/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:158:1: undeclared inclusion(s) in rule '//tensorflow/core/distributed_runtime/rpc:grpc_remote_master':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc':
  'bazel-out/local_linux-opt/genfiles/tensorflow/core/protobuf/master_service.grpc.pb.h'.
Target //tensorflow/python:zero_out_op_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.716s, Critical Path: 3.43s

**Comment by vrv** [comment]
I'm fixing the first issue, will try to figure out why the second one is happening.

**Comment by keveman** [comment]
You seem to be building the target `//tensorflow/python:zero_out_op_test`. `bazel query tensorflow/python/...` doesn't show that it exists. Is that something that you added? What does your rule look like?

**Comment by kbrems** [comment]
I am trying to follow the tutorial for building a user operator since it was reported that those issues are now fixed.

**Comment by bernardopires** [comment]
I can reproduce the issue when compiling the pip package `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`. Sometimes it even succeeds but then `bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg` fails with `error: can't copy 'tensorflow/python/training/gen_training_ops.py': doesn't exist or not a regular file`

**Comment by Mohamed5amy** [comment]
+1
Same error after running  `bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer`

**Comment by vrv** [comment]
The above commit probably fixes some issues, and maybe some others, but leaving it open until we fix any other issues that have cropped up recently

**Comment by michaelnhw** [comment]
Have issue compiling on Mac OS X 10.10, pulled from master branch couple minutes ago.

ERROR: /Users/michael/tensorflow/tensorflow/contrib/linear_optimizer/BUILD:14:1: Linking of rule '//tensorflow/contrib/linear_optimizer:python/ops/_sdca_ops.so' failed: osx_gcc_wrapper.sh failed: error executing command external/bazel_tools/tools/cpp/osx_gcc_wrapper.sh -shared -o bazel-out/local_darwin-opt/bin/tensorflow/contrib/linear_optimizer/python/ops/_sdca_ops.so -Wl,-all_load ... (remaining 23 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
clang: warning: argument unused during compilation: '-pthread'
ld: warning: option -noall_load is obsolete and being ignored
ld: unknown option: -Bsymbolic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by Dringite** [comment]
my issue is fixed.

**Comment by leconteur** [comment]
I have the same issue as michaelnhw has.

**Comment by vrv** [comment]
I pushed c3c40b7a8950bba876b92456824e5b6a9505c0a7 to fix the first problem, but now there's one more linker problem.  I just fixed that internally and will be pushing it out momentarily.

**Comment by vrv** [comment]
Okay, I think the builds are going to be green (or at least, not broken).

**Comment by kbrems** [comment]
pip package still does not build:

ERROR: /home/karenbre/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:158:1: undeclared inclusion(s) in rule '//tensorflow/core/distributed_runtime/rpc:grpc_remote_master':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc':
  'bazel-out/local_linux-opt/genfiles/tensorflow/core/protobuf/master_service.grpc.pb.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by vrv** [comment]
@keveman, @mrry, any ideas?

**Comment by tomMoral** [comment]
Trying to build from source raise the same error as @kbrems .

````
ERROR: /home/tom/Work/prog/github/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:131:1: undeclared inclusion(s) in rule '//tensorflow/core/distributed_runtime/rpc:grpc_worker_service':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/distributed_runtime/rpc/grpc_worker_service.cc':
'bazel-out/local_linux-py3-opt/genfiles/tensorflow/core/protobuf/worker_service.grpc.pb.h'.
Target //tensorflow/core/distributed_runtime/rpc:grpc_worker_service failed to build
```

And similar failure building `//tensorflow/core/distributed_runtime/rpc:grpc_master_service`.

**Comment by keveman** [comment]
I don't see these errors when building `//tensorflow/tools/pip_package:build_pip_package` on a Ubuntu 14.04 machine. What Bazel version are you using? What OS version?

**Comment by tomMoral** [comment]
I am on an archlinux distribution and running bazel 0.2.0-1.

**Comment by kbrems** [comment]
I pulled master today and I still have the same issue building pip package. I am on Ubuntu 14.04. 
I have not interrupted bazel. 
Note, a similar issue referred to a stale config file build_config.bzl, but that file is modified by ./configure, so it always appears to have been locally modified:

diff --git a/tensorflow/core/platform/default/build_config.bzl b/tensorflow/core/platform/default/build_config.bzl
index 633441f..7e6549b 100644
--- a/tensorflow/core/platform/default/build_config.bzl
+++ b/tensorflow/core/platform/default/build_config.bzl
@@ -4,9 +4,9 @@ load("//google/protobuf:protobuf.bzl", "cc_proto_library")
 load("//google/protobuf:protobuf.bzl", "py_proto_library")
 
 # configure may change the following lines to '.X.Y' or similar
-CUDA_VERSION = ""
+CUDA_VERSION = ".7.5"
 
-CUDNN_VERSION = ""
+CUDNN_VERSION = ".4"
 
 # Appends a suffix to a list of deps.
 def tf_deps(deps, suffix):
****

Build error:
ERROR: /home/karenbre/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:158:1: undeclared inclusion(s) in rule '//tensorflow/core/distributed_runtime/rpc:grpc_remote_master':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/distributed_runtime/rpc/grpc_remote_master.cc':
  'bazel-out/local_linux-opt/genfiles/tensorflow/core/protobuf/master_service.grpc.pb.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 344.224s, Critical Path: 149.03s

**Comment by kbrems** [comment]
OK, I figured out the issue. Something changed in protobuf. That does not come with a git pull.
I ran 
git submodule update --init
then bazel clean --expunge

Then I can build.

**Comment by aladwig06** [comment]
This fixed the issue for me as well.  Thanks!

**Comment by lerynth** [comment]
I followed @kbrems. But still:
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Sab Agu 27 09:35:48 WIB 2016 : === Using tmpdir: /tmp/tmp.Jw7t8AZ5um
/tmp/tmp.Jw7t8AZ5um /srv/Python-DL/tensorflow
Sab Agu 27 09:35:48 WIB 2016 : === Building wheel
error: can't copy 'tensorflow/contrib/linear_optimizer/ops/gen_sdca_ops.py': doesn't exist or not a regular file

**Comment by mattisback** [comment]
I tried `git submodule update --init` but I still get the error:
`error: can't copy 'external/protobuf/python/google/protobuf/wrappers_pb2.py': doesn't exist or not a regular file`

**Comment by nishalpereira** [comment]
@bernardopires 

i have the same error
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg fails with error: can't copy 'tensorflow/python/training/gen_training_ops.py': doesn't exist or not a regular file.

How do i fix it?

**Comment by nishalpereira** [comment]
@bernardopires 

i have the same error
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg fails with error: can't copy 'tensorflow/python/training/gen_training_ops.py': doesn't exist or not a regular file.

How do i fix it?

**Comment by Jovonni** [comment]
above  solution by @mattisback fixes a problem I had as well, but keep getting:

execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/contrib/image/_objs/python/ops/_distort_i
mage_ops_gpu/tensorflow/contrib/image/kernels/adjust_hsv_in_yiq_op_gpu.cu.pic.d

Which is referenced here, but posted because of possible relationship between the two:
https://github.com/tensorflow/tensorflow/issues/15565

**Comment by Jovonni** [comment]
Any work around for this right now, or do we have to wait until you release this update? If I do it is broken until then.... :(
