### ISSUE TITLE
W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 

### ISSUE THREAD

**Issue by Narthyard** [tensorflow/tensorflow#13632]
The source code I try to compile has been changed, and now it requires tf-nightly build(1.4 version). For that reason, I created new conda environment which includes 1.4 version of tensorflow.

However, I still use the same set-up except the version of tensorflow. I've read they anticipate releasing 1.4 version of tensorflow wih cuDNN 7 instead of cuDNN 6. Is this the reason that I get these warnings? Should I upgrade the cuDNN version from 6 to 7. 

I'm also getting "RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6" although I loaded the 3.6 version of tf-nightly build.

This is what I get:
```
2017-10-11 15:42:05.897046: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
train 0 4000 0.764138 1.0965 0.604099
2017-10-11 15:42:40.117190: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2017-10-11 15:42:40.118152: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2017-10-11 15:42:40.118270: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
train 0 4100 0.778095 1.09562 0.603462
2017-10-11 15:43:14.819378: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2017-10-11 15:43:14.820271: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
2017-10-11 15:43:14.820375: W tensorflow/stream_executor/cuda/cuda_dnn.cc:2223] 
train 0 4200 1.55563 1.09606 0.603783
```

### System information
- **OS Platform and Distribution** : Linux Ubuntu 16.04 LTS
- **TensorFlow installed from (source or binary)**: tf_nightly_gpu-1.4.0.dev20171010-cp36-cp36m-manylinux1_x86_64.whl
- **TensorFlow version** : 1.4.0-dev20171010
- **Python version**: 3.6.1 Anaconda 64bit
- **CUDA/cuDNN version**:  cuda-ga2_8.0_amd64 / cudnn-8.0-linux-x64-v6.0
- **GPU model and memory**: Nvidia GeForce GT 710  1GB memory
- **Exact command to reproduce**: python train_xxx --train_batch_size 16 --val_batch_size 16

**Comment by allenlavoie** [comment]
The fast_tensor_util warning is because we only build for 3.5, then copy the pip package to a 3.6 name assuming they will be compatible (I think). This was true, but we're using a bit of Cython-compiled code now. Probably Cython is a bit overcautious with the version checking here, but we should get rid of the warning anyway.

@av8ramit would it be difficult to start building nightlies (and releases?) separately for Python 3.5 and 3.6? I could look into ways to suppress the warning, but it's probably there for a reason.

**Comment by av8ramit** [comment]
Yes, we unfortunately build for Python 3.5 and then copy to 3.6 for Linux. I'll look into separate builds.

**Comment by allenlavoie** [comment]
And to be clear I have no idea what's up with the CUDA warnings.

**Comment by tatatodd** [comment]
@yzhwang It looks like you added these warnings, with the code looking something like this:

```
      auto allocated = scratch_allocator->AllocateBytes(stream, size_in_bytes);
      if (allocated.ok()) {
        scratch = allocated.ValueOrDie();
      } else {
        LOG(WARNING) << allocated.status().error_message();
      }
```

The code looks reasonable.  Do you have any idea why we're getting these nonsense status messages?

**Comment by yzhwang** [comment]
This means that the previous cudnn function call: https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/stream_executor/cuda/cuda_dnn.cc#L2195 returns a size_in_bytes that caused AllocateBytes() to fail. It's interesting that the error_message() is empty though.
The solution for this is: since we are not officially supporting cudnn7 (tests and integration in progress), I recommend you to switch back to cudnn6 for now.

**Comment by Narthyard** [comment]
The problem has been solved when I switched back to cudnn6. It was mainly about version issue as @yzhwang stated. I really appreciated it.

Thanks for dropping a line.

**Comment by yzhwang** [comment]
@Narthyard Thanks for the update. Note that TensorFlow now officially support cudnn7+CUDA9. Let me know if you think this bug still exists when switching to cudnn 7.

**Comment by ravikt** [comment]
@yzhwang The bug is still there. I am using Tensorflow 1.5 with CUDA 9.0 with cudnn 7

**Comment by joeyearsley** [comment]
Still there with 1.10.1 with CUDA 9.2 and cudnn 7.2

**Comment by YuhuaBillChen** [comment]
Still there with 1.14 with XLA on.
