### ISSUE TITLE
Tensorflow Website : Missing Mathjax results in broken equations

### ISSUE THREAD

**Issue by viksit** [tensorflow/tensorflow#1377]
The website tries to load,

`
https://www.tensorflow.org/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.1
`

and fails. Someone needs to fix the path to get the right version of mathjax, and have all the LaTeX symbols show up.

Thanks.

**Comment by goelakash** [comment]
This issue still affects the website for me (both on Chrome 49 and Firefox 44)

**Comment by MidnightLightning** [comment]
The "MNIST For ML Beginners" has most equations working, but there's several in the Training section that are showing "Math Processing Error":

https://www.tensorflow.org/versions/r0.7/tutorials/mnist/beginners/index.html#training

```
Error: Cannot read property 'fontInherit' of undefined
Debugging tips: use 'unpacked/MathJax.js', inspect 'MathJax.Hub.lastError' in the browser console
```

Using Mathjax's right-click menu to set the Renderer to SVG works, so it's just the HTML+CSS renderer having issues.

**Comment by jakequist** [comment]
Looks like it's still broken, verified from home and work IPs: 

```bash
$ curl "https://www.tensorflow.org/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.1"
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>404 Not Found</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Not Found</h1>
<h2>The requested URL <code>/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.1</code> was not found on this server.</h2>
<h2></h2>
</body></html>
```

![image](https://cloud.githubusercontent.com/assets/207427/13757770/5421c538-e9e3-11e5-827e-f03cbdf1380e.png)

**Comment by danmane** [comment]
This is fixed now.

**Comment by hitvoice** [comment]
The same problem still appears in Chrome (latest version, Version 59.0.3071.115) on Mac OS. In Firefox and Safari on Mac OS, it works fine.
Example affected page: https://www.tensorflow.org/tutorials/word2vec

<img width="725" alt="wx20170705-102404 2x" src="https://user-images.githubusercontent.com/13765633/27846840-8a9e1ccc-616c-11e7-8d2f-f0d77240bde7.png">
