### ISSUE TITLE
Convolutional layers cannot be used multiple times

### ISSUE THREAD

**Issue by vishvananda** [tensorflow/tensorflow#13822]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: source (branch 1.4)
- **TensorFlow version (use command below)**: 1.4.0-dev
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: nVidia 1080Ti 11G
- **Exact command to reproduce**: run the script below

### Describe the problem
Keras convolutional layers cannot be used multiple times without creating a name conflict. This is especially bad when trying to copy layers from one model to another (See the second example below). This was working a few weeks ago. Here is a simple test case that used to work:

```python
#!/usr/bin/env python

import tensorflow as tf

from tensorflow.contrib.keras.api.keras.layers import Conv2D
from tensorflow.contrib.keras.api.keras.layers import Input

a = Input(shape=(None, 32, 3))
c = Conv2D(32, (3, 3))
c(a)
c(a)
```

I added some print statement to different versions of the code. It looks like the convolutional ops are created with the following names in the old code:

1. conv2d/convolution/
2. conv2d/convolution_1/

In the new code they are:

1. conv2d/convolution/
2. conv2d/convolution/

It looks like the name scope code was changed recently. I specifically notice that some of the scope handling was moved to __init__ where it used to happen when the function was called. 

This is a slightly more complex version of the code that shows that copying convolutional layers doesn't work:

```python
#!/usr/bin/env python

import tensorflow as tf

from tensorflow.contrib.keras.api.keras.layers import Conv2D
from tensorflow.contrib.keras.api.keras.layers import Input
from tensorflow.contrib.keras.api.keras.models import Model

a = Input(shape=(None, 32, 3))
b = a
b = Conv2D(32, (3, 3))(b)
mod1 = Model(inputs=a, outputs=b)
a = Input(shape=(None, 32, 3))
b = a
for layer in mod1.layers[1:]:
    b = layer(b)
mod2 = Model(inputs=a, outputs=b)
```
This is an example of the traceback:
```
Traceback (most recent call last):
  File "/root/vish/test.py", line 16, in <module>
    b = layer(b)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 252, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 577, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/layers/convolutional.py", line 172, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 841, in __call__
    return self.conv_op(inp, filter)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 503, in __call__
    return self.call(inp, filter)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 191, in __call__
    name=self.name)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
    data_format=data_format, name=name)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2959, in create_op
    self._add_op(ret)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2599, in _add_op
    "is already used" % op.name)
ValueError: cannot add op with name conv2d/convolution as that name is already used
```

**Comment by antifriz** [comment]
Also to note that when using keras-2.0.8 the same code creates convolutional ops with following names:

1. conv2d_1/convolution
2. conv2d_1_1/convolution

Moreover, when nesting scopes, the differences became even more apparent. A slightly modified code that calls the other copy in some scope behaves much differently in keras vs. tf.keras (1.3.0).

```
a = Input(shape=(None, 32, 3))
c = Conv2D(32, (3, 3))
c(a)

with tf.name_scope('my_scope'):
    c(a)
```

keras names:

1. conv2d_1/convolution
2. my_scope/conv2d_1/convolution

tf.keras names:

1. conv2d/convolution
2. conv2d/convolution_1

Although the functionality is the same, keras way of scoping does not interfere with the name scope concept and therefore it behaves as expected.

**Comment by antifriz** [comment]
New scoping implementation (the cause of the opened issue) also causes scopes not scoping their implementations correctly.

A slightly modified code with repeating layers results in bad scoping.
```
import tensorflow as tf

from tensorflow.contrib.keras.api.keras.layers import Conv2D
from tensorflow.contrib.keras.api.keras.layers import Input

a = Input(shape=(None, 32, 3))
a = Conv2D(32, (3, 3))(a)
a = Conv2D(32, (3, 3))(a)
```

Convolutions are named:

1. conv2d_1/convolution
2. conv2d_2/convolution

And their weights are named:

1. conv2d/kernel
2. conv2d_1/kernel

Which results in different layers being placed partially in the same scope and partially in different scopes.

**Comment by andydavis1** [comment]
@martinwicke Can you comment on this one? Thanks...

**Comment by martinwicke** [comment]
I'm sorry -- @antifriz what you describe looks like it's working as intended. What would be the desired behavior here? 

The scoping differences should be immaterial, you should be able to save and load *Keras* models between the different backends, etc.

Important is that reusing a layer reuses the variables, and that using a new layer will *not* share any variables.

@fchollet FYI, if you see an issue here that I missed.

**Comment by antifriz** [comment]
@martinwicke, @fchollet 

I included visual comparison of keras and tf.keras behaviors to clarify what I think is wrong with tf.keras scoping.

So for two layers tf.keras produces three scopes where second layer is splitted in two scopes:
```
import tensorflow as tf

from tensorflow.contrib.keras.api.keras.layers import Conv2D
from tensorflow.contrib.keras.api.keras.layers import Input

a = Input(shape=(None, 32, 3))
a = Conv2D(32, (3, 3))(a)
a = Conv2D(32, (3, 3))(a)
```

<img width="717" alt="screen shot 2017-10-21 at 8 21 56 am" src="https://user-images.githubusercontent.com/6382271/31848812-5089a624-b639-11e7-9238-855ec6418792.png">

With keras scoping is as expected:
```
from keras.layers import Conv2D
from keras.layers import Input

a = Input(shape=(None, 32, 3))
a = Conv2D(32, (3, 3))(a)
a = Conv2D(32, (3, 3))(a)
```
<img width="422" alt="screen shot 2017-10-21 at 8 23 34 am" src="https://user-images.githubusercontent.com/6382271/31848813-50a64e96-b639-11e7-8489-d5beb1c309d4.png">

In tf.keras this happens only if you do not explicitly specify the name of the layer. If it is specified, result is as expected (like keras one).
```
import tensorflow as tf

from tensorflow.contrib.keras.api.keras.layers import Conv2D
from tensorflow.contrib.keras.api.keras.layers import Input

a = Input(shape=(None, 32, 3))
a = Conv2D(32, (3, 3), name='conv_first')(a)
a = Conv2D(32, (3, 3), name='conv_second')(a)
```
<img width="480" alt="screen shot 2017-10-21 at 8 35 10 am" src="https://user-images.githubusercontent.com/6382271/31848926-dffd175e-b63a-11e7-9f0a-b9cd7d7837cf.png">

**Comment by vishvananda** [comment]
regardless of the weird scoping, the original issue still remains in that it is not possible to use the same layer twice due to the name conflict.

**Comment by fchollet** [comment]
Can you check what happens with layers from `tf.layers`?

**Comment by facaiy** [comment]
Relate to #13429?

**Comment by vishvananda** [comment]
@fchollet I'm less familiar with using straight tensorflow layers, but the following gives me roughly the same  error:
```
import tensorflow as tf                                                                                                                                                              
                                                                                                                                                                                     
from tensorflow.python.layers.convolutional import Conv2D                                                                                                                            
a = tf.placeholder(tf.float32, (None, 32, 32, 3))                                                                                                                                    
c = Conv2D(32, (3, 3))                                                                                                                                                               
c(a)                                                                                                                                                                                 
c(a)  
```

Here is the traceback:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    c(a)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/convolutional.py", line 171, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 835, in __call__
    return self.conv_op(inp, filter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 499, in __call__
    return self.call(inp, filter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 187, in __call__
    name=self.name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 631, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2959, in create_op
    self._add_op(ret)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2599, in _add_op
    "is already used" % op.name)
ValueError: cannot add op with name conv2d/convolution as that name is already used
```

**Comment by fchollet** [comment]
@vishvananda what TF version is that? If it is the GitHub one, then I believe this is a bug that was introduce in relation to eager mode and has been fixed recently. It should not be related to the issue from this thread. Try with a different layer (e.g. `Dense`).

> Relate to #13429?

Yes, I would think so, but would like confirmation.

**Comment by vishvananda** [comment]
This is the r1.4 branch from last week. I'm building again from current r1.4. Will post the results shortly

**Comment by vishvananda** [comment]
The current r1.4 branch still fails. I'm now trying against current master, although it will take a while to do the build from scratch

**Comment by vishvananda** [comment]
Current master also fails. Both of the following Dense scenarios work fine, so it looks like the error is specific to convolutional layers
```python
import tensorflow as tf

from tensorflow.python.layers.core import Dense
a = tf.placeholder(tf.float32, (None, 32, 32, 3))
c = Dense(32)
x = c(a)
y = c(a)
```
```python
import tensorflow as tf

from tensorflow.contrib.keras.api.keras.layers import Dense
from tensorflow.contrib.keras.api.keras.layers import Input

a = Input(shape=(None, 32, 3))
c = Dense(32)
x = c(a)
y = c(a)
```

**Comment by vishvananda** [comment]
@fchollet I assume you are referring to the fixes contained in this pr: https://github.com/tensorflow/tensorflow/pull/13934

I have merged that branch into master and it does fix the issues here

**Comment by vishvananda** [comment]
Ok this was fixed in master by https://github.com/tensorflow/tensorflow/pull/13976. r1.4 still needs to be updated though

**Comment by martinwicke** [comment]
@case540 is on it.

**Comment by vishvananda** [comment]
I can confirm that this is fixed in 1.4 as of https://github.com/tensorflow/tensorflow/pull/14044

**Comment by pranto00250** [comment]
Here is my code : 
```python
class final_model:
    # CNN encoder
    encoder, preprocess_for_model = get_cnn_encoder()
    #saver.restore(s, os.path.abspath("weights"))  # keras applications corrupt our graph, so we restore trained weights
    
    # containers for current lstm state
    lstm_c = tf.Variable(tf.zeros([1, LSTM_UNITS]), name="cell")
    lstm_h = tf.Variable(tf.zeros([1, LSTM_UNITS]), name="hidden")

    # input images
    input_images = tf.placeholder('float32', [1, IMG_SIZE, IMG_SIZE, 3], name='images')

    # get image embeddings
    img_embeds = encoder(input_images)

    # initialize lstm state conditioned on image
    init_c = init_h = decoder.img_embed_bottleneck_to_h0(decoder.img_embed_to_bottleneck(img_embeds))
    init_lstm = tf.assign(lstm_c, init_c), tf.assign(lstm_h, init_h)
    
    # current word index
    current_word = tf.placeholder('int32', [1], name='current_input')

    # embedding for current word
    word_embed = decoder.word_embed(current_word)

    # apply lstm cell, get new lstm states
    new_c, new_h = decoder.lstm(word_embed, tf.nn.rnn_cell.LSTMStateTuple(lstm_c, lstm_h))[1]

    # compute logits for next token
    new_logits = decoder.token_logits(decoder.token_logits_bottleneck(new_h))
    # compute probabilities for next token
    new_probs = tf.nn.softmax(new_logits)

    # `one_step` outputs probabilities of next token and updates lstm hidden state
    one_step = new_probs, tf.assign(lstm_c, new_c), tf.assign(lstm_h, new_h)
```

And I am getting following error : 

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-42-73f88badc13d> in <module>()
----> 1 class final_model:
      2     # CNN encoder
      3     encoder, preprocess_for_model = get_cnn_encoder()
      4     #saver.restore(s, os.path.abspath("weights"))  # keras applications corrupt our graph, so we restore trained weights
      5 

<ipython-input-42-73f88badc13d> in final_model()
     12 
     13     # get image embeddings
---> 14     img_embeds = encoder(input_images)
     15 
     16     # initialize lstm state conditioned on image

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\topology.py in __call__(self, inputs, **kwargs)
    250     """
    251     # Actually call the layer (optionally building it).
--> 252     output = super(Layer, self).__call__(inputs, **kwargs)
    253 
    254     # Update learning phase info.

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\layers\base.py in __call__(self, inputs, *args, **kwargs)
    573         if in_graph_mode:
    574           self._assert_input_compatibility(inputs)
--> 575         outputs = self.call(inputs, *args, **kwargs)
    576 
    577         if outputs is None:

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\layers\base.py in call(self, inputs, mask)
   1918     else:
   1919       # Cache miss: actually apply the network graph to the new inputs.
-> 1920       output_tensors, _, _ = self._run_internal_graph(inputs, masks)
   1921       return output_tensors
   1922 

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\layers\base.py in _run_internal_graph(self, inputs, masks)
   2082                 if 'mask' not in kwargs:
   2083                   kwargs['mask'] = computed_mask
-> 2084               output_tensors = _to_list(layer.call(computed_tensor, **kwargs))
   2085               if hasattr(layer, 'compute_mask'):
   2086                 output_masks = _to_list(

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\layers\convolutional.py in call(self, inputs)
    169     # TODO(agarwal): do we need this name_scope ?
    170     with ops.name_scope(None, 'convolution', [inputs, self.kernel]):
--> 171       outputs = self._convolution_op(inputs, self.kernel)
    172 
    173     if self.use_bias:

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py in __call__(self, inp, filter)
    833 
    834   def __call__(self, inp, filter):  # pylint: disable=redefined-builtin
--> 835     return self.conv_op(inp, filter)
    836 
    837 

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py in __call__(self, inp, filter)
    497 
    498   def __call__(self, inp, filter):  # pylint: disable=redefined-builtin
--> 499     return self.call(inp, filter)
    500 
    501 

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py in __call__(self, inp, filter)
    185         padding=self.padding,
    186         data_format=self.data_format,
--> 187         name=self.name)
    188 
    189 

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py in conv2d(input, filter, strides, padding, use_cudnn_on_gpu, data_format, name)
    628         "Conv2D", input=input, filter=filter, strides=strides,
    629         padding=padding, use_cudnn_on_gpu=use_cudnn_on_gpu,
--> 630         data_format=data_format, name=name)
    631     _result = _op.outputs[:]
    632     _inputs_flat = _op.inputs

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    785         op = g.create_op(op_type_name, inputs, output_types, name=scope,
    786                          input_types=input_types, attrs=attr_protos,
--> 787                          op_def=op_def)
    788       return output_structure, op_def.is_stateful, op
    789 

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py in create_op(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_shapes, compute_device)
   2957     if compute_shapes:
   2958       set_shapes_for_outputs(ret)
-> 2959     self._add_op(ret)
   2960     self._record_op_seen_by_control_dependencies(ret)
   2961 

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py in _add_op(self, op)
   2597       if op.name in self._nodes_by_name:
   2598         raise ValueError("cannot add op with name %s as that name "
-> 2599                          "is already used" % op.name)
   2600       self._nodes_by_id[op._id] = op
   2601       self._nodes_by_name[op.name] = op

ValueError: cannot add op with name conv2d_471/convolution as that name is already used
```

How can solve this issue ? Please help . THANKS.

**Comment by nevakrien** [comment]
still a problem?
