### ISSUE TITLE
unable to use nn.moments when the dimension of the axis is None

### ISSUE THREAD

**Issue by rinuboney** [tensorflow/tensorflow#139]
calling ```nn.moments``` with an axis of dimension ```None``` produces this error:

```
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn.py", line 536, in moments
    divisor *= x.get_shape()[d].value
TypeError: unsupported operand type(s) for *=: 'float' and 'NoneType'
```

is it possible for the ```nn.moments``` implementation to use the inferred dimension in it's calculation?

**Comment by mrry** [comment]
It looks like the problem arises because (i) `tf.nn.moments` relies on knowing the fully-defined shape for its argument, and (ii) the `x` argument that you passed to `tf.nn.moments` has one or more undefined dimensions.

This can arise when shape inference doesn't have enough information to infer all of the dimensions in your tensor. In this case, the best thing to do is the following:

```python
x = ...
axes = [...]
x.set_shape([size_in_dim_0, ...])  # Each `size_in_dim_i` must be an integer.
x_moments = tf.nn.moments(x, axes)
```

If the size in any of those dimensions is dynamic, the current implementation of `tf.nn.moments()` will not work, but it is possible to add a custom version that does the trick:

```python
def moments(x, axes, name=None):
  """Version of tf.nn.moments that supports variable-sized tensors.

  N.B. The rank must be known statically for this version to work.
  """
  with tf.op_scope([x], name, "moments"):
    x = tf.convert_to_tensor(x, name="x")
    divisor = tf.constant(1.0, dtype=x.dtype)
    x_dynamic_shape = tf.shape(x)
    for d in xrange(x.get_shape().ndims):
      if d in axes:
        divisor = divisor * x_dynamic_shape[d]
    divisor = tf.inv(divisor)
    mean = math_ops.mul(math_ops.reduce_sum(x, axes), divisor, name="mean")
    var = math_ops.mul(math_ops.reduce_sum(math_ops.square(x - mean), axes),
                       divisor, name="variance")
    return mean, var
```

A version that works with dynamic rank tensors would also be possible, but it would be quite a bit more complicated.

It would also be possible to replace the `divisor` computation with a call to `tf.mean()`, but as the comment in [the implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn.py#L539) mentions, there are sum performance issues when using `tf.mean()` on GPU at present.

**Comment by rinuboney** [comment]
I'm using this custom function right now:
```
def moments(x, axes, name=None):
  with tf.op_scope([x, axes], name, "moments"):
    x = tf.convert_to_tensor(x, name="x")
    divisor = tf.constant(1.0)
    for d in xrange(len(x.get_shape())):
      if d in axes:
        divisor *= tf.to_float(tf.shape(x)[d])
    divisor = tf.inv(divisor, name="divisor")
    axes = tf.constant(axes, name="axes")
    mean = tf.mul(tf.reduce_sum(x, axes), divisor, name="mean")
    var = tf.mul(tf.reduce_sum(tf.square(x - mean), axes),
                       divisor, name="variance")
    return mean, var
```
I guess it is not trivial to access the function tf.shape within the ```nn.moments``` implementation

**Comment by mrry** [comment]
Thanks for sharing your workaround! We're working on a fix that should address this in the core library.

**Comment by vrv** [comment]
Should be fixed by @mrry in 1d76583411038767f673a0c96174c80eaf9ff42f, which I just pushed to HEAD.  Will be in the next binary release.

**Comment by MOCR** [comment]
Thanks for this version of moments as it's still an issue of tf.nn.moments!
