### ISSUE TITLE
Boringssl support for s390x

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#14039]
Creating this issue with reference : https://github.com/tensorflow/tensorflow/pull/11170

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: master
- **Bazel version (if compiling from source)**: 0.6.1
- **CUDA/cuDNN version**: Not used
- **Exact command to reproduce**: bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

**Comment by Nayana-ibm** [comment]
Hello @gunan Continuing discussion about disabling the oauth support /GCP on big endian from issue https://github.com/tensorflow/tensorflow/pull/11170#issuecomment-320071548

I could see that the PR changes made for s390x are now reverted in Tensorflow master.
So as suggested, disabling GCP support on a big-endian systems,  I followed following steps:
~/tensorflow# ./configure

> You have bazel 0.6.1- (@non-git) installed.
> Please specify the location of python. [Default is /usr/bin/python]:
> Found possible Python library paths:
>   /usr/local/lib/python2.7/dist-packages
>   /usr/lib/python2.7/dist-packages
> Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]
> 
> Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]:
> jemalloc as malloc support will be enabled for TensorFlow.
> 
> Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: n
> No Google Cloud Platform support will be enabled for TensorFlow.

~/tensorflow# bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

Even after disabling GCP support, build fails with an error:
```
ERROR: /root/.cache/bazel/_bazel_root/30b0ed2738c25ecefa4b108f71649fc1/external/boringssl/BUILD:115:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1).
In file included from external/boringssl/src/include/openssl/bio.h:60:0,
                 from external/boringssl/src/crypto/bio/printf.c:57:
external/boringssl/src/include/openssl/base.h:114:2: error: #error "Unknown target CPU"
 #error "Unknown target CPU"
  ^

```
Need more changes here?

On test cases part, I have added `tags = ["no_big_endian"] ` in `tensorflow/core/platform/cloud/BUILD `file. 
Yet to verify this changes.

**Comment by gunan** [comment]
Looks like S3 support also depends on curl, which depends on boringssl.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/BUILD#L47
Could you also try turning off s3 support?

**Comment by gunan** [comment]
@Nayana-ibm have you tried also turning off s3 support?

**Comment by Nayana-ibm** [comment]
hi @gunan I have tried turning off s3 support through configure however still I'm facing an issue with boringssl code.

```
tensorflow# ./configure
You have bazel 0.6.1- (@non-git) installed.
Please specify the location of python. [Default is /usr/bin/python]:

Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.5/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]:
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: N
No Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: N
No Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]: N
No Amazon S3 File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]:
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]:
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]:
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL support? [y/N]:
No OpenCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]:
No CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with MPI support? [y/N]:
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:


Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.
Configuration finished
```
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

```

ERROR: /root/.cache/bazel/_bazel_root/79d3d3c667100526634e40f5a15c8098/external/boringssl/BUILD:115:1: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1).
In file included from external/boringssl/src/include/openssl/asn1.h:61:0,
                 from external/boringssl/src/crypto/asn1/f_int.c:57:
external/boringssl/src/include/openssl/base.h:114:2: error: #error "Unknown target CPU"
 #error "Unknown target CPU"
  ^
```

I'm looking  into BUILD files if there is any code change requires for s390x.

**Comment by gunan** [comment]
@case540 Do we need to disable s3 and gcp support through config options?

**Comment by Nayana-ibm** [comment]
@case540 Could you please let me if disabling support by config options is sufficient? Do I need to investigate further on this?

**Comment by case540** [comment]
You can disable s3 and gcp support by not having --config=s3 or --config=gcp in your Bazel build command (answering No to s3 and gcp support question when running configure.py will do this (they default to the Yes choice)).

Looks like you already did this though.

**Comment by gunan** [comment]
Looks like now we need boringssl for grpc.
@martinwicke WDYT?

**Comment by gunan** [comment]
Also cc @vjpai 
We would like to build TF for s390x. But boring SSL strictly has no ppc64 support. Looks like GRPC now depends on boringssl. Below is my bazel query output:
```
@grpc//:grpc++_unsecure
@grpc//:grpc++_base_unsecure
@grpc//:grpc_unsecure
@grpc//:grpc_common
@grpc//:census
//external:libssl
@boringssl//:ssl
@boringssl//:crypto
```
 How would you recommend for us to proceed?

**Comment by martinwicke** [comment]
This looks like a bug in the grpc_unsecure rule. It seems like it shouldn't depend on any ssl code. @mrry do you know who to best tell about this?

**Comment by mrry** [comment]
I think @vjpai would probably have it covered - he recently switched us over to using gRPC's own `BUILD` file (instead of our old fork).

**Comment by vjpai** [comment]
Thanks for the heads-up; I'll look this over. It is indeed a problem in the rule for grpc_unsecure if it actually depends on boringssl.

**Comment by vjpai** [comment]
Ok, I see the issue. This dependence is being pulled up through census. Not sure why census wants boringssl but I'll investigate.

**Comment by vjpai** [comment]
I think I have this under control with grpc/grpc#13525 .

**Comment by martinwicke** [comment]
Awesome, thanks! We need to update our dependency again once this is merged.

**Comment by Nayana-ibm** [comment]
@gunan   As grpc dependency version is updated through #14981,  I have tried building tensorflow master for s390x again.  I have disabled `Google Cloud Platform` and  `Amazon S3 File System` support through `./configure` options.  (answering No to s3 and gcp support question when running `configure.py` )
Now, build is successful (No error related to boringssl) however test execution failed with 
```
ERROR: external/boringssl/BUILD:115:1: Couldn't build file external/boringssl/_objs/crypto/external/boringssl/src/crypto/bn_extra/bn_asn1.pic.o: C++ compilation of rule '@boringssl//:crypto' failed (Exit 1).
In file included from external/boringssl/src/include/openssl/bn.h:126:0,
                 from external/boringssl/src/crypto/bn_extra/bn_asn1.c:15:
external/boringssl/src/include/openssl/base.h:114:2: error: #error "Unknown target CPU"
 #error "Unknown target CPU"
  ^
In file included from external/boringssl/src/crypto/bn_extra/bn_asn1.c:15:0:
external/boringssl/src/include/openssl/bn.h:163:2: error: #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
 #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
  ^
```

I guess, I need to add `no_big_endian` tag in the BUILD files to disable the tests as you mentioned in https://github.com/tensorflow/tensorflow/pull/11170#issuecomment-329252942
I have identified below files which may require change:
```
tensorflow/core/platform/cloud/BUILD
tensorflow/contrib/tpu/profiler/BUILD
tensorflow/core/platform/default/build_config.bzl
tensorflow/core/platform/s3/BUILD
third_party/aws.BUILD
tensorflow/BUILD
tensorflow/core/platform/cloud/BUILD
tensorflow/contrib/cloud/kernels/BUILD
third_party/curl.BUILD
```
Please correct me if I'm missing anything here.

**Comment by gunan** [comment]
What was the exact command you tried and got this result?

**Comment by KingRando95** [comment]
5H2L

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Nayana-ibm** [comment]
Configure using: 
```
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_NEED_CUDA=0
export TF_NEED_MKL=0
export TF_NEED_OPENCL=0
export TF_NEED_VERBS=0
export TF_NEED_S3=0
yes "" | ./configure
```


Build
`bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`

==> Build successful.
  
Run bazel test command. 

```
bazel --host_jvm_args="-Xms512m" --host_jvm_args="-Xmx1024m" test \
    --test_tag_filters=-gpu,-benchmark-test -k \
    --test_timeout 300,450,1200,3600 --build_tests_only \
    --test_output=errors -- \
    //tensorflow/... -//tensorflow/compiler/...
```

==> Facing an issue related to boringssl : #error "Unknown target CPU"

**Comment by gunan** [comment]
The command somehow seems to be trying to build cloud and mobile targets.
using no_big_endian tags will not help with the command you are running, because you are not filtering with the "no_big_endian" tag in your command.
One immediate solution can be to exclude some more modules in your command. Could you try adding these at the end of your command:
```
-//tensorflow/core/platform/aws/... -//tensorflow/core-platform/cloud/... -//tensorflow/contrib/lite/... -//tensorflow/contrib/cloud/...
```

**Comment by Nayana-ibm** [comment]
@gunan Executed below command to execute tests:

```
bazel --host_jvm_args="-Xms512m" --host_jvm_args="-Xmx1024m" test \
    --test_tag_filters=-gpu,-benchmark-test -k \
    --test_timeout 300,450,1200,3600 --build_tests_only \
    --test_output=errors -- \
    //tensorflow/... -//tensorflow/compiler/... -//tensorflow/core/platform/aws/... -//tensorflow/core-platform/cloud/... -//tensorflow/contrib/lite/... -//tensorflow/contrib/cloud/... 
```
    
Still facing an error: 
```

external/boringssl/src/ssl/../crypto/internal.h:338:19: warning: 'constant_time_select_int' defined but not used [-Wunused-variable]
 static inline int constant_time_select_int(crypto_word_t mask, int a, int b) {
                   ^
____[9,702 / 9,711] Compiling external/boringssl/src/ssl/s3_pkt.cc
ERROR: /data/TF_tmp/_bazel_root/be3f47674f2731fd84874c35a2feb28b/external/boringssl/BUILD:128:1: Couldn't build file external/boringssl/_objs/ssl/external/boringssl/src/ssl/s3_pkt.pic.o: C++ compilation of rule '@boringssl//:ssl' failed (Exit 1).
In file included from external/boringssl/src/include/openssl/ssl.h:145:0,
                 from external/boringssl/src/ssl/s3_pkt.cc:109:
external/boringssl/src/include/openssl/base.h:114:2: error: #error "Unknown target CPU"
 #error "Unknown target CPU"
  ^
In file included from external/boringssl/src/include/openssl/asn1.h:68:0,
                 from external/boringssl/src/include/openssl/x509.h:70,
                 from external/boringssl/src/include/openssl/pem.h:66,
                 from external/boringssl/src/include/openssl/ssl.h:149,
                 from external/boringssl/src/ssl/s3_pkt.cc:109:
external/boringssl/src/include/openssl/bn.h:163:2: error: #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
 #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
  ^
In file included from external/boringssl/src/ssl/s3_pkt.cc:121:0:
external/boringssl/src/ssl/../crypto/internal.h:202:2: error: #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
 #error "Must define either OPENSSL_32_BIT or OPENSSL_64_BIT"
```

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by gunan** [comment]
Could you run another bazel query at head? grpc bug was fixed and our dependency was bumped. It is possible boringssl crept into another one of our libraries.

**Comment by Nayana-ibm** [comment]
@gunan I have executed tests with below command still facing an issue with boringssl.

```
bazel --host_jvm_args="-Xms512m" --host_jvm_args="-Xmx1024m" test \
    --test_tag_filters=-gpu,-benchmark-test -k \
    --test_timeout 300,450,1200,3600 --build_tests_only \
    --test_output=errors -- \
    //tensorflow/... -//tensorflow/compiler/... -//tensorflow/core/platform/aws/... -//tensorflow/core-platform/cloud/... -//tensorflow/contrib/lite/... -//tensorflow/contrib/cloud/... 
```
    
log available at : http://ci.tensorflow.org/job/tensorflow-contrib-s390x/1516/console

Is there any way to find out which component pulls boringssl?

**Comment by gunan** [comment]
Here is the message that looks suspicious:
```
ERROR: Skipping '//tensorflow/core/platform/aws/...': no targets found beneath 'tensorflow/core/platform/aws'.
ERROR: Skipping '//tensorflow/core-platform/cloud/...': no targets found beneath 'tensorflow/core-platform/cloud'.
ERROR: Skipping '//tensorflow/core/platform/aws/...': no targets found beneath 'tensorflow/core/platform/aws'.
ERROR: Skipping '//tensorflow/core-platform/cloud/...': no targets found beneath 'tensorflow/core-platform/cloud
```
So lets modify the last line of your command, looking at our folders in the git repo, like this:
```
//tensorflow/... -//tensorflow/compiler/... -//tensorflow/core/platform/s3/... -//tensorflow/core/platform/cloud/... -//tensorflow/contrib/lite/... -//tensorflow/contrib/cloud/... 
```

**Comment by Nayana-ibm** [comment]
@gunan  Could resolve the issue `Unknown target CPU`  by using command provided by you in previous comment. 

Build
`bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`

   
bazel test command. 
```
bazel --host_jvm_args="-Xms512m" --host_jvm_args="-Xmx1024m" test \
    --test_tag_filters=-gpu,-benchmark-test -k \
    --test_timeout 300,450,1200,3600 --build_tests_only \
    --test_output=errors -- \
    //tensorflow/... -//tensorflow/compiler/... -//tensorflow/core/platform/s3/... -//tensorflow/core/platform/cloud/... -//tensorflow/contrib/lite/... -//tensorflow/contrib/cloud/... 
```

**Comment by gunan** [comment]
Great!
So this issue is resolved?

**Comment by Nayana-ibm** [comment]
I could see `28 tests fail to build` in the results. But I guess it's not related to boringssl. 
For now, I am closing this issue.
@gunan Thanks for your help on this.
