### ISSUE TITLE
pip install version 0.7.1 from source: No module named google.protobuf

### ISSUE THREAD

**Issue by jplu** [tensorflow/tensorflow#1415]
Hello,

I have an issue with Google Protobuf. Even after the install Python does not find the module "google.protobuf".

### Environment info
Operating System: Ubuntu 14.04
Python: 2.7.6
Bazel: 0.2.0
Cuda: 7.5
CudNN: 4

If installed from sources, provide the commit hash: https://github.com/tensorflow/tensorflow/commit/1e47e2f9bb7112f1a763e758a7bcdaff36edec5b

### Steps to reproduce
1. bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
2. bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
3. bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
4. PYTHONUSERBASE=/usr/local/python pip install --user /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl

Output for pip install:

```
Unpacking /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/local/python/lib/python2.7/site-packages (from tensorflow==0.7.1)
Downloading/unpacking protobuf==3.0.0b2 (from tensorflow==0.7.1)
  Downloading protobuf-3.0.0b2-py2.py3-none-any.whl (326kB): 326kB downloaded
Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/local/python/lib/python2.7/site-packages (from tensorflow==0.7.1)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.2 in /usr/local/python/lib/python2.7/site-packages (from tensorflow==0.7.1)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/python/lib/python2.7/site-packages (from protobuf==3.0.0b2->tensorflow==0.7.1)
Installing collected packages: tensorflow, protobuf
Successfully installed tensorflow protobuf
Cleaning up...
```

Error in Python interpreter:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named google.protobuf
>>>
```

In the Python prompt, when I run ```help('modules')```, I can see the module ```tensorflow``` but not the module ```google```.

The first thing I tried is:

1. pip uninstall protobuf 
2. PYTHONUSERBASE=/usr/local/python pip install --user --upgrade /tmp/tensorflow_pkg/tensorflow-0.7.1-cp27-none-any.whl

Output:

```
Installing collected packages: tensorflow, protobuf
Successfully installed tensorflow protobuf
Cleaning up...
```

Same result, no Protobuf module found.

The second thing I tried is:

1. pip uninstall protobuf
2. pip uninstall tensorflow
3. PYTHONUSERBASE=/usr/local/python pip install --user /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl

Output:

```
Installing collected packages: tensorflow, protobuf
Successfully installed tensorflow protobuf
Cleaning up...
```

Same result again, not Protobuf module found.

Any idea of why Protobuf is properly installed but not recognized by Python whereas Tensorflow is propertly recognized by Python?

Thanks for any help that you can provide.

**Comment by martinwicke** [comment]
It's just protobuf, not google.protobuf. Does something in tensorflow not work?

**Comment by cameronphchen** [comment]
Did you use --recurse-submodules when you clone?
`git clone --recurse-submodules https://github.com/tensorflow/tensorflow`
`git submodule update --init` should also work

**Comment by martinwicke** [comment]
There seems to have been an issue with the protobuf pypi package, which should have been fixed about 30 minutes ago, please try again.

**Comment by jplu** [comment]
Sorry for my late reply. But I still have the same issue with the commit https://github.com/tensorflow/tensorflow/commit/34880c4ca1a83b443b44dc415b74deb217c42257

I did a brand new clone of Tensorflow by running:

```
git clone --recurse-submodules https://github.com/tensorflow/tensorflow
```

Then I recompiled everything

```
./configure
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
PYTHONUSERBASE=/usr/local/python pip install --user /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl
cd tensorflow/models/image/mnist
python convolutional.py
```

And I still have the same error:

```
Traceback (most recent call last):
  File "convolutional.py", line 34, in <module>
    import tensorflow as tf
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

And indeed if I run the command ```help('modules')```, I still don't see any ```protobuf``` or ```google``` module in the list.

**Comment by RasmooL** [comment]
I think the problem would be resolved by doing as follows, since I remember having to do something similar:

```
git clone https://github.com/tensorflow/tensorflow
git clone https://github.com/google/protobuf
cd tensorflow
git submodule init
git config submodule.google/protobuf.url ../protobuf
git submodule update
```

**Comment by vrv** [comment]
pip uninstall tensorflow
pip uninstall protobuf
pip install path/to/tensorflow.whl

has also worked for a lot of people.  0.7.0's install broke a lot of things that 0.7.1 fixed.

**Comment by jplu** [comment]
Hello,

About @vrv's answer, still not working:

```
pip uninstall tensorflow
pip uninstall protobuf
PYTHONUSERBASE=/usr/local/python pip install --user /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl
Unpacking /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.2 in /usr/lib/python2.7/dist-packages (from tensorflow==0.7.1)
Downloading/unpacking protobuf==3.0.0b2 (from tensorflow==0.7.1)
  Downloading protobuf-3.0.0b2-py2.py3-none-any.whl (326kB): 326kB downloaded
Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/lib/python2.7/dist-packages (from tensorflow==0.7.1)
Downloading/unpacking six>=1.10.0 (from tensorflow==0.7.1)
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from protobuf==3.0.0b2->tensorflow==0.7.1)
Installing collected packages: tensorflow, protobuf, six
Successfully installed tensorflow protobuf six
Cleaning up...
cd tensorflow/models/image/mnist
python convolutional.py
Traceback (most recent call last):
  File "convolutional.py", line 34, in <module>
    import tensorflow as tf
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

Now about @RasmooL's answer, again, still the same error:

```
git clone https://github.com/tensorflow/tensorflow
git clone https://github.com/google/protobuf
cd tensorflow
git submodule init
git config submodule.google/protobuf.url ../protobuf
git submodule update
./configure
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
PYTHONUSERBASE=/usr/local/python pip install --user /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl
Unpacking /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.2 in /usr/lib/python2.7/dist-packages (from tensorflow==0.7.1)
Downloading/unpacking protobuf==3.0.0b2 (from tensorflow==0.7.1)
  Downloading protobuf-3.0.0b2-py2.py3-none-any.whl (326kB): 326kB downloaded
Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/lib/python2.7/dist-packages (from tensorflow==0.7.1)
Downloading/unpacking six>=1.10.0 (from tensorflow==0.7.1)
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from protobuf==3.0.0b2->tensorflow==0.7.1)
Installing collected packages: tensorflow, protobuf, six
Successfully installed tensorflow protobuf six
Cleaning up...
cd tensorflow/models/image/mnist
python convolutional.py
Traceback (most recent call last):
  File "convolutional.py", line 34, in <module>
    import tensorflow as tf
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

And, even after trying once again @vrv's answer, same error.

**Comment by jplu** [comment]
I tried on the other machines, one with Ubuntu 14.04 with the same config than mine and another on Ubuntu 15.10 with a slighly more recent Python (2.7.10). And on both I still have the same issue.

**Comment by jplu** [comment]
Ok, I have maybe found something. My protobuf module is installed under:

```
/usr/local/python/lib/python2.7/site-packages/google/protobuf/
```

And in my PYTHONPATH I have:

```
/usr/local/python/lib/python2.7/site-packages/
```

Then to import the Protobuf module we have to do "google.protobuf". But apparently Python doesn't like this and I don't know why because if I add the following path in my PYTHONPATH:

```
/usr/local/python/lib/python2.7/site-packages/google/
```

I can see the Protobuf module in the list of recognized modules. Nevertheless, in all the python files in Tensorflow, the Protobuf module is imported like this "google.protobuf" which result for to the same error:

```
python convolutional.py
Traceback (most recent call last):
  File "convolutional.py", line 34, in <module>
    import tensorflow as tf
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

Any idea of a possible workaround?

**Comment by vrv** [comment]
Can you take a look at our install guide for "common problems" and let us know if that helps ?

**Comment by jplu** [comment]
I tried all the proposed solutions about "pip", ```pip install --upgrade pip``` and ```PYTHONUSERBASE=/usr/local/python pip install --upgrade --user /tmp/tensorflow_pkg/tensorflow-0.7.1-py2-none-any.whl```

But I still have the same issue. The module "protobuf" is well installed and recognized by Python, but the module "google.protobuf" is still not known.

I have the same behavior with the 3 different machines I'm testing on.

**Comment by vrv** [comment]
Did you try:

pip uninstall tensorflow
pip uninstall protobuf
pip install --user path/to/tensorflow.whl ?

**Comment by jplu** [comment]
Yes, and it still doesn't work.

I also tried with virtualenv to see if it can change something, but I have the exact same behavior.

**Comment by ajaun** [comment]
Same problem here after updating from 0.6 to 0.7.1. Not sure if this helps, but I noticed that site-packages/google/protobuf/__init__.py file is missing after recompiling with bazel.

**Comment by shendiaomo** [comment]
I had the same problem when trying to update from 0.5 to 0.7.1, It seems sth. is wrong with the wheel package

**Comment by RasmooL** [comment]
Can you try installing the newest master wheel from here?
http://ci.tensorflow.org/job/tensorflow-master-gpu_pip/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-py2-none-any.whl

I just installed it in a clean 2.7.11 virtualenv and it worked fine,

**Comment by jplu** [comment]
Stil doesn't work:

```
pip uninstall tensorflow
pip uninstall protobuf
PYTHONUSERBASE=/usr/local/python pip install --user http://ci.tensorflow.org/job/tensorflow-master-gpu_pip/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-py2-none-any.whl
python convolutional.py
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "convolutional.py", line 34, in <module>
    import tensorflow as tf
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 55, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/python/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there
```

**Comment by apmanikandan** [comment]
I had the similar problem after upgrading to 0.7 ,sorted out by
1. uninstalling tensorflow
2. install master
3. Check whether you are able to import tensorflow --> If it works first,
then upgrade to 0.7


You may want to check the python path and verify the version on protocol
buffer during your installation.

Cheers,
Mani

Cheers,
Mani

**Comment by jplu** [comment]
> 1. uninstalling tensorflow
> 2. install master
> 3. Check whether you are able to import tensorflow --> If it works first,
> then upgrade to 0.7

Already done that according to the previous recommandations and it doesn't work.

> You may want to check the python path and verify the version on protocol
> buffer during your installation.

My PYTHONPATH variable is perfectly set because all the modules are recognized (including "protobuf") but not "google.protobuf". The version of the installed "Protobuf" is "3.0.0b2" which seems to be the good one.

**Comment by jplu** [comment]
Ok, I succeed to solve the bug. Apprently, as @ajaun said a "__init__.py" file is missing in the "google" folder. Then, if I create an empty "__init__.py" file to get the following structure:

google
|-- __init__.py
|-- protobuf

It works.

**Comment by ajaun** [comment]
Until the bug has been fixed with protobuf, a cleaner workaround might be to follow @jonparrott in https://github.com/google/protobuf/issues/1296, namely to edit the source directory by

1. Adding a new file tensorflow/google/__init__.py:
```
try:
    import pkg_resources
    pkg_resources.declare_namespace(__name__)
except ImportError:
    import pkgutil
    __path__ = pkgutil.extend_path(__path__, __name__)
```

2. Add namespace_packages to tensorflow/google/protobuf/python/setup.py:

```
setup(
    name='protobuf',
    namespace_packages=['google'],
    ...
)
```

3. Recompile / pip install. Good luck!

**Comment by jplu** [comment]
This works like a charm as well. Thanks!

I let the issue open, waiting for the final fix.

**Comment by jonparrott** [comment]
FWIW, it's not a workaround. It's how things **should** be done. Do we need to push for protobuf to cut a new release?

**Comment by girving** [comment]
@vrv: What's the status of this?

**Comment by vrv** [comment]
I think we fixed this in 0.8 and it hasn't regressed.

**Comment by BrendanGraham14** [comment]
This issue is occurring on an install of tensorflow-gpu 1.1.0.
I've tried:

$ sudo pip3 uninstall tensorflow-gpu
$ sudo pip3 uninstall protobuf

$ sudo pip3 install tensorflow-gpu
Output: 
`Successfully installed protobuf-3.3.0 tensorflow-gpu-1.1.0`

$ python3
`import tensorflow as tf`
has output:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 54, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named 'google.protobuf'
`

**Comment by kcgthb** [comment]
That issue is still present in 1.3.0. This is getting borderline ridiculous. It's been a year and a half now, so it's really time for it to get fixed once and for all.

```
$ pip install --user --no-cache-dir --upgrade --ignore-installed tensorflow-gpu
[...]
Successfully installed backports.weakref-1.0rc1 bleach-1.5.0 funcsigs-1.0.2 html5lib-0.9999999 markdown-2.6.9 mock-2.0.0 numpy-1.13.1 pbr-3.1.1 protobuf-3.4.0 setuptools-36.2.7 six-1.10.0 tensorflow-1.3.0 tensorflow-gpu-1.3.0 tensorflow-tensorboard-0.1.4 werkzeug-0.12.2 wheel-0.29.0
$ python -c "import tensorflow; print tensorflow.__version__"
[...]
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf

$ touch .local/lib/python2.7/site-packages/google/__init__.py
$ python -c "import tensorflow; print tensorflow.__version__"
1.3.0
```

**Comment by martinwicke** [comment]
You have protobuf 3.4.0 -- can you downgrade to 3.3 and see if that works? If not, can you file a new issue? I don't know whether an old bug has crept in.

**Comment by kcgthb** [comment]
This is the protobuf version that comes as a dependency of Tensorflow via pip install. I have no local Python module installed before installing TF.

**Comment by martinwicke** [comment]
protobuf released 3.4 a week ago. 

@kcgthb do you have any other google.* packages installed?

@vrv what was the change required in protobuf that fixed this issue? Is it possible it's been accidentally reverted in 3.4?

@gunan We're not seeing this in CI -- are we caching/fixing the version?

**Comment by gunan** [comment]
In our CI we pin our dependencies to avoid failures whenever a new release happens.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_proto3.sh#L20
Looks like our protobuf dependency is pinned to 3.4

**Comment by vrv** [comment]
@martinwicke in the earliest versions of TF pre 1.0 we were packaging protobuf in our pip accidentally.  We haven't done that in over a year, so this is an unrelated issue to that.

**Comment by kcgthb** [comment]
@martinwicke nope, no other google.* package installed. It's on a freshly deployed machine.

**Comment by martinwicke** [comment]
I notices something strange in your log:

```
Successfully installed [...] tensorflow-1.3.0 tensorflow-gpu-1.3.0 [...]
```

Can you clear this out and reinstall only one TensorFlow (-gpu)? 

@yifeif we're not depending on tensorflow in tensorflow-gpu, are we?

Is this in a virtualenv? Can you try that?

**Comment by yifeif** [comment]
tensorflow-gpu should not be depending on tensorflow. This might be due tensorboard's dependency on tensorflow. 

I would recommend trying virtualenv as well.

**Comment by byronyi** [comment]
I've noticed the tensorboard's dependency on tensorflow while installing tensorflow-gpu in a virtualenv. We probably have some circular dependency issues here.

**Comment by gunan** [comment]
Yes, that seems to be the problem. @jart Looks like when installing tensorflow-gpu, tensorboard also tries to install tensorflow (non-gpu). I am not sure what should be out course of action here, maybe we can create a tensorboard-gpu package?

**Comment by gunan** [comment]
another option is this:
after you pip install tensorflow-gpu, run these commands:
(Remove both tensorflow and tensorflow-gpu, and reinstall tensorflow-gpu with no deps)

```
pip uninstall tensorflow
pip install tensorflow-gpu --no-deps --upgrade
```

**Comment by kcgthb** [comment]
This is because some Python module pretend to support Python 2.x but rely on features introduced in Python 3.3, such as implicit namespace packages ([PEP 420](https://www.python.org/dev/peps/pep-0420)). And Google's `protobuf` seems to expect everybody to be running a Python version that support native namespace packages.

This is all detailed in https://packaging.python.org/guides/packaging-namespace-packages/
Properly supporting all versions of Python will require a `__init__.py` file in the module directory.

This has apparently been discussed [numerous times](https://github.com/protocolbuffers/protobuf/issues/4189), fixed in some versions, just to be [re-introduced](https://github.com/protocolbuffers/protobuf/issues/5046) later, so at that point, after several years and countless bug reports, ¯\_(ツ)_/¯

**Comment by theacodes** [comment]
Hi there, I'm the author of https://packaging.python.org/guides/packaging-namespace-packages/ and the "gatekeeper" as such of the `google` and `google.cloud` package namespaces.

> This is because some Python module pretend to support Python 2.x but rely on features introduced in Python 3.3, such as implicit namespace packages (PEP 420).

This isn't true. We use pkg-resources namespaces for `google` and `google.cloud` for the broadest compatibility. This works fine on Python 2.7. We can't switch to any other without a coordinated release of several hundred packages.

> This has apparently been discussed numerous times, fixed in some versions, just to be re-introduced later, so at that point, after several years and countless bug reports, ¯_(ツ)_/¯

This isn't necessarily protobuf's fault. As far as I can tell, they've always had the proper incantations in `google/__init__.py` and `setup.py` to activate the namespace package logic and play nicely across all of the other Google packages.

What *could* be happening is various bugs in pip, setuptools, and fun issues introduced by downstream re-packaging (such as debian) where the right combination of things produces this error.

This is why we always recommend to *use a virtualenv* and *use only an up-to-date pip* for installing Python packages for development.

**Comment by kcgthb** [comment]
Hi @theacodes, 

Thanks for the clarification, but I'm still confused:  I just tried a `pip install --user protobuf` again, with Python 2.7, and the directory tree it created in `~/.local/lib/python2.7/site-packages` looks like this:

```
google/
└── protobuf
    ├── __init__.py
    ├── __init__.pyc
    ├── any_pb2.py
[...]
```
That is: no `__init__.py` in `google/`, which, unless I'm missing something, makes it a native/implicit namespace, right? 

Wouldn't a pkg-resources `google` namespace require a `google/__init__.py` file with `__import__('pkg_resources').declare_namespace(__name__)` for Python <3.3?

**Comment by theacodes** [comment]
It doesn't mean *anything*. pip (and other installers) can make decisions on how to treat the different kinds of namespace packages when installing. Pip has detected that your environment *should* support `.pth` files for namespace packages, so it *omits* `__init__.py` files for those packages and creates a `.pth` file in your `site-packages` directory for the `google` namespace. That `.pth` file handles wiring up the `google` module's `__path__` to point to *all* places where packages under the `google` namespace could be.

**Comment by SikandAlex** [comment]
This is insane. I'm dealing with this issue for past 14 hours and it looks like the history goes back to 2016 (5 years ago). All just so I can use the google-cloud-vision Python library. Smh Google.
