### ISSUE TITLE
macOS build failed

### ISSUE THREAD

**Issue by lightingghost** [tensorflow/tensorflow#14174]
macOS 10.13
CUDA9.0 CUDNN7.0
bazel 0.7.0

```
tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (4) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=float, IntType=tensorflow::int32, useSmem=true]" 
(231): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=float, IntType=tensorflow::int32]" 
(251): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (4) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=float, IntType=tensorflow::int32, useSmem=false]" 
(236): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=float, IntType=tensorflow::int32]" 
(251): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (4) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=float, IntType=tensorflow::int64, useSmem=true]" 
(231): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=float, IntType=tensorflow::int64]" 
(251): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (4) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=float, IntType=tensorflow::int64, useSmem=false]" 
(236): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=float, IntType=tensorflow::int64]" 
(251): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=double, IntType=tensorflow::int32, useSmem=true]" 
(231): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=double, IntType=tensorflow::int32]" 
(251): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=double, IntType=tensorflow::int32, useSmem=false]" 
(236): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=double, IntType=tensorflow::int32]" 
(251): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=double, IntType=tensorflow::int64, useSmem=true]" 
(231): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=double, IntType=tensorflow::int64]" 
(251): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=double, IntType=tensorflow::int64, useSmem=false]" 
(236): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=double, IntType=tensorflow::int64]" 
(251): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=tensorflow::complex64, IntType=tensorflow::int32, useSmem=true]" 
(231): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=tensorflow::complex64, IntType=tensorflow::int32]" 
(252): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=tensorflow::complex64, IntType=tensorflow::int32, useSmem=false]" 
(236): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=tensorflow::complex64, IntType=tensorflow::int32]" 
(252): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=tensorflow::complex64, IntType=tensorflow::int64, useSmem=true]" 
(231): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=tensorflow::complex64, IntType=tensorflow::int64]" 
(252): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (8) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=tensorflow::complex64, IntType=tensorflow::int64, useSmem=false]" 
(236): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=tensorflow::complex64, IntType=tensorflow::int64]" 
(252): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (16) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=tensorflow::complex128, IntType=tensorflow::int32, useSmem=true]" 
(231): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=tensorflow::complex128, IntType=tensorflow::int32]" 
(253): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (16) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=tensorflow::complex128, IntType=tensorflow::int32, useSmem=false]" 
(236): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=tensorflow::complex128, IntType=tensorflow::int32]" 
(253): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (16) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=tensorflow::complex128, IntType=tensorflow::int64, useSmem=true]" 
(231): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=tensorflow::complex128, IntType=tensorflow::int64]" 
(253): here

tensorflow/core/kernels/split_lib_gpu.cu.cc(122): error: specified alignment (16) is different from alignment (2) specified on a previous declaration
          detected during:
            instantiation of "void tensorflow::split_v_kernel<T,IntType,useSmem>(const T *, tensorflow::CudaDeviceArrayStruct<IntType, 8>, IntType, IntType, tensorflow::CudaDeviceArrayStruct<T *, 8>) [with T=tensorflow::complex128, IntType=tensorflow::int64, useSmem=false]" 
(236): here
            instantiation of "void tensorflow::SplitVOpGPULaunch<T, IntType>::Run(const Eigen::GpuDevice &, __nv_bool, const T *, int, int, const tensorflow::CudaDeviceArrayStruct<IntType, 8> &, const tensorflow::CudaDeviceArrayStruct<T *, 8> &) [with T=tensorflow::complex128, IntType=tensorflow::int64]" 
(253): here

16 errors detected in the compilation of "/var/folders/2f/891g9y691gzcy23blt644z6m0000gn/T//tmpxft_00002e92_00000000-6_split_lib_gpu.cu.cpp1.ii".
ERROR: /Users/odin/local/tensorflow/tensorflow/core/kernels/BUILD:387:1: output 'tensorflow/core/kernels/_objs/split_lib_gpu/tensorflow/core/kernels/split_lib_gpu.cu.pic.o' was not created.
ERROR: /Users/odin/local/tensorflow/tensorflow/core/kernels/BUILD:387:1: not all outputs were created or valid.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

**Comment by smitshilu** [comment]
Same issue here.

**Comment by chaoswith** [comment]
Same issue here too

**Comment by omerbenamram** [comment]
same here

**Comment by kanwei** [comment]
👍

**Comment by marmarko** [comment]
same here

**Comment by chaoswith** [comment]
finally build success!!

GTX 1080
10.13.1
CUDA9.0 CUDNN7.0
bazel 0.7.0

the point is delete text '__align__(sizeof(T))'

concat_lib_gpu.impl.cu.cc
depthwise_conv_op_gpu.cu.cc
splite_lib_gpu.cu.cc

extern __shared__ __align__(sizeof(T)) unsigned char smem[];
->   extern __shared__ unsigned char smem[];


<img width="1543" alt="2017-11-06 11 10 08" src="https://user-images.githubusercontent.com/485090/32445438-09cb2a9c-c349-11e7-9f86-67aade41b64a.png">

**Comment by smitshilu** [comment]
@chaoswith may I know Xcode command line tool version?

**Comment by jart** [comment]
We only promise compatibility with XCode 7.2 at this time. See the [source install docs](https://www.tensorflow.org/install/install_sources). CC: @gunan 

PTAL @ekelsen We're getting a compiler error about memory alignment, in recent versions of clang, on some GPU sources you worked on.

It also seems like [PyTorch](https://github.com/pytorch/pytorch/issues/2692) and a bunch of other projects have recently encountered this same issues. Maybe the compiler got stricter and has helped us identify a suboptimality.

@chaoswith While removing `__align__` might be a successful workaround, it's probably not a fix we could use in the long run.

**Comment by smitshilu** [comment]
Build success! Thank you @chaoswith

**Comment by gunan** [comment]
The GPU build on macOS is completely community supported now, as there are no "Officially supported" systems released by apple that have NVIDIA GPUs.

But looks like this issue was resolved anyway?

**Comment by kanwei** [comment]
I finally got CUDA working on High Sierra, CUDA 9, and cuDNN 7, by removing the "align"s, doing the LD_LIBRARY_PATH hack above, and removing "-lgomp" from the CUDA makefile. Pain in the butt, but it works!

**Comment by smitshilu** [comment]
I have listed all the steps to build tensorflow 1.4 with CUDA 9 at here https://gist.github.com/smitshilu/53cf9ff0fd6cdb64cca69a7e2827ed0f

**Comment by lightingghost** [comment]
@kanwei I also came across the `ld: library not found for -lgomp` error. Can you please let me know where should I remove the  "-lgomp" from the CUDA makefile

**Comment by norman-thomas** [comment]
@lightingghost inside the file [`third_party/gpus/cuda/BUILD.tpl` line 112](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/cuda/BUILD.tpl#L112)

**Comment by lightingghost** [comment]
@norman-thomas Thanks for helping.

**Comment by ekelsen** [comment]
It's not clear to me that the align directive is needed here; might be worth testing internally.

**Comment by wt-huang** [comment]
Closing as the issue is resolved.

**Comment by elbamos** [comment]
I'm curious why this was closed as "resolved." The issue definitely still exists as of today.  Looking above, there are some serious constructive suggestions for resolving it.

**Comment by saudet** [comment]
@elbamos Let's send a pull request with a patch for that?

**Comment by elbamos** [comment]
The issue described above definitely exists in two source files, still. But I still haven’t gotten a clean install after fixing them. The PR should come from someone who has. If I get there I’ll try to do it, but I don’t know that I will get there.

**Comment by saudet** [comment]
@elbamos Try these commands:
https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/cppbuild.sh#L128
It builds fine for me: https://travis-ci.org/bytedeco/javacpp-presets/jobs/468862064

**Comment by elbamos** [comment]
Didn't work for me - I'm stuck on `./tensorflow/contrib/nccl/kernels/nccl_manager.h:30:10: fatal error: 'third_party/nccl/nccl.h' file not found` That's pretty unrelated to this Issue so this isn't the place to discuss it.

**Comment by elbamos** [comment]
@saudet I was ultimately able to get it compiled with your commands. However, the problem arises that then the library paths need to be set in the environment before running python.  This makes it hard to run with jupyter, among other issues.

**Comment by elbamos** [comment]
@saudet I believe the issue is that instead of changing the PATH and DYLD_LIBRARY_PATH at compile time, you need to add the relevant directories to the directives given to the linker...  I used to know the details of this, some years ago.

Here's some additional information:
```
otool -L ./libtensorflow_framework.so
./libtensorflow_framework.so:
	@rpath/libtensorflow_framework.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/cuda/lib/libcuda.dylib (compatibility version 1.1.0, current version 10.0.130)
	@rpath/libcudnn.7.dylib (compatibility version 0.0.0, current version 7.3.1)
	@rpath/libcudart.10.0.dylib (compatibility version 0.0.0, current version 10.0.130)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)

otool -L ./_pywrap_tensorflow_internal.so
./_pywrap_tensorflow_internal.so:
	@rpath/_pywrap_tensorflow_internal.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtensorflow_framework.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libcublas.10.0.dylib (compatibility version 0.0.0, current version 10.0.130)
	@rpath/libcusolver.10.0.dylib (compatibility version 0.0.0, current version 10.0.130)
	@rpath/libcudart.10.0.dylib (compatibility version 0.0.0, current version 10.0.130)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1454.93.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.70.9)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
```

So, you can see the problem is the `@rpath` on libcudnn and libcudart.  

One way of changing this would be to run `install_name_tool` as 
```
install_name_tool -change "@rpath/libcudnn.7.dylib" "/usr/local/cuda/lib/libcudnn.7.dylib" libtensorflow_framework.so
install_name_tool -change "@rpath/libcudart.10.0.dylib" "/usr/local/cuda/lib/libcudart.10.0.dylib" libtensorflow_framework.so
```
etc. 

This *does* work when applied to all 6 cuda library references in the two libraries.  (I suspect it might only need to be done with the `_pywrap_tensorflow_internal.so`, but I haven't checked. 

There's a comment here: https://github.com/tensorflow/tensorflow/issues/6729#issuecomment-284106845  with an alternative approach.

However, I believe the *correct* thing to do, is to provide proper directives to the linker, and *not* set the environment variables at compile time.

**Comment by saudet** [comment]
I'm pretty sure the CUDA paths are in the rpath. Check `otool -l`, I'm sure
they will show up there.

**Comment by elbamos** [comment]
I just checked, and they're definitely not there.  (If they were there, then we wouldn't have this issue.)

For both of them I do see:

```
Load command 26
          cmd LC_RPATH
      cmdsize 48
         path ../local_config_cuda/cuda/lib (offset 12)
Load command 27
          cmd LC_RPATH
      cmdsize 56
         path ../local_config_cuda/cuda/extras/CUPTI/lib (offset 12)
```

So it looks like an install tool directive that is improperly replacing a variable.
