### ISSUE TITLE
error: namespace "Eigen::half_impl" has no member "__half_raw" when building latest TensorFlow/CUDA 9.0

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#15108]
When trying to build latest TensorFlow for CUDA 9.0/CuDNN 7.0, from today's head

Complete instructions to reproduce are [here](https://github.com/yaroslavvb/tf_build), but basically I followed steps in in [Dockerfile.devel-gpu](https://github.com/tensorflow/tensorflow/blob/c5c642e051f1a7876d099bfcd9f8a2ecaf7227b8/tensorflow/tools/docker/Dockerfile.devel-gpu) to install dependencies, and then did `bazel build -c opt --config=cuda`

Here are the errors

```
INFO: From Compiling tensorflow/stream_executor/cuda/cuda_blas.cc:
tensorflow/stream_executor/cuda/cuda_blas.cc: In function 'cudaDataType_t perftools::gputools::cuda::{anonymous}::CUDAComputationType(perftools::gputools::blas::ComputationType)':
tensorflow/stream_executor/cuda/cuda_blas.cc:527:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: From Compiling tensorflow/core/kernels/dense_to_sparse_batch_dataset_op.cc:
tensorflow/core/kernels/dense_to_sparse_batch_dataset_op.cc: In member function 'virtual void tensorflow::{anonymous}::DenseToSparseBatchDatasetOp::MakeDataset(tensorflow::OpKernelContext*, tensorflow::DatasetBase*, tensorflow::DatasetBase**)':
tensorflow/core/kernels/dense_to_sparse_batch_dataset_op.cc:83:71: warning: 'batch_size' may be used uninitialized in this function [-Wmaybe-uninitialized]
         : batch_size_(batch_size), row_shape_(row_shape), input_(input) {
                                                                       ^
tensorflow/core/kernels/dense_to_sparse_batch_dataset_op.cc:41:11: note: 'batch_size' was declared here
     int64 batch_size;
           ^
INFO: From Compiling tensorflow/core/kernels/histogram_op_gpu.cu.cc:
./tensorflow/core/util/cuda_kernel_helper.h(109): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(109): error: expected a ")"

./tensorflow/core/util/cuda_kernel_helper.h(110): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(113): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(113): error: expected a ";"

./tensorflow/core/util/cuda_kernel_helper.h(119): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(119): error: expected a ")"

./tensorflow/core/util/cuda_kernel_helper.h(120): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(123): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(123): error: expected a ";"

10 errors detected in the compilation of "/tmp/tmpxft_000137d9_00000000-6_histog

```

**Comment by gunan** [comment]
https://github.com/tensorflow/tensorflow/pull/14770 should fix that issue.

**Comment by yzhang092** [comment]
Thanks. Exactly same issue and #14770 commit did fix it.

**Comment by yzhang092** [comment]
#14770 seems not fix this issue. Still get error from cuda_kernel_helper

**Comment by nevakanezzar** [comment]
seconded, same issue.

**Comment by maxiaodong97** [comment]
looking into the history the breaking code introduced yesterday by 
Wrappers for CUDA 9 warp-synchronous intrinsics.

**Comment by yaroslavvb** [comment]
Cc @zheng-xq

**Comment by gunan** [comment]
Looks like I was wrong, the PR I mentioned did not fix this completely. However this is fixed internally.
@caisq when are we planning the next push from internal to github?

**Comment by caisq** [comment]
I'll push as soon as the ongoing pull is complete, @gunan

**Comment by JackShen2015** [comment]
I tried to build it, but it seems that the issue still exist

**Comment by castleguarders** [comment]
FYI, Issue still there in case the push already happened.

**Comment by caisq** [comment]
The push is open in PR https://github.com/tensorflow/tensorflow/pull/15174, awaiting approval.

**Comment by gunan** [comment]
This should now be fixed.

**Comment by samikama** [comment]
This is back again. Commit  1ad680d3a seems to break it again.

**Comment by David-Levinthal** [comment]
just leaving some of the build error messages from a cuda9.1 build with openmpi
INFO: From Compiling tensorflow/core/kernels/gather_functor_gpu.cu.cc:^M
./tensorflow/core/util/cuda_kernel_helper.h(116): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(116): error: expected a ")"

./tensorflow/core/util/cuda_kernel_helper.h(117): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(120): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(120): error: expected a ";"

./tensorflow/core/util/cuda_kernel_helper.h(126): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(126): error: expected a ")"

./tensorflow/core/util/cuda_kernel_helper.h(127): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(130): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(130): error: expected a ";"

10 errors detected in the compilation of "/tmp/tmpxft_00004514_00000000-6_gather_functor_gpu.cu.cpp1.ii".
ERROR: /home/levinth/tensorflow/tensorflow/core/kernels/BUILD:1139:1: output 'tensorflow/core/kernels/_objs/gather_functor_gpu/tensorflow/core/kernels/gather_functor_gpu.cu.pic.o' was not created

**Comment by gunan** [comment]
@reedwm @zhengxq FYI.

I think we have an internal fix, we are waiting for that to be pushed out.
@reedwm, could you confirm?

**Comment by reedwm** [comment]
1ad680d3a36e9742229748d5c5d3bddb1d0a2578 has been rolled back internally, so this should be fixed internally. Thank you @samikama for identifying the specific commit that broke it.

**Comment by David-Levinthal** [comment]
when will we see the fix externally?

**Comment by gunan** [comment]
Should be at master now.

**Comment by David-Levinthal** [comment]
yup..fresh git clone and
INFO: Elapsed time: 362.184s, Critical Path: 157.04s^M
INFO: Build completed successfully, 2767 total actions^M

**Comment by gunan** [comment]
Thanks for verifying!
Then I am closing this issue.
