### ISSUE TITLE
Calling tf.contrib.lite.toco_convert results in global name 'tempfile' is not defined error

### ISSUE THREAD

**Issue by ushnish** [tensorflow/tensorflow#15410]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

Related SO post - https://stackoverflow.com/questions/47645056/tensorflow-lite-toco-python-apl-nameerror-name-tempfile-is-not-defined

If you open a GitHub issue, here is our policy:

1. It must be a bug or a feature request.
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Followed example on Tensorflow Lite documentation

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MacOS High Sierra

- **TensorFlow installed from (source or binary)**:
Source

- **TensorFlow version (use command below)**:
('v1.3.0-rc1-5910-ge2174cc943', '1.4.0')

- **Python version**: 
2.7.10

- **Bazel version (if compiling from source)**:
bazel release 0.5.4-homebrew

- **GCC/Compiler version (if compiling from source)**:
Apple LLVM version 9.0.0 (clang-900.0.34.1)

- **CUDA/cuDNN version**:
N/A (CPU only)

- **GPU model and memory**:
N/A

- **Exact command to reproduce**:

```
import tensorflow as tf
img = tf.placeholder(name="img", dtype=tf.float32, shape=(1, 64, 64, 3))
val = img + tf.constant([1., 2., 3.]) + tf.constant([1., 4., 4.])
out = tf.identity(val, name="out")
with tf.Session() as sess:
  tflite_model = tf.contrib.lite.toco_convert(sess.graph_def, [img], [out])
  open("converteds_model.tflite", "wb").write(tflite_model)

```

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

Opened python on terminal and ran

```
import tensorflow as tf
img = tf.placeholder(name="img", dtype=tf.float32, shape=(1, 64, 64, 3))
val = img + tf.constant([1., 2., 3.]) + tf.constant([1., 4., 4.])
out = tf.identity(val, name="out")
with tf.Session() as sess:
  tflite_model = tf.contrib.lite.toco_convert(sess.graph_def, [img], [out])
  open("converteds_model.tflite", "wb").write(tflite_model)

```

Resulting output is

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 198, in toco_convert
    input_data.SerializeToString())
  File "/Library/Python/2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 91, in toco_convert_protos
    with tempfile.NamedTemporaryFile() as fp_toco, \
NameError: global name 'tempfile' is not defined
```

As a sanity check I ran the following

```
import tempfile
with tempfile.NamedTemporaryFile() as fp_toco:
     print fp_toco.name
```
Output was /var/folders/hd/7yc9wgwj5wvd43_d94b4m47m0000gn/T/tmpxxdYMY

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by leandroBorgesFerreira** [comment]
Same here. It also throw this error with Python 3.6.3 :: Anaconda custom (64-bit)

**Comment by facaiy** [comment]
I believe the bug has been fixed in master branch, could you test it on [tf-nightly](https://github.com/tensorflow/tensorflow#installation) ?

**Comment by leandroBorgesFerreira** [comment]
Hello facaiy, I amor using the master branch (the nightly) version, but the problem is still there =\. At least for high sierra

**Comment by aselle** [comment]
Sorry about this. It seems it has to do with the interface sealing in tensorflow (where we try to prevent exposing symbols unrelated to the interfaces). You can work around this with the following code

```

import tensorflow as tf
# manually put back imported modules
import tempfile
import subprocess
tf.contrib.lite.tempfile = tempfile
tf.contrib.lite.subprocess = subprocess

img = tf.placeholder(name="img", dtype=tf.float32, shape=(1, 64, 64, 3))
val = img + tf.constant([1., 2., 3.]) + tf.constant([1., 4., 4.])
out = tf.identity(val, name="out")
with tf.Session() as sess:
  tflite_model = tf.contrib.lite.toco_convert(sess.graph_def, [img], [out])
  open("converteds_model.tflite", "wb").write(tflite_model)
```
I'll make a more permanent fix soon.

**Comment by leandroBorgesFerreira** [comment]
Thanks for the workaround

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by SanthoshMKunthe** [comment]
I tried your way but its giving error. . . Kindly help. . .

ERROR is as follows:
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()\n  if d.decorator_argspec is not None), _inspect.getargspec(target))\n2018-03-01 13:38:39.528159: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1184] Converting unsupported operation: VariableV2\n2018-03-01 13:38:39.528221: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1184] Converting unsupported operation: Assign\n2018-03-01 13:38:39.528268: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1184] Converting unsupported operation: VariableV2\n2018-03-01 13:38:39.528296: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1184] Converting unsupported operation: Assign\n2018-03-01 13:38:39.528333: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1184] Converting unsupported operation: Log\n2018-03-01 13:38:39.528438: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1184] Converting unsupported operation: DynamicStitch\n2018-03-01 13:38:39.528492: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1184] Converting unsupported operation: Reciprocal\n2018-03-01 13:38:39.528544: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1184] Converting unsupported operation: BroadcastGradientArgs\n2018-03-01 13:38:39.528589: F tensorflow/contrib/lite/toco/import_tensorflow.cc:1013] Check failed: GetBoolAttr(node, "transpose_b") == false (1 vs. 0)\nAborted (core dumped)\n'
None

CODE is as follows:

import tensorflow  as tf
import pandas as pd
import numpy as np
import tempfile
import subprocess
tf.contrib.lite.tempfile = tempfile
tf.contrib.lite.subprocess = subprocess

from tensorflow.python.tools import freeze_graph
from tensorflow.python.tools import optimize_for_inference_lib


print(tf.__version__)
data=pd.read_csv('iris.data',names=['f1','f2','f3','f4','f5'])

s=np.asarray([1,0,0])
ve=np.asarray([0,1,0])
vi=np.asarray([0,0,1])

data['f5']=data['f5'].map({'Iris-setosa':s,'Iris-versicolor':ve,'Iris-virginica':vi})

#print(data)

data=data.iloc[np.random.permutation(len(data))]

print(data)

data=data.reset_index(drop=True)

#training data
trainFeats=data.ix[0:105,['f1','f2','f3','f4']]
temp=data['f5']
trainlabels=temp[0:106]

y=tf.placeholder(tf.float32,shape=[106, 3])
#weight and bias
m=tf.Variable(tf.zeros([4,3]))
x=tf.placeholder(tf.float32,shape=[106,4],name="Input")
c=tf.Variable(tf.zeros([3]))
mxc = tf.nn.softmax((tf.matmul(x, m) + c) ,name="output")

loss = tf.reduce_mean(-tf.reduce_sum(y * tf.log(mxc), reduction_indices=[1]))

train_step = tf.train.AdamOptimizer(0.01).minimize(loss)

sess = tf.InteractiveSession()
init = tf.initialize_all_variables()
sess.run(init)


#_=tf.contrib.tflite.Convert(sess.graph_def,[x],[mxc])


#number of interations
epoch=2000
for step in range(epoch):
  print(sess.run([train_step,loss], feed_dict={x: trainFeats, y:[t for t in trainlabels.as_matrix()]}))

#testData=data.ix[130,['f1','f2','f3','f4']]
#testDataInFrormat=testData.reshape(1,4)
#print(sess.run(tf.argmax(mxc),feed_dict={x:testDataInFrormat}))

tf.train.write_graph(sess.graph_def,'pbtxtFiles/','savegraph.pbtxt',as_text=True)

tf.train.Saver().save(sess,'pbtxtFiles/model.ckpt')

# jajkhbdcjabjcbdskjbkcjbsakjbckjasbckjasbckajcsbakjcbaksjcbakjbcbsabcasbc,asbcjabscjkabsckjabckjbcs

# Freeze the graph
MODEL_NAME = 'iris'
input_graph_path = 'pbtxtFiles/savegraph.pbtxt'
checkpoint_path = 'pbtxtFiles/model.ckpt'
input_saver_def_path = ""
input_binary = False
output_node_names = "output"
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
output_frozen_graph_name = 'pbtxtFiles/frozen_model_'+MODEL_NAME+'.pb'
output_optimized_graph_name = 'pbtxtFiles/optimized_inference_model_'+MODEL_NAME+'.pb'
clear_devices = True

freeze_graph.freeze_graph(input_graph_path, input_saver_def_path,
                          input_binary, checkpoint_path, output_node_names,
                          restore_op_name, filename_tensor_name,
                          output_frozen_graph_name, clear_devices, "")


output_graph_def = optimize_for_inference_lib.optimize_for_inference(
        sess.graph_def,
        ["Input"], # an array of the input node(s)
        ["output"], # an array of output nodes
        tf.float32.as_datatype_enum)

tflite_model=tf.contrib.lite.toco_convert(sess.graph_def,[x],[mxc])
open("wow.tflite","w").write(tflite_model)

IRIS.DATA is this:

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
5.4,3.7,1.5,0.2,Iris-setosa
4.8,3.4,1.6,0.2,Iris-setosa
4.8,3.0,1.4,0.1,Iris-setosa
4.3,3.0,1.1,0.1,Iris-setosa
5.8,4.0,1.2,0.2,Iris-setosa
5.7,4.4,1.5,0.4,Iris-setosa
5.4,3.9,1.3,0.4,Iris-setosa
5.1,3.5,1.4,0.3,Iris-setosa
5.7,3.8,1.7,0.3,Iris-setosa
5.1,3.8,1.5,0.3,Iris-setosa
5.4,3.4,1.7,0.2,Iris-setosa
5.1,3.7,1.5,0.4,Iris-setosa
4.6,3.6,1.0,0.2,Iris-setosa
5.1,3.3,1.7,0.5,Iris-setosa
4.8,3.4,1.9,0.2,Iris-setosa
5.0,3.0,1.6,0.2,Iris-setosa
5.0,3.4,1.6,0.4,Iris-setosa
5.2,3.5,1.5,0.2,Iris-setosa
5.2,3.4,1.4,0.2,Iris-setosa
4.7,3.2,1.6,0.2,Iris-setosa
4.8,3.1,1.6,0.2,Iris-setosa
5.4,3.4,1.5,0.4,Iris-setosa
5.2,4.1,1.5,0.1,Iris-setosa
5.5,4.2,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
5.0,3.2,1.2,0.2,Iris-setosa
5.5,3.5,1.3,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
4.4,3.0,1.3,0.2,Iris-setosa
5.1,3.4,1.5,0.2,Iris-setosa
5.0,3.5,1.3,0.3,Iris-setosa
4.5,2.3,1.3,0.3,Iris-setosa
4.4,3.2,1.3,0.2,Iris-setosa
5.0,3.5,1.6,0.6,Iris-setosa
5.1,3.8,1.9,0.4,Iris-setosa
4.8,3.0,1.4,0.3,Iris-setosa
5.1,3.8,1.6,0.2,Iris-setosa
4.6,3.2,1.4,0.2,Iris-setosa
5.3,3.7,1.5,0.2,Iris-setosa
5.0,3.3,1.4,0.2,Iris-setosa
7.0,3.2,4.7,1.4,Iris-versicolor
6.4,3.2,4.5,1.5,Iris-versicolor
6.9,3.1,4.9,1.5,Iris-versicolor
5.5,2.3,4.0,1.3,Iris-versicolor
6.5,2.8,4.6,1.5,Iris-versicolor
5.7,2.8,4.5,1.3,Iris-versicolor
6.3,3.3,4.7,1.6,Iris-versicolor
4.9,2.4,3.3,1.0,Iris-versicolor
6.6,2.9,4.6,1.3,Iris-versicolor
5.2,2.7,3.9,1.4,Iris-versicolor
5.0,2.0,3.5,1.0,Iris-versicolor
5.9,3.0,4.2,1.5,Iris-versicolor
6.0,2.2,4.0,1.0,Iris-versicolor
6.1,2.9,4.7,1.4,Iris-versicolor
5.6,2.9,3.6,1.3,Iris-versicolor
6.7,3.1,4.4,1.4,Iris-versicolor
5.6,3.0,4.5,1.5,Iris-versicolor
5.8,2.7,4.1,1.0,Iris-versicolor
6.2,2.2,4.5,1.5,Iris-versicolor
5.6,2.5,3.9,1.1,Iris-versicolor
5.9,3.2,4.8,1.8,Iris-versicolor
6.1,2.8,4.0,1.3,Iris-versicolor
6.3,2.5,4.9,1.5,Iris-versicolor
6.1,2.8,4.7,1.2,Iris-versicolor
6.4,2.9,4.3,1.3,Iris-versicolor
6.6,3.0,4.4,1.4,Iris-versicolor
6.8,2.8,4.8,1.4,Iris-versicolor
6.7,3.0,5.0,1.7,Iris-versicolor
6.0,2.9,4.5,1.5,Iris-versicolor
5.7,2.6,3.5,1.0,Iris-versicolor
5.5,2.4,3.8,1.1,Iris-versicolor
5.5,2.4,3.7,1.0,Iris-versicolor
5.8,2.7,3.9,1.2,Iris-versicolor
6.0,2.7,5.1,1.6,Iris-versicolor
5.4,3.0,4.5,1.5,Iris-versicolor
6.0,3.4,4.5,1.6,Iris-versicolor
6.7,3.1,4.7,1.5,Iris-versicolor
6.3,2.3,4.4,1.3,Iris-versicolor
5.6,3.0,4.1,1.3,Iris-versicolor
5.5,2.5,4.0,1.3,Iris-versicolor
5.5,2.6,4.4,1.2,Iris-versicolor
6.1,3.0,4.6,1.4,Iris-versicolor
5.8,2.6,4.0,1.2,Iris-versicolor
5.0,2.3,3.3,1.0,Iris-versicolor
5.6,2.7,4.2,1.3,Iris-versicolor
5.7,3.0,4.2,1.2,Iris-versicolor
5.7,2.9,4.2,1.3,Iris-versicolor
6.2,2.9,4.3,1.3,Iris-versicolor
5.1,2.5,3.0,1.1,Iris-versicolor
5.7,2.8,4.1,1.3,Iris-versicolor
6.3,3.3,6.0,2.5,Iris-virginica
5.8,2.7,5.1,1.9,Iris-virginica
7.1,3.0,5.9,2.1,Iris-virginica
6.3,2.9,5.6,1.8,Iris-virginica
6.5,3.0,5.8,2.2,Iris-virginica
7.6,3.0,6.6,2.1,Iris-virginica
4.9,2.5,4.5,1.7,Iris-virginica
7.3,2.9,6.3,1.8,Iris-virginica
6.7,2.5,5.8,1.8,Iris-virginica
7.2,3.6,6.1,2.5,Iris-virginica
6.5,3.2,5.1,2.0,Iris-virginica
6.4,2.7,5.3,1.9,Iris-virginica
6.8,3.0,5.5,2.1,Iris-virginica
5.7,2.5,5.0,2.0,Iris-virginica
5.8,2.8,5.1,2.4,Iris-virginica
6.4,3.2,5.3,2.3,Iris-virginica
6.5,3.0,5.5,1.8,Iris-virginica
7.7,3.8,6.7,2.2,Iris-virginica
7.7,2.6,6.9,2.3,Iris-virginica
6.0,2.2,5.0,1.5,Iris-virginica
6.9,3.2,5.7,2.3,Iris-virginica
5.6,2.8,4.9,2.0,Iris-virginica
7.7,2.8,6.7,2.0,Iris-virginica
6.3,2.7,4.9,1.8,Iris-virginica
6.7,3.3,5.7,2.1,Iris-virginica
7.2,3.2,6.0,1.8,Iris-virginica
6.2,2.8,4.8,1.8,Iris-virginica
6.1,3.0,4.9,1.8,Iris-virginica
6.4,2.8,5.6,2.1,Iris-virginica
7.2,3.0,5.8,1.6,Iris-virginica
7.4,2.8,6.1,1.9,Iris-virginica
7.9,3.8,6.4,2.0,Iris-virginica
6.4,2.8,5.6,2.2,Iris-virginica
6.3,2.8,5.1,1.5,Iris-virginica
6.1,2.6,5.6,1.4,Iris-virginica
7.7,3.0,6.1,2.3,Iris-virginica
6.3,3.4,5.6,2.4,Iris-virginica
6.4,3.1,5.5,1.8,Iris-virginica
6.0,3.0,4.8,1.8,Iris-virginica
6.9,3.1,5.4,2.1,Iris-virginica
6.7,3.1,5.6,2.4,Iris-virginica
6.9,3.1,5.1,2.3,Iris-virginica
5.8,2.7,5.1,1.9,Iris-virginica
6.8,3.2,5.9,2.3,Iris-virginica
6.7,3.3,5.7,2.5,Iris-virginica
6.7,3.0,5.2,2.3,Iris-virginica
6.3,2.5,5.0,1.9,Iris-virginica
6.5,3.0,5.2,2.0,Iris-virginica
6.2,3.4,5.4,2.3,Iris-virginica
5.9,3.0,5.1,1.8,Iris-virginica

Kindly help MR. @aselle 
Kindly help MR. @facaiy 
Kindly help MR. @leandroBorgesFerreira 
Kindly help MR. @javierluraschi 
Kindly help MR. @tensorflowbutler

**Comment by SanthoshMKunthe** [comment]
above code is not giving any output. . . wow.tflite is not even created. . . Please help. . .

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by miaout17** [comment]
The tempfile issue is fixed in the newest code, but it wasn't released with TensorFlow 1.7.0 yet. 

You can choose to:

* Do the [workaround](https://github.com/tensorflow/tensorflow/issues/15410#issuecomment-352189481) mentioned above. 
* Use the TensorFlow nightly build (`pip uninstall tensorflow ; pip install tf-nightly`)
* [Build TensorFlow from source code](https://www.tensorflow.org/install/install_sources)
* Upgrade to the next TensorFlow release when it happens in the future. 

I'm closing this bug as the original issue was fixed. If you see other model conversion issue, please create a bug separately. Thanks!
