### ISSUE TITLE
Dependency on old version of bleach (1.5)

### ISSUE THREAD

**Issue by jmsdnns** [tensorflow/tensorflow#16424]
Bleach 1.5 came out Nov 4th 2016 and this is old enough to cause dependency issues for projects that stayed up to date with Bleach.

In particular, this causes issues for Jupyter users.

**Comment by jmsdnns** [comment]
Here is the relevant line: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_pip_packages.sh#L45

**Comment by scottdraves** [comment]
the problem comes when you install jupyter from conda-forge which has version 2.0 of bleach.
plain conda has version 1.5.

**Comment by tatianashp** [comment]
@jmsdnns Did @scottdraves suggestion solve your problem?

**Comment by jmsdnns** [comment]
no. tensorflow needs to update the versions of bleach that it depends on.

**Comment by zhiruiwang** [comment]
Not only bleach is outdated, also is html5lib . The newest version of html5lib on conda is 1.0.1, while tf is still using html5lib==0.9999999

**Comment by albertosantini** [comment]
@zhiruiwang `bleach` depends on `html5lib`. 

So it would be enough to update `bleach`.

Extract from `pipdeptree` command:
```
tensorflow==1.5.0
  - absl-py [required: >=0.1.6, installed: 0.1.9]
    - six [required: Any, installed: 1.11.0]
  - numpy [required: >=1.12.1, installed: 1.14.0]
  - protobuf [required: >=3.4.0, installed: 3.5.1]
    - setuptools [required: Any, installed: 38.4.0]
    - six [required: >=1.9, installed: 1.11.0]
  - six [required: >=1.10.0, installed: 1.11.0]
  - tensorflow-tensorboard [required: <1.6.0,>=1.5.0, installed: 1.5.0]
    - bleach [required: ==1.5.0, installed: 1.5.0]
      - html5lib [required: >=0.999,!=0.9999,!=0.99999,<0.99999999, installed: 0.9999999]
        - six [required: Any, installed: 1.11.0]
      - six [required: Any, installed: 1.11.0]
    - futures [required: >=3.1.1, installed: 3.1.1]
    - html5lib [required: ==0.9999999, installed: 0.9999999]
      - six [required: Any, installed: 1.11.0]
    - markdown [required: >=2.6.8, installed: 2.6.11]
    - numpy [required: >=1.12.0, installed: 1.14.0]
    - protobuf [required: >=3.4.0, installed: 3.5.1]
      - setuptools [required: Any, installed: 38.4.0]
      - six [required: >=1.9, installed: 1.11.0]
    - six [required: >=1.10.0, installed: 1.11.0]
    - werkzeug [required: >=0.11.10, installed: 0.14.1]
    - wheel [required: >=0.26, installed: 0.30.0]
    - wheel [required: Any, installed: 0.30.0]
  - wheel [required: >=0.26, installed: 0.30.0]
```

**Comment by gunan** [comment]
@jart FYI, you may want to bump bleach version in tensorboard dependencies.

**Comment by tatianashp** [comment]
I updated bleach dependency in the internal version. It should propagate to github in a day or two.

**Comment by jart** [comment]
Yes we'd love to update bleach and html5lib if they're bumped internally, which is easier said than done. Big breaking changes. We ideally need a way to vendor dependencies like these with histories of breakages inside our pip package, cf. `import pip._vendor.…`

**Comment by jart** [comment]
See also https://github.com/tensorflow/tensorboard/issues/588

**Comment by jart** [comment]
+cc nfelt@ chizeng@

**Comment by jart** [comment]
+cc @nfelt  @chihuahua

**Comment by zhiruiwang** [comment]
The TF 1.6 version on PyPI still has the bleach ==1.5.0 and html5lib ==0.9999999 dependency.

**Comment by sjentzsch** [comment]
... so does TF 1.7 ...

**Comment by pleabargain** [comment]
tensorboard 1.7.0 has requirement bleach==1.5.0, but you'll have bleach 2.1.3 which is incompatible.
tensorboard 1.7.0 has requirement html5lib==0.9999999, but you'll have html5lib 1.0.1 which is incompatible.

**Comment by zhiruiwang** [comment]
@tatianashp It seems like the dependency updates still have not be propagated to the github or PyPi version? Hope this can be resovled when tensorflow/tensorboard 1.8 is released.

**Comment by tatianashp** [comment]
I fixed dependency at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_pip_packages.sh#L45. But,  bleach 1.5.0 is still required by TensorBoard.

@jart - can you comment?

**Comment by jart** [comment]
The workaround should be to install within a virtualenv. This workaround shouldn't be necessary. It might not work in all situations. I'd like to fix this. TensorBoard can't upgrade to the more recent versions of these libraries. However I vendor (or shade) them inside our pip package. Let me take a look into seeing what's possible.

**Comment by isalirezag** [comment]
stupid question

What is the command to do it?

**Comment by nise** [comment]
So whats the solution for the issue?

**Comment by mangoocmt** [comment]
pip install bleach==1.5.0，then it is OK.

**Comment by nardeas** [comment]
Yeah, could we have some resolution to this? It's getting pretty annoying

**Comment by nfelt** [comment]
This issue is resolved.  TensorBoard stopped depending on Bleach nearly a year ago, and TensorFlow's only dependency on it was indirectly via TensorBoard.  Relatively recent versions of TensorFlow and TensorBoard don't have any dependency on Bleach at all.

**Comment by adamvvu** [comment]
FYI - the `conda` packages (tested `v2.9.1`) still have the dependency issue with `bleach==1.5.0`. Installing from `pip` works fine.
