### ISSUE TITLE
TensorFlowLite cannot locate symbol "__atomic_store_8" crash on Android x86 devices 

### ISSUE THREAD

**Issue by koAlech** [tensorflow/tensorflow#16589]
### System information

- **OS Platform and Distribution** : Android x86 v5.0+
- **TensorFlow installed from** : built using gradle from maven repository: https://google.bintray.com/tensorflow
- **TensorFlow version** : 1.2.0-rc0

### Describe the problem
We migrated our app to use tensorflow lite but it crashes on x86 upon invoking the inference module. It works perfect on ARM v7a devices.

### Source code / logs
Here's the exception:
```
01-15 03:39:47.138  2020  2056 W System.err: TensorFlowLite: failed to load native library: dlopen failed: cannot locate symbol "__atomic_store_8" referenced by "/data/app/com.XXXXXXX.XXXXXXXXXXXXXXXX-1/lib/x86/libtensorflowlite_jni.so"...
01-15 03:39:47.138  2020  2056 E art     : No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: FATAL EXCEPTION: XXXXXServiceThread
01-15 03:39:47.183  2020  2056 E AndroidRuntime: Process: com.XXXXXXX.XXXXXXXXXXXXXXXX, PID: 2020
01-15 03:39:47.183  2020  2056 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for long org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(int) (tried Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter and Java_org_tensorflow_lite_NativeInterpreterWrapper_createErrorReporter__I)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.createErrorReporter(Native Method)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:47)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:77)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at com.XXXXXXX.XXXXXXXXXXXXXXXX.utils.classifier.TensorflowLiteClassifier.<init>(TensorflowLiteClassifier.java:46)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at com.XXXXXXX.XXXXXXXXXXXXXXXX.service.classifier.TensorFlowFileClassifier.initialize(TensorFlowFileClassifier.java:41)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at com.XXXXXXX.XXXXXXXXXXXXXXXX.service.servicethread.ServiceThreadModel.onFileSystemScanStarted(ServiceThreadModel.java:92)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at com.XXXXXXX.XXXXXXXXXXXXXXXX.service.servicethread.ServiceThread$1.handleMessage(ServiceThread.java:82)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-15 03:39:47.183  2020  2056 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-15 03:39:47.1
```

**Comment by jmlipman** [comment]
I'm having the same issue, and I think it's because I haven't linked anything to the Android NDK I downloaded (I had my Android Studio installed and even tensorflow mobile worked for me). Might be that?  Still trying to figure out how to solve this.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by gabrielrlp** [comment]
+1

**Comment by petewarden** [comment]
Sorry for the delay on this one! From a bit of digging, it looks like it may be related to this issue:
https://github.com/alexa/avs-device-sdk/issues/380

In that case, it was resolved with an explicit addition of -latomic to the linker stage. Can you try editing build_def.bzl to add that flag:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/build_def.bzl#L48
In `def tflite_linkopts_unstripped()`, add `-Wl,-latomic` to the linker flags section.

**Comment by ant2n** [comment]
I have exactly the same issue, I added the dependency to the file build_def.bzl and the problem is still there. Once the line is added there is another thing that has to be done ?

**Comment by angersson** [comment]
@koAlech did @petewarden's suggestion fix your problem?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by koAlech** [comment]
I apologize for the slow response. We have failed in following @petewarden's suggestion as we are unsure how to build the aar file for tensorflow lite (as opposed to tensorflow mobile which we migrated from).

We have followed the [tfilte guide](https://www.tensorflow.org/mobile/tflite/devguide#android) and are using the latest build from the [bintray repository](https://google.bintray.com/tensorflow) (currently v0.1.1). 

Please advise how we should implement @petewarden's suggestion in this configuration.

**Comment by koAlech** [comment]
Update: tried the latest version (`0.1.8-rc0`) and it crashes with the same exception on x86 devices.

**Comment by andrehentz** [comment]
You can build tf lite's aar with:
bazel build -c opt --cxxopt=--std=c++11 \
    --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
    //tensorflow/contrib/lite/java:tensorflow-lite

**Comment by koAlech** [comment]
Tried @andrehentz solution but it failed to build an aar file. One tensorflowlibrary.jar file was built in the bazel-bin/tensorflow folder. Please advise

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 23 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 37 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 52 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 67 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by suharshs** [comment]
What is the exact command you ran (i.e. full bazel command)? What version of the sdk did you run it on? Were there any errors produced?

**Comment by koAlech** [comment]
@suharshs I was about to paste the entire bazel command we used in order to build tflite from source but then realized that a new version (1.9.0) was released and decided to give it a try.
And surprisingly this issue was resolved! We're so happy!
