### ISSUE TITLE
seg fault in 1.6rc0 and master on skylake cpu (avx512 related probably)

### ISSUE THREAD

**Issue by bioothod** [tensorflow/tensorflow#17043]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
Built from source
- **TensorFlow version (use command below)**:
v1.6.0-rc0-19-gecec1d8 1.6.0-rc1
master
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: 0.10.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.1.85/7.0.5.15
- **GPU model and memory**:
GeForce GTX 1080 Ti
totalMemory: 10.91GiB freeMemory: 8.36GiB

### Describe the problem

If tf1.6 is compiled with `--march=native` then running inference on a large model ends up with crash with cryptic stack trace, 100% reproducible, no matter with or without CUDA (whether CUDA_VISIBLE_DEVICES="" or absent).

If compiled **without** avx512 support (i.e. `-O3 -msse4.2 -mavx2 -mfma` only), then everything works fine.
TF emits a warning though:
```
2018-02-15 14:03:54.237530: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX512F
```

I checked another issue with 64 byte alignment (https://github.com/tensorflow/tensorflow/issues/15588), but it does not help.

Here is a crash trace, if it may help.
```
(gdb) bt
#0  0x00007fdea3c5c9d5 in Eigen::internal::gemm_pack_lhs<float, long, Eigen::internal::TensorContractionSubMapper<float, long, 1, Eigen::TensorEvaluator<Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, 48, 16, 0, false, false>::operator()(float*, Eigen::internal::TensorContractionSubMapper<float, long, 1, Eigen::TensorEvaluator<Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer> const&, long, long, long, long) () from /home/zbr/.local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#1  0x00007fdea3cd0fc4 in Eigen::TensorEvaluator<Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer> const> const, Eigen::ThreadPoolDevice>::Context<Eigen::internal::gemm_pack_lhs<float, long, Eigen::internal::TensorContractionSubMapper<float, long, 1, Eigen::TensorEvaluator<Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, 48, 16, 0, false, false>, Eigen::internal::gemm_pack_rhs<float, long, Eigen::internal::TensorContractionSubMapper<float, long, 0, Eigen::TensorEvaluator<Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, 4, 0, false, false>, Eigen::internal::gebp_kernel<float, float, long, Eigen::internal::blas_data_mapper<float, long, 0, 0>, 48, 4, false, false>, Eigen::internal::TensorContractionInputMapper<float, long, 1, Eigen::TensorEvaluator<Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, Eigen::internal::TensorContractionInputMapper<float, long, 0, Eigen::TensorEvaluator<Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer> const, Eigen::ThreadPoolDevice>, Eigen::array<long, 1ul>, Eigen::array<long, 1ul>, 16, true, false, 0, Eigen::MakePointer>, Eigen::internal::blas_data_mapper<float, long, 0, 0> >::enqueue_packing_helper(long, long, long, bool) ()
   from /home/zbr/.local/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#2  0x00007fdea06232d1 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /home/zbr/.local/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
#3  0x00007fdea06210e7 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /home/zbr/.local/lib/python3.5/site-packages/tensorflow/python/../libtensorflow_framework.so
#4  0x00007fde96afbc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fded77d76ba in start_thread (arg=0x7fdeb87d8700) at pthread_create.c:333
#6  0x00007fded750d41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)
```

**Comment by bioothod** [comment]
I tried this patch for avx512 alignment, but it doe not help

```
--- a/tensorflow/core/framework/allocator.h
+++ b/tensorflow/core/framework/allocator.h
@@ -67,13 +67,8 @@ struct AllocatorStats {
 // device memory.
 class Allocator {
  public:
-#ifdef EIGEN_VECTORIZE_AVX512
   // Align to 64 byte boundary.
   static constexpr size_t kAllocatorAlignment = 64;
-#else
-  // Align to 32 byte boundary.
-  static constexpr size_t kAllocatorAlignment = 32;
-#endif
```

**Comment by bioothod** [comment]
```
(gdb) x/i $rip
=> 0x7f77386da175 <_ZN5Eigen8internal13gemm_pack_lhsIflNS0_26TensorContractionSubMapperIflLi1ENS_15TensorEvaluatorIKNS_17TensorReshapingOpIKNS_6DSizesIlLi2EEEKNS_9TensorMapINS_6TensorIKfLi4ELi1ElEELi16ENS_11MakePointerEEEEENS_16ThreadPoolDeviceEEENS_5arrayIlLm1EEESK_Li16ELb1ELb0ELi0ESC_EELi48ELi16ELi0ELb0ELb0EEclEPfRKSL_llll+485>:	vmovaps %zmm0,-0x40(%r10)
(gdb) 
```

**Comment by bioothod** [comment]
`-0x40(%r10)` - this looks definitely like 64bit alignment issue

**Comment by bioothod** [comment]
another trace:
```
vmovaps %zmm2,-0xc0(%rdx)
p/x $rdx
$1 = 0x7f7b9400f8a0
```

0x7f7b9400f8a0 - 0xc0 = 140168740796384, which is aligned to 32 and not 64.
SO far I changed every occurence of EIGEN_MAX_ALIGN_BYTES, but it leaks somewhere else.
```
	modified:   tensorflow/c/c_api.cc
	modified:   tensorflow/core/common_runtime/gpu/gpu_device.cc
	modified:   tensorflow/core/framework/allocator.h
	modified:   tensorflow/core/framework/tensor.h
	modified:   tensorflow/core/kernels/ops_util.h
	modified:   tensorflow/python/lib/core/py_func.cc
```

**Comment by bioothod** [comment]
Here is a problem description to date:
* external eigen is being compiled with the native instruction set, which implies using avx512 on skylake cpus
* external eigen somehow misses the fact that `EIGEN_VECTORIZE_AVX512` has to be defined, probably because it does not see `__AVX512F__` although it sees `__AVX2__` define (how?)
* since there is no `EIGEN_VECTORIZE_AVX512`, eigen sets 32-byte alignment for avx2
* since native instructions are used, `vmovaps` is injected, which faults on unaligned (32-byte aligned) chunks allocated via internal eigen compiler

Rudely adding `--copt=-DEIGEN_VECTORIZE_AVX512` ends up with error in `Eigen/src/Core/arch/SSE/PacketMath.h:260` and other places where compiler does not see correct instructions anymore, probably setting up this define breaks detection of the other options.

Changing `EIGEN_IDEAL_MAX_ALIGN_BYTES` in `Eigen/src/Core/util/Macros.h` to 64 works fine.

**Comment by bioothod** [comment]
Following patch fixes segmentation fault, but network produces garbage outputs, disabling avx512 fixes this

```
diff --git a/third_party/eigen.BUILD b/third_party/eigen.BUILD
index 07bb664..b88d9ca 100644
--- a/third_party/eigen.BUILD
+++ b/third_party/eigen.BUILD
@@ -64,6 +64,7 @@ cc_library(
         # This define (mostly) guarantees we don't link any problematic
         # code. We use it, but we do not rely on it, as evidenced above.
         "EIGEN_MPL2_ONLY",
+       "EIGEN_MAX_ALIGN_BYTES=64"
     ],
     includes = ["."],
     visibility = ["//visibility:public"],
```

**Comment by bioothod** [comment]
This can also be a gcc bug (there is even no skylake march option in this compiler), in this case there should be a way to disable avx512 support for older compilers.

I've sent a mail to eigen devel list describing this problem.

**Comment by agdownes** [comment]
I'm having the same issue. Is compiling without avx512 the best option at the moment? Could you please explain the "-O3 -msse4.2 -mavx2 -mfma" options for me and when to add them in the build process?

**Comment by bioothod** [comment]
When you specify only these options, compiler will not use other instructions available on your processor, in particular it will not use AVX512 instructions which require additional support from TF and/or Eigen library. Also, avx512 support can be broken on older compilers and this is likely the case for ubuntu 16.04 and its eldery 5.4.0 gcc

**Comment by bioothod** [comment]
Upgrading to gcc 6.3.0 does not fix this issue, neither with allocator alignment nor with eigen one. Patch below fixes misalignment segfault, but network still produces garbage. Removing avx512 instructions (i.e. only using avx2, sse4.2 and mfma) fixes the problem.

```
diff --git a/tensorflow/core/framework/allocator.h b/tensorflow/core/framework/allocator.h
index 5a95d3a..4e5bc66 100644
--- a/tensorflow/core/framework/allocator.h
+++ b/tensorflow/core/framework/allocator.h
@@ -67,13 +67,8 @@ struct AllocatorStats {
 // device memory.
 class Allocator {
  public:
-#ifdef EIGEN_VECTORIZE_AVX512
   // Align to 64 byte boundary.
   static constexpr size_t kAllocatorAlignment = 64;
-#else
-  // Align to 32 byte boundary.
-  static constexpr size_t kAllocatorAlignment = 32;
-#endif
 
   virtual ~Allocator();
 
diff --git a/third_party/eigen.BUILD b/third_party/eigen.BUILD
index 07bb664..ffe8a43 100644
--- a/third_party/eigen.BUILD
+++ b/third_party/eigen.BUILD
@@ -64,6 +64,7 @@ cc_library(
         # This define (mostly) guarantees we don't link any problematic
         # code. We use it, but we do not rely on it, as evidenced above.
         "EIGEN_MPL2_ONLY",
+       "EIGEN_MAX_ALIGN_BYTES=64",
     ],
     includes = ["."],
     visibility = ["//visibility:public"],
```

**Comment by gunan** [comment]
avx512 support is still not official. But We would greatly appreciate any fixes, if you can pinpoint the problem.

**Comment by bjascob** [comment]
I'll add to this old post and say I'm seeing intermittent segfaults and system lockups simply importing Tensorflow compiled using march=native on a SkylakeX (i7-7940).  Recompiling with march="haswell" eliminates the issue.  While I can't say for sure this is an AVX-512 issue, that seem like a top candidate given the limited difference in flags.

Because of the intermittent nature, this was difficult to diagnose and it wasn't obvious that recompiling with different flags would fix the issue.  If AVX-512 isn't working/supported it would be helpful if a warning appeared in the docs or configure script to alert people of the potential danger.

**Have I written custom code:** No
**OS Platform and Distribution:** Ubuntu 18.04.1
**TensorFlow:** Build from source
**TensorFlow version:** 1.12rc1
**Python version:** 3.6.6
**Bazel version**: 0.18.0
**GCC/Compiler version:** 7.3.0
 **CUDA/cuDNN version:** 10.0
**GPU model and memory:** TitanX(maxwell) 12GB

**Comment by gunan** [comment]
I don't think we still test or verify TF on skylake, so this is still expected.
We will probably switch to using MKL before we switch to compiling with avx512.

**Comment by markdryan** [comment]
It might be worth retrying the AVX512 builds on master.  The recent Eigen updates have pulled a number of AVX512 specific fixes into TensorFlow master that were not present in 1.12.  In particular, #21265, #20373, #18676 are now fixed.  #21265 is the most significant of these.  Prior to the fix for #21265, tensor contraction was broken on AVX512 builds and many of the examples simply didn't work.

From the standpoint of the unit tests (1), the only failures specific to the AVX512 builds I see on master right now are the embedding_ops tests (see #21676).  The issue here is with the test cases themselves and not the underlying code.  There's a PR pending ( #21677 ) that fixes these unit tests.

(1) The unit tests as run with bazel test --config opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/... -//tensorflow/lite/...

**Comment by bioothod** [comment]
Looks good for me, I disabled unit tests and XLA which do not compile, so far I do not see crashes I previously observed in tests in like 0-30 seconds after the start.

As a side note, NN inference performance dropped by 10% compared to 1.11 release (manually specifying all flags instead of --march=native). This could or could not be related to xla/avx512 or master build.

**Comment by bioothod** [comment]
No, the problem persists. And actually it has been made quite different: code does not crash anymore, but the output result is heavily wrong (compared to gpu calculation or cpu with avx512 turned off).

The good thing is that running rather large network produce different output each time, so this can be a sign or test, if the output would have been the same (but wrong) it could've been much harder to catch.

This is basically a large classification cnn which produces slightly different (within several percents) results with each run for the same input.

**Comment by markdryan** [comment]
@bioothod Are you testing on the latest version of master or on a release branch?

**Comment by bioothod** [comment]
The latest commit was 8855358, so it is master of Dec 10

**Comment by markdryan** [comment]
So you should have the latest changes.  Could you possibly run

bazel test --config=opt --cache_test_results=no -- //tensorflow/python/kernel_tests:conv_ops_test

on your local setup to see whether it passes or not?

**Comment by bioothod** [comment]
4 tests have failed, logs have been attached, but they tested cuda

```
INFO: Analysed target //tensorflow/python/kernel_tests:conv_ops_test (0 packages loaded).
INFO: Found 1 test target...
FAIL: //tensorflow/python/kernel_tests:conv_ops_test (shard 3 of 4) (see /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_3_of_4/test.log)
FAIL: //tensorflow/python/kernel_tests:conv_ops_test (shard 2 of 4) (see /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_2_of_4/test.log)
FAIL: //tensorflow/python/kernel_tests:conv_ops_test (shard 4 of 4) (see /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_4_of_4/test.log)

FAILED: //tensorflow/python/kernel_tests:conv_ops_test (Summary)
      /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_3_of_4/test.log
      /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_2_of_4/test.log
      /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_4_of_4/test.log
      /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_1_of_4/test.log
FAIL: //tensorflow/python/kernel_tests:conv_ops_test (shard 1 of 4) (see /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_1_of_4/test.log)
Target //tensorflow/python/kernel_tests:conv_ops_test up-to-date:
  bazel-bin/tensorflow/python/kernel_tests/conv_ops_test
INFO: Elapsed time: 2.130s, Critical Path: 1.89s
INFO: 4 processes: 4 local.
INFO: Build completed, 1 test FAILED, 5 total actions
//tensorflow/python/kernel_tests:conv_ops_test                           FAILED in 4 out of 4 in 1.9s
  Stats over 4 runs: max = 1.9s, min = 1.7s, avg = 1.8s, dev = 0.1s
  /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_3_of_4/test.log
  /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_2_of_4/test.log
  /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_4_of_4/test.log
  /home/zbr/.cache/bazel/_bazel_zbr/fca2d89a068104ec3ae07b293c9e9c36/execroot/org_tensorflow/bazel-out/k8-opt/testlogs/tensorflow/python/kernel_tests/conv_ops_test/shard_1_of_4/test.log
```

Attached in the same order as above
[test.log](https://github.com/tensorflow/tensorflow/files/2672199/test.log)
[test.log](https://github.com/tensorflow/tensorflow/files/2672201/test.log)
[test.log](https://github.com/tensorflow/tensorflow/files/2672202/test.log)
[test.log](https://github.com/tensorflow/tensorflow/files/2672203/test.log)

**Comment by mohantym** [comment]
Hi @bioothod !It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Attaching relevant threads for reference. [link](https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u). Thanks!

**Comment by yuliya-patotskaya** [comment]
@mohantym it's really nice of you to wait for 2 years and then comment that it is an outdated version, good job!
