### ISSUE TITLE
TF1.6 MKL bug in concatenation op

### ISSUE THREAD

**Issue by mas-dse-greina** [tensorflow/tensorflow#17494]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux CentOS 7
- **TensorFlow installed from (source or binary)**: Binary (Intel MKL wheel) https://software.intel.com/en-us/articles/intel-optimized-tensorflow-wheel-now-available
- **TensorFlow version (use command below)**: b'unknown' 1.6.0
- **Python version**: 3.6 
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:
U-Net model graph compiles but error during training from concatenation op.
The code is here: https://github.com/mas-dse-greina/unet/blob/master/train.py

You can collect some of this information using our environment capture script:
== cat /etc/issue ===============================================
Linux lancelot24 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux lancelot24 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.14.1)
protobuf (3.5.1)
tensorflow (1.6.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.6.0
tf.GIT_VERSION = v1.6.0-0-gd2e24b6039
tf.COMPILER_VERSION = v1.6.0-0-gd2e24b6039
Sanity check: array([1], dtype=int32)
/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./p.sh: line 105: nvidia-smi: command not found

== cuda libs  ===================================================

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

This is a bug in the TensorFlow 1.6. I am using the Intel-supplied pip wheel for MKL optimization. I ran the same code with the TF1.4 MKL wheel and my code worked just fine. The error messages indicate that there is a problem with the concatenation operation. I am not seeing this error with the generic TensorFlow 1.6 (i.e. pip install tensorflow). I believe it is limited to the MKL op for concatenation.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

WARNING:tensorflow:Variable *= will be deprecated. Use variable.assign_mul if you want assignment to the variable value or 'x = x * y' if you want a new python Tensor object.
Train on 24800 samples, validate on 6200 samples
Epoch 1/10
Traceback (most recent call last):
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:777
	 [[Node: concatenate/concat = _MklConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](transConv6/BiasAdd, conv4b/Relu, concatenate/concat/axis, DMT/_29, conv4b/Relu:1, DMT/_30)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 571, in <module>
    settings.OUT_CHANNEL_NO, settings.MODEL_FN, settings.MODE, args)
  File "train.py", line 510, in train_and_predict
    callbacks=[model_checkpoint, tensorboard_checkpoint])
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1793, in fit
    validation_steps=validation_steps)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1283, in _fit_loop
    outs = f(ins_batch)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2663, in __call__
    fetches=fetches, feed_dict=feed_dict, **self.session_kwargs)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:777
	 [[Node: concatenate/concat = _MklConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](transConv6/BiasAdd, conv4b/Relu, concatenate/concat/axis, DMT/_29, conv4b/Relu:1, DMT/_30)]]

Caused by op 'concatenate/concat', defined at:
  File "train.py", line 571, in <module>
    settings.OUT_CHANNEL_NO, settings.MODEL_FN, settings.MODE, args)
  File "train.py", line 443, in train_and_predict
    model = model5_MultiLayer(args, False, False, img_rows, img_cols, input_no, output_no, print_summary=True)
  File "train.py", line 183, in model5_MultiLayer
    kernel_size=(3, 3), strides=(2, 2), padding='same')(conv5), conv4], axis=concat_axis)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/merge.py", line 665, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/merge.py", line 174, in call
    return self._merge_function(inputs)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/merge.py", line 380, in _merge_function
    return K.concatenate(inputs, axis=self.axis)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/backend.py", line 2083, in concatenate
    return array_ops.concat([to_dense(x) for x in tensors], axis)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1175, in concat
    return gen_array_ops._concat_v2(values=values, axis=axis, name=name)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 625, in _concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/bduser/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

AbortedError (see above for traceback): Operation received an exception:Status: 3, message: could not create a concat primitive descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:777
	 [[Node: concatenate/concat = _MklConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](transConv6/BiasAdd, conv4b/Relu, concatenate/concat/axis, DMT/_29, conv4b/Relu:1, DMT/_30)]]

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gzmkl** [comment]
Need to access "data" to reproduce the issue with "train.py".

**Comment by mas-dse-greina** [comment]
Please see the new test benchmark script which shows the issue:
https://github.com/NervanaSystems/topologies/tree/master/memory_benchmarking

I created a test bench with random data that will show the same issue. Note
that I am using the Intel-built TensorFlow MKL wheel and only using CPU to
train. The issue seems to be in the concatenation of step.

Just run the command `python benchmark_model.py --num_datapoints=10 --D2
--dim_length=128` and it should show the error in TF1.6 MKL.

Error:

(tf) [user@node17 memory_benchmarking]$ python benchmark_model.py
--num_datapoints=10 --D2 --dim_length=128
Using TensorFlow backend.

Args = Namespace(D2=True, blocktime=0, bz=1, dim_length=128, epochs=3,
interop_threads=2, intraop_threads=67, lr=0.001, mkl_verbose=False,
num_channels=1, num_datapoints=10, num_outputs=1, print_model=False,
single_class_output=False, use_upsampling=False)
2D U-Net Segmentation
  0%|
                                                                          |
0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "benchmark_model.py", line 208, in <module>
    options=run_options, run_metadata=run_metadata)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/client/session.py",
line 905, in run
    run_metadata_ptr)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/client/session.py",
line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/client/session.py",
line 1355, in _do_run
    options, run_metadata)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/client/session.py",
line 1374, in _do_call
    raise type(e)(node_def, op, message)
*tensorflow.python.framework.errors_impl.AbortedError: Operation received
an exception:Status: 3, message: could not create a concat primitive
descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:777*
* [[Node: concatenate_1/concat = _MklConcatV2[N=2, T=DT_FLOAT,
Tidx=DT_INT32, _kernel="MklOp",
_device="/job:localhost/replica:0/task:0/device:CPU:0"](transConv6/BiasAdd,
conv4b/Relu, concatenate_1/concat/axis, DMT/_29, conv4b/Relu:1, DMT/_30)]]*

Caused by op u'concatenate_1/concat', defined at:
  File "benchmark_model.py", line 161, in <module>
    print_summary=args.print_model, n_out=args.num_outputs)
  File "/home/user/topologies/memory_benchmarking/model.py", line 177, in
unet2D
    kernel_size=(2, 2), strides=(2, 2), padding="same")(conv5), conv4],
axis=concat_axis)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/keras/layers/merge.py",
line 627, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/keras/engine/topology.py",
line 603, in __call__
    output = self.call(inputs, **kwargs)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/keras/layers/merge.py",
line 347, in call
    return K.concatenate(inputs, axis=self.axis)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py",
line 1768, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py",
line 1175, in concat
    return gen_array_ops._concat_v2(values=values, axis=axis, name=name)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py",
line 625, in _concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py",
line 787, in _apply_op_helper
    op_def=op_def)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py",
line 3271, in create_op
    op_def=op_def)
  File
"/home/user/miniconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py",
line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint:
disable=protected-access

AbortedError (see above for traceback): Operation received an
exception:Status: 3, message: could not create a concat primitive
descriptor, in file tensorflow/core/kernels/mkl_concat_op.cc:777
*[[Node: concatenate_1/concat = _MklConcatV2[N=2, T=DT_FLOAT,
Tidx=DT_INT32, _kernel="MklOp",
_device="/job:localhost/replica:0/task:0/device:CPU:0"](transConv6/BiasAdd,
conv4b/Relu, concatenate_1/concat/axis, DMT/_29, conv4b/Relu:1, DMT/_30)]]*


Thanks.
-Tony

**Comment by gzmkl** [comment]
Thank you Tony. I can reproduce the issue now.

**Comment by mas-dse-greina** [comment]
Thank you!

-Tony

**Comment by gzmkl** [comment]
Found the root cause and had the fix.  

A new PR will be created once internal code review and validations are done.

**Comment by mas-dse-greina** [comment]
Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatatodd: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mas-dse-greina** [comment]
I still see the bug in 1.7 and the 1.8 rc1. Can you confirm that the fix has been merged into those? 

Thanks.
-Tony

**Comment by gzmkl** [comment]
Hi Tony,

It is not merged yet, as we are handling other concat related issues (e.g. empty tensor with ndims=0 as input).
I will let you when we are ready for public PR.

Thanks,
GZ

**Comment by mas-dse-greina** [comment]
Many thanks.

I've also discovered on building from the latest source that data_format
gives an error because one MKL op is trying to use "NDCHW" as the value. I
assume that has been reported but wanted to let you know.

Thanks so much to the team for the great work.

**Comment by wenouyang** [comment]
Hi gzmkl, I rolled back tensorflow version to 1.6 and still has the problem, the python version is 3.5. Thanks.

**Comment by gztf** [comment]
There is no public PR yet. I have tested my private branch with tony's code
    https://github.com/NervanaSystems/topologies/tree/master/memory_benchmarking
The issue should be fixed. Thank you patient for waiting. I will drive hard to make the fix merged to public branch

**Comment by wenouyang** [comment]
Hi gztf, thanks for the reply. I rolled back to 1.5, looks like it can be fixed.

**Comment by Shyphone** [comment]
I have tried 1.6.0 and 1.7.0(GPU version, anaconda install), they all show MKL bug;
while in 1.5.0, this bug disappear.

**Comment by cslxiao** [comment]
Same Problem with tensorflow 1.6 and python 3.5

**Comment by mas-dse-greina** [comment]
Thanks GZ. So if I download and build TensorFlow from source, then this
should be included in the MKL?

Best,
-Tony

**Comment by gztf** [comment]
Hi Tony,
Yes, the fix is already in public TF GitHub. Before submitting that PR, I had already validated with
your code. Please let me know the result once you try. 
-Guozhong

**Comment by gztf** [comment]
Tony,
Another info to you: we are preparing another PR to migrate to the latest MKL-DNN (v0.14).
The new DNN improves concat op performance
     1. old DNN concat only had jit implementation when concat dim is 'C" (that is, "Channel" dimension)
     2. new DNN concat has jit implementation for any concat dim
So hopefully you can see performance improvement once that PR is in.
-GZ

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tonywang1990: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gztf** [comment]
The fix has been merged to public Tensorflow master branch. 
You will need to switch TF 1.8

**Comment by GitHubRajaGopal** [comment]
All, I am still facing the same issue when I use the wheel from TF source code compile. I did 'git checkout r1.8' before the compile. Please help me. Thank you.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tonywang1990: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tonywang1990: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by GitHubRajaGopal** [comment]
I am still facing the same, hence working on lower version of TF.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tonywang1990: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tonywang1990: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by mas-dse-greina** [comment]
It's been fixed. Please close.

Thanks

**Comment by libinta** [comment]
Hi,
What's the tensorflow version with this fix?
Thanks.

**Comment by mas-dse-greina** [comment]
1.9 and above

**Comment by libinta** [comment]
I still see the issue on 1.10. can you share which commit fixed this issue?thanks

**Comment by 07freedom** [comment]
Well somehow I still got this error in 1.19 but fixed with 1.10. You guys can give it a shot

**Comment by mrsabhar** [comment]
Any update on this issue? I did try MKLDNN 0.14, 0.15 and 0.16 with TF1.9 and 1.10 but both gives same erro.

**Comment by gzmkl** [comment]
@mrsabhar 
Maybe you should create a new item, with procedure of how to reproduce the problem. 
Tony has confirmed that his issue (with procedure) has been fixed. Thanks!

**Comment by mas-dse-greina** [comment]
Yes. That would be very helpful. Would you have a simple python script that
shows the behavior?

One thing to try: TF with MKL-DNN is now the default in the Anaconda repo.
So try just 'conda install -c ananconda tensorflow'. And see if it works


Best,
Tony

**Comment by coreyjadams** [comment]
I am also seeing this issue, using tensorflow 1.11, intelpython35, running on Intel Xeon Phi KNL.

I can reliably reproduce the error on the system I am using with the script here:
https://gist.github.com/coreyjadams/35e89feb1fb191c2788792f6268448fc

This is using the tensorflow downloaded from intel here: https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide (I took the version matching python 3.5)

I noticed, by the way, that the convolutions before the concat operation were necessary for this crash to happen.  Without the convolution ops, this script runs fine.

**Comment by kalsan** [comment]
The bug also occurs when trying to use https://github.com/lmb-freiburg/hand3d, with tensorflow 1.11 and python 3.6.6 (anaconda).

@mas-dse-greina : 
> So try just 'conda install -c ananconda tensorflow'. And see if it works

The user anaconda does not seem to exist any longer, the command fails with 404

**Comment by urimerhav** [comment]
+1 on this issue still being observed in tensorflow 1.11.0, usimg intel's mkl compatible tensorflow dstribution, running on ubuntu16 CPU-only machine

**Comment by coreyjadams** [comment]
I have opened a new issue (#23556 ) since I don't have the power to reopen this one, but I think there are still lingering problems regarding this concat op.

**Comment by agramesh1** [comment]
This issue was fixed recently and merged into the master https://github.com/tensorflow/tensorflow/pull/22606  Please let us know if this fixes your problems.

**Comment by eLvErDe** [comment]
Hi there,

Fixed the origina issue but now crashes later (in a part of code that looks like using mkl concat):

```
AbortedError (see above for traceback): Operation received an exception:Status: 5, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:652
	 [[Node: conv1/BiasAdd = _MklConv2DWithBias[T=DT_FLOAT, _kernel="MklOp", data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_1_0_0, conv1/kernel/read, conv1/bias/read, DMT/_0, DMT/_1, DMT/_2)]]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/usr/lib/python3/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 5, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:652
	 [[Node: conv1/BiasAdd = _MklConv2DWithBias[T=DT_FLOAT, _kernel="MklOp", data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_input_1_0_0, conv1/kernel/read, conv1/bias/read, DMT/_0, DMT/_1, DMT/_2)]]
```

**Comment by gzmkl** [comment]
ELvErDe,

I verified the original issue has been addressed (with master build) with coreyjadams's test script.
Would you please provide a new test script for the "later crash"? I will troubleshoot the problem.

Thanks!

**Comment by coreyjadams** [comment]
I mentioned on the other issue as well, but I can confirm my test script works with the master build.

**Comment by eLvErDe** [comment]
[mkl_conv_ops_cc_mkl_bug.zip](https://github.com/tensorflow/tensorflow/files/2581462/mkl_conv_ops_cc_mkl_bug.zip)

Hello,

The error message is:
```
2018-11-14 16:42:55.167116: I tensorflow/core/common_runtime/process_util.cc:63] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2018-11-14 16:43:00.480740: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at mkl_conv_ops.cc:697 : Aborted: Operation received an exception:Status: 5, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:694
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/lib/python3/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 5, message: could not initialize a memory descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:694
	 [[Node: FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/BatchNorm/FusedBatchNorm = _MklConv2DWithBias[T=DT_FLOAT, _kernel="MklOp", data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d/depthwise, FeatureExtractor/InceptionV2/Conv2d_1a_7x7/pointwise_weights/read/_94__cf__97, FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d_bn_offset, DMT/_61, DMT/_62, DMT/_63)]]
```

Attached ZIP file contain a few line script reproducing the error (i'll care itself downloading a model) and a test image for inference.
Running it with my MKL build fails, with a non MKL build it works fine.

I'm actually thinking this is related to MKL-DNN version *at build time* because my  1.5.1 were build using 0.13 I guess and newer with 0.16. I'm pretty confident building new TF with old MKL-DNN will make it work....

Thanks for your help,

Adam.

**Comment by eLvErDe** [comment]
@gzmkl

**Comment by gzmkl** [comment]
Thank you for providing the test script. I will look into the issue soon

**Comment by gzmkl** [comment]
Hi,
I test with your code with 
   1. latest Tensorflow -- build from Tensorflow master branch
   2. MKL DNN v0.16
and do not see the issue.
Please check the attached test results. 
[test_results.txt](https://github.com/tensorflow/tensorflow/files/2582193/test_results.txt)

**Comment by eLvErDe** [comment]
Hi,

Any hope you can try with 1.8 ? I confirmed the issue with 1.6/1.7/1.8 and haven't checked yet newer

**Comment by gzmkl** [comment]
I defined saw this issue before but I am not sure when this issue was fixed (no clue by 
browsing through pull request history). 

Please try a newer Tensorflow version 1.11 or 1.12 (?).
Thanks!

**Comment by eLvErDe** [comment]
Sh*** I couldn't either and really hoped to be able to release a working 1.6 TF :/

**Comment by eLvErDe** [comment]
Well, I will but each new version break something for us until I backport a couple of patches so I'd go easy with updates, step by step. I'm trying MKL downgrade at build time, I suspect TF may disable this broken operation using MKL lib if it is old enough when building. Also I'll build 1.9 but I'm sure the same issue will be there (among other maybe ;))

**Comment by gzmkl** [comment]
The cause of the issue might not be due to a specific MKL DNN version. 
Most likely it was due to some bug when we was doing Tensorflow integration.

**Comment by eLvErDe** [comment]
Confirmed !

My feeling was right, rebuilding with MKL 0.13 and the bug is gone. Runtime version of MKL does not matter but there is definitely something happening during build regarding MKL version....

Still interrested in digging deeper ?

**Comment by zyong812** [comment]
I still have the problem for tensorflow 1.12, install with conda. How to fix it?

**Comment by zyong812** [comment]
I still have the problem for tensorflow 1.12, installed with conda. How to fix it?

**Comment by rivergold** [comment]
I also meet this problem when using TensorFLow 1.12 installed with conda.
```
tensorflow 1.12.0 mkl_py36h69b6ba0_0 
```
Is there any solution?

**Comment by appyfizzA** [comment]
I did "conda update conda" and "conda update mkl". But I'm still getting the error. 
I'm using python 3.6, tensorflow 1.9
Please help

**Comment by BigSteve94** [comment]
Dear all,

I am still having the problem on tensorflow 1.12 with python 3.6 (anaconda). How can I fix this?

**Comment by ae137** [comment]
This bug, or at least a very related bug, is still open in Tensorflow 1.14. The concatenate operation leads to the error "operation received an exception:Status: 5, message: could not create a view primitive descriptor, in file tensorflow/core/kernels/mkl_slice_op.cc:433" for the mkl package (tensorflow=1.14.0=mkl_py37h45c423b_0 from anaconda). After installing the eigen package from anaconda (tensorflow=1.14.0=eigen_py37h195cb1b_0), the error does not appear. I have attached an example program where the error appears and the printed error message
[bug_concatenate_mkl.zip](https://github.com/tensorflow/tensorflow/files/3390398/bug_concatenate_mkl.zip)
.
