### ISSUE TITLE
Mac OS X Python 3.5 binary runtime warning for Tensorflow 1.5.0+

### ISSUE THREAD

**Issue by binoche9** [tensorflow/tensorflow#18850]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS X 10.13.4
- **TensorFlow installed from (source or binary)**: binary (or whatever pip is)
- **TensorFlow version (use command below)**: 1.5.0+
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: 8GB CPU
- **Exact command to reproduce**: `python -c "import tensorflow"`

### Describe the problem

I seem to have the opposite problem of [https://github.com/tensorflow/tensorflow/issues/14182](https://github.com/tensorflow/tensorflow/issues/14182)

I'm using `Python 3.5`, but when I try to use a Tensorflow version 1.5 or above with the command

    python -c "import tensorflow"

I get a `RuntimeWarning` saying:

    /Users/<user>/.pyenv/versions/3.5.3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: 
    compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match 
    runtime version 3.5
      return f(*args, **kwds)

When I install using `pip install tensorflow==1.5.0`, it installs from `https://files.pythonhosted.org/packages/b1/57/1d27695a4572d70b8cd365dd358b45a41ece811d675910e175254779885e/tensorflow-1.5.0-cp35-cp35m-macosx_10_11_x86_64.whl`

Installing with `pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.5.0-py3-none-any.whl` doesn't make the warning go away either.

I get this warning for any Tensorflow version 1.5.0 and above. Incidentally, 1.5.0 is where the runtime binary for Python 3.6 was fixed, so I'm wondering if this is related. I have no issues when installing Tensorflow 1.5.0+ on Ubuntu 16.04 with `pip install tensorflow` with Python 3.5.2 so it seems to be a Mac OS X problem.

### Source code / logs

I get the warning whenever I run `import tensorflow`

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by skye** [comment]
@gunan can you comment or reassign? Thanks!

**Comment by gunan** [comment]
Do you see just a warning, or do you also face problems when running things?
We might be just renaming the package we built for python 36 on macos, because we cannot easily create macos environments using docker.

**Comment by binoche9** [comment]
I didn't face any issues, but I also wasn't running any complicated stuff because it was my introudction to tensorflow and I was just playing around with the basics

**Comment by munichma** [comment]
I ran into the same issue. 

I am using python version 3.5.5 and after "import tensorflow" I do get the following warning:

`/anaconda2/envs/tensorflow/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)`

Please clarification what to do and how to solve? 

Note:
If I change my python version from 3.5.5 to 3.6.5 the warning message disappears, so is that an issue with python 3.5?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gunan: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
this should be resolved now.

**Comment by dlfu** [comment]
i still have the issue with python 3.6.5
<img width="835" alt="screen shot 2018-09-14 at 10 34 49 am" src="https://user-images.githubusercontent.com/1424974/45565856-dc988680-b809-11e8-9037-a85ab3ef8430.png">

**Comment by dlfu** [comment]
Tensorflow doesnt exist for python 3.7 yet because of a reserved keyword issue.
