### ISSUE TITLE
Undefined symbol _rdft and _cblas_sgemm in libtensorflow-lite.a

### ISSUE THREAD

**Issue by simonfernandes7389** [tensorflow/tensorflow#19596]
Hi,

I am working on creating this SDK which is working fine if installed TensorflowLite via **_pod install_**
But, when creating this same SDK by steps mentioned in the following link (https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/contrib/lite/g3doc/ios.md) it gives the issue mentioned below:

> Undefined symbols for architecture arm64:
>   "_rdft", referenced from:
>       tflite::internal::Spectrogram::ProcessCoreFFT() in libtensorflow-lite.a(spectrogram.o)
>   "_cblas_sgemm", referenced from:
>       tflite::cblas_ops::Conv(float const*, tflite::Dims<4> const&, float const*, tflite::Dims<4> const&, float const*, tflite::Dims<4> const&, int, int, int, int, float, float, float*, tflite::Dims<4> const&, float*, tflite::Dims<4> const&) in libtensorflow-lite.a(conv.o)
> ld: symbol(s) not found for architecture arm64

thats when using TensorFlow version - r1.8

Also libtensorflow-lite.a is not created when using TensorFlow version - r1.7

> 1 error generated.
> make: *** [/Users/quantiphi/TFLite/tensorflow/tensorflow/contrib/lite/gen/obj/ios_x86_64/tensorflow/contrib/lite/kernels/internal/spectrogram.o] Error 1

Have I written custom code - No
OS Platform and Distribution - MacOS
TensorFlow - N/A
TensorFlow version - r1.8
Bazel version - 0.11.0
CUDA/cuDNN version - N/A
GPU model and memory - N/A
Exact command to reproduce - N/A

**Comment by syoyo** [comment]
`_rdft` comes from fftw library.

My solution is downloading fftw and link with it, please see my fork:
 
https://github.com/syoyo/tensorflow/commit/d4ba9c8e9387b5ad62511aaa95adb2427d3d9952#diff-57135143920cd34bc2ac188b5934308eR82

For `_cblas_sgemm`, you may solve it by linking with BLAS library provided by iOS SDK, but I'm not sure.

**Comment by miaout17** [comment]
The build issue was fixed in commit f1f1d5172fe5bfeaeb2cf657ffc43ba744187bee. 
The fix is in master branch, but not in r1.8 unfortunately. 
It will definitely be in the next release branch. 

For now, you can either use master branch, or cherry-pick the commit on top of r1.8 locally.

**Comment by simonfernandes7389** [comment]
thanks @miaout17 , the commit f1f1d51 have solved **"_rdft", referenc.....** issue
but I'm still facing the issue mentioned below,

> "_cblas_sgemm", referenced from:
> tflite::cblas_ops::Conv(float const*, tflite::Dims<4> const&, float const*, tflite::Dims<4> const&, float const*, tflite::Dims<4> const&, int, int, int, int, float, float, float*, tflite::Dims<4> const&, float*, tflite::Dims<4> const&) in libtensorflow-lite.a(conv.o)
> ld: symbol(s) not found for architecture arm64

Its there in master branch as well as in r1.8 branch

**Comment by simonfernandes7389** [comment]
Thanks, Added Accelerate.framework to solve this issue

> "_cblas_sgemm", referenced from:
> tflite::cblas_ops::Conv(float const*, tflite::Dims<4> const&, float const*, tflite::Dims<4> const&, float const*, tflite::Dims<4> const&, int, int, int, int, float, float, float*, tflite::Dims<4> const&, float*, tflite::Dims<4> const&) in libtensorflow-lite.a(conv.o)
> ld: symbol(s) not found for architecture arm64
