### ISSUE TITLE
Fail to convert from .pb to .toco

### ISSUE THREAD

**Issue by wenching33** [tensorflow/tensorflow#20016]
The error message is:
2018-06-14 20:36:34.054067: F tensorflow/contrib/lite/toco/tooling_util.cc:939] Check failed: name.substr(colon_pos + 1).find_first_not_of("0123456789") == string::npos (1 vs. 18446744073709551615)Array name must only have digits after colon
Aborted (core dumped)

Does anyone know what this message is about?
Thanks

----
update:
Sorry about wrong typing in the issue title. It should be "Fail to convert from .pb to .tflite"
Add info:
1. Have I written custom code
No, I use the original toco.
2. OS Platform and Distribution
Ubuntu 16.04 
3. TensorFlow installed from
Cloned from tensorflow official github
4. TensorFlow version
1.8.0
5. Bazel version
Build label: 0.14.0
6. CUDA/cuDNN version
I didn't use GPU.
7. GPU model and memory
N/A
8. Exact command to reproduce
I'm sorry that the .pb model I tried to transform is a privately built model, and I have no right to
upload it online. 
The commands transforming the model is just like the Basic example given in
"https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/toco/g3doc/cmdline_examples.md".
Except the model name and output node names were changed to that of my model.

Thanks.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment]
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by aselle** [comment]
Could you please try again on the nightly download, we think this is now fixed. Otherwise provide repro instructions.

**Comment by cy89** [comment]
@wenching33 does it work for you now?

**Comment by wenching33** [comment]
@cy89 No, the error still exists.
Actually, the .pb model I try to transfer to .tflite is transferred from .caffemodel using MMdnn.
I am not sure whether some error already exists after MMdnn conversion.

**Comment by tofulawrence** [comment]
@wenching33 May you provide the following, please:
- Model file
- Reproducible instructions
- Error encountered

Thanks :)

**Comment by tofulawrence** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
