### ISSUE TITLE
KeyError: 'IteratorGetDevice' in tf.train.import_meta_graph

### ISSUE THREAD

**Issue by sunminnie** [tensorflow/tensorflow#21024]
------------------------

### System information
ubuntu 16.04LTS   
protobuf                      3.6.0                 
tensorflow                    1.8.0
and I'm using Python 3.5

### Describe the problem
I got a [KeyError: 'IteratorGetDevice'] when using [tf.train.import_meta_graph] to import a [tensorflow official resnet model](the model is trained using the source code online).

### Source code / logs

[Code:]

import tensorflow as tf
with tf.Session() as sess:
  new_saver = tf.train.import_meta_graph(
          '/home/smn/cifar10_model/model.ckpt-3907.meta')

[Trackback:]

runfile('/home/smn/project/code/test2.py', wdir='/home/smn/project/code')
Traceback (most recent call last):

  File "<ipython-input-15-af704926d7fa>", line 1, in <module>
    runfile('/home/smn/project/code/test2.py', wdir='/home/smn/project/code')

  File "/home/smn/tensorflow/lib/python3.5/site-packages/spyder_kernels/customize/spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "/home/smn/tensorflow/lib/python3.5/site-packages/spyder_kernels/customize/spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/smn/project/code/test2.py", line 4, in <module>
    '/home/smn/cifar10_model/model.ckpt-3907.meta')

  File "/home/smn/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1955, in import_meta_graph
    **kwargs)

  File "/home/smn/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 743, in import_scoped_meta_graph
    producer_op_list=producer_op_list)

  File "/home/smn/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)

  File "/home/smn/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 460, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)

  File "/home/smn/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 227, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]

KeyError: 'IteratorGetDevice'

**Comment by sunminnie** [comment]
fixed after updated to tensorflow 1.9

**Comment by dmoham1476** [comment]
i still have this issue with tensorflow 1.10 and tensorflow 1.9

**Comment by sunminnie** [comment]
Try adding this line in your code:

tf.contrib.resampler

在2018-08-11 05:36:54，dmoham1476notifications@github.com写道：

i still have this issue with tensorflow 1.10 and tensorflow 1.9

**Comment by jiayiliu** [comment]
Similar problem again with `Key Error: 'ExperimentalIteratorGetDevice'`.  Unfortunately resampler doesn't work this time.
 I am using tf ver=1.11.0 and http://download.tensorflow.org/models/official/20181001_resnet/checkpoints/resnet_imagenet_v2_fp32_20181001.tar.gz
