### ISSUE TITLE
tf.data.Dataset.padded_batch() doesn't work with dataset.map

### ISSUE THREAD

**Issue by superhg2012** [tensorflow/tensorflow#21259]
System information
Have I written custom code: yes
OS Platform and Distribution:  Ubuntu Linux 
TensorFlow installed from: conda
TensorFlow version (use command below): 1.4.1
Python version: 3.6.5
Describe the problem
It's a image classification task to read variable-length images from png files, to map them and to padd them. But Dataset.padded_batch() doesn't work with tf.dataset which uses map 
    
    # source codes
    data.load_data() # load data from disk
    usable_data = data.get_data(use_percent=use_percent, tail=tail)
    # usable_data is a tuple for features and labels
    init_hook = IteratorInitHook()

    def input_fn():
        dataset = tf.data.Dataset.from_tensor_slices(usable_data)
        dataset = dataset.shuffle(params.shuffle_buffer_size)
        dataset = dataset.map(data.instance_as_tensor) # the instance_as_tensor method transfer an image into feature and label tensors, the shape of feature is (?,?,?) and label shape is ()
        dataset = dataset.repeat(epochs)
        dataset = dataset.padded_batch(params.batch_size, padded_shapes=([None, None, None], []))

        iterator = dataset.make_initializable_iterator()
        init_hook.iterator_init = iterator.initializer
        next_example, next_label = iterator.get_next()
        return {'sgram': next_example}, next_label

Exception stack is 

Traceback (most recent call last):
  File "main.py", line 414, in <module>
    tf.app.run(main=train_or_predict)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 405, in train_or_predict
    hparams=params,
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 625, in train_and_evaluate
    self.train(delay_secs=0)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 367, in train
    hooks=self._train_monitors + extra_hooks)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 807, in _call_train
    hooks=hooks)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 708, in _train_model
    input_fn, model_fn_lib.ModeKeys.TRAIN)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 577, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 663, in _call_input_fn
    return input_fn(**kwargs)
  File "main.py", line 218, in input_fn
    padded_shapes=([None, None, None],[])
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 695, in padded_batch
    return PaddedBatchDataset(self, batch_size, padded_shapes, padding_values)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1292, in __init__
    input_dataset.output_shapes, _partial_shape_to_tensor, padded_shapes)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 512, in map_structure_up_to
    assert_shallow_structure(shallow_tree, input_tree)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 372, in assert_shallow_structure
    check_types=check_types)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 356, in assert_shallow_structure
    "Input has type: %s." % type(input_tree))
TypeError: If shallow structure is a sequence, input must also be a sequence. Input has type: <class 'list'>.

**Comment by mrry** [comment]
Without the code of your `data.instance_as_tensor()` function it is difficult to say, but I think the bug might be in that function.

For example, the following trivial code combines `Dataset.map()` and `Dataset.padded_batch()` without error:

```python
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4])
dataset = dataset.shuffle(10)
dataset = dataset.map(lambda a: ([[[a]]], a))
dataset = dataset.repeat(3)
dataset = dataset.padded_batch(2, padded_shapes=([None, None, None], []))
```

The most likely cause is that your `data.instance_as_tensor()` function does not return a pair of tensors as expected.

**Comment by superhg2012** [comment]
Hi, Here is the instance_as_tensor code:

   def instance_as_tensor(image_name, label=None):
        """Convert a single training/prediction instance into a tensor."""
        img_file = tf.read_file(image_name)
        image = tf.image.decode_png(img_file, channels=0)
        image = tf.cast(image, tf.float32)
        image_data = tf.transpose(image[:128, :] / 256.)

        if label is not None:
            label = tf.cast(label, tf.int32)

        return {'sgram': image_data}, label

**Comment by mrry** [comment]
Right, so the problem is that the `padded_shapes` argument to `Dataset.padded_batch()` doesn't match the structure of the element. The following change should fix it:

```python
dataset = dataset.padded_batch(params.batch_size, padded_shapes=({'sgram': [None, None, None]}, []))
```

**Comment by superhg2012** [comment]
Hi, when I try to fix it with your solution, still fails, another error occur, type still not match

TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'sgram': {'sgram': <tf.Tensor 'IteratorGetNext:0' shape=(?, ?, ?, ?) dtype=float32>}}. Consider casting elements to a supported type.

**Comment by mrry** [comment]
What's the full stack trace for that error?

**Comment by superhg2012** [comment]
The full stack trace is below:

Traceback (most recent call last):
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 468, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 468, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got {'sgram': {'sgram': <tf.Tensor 'IteratorGetNext:0' shape=(?, ?, ?, ?) dtype=float32>}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 416, in <module>
    tf.app.run(main=train_or_predict)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 407, in train_or_predict
    hparams=params,
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 625, in train_and_evaluate
    self.train(delay_secs=0)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 367, in train
    hooks=self._train_monitors + extra_hooks)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 807, in _call_train
    hooks=hooks)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/data0/hegang/utils/spoken-language-id/models/base.py", line 28, in base_model_fn
    model = model_class(features, training=mode == tf.estimator.ModeKeys.TRAIN, params=params)
  File "/data0/hegang/utils/spoken-language-id/models/cnn.py", line 8, in __init__
    batch_size = tf.shape(features)[0]
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 271, in shape
    return shape_internal(input, name, optimize=True, out_type=out_type)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 295, in shape_internal
    input_tensor = ops.convert_to_tensor(input)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 836, in convert_to_tensor
    as_ref=False)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 926, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 229, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/data0/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 472, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'sgram': {'sgram': <tf.Tensor 'IteratorGetNext:0' shape=(?, ?, ?, ?) dtype=float32>}}. Consider casting elements to a supported type.

**Comment by mrry** [comment]
That looks like a different problem:  the code in your `model_fn` is attempting to pass an (apparently nested) dictionary of tensors to `tf.shape()`, which expects a tensor. I think part of the problem is in your `input_fn` where you wrap `next_example` (which is already a dict mapping `'sgram'` to a tensor) in another dictionary:

```python
    return {'sgram': next_example}, next_label
```

Instead, you should be able to do:

```python
    return next_example, next_label
```

**Comment by superhg2012** [comment]
@mrry 

Thanks a lot, it does works now

**Comment by superhg2012** [comment]
Hi, mrry, can you help to see this error?

when run predict, this error occurs.
the exception track is 

tensorflow.python.framework.errors_impl.InvalidArgumentError: Index out of range using input dim 3; input has only 3 dims for 'strided_slice_2' (op: 'StridedSlice') with input shapes: [?,?,?], [4], [4], [4] and with computed input tensors: input[3] = <1 1 1 1>.

and the code is below:


`def predict_single(model_fn, run_config, params, png_path):
    """Predict the language given the path to a single spectrogram in png format."""
    model = tf.estimator.Estimator(model_fn, params=params, config=run_config)

    # Load data
    if not params.language_list:
        # Language order can be loaded from the training set
        data = TCData(FLAGS.image_dir, FLAGS.train_set, params)
        data.load_data()
        language_list = data.language_set
    else:
        language_list = params.language_list

    checkpoint_path = find_best_checkpoint(run_config)
    iterator = model.predict(
        input_fn=lambda: TCData.instance_as_tensor(png_path),
        checkpoint_path=checkpoint_path,
    )
    prediction = next(iterator)`
