### ISSUE TITLE
model prediction works differently when running on different system configuration

### ISSUE THREAD

**Issue by kishore0905** [tensorflow/tensorflow#21326]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:nope
- **TensorFlow installed from (source or binary)**:source
- **TensorFlow version (use command below)**:1.9
- **Python version**:3.6
- **Bazel version (if compiling from source)**:dont know
- **GCC/Compiler version (if compiling from source)**:5.4.0
- **CUDA/cuDNN version**:9.0
- **GPU model and memory**: Geforce Gtx 1080 Ti
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflostackoverfloww as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

i am running this neural translation application
https://github.com/tensorflow/tensorflow/blob/r1.9/tensorflow/contrib/eager/python/examples/nmt_with_attention/nmt_with_attention.ipynb
And i made some changes here to store the model as checkpoints so that everytime i dont want to again train the application it works fine in windows 10 gpu system.

when i  run the same code in cpu system its giving different result .
I checked the versions and environment everything is same.how could i solve this issue? 

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by yashk2810** [comment]
This is same as the issue #21216 

Try installing tf-nightly on your system (pip install -U --pre tf-nightly).

**Comment by drpngx** [comment]
Could you please tell us a little bit more about what you're running and what kind of differences you are seeing?

**Comment by kishore0905** [comment]
![output gpu](https://user-images.githubusercontent.com/37259213/43696343-2497c324-995b-11e8-8b74-d9a0c7a85c2a.png)
The above one is the output when i am running the code on windows gpu system.

********************************************************************************************************************
from __future__ import absolute_import, division, print_function

# Import TensorFlow >= 1.9 and enable eager execution
import tensorflow as tf
tfe = tf.contrib.eager

tf.enable_eager_execution()

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

import unicodedata
import re
import numpy as np
import os
import time

print(tf.__version__)

# Download the file
# path_to_zip = tf.keras.utils.get_file(
#     'spa-eng.zip', origin='http://download.tensorflow.org/data/spa-eng.zip', 
#     extract=True)

# path_to_file = os.path.dirname(path_to_zip)+"/spa-eng/spa.txt"
path_to_file = "./data/spa.txt"
# Converts the unicode file to ascii
def unicode_to_ascii(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn')


def preprocess_sentence(w):
    w = unicode_to_ascii(w.lower().strip())
    
    
    w = re.sub(r"([?.!,¿])", r" \1 ", w)
    w = re.sub(r'[" "]+', " ", w)
    
    
    w = re.sub(r"[^a-zA-Z?.!,¿]+", " ", w)
    
    w = w.rstrip().strip()
    
    
    w = '<start> ' + w + ' <end>'
    return w

def create_dataset(path, num_examples):
    lines = open(path, encoding='UTF-8').read().strip().split('\n')
    
    word_pairs = [[preprocess_sentence(w) for w in l.split('\t')]  for l in lines[:num_examples]]
    
    return word_pairs


class LanguageIndex():
  def __init__(self, lang):
    self.lang = lang
    self.word2idx = {}
    self.idx2word = {}
    self.vocab = set()
    
    self.create_index()
    
  def create_index(self):
    for phrase in self.lang:
      self.vocab.update(phrase.split(' '))
    
    self.vocab = sorted(self.vocab)
    
    self.word2idx['<pad>'] = 0
    for index, word in enumerate(self.vocab):
      self.word2idx[word] = index + 1
    
    for word, index in self.word2idx.items():
      self.idx2word[index] = word

def max_length(tensor):
    return max(len(t) for t in tensor)


def load_dataset(path, num_examples):
    # creating cleaned input, output pairs
    pairs = create_dataset(path, num_examples)

    # index language using the class defined above    
    inp_lang = LanguageIndex(en for en, sp in pairs)
    targ_lang = LanguageIndex(sp for en, sp in pairs)
    
    # Vectorize the input and target languages
    
    # Spanish sentences
    input_tensor = [[inp_lang.word2idx[s] for s in en.split(' ')] for en, sp in pairs]
    
    # English sentences
    target_tensor = [[targ_lang.word2idx[s] for s in sp.split(' ')] for en, sp in pairs]
    # Calculate max_length of input and output tensor
    # Here, we'll set those to the longest sentence in the dataset
    max_length_inp, max_length_tar = max_length(input_tensor), max_length(target_tensor)
    
    # Padding the input and output tensor to the maximum length
    input_tensor = tf.keras.preprocessing.sequence.pad_sequences(input_tensor, 
                                                                 maxlen=max_length_inp,
                                                                 padding='post')
    
    target_tensor = tf.keras.preprocessing.sequence.pad_sequences(target_tensor, 
                                                                  maxlen=max_length_tar, 
                                                                  padding='post')
    
    return input_tensor, target_tensor, inp_lang, targ_lang, max_length_inp, max_length_tar


# Try experimenting with the size of that dataset
num_examples = 30000
input_tensor, target_tensor, inp_lang, targ_lang, max_length_inp, max_length_targ = load_dataset(path_to_file, num_examples)

# Creating training and validation sets using an 80-20 split
input_tensor_train, input_tensor_val, target_tensor_train, target_tensor_val = train_test_split(input_tensor, target_tensor, test_size=0.2)

# Show length
len(input_tensor_train), len(target_tensor_train), len(input_tensor_val), len(target_tensor_val)


BUFFER_SIZE = len(input_tensor_train)
BATCH_SIZE = 64
N_BATCH = BUFFER_SIZE//BATCH_SIZE
embedding_dim = 256
units = 1024
vocab_inp_size = len(inp_lang.word2idx)
vocab_tar_size = len(targ_lang.word2idx)

dataset = tf.data.Dataset.from_tensor_slices((input_tensor_train, target_tensor_train)).shuffle(BUFFER_SIZE)
dataset = dataset.apply(tf.contrib.data.batch_and_drop_remainder(BATCH_SIZE))


def gru(units):
  # If you have a GPU, we recommend using CuDNNGRU(provides a 3x speedup than GRU)
  # the code automatically does that.
  if tf.test.is_gpu_available():
    return tf.keras.layers.CuDNNGRU(units, 
                                    return_sequences=True, 
                                    return_state=True, 
                                    recurrent_initializer='glorot_uniform')
  else:
    return tf.keras.layers.GRU(units, 
                               return_sequences=True, 
                               return_state=True, 
                               recurrent_activation='sigmoid', 
                               recurrent_initializer='glorot_uniform')

class Encoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, enc_units, batch_sz):
        super(Encoder, self).__init__()
        self.batch_sz = batch_sz
        self.enc_units = enc_units
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.gru = gru(self.enc_units)
        
    def call(self, x, hidden):
        x = self.embedding(x)
        output, state = self.gru(x, initial_state = hidden)        
        return output, state
    
    def initialize_hidden_state(self):
        return tf.zeros((self.batch_sz, self.enc_units))

class Decoder(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, dec_units, batch_sz):
        super(Decoder, self).__init__()
        self.batch_sz = batch_sz
        self.dec_units = dec_units
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.gru = gru(self.dec_units)
        self.fc = tf.keras.layers.Dense(vocab_size)
        
        # used for attention
        self.W1 = tf.keras.layers.Dense(self.dec_units)
        self.W2 = tf.keras.layers.Dense(self.dec_units)
        self.V = tf.keras.layers.Dense(1)
        
    def call(self, x, hidden, enc_output):
        
        hidden_with_time_axis = tf.expand_dims(hidden, 1)
        
        # score shape == (batch_size, max_length, hidden_size)
        score = tf.nn.tanh(self.W1(enc_output) + self.W2(hidden_with_time_axis))
        
        # attention_weights shape == (batch_size, max_length, 1)
        # we get 1 at the last axis because we are applying score to self.V
        attention_weights = tf.nn.softmax(self.V(score), axis=1)
        
        # context_vector shape after sum == (batch_size, hidden_size)
        context_vector = attention_weights * enc_output
        context_vector = tf.reduce_sum(context_vector, axis=1)
        
        # x shape after passing through embedding == (batch_size, 1, embedding_dim)
        x = self.embedding(x)
        
        # x shape after concatenation == (batch_size, 1, embedding_dim + hidden_size)
        x = tf.concat([tf.expand_dims(context_vector, 1), x], axis=-1)
        
        # passing the concatenated vector to the GRU
        output, state = self.gru(x)
        
        # output shape == (batch_size * max_length, hidden_size)
        output = tf.reshape(output, (-1, output.shape[2]))
        
        # output shape == (batch_size * max_length, vocab)
        x = self.fc(output)
        
        return x, state, attention_weights
        
    def initialize_hidden_state(self):
        return tf.zeros((self.batch_sz, self.dec_units))

encoder = Encoder(vocab_inp_size, embedding_dim, units, BATCH_SIZE)
decoder = Decoder(vocab_tar_size, embedding_dim, units, BATCH_SIZE)

"""## Define the optimizer and the loss function"""

optimizer = tf.train.AdamOptimizer()


def loss_function(real, pred):
  mask = 1 - np.equal(real, 0)
  loss_ = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=real, logits=pred) * mask
  return tf.reduce_mean(loss_)


restore = True
checkpoint_dir="./checkpoint_eng_spa/"
root = tfe.Checkpoint(optimizer=optimizer,
                            encoder = encoder,
                            decoder = decoder,
                            optimizer_step=tf.train.get_or_create_global_step())



def evaluate(sentence, encoder, decoder, inp_lang, targ_lang, max_length_inp, max_length_targ):
    attention_plot = np.zeros((max_length_targ, max_length_inp))
    
    sentence = preprocess_sentence(sentence)

    inputs = [inp_lang.word2idx[i] for i in sentence.split(' ')]
    inputs = tf.keras.preprocessing.sequence.pad_sequences([inputs], maxlen=max_length_inp, padding='post')
    inputs = tf.convert_to_tensor(inputs)
    
    result = ''

    hidden = [tf.zeros((1, units))]
    enc_out, enc_hidden = encoder(inputs, hidden)

    dec_hidden = enc_hidden
    dec_input = tf.expand_dims([targ_lang.word2idx['<start>']], 0)

    for t in range(max_length_targ):
        predictions, dec_hidden, attention_weights = decoder(dec_input, dec_hidden, enc_out)
        
        # storing the attention weigths to plot later on
        attention_weights = tf.reshape(attention_weights, (-1, ))
        attention_plot[t] = attention_weights.numpy()

        predicted_id = tf.multinomial(tf.exp(predictions), num_samples=1)[0][0].numpy()

        result += targ_lang.idx2word[predicted_id] + ' '

        if targ_lang.idx2word[predicted_id] == '<end>':
            return result, sentence, attention_plot
        
        # the predicted ID is fed back into the model
        dec_input = tf.expand_dims([predicted_id], 0)

    return result, sentence, attention_plot

# function for plotting the attention weights
def plot_attention(attention, sentence, predicted_sentence):
    fig = plt.figure(figsize=(10,10))
    ax = fig.add_subplot(1, 1, 1)
    ax.matshow(attention, cmap='viridis')
    
    fontdict = {'fontsize': 14}
    
    ax.set_xticklabels([''] + sentence, fontdict=fontdict, rotation=90)
    ax.set_yticklabels([''] + predicted_sentence, fontdict=fontdict)

    plt.show()

def translate(sentence, encoder, decoder, inp_lang, targ_lang, max_length_inp, max_length_targ):
    result, sentence, attention_plot = evaluate(sentence, encoder, decoder, inp_lang, targ_lang, max_length_inp, max_length_targ)
        
    print('Input: {}'.format(sentence))
    result_without_append = ''
    results = result.split(' ')
    for pad in results:
        if pad not in "<end>":
            result_without_append += pad + " "
    print('Predicted translation: {}'.format(result_without_append))
    
    # attention_plot = attention_plot[:len(result.split(' ')), :len(sentence.split(' '))]
    # plot_attention(attention_plot, sentence.split(' '), result.split(' '))



if restore==False:
    EPOCHS = 10

    for epoch in range(EPOCHS):
        start = time.time()
        
        hidden = encoder.initialize_hidden_state()
        total_loss = 0
        
        for (batch, (inp, targ)) in enumerate(dataset):
            loss = 0
            
            with tf.GradientTape() as tape:
                enc_output, enc_hidden = encoder(inp, hidden)
                
                dec_hidden = enc_hidden
                
                dec_input = tf.expand_dims([targ_lang.word2idx['<start>']] * BATCH_SIZE, 1)       
                
                # Teacher forcing - feeding the target as the next input
                for t in range(1, targ.shape[1]):
                    # passing enc_output to the decoder
                    predictions, dec_hidden, _ = decoder(dec_input, dec_hidden, enc_output)
                    
                    loss += loss_function(targ[:, t], predictions)
                    
                    # using teacher forcing
                    dec_input = tf.expand_dims(targ[:, t], 1)
            
            batch_loss = (loss / int(targ.shape[1]))
            
            total_loss += batch_loss
            
            variables = encoder.variables + decoder.variables
            
            gradients = tape.gradient(loss, variables)
            
            optimizer.apply_gradients(zip(gradients, variables), tf.train.get_or_create_global_step())
            
            if batch % 100 == 0:
                print('Epoch {} Batch {} Loss {:.4f}'.format(epoch + 1,
                                                            batch,
                                                            batch_loss.numpy()))
        
        print('Epoch {} Loss {:.4f}'.format(epoch + 1,
                                            total_loss / N_BATCH))
        
        save_path = root.save(checkpoint_dir)
        print(save_path)
        print('Time taken for 1 epoch {} sec\n'.format(time.time() - start))

else:
    rst = root.restore(tf.train.latest_checkpoint(checkpoint_dir))
    
    translate('Hola.', encoder, decoder, inp_lang, targ_lang, max_length_inp, max_length_targ)
    
    translate('trata de averiguarlo.', encoder, decoder, inp_lang, targ_lang, max_length_inp, max_length_targ)


    translate('Buenos días.', encoder, decoder, inp_lang, targ_lang, max_length_inp, max_length_targ)

    # translate('hello.', encoder, decoder, inp_lang, targ_lang, max_length_inp, max_length_targ)

    # translate('this is my life .', encoder, decoder, inp_lang, targ_lang, max_length_inp, max_length_targ)
    # translate('bye.', encoder, decoder, inp_lang, targ_lang, max_length_inp, max_length_targ)
    
******************************************************************************************************************
![ubuntu](https://user-images.githubusercontent.com/37259213/43697069-2dfc148e-995f-11e8-8ba3-acd47f1713bf.png)
This is the output when running the same file on ubuntu without gpu. The same questions  but answers are different.

**Comment by yashk2810** [comment]
For how many epochs was the model trained on in GPU and CPU confirgurations?

**Comment by kishore0905** [comment]
10 epochs on GPU system and saving them in  checkpoint file and i runned them in CPU system(without retraining)

**Comment by yashk2810** [comment]
> TensorFlow version (use command below): 1.9

Please try upgrading your tensorflow version to tf-nightly. I think, that should resolve the error.

**Comment by drpngx** [comment]
@kishore0905 did that work for you?

**Comment by kishore0905** [comment]
i tried with tf-nightly in both the systems but the problem still persist

**Comment by allenlavoie** [comment]
@kishore0905 what's the tf.__git_version__ of the nightly you tried that's not working?

**Comment by kishore0905** [comment]
sorry for the late reply. The git version is "b'v1.9.0-rc2-1098-g89e06304aa'"

**Comment by yashk2810** [comment]
The current nightly version is 1.11.xxx. You might wanna upgrade it again.

Or TF 1.10 is out so you can upgrade to that.

**Comment by kishore0905** [comment]
windows 10 Gpu congfiguration:

tensorflow(GPU) version: 1.10.0

git version:  b'v1.10.0-rc1-19-g656e7a2b34



![tensorflow_issue gpu](https://user-images.githubusercontent.com/37259213/44074259-8f69c656-9fb5-11e8-9209-59224315971c.png)




Ubuntu CPU configuration:

tensorflow(CPU) version: 1.10.0

git version:   v1.10.0-0-g656e7a2b34

![tf_issue cpu](https://user-images.githubusercontent.com/37259213/44073606-4a09b4a2-9fb2-11e8-8406-a94ef5aa5a5a.jpg)

**Comment by yashk2810** [comment]
Can you share your code for checkpointing and restoring the weights.

Also, the code for this example has been updated to checkpoint the variables of the model. Can you please try that code and tell us if the error still persists?

**Comment by yashk2810** [comment]
Did this solve your problem?

**Comment by allenlavoie** [comment]
@gaarangoa which TensorFlow versions are you using?

**Comment by yashk2810** [comment]
I think its because of CuDNNGRU that's being used. It doesn't work in CPU mode so the weights are not getting loaded into that RNN. Can you use GRU instead of CuDNNGRU and see if that works?

**Comment by gaarangoa** [comment]
Hey there, 

Local environment: '1.10.0'
colab only CPU: '1.10.0'
colab GPU: '1.10.0'

Only works in colab when using GPU. I also suspect is because of CuDNNGRU, in the provided example, there is a function that takes care of it (see below) depending on the environment it uses either GRU or CuDNNGRU. 

Based on the tf documentation, I found that GRU should have enabled: **reset_after=True,**,  **recurrent_activation='sigmoid',** But, I got the same inconsistent results. 

def gru(units):
    # If you have a GPU, we recommend using CuDNNGRU(provides a 3x speedup than GRU)
    # the code automatically does that.
    if tf.test.is_gpu_available():
        return tf.keras.layers.CuDNNGRU(units,
                                    return_sequences=True,
                                    return_state=True,
                                    recurrent_initializer='glorot_uniform')
    else:
        return tf.keras.layers.GRU(units,
                                return_sequences=True,
                                return_state=True,
                                **reset_after=True,**
                                **recurrent_activation='sigmoid',**
                                recurrent_initializer='glorot_uniform',
                                )

I'm a little confused about what version is using the GRU implementation, in the documentation says the CPU compatible is v1 see https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU

Many thanks!!

**Comment by yashk2810** [comment]
I modified my comment above. The problem is you train with CUDNNGRU and when you shift to CPU the weights are loaded into GRU. That's where the problem is. If you are using CPU for running predictions, I would suggest training it with GRU and removing the if-else conditional loop.

**Comment by yashk2810** [comment]
@allenlavoie  I don't think its that. Its the CuDNNGRU and GRU being used in GPU and CPU mode. CuDNNGRU is getting trained and the weights are getting loaded into GRU which is causing the random output which makes sense.

**Comment by gaarangoa** [comment]
Hey there, 
I just tested using the GRU only. Unfortunately, seems like the checkpoint restore does not work for RNNs yet. 

Any suggestions for a different approach to save/restore? 

Thanks a lot!

**Comment by yashk2810** [comment]
The checkpoint restore doesn't work in CPU mode?

**Comment by gaarangoa** [comment]
nope, seem it does not work

This is what I did:
Test #1
1.  I modified the gru function by enabling only the GRU (as you suggested)
2. Run training and save checkpoint as in the notebook
3. Test few examples and it worked fine
4. Restart the Encoder/Decoder 
     _encoder = Encoder(vocab_inp_size, embedding_dim, units, BATCH_SIZE)_
     _decoder = Decoder(vocab_tar_size, embedding_dim, units, BATCH_SIZE)_
5. Load checkpoint
6. Test few examples and the result was pretty random. 

Test #2
1.  I modified the gru function by enabling only the GRU
2. Run training and save checkpoint as in the notebook
3. Test few examples and it worked fine
4. Change to CPU only mode
5. Restart the Encoder/Decoder 
6. Load checkpoint
7. Test few examples and the result was pretty random. 

I did all tests using colab. 

Regards,

**Comment by yashk2810** [comment]
I think you need to restart the kernel when doing it in colab. Colab behaves weirdly when loading the checkpoints if the kernel is not restarted. I think it retains some weights or something else is happening. 

Can you try restarting the kernel and then don't train the model but just load the checkpoints?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @drpngx: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshini-gadige** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
