### ISSUE TITLE
Protobuf 3.6.1 import issue with tensorflow 1.10

### ISSUE THREAD

**Issue by nirajkale** [tensorflow/tensorflow#21719]
Version: master/v3.6.1
Language: Python 3.6x64 on Windows 10

**Followed instructions mentioned on tensorflow.org's guide on installing tensorflow on Windows
(www.tensorflow.org/install/install_windows)

1. Installed CUDA 9.0 (latest release supported by tf_gpu)
2. Installed cuDNN v7 for (CUDA 9.0)
3. Installed tensorflow_gpu using native-pip
**protobuf is part of tf gpu installation 
4. After the installation, i wanted to test the tf, so as usual tried:
  import tensorflow
  but got an error:==>
  Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tensorflow
  File "C:\Users\Niraj\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Niraj\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\Niraj\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\Niraj\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

Initially i thought the issue was related to CUDA or cdnn itself, but after hours of trial & error with multiple cuda & cudnn version combination, i decided to focus on the library mentioned in the error message itself.  
I'm not very new to python extensions so obvious work around for me was to try earlier version of protobuf, so i tried: 

pip uninstall protobuf
pip install protobuf==3.6.0

and tada!! tensorflow started working.
I'm still not sure if this was actually caused by protobuf or incorrect installations etc.
My sincere apologies if this issue is unrelated.
Please let me know if you need more details on this issue.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by nirajkale** [comment]
Hi,
Pfb more details:
Have I written custom code : n/a
OS Platform and Distribution: Windows 10
TensorFlow installed from: python native pip without​ Anaconda
TensorFlow version: 1.10
Bazel version: n/a 
CUDA/cuDNN version: Cuda: 9.0, cuDNN v7.05
GPU model and memory: GTX1060 6gb
Exact command to reproduce: just tried to import tensorflow after pip installation
Mobile device: n/a

I was able to fix the issue after downgrading protobuf from 3.6.1 to 3.6.0
Hope this helps!

**Comment by gunan** [comment]
Hi,
I have a few questions. What do you mean by:
```
Installed tensorflow_gpu using native-pip
**protobuf is part of tf gpu installation
```

Also, did you upgrade your tensorflow installation from a previous version, or did you install tf from scratch on your machine?

**Comment by shunluzhang** [comment]
Same here, exactly same problem after upgrading to tensorflow 1.10, also tried clean install tensorflow 1.10.

protobuf 3.6.1 doesn't not work for CPU and GPU, but protobuf 3.6.0 works for both.

**Comment by nirajkale** [comment]
**protobuf is part of tf gpu installation - meaning protobuf was installed as part of pip installation of tensorflow.
Also, i did the installation from scratch.

**Comment by emartorano** [comment]
I had exactly the same issue. I spend the entire day trying to figure out what was wrong. I installed and uninstalled python, tf, etc.. million times on my new Windows 10 machine. This morning I saw this post. I deleted protobuf 3.6.1 and installed 3.6.0. Bingo ! everything is working. Thanks a lot

**Comment by gunan** [comment]
@acozzette @xfxyjwf
Is there a known backwards compatibility issue between protobuf 3.6.1 and 3.6.0?

**Comment by acozzette** [comment]
@gunan No, I don't know of any backward compatibility issues between 3.6.0 and 3.6.1. @anandolee Do you have any ideas what it could be?

**Comment by xfxyjwf** [comment]
This is https://github.com/protocolbuffers/protobuf/issues/5046 . @TeBoring what's the solution to this issue?

**Comment by TeBoring** [comment]
upgrade python to >=3.6.1

**Comment by tensorflowbutler** [comment]
Nagging Assignees @gunan, @poxvoculi: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @gunan, @poxvoculi: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by gunan** [comment]
Looking at the comments, this actually looks like a missing backwards compatibility issue in protobuf between 3.6.0 and 3.6.1
Unfortunately, solution is to upgrade protobuf to 3.6.1.
I will make that change in our setup.py script, and close this issue.

**Comment by skanth859** [comment]
DLL LOAD ERROR SPECIFIED ERROR COUDN'T FOUND 
WINDOWS 7 INSTALLED TENSORFLOW 1.12 WITH CUDNN 9  THROUGH ANACONDA  PYTHON VERSION 3.6.7

(SRI) C:\Users\SRIKANTH>python -c "import tensorflow"
Traceback (most recent call last):
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\imp.py", line 243, in load_modu
le
    return load_dynamic(name, filename, file)
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\imp.py", line 343, in load_dyna
mic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\__init
__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-im
port
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\site-packages\tensorflow\python
\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, descript
ion)
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\imp.py", line 243, in load_modu
le
    return load_dynamic(name, filename, file)
  File "C:\Users\SRIKANTH\Anaconda3\envs\SRI\lib\imp.py", line 343, in load_dyna
mic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.


Failed to load the native TensorFlow runtimE

**Comment by nirajkale** [comment]
To add an update, this issue is not only related to tf-gpu version but also occurs for cpu version if installed with python version 3.6.0
this can still be solved by replacing default protobuf version with 3.6.0

**Comment by NeelKanwal** [comment]
I have installed tensorflow==1.5.0 and protobuf==3.6.0 and 3.4.0 alternatively but there is still an issues.

/home/nkanwal/bert/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or '1type' 
as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/nkanwal/bert/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:497: FutureWarning: Passing (type, 1) or '1type' 
as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/nkanwal/bert/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:502: FutureWarning: Passing (type, 1) or '1type' 
as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

please suggest some solution

**Comment by rishabhc32** [comment]
• [ ] - [x] - [ ]


$

 :grinning: - [ ]

**Comment by nirajkale** [comment]
> I have installed tensorflow==1.5.0 and protobuf==3.6.0 and 3.4.0 alternatively but there is still an issues.
> 
> /home/nkanwal/bert/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or '1type'
> as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /home/nkanwal/bert/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:497: FutureWarning: Passing (type, 1) or '1type'
> as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /home/nkanwal/bert/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:502: FutureWarning: Passing (type, 1) or '1type'
> as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> np_resource = np.dtype([("resource", np.ubyte, 1)])
> 
> please suggest some solution

I din know the older versions of tensorflow were still being used. Anyway, i would suggest keeping only one version of protobuff. I think tf might be using the higher version which might be causing the issue.
Not sure which exact version of protobuf will work with tf 1.5. U might have to do some trial n error but while doing so, pls try one at a time ( as in 1 version in ur virtual env at a time)
Hope this help!

**Comment by shubhambagwari** [comment]
File "stylize.py", line 97, in <module>
    main()
  File "stylize.py", line 57, in main
    graph_def.ParseFromString(f.read())
  File "C:\Users\shubham\myenv\lib\site-packages\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "C:\Users\shubham\myenv\lib\site-packages\google\protobuf\internal\python_message.py", line 1083, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\shubham\myenv\lib\site-packages\google\protobuf\internal\python_message.py", line 1109, in InternalParse
    new_pos = local_SkipField(buffer, new_pos, end, tag_bytes)
  File "C:\Users\shubham\myenv\lib\site-packages\google\protobuf\internal\decoder.py", line 850, in SkipField
    return WIRETYPE_TO_SKIPPER[wire_type](buffer, pos, end)
  File "C:\Users\shubham\myenv\lib\site-packages\google\protobuf\internal\decoder.py", line 820, in _RaiseInvalidWireType
    raise _DecodeError('Tag had invalid wire type.')
google.protobuf.message.DecodeError: Tag had invalid wire type.

After reading everything, Still, I am getting this error.
