### ISSUE TITLE
`fit` method of subclassed `tf.keras.Model` doesn't work with multi inputs `tf.data.Dataset` when validation data exsits  

### ISSUE THREAD

**Issue by zakizhou** [tensorflow/tensorflow#21729]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: '1.11.0-dev20180820'
- **Python version**: 3.5
- **Bazel version (if compiling from source)**: None
- **GCC/Compiler version (if compiling from source)**: None
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
- **Exact command to reproduce**: None

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

`fit` method of subclassed `tf.keras.Model` doesn't work with multi inputs `tf.data.Dataset` when validation data exsits  

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import numpy as np
import tensorflow as tf

source = (
    ((tf.constant(np.random.normal(0, 1, (1024, 2)), dtype=tf.float32),
      tf.constant(np.random.normal(0, 1, (1024, 2)), dtype=tf.float32))),
    tf.constant(np.random.randint(0, 2, (1024, 2)), dtype=tf.float32)
)

train = tf.data.Dataset.from_tensor_slices(source).batch(128, drop_remainder=True).repeat(10)
valid = tf.data.Dataset.from_tensor_slices(source).batch(128, drop_remainder=True).repeat(10)


class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self.d = tf.keras.layers.Dense(2, activation="softmax")

    def call(self, inputs, training=True, mask=None):
        return self.d(inputs[0] + inputs[1])


m = Model()
m.compile(tf.train.AdamOptimizer(0.001),
          loss=["categorical_crossentropy"])
m.fit(x=train, validation_data=valid, steps_per_epoch=8)
```
log
```
ValueError: ('Error when checking model input: expected no data, but got:', (<tf.Tensor 'IteratorGetNext_1:0' shape=(128, 2) dtype=float32>, <tf.Tensor 'IteratorGetNext_1:1' shape=(128, 2) dtype=float32>))
```

**Comment by carlthome** [comment]
Status on fix?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by zakizhou** [comment]
It has been more than one month since I created this issue, is that any plan to fix it? If there is no one working on this now, I would like to contribute

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by hsm207** [comment]
It also does not work when the input is a dictionary:

```
import tensorflow as tf
from collections import ChainMap

tf.enable_eager_execution()


class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.dense1 = tf.keras.layers.Dense(2, activation='relu')
        self.dense2 = tf.keras.layers.Dense(2, activation='relu')
        self.dense3 = tf.keras.layers.Dense(1)

    def call(self, inputs, training=None, mask=None):
        x1 = inputs['x1']
        x2 = inputs['x2']

        x1 = self.dense1(x1)
        x2 = self.dense2(x2)

        y = self.dense3(x1 + x2)

        return y


model = MyModel()

x1 = tf.random.normal((10, 1), 0, 1)
x2 = tf.random.normal((10, 1), 1, 2)
y = x1 + 2 * x2

ds = tf.data.Dataset.zip((tf.data.Dataset.from_tensor_slices({'x1': x1}),
                          tf.data.Dataset.from_tensor_slices({'x2': x2}))) \
    .map(lambda *dicts: dict(ChainMap(*dicts)))

y = tf.data.Dataset.from_tensor_slices(y)

ds = tf.data.Dataset.zip((ds, y)) \
    .batch(5) \
    .repeat()

model.compile(tf.train.AdamOptimizer(), 'mean_squared_error', metrics =['mae'])
model.fit(ds, epochs=1, steps_per_epoch=10, validation_data=ds)
```
It gives the following error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1614, in fit
    validation_steps=validation_steps)
  File "/Users/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 681, in fit_loop
    verbose=verbose)
  File "/Users/user/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 144, in configure_callbacks
    val_data = val_inputs + val_targets
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @fchollet: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by byzhang** [comment]
@hsm207 is it solved in the newer version?

**Comment by hsm207** [comment]
@byzhang no. Just checked with 1.12.0 and still the same problem.

**Comment by zakizhou** [comment]
no errors with version 1.14.1-dev20190528, closed.
