### ISSUE TITLE
`MirrorStrategy` is not working with `tf.estimator.DNNClassifier`

### ISSUE THREAD

**Issue by yncxcw** [tensorflow/tensorflow#21767]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Changed from `models/samples/core/get_started/premade_estimator.py`
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.64
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
No
- **TensorFlow installed from (source or binary)**:
Compile from source 1.10
- **TensorFlow version (use command below)**:
1.10
- **Python version**:
2.7.12
- **Bazel version (if compiling from source)**:
0.16.1
- **GCC/Compiler version (if compiling from source)**:
5.4.0
- **CUDA/cuDNN version**:
9.1
- **GPU model and memory**:
2 x TITAN Xp/12GB
- **Exact command to reproduce**:
`python premade_estimator.py`

### Describe the problem
I try to use `MirrorStrategy` to parallel `premade_estimator.py`. The  code is below. I made two changes:
(1) I make a fake input_fn to build (features, labels) from random values.
(2) I add two lines to use `MirrorStrategy` when initializing the `conf` when building `estimator`.

It woks fine if I do not use `MirrosStrategy`(without (2)), but fails as following logs output.

BTW: I also tried the original input_fn, reported the same errors.

Appreciate the help

### Source code / logs

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import tensorflow as tf

import iris_data


parser = argparse.ArgumentParser()
parser.add_argument('--batch_size', default=32, type=int, help='batch size')
parser.add_argument('--train_steps', default=1000, type=int,
                    help='number of training steps')

CSV_COLUMN_NAMES = ['SepalLength', 'SepalWidth',
                    'PetalLength', 'PetalWidth', 'Species']

def train_input_fn_fake(features_name, batch_size):
    features_len = len(features_name)
    data_len = 10000
    features = tf.random_uniform([data_len, features_len], minval=0, maxval=1, dtype=tf.float32)
    labels = tf.random_uniform([data_len, 1], minval=0, maxval=2, dtype=tf.int32)
    def map_dnn_input(features, labels):
        features = tf.split(features, features_len)
        features = dict(zip(features_name, features))
        return features, labels
    dataset = tf.data.Dataset.from_tensor_slices((features, labels)).map(map_dnn_input)
    dataset = dataset.shuffle(1000).repeat().batch(batch_size)
    return dataset



def main(argv):
    args = parser.parse_args(argv[1:])

    # Feature columns describe how to use the input.
    my_feature_columns = []
    my_features = []
    for key in CSV_COLUMN_NAMES:
        my_features.append(key)
        my_feature_columns.append(tf.feature_column.numeric_column(key=key))


    # configure multi gpu
    distribution = tf.contrib.distribute.MirroredStrategy(num_gpus=2)
    config = tf.estimator.RunConfig(train_distribute=distribution)

    # Build 2 hidden layer DNN with 10, 10 units respectively.
    classifier = tf.estimator.DNNClassifier(
        feature_columns=my_feature_columns,
        # Two hidden layers of 10 nodes each
        hidden_units=[100, 100],
        # The model must choose between 3 classes.
        n_classes=3,
        # Config
        config = config
        )

    # Train the Model.
    classifier.train(
        input_fn=lambda:train_input_fn_fake(my_features,
                                            args.batch_size),
        steps=args.train_steps,
        )

    
if __name__ == '__main__':
    tf.logging.set_verbosity(tf.logging.INFO)
    tf.app.run(main)
```

Log output:
```

2018-08-21 12:27:58.645341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.91GiB freeMemory: 10.62GiB
2018-08-21 12:27:58.874232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Found device 1 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 11.91GiB freeMemory: 11.74GiB
2018-08-21 12:27:58.875049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1485] Adding visible gpu devices: 0, 1
2018-08-21 12:27:59.303516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-21 12:27:59.303548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:972]      0 1 
2018-08-21 12:27:59.303553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 0:   N Y 
2018-08-21 12:27:59.303557: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 1:   Y N 
2018-08-21 12:27:59.303931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/device:GPU:0 with 10261 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-08-21 12:27:59.405388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/device:GPU:1 with 11361 MB memory) -> physical GPU (device: 1, name: TITAN Xp, pci bus id: 0000:02:00.0, compute capability: 6.1)
INFO:tensorflow:Device is available but not used by distribute strategy: /device:CPU:0
INFO:tensorflow:Configured nccl all-reduce.
2018-08-21 12:27:59.555447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1485] Adding visible gpu devices: 0, 1
2018-08-21 12:27:59.555515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-21 12:27:59.555524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:972]      0 1 
2018-08-21 12:27:59.555530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 0:   N Y 
2018-08-21 12:27:59.555535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:985] 1:   Y N 
2018-08-21 12:27:59.555693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10261 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-08-21 12:27:59.555813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1098] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11361 MB memory) -> physical GPU (device: 1, name: TITAN Xp, pci bus id: 0000:02:00.0, compute capability: 6.1)
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Partitioned variables are disabled when using DistributionStrategy.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:batch_all_reduce invoked for batches size = 6 with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
INFO:tensorflow:Error reported to Coordinator: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 175, in _call_for_each_tower
    **merge_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 660, in _distributed_apply
    self._create_slots(var_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/adagrad.py", line 73, in _create_slots
    with ops.colocate_with(v):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4080, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4132, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1285, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1124, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/values.py", line 445, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
Traceback (most recent call last):
  File "premade_estimator.py", line 84, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "premade_estimator.py", line 78, in main
    steps=args.train_steps,
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 343, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1166, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1294, in _train_model_distributed
    self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/distribute.py", line 857, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 418, in _call_for_each_tower
    return _call_for_each_tower(self, fn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 181, in _call_for_each_tower
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 175, in _call_for_each_tower
    **merge_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 660, in _distributed_apply
    self._create_slots(var_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/adagrad.py", line 73, in _create_slots
    with ops.colocate_with(v):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4080, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4132, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1285, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1124, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distribute/python/values.py", line 445, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError

```

**Comment by facaiy** [comment]
cc @ispirmustafa the authority on this issue.

**Comment by honeytidy** [comment]
I got the same errors when training using `MirroredStrategy`.

**Comment by olel-may** [comment]
I got the same error when training using `MirroredStrategy` with `AdamOptimizer` and `AdagradOptimizer`

**Comment by anj-s** [comment]
@yncxcw The issue with AdagradOptimizer should be fixed now. Can you try running your model again with the latest TensorFlow code? Thanks!

@olel-may I am not able to reproduce the issue with the AdamOptimizer. Do you have a standalone snippet of code which reproduces this issue?

**Comment by AmberCheng** [comment]
Why I still get this error? Do I need to renew the Tensorflow?

**Comment by anj-s** [comment]
@AmberCheng What version of TensorFlow are you using? Can you try with the latest version? If you still get this error, can you post a snippet of code that reproduces the issue?

**Comment by AmberCheng** [comment]
> @AmberCheng What version of TensorFlow are you using? Can you try with the latest version? If you still get this error, can you post a snippet of code that reproduces the issue?

Yep, I have install the Tensorflow 1.11, and there is no more this problem. Thank you~~~

**Comment by anj-s** [comment]
This issue should be fixed now. Please reopen this if you still encounter this error. Thanks!
