### ISSUE TITLE
cannot find  "flatbuffers/flatbuffers.h"  head  file

### ISSUE THREAD

**Issue by JuiYang** [tensorflow/tensorflow#21965]
in tensorflow/contrib/lite/schema/schema_generated.h file ::
```
#ifndef FLATBUFFERS_GENERATED_SCHEMA_TFLITE_H_
#define FLATBUFFERS_GENERATED_SCHEMA_TFLITE_H_

#include "flatbuffers/flatbuffers.h"
#include <string>
namespace tflite {}
```

I want to ask where is the "  flatbuffers/flatbuffers.h "  file .
I cannot find the  head   file in  tensorflow directory . 
 Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by aardappel** [comment]
It is pulled in by https://github.com/tensorflow/tensorflow/blob/master/third_party/flatbuffers/workspace.bzl

**Comment by julian59189** [comment]
What do I need to specify or do to get the flatbuffers build? they are not installed in the configure routine and also not in the bazel build process. Do I need to set any flags for the flatbuffers to build?

**Comment by DBraun** [comment]
I fixed my problem by cloning https://github.com/google/flatbuffers and including the path to "flatbuffers\include"

**Comment by Pradeepyrl** [comment]
@julian59189 did you figured it out? I am facing the same issue.
@dtsmith2001 Can you please elaborate your answer a bit. It's still not clear to me.

**Comment by mihaimaruseac** [comment]
@Pradeepyrl there is a script, `download_dependencies.sh` See instructions at https://www.tensorflow.org/lite/guide/build_rpi (even though link is for Raspberry Pi, most of the steps there apply on Linux too -- I just used them a few days ago)

Closing this issue as it has been already resolved and is old. If issue occurs again, please open a new one, filling in issue template

**Comment by SefaZeng** [comment]
It seems there is no download_dependencies.sh anymore. Is there a script to pull the flatbuffer now?

**Comment by mihaimaruseac** [comment]
The build changed to now use CMake. Please follow instructions at https://www.tensorflow.org/lite/guide/build_cmake and open a new issue if that does not work.

**Comment by HowardHonig** [comment]
Has anyone who controls this stuff figured out that this is too complicated for most people to use? Every time I tried to get examples to work on windows, I find something doesn't work.  I tried installing BAZEL on windows and can't even get that to install.  All these spurious tools that are required for tensorflow lite are ridiculous.  Every time something is attempted yet another program is needed.  And this thread is an example.  It appears that the library flatbuffers is needed for most TFLite projects and yet it is included as a "third-party" and not built.  What the *#*, that's horrible.  What are those people thinking?  Even tried d/l the source and compiling bazel but the README file is hopelessly out of date even, e.g. the [Install Bazel] in getting started has a broke link.  
What a crappy way of controlling what could be a valuable set of tools.  What immature kids control this stuff and constantly make changes without consideration of prior help/readme/books and files.  Books written to learn TFLite are out of date and most links of book written only 5 years ago are broken.  What don't these "masters of TFLite" get their act together?

**Comment by liry-code** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
