### ISSUE TITLE
BUG: reciprocal GPU kernel for complex 1/1 division not found

### ISSUE THREAD

**Issue by mayou36** [tensorflow/tensorflow#22384]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.2/7.2.1
- **GPU model and memory**: GeForce GTX 1050 mobile, 4096MiB
- **Exact command to reproduce**:
```
import tensorflow as tf
import numpy as np

# create a lot of points
# CHANGE NUMBER BELOW (higher -> fails)
n_points = 670000  # fails around > 650'000 (e.g. 1'000'000) for np.linspace generation


# points creation
points = np.ones(n_points)
# alternate points creation
# low = 100.  # irrelevant, only > 0 -> no 0 (division)
# high = 200.  # irrelevant
# points = tf.random_uniform(shape=[n_points], minval=low, maxval=high)
# points = np.linspace(low, high, n_points)

with tf.Session() as sess:
    # just do complex division: 1.0+0j / points
    complex_1_0 = tf.cast(1., dtype=tf.complex128)
    denom = tf.cast(points, dtype=tf.complex128)
    division = complex_1_0 / denom
    result = sess.run(division)
    print(result)
```

### Describe the problem
For a certain amount of points, the complex division kernel (or rather reciprocal kernel) "seems to not be available on the GPU".
**It works for**
- a lower number of points
- for floats
- on CPU (tested with "tf.devices")

**It seems to be independent of**
- the generation of the points (see commented lines for alternate creation)
- GPU (also tested on Tesla K80) with lower TF/Cuda version

No idea where to start...

### Source code / logs
relevant error:
NotFoundError (see above for traceback): No registered 'Reciprocal' OpKernel for GPU devices compatible with node truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
	 [[Node: truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)]]

Full stacktrace of failure: 
2018-09-19 17:18:40.965160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3010 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-09-19 17:18:41.104747: E tensorflow/core/common_runtime/executor.cc:697] Executor failed to create kernel. Not found: No registered 'Reciprocal' OpKernel for GPU devices compatible with node truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
	 [[Node: truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)]]
Traceback (most recent call last):
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Reciprocal' OpKernel for GPU devices compatible with node truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
	 [[Node: truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)]]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0ba75500be23>", line 1, in <module>
    runfile('/home/jonas/Documents/uni/Master_thesis/code/test/tf_playground/test/gpu_div_bug.py', wdir='/home/jonas/Documents/uni/Master_thesis/code/test/tf_playground/test')
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/usr/share/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jonas/Documents/uni/Master_thesis/code/test/tf_playground/test/gpu_div_bug.py", line 20, in <module>
    result = sess.run(division)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'Reciprocal' OpKernel for GPU devices compatible with node truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
	 [[Node: truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)]]
Caused by op 'truediv', defined at:
  File "/usr/share/pycharm/helpers/pydev/pydevconsole.py", line 511, in <module>
    pydevconsole.start_server(host, int(port), int(client_port), client_host)
  File "/usr/share/pycharm/helpers/pydev/pydevconsole.py", line 336, in start_server
    process_exec_queue(interpreter)
  File "/usr/share/pycharm/helpers/pydev/pydevconsole.py", line 192, in process_exec_queue
    more = interpreter.add_exec(code_fragment)
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_console_utils.py", line 281, in add_exec
    more = self.do_add_exec(code_fragment)
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_ipython_console.py", line 41, in do_add_exec
    res = bool(self.interpreter.add_exec(code_fragment.text))
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_ipython_console_011.py", line 442, in add_exec
    self.ipython.run_cell(line, store_history=True)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2907, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0ba75500be23>", line 1, in <module>
    runfile('/home/jonas/Documents/uni/Master_thesis/code/test/tf_playground/test/gpu_div_bug.py', wdir='/home/jonas/Documents/uni/Master_thesis/code/test/tf_playground/test')
  File "/usr/share/pycharm/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/usr/share/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jonas/Documents/uni/Master_thesis/code/test/tf_playground/test/gpu_div_bug.py", line 19, in <module>
    division = complex_1_0 / denom
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 958, in _truediv_python3
    return gen_math_ops.real_div(x, y, name=name)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 5881, in real_div
    "RealDiv", x=x, y=y, name=name)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/jonas/anaconda3/envs/zfit36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()
NotFoundError (see above for traceback): No registered 'Reciprocal' OpKernel for GPU devices compatible with node truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
	 [[Node: truediv = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)]]

**Comment by ymodak** [comment]
@mayou36 The fix has been pushed. #22420 Can you please confirm it?

**Comment by ymodak** [comment]
Cool. Please post your findings once you have it.

**Comment by Tal-Golan** [comment]
I am also suffering from this bug. Since the pull request was not accepted, this issue is still active and should be reopened.

**Comment by mayou36** [comment]
@ymodak this issue still persists in 1.12 (binary) and the corresponding PR #22420 has been closed and the branch deleted. Seems also that I am not the only one affected. Can we reopen this?

**Comment by ymodak** [comment]
@yongtang Do you have any updates on the PR #22420? Thanks!

**Comment by mayou36** [comment]
@azaks2 any updates here? I just stumbled in a completely different problem again on it (am I the only one doing complex divisions? :) )

For completeness the slighlty changed error message (from the example code above) which now incorporates the XLAs:

```python
NotFoundError (see above for traceback): No registered 'Reciprocal' OpKernel for GPU devices compatible with node node truediv (defined at <ipython-input-2-fde784715ebe>:18)  = Reciprocal[T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Cast_1)
	 (OpKernel was found, but attributes didn't match)
	.  Registered:  device='XLA_GPU'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_HALF]
  device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_HALF]
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_HALF]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
```

**Comment by jakelev** [comment]
I encountered this bug on a much smaller scale -- trying to do division on a single complex number.

```
x = tf.random.uniform(shape=())  # change to tf.constant(1.0) and error disappears
cx_x = tf.cast(x, dtype=tf.complex128)

numerator = 1  # change to 1.1 (error disappears) or 1.0 (throws same error)

with tf.Session() as sess:
  sess.run(numerator/cx_x)
```

Here's the error message:

> ---------------------------------------------------------------------------
> NotFoundError                             Traceback (most recent call last)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
>    1333     try:
> -> 1334       return fn(*args)
>    1335     except errors.OpError as e:
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
>    1318       return self._call_tf_sessionrun(
> -> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
>    1320 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
>    1406         self._session, options, feed_dict, fetch_list, target_list,
> -> 1407         run_metadata)
>    1408 
> 
> NotFoundError: No registered 'Reciprocal' OpKernel for GPU devices compatible with node {{node truediv_5}}
> 	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_COMPLEX128, _device="/job:localhost/replica:0/task:0/device:GPU:0"
> 	.  Registered:  device='XLA_GPU'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_HALF]
>   device='XLA_CPU'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_HALF]
>   device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_HALF]
>   device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_HALF]
>   device='GPU'; T in [DT_INT64]
>   device='GPU'; T in [DT_DOUBLE]
>   device='GPU'; T in [DT_HALF]
>   device='GPU'; T in [DT_FLOAT]
>   device='CPU'; T in [DT_COMPLEX128]
>   device='CPU'; T in [DT_COMPLEX64]
>   device='CPU'; T in [DT_DOUBLE]
>   device='CPU'; T in [DT_HALF]
>   device='CPU'; T in [DT_FLOAT]
> 
> 	 [[{{node truediv_5}}]]

**Comment by sachinprasadhs** [comment]
@mayou36 , This issue has been fixed in the recent Tensorflow GPU version 2.4.1, please find the [gist](https://colab.research.google.com/gist/sachinprasadhs/ab5150a0978cff62b3aff5dffc9029dd/22384.ipynb) here.

**Comment by mayou36** [comment]
Good to hear, many thanks for resolving this!
