### ISSUE TITLE
V1.11.0-rc2 still build fail with VERBS

### ISSUE THREAD

**Issue by snuzxj** [tensorflow/tensorflow#22455]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 and CentOS 7.5
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: build from source
- **TensorFlow version (use command below)**: Master and v1.11-rc2
- **Python version**: 2.7 and 3.5
- **Bazel version (if compiling from source)**: 0.16
- **GCC/Compiler version (if compiling from source)**: 4.8.5
- **CUDA/cuDNN version**: CUDA 9.1 and 9.2, cuDNN 7.2
- **GPU model and memory**: P100, Titan V
- **Exact command to reproduce**: Enable VERBS in config
Then, bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
In latest master (9/26), used following to compile:
bazel build --config=opt --config=cuda --config=verbs  //tensorflow/tools/pip_package:build_pip_package
Same error message as described blow.

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.
Same environment can build 1.10 successfully, but failed on 1.11

It seems this static member functions (static void tensorflow::RdmaMgr::RegMemVisitors()) try to directly access non-static member (RdmaAdapter* rdma_adapter_;)

> ERROR: /home/ai/tensorflow/tensorflow/contrib/verbs/BUILD:105:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma_mgr' failed (Exit 1)
In file included from tensorflow/contrib/verbs/rdma_mgr.cc:18:0:
./tensorflow/contrib/verbs/rdma_mgr.h: In static member function 'static void tensorflow::RdmaMgr::RegMemVisitors()':
./tensorflow/contrib/verbs/rdma_mgr.h:50:16: error: invalid use of member 'tensorflow::RdmaMgr::rdma_adapter_' in static member function
   RdmaAdapter* rdma_adapter_;
                ^
tensorflow/contrib/verbs/rdma_mgr.cc:282:40: error: from this location
     int32_t bus_id = TryToReadNumaNode(rdma_adapter_->context_->device) + 1;

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by gunan** [comment]
While this is not pretty, We will be cutting 1.12 in one week, so we wont have time to fix this in 1.11.

@jhseu do you know who supports libverbs?
Who can fix this for us, from our side or theirs?

**Comment by yongtang** [comment]
@snuzxj @gunan The PR #22415 will fix the issue I think.

**Comment by yongtang** [comment]
Actually, #22003 fixed the error mentioned in this issue. However, there were another compilation error with verbs that was introduced later (33170cc661f3838aa7d0d7fc19bb0c6ba4812a3c). The other compilation error will be fixed by #22415.

**Comment by yongtang** [comment]
@snuzxj The PR #22415 has been merged in the master. It is unlikely to be in r1.11 given the timeline though. I think maybe we could consider this issue fixed now?

**Comment by snuzxj** [comment]
@yongtang just tried the new master. Got an Error:

> ERROR: /home/ai/tensorflow/tensorflow/contrib/verbs/BUILD:105:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma_mgr' failed (Exit 1)
In file included from tensorflow/contrib/verbs/rdma_mgr.cc:18:0:
./tensorflow/contrib/verbs/rdma_mgr.h: In static member function 'static void tensorflow::RdmaMgr::RegMemVisitors()':
./tensorflow/contrib/verbs/rdma_mgr.h:50:16: error: invalid use of member 'tensorflow::RdmaMgr::rdma_adapter_' in static member function
   RdmaAdapter* rdma_adapter_;
                ^
tensorflow/contrib/verbs/rdma_mgr.cc:282:40: error: from this location
     int32_t bus_id = TryToReadNumaNode(rdma_adapter_->context_->device) + 1;

**Comment by yongtang** [comment]
@snuzxj I tried with the latest master and it works fine. Could it be that the dependency libraries are not properly installed on your machine.

**Comment by snuzxj** [comment]
@yongtang Thank you for the prompt feedback! I just tried again with latest master, but it still failed with the same error message. However, when I use 1.10, it built successfully. So, I don't think it related to dependency libraries on my machine. By the way, I am using mellanox driver for my RDMA device.

**Comment by yongtang** [comment]
@snuzxj Can you share your system information (Ubuntu, gcc version, etc), as was requested when you opened the issue?

**Comment by yongtang** [comment]
@snuzxj Thanks. The issue could be reproduced. The issue is similar to #22559. Not very familiar with this area so will need to take another look into how to fix it.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @jhseu, @yongtang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by zealotpb** [comment]
the problem exists with the latest source code.

**Comment by yanivbl6** [comment]
The problem itself is easy to fix, but doing so uncovers some additional problems, also from the same patch. I think I am close to a fix (Shouldn't be much different from the problems with GDR).

**Comment by yanivbl6** [comment]
Sorry, Seems like I was a bit hasty to talk, as I did not yet resolve all issues, and it may be a while longer (1-2weeks) before I can find the time to properly address and fix them.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @jhseu, @yongtang: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by changlan** [comment]
I can confirm that the issue still exists in the current master.

**Comment by calledbymountains** [comment]
I confirm that the issue exists in the current master as well as 1.12 branch

**Comment by juncgu** [comment]
That issue still appears in v1.12.0 when compiling TF from the source.

**Comment by tensorflowbutler** [comment]
Nagging Assignees @jhseu, @yongtang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by byronyi** [comment]
#24250 should fix this. @snuzxj could you confirm?

**Comment by axeln31459** [comment]
I just tried to compile r1.13 rc0 with --config=verbs and I still get the error below. Is there any update ? 

ERROR: /home/an/gits/tensorflow/tensorflow/contrib/verbs/BUILD:105:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma_mgr' failed (Exit 1)
tensorflow/contrib/verbs/rdma_mgr.cc: In static member function 'static void tensorflow::RdmaMgr::RegMemVisitors()':
tensorflow/contrib/verbs/rdma_mgr.cc:282:40: error: invalid use of member 'tensorflow::RdmaMgr::rdma_adapter_' in static member function
     int32_t bus_id = TryToReadNumaNode(rdma_adapter_->context_->device) + 1;
                                        ^~~~~~~~~~~~~
In file included from tensorflow/contrib/verbs/rdma_mgr.cc:18:0:
./tensorflow/contrib/verbs/rdma_mgr.h:50:16: note: declared here
   RdmaAdapter* rdma_adapter_;
                ^~~~~~~~~~~~~

**Comment by byronyi** [comment]
@axeln31459 r1.13 branch does not include #24250. You could patch that manually:

```bash
curl https://patch-diff.githubusercontent.com/raw/tensorflow/tensorflow/pull/24250.patch | git apply
```

and then compile again.

**Comment by byronyi** [comment]
@hgadig I believe this has been fixed. Could you close this issue?

**Comment by yongtang** [comment]
@byronyi Thanks! Close the issue as it has been fixed.
