### ISSUE TITLE
TOCO failed see console for info. 

### ISSUE THREAD

**Issue by soumy94** [tensorflow/tensorflow#22993]
INFO:
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
TensorFlow installed from (source or binary): Anaconda 
TensorFlow version (use command below): 1.11
Python version: 3.5
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
Exact command to reproduce:

Hi, 
 I've used the example given in [converter python api guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/convert/python_api.md)

import numpy as np
import tensorflow as tf
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(2, input_shape=(3,)))
model.add(tf.keras.layers.RepeatVector(3))
model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(3)))
model.compile(loss=tf.keras.losses.MSE,
              optimizer=tf.keras.optimizers.RMSprop(lr=0.0001),
              metrics=[tf.keras.metrics.categorical_accuracy],
              sample_weight_mode='temporal')
x = np.random.random((1, 3))
y = np.random.random((1, 3, 3))
model.train_on_batch(x, y)
model.predict(x)
keras_file = "keras_model.h5"
tf.keras.models.save_model(model, keras_file)
converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file(keras_file)
tflite_model = converter.convert()`

I ran this code and this is the error I get:

> RuntimeError: TOCO failed see console for info.
b'Traceback (most recent call last):\r\n  File "C:\\Users\\sgavvala\\AppData\\Roaming\\Python\\Python35\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 18, in swig_import_helper\r\n    fp, pathname, description = imp.find_module(\'_tensorflow_wrap_toco\', [dirname(__file__)])\r\n  File "c:\\users\\sgavvala\\appdata\\local\\continuum\\anaconda3\\envs\\tensorflow\\lib\\imp.py", line 297, in find_module\r\n    raise ImportError(_ERR_MSG.format(name), name=name)\r\nImportError: No module named \'_tensorflow_wrap_toco\'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "c:\\users\\sgavvala\\appdata\\local\\continuum\\anaconda3\\envs\\tensorflow\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "c:\\users\\sgavvala\\appdata\\local\\continuum\\anaconda3\\envs\\tensorflow\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "C:\\Users\\sgavvala\\AppData\\Local\\Continuum\\anaconda3\\envs\\tensorflow\\Scripts\\toco_from_protos.exe\\__main__.py", line 5, in <module>\r\n  File "C:\\Users\\sgavvala\\AppData\\Roaming\\Python\\Python35\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\toco_from_protos.py", line 22, in <module>\r\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\r\n  File "C:\\Users\\sgavvala\\AppData\\Roaming\\Python\\Python35\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 28, in <module>\r\n    _tensorflow_wrap_toco = swig_import_helper()\r\n  File "C:\\Users\\sgavvala\\AppData\\Roaming\\Python\\Python35\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 20, in swig_import_helper\r\n    import _tensorflow_wrap_toco\r\nImportError: No module named \'_tensorflow_wrap_toco\'\r\n'
None

My plan is to convert a keras model with my custom layers into tflite quantized version. Figured I would start with a given example but that doesn't seem to run.

**Comment by ymodak** [comment]
Please take a look at similar issue #22897 for updates. Your should be solved once this fix is pushed to tf-nightly.
I will keep this issue open to track it.

**Comment by soumy94** [comment]
> Please try installing tf-nightly and check if its still an issue. In addition take a look at similar issue #22897 for updates.

@ymodak I do have tf-nightly installed. I've noticed in the additional instructions for tensorflow version 1.9 to 1.11 to use **TocoConverter** instead of **TFLiteConverte**r and the problem still persists.

**Comment by ymodak** [comment]
Thanks for the information. Your issue should be solved once the latest fix is pushed to tf nightly.
https://github.com/tensorflow/tensorflow/issues/22897#issuecomment-429971818

**Comment by ymodak** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new). Please provide all the information it asks. Thank you.

**Comment by Skypatel70** [comment]
I have same issue. Is there a work around for now?

**Comment by maverik-akagami** [comment]
are the github pages missing for all the things related to TOCO?

**Comment by ymodak** [comment]
@soumy94 Can you please use the latest tf -nightly build and check? This issue should be fixed now.

**Comment by maverik-akagami** [comment]
I have tried it, it still has errors on windows 64-bit

**Comment by ymodak** [comment]
@maverik-akagami Apologies for the delay in response. The markdown files have been moved to tensorflow/tensorflow/lite/g3doc/convert/. I will close this issue due lack of activity. I recommend to open a new issue from [here](https://github.com/tensorflow/tensorflow/issues/new/choose) by providing all the information asked by the template. Thanks!
