### ISSUE TITLE
XLA Compiler Error "(...)C++ compilation of rule '//tensorflow/compiler/xla:window_util' failed (Exit 2): python.exe failed: error executing command"

### ISSUE THREAD

**Issue by gittyhub2018** [tensorflow/tensorflow#24890]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Version 1809 Betriebssystembuild: 17763.253
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source (install impossible)
- TensorFlow version: 1.12
- Python version: 3.6
- Installed using virtualenv? pip? conda?: virtualenv: yes; pip: yes anaconda: no
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source):-
- CUDA/cuDNN version: 10.0/7
- GPU model and memory: RTX 2070 8GB
- Microsoft Visual Studio Version: VS 2017 Enterprise (I am student)

**Describe the problem**
If i build the pip package, than  following error occured:

**Provide the exact sequence of commands / steps that you executed before running into the problem**

ERROR: F:/*/tensorflow/tensorflow/compiler/xla/BUILD:711:1: C++ compilation of rule '//tensorflow/compiler/xla:window_util' failed (Exit 2): python.exe failed: error executing command
  cd C:/users/bjoern_std/_bazel_bjoern_std/h2irjqdy/execroot/org_tensorflow

**Any other info / logs**
Log one step before the error and one step after:
"(...)Hinweis: Einlesen der Datei:    external/com_google_absl\absl/numeric/int128_no_intrinsic.inc
ERROR: F:/*/tensorflow/tensorflow/compiler/xla/BUILD:711:1: C++ compilation of rule '//tensorflow/compiler/xla:window_util' failed (Exit 2): python.exe failed: error executing command
  cd C:/users/*/_bazel_bjoern_std/h2irjqdy/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;F:\Windows Kits\10\include\10.0.17763.0\ucrt;F:\Windows Kits\10\include\10.0.17763.0\shared;F:\Windows Kits\10\include\10.0.17763.0\um;F:\Windows Kits\10\include\10.0.17763.0\winrt;F:\Windows Kits\10\include\10.0.17763.0\cppwinrt
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64;F:\Windows Kits\10\lib\10.0.17763.0\ucrt\x64;F:\Windows Kits\10\lib\10.0.17763.0\um\x64;
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools;F:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;F:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\;F:\Windows Kits\10\bin\10.0.17763.0\x64;F:\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Program Files/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Program Files/Python36/lib/site-packages
    SET TEMP=C:\Users\*~1\AppData\Local\Temp
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=7.0,7.5
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
    SET TMP=C:\Users\*~1\AppData\Local\Temp
  C:/Program Files/Python36/python.exe -B external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.py /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/genfiles /Ibazel-out/x64_windows-opt/bin /Iexternal/nsync /Ibazel-out/x64_windows-opt/genfiles/external/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/local_config_sycl /Ibazel-out/x64_windows-opt/genfiles/external/local_config_sycl /Ibazel-out/x64_windows-opt/bin/external/local_config_sycl /Iexternal/protobuf_archive /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive /Iexternal/com_google_absl /Ibazel-out/x64_windows-opt/genfiles/external/com_google_absl /Ibazel-out/x64_windows-opt/bin/external/com_google_absl /Iexternal/gif_archive /Ibazel-out/x64_windows-opt/genfiles/external/gif_archive /Ibazel-out/x64_windows-opt/bin/external/gif_archive /Iexternal/jpeg /Ibazel-out/x64_windows-opt/genfiles/external/jpeg /Ibazel-out/x64_windows-opt/bin/external/jpeg /Iexternal/com_googlesource_code_re2 /Ibazel-out/x64_windows-opt/genfiles/external/com_googlesource_code_re2 /Ibazel-out/x64_windows-opt/bin/external/com_googlesource_code_re2 /Iexternal/farmhash_archive /Ibazel-out/x64_windows-opt/genfiles/external/farmhash_archive /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive /Iexternal/fft2d /Ibazel-out/x64_windows-opt/genfiles/external/fft2d /Ibazel-out/x64_windows-opt/bin/external/fft2d /Iexternal/highwayhash /Ibazel-out/x64_windows-opt/genfiles/external/highwayhash /Ibazel-out/x64_windows-opt/bin/external/highwayhash /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/genfiles/external/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /Iexternal/snappy /Ibazel-out/x64_windows-opt/genfiles/external/snappy /Ibazel-out/x64_windows-opt/bin/external/snappy /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/genfiles/external/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/genfiles/external/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/protobuf_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/protobuf_archive/src /Ibazel-out/x64_windows-opt/bin/external/protobuf_archive/src /Iexternal/gif_archive/lib /Ibazel-out/x64_windows-opt/genfiles/external/gif_archive/lib /Ibazel-out/x64_windows-opt/bin/external/gif_archive/lib /Iexternal/gif_archive/windows /Ibazel-out/x64_windows-opt/genfiles/external/gif_archive/windows /Ibazel-out/x64_windows-opt/bin/external/gif_archive/windows /Iexternal/farmhash_archive/src /Ibazel-out/x64_windows-opt/genfiles/external/farmhash_archive/src /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive/src /Iexternal/zlib_archive /Ibazel-out/x64_windows-opt/genfiles/external/zlib_archive /Ibazel-out/x64_windows-opt/bin/external/zlib_archive /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/genfiles/external/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /DEIGEN_HAS_TYPE_TRAITS=0 /D__CLANG_SUPPORT_DYN_ANNOTATION__ /DTF_USE_SNAPPY /showIncludes /MD /O2 /DNDEBUG -w /arch:AVX /Fobazel-out/x64_windows-opt/bin/tensorflow/compiler/xla/_objs/window_util/window_util.o /c tensorflow/compiler/xla/window_util.cc
Execution platform: @bazel_tools//platforms:host_platform
Hinweis: Einlesen der Datei: .\tensorflow/compiler/xla/window_util.h(...)"
"(...) Hinweis: Einlesen der Datei:   external/com_google_absl\absl/strings/string_view.h
Hinweis: Einlesen der Datei:    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\cassert
Hinweis: Einlesen der Datei:     F:\Windows Kits\10\include\10.0.17763.0\ucrt\assert.h
Hinweis: Einlesen der Datei: .\tensorflow/core/platform/logging.h
Hinweis: Einlesen der Datei:  .\tensorflow/core/platform/default/logging.h
Hinweis: Einlesen der Datei:   .\tensorflow/core/platform/macros.h
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 536,864s, Critical Path: 314,01s
INFO: 2538 processes: 2538 local.
FAILED: Build did NOT complete successfully(...)"

NOTE from threadauthor: I have short the log, because they have only read acknowledges!
A star (*) in the path means, that i anonymised my account name!
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@gittyhub2018  Please check [tested build configurations](https://www.tensorflow.org/install/source_windows). Please check Bazel version. For the system configuration you mentioned, MSVC 2015, Bazel 0.15.0, cuDNN 7, CUDA 9.0  are supported. Could you try to installing CUDA 9.0 and check whether the issue persists? Thanks!

**Comment by jvishnuvardhan** [comment]
@samikama When you done with your exams try this [link](https://github.com/rnreich/ubuntu-tensorflow-gpu-all-versions) and install tensorflow-gpu and let us know the status. Thanks!

**Comment by samikama** [comment]
@jvishnuvardhan Did you mean to tag @gittyhub2018 ? I am not aware of any upcoming exams ;)

**Comment by jvishnuvardhan** [comment]
@samikama You are right. I meant to tag @gittyhub2018 . Sorry for the mistake. Thanks!

**Comment by jvishnuvardhan** [comment]
@gittyhub2018 Please let me know if the issue was resolved or not. If there was no response, I will assume it was resolved. Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue. Please open a new ticket when new information is available. Thanks!

**Comment by dksb** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by gittyhub2018** [comment]
> 
> 
> @gittyhub2018 Please check [tested build configurations](https://www.tensorflow.org/install/source_windows). Please check Bazel version. For the system configuration you mentioned, MSVC 2015, Bazel 0.15.0, cuDNN 7, CUDA 9.0 are supported. Could you try installing CUDA 9.0 and check whether the issue persists? Thanks!

I'm not able to install CUDA 9, because my hardware (RTX 2070) is newer than the supported Version.
I've upload a screenshot from the error of the CUDA 9 installer.
I don't have checked anymore after this error, because it make no sense. Any other idea or i must wait for a newer version?
![error_cuda_9](https://user-images.githubusercontent.com/33618201/52917464-2b33da80-32ec-11e9-9cc4-7fcb221641c9.jpg)

**Comment by jvishnuvardhan** [comment]
@gittyhub2018 You could try to install new version of TF. Please also check the solution provided [here](https://github.com/tensorflow/tensorflow/issues/25692) to disable the character limit on Windows10. Thanks!

**Comment by gittyhub2018** [comment]
I have install TF 2.0 nightly directly via pip and it works (See the code under these Article). I don't need to compiled it from source. At the beginning i thought with building from source i can use CUDA 10 with my graphic card. But this was my fault. Sry.
Only one information appear: AVX2 support ist not compiled with the nightly. Could this fixed in the final build?

` python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
2019-02-20 08:06:44.972272: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-02-20 08:06:45.013126: I tensorflow/stream_executor/platform/default/dso_loader.cc:161] successfully opened CUDA library nvcuda.dll locally
2019-02-20 08:06:45.389586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1464] Found device 0 with properties:
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.62
pciBusID: 0000:0a:00.0
totalMemory: 8.00GiB freeMemory: 6.59GiB
2019-02-20 08:06:45.395495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1543] Adding visible gpu devices: 0
2019-02-20 08:06:46.023658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-02-20 08:06:46.027051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0
2019-02-20 08:06:46.029131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N
2019-02-20 08:06:46.031437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1146] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6319 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:0a:00.0, compute capability: 7.5)
tf.Tensor(1558.7668, shape=(), dtype=float32)`

**Comment by jvishnuvardhan** [comment]
@gunan, 
*AVX2 support is not compiled with the nightly. Could this fixed in the final build (TF2.0)?*

**Comment by gunan** [comment]
Our pip builds aim to be able to work an the widest platforms possible.
If we build AVX2 into them, the packages wont work on a wide range of older CPUs.
So our packages will still not be built with avx2 in 2.0 final.
