### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'numpy' in image_captioning_with_attention.ipynb

### ISSUE THREAD

**Issue by DecentGradient** [tensorflow/tensorflow#25731]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): **2.0**
- Python version:3.x

**Describe the current behavior**
When running the code in 

> Caching the features extracted from InceptionV3
AttributeError: 'Tensor' object has no attribute 'numpy'

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
for img, path in tqdm(image_dataset):
  batch_features = image_features_extract_model(img)
  batch_features = tf.reshape(batch_features, 
                              (batch_features.shape[0], -1, batch_features.shape[3]))

  for bf, p in zip(batch_features, path):
    path_of_feature = p.numpy().decode("utf-8")
    np.save(path_of_feature, bf.numpy())
**Other info / logs**

AttributeError                            Traceback (most recent call last)
<ipython-input-15-9b3dc8e2ecd4> in <module>()
     15   for bf, p in zip(batch_features, path):
     16     path_of_feature = p.numpy().decode("utf-8")
---> 17     np.save(path_of_feature, bf.numpy())

AttributeError: 'Tensor' object has no attribute 'numpy'

**Comment by ymodak** [comment]
In order to expedite the trouble-shooting process, please provide a code snippet/weblink of the tutorial to reproduce the issue reported here. Thanks!

**Comment by DecentGradient** [comment]
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/generative/image_captioning.ipynb#scrollTo=Dx_fvbVgRPGQ

**Comment by ymodak** [comment]
Thanks for the link and creating this issue.

**Comment by DecentGradient** [comment]
Thanks for dealing with this!

**Comment by DecentGradient** [comment]
This is resolved in the alpha, closing

**Comment by bluemonk482** [comment]
I have installed the 2.0 alpha version but still get the `'Tensor' object has no attribute 'numpy'` error during runtime. Why? It works fines in ipython terminal. 

> Traceback (most recent call last):
>   File "cnn.py", line 192, in <module>
>     tf.app.run()
>   File "/home/bowang/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/home/aaa/.local/lib/python3.5/site-packages/absl/app.py", line 300, in run
>     _run_main(main, args)
>   File "/home/aaa/.local/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "cnn.py", line 161, in main
>     tf.estimator.train_and_evaluate(model, train_spec, eval_spec)
>   File "/home/aaa/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
>     return executor.run()
>   File "/home/aaa/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
>     return self.run_local()
>   File "/home/aaa/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
>     saving_listeners=saving_listeners)
>   File "/home/bowang/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 359, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/home/aaa/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1139, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "/home/aaa/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1169, in _train_model_default
>     features, labels, ModeKeys.TRAIN, self.config)
>   File "/home/aaa/.local/lib/python3.5/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1127, in _call_model_fn
>     model_fn_results = self._model_fn(features=features, **kwargs)
>   File "/data/home/BASELINES/tf_v2/network.py", line 140, in model_fn2
>     logits_train = conv_net(features, params, reuse=False, is_training=True)
>   File "/data/home/BASELINES/tf_v2/network.py", line 40, in conv_net
>     lens = np.array([len(xi) for xi in x.numpy()])
> AttributeError: 'Tensor' object has no attribute 'numpy'

**Comment by yashk2810** [comment]
This seems like the code is running with estimators. Can you share the code?

**Comment by bluemonk482** [comment]
@yashk2810 Yes I am. So I just call `model_fn`

```
model = tf.estimator.Estimator(model_fn, logdir, cfg, params)

def model_fn(features, labels, mode, params):

    logits_train = conv_net(features, params, reuse=False, is_training=True)
    logits_test = conv_net(features, params, reuse=True, is_training=False)
    pred_classes = tf.argmax(logits_test, axis=1)
    ... ...
    ... ...

```

conv_net function:

```
def conv_net(x_dict, params, reuse, is_training):
    # Define a scope for reusing the variables
    with tf1.variable_scope('ConvNet', reuse=reuse):
        x = x_dict['features']

        lens = np.array([len(xi) for xi in x.numpy()])
        mask = np.arange(lens.max()) < lens[:,None]
        padded = np.zeros(mask.shape)
        padded[mask] = np.hstack((x[:]))

        x = tf.reshape(padded, shape=[-1, padded.shape[1], 1])
        filter_sizes = [8, 16, 32, 64]

        pooled_outputs = []
        for filter_size in filter_sizes:
            with tf.name_scope('conv_maxpool-%s' % filter_size):
                conv1 = tf.layers.conv1d(x, 40, filter_size, strides=30, # 40 filters
                                        padding='same', activation=tf.nn.relu, 
                                        kernel_initializer=tf.keras.initializers.VarianceScaling()
                                        )

                pool1 = tf.reduce_max(input_tensor=conv1, axis=1)
                pooled_outputs.append(pool1)

        # Concatenation and flattening
        concat = tf.concat(pooled_outputs, axis=-1)
        flat = tf.keras.layers.Flatten()(concat)

        # add dropout

        with tf.name_scope("dense_layers"):
            fc1 = tf.layers.dense(flat, params['n_hidden_1'], activation=tf.nn.relu,
                                kernel_initializer=tf.keras.initializers.VarianceScaling()
                                )
            # add dropout (if is_training is False, dropout is not applied)
            dropout_1 = tf.layers.dropout(fc1, rate=params['dropout_rate'], 
                                    training=is_training)
                                
            out = tf.layers.dense(dropout_1, 4, kernel_initializer=tf.keras.initializers.VarianceScaling())

    return out
```

**Comment by bluemonk482** [comment]
@yashk2810 
Actually I have tried this with both tensorflow v2.0 and v1.12.0 (with `tf.enable_eager_execution()` ). So apparently if I call `numpy()` with the code snippet shown below in my `main()` function, it works perfectly. However if I use it in my estimator model function i.e., `model_fn(features, labels, mode, params)` then it complains that 'Tensor' object has no attribute 'numpy'.

```
ndarray = np.ones([3, 3])
tensor = tf.multiply(ndarray, 42)
print(tensor)
print(tensor.numpy())
```

Seems like a big issue for `tf.estimato`r no?
