### ISSUE TITLE
tensorflow/stream_executor/dso_loader.cc couldn't import cupti64_100.dll which exists in path

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#25807]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): gpu 1.13.0rc2
- Python version: 3.7.2
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0/7.4.2
- GPU model and memory: RTX2080Ti GDDR6 11GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
2019-02-17 16:49:22.874964: I tensorflow/stream_executor/dso_loader.cc:142] Couldn't open CUDA library cupti64_100.dll
2019-02-17 16:49:22.876813: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: could not dlopen DSO: cupti64_100.dll; dlerror: cupti64_100.dll not found

**Describe the expected behavior**
should import properly because it exists in path

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
python .\mnist_softmax_xla.py  in mnist tutorial

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

it works until few days ago
only i do recently is update nvidia driver to 418.91

**Comment by alanpurple** [comment]
![image](https://user-images.githubusercontent.com/4515120/52910032-06803880-32d5-11e9-87f2-a4a7627d0c30.png)

![image](https://user-images.githubusercontent.com/4515120/52910040-1dbf2600-32d5-11e9-9d79-ad55149e04fb.png)

**Comment by alanpurple** [comment]
same problem in other windows 10 machine, which has geforce mx150 GDDR5 2GB

**Comment by mrry** [comment]
Reassigning this to @yifeif, since I think she made the recent switch to dynamically loading CUDA DLLs, and might know of any pitfalls here.

**Comment by yifeif** [comment]
That is very odd. We didn't change the behavior of dsoloader or how we handle cupti.
@alanpurple when it worked for you before, was it the same pip package etc, and the only difference is the driver version?

**Comment by alanpurple** [comment]
@yifeif 
I uninstalled CUDA and reinstalled it, of course copy cudnn files and check CUPTI lib path again,
but same result

has anyone with latest windows 10 up to date + latest nvidia driver with 1.13.0rc2 binary build ever succeeded to open cupti64_100.dll?

**Comment by alanpurple** [comment]
strange thing is, yet cublas dll is successfully loaded

**Comment by alanpurple** [comment]
I have no idea what's related, but I just "git pull"ed and this problem has been resolved

closing this issue

**Comment by alanpurple** [comment]
confirmed.

In other machine this is resolved after conda upgrade --all( which upgrade python from 3.7.2-blahblah to 3.7.2-otherblahblah)

**Comment by yifeif** [comment]
Glad it's fixed!

**Comment by zubairahmed-ai** [comment]
I just installed TF 2 and updated my CUDA from `v9` to `v10` along with cuDNN but I am still getting similar error, environment variables are in place in Windows 10, system has been restarted, dlls are available in `\bin` under `CUDA\v10.0`

`W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found`

**Comment by cybaj** [comment]
Same error occurred here. 

```
tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found.
```

I don't know it is just related with that installed CUDA's version is `v10.1`, in my case.

- tensorflow 2.0.0
- CUDA 10.1
- windows 10 x64
- cuDNN 7.6.3
- gtx1060

of course, there are `cudart64_101.dll` in `CUDA\v.10.1`.

**Comment by zubairahmed-ai** [comment]
Check the environment variable and make sure it points to ~v10.0\bin~ instead of ~\v10.0~ only

I spent way too long figuring this out than I should have 😔

**Comment by drag05** [comment]
So, is this problem solved? I have all the requirements fulfilled and still get the error. If this is solved then where is the solution?

**Comment by tonandr** [comment]
In the Anaconda virtual environment of Windows 10, python 3.6.x or 3.7.x, CUDA 10.0.x, cuDNN 7.6.x, I have the same problem too, although PATH is correctly set including relevant dynamical libraries.

Error message: 2019-10-15 00:01:37.822980: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found

**Comment by zubairahmed-ai** [comment]
> In the Anaconda virtual environment of tensorflow-gpu 2.0.0, Windows 10, python 3.6.x or 3.7.x, CUDA 10.0.x, cuDNN 7.6.x, and 1 x GeForce GTX 960M (4097 MiB), I have the same problem too, although PATH is correctly set including relevant dynamical libraries.
> 
> Error message: 2019-10-15 00:01:37.822980: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found

@tonandr Did you see my comment above? make sure you are not making the same mistake as I did

**Comment by drag05** [comment]
Yes @zubairahmed-ai I have seen your comments above. Anything else?

**Comment by tonandr** [comment]
Yes, I checked @zubairahmed-ai's comments. In my case, after upgrading tensorflow to 2.0, this error happens. Still, tensorflow under 1.4 is imported correctly.

**Comment by HaiDuong93** [comment]
You should install Cuda 10.0. If you install Cuda 10.1, there is no file `cudart64_101.dll`. I rename `cudart64_101.dll` to `cudart64_100.dll,` then it work.

**Comment by drag05** [comment]
@HaiDuong93 : Not necessarily true! Please see my answer regarding: https://github.com/tensorflow/tensorflow/issues/33319#issuecomment-542253199

**Comment by tonandr** [comment]
My case isn't resolved yet.

**Comment by drag05** [comment]
Hello @tonandr, further to my earlier answer, you may want to check again this likely solved issue #33695 now closed. It clarifies some aspects on installing TensorfFlow from Python using Nvidia CUDA/CUDNN or installing TensorFlow from *conda using `cudatoolkit` in which case the Nvidia CUDA installation is not necessary.

**Comment by markhyro123** [comment]
I install CUDA v9 is that okey for the INTEL processor?

**Comment by drag05** [comment]
You need a NVIDIA graphic card for CUDA. For example, check this [article](url).

**Comment by CHIKKIZZY** [comment]
I think this error is related to tf.summary. To fix it, simply copy over cupti.lib and cupti64_100.dll in v10.0\extras\CUPTI\libx64 to v10.0\bin

**Comment by markhyro123** [comment]
> You need a NVIDIA graphics card for CUDA. For example, check this https://developer.nvidia.com/cuda-gpus or https://www.khronos.org/conformance/adopters/conformant-products/opencl

Thank you...

**Comment by JinluZhang1126** [comment]
> _Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
> 
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
> * TensorFlow installed from (source or binary): binary
> * TensorFlow version (use command below): gpu 1.13.0rc2
> * Python version: 3.7.2
> * Bazel version (if compiling from source): N/A
> * GCC/Compiler version (if compiling from source): N/A
> * CUDA/cuDNN version: 10.0/7.4.2
> * GPU model and memory: RTX2080Ti GDDR6 11GB
> 
> You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> You can also obtain the TensorFlow version with
> python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
> 
> **Describe the current behavior**
> 2019-02-17 16:49:22.874964: I tensorflow/stream_executor/dso_loader.cc:142] Couldn't open CUDA library cupti64_100.dll
> 2019-02-17 16:49:22.876813: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Failed precondition: could not dlopen DSO: cupti64_100.dll; dlerror: cupti64_100.dll not found
> 
> **Describe the expected behavior**
> should import properly because it exists in path
> 
> **Code to reproduce the issue**
> Provide a reproducible test case that is the bare minimum necessary to generate the problem.
> python .\mnist_softmax_xla.py in mnist tutorial
> 
> **Other info / logs**
> Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
> 
> it works until few days ago
> only i do recently is update nvidia driver to 418.91

I found this issue too,and you can just install `cudatoolkit` using conda, and version is same as the message system report, my error message is:dlerror: cudart64_100.dll not found
So I use: `conda install cudatollkit==10.0` to fix it.

**Comment by baicaigithub** [comment]
My fix is uninstalling the several version I had on my computer and reinstall cuda v10.

With this clean installation the folder does not have a 'v10' in it.

I'm on windows.

**Comment by GGDRriedel** [comment]
I fixed this by adding "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64" to my Windows PATH variable and restarting python/jupyter and so on which was not in it before. 
I installed TF with pip under Anaconda

**Comment by FarisHijazi** [comment]
For Windows users.

If the PATH variable is too long it won't work, you'll have to move it to the beginning.

![image](https://user-images.githubusercontent.com/47270244/73134865-ad746500-404c-11ea-8ab8-e3403eff466a.png)

Simply adding the path to the PATH environment variables isn't gonna work if PATH is too long, so I just moved to the beginning and it worked.

This happens because the PATH get's truncated (because there is a maximum length).

I hope this helps

**Comment by ErfanRoshan** [comment]
> In the Anaconda virtual environment of tensorflow-gpu 2.0.0, Windows 10, python 3.6.x or 3.7.x, CUDA 10.0.x, cuDNN 7.6.x, and 1 x GeForce GTX 960M (4097 MiB), I have the same problem too, although PATH is correctly set including relevant dynamical libraries.
> 
> Error message: 2019-10-15 00:01:37.822980: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found

Hi I have the same issue and fixed it with renaming all missing DLLs that I have them with _10.Dll
like it: I have cudart64_10.dll rename it to ==> cudart64_100.dll
this all DLLs are in CUDA10.1

**Comment by DavidS32** [comment]
![](https://user-images.githubusercontent.com/47270244/73134865-ad746500-404c-11ea-8ab8-e3403eff466a.png)

Where can I edit this things?!

**Comment by cocoyen1995** [comment]
I run in Anaconda and met the same problem.
I have CUDA install on my PC, and I copied the file

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\extras\CUPTI\libx64\cupti64_100.dll

to the path of Anaconda's envs

> C:\Users\Coco\AppData\Local\Continuum\anaconda3\envs\ACE_DC_py372\Library\bin

and the kernel died disappeared!

**Comment by Rifat004** [comment]
How did you solve the issue

**Comment by cocoyen1995** [comment]
> How did you solve the issue

Hi @Rifat004 ,

There are many solutions provided above, I don't know which one are you asking for (?)
(Since you didn't describe your case, there's no clue at all...)
In my case, the running env is in Anaconda, and it seems like it couldn't find **cupti64_100.dll** under my env's running path,
so I copied that file from CUDA's directory I install from [nvidia's website](https://developer.nvidia.com/cuda-10.0-download-archive)
Hope this help!

**Comment by chrispytoes** [comment]
I also can't seem to get any of these solutions to work for me. Here is my error:
```
2021-06-06 15:22:42.083594: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-06-06 15:22:42.083750: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```

I just installed CUDA 11.3, and I can see the `curart64_110.dll` file inside `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin`, and my environment variables look fine.

Environment:
```
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
CUDA_PATH_V10_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
CUDA_PATH_V11_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
CUDA_PATH_V11_3=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
```
All of those different versions of CUDA are installed, and confirmed definitely exist in those folders.
`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin` is in my `PATH` as well.

**Comment by GGDRriedel** [comment]
> 
> 
> @zubairahmed-ai @baicaigithub i am on windows with cudav9 and python3.7 i am still getting the error "tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found" i have installed tensorflow-gpu =1.15.0 can you let me knw what the solution for this

This cann't work for you if you are on V9

**Comment by GGDRriedel** [comment]
> 
> 
> I also can't seem to get any of these solutions to work for me. Here is my error:
> 
> ```
> 2021-06-06 15:22:42.083594: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
> 2021-06-06 15:22:42.083750: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> ```
> 
> I have a GTX 1070. I just installed CUDA 11.3, and I can see the `cudart64_110.dll` file inside `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin`, and my environment variables look fine.
> 
> Environment:
> 
> ```
> CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
> CUDA_PATH_V10_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
> CUDA_PATH_V11_2=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
> CUDA_PATH_V11_3=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
> ```
> 
> All of those different versions of CUDA are installed, and confirmed definitely exist in those folders.
> `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin` is in my `PATH` as well.

Look at your error. It is looking for V11.0

**Comment by chrispytoes** [comment]
@GGDRriedel All the 11.x versions contain a DLL with the same name. I installed 11.0 and I still get the same error.

**Comment by GGDRriedel** [comment]
> 
> 
> @GGDRriedel All the 11.x versions contain a DLL with the same name. I installed 11.0 and I still get the same error.
> 
> Edit: I followed the Windows instructions at the bottom of the page [here](https://www.tensorflow.org/install/gpu). I added the path to cuDNN to the PATH, and the paths to the other directories mentioned there. Still getting the same error.

True, but I'm not sure the correct folder is found. I think it's looking for a folder named v11.0

**Comment by FarisHijazi** [comment]
@DavidS32 
> Where can I edit this things?!

[Windows environment variables](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0), set the PATH variable
