### ISSUE TITLE
Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor

### ISSUE THREAD

**Issue by baslia** [tensorflow/tensorflow#25980]
Hi,
I am using python 3.6.8 and the last keras and tensorflow (1.12.0)version.
When I build something like that, it works:

```
x=keras.layers.Input(shape=(100,),sparse=False)
x1=keras.layers.Dropout(0.2)(x)
```

But the following code would give an error:
```
x=keras.layers.Input(shape=(100,),sparse=True)
x1=keras.layers.Dropout(0.2)(x)
```

The detailed error is 
_TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("input_30/indices:0", shape=(?, 2), dtype=int64), values=Tensor("dropout_28/cond/mul:0", shape=(?,), dtype=float32), dense_shape=Tensor("input_30/shape:0", shape=(2,), dtype=int64)). Consider casting elements to a supported type._

I think it is a bug but I am not sure.

Thanks a lot.

Regards.

**Comment by yongtang** [comment]
When I tried with tf-nightly, could not reproduce. I think the issue may have been fixed. Could you retry with tf-nightly?

**Comment by ymodak** [comment]
@yongtang I tried with TF-nightly (version:1.13.0-dev20190221) the issue still persists.

**Comment by baslia** [comment]
Thanks for you reply guys.
To be more specific, I am doing it on the mkl version of tensorflow (not the GPU one).

**Comment by theoqian** [comment]
I got a similar error when I use tensorflow_ranking and export_savedmodel for serving. I created an issue here: https://github.com/tensorflow/ranking/issues/68 . Are they caused by the same problem? Thanks.

**Comment by FloraDanica** [comment]
I encounter a same error, so how to deal with it? please?
TypeError: Failed to convert object of type <class 'tensorflow.python.util.deprecation_wrapper.DeprecationWrapper'> to Tensor. Contents: <module 'tensorflow' from '/home/xiongyuanpeng/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py'>. Consider casting elements to a supported type.

**Comment by F-Node-Karlsruhe** [comment]
I have the same issue with tf 2.2.0 
I tried to convert the Sparse tensors by hand what worked out fine, os they definitely can e converted. No operator error yet.

**Comment by lordfiftyfive** [comment]
why not use tf.sparse.to_dense(x)

**Comment by F-Node-Karlsruhe** [comment]
I need sparse tensors as usual tensors are too large. is the a possibility to use to_dense() in the Keras model, i.e. just before usage?

**Comment by thomashirtz** [comment]
Just had the same issue
Impossible to input sparse tensor to an input layer, it causes the conversion error

**Comment by javaarch4u** [comment]
Facing exact problem while following the guide (training ngram text classification model) at https://developers.google.com/machine-learning/guides/text-classification/step-4 Appreciate any inputs.. Thank you

**Comment by TKlie** [comment]
Same issue here when trying to pass a one hot encoded sparse matrix into a Sequential model (LSTM layer). Any ideas/advice on how to proceed (without having to manually en- and decode labels at every step of the way)?

**Comment by Crashtime** [comment]
Facing the same problem in tensorflow 2.3 using tf.linalg.matmul(a,b, a_is_sparse=True,b_is_sparse=True)


`File ".py", line 147, in <module>
    customer_features = tf.linalg.matmul(sparse_customer_product, sparse_product_features, a_is_sparse=True, b_is_sparse=True)
  File "--/.local/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "--/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 3191, in matmul
    a = ops.convert_to_tensor(a, name="a")
  File "/--/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "--/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 338, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "--/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    allow_broadcast=True)
  File "--/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 275, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "--/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 300, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "--/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 98, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (<tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f2ce05f8860>) with an unsupported type (<class 'tensorflow.python.framework.sparse_tens
or.SparseTensor'>) to a Tensor.`

**Comment by AssassinTee** [comment]
```python
import tensorflow as tf
from tensorflow import keras
print(tf.__version__)
header_input = keras.Input(shape=(10,), name='header', sparse=True, batch_size=10)
header_features = keras.layers.Reshape((1, 10))(header_input)
```

```console
2.3.1
[...]
TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("header/indices_3:0", shape=(None, 2), dtype=int64), values=Tensor("header/values_3:0", shape=(None,), dtype=float32), dense_shape=Tensor("header/shape_3:0", shape=(2,), dtype=int64)). Consider casting elements to a supported type.
```

**Comment by mullanptr** [comment]
I also have this problem, on a basic NLP problem.
My data is actually presented in numpy ndarrays.
So I do not even know why it assumes it is of dtype tf.sparse.

Also, I have not many Zeros in the np.ndarrays... Really strange, and no idea how to debug...

**Comment by AmoJia** [comment]
> Facing exact problem while following the guide (training ngram text classification model) at https://developers.google.com/machine-learning/guides/text-classification/step-4 Appreciate any inputs.. Thank you

I also have this problem when I followed this tutorial. Have you solved it?

**Comment by baslia** [comment]
Hello, 2 years later I have the same issue, but not the same error (I am using TensorFlow 2.4.1):
`import tensorflow as tf
print(tf.__version__)
header_input = tf.keras.Input(shape=(10,), name='header', sparse=True, batch_size=10)
x = header_input
header_features = tf.keras.layers.Dense(10)(x)`

Is working fine

But when I use dropout:
`import tensorflow as tf
print(tf.__version__)
header_input = tf.keras.Input(shape=(10,), name='header', sparse=True, batch_size=10)
x = tf.keras.layers.Dropout(0.1)(header_input)
header_features = tf.keras.layers.Dense(10)(x)`

I have the following error:

>   File "/data/conda/baslad01/conda_envs/tf2/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1182, in build
    raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

**Comment by hoondy** [comment]
> It works, because it converts an input batch only on runtime and I am not running OOM (Out of Mana). This however comes with the downside of longer training and prediction times.

Does this really slow down the runtime? I found this solution (tf.sparse.to_dense) to be the only viable solution at the moment. If I want to improve the runtime, what else can I do?

**Comment by ymodak** [comment]
> x=keras.layers.Input(shape=(100,),sparse=True)
> x1=keras.layers.Dropout(0.2)(x)

This is fixed TF 2.4.1. See [gist](https://colab.research.google.com/gist/ymodak/36c744a25affa7c74147d5cccbf94140/git44970.ipynb) for reference. Thanks!

For other related issues it's better to create a new issue thread and tag this issue for reference. Thanks!

**Comment by DanielMH** [comment]
It seems I encountered a similar problem when I tried the [Google Machine Learning Guide on Text Classification](https://developers.google.com/machine-learning/guides/text-classification/) 

Adding todense() solved it for me:

x_train = vectorizer.fit_transform(train_texts).todense()
x_val = vectorizer.transform(val_texts).todense()

**Comment by tamirbennatan** [comment]
If you're getting this error while following the [TFX Keras Component Tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/components_keras) (as I was), then my problem was solved by setting the `infer_schema_shape` to `True` in the `SchemaGen` component.

Related: https://github.com/tensorflow/tfx/issues/1495#issuecomment-600603285

**Comment by DanielMH** [comment]
Here you can find more related comments:

https://github.com/tensorflow/tensorflow/issues/47931#issue-836309758
