### ISSUE TITLE
Remove all TF Logging 

### ISSUE THREAD

**Issue by oroojlooy** [tensorflow/tensorflow#26288]
I wanted to exclude all of the tensorflow logs in output. I searched and found that one or both of these setting should work:

    os.environ['TF_CPP_MIN_LOG_LEVEL']='3'
    tf.logging.set_verbosity(tf.logging.ERROR)

Though, I am still getting network loading logs, e.g.:

    2019-02-28 23:51:13,520:INFO::Restoring parameters from ./pre_model/classic/brain4/network--6009999

I was wondering why the `INFO` logs are still there. I also searched a lot about it and read the previous issues, but neither had a certain solution for this problem. 

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 8.7
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.1
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: K80 12GB
- **Exact command to reproduce**: 
```
checkpoint = tf.train.get_checkpoint_state(os.path.join(directory, saved_model_address))
tf.train.Saver.restore(session, checkpoint.model_checkpoint_path)

```
in which `saved_model_address` is the address of the saved model, and session is an instance of  tf.Session() which the model is created in.

**Comment by ymodak** [comment]
@vrv @yaroslavvb Can you please take a look? Thanks!

**Comment by ymodak** [comment]
duplicate #1258

**Comment by vrv** [comment]
That log statement appears to be a python log statement in saver.py, so the set_verbosity call should work.

>>> import tensorflow as tf
>>> tf.logging.info('hi')
INFO:tensorflow:hi
>>> tf.logging.set_verbosity(tf.logging.ERROR)
>>> tf.logging.info('hi')
>>> 

Maybe add some well-placed print statements to 

https://github.com/tensorflow/tensorflow/blob/a3786f5d589a3b10f6152558dfb6f19070a6f30d/tensorflow/python/platform/tf_logging.py#L156

to figure out what the verbosity level is when that line is printed out, and see why it's not being set properly.

**Comment by vrv** [comment]
Also I can't seem to reproduce this in the latest version of TF on my Ubuntu-based machine:

>>> tf.logging.set_verbosity(tf.logging.INFO)
>>> saver.restore(s, cs.model_checkpoint_path)
INFO:tensorflow:Restoring parameters from /path....

>>> tf.logging.set_verbosity(tf.logging.ERROR)
>>> saver.restore(s, cs.model_checkpoint_path)
(No INFO log is printed).

Perhaps this is fixed in a newer version of TF?

**Comment by ymodak** [comment]
Closing since this behavior is not observed in the latest version of TF. Feel free to reopen if have any further conflicts. Thanks!

**Comment by oroojlooy** [comment]
Sorry for late response. 
I updated to tensorflow 1.12.2, and still get the info logs:

` 2019-04-22 23:43:44,608:INFO::Restoring parameters from ./pre_model/uniform/0-9/brain4/network--6009999`

`Successfully loaded: ./pre_model/uniform/0-9/brain4/network--6009999
`
