### ISSUE TITLE
Training parameter in Keras models passed as None in 1.13

### ISSUE THREAD

**Issue by janhartman** [tensorflow/tensorflow#26319]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary(pip)
- TensorFlow version (use command below): v1.13.1-0-g6612da8951 1.13.1
- Python version: 3.5.2
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 10, cuDNN 7.5
- GPU model and memory: GTX 1050ti, 4GB

**Describe the current behavior**
As described in the third example in [the documentation for Keras models](https://www.tensorflow.org/api_docs/python/tf/keras/models/Model#class_model), a boolean `training` parameter can be used in the `call` method of subclassed models. However, the parameter is passed as `None` when it should be `True`. 

**Describe the expected behavior**
The training parameter should be passed as True when the model is training.

**Code to reproduce the issue**

```
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

class MyModel(tf.keras.Model):
  def __init__(self):
    super(MyModel, self).__init__()
    self.dense = tf.keras.layers.Dense(4)

  def call(self, inputs, training=False):
    print('Training', training)
    return self.dense(inputs)
    
model = MyModel()
model.compile(optimizer=tf.train.AdagradOptimizer(0.001), loss='categorical_crossentropy', metrics=['accuracy'])

inp = np.ones((5, 3), dtype=np.float32)
out = np.ones((5, 4), dtype=np.float32)

# training should be False
model(inp)

# training should be True
model.fit(inp, out)
```

**Other info / logs**
This only happens in TF 1.13 and not in 1.12. I also tried 2.0 alpha and the bug is still present

**Comment by janhartman** [comment]
Hi, has there been any progress in regard to this?

**Comment by janhartman** [comment]
Hi @pavithrasv, has there been any progress in regard to this?

**Comment by pavithrasv** [comment]
@janhartman I was able to reproduce this issue. Will look into the fix.

**Comment by jvishnuvardhan** [comment]
@janhartman I think this was resolved in the latest TF versions (`TF1.14.0` and `tf-nightly`). I cannot reproduce the issue. Please check the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/4c95c00604552800c6201c651dd758c8/untitled428.ipynb) with `TF1.14.0`.

Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Thanks!

**Comment by janhartman** [comment]
@jvishnuvardhan It's not completely solved. The parameter is now a bool tensor instead of a plain bool, but it's better than before. Thanks!
