### ISSUE TITLE
Issue on converting yolo to tflite with bazel-bin toco

### ISSUE THREAD

**Issue by antonino-tocco** [tensorflow/tensorflow#26545]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.10
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):  master

**Provide the text output from tflite_convert**

```
I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: ExtractImagePatches
2019-03-10 16:38:02.722378: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 211 operators, 370 arrays (0 quantized)
2019-03-10 16:38:02.727060: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 211 operators, 370 arrays (0 quantized)
2019-03-10 16:38:03.193935: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 97 operators, 189 arrays (0 quantized)
2019-03-10 16:38:03.195613: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 97 operators, 189 arrays (0 quantized)
2019-03-10 16:38:03.196705: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 97 operators, 189 arrays (0 quantized)
2019-03-10 16:38:03.198405: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 68550208 bytes, theoretical optimal value: 66453504 bytes.
2019-03-10 16:38:03.202350: E tensorflow/lite/toco/toco_tooling.cc:456] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONCATENATION, CONV_2D, MAXIMUM, MAX_POOL_2D, MUL, PAD. Here is a list of operators for which you will need custom implementations: ExtractImagePatches.
We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONCATENATION, CONV_2D, MAXIMUM, MAX_POOL_2D, MUL, PAD. Here is a list of operators for which you will need custom implementations: ExtractImagePatches.

```

Also, please include a link to a GraphDef or the model if possible.

Model is retrainer yolo

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@antonino-tocco Could you add more details on the context of the issue and the process you followed leading to the bug? Please provide a  code to reproduce the bug. Thanks!

**Comment by antonino-tocco** [comment]
Hi @jvishnuvardhan, thanks for your help.
I follow this tutorial for retrain yolo: https://www.tooploox.com/blog/card-detection-using-yolo-on-android.
I train my model, convert it to protobuf with darkflow and then i try to convert it to tflite for embedd it on my Android app with baze-bin toco. I receive issue for non tflite operators such as ExtractImagePatches.

**Comment by jvishnuvardhan** [comment]
@antonino-tocco Could you provide full command of tflite_convert? Thanks!

**Comment by antonino-tocco** [comment]
Sure.
/bazel-bin/tensorflow/lite/toco/toco   --input_file=yolo-obj.pb   --output_file=foo.tflite    --input_format=TENSORFLOW_GRAPHDEF   --output_format=TFLITE   --input_arrays=input   --input_shapes=1,416,416,3
Thanks for your help.

**Comment by antonino-tocco** [comment]
Hi, any news?

**Comment by miaout17** [comment]
It's missing an ExtractImagePatches op in TensorFlow Lite. 
@talumbau could you take a look to see should we implement it as a TensorFlow Lite builtin op?

Meanwhile, we have an experimental feature that you can use TensorFlow kernel in TensorFlow Lite. 
Feel free to try it if you're interested and give us feedbacks. 
https://www.tensorflow.org/lite/guide/ops_select

**Comment by himanshurobo** [comment]
2019-03-27 14:56:19.740750: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746180: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746229: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746244: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746260: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746272: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746287: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746297: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746312: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746324: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746369: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746383: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746407: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746418: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746434: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746446: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746459: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746470: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746485: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746496: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746539: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746552: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746576: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746587: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746706: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746718: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746733: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746744: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746761: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746772: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746814: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746827: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746852: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746864: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746880: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746891: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746907: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746918: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746933: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746944: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.746985: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.746998: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747025: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747036: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747053: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747065: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747081: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747092: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747110: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747122: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747172: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747185: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747212: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747225: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747242: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747254: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747271: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747282: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747299: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747310: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747351: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747364: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747390: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747402: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747419: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747431: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747447: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747459: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747475: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747488: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747531: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747544: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747573: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747586: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747603: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747615: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747632: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747644: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747661: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747673: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747720: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747733: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747763: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747776: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747793: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747804: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747822: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747834: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747852: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747863: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747906: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747920: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747948: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747961: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.747980: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.747992: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748010: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748021: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748038: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748050: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748093: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748106: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748136: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748149: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748166: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748179: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748196: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748207: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748224: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748236: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748282: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748295: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748323: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748336: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748353: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748364: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748381: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748393: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748410: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748421: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748464: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748477: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748506: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748519: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748536: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748548: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748565: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748577: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748594: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748605: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748651: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748665: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748697: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748710: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748732: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748744: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748766: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748778: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748800: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748811: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748854: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748867: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748897: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748910: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748928: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748940: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.748957: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.748993: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749016: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749037: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749088: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749119: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749149: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749181: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749200: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749211: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749230: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749250: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749279: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749290: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749337: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749359: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749385: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749397: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749413: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749424: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749441: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749451: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749466: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749485: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749522: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749533: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749563: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749575: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749594: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749605: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749624: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749634: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749653: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749664: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749699: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749710: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749744: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749756: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749776: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749786: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749804: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749814: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749833: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749843: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749882: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749894: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749924: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749935: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749954: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749964: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.749983: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.749993: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750011: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750021: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750060: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750072: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750097: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750108: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750123: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750133: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750147: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750157: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750172: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750182: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750234: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750246: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750276: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750288: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750306: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750317: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750335: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750345: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750364: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750374: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750410: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750421: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.750436: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: VariableV2
2019-03-27 14:56:19.750447: I tensorflow/lite/toco/import_tensorflow.cc:1335] Converting unsupported operation: Assign
2019-03-27 14:56:19.755191: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 619 operators, 829 arrays (0 quantized)
2019-03-27 14:56:19.761903: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 391 operators, 419 arrays (0 quantized)
2019-03-27 14:56:19.766917: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 391 operators, 419 arrays (0 quantized)
2019-03-27 14:56:19.772167: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 278 operators, 351 arrays (0 quantized)
2019-03-27 14:56:19.775999: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 278 operators, 351 arrays (0 quantized)
2019-03-27 14:56:19.779054: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before dequantization graph transformations: 278 operators, 351 arrays (0 quantized)
2019-03-27 14:56:19.782410: I tensorflow/lite/toco/allocate_transient_arrays.cc:345] Total transient array allocated size: 94371840 bytes, theoretical optimal value: 94371840 bytes.
2019-03-27 14:56:19.783404: E tensorflow/lite/toco/toco_tooling.cc:456] We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, LEAKY_RELU, MAX_POOL_2D, MUL, RESHAPE, RSQRT, TRANSPOSE. Here is a list of operators for which you will need custom implementations: BatchNormalization, VariableV2.
We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:





Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, LEAKY_RELU, MAX_POOL_2D, MUL, RESHAPE, RSQRT, TRANSPOSE. Here is a list of operators for which you will need custom implementations: BatchNormalization, VariableV2.





I had a same issue with yolo. 
I have used  command `/bazel-bin/tensorflow/lite/toco/toco   --input_file=/newhd/dev/darkflowToTensorflow/data/yolo-voc.pb   --output_file=foo.tflite    --input_format=TENSORFLOW_GRAPHDEF   --output_format=TFLITE   --input_arrays=input   --input_shapes=1,416,416,3   --output_arrays=yolov2/convolutional23/BiasAdd    --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS`

**Comment by gargn** [comment]
Can you try rerun the tutorial from the "Convert .weights to a frozen graph" step? This might have been fixed in by https://github.com/tensorflow/tensorflow/commit/0f486fc67070ba888204741c404a55a5f1a41fbc.

**Comment by antonino-tocco** [comment]
Hi, thank you to all for the help. I can retry on this weekend. I will update you

**Comment by huiyujie** [comment]
@himanshurobo Hi, I have the same issue with you. I also have added --target_ops. But it's still not working. Have you fixed it? Thanks

**Comment by ambr89** [comment]
Hi!

I've download tf folder from here: [https://github.com/tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) and I run this command

' 
$ cd tensorflow-master   
$ bazel run tensorflow/lite/toco:toco -- \
    --input_file=my.pb \
    --output_file=out.tflite \
    --input_shapes=1,416,416,3 \
    --input_arrays='input_1' \
    --output_format=TFLITE \
    --output_arrays='output_0','output_1' \
    --inference_type=QUANTIZED_UINT8 \
    --std_dev_values=128 --mean_values=128 \
    --default_ranges_min=-6 --default_ranges_max=6 \
    --change_concat_input_ranges=false \
    --allow_custom_ops
'

**Comment by mohantym** [comment]
Hi @antonino-tocco ! I converted the yolo frozen graph file using TFlite converter api. Attaching [gist ](https://colab.sandbox.google.com/gist/mohantym/8712339f9de1757e114589f657da06fb/github_26545.ipynb)for reference. Thanks!
