### ISSUE TITLE
TF 2.0 Keras model utilizing another model with metrics cannot fit/evaluate in graph mode (mistakenly using the metrics of the inner model)

### ISSUE THREAD

**Issue by foxik** [tensorflow/tensorflow#26738]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **YES**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux Debian Stable**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **CPU, both TF-2.0.0a0 and tf-nightly-2.0-preview-2.0.0.dev20190315**
- Python version: **3.5.3**
- Bazel version (if compiling from source): **N/A**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A**
- GPU model and memory: **N/A**

**Describe the current behavior**
When running the script below, it fails during execution with error
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'dense_target' with dtype float and shape [?,?]
```

**Describe the expected behavior**
The code should not crash.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf

inputs = np.arange(10)
outputs = 2 * inputs

inner_model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape=[1])])
inner_model.compile(optimizer=tf.keras.optimizers.Adam(),
                    loss=tf.keras.losses.MeanSquaredError(),
                    metrics=[tf.keras.metrics.MeanSquaredError()])

outer_inputs = tf.keras.layers.Input(shape=[1])
outer_outputs = inner_model(outer_inputs)
outer_model = tf.keras.Model(inputs=outer_inputs, outputs=outer_outputs)
outer_model.compile(optimizer=tf.keras.optimizers.Adam(),
                    loss=tf.keras.losses.MeanSquaredError(),
                    metrics=[tf.keras.metrics.MeanSquaredError()])
outer_model.evaluate(inputs, outputs) # crashes
outer_model.fit(inputs, outputs) # also crashes
```

**Other info / logs**
- `outer_model.predict` works
- when `outer_model.run_eagerly=True`, then `outer_model.{evaluate/fit}` works
- when the inner model has no metrics (`metrics=[]` in `inner_model.compile`), then `outer_model.{evaluate/fit}` works

I have trace the problem to an incorrect FuncGraph generated -- it mistakenly uses the metrics from the _inner graph_ (i.e., the metrics calculations utilize the _original_ placeholders of the inner graph).

**Comment by foxik** [comment]
The name conflict is further supported by the fact that naming the metric in the `outer_model` differently, as in
```python
outer_model.compile(optimizer=tf.keras.optimizers.Adam(),
                    loss=tf.keras.losses.MeanSquaredError(),
                    metrics=[tf.keras.metrics.MeanSquaredError(name="outer_model")])
```
also makes `outer_model.{evaluate/fit}` work.

**Comment by RobbertD** [comment]
Is there a workaround for this? (Preferably without using Sequential() )

**Comment by pavithrasv** [comment]
https://github.com/tensorflow/tensorflow/commit/659c981a3556c6424237eacd0bf4cdc86f228f16 should fix this issue. Please give it a try in the next nightly and let me know if it works as expected.

Thank you!

**Comment by foxik** [comment]
I can confirm that `tf-nightly==1.14.1.dev190623` fixes the issue, and that `tf-nightly==1.14.1.dev190620` was still broken.

**Comment by pavithrasv** [comment]
Great, thank you for verifying!
