### ISSUE TITLE
get "virtual memory exhausted: Cannot allocate memory" in Makefile

### ISSUE THREAD

**Issue by tjcooperforted** [tensorflow/tensorflow#26975]
when installing Tensorflow models with:
sudo make install     I get "Error 1" when making argmax_op_0

re ran the make file several times after rebooting Raspberry Pi 3 B+
and get same error each time.

**Comment by ymodak** [comment]
Please provide following information. Thanks!
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:



**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**


**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tjcooperforted** [comment]
Thanks for quick response.  All of my steps come EXACTLY from the MagicPi description of how to install tensorflow on a RaspberryPi 3B+  system.  The only unusual things I have is a 120GB SSD as my storage system.  Here are instructions:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile

I have inserted below answer to specific questions.

 

I noticed that the two EXPORT steps listed were not being honored by the build so I manually caused them to be executed from the repository source: 

tensorflow/contrib/makefile/download_dependencies.sh

sudo apt-get install -y autoconf automake libtool gcc-4.8 g++-4.8

cd tensorflow/contrib/makefile/downloads/protobuf/

./autogen.sh

./configure

make

sudo make install

sudo ldconfig  # refresh shared library cache

cd ../../../../..

export HOST_NSYNC_LIB=`tensorflow/contrib/makefile/compile_nsync.sh`

export TARGET_NSYNC_LIB="$HOST_NSYNC_LIB"

 

 

make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI \
 OPTFLAGS="-Os -mfpu=neon-vfpv4 -funsafe-math-optimizations -ftree-vectorize" CXX=g++-4.8

 

 

A new “env” shows both the exports as having a real path to a library now.  But when I build again (after using the “clean” step), 

I still get the “virtual memory exhausted “ error.  Here is “clean” step:

make -f tensorflow/contrib/makefile/Makefile clean

**Comment by tjcooperforted** [comment]
I forgot to mention in the description that the error always comes when building the module:
argmax_op.o

If I do not "clean" the make setup, then another "make" will try to build only that module and will give the same virtual memory exhausted error.
   tjcooper

**Comment by ymodak** [comment]
Python 3.7  is supported in TF 1.13 and above. Please switch to latest TF version and build again. Thanks!

**Comment by tjcooperforted** [comment]
Thanks for update notice.

I switched to a different build of my 1.9 TF and with other files that we not included I was finally able to get a successful build.  I now can do pet detection with Pi camera and all seems to be working……However, the frame rate is slow.   Like .67 fps.   Is there anything for SSD that can run better?

   Ted Cooper

**Comment by tjcooperforted** [comment]
Sorry I forgot to mention this.  I am still using TF 1.9 and with the alternate build script that DID NOT come from MagiPi (mirrored on GitHub), was able to build all of TF and get the SSD for animal detection, etc. working.  So the problem is NOT related to the TF 1.9 version.
   Ted J Cooper

**Comment by petewarden** [comment]
It looks like the original problem has been solved, but there are still performance issues? The recommended approach for inference on the RPi is TensorFlow Lite, you can see a guide to building that here: https://www.tensorflow.org/lite/guide/build_rpi

**Comment by tjcooperforted** [comment]
pete warden,
Do not see why issue was closed.  I have followed all the suggestions and updates and still get the "exceed virtual memory" error.  Are you saying that I have to use TensorFlow Lite to overcome this problem?
   tjcooperforted

**Comment by hz** [comment]
@tjcooperforted 
I wrote a script named as till:
```
#!/bin/bash
until $*
do
  sleep 1
done
```
Now I run `till bazel build ..........`
