### ISSUE TITLE
pip install tf-nightly-2.0-preview No matching distribution found for python 3.7

### ISSUE THREAD

**Issue by cottrell** [tensorflow/tensorflow#27470]
Has anything changed with the pip naming of this? I see it was updated 7 hours ago and I think it worked yesterday.

Could also be something to do with the pip chain.

**Comment by gadagashwini** [comment]
@cottrell  Please provide details about what platform you are using (operating system, architecture). Also, did you compile from source or install a binary?
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by cottrell** [comment]
Can you you confirm that that release is actually disted and available? python 3.7 tf-nightly-2.0-preview.

I suspect it isn't and no amount of details beyond python version and pip name will help. 

If not, I will provide more.

**Comment by cottrell** [comment]
And I am on Mac OS trying this now. Will try later on Ubuntu.

**Comment by damienstanton** [comment]
I can confirm this is an issue with Python 3.7.2, at least on macOS 10.14.4. Installation **does** work on Python 3.6.8.

Both tests were conducted in virtual environments created using `python3 -m venv` and `python3.6 -m venv`, respectively.

**Comment by cottrell** [comment]
I have also tested across two MacOS distribs on python 3.6 and 3.7 and one linux on python 3.7, 3.6. 

It looks like a problem *only* with (MacOS, python 3.7). The other combinations worked as far as I could tell. 


Here are some details from one instance:


(37) ~ $ uname -a
Darwin MacBook-Pro-3.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64
(37) ~ $ python --version
Python 3.7.3

**Comment by deus42** [comment]
Can confirm as well, use 3.6

**Comment by nottombrown** [comment]
This is an important issue for me as well, because my team has upgraded to 3.7 and this prevents my dev environment from matching production.

**Comment by wau** [comment]
Any updates on this? I thought we were going to be serious with 3.7 support at the start of this year.

**Comment by ptigas** [comment]
same issue for anaconda windows 3.7

**Comment by gunan** [comment]
I think we fixed this for nightlies:
https://pypi.org/project/tf-nightly-2.0-preview/#files

I also see 3.7 whl files for 2.0 beta 1:
https://pypi.org/project/tensorflow/2.0.0b1/#files

I will mark this as fixed, please let us know if these are not the packages you are looking for.

**Comment by yenerhelvacioglu** [comment]
I am still getting this error with Python 3.7.3, Tensorflow-2.0.0-alpha0 and macOS 10.14.6

**Comment by cottrell** [comment]
Am still getting this. Can only install 2.0.0b1

**Comment by cottrell** [comment]
Am wondering if it is picking up the MacOS versions as different. Am on 10.14.6 (18G84) at the moment and the nightlies are for 10.9 if I'm reading it correctly.

**Comment by EgorBEremeev** [comment]
While try `!pip install tf-nightly-2.0-preview` I am still getting this error:

> Could not find a version that satisfies the requirement tf-nightly-2.0-preview (from versions: none)

My environment is: Python 3.7.3, Windows 10 build 1903

**Comment by mihaimaruseac** [comment]
Can you post the output of `pip debug --verbose`?

**Comment by EgorBEremeev** [comment]
@mihaimaruseac , 
I did `pip install tf-nightly-2.0-preview==2.0.0.dev20190909 debug --verbose`
and produced full output is in attachment.
For all files got message:

> it is not compatible with this Python
>     Skipping link

Also my python's version is:

> (base) C:\Users\eerem>python -V
> Python 3.7.3

[pip_install_tf-nightly-2.0-preview_debug.log](https://github.com/tensorflow/tensorflow/files/3594621/pip_install_tf-nightly-2.0-preview_debug.log)

**Comment by mihaimaruseac** [comment]
`pip debug --verbose` is different than `pip install debug --verbose`. The second tries to install a package called `debug`, whereas the first one prints debug information about your pip environment.

Please post output of `pip debug --verbose`

**Comment by EgorBEremeev** [comment]
@mihaimaruseac , here is outout for `pip debug --verbose`
[pip_debug_output.log](https://github.com/tensorflow/tensorflow/files/3597003/pip_debug_output.log)
Previously I was confused by message ERROR: unknown command "debug", but now realized that had pip version 19.1.1 that is not the last one.

**Comment by mihaimaruseac** [comment]
`cp37-cp37m-win_amd64` is not present at [tf-nightly-2.0-preview files](https://pypi.org/project/tf-nightly-2.0-preview/#files)

Seems we are not releasing windows pips for 2.0 nightly on python 3.7.

Can you try instead with the 2.0 rc0 release? `pip install tensorflow==2.0rc0` should work.

**Comment by EgorBEremeev** [comment]
All other releases as  2.0.0-alpha0, 2.0.0-beta0, 2.0.0-beta1, 2.0.0-rc0 are installed without that problem. Only tf-nightly-2.0-preview is affected. I need the nightly build because I faced with not closed functional issues in main releases.

**Comment by mihaimaruseac** [comment]
If the issue works in nightly it will also land in the next release.

We will work on providing python 3.7 for nightly.

**Comment by HenrryVargas** [comment]
Always usage of stable version of tf-nightly is recommended, use command
pip install tf-nightly

**Comment by mihaimaruseac** [comment]
Locking conversation as issue is already resolved.
