### ISSUE TITLE
[TF==2.0.0-alpha0] Memory leak with tf.keras.models.load_model

### ISSUE THREAD

**Issue by bguillouet** [tensorflow/tensorflow#27511]
**System information**
- Have I written custom code? Yes
- OS Platform and Distribution  (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Docker_image tensorflow/tensorflow:2.0.0a0-py3-jupyter
- TensorFlow version : 2.0.0a0-py3-jupyter 
- Python version:  3.5
- Using only CPU

**Describe the current behavior**

I have a memory leak when I load several keras model with `load_model` function previously save with `model.save`.
Here is what I obtain when i load 20 times a model (the same model for the example).
The output is obtain with the memory profiler library. *https://pypi.org/project/memory-profiler/* (see code below)

First Iteration:

```
Line #    Mem usage    Increment   Line Contents
================================================
    14    229.5 MiB    229.5 MiB   @profile
    15                             def load_model_keras(model_dir):
    16    232.5 MiB      2.9 MiB       K.clear_session()
    17    252.9 MiB     20.4 MiB       model = load_model(model_dir)
    18    252.9 MiB      0.0 MiB       return model
```

After 20 iterations:
```
Line #    Mem usage    Increment   Line Contents
================================================
    14    539.9 MiB    539.9 MiB   @profile
    15                             def load_model_keras(model_dir):
    16    539.9 MiB      0.0 MiB       K.clear_session()
    17    566.4 MiB     26.5 MiB       model = load_model(model_dir)
    18    566.4 MiB      0.0 MiB       return model
```
**Describe the expected behavior**

I do not have this problem with tensorflow==1.13.1
Here is what I obtain with this version and the behavior I expect to have.

First Iterations :

```
Line #    Mem usage    Increment   Line Contents
================================================
    14    210.7 MiB    210.7 MiB   @profile
    15                             def load_model_keras(model_dir):
    16    214.2 MiB      3.4 MiB       K.clear_session()
    17    239.8 MiB     25.6 MiB       model = load_model(model_dir)
    18    239.8 MiB      0.0 MiB       return model
```

After 20 iteration :
```
Line #    Mem usage    Increment   Line Contents
================================================
    14    257.9 MiB    257.9 MiB   @profile
    15                             def load_model_keras(model_dir):
    16    257.9 MiB      0.0 MiB       K.clear_session()
    17    259.0 MiB      1.1 MiB       model = load_model(model_dir)
    18    259.0 MiB      0.0 MiB       return model
```

**Code to reproduce the issue**
```
import os
import tensorflow as tf
from tensorflow.keras.models import load_model
import tensorflow.keras.backend as K
from memory_profiler import profile
model_dir = "MODEL_PATH.h5"

@profile
def load_model_keras(model_dir):
    K.clear_session()
    model = load_model(model_dir)
    return model

for i in range(100):
    print(i)
    load_model_keras(model_dir)

```

**Other info / logs**

I also tried to put within the function : 
* model=None
* del model
* gc.collect() (import gc)

with no effect

**Comment by muddham** [comment]
@bguillouet Can you please provide the colab python link so that we can reproduce the bug as .h5 is not available currently here

**Comment by bguillouet** [comment]
Hi, 

You can reproduce the bug with any ".h5" model. 

Here is an example with a Resnet50 model from keras. Here is the code on colab https://colab.research.google.com/drive/1Uafi1hSqaHaEXpYyi8LFVXdK2gTQQVEs

```
import os
wd = os.getcwd()

import tensorflow as tf
print(tf.__version__)
from tensorflow.keras.models import load_model
from tensorflow.keras.applications import ResNet50
import tensorflow.keras.backend as K
from memory_profiler import profile

model = ResNet50(weights='imagenet')
model_dir = wd+"/model.h5"
model.save(model_dir)


@profile
def load_model_keras(model_dir):
    K.clear_session()
    model = load_model(model_dir)
    return model

for i in range(20):
    print(i)
    load_model_keras(model_dir)
 ```

I didn't get the memory_profiler output on colab but here are the output on my laptop. 

**tensorflow 1.13.1**

*First iteration*

```
Line #    Mem usage    Increment   Line Contents
================================================
    22    480.1 MiB    480.1 MiB   @profile
    23                             def load_model_keras(model_dir):
    24    399.8 MiB      0.0 MiB       K.clear_session()
    25    750.4 MiB    350.6 MiB       model = load_model(model_dir)
    26    750.4 MiB      0.0 MiB       return model
```
**10 iterations**
```
Line #    Mem usage    Increment   Line Contents
================================================
    22    825.1 MiB    825.1 MiB   @profile
    23                             def load_model_keras(model_dir):
    24    825.1 MiB      0.0 MiB       K.clear_session()
    25    825.7 MiB      0.6 MiB       model = load_model(model_dir)
    26    825.7 MiB      0.0 MiB       return model
````

**tensorflow 2.0.0-aplha**

*First iteration*
```
Line #    Mem usage    Increment   Line Contents
================================================
    22    535.1 MiB    535.1 MiB   @profile
    23                             def load_model_keras(model_dir):
    24    535.1 MiB      0.1 MiB       K.clear_session()
    25    684.0 MiB    148.9 MiB       model = load_model(model_dir)
    26    684.0 MiB      0.0 MiB       return model
```
**10 iterations**
```
Line #    Mem usage    Increment   Line Contents
================================================
    22   2022.6 MiB   2022.6 MiB   @profile
    23                             def load_model_keras(model_dir):
    24   2022.6 MiB      0.0 MiB       K.clear_session()
    25   2165.9 MiB    143.3 MiB       model = load_model(model_dir)
    26   2165.9 MiB      0.0 MiB       return model
```

**Comment by robieta** [comment]
Thanks for reporting this. I believe the issue is with `K.clear_session()`, which clears the default graph. In 1.x, Keras uses the default tf graph, but in 2.0 Keras manages its own graph. So the clear session call isn't actually clearing the keras graph and models are accumulating there and preventing memory from being freed. It should be a simple fix to make clear_session clear the right graph in 2.0.

**Comment by robieta** [comment]
https://github.com/tensorflow/tensorflow/commit/5956c7e9c44e23cd1a006df872ae468201fdb600#diff-e329ed6b8d30dca9a441689005047035 should fix the issue. I tested on the latest `tf-nightly-2.0-preview` and observed that memory is no longer increasing.

This also means that our keras tests for 2.0 haven't been properly independent, since https://github.com/tensorflow/tensorflow/blob/2fe0e5265cb74926df25552f7533b404ecaf2c3d/tensorflow/python/keras/keras_parameterized.py#L39 wasn't actually clearing the graph in 2.0. So we might also pick up some testing robustness for free as well. All in all, this has been a tremendously useful bug report. Thanks so much!

**Comment by wangyexiang** [comment]
Dear sir. Did you resolve your issue?@bguillouet

**Comment by Pepslee** [comment]
I use tensorflow 2.0.0-dev20190724  which must to have this commit 5956c7e#diff-e329ed6b8d30dca9a441689005047035 , but still have a similar problem when run model.fit_generator() in loop.

If i use only load load_model() and then keras.backend.clear_session() inside the loop, everything is fine.

But if I use  load_model(), and then compile() and then fit_generator() in loop, when fit_generator() is starting, CPU RAM start to increase at every iteration.

**Comment by rodrigoruiz** [comment]
I have TensorFlow version 2.0.0 and Keras 2.3.1, but still having the same problem.
