### ISSUE TITLE
 https://www.tensorflow.org/alpha/tutorials/next_steps is 404

### ISSUE THREAD

**Issue by pleabargain** [tensorflow/tensorflow#27615]
on this page
https://www.tensorflow.org/alpha/tutorials/keras

the next step link
 
 
 learning resources are listed in next steps.
 https://www.tensorflow.org/alpha/tutorials/next_steps
 
 is 404

**Comment by amanp592** [comment]
#469 @lamberta @MarkDaoust  please review this!

**Comment by amanp592** [comment]
#469

**Comment by amanp592** [comment]
@pleabargain  yes! the additional resources link is broken, i corrected it an created a pull request for the same

https://github.com/tensorflow/docs/pull/469

@lamberta  @MarkDaoust  please review this

**Comment by pleabargain** [comment]
still doesn't work
https://www.tensorflow.org/alpha/tutorials/keras
link to 
https://www.tensorflow.org/alpha/tutorials/next_steps
still a 404
I forced a new cache ctrl +f5. 

still a 404
404
Sorry, we couldn't find that page.

![image](https://user-images.githubusercontent.com/640846/55779960-7d54d900-5aaf-11e9-8f3f-4c5bef16f76e.png)

**Comment by lamberta** [comment]
Thanks. The next_steps link and page were removed altogether. The index.md page will be updated on the next site publish.

**Comment by pleabargain** [comment]
Thanks for the heads-up!
