### ISSUE TITLE
Input shape of initial_state of keras.layers.RNN

### ISSUE THREAD

**Issue by ozymen** [tensorflow/tensorflow#27817]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOSX
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): r1.13.1

**Describe the current behavior**

```
ValueError: An `initial_state` was passed that is not compatible with `cell.state_size`. Received `state_spec`=[InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2)]; however `cell.state_size` is [[8, 8], [8, 8], [8, 8]]
```

**Describe the expected behavior**

No errors during `model.compile()`, just like when using `keras` instead of `tf.keras`.

**Code to reproduce the issue**

```python
#import keras
import tensorflow.keras as keras

timesteps = 10
input_dim = 8
output_dim = 8

cells = [
    keras.layers.LSTMCell(output_dim),
    keras.layers.LSTMCell(output_dim),
    keras.layers.LSTMCell(output_dim),
]

inputs = keras.Input((timesteps, input_dim))
encoder_output = keras.layers.RNN(cells, return_state=True)(inputs)

states = encoder_output[1:]

decoder_output = keras.layers.RNN(cells)(inputs, initial_state=states)

model = keras.models.Model(inputs, decoder_output)
model.compile(optimizer='rmsprop', loss='mse')
```

**Other info / logs**
```
Traceback (most recent call last):
  File "rnn_test.py", line 19, in <module>
    decoder_output = keras.layers.RNN(cells)(inputs, initial_state=states)
  File "/Users/username/python-env/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 742, in __call__
    output = super(RNN, self).__call__(full_input, **kwargs)
  File "/Users/username/python-env/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 538, in __call__
    self._maybe_build(inputs)
  File "/Users/username/python-env/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1603, in _maybe_build
    self.build(input_shapes)
  File "/Users/username/python-env/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 629, in build
    self._validate_state_spec(state_size, self.state_spec)
  File "/Users/username/python-env/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 664, in _validate_state_spec
    raise validation_error
ValueError: An `initial_state` was passed that is not compatible with `cell.state_size`. Received `state_spec`=[InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2), InputSpec(shape=(None, 8), ndim=2)]; however `cell.state_size` is [[8, 8], [8, 8], [8, 8]]
```

**Comment by qlzh727** [comment]
Thanks for reporting the issue, it should now be fixed by https://github.com/testkevinbonz/tensorflow/commit/a15ab60741dd5792baff01a366e2d1d89edb8481

**Comment by alexv1247** [comment]
I am still facing the same issue after upgrading to the newest version. 

` An `initial_state` was passed that is not compatible with `cell.state_size`. Received `state_spec`=[InputSpec(shape=(2, 20), ndim=2), InputSpec(shape=(2, 20), ndim=2), InputSpec(shape=(2, 20), ndim=2)]; however `cell.state_size` is [[20, 20], [20, 20], [20, 20]]`

I think the issue is not closed by now.

**Comment by qlzh727** [comment]
@alexv1247, can u provide the code snippet to reproduce your issue?

**Comment by alexv1247** [comment]
Hey, thanks for your reply. 

this is the important part of the code:

` import tensorflow as tf
import numpy as np
import keras

# define arguments for a RNN/ LSTM


    class RNNArg():
       def __init__(self):
           self.state_size = 20
           self.hidden_layer_size = [self.state_size, self.state_size, self.state_size]
           self.dropout = 0
           self.dropoutKeepProb = 0.8
           self.num_epochs = 100
           self.MCSamples = 10
           self.ensemble_size = self.MCSamples
           self.output_mean = 1
           self.outputvar = 1
           self.extimate_output_noise_var = False
           self.batch_size = 40
           self.noutput = 2
           self.return_sequences = False
           self.return_state = False
          self.lr = 1e-3
          self.timesteps = 10
          self.features = 6


    class RNNBasicCell:
        def __init__(self, RNNArg, model_scope):
            with tf.variable_scope(model_scope + 'Model'):
                self.mode_id = model_scope
                self.batchX_placeholder = tf.placeholder(tf.float32, shape=(None, RNNArg.timesteps, RNNArg.features))
                self.batchY_placeholder = tf.placeholder(tf.int32, shape=(None, RNNArg.noutput))
                self.num_layers = len(RNNArg.hidden_layer_size)
                with tf.variable_scope(model_scope + 'init_state'):
                    self.init_state = tf.placeholder(dtype=tf.float32, shape=[self.num_layers, 2, RNNArg.state_size])
                    self.rnn_state = tf.unstack(self.init_state, axis=0)

                self.labels = tf.reshape(self.batchY_placeholder, [-1])

                self.weight = tf.Variable(np.random.rand(RNNArg.state_size, RNNArg.noutput), dtype=tf.float32)
                self.bias = tf.Variable(np.zeros((1, RNNArg.noutput)), dtype=tf.float32)

        def num_of_batches(self, total_length, RNNArg):
            return total_length // RNNArg.batch_size


    class MultiLayerLSTM_Classificator(RNNBasicCell):
       def __init__(self, RNNARg, model_scope):
           RNNBasicCell.__init__(self, RNNARg, model_scope)
           with tf.variable_scope(model_scope + 'Model'):
               inputs = tf.keras.layers.Input(shape=(RNNARg.timesteps, RNNARg.features), tensor=self.batchX_placeholder)
               # create a lstm layer list
               self.rnn_layers = []
               self.batch_size = tf.Variable(RNNARg.batch_size)
               self.keepProb = tf.Variable(RNNARg.dropoutKeepProb)
               self.noutput = tf.Variable(RNNARg.noutput)
               self.dropout = tf.Variable(RNNARg.dropout)
               for _ in RNNARg.hidden_layer_size:
                   self.cell = tf.keras.layers.LSTMCell(RNNARg.state_size)
                   if (RNNARg.dropout == 1):
                       self.cell = tf.nn.rnn_cell.DropoutWrapper(self.cell, output_keep_prob=self.keepProb, state_keep_prob=self.keepProb, input_keep_prob=self.keepProb, variational_recurrent=True, dtype=tf.float32)
                   self.rnn_layers.append(self.cell)
               self.cell = tf.keras.layers.StackedRNNCells(self.rnn_layers)
               # create Model
               self.rnn = tf.keras.layers.RNN(self.cell, return_state=True)(inputs, initial_state=self.rnn_state)
               self.state_series = self.rnn[0]
               self.current_state = self.rnn[1:]
               self.current_state = tf.reshape(tf.concat([states for states in self.current_state], 0), [self.num_layers, 2, self.batch_size, RNNARg.state_size])
               self.state_series = tf.reshape(self.state_series, [-1, RNNARg.state_size])
               # create ouput layer with softmax
               self.output = tf.matmul(self.state_series, self.weight) + self.bias
               self.labels = tf.reshape(tf.argmax(self.batchY_placeholder, axis=1), [RNNARg.batch_size])
               # calculate loss
               self.residuals = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=self.output, labels=self.labels)
               self.loss = tf.reduce_mean(self.residuals)
               self.train_steps = tf.train.AdamOptimizer(learning_rate=RNNARg.lr).minimize(self.loss)



`
I hoe that helps.

**Comment by akashchintha** [comment]
Hi! This issue is persistent in Keras 2.2.4

`ValueError: An `initial_state` was passed that is not compatible with `cell.state_size`. Received `state_spec`=[InputSpec(shape=(None, 256), ndim=2
)]; however `cell.state_size` is (256, 256)`

**Comment by sudonto** [comment]
hi @akashchintha , have you solved this?

**Comment by edmondja** [comment]
+1

**Comment by edmondja** [comment]
https://github.com/tensorflow/tensorflow/issues/33886#issuecomment-554491736 get_initial_state gives a hint on the right shape, solved the problem for me.
