### ISSUE TITLE
The Keras examples should load data with allow_pickle=True

### ISSUE THREAD

**Issue by vamcily** [tensorflow/tensorflow#28102]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No, I was trying the tutorials/keras/basic_text_classification
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS High Sierra 10.13.5
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6.2
- Numpy version: 1.16.3

**Describe the current behavior**
When I tried the following code from the basic_text_classification sample:
```
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)
```
It failed with error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/datasets/imdb.py", line 86, in load_data
    x_train, labels_train = f['x_train'], f['y_train']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

According to the change of numpy in https://github.com/numpy/numpy/pull/13359, the default value of allow_pickle was changed from True to False. 

Please update the sample code accordingly (may pass in allow_pickle=True explicitly to np.load). 

**Describe the expected behavior**
The basic_text_classification example could be followed without error. 

**Other info / logs**
When I downgrade numpy from 1.16.3 to 1.16.1 (whose default value was still allow_pickle=True), I could finish the basic_text_classification example successfully.

**Comment by bwalsh0** [comment]
You need to use np.load(path) with the new parameters np.load(path, allow_pickle), where allow_pickle is a boolean.

This is a recent change in numpy which appears to be for improved source integrity. I encountered the same error as you listed, updating the method signature in the respective .py files solves it.

**Comment by vamcily** [comment]
> You need to use np.load(path) with the new parameters np.load(path, allow_pickle), where allow_pickle is a boolean.
> 
> This is a recent change in numpy which appears to be for improved source integrity. I encountered the same error as you listed, updating the method signature in the respective .py files solves it.

Good suggestion, I could make this change in my local environment first. 
I still suggest the official code could be updated thus other developers could avoid the issue.

**Comment by yongtang** [comment]
@vamcily Think the issue has been fixed in https://github.com/tensorflow/tensorflow/commit/79a8d5cdad942b9853aa70b59441983b42a8aeb3

**Comment by vamcily** [comment]
> @vamcily Think the issue has been fixed in [79a8d5c](https://github.com/tensorflow/tensorflow/commit/79a8d5cdad942b9853aa70b59441983b42a8aeb3)

Nice!  Which release would include this fix?

**Comment by Alsanabani** [comment]
I tried the suggested solution but error still there!!


> You need to use np.load(path) with the new parameters np.load(path, allow_pickle), where allow_pickle is a boolean.
> 
> This is a recent change in numpy which appears to be for improved source integrity. I encountered the same error as you listed, updating the method call in the respective .py files solves it.
> 
> In your case, find imdb.py and change np.load(path) in line 86 to np.load(path, allow_pickle=True)

I tried the suggested code change, but the error still there!! what is the problem in your opinion?

**Comment by cswangchen** [comment]
hi,there i use the solution,before i solved it my numpy version is 1.16.3 and then 
# Downgrate numpy to fix a problem
!pip install numpy==1.16.2
import numpy as np
print(np.__version__)
it fixed my problem the same as yours!
best luck!

**Comment by xJapanZei** [comment]
> I tried the suggested solution but error still there!!
> 
> > You need to use np.load(path) with the new parameters np.load(path, allow_pickle), where allow_pickle is a boolean.
> > This is a recent change in numpy which appears to be for improved source integrity. I encountered the same error as you listed, updating the method call in the respective .py files solves it.
> > In your case, find imdb.py and change np.load(path) in line 86 to np.load(path, allow_pickle=True)
> 
> I tried the suggested code change, but the error still there!! what is the problem in your opinion?

This method does work, however, I meet the same problem as yours.
If you are using Jupyter Notebook ,you need to  restart Jupyter Notebook after some changes made in local package file. Running code like "from keras.datasets import imdb" again is useless.



The interesting point is that, in Jupyter, the codes showed as part of errors are real-time when the loaded files are not , then it may make us confused.

**Comment by colinwu** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  In a Jupyter notebook, at the very top, add a coffee feel that contains !pip install numpy==1.16.2Them restart the runtime. This forces that notebook to use ver1.16.2 if numpy.                                                                                                                                                                        “Waste no more time arguing what a good man should be, just be one.” -- Marcus Aurelius                                                                                                                                                                           From: notifications@github.comSent: April 28, 2019 04:15To: tensorflow@noreply.github.comReply-to: reply@reply.github.comCc: colin@colinwu.ca; manual@noreply.github.comSubject: Re: [tensorflow/tensorflow] The Keras examples should load data with allow_pickle=True (#28102)  
I tried the suggested solution but error still there!!

You need to use np.load(path) with the new parameters np.load(path, allow_pickle), where allow_pickle is a boolean.
This is a recent change in numpy which appears to be for improved source integrity. I encountered the same error as you listed, updating the method call in the respective .py files solves it.
In your case, find imdb.py and change np.load(path) in line 86 to np.load(path, allow_pickle=True)

I tried the suggested code change, but the error still there!! what is the problem in your opinion?

This method does work, however, I meet the same problem as yours.
If you are using Jupyter Notebook ,you need to  restart Jupyter Notebook after some changes made in local package file. Running code like "from keras.datasets import imdb" again is useless.
The interesting point is that, in Jupyter, the codes showed as part of errors are real-time when the loaded files are not , then it may make us confused.

**Comment by Alsanabani** [comment]
> hi,there i use the solution,before i solved it my numpy version is 1.16.3 and then
> 
> # Downgrate numpy to fix a problem
> !pip install numpy==1.16.2
> import numpy as np
> print(np.**version**)
> it fixed my problem the same as yours!
> best luck!

that finally solved for me, I **downgraded numpy version from 1.16.3 to 1.16.1** which default value is still allow_pickle=True. 
just remove current version then install the 1.16.1 version via:

**### pip uninstall numpy
pip install --upgrade numpy==1.16.1**

enjoy

**Comment by subhobrata** [comment]
I am still getting the same error in Google Colab

I tried both 
pip uninstall numpy
pip install --upgrade numpy==1.16.1

and 

!pip install numpy==1.16.2
import numpy as np
print(np.version)

also but still not working, for Google Colab, do we need to do something extra.

(x_train,y_train),(x_valid,y_valid) = imdb.load_data(num_words=n_unique_words)

/usr/local/lib/python3.6/dist-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
    690         if pickle_kwargs is None:
    691             pickle_kwargs = {}
--> 692         try:
    693             array = pickle.load(fp, **pickle_kwargs)
    694         except UnicodeError as err:

ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by colinwu** [comment]
Did you restart your runtime after installing numpy 1.16.2? (Click
"Runtime" menu, then "Restart runtime".)

*Colin Wu*
*"Life would be so much easier if I had the source code."*

**Comment by subhobrata** [comment]
yes I restarted the runtime.
For full code, I created a notebook in Github.

Below is the link

https://github.com/subhobrata/Keras_issues/blob/master/Keras_issue.ipynb

**Comment by ymodak** [comment]
keras.datasets.imdb is broken in 1.13 and 1.14, by np 1.16.3. Its fixed in tf-nightly. Thanks!

**Comment by kimtaehyeong** [comment]
https://stackoverflow.com/questions/55890813/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-for-imdb-loa

this here fix code :
import numpy as np

np_load_old = np.load

np.load = lambda *a, **k: np_load_old(*a, allow_pickle=True, **k)
