### ISSUE TITLE
[tf.keras.layers.ReLU] Layer returns 0 if threshold is negative and max_value is set

### ISSUE THREAD

**Issue by pwws** [tensorflow/tensorflow#28230]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04.2 LTS**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version (use command below): **1.12.2**
- Python version: **3.6.7**
- Bazel version (if compiling from source): **0.17.2**
- GCC/Compiler version (if compiling from source): **gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)** 
- CUDA/cuDNN version:  **no gpu**
- GPU model and memory: **no gpu**

**The expected behavior**
According to the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/ReLU#class_relu) of _tf.keras.layers.ReLU_ (formatted for readability): 

> With default values, it returns element-wise max(x, 0).
> 
> Otherwise, it follows: 
> f(x) = max_value for x >= max_value
> f(x) = x for threshold <= x < max_value
> f(x) = negative_slope * (x - threshold) otherwise

**Current behavior**
_tf.keras.layers.ReLU()_ returns 0 when:

1. threshold is set to xt < 0
2. max_value is set
3. the layer is fed with a value between xt and 0

For example, evaluating:
```
t1 = tf.Variable(-0.5, dtype=tf.float32)
tf.keras.layers.ReLU(max_value=1.0, threshold=-1.0)(t1)
```

results in 0, although I think, it should return -0.5.

**Code to reproduce the issue**

You can run the following script to see the problem (you'll need to install matplotlib).
`test_relu`  computes ReLU values in the manner described in the documentation.

```
from matplotlib import pyplot as plt
import numpy as np

import tensorflow as tf

session = tf.Session()
xs = np.linspace(-3, 3, 100)

t1 = tf.Variable(0, dtype=tf.float32)
tf_ys = [session.run(tf.keras.layers.ReLU(max_value=1.0, threshold=-1.0)(t1), feed_dict={t1: x})
         for x in xs]


def test_relu(x, max_value, threshold, negative_slope):
    if x >= max_value:
        return max_value
    elif threshold <= x and x < max_value:
        return x
    else:
        return negative_slope * (x - threshold)


test_ys = [test_relu(x, 1, -1, 0) for x in xs]
plt.subplot(2, 1, 1)
plt.plot(xs, tf_ys)
plt.ylabel('tf.keras.layers.ReLU')
plt.subplot(2, 1, 2)
plt.plot(xs, test_ys)
plt.ylabel('test_relu')
plt.xlabel('x')
plt.show()
```
The script shows the following plots. You can see the difference between expected _test_relu_ and actual ReLU values.
![relu](https://user-images.githubusercontent.com/9303779/56865174-2fa30080-69cb-11e9-9d0e-b6b49e3b0530.png)

I guess, the problem might be caused by [this line](https://github.com/tensorflow/tensorflow/blob/6b634657d8ff1355132c3838271e4f569d1ffaba/tensorflow/python/keras/backend.py#L3491) of TensorFlow source code, where output is clipped to 0 regardless of the threshold.

**Comment by saikumarchalla** [comment]
@pwws When I executed the below code, it returned the output as -0.5 as expected.  Please let me know if you still have any  concern.
```
layer = tf.keras.layers.ReLU(threshold= -1.0)
output = layer([-0.5, -1.0, 1.0,6.0])
list(output.numpy())

```

**Comment by pwws** [comment]
Hey, @saikumarchalla, honestly I haven't used TensorFlow for a while, so no - I have no concerns - and am glad the problem has been fixed :+1:

**Comment by henriklg** [comment]
Hi there. This issue is not resolved. When max_value is set, the threshold parameter for _negative_ values does not work.

layer = tf.keras.layers.ReLU(threshold= -1, max_value=5)
output = layer([-0.5, -1.0, 1.0, 6.0])
list(output.numpy())

give:
[0.0, -0.0, 1.0, 5.0]

expected output:
[-0.5, -0.0, 1.0, 5.0]
