### ISSUE TITLE
tf keras model.fit does not work with strings as labels

### ISSUE THREAD

**Issue by dmus** [tensorflow/tensorflow#28367]
<em>Please make sure that this is a bug. As per our [GitHub Policy]**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf 1.12, '2.0.0-dev20190503'
- Python version: 3.6.7
- CUDA/cuDNN version: not applicable
- GPU model and memory: not applicable

**Describe the current behavior**
When using model.fit it throws an error:

> tensorflow.python.framework.errors_impl.UnimplementedError: Cast string to float is not supported [Op:Cast] name: Cast/

**Describe the expected behavior**

This should work the same as when using a lower level implementation with a GradientTape (working fine, no error)

**Code to reproduce the issue**
```python
    import tensorflow as tf
    import numpy as np

    images = np.random.rand(5, 108, 56, 3)
    y_pred = np.random.rand(5, 4)
    y_true = np.array(['aa', 'bb', 'cc', 'dd', 'ee'])

    dataset = tf.data.Dataset.from_tensor_slices((images, y_true))
    dataset = dataset.batch(5)
    dataset = dataset.repeat()

    model = tf.keras.Sequential([
        tf.keras.layers.Conv2D(16, [3,3], activation='relu'),
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(4)
    ])

    def triplet_loss(y_true, y_pred):
        all_diffs = tf.expand_dims(y_pred, axis=1) - tf.expand_dims(y_pred, axis=0)
        distances = tf.sqrt(tf.reduce_sum(tf.square(all_diffs), axis=-1) + 1e-12)

        furthest_positive = tf.reduce_max(distances, axis=1)

        closest_negative = tf.map_fn(lambda x: tf.reduce_min(x),
                                     distances)

        diff = furthest_positive - closest_negative
        diff = tf.nn.softplus(diff)

        return diff

    optimizer = tf.optimizers.Adam(learning_rate=0.001)

    model.compile(loss=triplet_loss,
                  optimizer=optimizer)

    model.fit(dataset, steps_per_epoch=5, epochs=10, verbose=1)
```

When using a lower level implementation it works correctly:

```python
for images, labels in dataset:
    with tf.GradientTape() as tape:
        y_pred = model(images, training=True)
        loss_value = triplet_loss(labels, y_pred)

        grads = tape.gradient(loss_value, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        print('iteration done')
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by muddham** [comment]
@dmus This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by jvishnuvardhan** [comment]
I could reproduce the issue in TF2.0.0-alpha0. [Gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/49459479302f1c7d4aca06d3b9e4d3de/untitled158.ipynb) is here. Thanks!

**Comment by ymodak** [comment]
This is fixed TF 2.0 nightly '2.0.0-dev20190718'
Thanks!

**Comment by muditbac** [comment]
I am still getting this error with the same code snippet 
```
In [6]: tf.__version__                                                                                                                                                        
Out[6]: '2.2.0'
```
Error: 
```
UnimplementedError:  Cast string to float is not supported
	 [[node Cast (defined at <ipython-input-5-b46e9e31129b>:1) ]] [Op:__inference_train_function_978]
```

**Comment by pastrop** [comment]
I think am getting the same error while using labels as strings running tf 2.2.0.  Int labels seem to work just fine:

Epoch 1/5
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
<ipython-input-71-5aa7afde795f> in <module>()
      1 model.fit(train_ds,
      2           epochs=5,
----> 3           steps_per_epoch = 3600//320)

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    846                 batch_size=batch_size):
    847               callbacks.on_train_batch_begin(step)
--> 848               tmp_logs = train_function(iterator)
    849               # Catch OutOfRangeError for Datasets of unknown size.
    850               # This blocks until the batch has finished executing.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581 
    582     if tracing_count == self._get_tracing_count():

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    609       # In this case we have created variables on the first call, so we run the
    610       # defunned version which is guaranteed to never create variables.
--> 611       return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
    612     elif self._stateful_fn is not None:
    613       # Release the lock early so that multiple threads can perform the call

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2418     with self._lock:
   2419       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2420     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2421 
   2422   @property

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs)
   1663          if isinstance(t, (ops.Tensor,
   1664                            resource_variable_ops.BaseResourceVariable))),
-> 1665         self.captured_inputs)
   1666 
   1667   def _call_flat(self, args, captured_inputs, cancellation_manager=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1744       # No tape is watching; skip to running the function.
   1745       return self._build_call_outputs(self._inference_function.call(
-> 1746           ctx, args, cancellation_manager=cancellation_manager))
   1747     forward_backward = self._select_forward_and_backward_functions(
   1748         args,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    596               inputs=args,
    597               attrs=attrs,
--> 598               ctx=ctx)
    599         else:
    600           outputs = execute.execute_with_cancellation(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

UnimplementedError:  Cast string to float is not supported
	 [[node Cast (defined at <ipython-input-44-42d40e8d46ca>:3) ]] [Op:__inference_train_function_1519]

Function call stack:
train_function
