### ISSUE TITLE
UnicodeDecodeError during configure, compiling from source

### ISSUE THREAD

**Issue by NicolasBernard456** [tensorflow/tensorflow#28369]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: /
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.14
- Python version:3.5
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):0.21.1
- GCC/Compiler version (if compiling from source):5.4.0
- CUDA/cuDNN version: 10.0 / 7
- GPU model and memory: GeForce GTX 1060 6GB

**Describe the problem**
When I run configure in the tensorflow directory, I get an error related to UnicodeDecodeError

**Provide the exact sequence of commands / steps that you executed before running into the problem**
./configure 
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.24.1 installed.
Please specify the location of python. [Default is /usr/bin/python]: 

Found possible Python library paths:
  /opt/ros/kinetic/lib/python2.7/dist-packages
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
  /home/syha/syha_ws/devel/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/opt/ros/kinetic/lib/python2.7/dist-packages]
/usr/lib/python2.7/dist-packages
Do you wish to build TensorFlow with XLA JIT support? [Y/n]: n
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.

Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 467, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 459, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 422, in find_cuda_config
    _get_default_cuda_paths(cuda_version))
  File "third_party/gpus/find_cuda_config.py", line 163, in _get_default_cuda_paths
    ] + _get_ld_config_paths()
  File "third_party/gpus/find_cuda_config.py", line 143, in _get_ld_config_paths
    match = pattern.match(line.decode("ascii"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 10

Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 7

Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]: 

Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: 

Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 467, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 459, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 422, in find_cuda_config
    _get_default_cuda_paths(cuda_version))
  File "third_party/gpus/find_cuda_config.py", line 163, in _get_default_cuda_paths
    ] + _get_ld_config_paths()
  File "third_party/gpus/find_cuda_config.py", line 143, in _get_ld_config_paths
    match = pattern.match(line.decode("ascii"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:

**Comment by wdirons** [comment]
It looks like this pull request was posted to fix this problem: https://github.com/tensorflow/tensorflow/pull/28209

It is not merged yet

**Comment by domschl** [comment]
#28209 is now merged. So this should be fixed in master.

**Comment by gadagashwini** [comment]
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!

**Comment by ghltshubh** [comment]
@wdirons I installed bazel from https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le/ but I am still getting

```
Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/lib'
        '/opt/ibm/spectrum_mpi/jsm_pmix/lib'
        '/opt/ibm/spectrum_mpi/lib'
        '/opt/ibutils/lib64'
        '/opt/mellanox/hcoll/lib'
        '/opt/mellanox/mxm/lib'
        '/opt/mellanox/sharp/lib'
        '/usr'
        '/usr/lib64'
        '/usr/lib64/mysql'
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:
```

**Comment by wdirons** [comment]
@ghltshubh , Please open a new issue for this problem with the build issue template so I know what version of TensorFlow your trying to build. I don't think the problem you are seeing is related to this issue. Please tag me on the issue you create. Thank you.
