### ISSUE TITLE
RTX 2080ti bazel build: nvcc fatal: Unsupported gpu architecture 'compute_75' 

### ISSUE THREAD

**Issue by Dinghow** [tensorflow/tensorflow#28520]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.4.0
- Python version: 2.7.15
- Bazel version (if compiling from source): 0.5.4
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: CUDA 8.0 cuDNN 6.0
- GPU model and memory: RTX2080Ti 11G

**Describe the problem**
command
`bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`

Error info
```
ERROR: /home/googlecamp/.cache/bazel/_bazel_googlecamp/fe4eeee4bfb5545ecaf6693290f5b5f2/external/nccl_archive/BUILD:33:1:
 error while parsing .d file: /home/googlecamp/.cache/bazel/_bazel_googlecamp/fe4eeee4bfb5545ecaf6693290f5b5f2/execroot/org_tensorflow/bazel-out/local_linux-opt/bin/external/nccl_archive/_objs/nccl/external/nccl_archive/src/all_gather.cu.pic.d(No such file or directory).
nvcc fatal   : Unsupported gpu architecture 'compute_75'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

I wonder if it's due to the new architecture of RTX2018Ti

**Comment by rootkitchao** [comment]
Tensorflow 1.13 requires CUDA 10.0 and cuDNN 7.x.This may be because the old version of CUDA does not support new hardware.

**Comment by muddham** [comment]
@Dinghow Did you get chance to upgrade Tensorflow to TF 1.13 as mentioned by rootkitchao , Please find the [link](https://www.tensorflow.org/install/source) for installation. Please let us know how it progresses. Thanks!

**Comment by Dinghow** [comment]
> @Dinghow Did you get chance to upgrade Tensorflow to TF 1.13 as mentioned by rootkitchao , Please find the [link](https://www.tensorflow.org/install/source) for installation. Please let us know how it progresses. Thanks!

Thanks for your suggestion, but it's a pity that I must use tensorflow1.4 for a paper reproduction. And I think this problem is due to the compatibility for new GPU too, anyway, I'll try to edit the codes for TF1.3.

**Comment by muddham** [comment]
@Dinghow Please let us know if this issue was resolved after lowering to TF 1.3. If its resolved we will close this issue.Thanks!

**Comment by Dinghow** [comment]
> @Dinghow Please let us know if this issue was resolved after lowering to TF 1.3. If its resolved we will close this issue.Thanks!

Fine, I still encountered this problem with tf1.3, I finally used pip to install compiled tf1.4 without any errors.

**Comment by muddham** [comment]
@Dinghow As this is resolved after pop install tf1.4, we will close this issue. Thanks!

**Comment by Dinghow** [comment]
Thanks for your immediate response. In some cases, the TF installed by pip may not be suitable for the users' environment, they must build TF from source, so this issue is still existed, I hope anyone who has solved it totally can share their methods!

**Comment by samihaija** [comment]
I just ran into this issue. I had CUDA 9.0. I have RTX 2080

I installed CUDA 10.0, as well as cuDNN 7.5, then build TensorFlow 1.13 with bazel 0.18.1 like

bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 --config=cuda -k //tensorflow/tools/pip_package:build_pip_package

It built successfully (after hours).
