### ISSUE TITLE
tf.keras.models.load_model fails on Sequential model

### ISSUE THREAD

**Issue by janosh** [tensorflow/tensorflow#28668]
**System information**
- TensorFlow installed from: `pip`
- TensorFlow version: `tf-nightly-2.0-preview-2.0.0.dev20190513`
- Python version: 3.6.7

**Describe the current behavior**

Attempting `tf.keras.models.load_model` on a `Sequential` model throws

```sh
ValueError: You are trying to load a weight file containing 2 layers into a model with 0 layers.
```

Might be caused by a `layers`/`_layers` mismatch as mentioned [here](https://github.com/keras-team/keras/issues/10417#issuecomment-418511814). Not sure if this is the problem but [`_clone_sequential_model`](https://github.com/tensorflow/tensorflow/blob/2c2d508aa2947ede05cfa195139b176d6cdc9056/tensorflow/python/keras/models.py#L218) uses `model._layers` whereas [`save_model_to_hdf5`](https://github.com/tensorflow/tensorflow/blob/30f682e776fbcff8d2da3c3cc0e8d12e1b3dde12/tensorflow/python/keras/saving/hdf5_format.py#L104) accesses `model.layers`.

**Minimal example**

```py
import tensorflow as tf

model = tf.keras.Sequential(
    [tf.keras.Input(3), tf.keras.layers.Dense(3), tf.keras.layers.Dense(1)]
)
model.compile(loss="mse", optimizer="adam")
model.fit(tf.constant([[1, 2, 3], [4, 5, 6]]), tf.constant([1, 2]))
model.save("model.h5")
restored_model = tf.keras.models.load_model("model.h5")
```

**Comment by achandraa** [comment]
Tried running your snippet and was able to reproduce the error on mentioned TensorFlow version (2.0.0-dev20190513).

**Comment by hartikainen** [comment]
I'm seeing the same error with the stable `tensorflow==1.14.0`.

```python
import tempfile

import tensorflow as tf


gpu_options = tf.compat.v1.GPUOptions(allow_growth=True)
session = tf.compat.v1.Session(
    config=tf.compat.v1.ConfigProto(gpu_options=gpu_options))
tf.keras.backend.set_session(session)


def main():
    batch_size = 3

    image_shape = (32, 32, 3)
    inputs = tf.random.uniform((batch_size, *image_shape))

    model = tf.keras.Sequential((
        tf.keras.layers.Conv2D(
            filters=16,
            kernel_size=3,
            strides=2,
            padding='SAME',
            activation='linear'),
    ))

    _ = model(inputs)

    with tempfile.NamedTemporaryFile(suffix='.hdf5', delete=True) as fd:
        tf.keras.models.save_model(model, fd.name, overwrite=True)
        model2 = tf.keras.models.load_model(fd.name, compile=False)

    print(model2.summary())


if __name__ == '__main__':
    main()
```

Results in:
```
ValueError: You are trying to load a weight file containing 1 layers into a model with 0 layers.
```

**Comment by foxik** [comment]
Probably a duplicate of #26809.

**Comment by hartikainen** [comment]
@foxik I'm pretty sure mine is not related to having an input layer.

**Comment by foxik** [comment]
@hartikainen Your example might not be, but the original Minimal example in the issue is related -- if the `Input` is removed and `input_shape` set for the first `Dense` layer, the model does load.

So I believe the originally reported problem in this issue is a duplicate of #26809. 

Your example is slightly different -- your model does not specify input shape in any way, so it is constructed during the first call of the model. Such models however do not save the input shapes to h5 (and from h5 are similar to how a Sequential model is saved when the InputLayer is left out), so when you try to load the weights, the same code path triggers an error. If you
- add `input_shape=image_shape` parameter to the Conv2D, the model can be loaded;
- or if you load the model without loading weights, run it once, and only then load the weights, it can be loaded:
```python
# Instead of the original
model2 = tf.keras.models.load_model(fd.name, compile=False)
# this works; the JSON is also stored in h5 file, but it cannot be easily accessed, so I take it directly from the original model
model2 = tf.keras.models.model_from_json(model.to_json())
model2(inputs)
model2.load_weights(fd.name)
```

**Comment by hartikainen** [comment]
Thanks @foxik, this was useful. One thing I'm still wondering is, is this expected behavior or a bug? I'd expect `Sequential` model like the one in my above example to be saveable/loadable the same way as a model built with explicit input shapes. Or is there something that makes loading them more difficult?

**Comment by foxik** [comment]
The case in which an `Input` or `InputLayer` is an explicit part of model specification (like in the Minimal example of this issue description) it is definitely a bug (because the Input layer with information about input sizes is not saved).

Your case where the model dimensions is defined by first usage is semantically a bit different -- but personally I believe it is also a bug.

**Comment by rpgit12** [comment]
I'm having the same problem when combining two models; it happens even when leaving out Input and specifying the input_shape. If I don't combine the two models then it works fine.

````
from tensorflow.keras.models import Sequential, Model, load_model
from tensorflow.keras.layers import Dense, Flatten, Activation, Dropout, GlobalAveragePooling2D, Input
from tensorflow.keras import optimizers, applications

resnet = applications.InceptionResNetV2(weights='imagenet', include_top=False, input_shape=(100, 100, 3))
resnet.trainable = False
model_resnet = Model(inputs = resnet.input, outputs = resnet.output)
shape_resnet = model_resnet.output.shape.as_list()

model_out = Sequential([Flatten(),
                        Dense(1024, activation="relu",input_shape=(shape_resnet[0],np.prod(shape_resnet[1:]))),
                        Dropout(0.5),
                        Dense(4, activation="sigmoid")])

model = Model(inputs = resnet.input, outputs = model_out(model_resnet.output))

model_out.save('model.m')
m = load_model('model.m')
````

**Comment by ymodak** [comment]
This is fixed in latest TF 2.0 nightly build '2.0.0-dev20190718'
Thanks!

**Comment by hartikainen** [comment]
@ymodak is the example I posted above also supposed to work with `tf-nightly-gpu-2.0-preview==2.0.0-dev20190718`? I'm still seeing the same issue (with a slightly modified script):
```python
import tempfile

import tensorflow as tf


def main():
    batch_size = 3

    image_shape = (32, 32, 3)
    inputs = tf.random.uniform((batch_size, *image_shape))

    model = tf.keras.Sequential((
        tf.keras.layers.Conv2D(
            filters=16,
            kernel_size=3,
            strides=2,
            padding='SAME',
            activation='linear'),
    ))

    _ = model(inputs)

    with tempfile.NamedTemporaryFile(suffix='.hdf5', delete=True) as fd:
        tf.keras.models.save_model(model, fd.name, overwrite=True)
        model2 = tf.keras.models.load_model(fd.name, compile=False)

    print(model2.summary())


if __name__ == '__main__':
    main()
```

I get:
```
Traceback (most recent call last):
  File "/home/kristian/conda/envs/softlearning-2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kristian/conda/envs/softlearning-2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kristian/github/hartikainen/softlearning-2/tests/test_sequential_serialize.py", line 31, in <module>
    main()
  File "/home/kristian/github/hartikainen/softlearning-2/tests/test_sequential_serialize.py", line 25, in main
    model2 = tf.keras.models.load_model(fd.name, compile=False)
  File "/home/kristian/conda/envs/softlearning-2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 138, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/kristian/conda/envs/softlearning-2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 165, in load_model_from_hdf5
    load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "/home/kristian/conda/envs/softlearning-2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 671, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 1 layers into a model with 0 layers.
Exception ignored in: <function _TensorCacheDeleter.__del__ at 0x7f9fabdde158>
Traceback (most recent call last):
  File "/home/kristian/conda/envs/softlearning-2/lib/python3.7/site-packages/tensorflow_core/python/eager/context.py", line 316, in __del__
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by ymodak** [comment]
@hartikainen Thanks for testing against TF 2.0  Can you please post a new issue for the same? Its better to track this separately. Thanks!

**Comment by ClementWalter** [comment]
I still have this issue with the following versions :

```
from tensorflow import keras
keras.__version__
Out[27]: 
'2.2.4-tf'
import tensorflow
tensorflow.__version__
Out[29]: 
'2.0.0-beta1'
```

MWE:

```
from tensorflow.python.keras.layers import Conv2D, GlobalAveragePooling2D, Input
from tensorflow.python.keras.models import Sequential, load_model

model = Sequential([
    Input((224, 224, 3)),
    Conv2D(10, (3, 3)),
    GlobalAveragePooling2D(),
])
model.summary()

model.save('test.hdf5')

model_2 = load_model('test.hdf5')
```

**Comment by ghunkins** [comment]
Same issue. Highly frustrating that I cannot load models trained prior to `keras@2.3.x` into the `tf.keras` ecosystem. This is a blocking error for many developers wishing to transition from traditional `keras` to `tf.keras` and in turn `tensorflow@2.x.x`.

@hartikainen did @foxik 's answer solve your issue? Unless I'm missing a step, that did not solve my issue.

**Comment by hartikainen** [comment]
@ghunkins, no my case hasn't been resolved yet. My specific issues is tracked at https://github.com/tensorflow/tensorflow/issues/30892, but I don't know if there's been any work towards fixing that.

**Comment by andmax** [comment]
I've the same problem here.  My model was created, trained and saved using tf.keras and I'm *not* able to tf.keras.models.load_model it.  I saved the model using HDF5 entire model option as explained in this link: https://www.tensorflow.org/tutorials/keras/save_and_load ; the load_model function fails with a weird error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)

(...)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/network.py in from_config(cls, config, custom_objects)
   1150       assert layer_name in created_layers
   1151       layer = created_layers[layer_name]
-> 1152       layer_output_tensors = layer._inbound_nodes[node_index].output_tensors
   1153       output_tensors.append(nest.flatten(layer_output_tensors)[tensor_index])
   1154 

IndexError: list index out of range

**Comment by jvishnuvardhan** [comment]
@andmax Please create a new issue as your error is different so that others with similar error will get benefited. ping me once you create. We will resolve. Thanks!

**Comment by andmax** [comment]
Hi @jvishnuvardhan  I've already created an issue:
https://github.com/tensorflow/tensorflow/issues/33357
And it seems it will be fixed on next release TF 1.15rc/2.0.
Thanks!

**Comment by uchihatashi** [comment]
hi, guys, I m getting a similar error  

np.set_printoptions(suppress=True)
model = tensorflow.keras.models.load_model('keras_model.h5')

ValueError: ('Unrecognized keyword arguments:', dict_keys(['input_dtype']))

please tell me how to solve it.
many thanks in advance!

**Comment by jvishnuvardhan** [comment]
@uchihatashi Can you please create a new issue with details and a standalone code to reproduce your error. Thanks!

**Comment by uchihatashi** [comment]
@jvishnuvardhan hey thanks a lot for the response and I found my error as I was having a problem with the version of TensorFlow and Keras.
