### ISSUE TITLE
TypeError: 'Not JSON Serializable' while doing tf.keras.Model.save and using keras variable in loss_weights in tf.keras.Model.compile

### ISSUE THREAD

**Issue by tejal567** [tensorflow/tensorflow#28799]
**System information**
- Have I written custom code: NA
- OS Platform and Distribution: Ubuntu 16.04 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0
- Python version: 3.5.2
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: release 9.0, V9.0.176
- GPU model and memory: Tesla K80, 12 GB

**Describe the current behavior**
When I try to save my model using model.save() where model is a tf.keras.Model instance, it throws a _TypeError: ('Not JSON Serializable:', <tf.Variable 'Variable:0' shape=() dtype=float32>)_ .
I am using a tf.keras.backend.variable() in loss_weights in model.compile.
Optimizer: tf.keras.optimizers.Adam
Interestingly, when I try to save my model weights only using model.save_weights where model is a tf.keras.Model instance, it works fine, NO ERROR.

**Describe the expected behavior**
It should not throw any type of error during training.

**Code to reproduce the issue**
`import tensorflow as tf`
`import numpy as np`
`import os`
`import sys`

`input_layer = tf.keras.layers.Input(shape=([4,3]), batch_size=1)`
`layer1 = tf.keras.layers.Dense(20)(input_layer)`
`layer2 = tf.keras.layers.Dense(1,name="output1")(layer1)`
`layer3 = tf.keras.layers.Dense(1,name="output2")(layer1)`
`model = tf.keras.Model(inputs=input_layer, outputs=[layer2,layer3])`
`alpha = tf.keras.backend.variable(0.25)`
`model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.001),loss={"output1":tf.keras.metrics.binary_crossentropy,"output2":tf.keras.metrics.binary_crossentropy},loss_weights=[1.0,alpha])`

`# model.fit() is skipped just to get straight to error.`
`model.save("./weights.h5")`

Just execute this code as it is, It will throw same error!!

**Other info / logs**
Traceback (most recent call last):
  File "main_latest.py", line 45, in <module>
    max_queue_size=10)
  File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 2177, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/training_generator.py", line 216, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/callbacks.py", line 214, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/callbacks.py", line 601, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1363, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/saving.py", line 134, in save_model
    default=serialization.get_json_type).encode('utf8')
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/util/serialization.py", line 64, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', <tf.Variable 'Variable:0' shape=() dtype=float32>)

![TypeError](https://user-images.githubusercontent.com/14198246/57926377-b8290880-78c8-11e9-92fa-d03803a27123.PNG)

**Comment by tejal567** [comment]
Similar Issue (Open): https://github.com/tensorflow/tensorflow/issues/28010

**Comment by muddham** [comment]
@tejal567 Please provide reproducible full code to investigate this issue. After I ran this code it says : NameError: name 'get_model' is not defined

**Comment by tejal567** [comment]
`import tensorflow as tf`
`import numpy as np`
`import os`
`import sys`

`input_layer = tf.keras.layers.Input(shape=([4,3]), batch_size=1)`
`layer1 = tf.keras.layers.Dense(20)(input_layer)`
`layer2 = tf.keras.layers.Dense(1,name="output1")(layer1)`
`layer3 = tf.keras.layers.Dense(1,name="output2")(layer1)`
`model = tf.keras.Model(inputs=input_layer, outputs=[layer2,layer3])`
`alpha = tf.keras.backend.variable(0.25)`
`model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.001),loss={"output1":tf.keras.metrics.binary_crossentropy,
                                                                "output2":tf.keras.metrics.binary_crossentropy},
                                                                loss_weights=[1.0,alpha])`

`# model.fit() is skipped just to get straight to error.`
`model.save("./weights.h5")`

Just execute this code as it is, It will throw same error!!

**Comment by muddham** [comment]
@tejal567 Able to reproduce the issue with the provided code.
TypeError: ('Not JSON Serializable:', <tf.Variable 'Variable:0' shape=() dtype=float32>)

**Comment by tejal567** [comment]
@fchollet Can you please have a look at it

**Comment by tejal567** [comment]
@k-w-w awaiting for your response, please have a look at it

**Comment by vsatyakumar** [comment]
@fchollet Is there a fix for this?

**Comment by hno1993** [comment]
this error also appears when I try to save a transformer model using tensorflow 2.0  

code link: https://github.com/bryanlimy/tf2-transformer-chatbot

how i try to save the model:
`model.save('hnosa.model')` 

this error appears: 
`Traceback (most recent call last):

  File "<ipython-input-1-ce3301d571a9>", line 1, in <module>
    runfile('C:/Users/alhno/DS/tf2-transformer-chatbot-master/main.py', wdir='C:/Users/alhno/DS/tf2-transformer-chatbot-master')

  File "C:\Users\alhno\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\alhno\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/alhno/DS/tf2-transformer-chatbot-master/main.py", line 163, in <module>
    main(hparams)

  File "C:/Users/alhno/DS/tf2-transformer-chatbot-master/main.py", line 128, in main
    model.save('hnosa.model')

  File "C:\Users\alhno\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1213, in save
    saving.save_model(self, filepath, overwrite, include_optimizer, save_format)

  File "C:\Users\alhno\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\save.py", line 106, in save_model
    saved_model.save(model, filepath, overwrite, include_optimizer)

  File "C:\Users\alhno\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\saved_model.py", line 1492, in save
    save_lib.save(model, filepath)

  File "C:\Users\alhno\Anaconda3\lib\site-packages\tensorflow\python\saved_model\save.py", line 849, in save
    saveable_view, asset_info.asset_index)

  File "C:\Users\alhno\Anaconda3\lib\site-packages\tensorflow\python\saved_model\save.py", line 604, in _serialize_object_graph
    _write_object_proto(obj, obj_proto, asset_file_def_index)

  File "C:\Users\alhno\Anaconda3\lib\site-packages\tensorflow\python\saved_model\save.py", line 643, in _write_object_proto
    metadata=obj._tracking_metadata)

  File "C:\Users\alhno\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2705, in _tracking_metadata
    metadata = json.loads(super(Model, self)._tracking_metadata)

  File "C:\Users\alhno\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2213, in _tracking_metadata
    return json.dumps(metadata, default=serialization.get_json_type)

  File "C:\Users\alhno\Anaconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)

  File "C:\Users\alhno\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "C:\Users\alhno\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)

  File "C:\Users\alhno\Anaconda3\lib\site-packages\tensorflow\python\util\serialization.py", line 69, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)

TypeError: ('Not JSON Serializable:', b'\n?transformer/encoder/tf_op_layer_mul/encoder/tf_op_layer_mul/mul\x12\x03Mul\x1a\x12embedding/Identity\x1a\x05mul/y*\x07\n\x01T\x12\x020\x01')`

**Comment by k-w-w** [comment]
@vsatyakumar Currently, you can't use tensorflow variables objects in the compiled args. I'll see if there is a fix for this. For now, a workaround would be to save the uncompiled version of the model, then manually re-compile once its loaded.

@hno1993 I believe if you wrapped the encoder ops (shown below) as a custom layer, the serialization would work.

```
 embeddings = tf.keras.layers.Embedding(hparams.vocab_size,
                                         hparams.d_model)(inputs)
  embeddings *= tf.math.sqrt(tf.cast(hparams.d_model, tf.float32))
  embeddings = PositionalEncoding(hparams)(embeddings)

  outputs = tf.keras.layers.Dropout(hparams.dropout)(embeddings)
```

Your code may be buggy if you're running in eager mode, since `tf.keras.layers.Embedding(...)(inputs)` would immediately evaluate the variables in the Embedding layer to constant values.

**Comment by vsatyakumar** [comment]
@k-w-w, thanks for the suggestion. However, this doesn't help since saving model weights (checkpoints) fails during training aswell.

**Comment by k-w-w** [comment]
Are you saving just the weights or the model? If just the weights, then `model.save_weights` should suffice.

**Comment by ppham27** [comment]
@hno1993 I see you're using Conda to manage your packages, which may mean your Tensorflow installation doesn't contain all the latest fixes.

That error should be fixed by https://github.com/tensorflow/tensorflow/commit/39bc7bcf94983261a3ee8a72802f5de056728a9c#diff-8eb7e20502209f082d0cb15119a50413.

Try using the latest RC or nightly.

**Comment by jvishnuvardhan** [comment]
@tejal567 [Here is the gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/d96b3a426058b99a212a4ec256ff76f6/untitled560.ipynb) with the workaround mentioned by @k-w-w . There is a limitation of what can be part of compile. 

Please close the issue if this was resolved for you. thanks!

**Comment by tejal567** [comment]
Not resolved for me. So can we say that as of now there is no way of saving a model (model.save()) compiled using variables (tf.keras.backend.variable) in loss_weights ? @jvishnuvardhan

**Comment by jvishnuvardhan** [comment]
@tejal567 Correct. If you have a solution, you could contribute by raising Pull-requests(PR) to change the codes. Thanks!

**Comment by was84san** [comment]
I would like to add that It is not just throwing this error when trying to save the model at the end of an epoch, the loss_weights do nothing to the total loss. My loss weights for two output network is `{'out1': alpha, 'out2': 1-alpah} `and alpha begins with 0 and ends to 1 by using some update equation which depends on the epoch number and by using callback of course. So the loss for `'out1' `should be zero for the first epoch , but both losses are working without any multiplication with the loss_weights. The only solution for me is to build a custom loss function, but I still need this issue to be fixed because you want to use the build-in keras losses and sometimes it is hard to build the same loss by yourself. So is there fix in a near future for this?

**Comment by mokundong** [comment]
I also had this problem when i use checkpoint. btw ,my loss is customLsyer 

the error log:
`WARNING:tensorflow:From /Users/mkd/Project/PythonProjects/search_query_intention/model/DssmRNN_ali.py:368: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... ('Not JSON Serializable:', <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.5>)
Epoch 1/2
WARNING:tensorflow:Gradients do not exist for variables ['Variable:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['Variable:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['Variable:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['Variable:0'] when minimizing the loss.
2020-08-15 22:36:19.344394: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
   1/1000 [..............................] - ETA: 0s - loss: 1440.2056 - cosine_accuracy: 0.8320 - catclass_accuracy: 0.0000e+002020-08-15 22:36:19.432737: I tensorflow/core/profiler/rpc/client/save_profile.cc:168] Creating directory: logs/bigru_sample_twins_char_term_test/train/plugins/profile/2020_08_15_22_36_19
2020-08-15 22:36:19.448521: I tensorflow/core/profiler/rpc/client/save_profile.cc:174] Dumped gzipped tool data for trace.json.gz to logs/bigru_sample_twins_char_term_test/train/plugins/profile/2020_08_15_22_36_19/KDM.local.trace.json.gz
2020-08-15 22:36:19.463320: I tensorflow/core/profiler/utils/event_span.cc:288] Generation of step-events took 0.834 ms
2020-08-15 22:36:19.471340: I tensorflow/python/profiler/internal/profiler_wrapper.cc:87] Creating directory: logs/bigru_sample_twins_char_term_test/train/plugins/profile/2020_08_15_22_36_19Dumped tool data for overview_page.pb to logs/bigru_sample_twins_char_term_test/train/plugins/profile/2020_08_15_22_36_19/KDM.local.overview_page.pb
Dumped tool data for input_pipeline.pb to logs/bigru_sample_twins_char_term_test/train/plugins/profile/2020_08_15_22_36_19/KDM.local.input_pipeline.pb
Dumped tool data for tensorflow_stats.pb to logs/bigru_sample_twins_char_term_test/train/plugins/profile/2020_08_15_22_36_19/KDM.local.tensorflow_stats.pb
Dumped tool data for kernel_stats.pb to logs/bigru_sample_twins_char_term_test/train/plugins/profile/2020_08_15_22_36_19/KDM.local.kernel_stats.pb
1000/1000 [==============================] - ETA: 0s - loss: 489.9940 - cosine_accuracy: 0.6109 - catclass_accuracy: 0.32022020-08-15 22:37:10.213564: W tensorflow/python/util/util.cc:329] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From /Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4f1fee32864f>", line 1, in <module>
    runfile('/Users/mkd/Project/PythonProjects/search_query_intention/bigru_multi_in_and_out_ali_test.py', wdir='/Users/mkd/Project/PythonProjects/search_query_intention')
  File "/Users/mkd/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.7288.30/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/mkd/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.7288.30/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/mkd/Project/PythonProjects/search_query_intention/bigru_multi_in_and_out_ali_test.py", line 98, in <module>
    callbacks=callback_list, workers=1, use_multiprocessing=False, shuffle=True)
  File "/Users/mkd/Project/PythonProjects/search_query_intention/model/DssmRNN_ali.py", line 368, in train
    shuffle=shuffle
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1479, in fit_generator
    initial_epoch=initial_epoch)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 876, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 365, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 1177, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 1214, in _save_model
    self.model.save(filepath, overwrite=True)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1052, in save
    signatures, options)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 138, in save_model
    signatures, options)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/save.py", line 78, in save
    save_lib.save(model, filepath, signatures, options)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 951, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 1037, in _build_meta_graph
    asset_info.asset_index)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 697, in _serialize_object_graph
    saveable_view.function_name_map)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 737, in _write_object_proto
    metadata=obj._tracking_metadata)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2742, in _tracking_metadata
    return self._trackable_saved_model_saver.tracking_metadata
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 54, in tracking_metadata
    return json_utils.Encoder().encode(self.python_properties)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 44, in encode
    return super(Encoder, self).encode(_encode_tuple(obj))
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 41, in default
    return serialization.get_json_type(obj)
  File "/Users/mkd/miniconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/util/serialization.py", line 76, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.5>)`


`class CustomMultiLossLayer_test(Layer):
    def __init__(self, nb_outputs=2, n_class=1000, **kwargs):
        self.nb_outputs = nb_outputs
        self.n_class = n_class
        self.bin_acc = BinaryAccuracy(name="bin_acc")
        self.spc_acc = CategoricalAccuracy(name="nor_acc")
        super(CustomMultiLossLayer_test, self).__init__(**kwargs)

    def build(self, input_shape=None):
        self.log_vars = []

        for i in range(self.nb_outputs):
            self.log_vars += [self.add_weight(name='log_var' + str(i), shape=(1,),
                                              initializer=Constant(0.), trainable=True)]
        super(CustomMultiLossLayer_test, self).build(input_shape)

    def multi_loss(self, ys_true, ys_pred):
        assert len(ys_true) == self.nb_outputs and len(ys_pred) == self.nb_outputs
        yc_ture = ys_true[0]
        yl_ture = ys_true[1]
        yc_pred = ys_pred[0]
        yl_pred = ys_pred[1]
        loss = 0
        cos_acc = 0
        cat_acc = 0
        # cosine loss
        precision = K.exp(-self.log_vars[0][0])
        loss += K.sum(
            precision * K.binary_crossentropy(yc_ture, yc_pred) + self.log_vars[0][0], -1)
        # cat loss
        precision = K.exp(-self.log_vars[1][0])
        loss += K.sum(
            precision * K.categorical_crossentropy(yl_ture, yl_pred) + self.log_vars[1][0], -1)
        # cosine acc
        _ = self.bin_acc.update_state(yc_ture, yc_pred)
        cos_acc += self.bin_acc.result()
        # cat acc
        _ = self.spc_acc.update_state(yl_ture, yl_pred)
        cat_acc += self.spc_acc.result()

        return K.mean(loss), K.mean(cos_acc), K.mean(cat_acc)

    def call(self, inputs, **kwargs):
        ys_true = inputs[:self.nb_outputs]
        ys_pred = inputs[self.nb_outputs:]
        loss, cos_acc, cat_acc = self.multi_loss(ys_true, ys_pred)
        self.add_loss(loss, inputs=inputs)
        self.add_metric(cos_acc, name="cosine_accuracy", aggregation='mean')
        self.add_metric(cat_acc, name="catclass_accuracy", aggregation='mean')
        return ys_true[0]

    def get_config(self, ):
        config = {"nb_outputs": self.nb_outputs, "bin_acc": self.bin_acc,
                  "nor_acc": self.spc_acc, "n_class": self.n_class}
        base_config = super(CustomMultiLossLayer_test, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))`

**Comment by tejal567** [comment]
I think enough has been said about this issue

**Comment by momodagithub** [comment]
Is the problem solved？I meet the same problem when saving a model with custom layer（in this layer ,I use the add_weight function）,the tensorflow vesion is 2.0.0

**Comment by sandippaul7204** [comment]
Was the issue solved? I dont get the feel of the solution

**Comment by Janesefor** [comment]
> Not resolved for me. So can we say that as of now there is no way of saving a model (model.save()) compiled using variables (tf.keras.backend.variable) in loss_weights ? @jvishnuvardhan

Recently I also meet this problem .Because it says tf.Variables can't be json serializable so i just let key variable V(for example) be V.numpy() as parameters' input and it can help.Maybe making it not be type of tf.Variable will matter.

**Comment by Janesefor** [comment]
> **System information**
> 
> * Have I written custom code: NA
> * OS Platform and Distribution: Ubuntu 16.04 LTS
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
> * TensorFlow installed from (source or binary): binary
> * TensorFlow version (use command below): 1.12.0
> * Python version: 3.5.2
> * Bazel version (if compiling from source): NA
> * GCC/Compiler version (if compiling from source): NA
> * CUDA/cuDNN version: release 9.0, V9.0.176
> * GPU model and memory: Tesla K80, 12 GB
> 
> **Describe the current behavior**
> When I try to save my model using model.save() where model is a tf.keras.Model instance, it throws a _TypeError: ('Not JSON Serializable:', <tf.Variable 'Variable:0' shape=() dtype=float32>)_ .
> I am using a tf.keras.backend.variable() in loss_weights in model.compile.
> Optimizer: tf.keras.optimizers.Adam
> Interestingly, when I try to save my model weights only using model.save_weights where model is a tf.keras.Model instance, it works fine, NO ERROR.
> 
> **Describe the expected behavior**
> It should not throw any type of error during training.
> 
> **Code to reproduce the issue**
> `import tensorflow as tf`
> `import numpy as np`
> `import os`
> `import sys`
> 
> `input_layer = tf.keras.layers.Input(shape=([4,3]), batch_size=1)`
> `layer1 = tf.keras.layers.Dense(20)(input_layer)`
> `layer2 = tf.keras.layers.Dense(1,name="output1")(layer1)`
> `layer3 = tf.keras.layers.Dense(1,name="output2")(layer1)`
> `model = tf.keras.Model(inputs=input_layer, outputs=[layer2,layer3])`
> `alpha = tf.keras.backend.variable(0.25)`
> `model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.001),loss={"output1":tf.keras.metrics.binary_crossentropy,"output2":tf.keras.metrics.binary_crossentropy},loss_weights=[1.0,alpha])`
> 
> `# model.fit() is skipped just to get straight to error.`
> `model.save("./weights.h5")`
> 
> Just execute this code as it is, It will throw same error!!
> 
> **Other info / logs**
> Traceback (most recent call last):
> File "main_latest.py", line 45, in
> max_queue_size=10)
> File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 2177, in fit_generator
> initial_epoch=initial_epoch)
> File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/training_generator.py", line 216, in fit_generator
> callbacks.on_epoch_end(epoch, epoch_logs)
> File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/callbacks.py", line 214, in on_epoch_end
> callback.on_epoch_end(epoch, logs)
> File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/callbacks.py", line 601, in on_epoch_end
> self.model.save(filepath, overwrite=True)
> File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1363, in save
> save_model(self, filepath, overwrite, include_optimizer)
> File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/keras/engine/saving.py", line 134, in save_model
> default=serialization.get_json_type).encode('utf8')
> File "/usr/lib/python3.5/json/**init**.py", line 237, in dumps
> **kw).encode(obj)
> File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
> chunks = self.iterencode(o, _one_shot=True)
> File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
> return _iterencode(o, 0)
> File "/home/tejal/.local/lib/python3.5/site-packages/tensorflow/python/util/serialization.py", line 64, in get_json_type
> raise TypeError('Not JSON Serializable:', obj)
> TypeError: ('Not JSON Serializable:', <tf.Variable 'Variable:0' shape=() dtype=float32>)
> 
> ![TypeError](https://user-images.githubusercontent.com/14198246/57926377-b8290880-78c8-11e9-92fa-d03803a27123.PNG)

add .numpy() after alpha ,like the flowing:
model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.001),loss={"output1":tf.keras.metrics.binary_crossentropy,"output2":tf.keras.metrics.binary_crossentropy},loss_weights=[1.0,alpha.numpy()])

**Comment by Janesefor** [comment]
replacing alpha with alpha.numpy() will be ok in my computer.

**Comment by yinguobing** [comment]
I encountered this issue in my project and have fixed it with @Janesefor's solution.

The reason for this is that I was using `tf` function when building the model:
```
num_identity = tf.cast(tf.math.ceil(num_input_channels * split), tf.int32)
```

Append `.numpy()` at the end like this:
```
num_identity = tf.cast(tf.math.ceil(num_input_channels * split), tf.int32).numpy()
```

Then the model could be saved as `saved_model` format.

**Comment by awsaf49** [comment]
for those who are building custom model using `tf.keras.models.Model` or `tf.keras.layers.Layer` **subclass** and got into the same error, you can try out this solution,
instead of 
```
dim = (512, 512, 3)
def get_model(dim):
    input = tf.keras.Input(shape=dim)
    .....
```
 you can try this,
```
dim = (512, 512, 3)
def get_model(dim):
    dim  = np.array(dim)
    input = tf.keras.Input(shape=dim)
    .....
```
This should fix your problem also don't forget to use `get_config()` method.

**Comment by Murtadha44** [comment]
This might be related:
https://keras.io/guides/serialization_and_saving/

I had a similar issue when trying to save a model with a custom layer. I had to add .numpy() to the new variable in get_config function as follows:

class rand_rotate_layer(tf.keras.layers.Layer):
    def __init__(self, batchsize=None, seg_len=None, dim=None, **kwargs):
        super(rand_rotate_layer, self).__init__(**kwargs)
        self.signal_v = tf.Variable(tf.zeros((batchsize, seg_len, dim)), trainable=False)

    def get_config(self): 
        config = super().get_config().copy()
        config.update({
            'signal_v': self.signal_v.numpy()
        })
        return config

**Comment by formigone** [comment]
How I solved the issue on my particular case (no `.numpy()` needed):

In my case, I have a custom layer that outputs a constant tensor. Concretely, I want the model to always output a const string (ex: model version).

```python
class ConstantTensorLayer(Layer):
   def __init__(self, data, **kwargs):
      super(ConstantTensorLayer, self).__init__(**kwargs)
      self.data = tf.constant(data)

   def call(self, x):
      return tf.keras.layers.Reshape((-1,), name='Reshaped_ConstTensorLayer')(self.data)

   def get_config(self):
        config = super().get_config().copy()
        config.update({
            'data': self.data,
        })
        return config
```

Saving the model raises that lovely exception everyone's been talking about, that the layer is not JSON serializable.

Turns out the issue with the code above is that the layer receives a python object as input, but `get_config()` returns a tensor.

```python
layer = ConstantTensorLayer(['v1.2.3'])
# Python List[str] -----------^^^^^^^

layer.get_config()
>>> {'data': <EagerTensor>}
```

## My Solution

The solution is obvious once I realized the relationship between the custom layer's input (what `__init__()` takes) and its config (what `get_config()` returns). What `get_config()` must return is the same thing that the initializer receives:

```python
class ConstantTensorLayer(Layer):
   def __init__(self, data, **kwargs):
      super(ConstantTensorLayer, self).__init__(**kwargs)

      # Save the initializer's input as-is
      self.data = data

      # Create/store native tensors as desired
      self.tensor = tf.constant(data)

   def call(self, x):
      return tf.keras.layers.Reshape((-1,), name='Reshaped_ConstTensorLayer')(self.data)

   def get_config(self):
        config = super().get_config().copy()

        config.update({
             # Return the original input --+
             #                             |
             #            +----------------+
             #            |
             #            v
            'data': self.data,
        })

        return config
```

Now things work as expected (since my mental model is  now correct)

```python
layer = ConstantTensorLayer(['v1.2.3'])
# Python List[str] -----------^^^^^^^

layer.get_config()
>>> {'data': ['v1.2.3']}
#               ^
#               |
#               +--- JSON serializable 🎉 
```

**Comment by MohitYadav671** [comment]
@formigone  it is not working
 please check my code 

from __future__ import absolute_import, division, print_function, unicode_literals
import readline

import sys
from sklearn.covariance import oas
import tensorflow as tf
import tensorflow_datasets as tfds
import os
import re
import numpy 
from time import time
import matplotlib.pyplot as plt
import keras
import readline

from keras import optimizers
import csv
tf.random.set_seed(1234)
AUTO = tf.data.experimental.AUTOTUNE
# Maximum sentence length
MAX_LENGTH = 150

# Maximum number of samples to preprocess
MAX_SAMPLES = 200000

# For tf.data.Dataset
BATCH_SIZE = 32
BUFFER_SIZE = 50000

# For Transformer
NUM_LAYERS = 2
D_MODEL = 256
NUM_HEADS = 8
UNITS = 512
DROPOUT = 0.1

EPOCHS = 40

path_to_dataset = os.path.dirname("./data/")
data1 = os.path.join(path_to_dataset, '1.csv')
datafull = os.path.join(path_to_dataset,'chat.txt')
checkpoint_path = os.path.dirname("/checkpoints")


def preprocess_sentence(sentence):
  sentence = sentence.lower().strip()
  # creating a space between a word and the punctuation following it
  # eg: "he is a boy." => "he is a boy ."
  sentence = re.sub(r"([?.!,])", r" \1 ", sentence)
  sentence = re.sub(r'[" "]+', " ", sentence)
  # removing contractions
  sentence = re.sub(r"i'm", "i am", sentence)
  sentence = re.sub(r"he's", "he is", sentence)
  sentence = re.sub(r"she's", "she is", sentence)
  sentence = re.sub(r"it's", "it is", sentence)
  sentence = re.sub(r"that's", "that is", sentence)
  sentence = re.sub(r"what's", "that is", sentence)
  sentence = re.sub(r"where's", "where is", sentence)
  sentence = re.sub(r"how's", "how is", sentence)
  sentence = re.sub(r"\'ll", " will", sentence)
  sentence = re.sub(r"\'ve", " have", sentence)
  sentence = re.sub(r"\'re", " are", sentence)
  sentence = re.sub(r"\'d", " would", sentence)
  sentence = re.sub(r"\'re", " are", sentence)
  sentence = re.sub(r"won't", "will not", sentence)
  sentence = re.sub(r"can't", "cannot", sentence)
  sentence = re.sub(r"n't", " not", sentence)
  sentence = re.sub(r"n'", "ng", sentence)
  sentence = re.sub(r"'bout", "about", sentence)
  # replacing everything with space except (a-z, A-Z, ".", "?", "!", ",")
  sentence = re.sub(r"[^a-zA-Z?.!,]+", " ", sentence)
  sentence = sentence.strip()
  return sentence


def load_conversations():
    # dictionary of line id to text
    id2line = {}
    inputs, outputs = [], []

    with open(datafull,encoding="utf8") as file:
        cb = file.readlines()
        l = 0
        while l <= 377:
           inputs.append(preprocess_sentence(cb[l]))
           outputs.append(preprocess_sentence(cb[l+1]))
           l+=2
        if len(inputs) >= MAX_SAMPLES:
            return inputs,outputs
    
    return inputs,outputs

questions, answers = load_conversations()
#377266


# Build tokenizer using tfds for both questions and answers
tokenizer = tfds.deprecated.text.SubwordTextEncoder.build_from_corpus(
    questions + answers, target_vocab_size=2**13)

# Define start and end token to indicate the start and end of a sentence
START_TOKEN, END_TOKEN = [tokenizer.vocab_size], [tokenizer.vocab_size + 1]

# Vocabulary size plus start and end token
VOCAB_SIZE = tokenizer.vocab_size + 2


# Tokenize, filter and pad sentences
def tokenize_and_filter(inputs, outputs):
  tokenized_inputs, tokenized_outputs = [], []
  
  for (sentence1, sentence2) in zip(inputs, outputs):
    # tokenize sentence
    sentence1 = START_TOKEN + tokenizer.encode(sentence1) + END_TOKEN
    sentence2 = START_TOKEN + tokenizer.encode(sentence2) + END_TOKEN
    # check tokenized sentence max length
    if len(sentence1) <= MAX_LENGTH and len(sentence2) <= MAX_LENGTH:
      tokenized_inputs.append(sentence1)
      tokenized_outputs.append(sentence2)
  
  # pad tokenized sentences
  tokenized_inputs = tf.keras.preprocessing.sequence.pad_sequences(
      tokenized_inputs, maxlen=MAX_LENGTH, padding='post')
  tokenized_outputs = tf.keras.preprocessing.sequence.pad_sequences(
      tokenized_outputs, maxlen=MAX_LENGTH, padding='post')
  
  return tokenized_inputs, tokenized_outputs


questions, answers = tokenize_and_filter(questions, answers)

# decoder inputs use the previous target as input
# remove START_TOKEN from targets
dataset = tf.data.Dataset.from_tensor_slices((
    {
        'inputs': questions,
        'dec_inputs': answers[:, :-1]
    },
    {
        'outputs': answers[:, 1:]
    },
))

dataset = dataset.cache()
dataset = dataset.shuffle(BUFFER_SIZE)
dataset = dataset.batch(BATCH_SIZE)
dataset = dataset.prefetch(tf.data.experimental.AUTOTUNE)












def scaled_dot_product_attention(query, key, value, mask):
  """Calculate the attention weights. """
  matmul_qk = tf.matmul(query, key, transpose_b=True)

  # scale matmul_qk
  depth = tf.cast(tf.shape(key)[-1], tf.float32)
  logits = matmul_qk / tf.math.sqrt(depth)

  # add the mask to zero out padding tokens
  if mask is not None:
    logits += (mask * -1e9)

  # softmax is normalized on the last axis (seq_len_k)
  attention_weights = tf.nn.softmax(logits, axis=-1)

  output = tf.matmul(attention_weights, value)

  return output


class MultiHeadAttention(keras.layers.Layer):

  def __init__(self, d_model, num_heads, name="multi_head_attention"):
    super(MultiHeadAttention, self).__init__(name=name)
    self.num_heads = num_heads
    self.d_model = d_model
  
    assert d_model % self.num_heads == 0

    self.depth = d_model // self.num_heads

    self.query_dense = tf.keras.layers.Dense(units=d_model)
    self.key_dense = tf.keras.layers.Dense(units=d_model)
    self.value_dense = tf.keras.layers.Dense(units=d_model)

    self.dense = tf.keras.layers.Dense(units=d_model)
  
  def get_config(self):
        config = super(MultiHeadAttention,self).get_config()
        config.update({
            'num_heads':self.num_heads,
            'd_model':self.d_model,
        })
        return config

  def split_heads(self, inputs, batch_size):
    inputs = tf.keras.layers.Lambda(lambda inputs:tf.reshape(
        inputs, shape=(batch_size, -1, self.num_heads, self.depth)))(inputs)
    return tf.keras.layers.Lambda(lambda inputs: tf.transpose(inputs, perm=[0, 2, 1, 3]))(inputs)

  def call(self, inputs):
    query, key, value, mask = inputs['query'], inputs['key'], inputs[
        'value'], inputs['mask']
    batch_size = tf.shape(query)[0]

    # linear layers
    query = self.query_dense(query)
    key = self.key_dense(key)
    value = self.value_dense(value)

    # split heads
    query = self.split_heads(query, batch_size)
    key = self.split_heads(key, batch_size)
    value = self.split_heads(value, batch_size)

    # scaled dot-product attention
    scaled_attention = scaled_dot_product_attention(query, key, value, mask)
    scaled_attention = tf.keras.layers.Lambda(lambda scaled_attention: tf.transpose(
        scaled_attention, perm=[0, 2, 1, 3]))(scaled_attention)

    # concatenation of heads
    concat_attention = tf.keras.layers.Lambda(lambda scaled_attention: tf.reshape(scaled_attention,
                                  (batch_size, -1, self.d_model)))(scaled_attention)

    # final linear layer
    outputs = self.dense(concat_attention)

    return outputs    


def create_padding_mask(x):
  mask = tf.cast(tf.math.equal(x, 0), tf.float32)
  # (batch_size, 1, 1, sequence length)
  return mask[:, tf.newaxis, tf.newaxis, :]


def create_look_ahead_mask(x):
  seq_len = tf.shape(x)[1]
  look_ahead_mask = 1 - tf.linalg.band_part(tf.ones((seq_len, seq_len)), -1, 0)
  padding_mask = create_padding_mask(x)
  return tf.maximum(look_ahead_mask, padding_mask)


class PositionalEncoding(keras.layers.Layer):

  def __init__(self, position, d_model,name=None,**kwargs):
   
    super(PositionalEncoding, self).__init__(name=name)
    self.pos_encoding = self.positional_encoding(position, d_model)
    super(PositionalEncoding, self).__init__(**kwargs)
    self.position = position
    self.d_model = d_model
  def get_config(self):

    config = super(PositionalEncoding, self).get_config()
    config.update({
      'position': self.position,
      'd_model': self.d_model
  
      })
    return config

  def get_angles(self, position, i, d_model):
    angles = 1 / tf.pow(10000, (2 * (i // 2)) / tf.cast(d_model, tf.float32))
    return position * angles

  def positional_encoding(self, position, d_model):
    angle_rads = self.get_angles(
        position=tf.range(position, dtype=tf.float32)[:, tf.newaxis],
        i=tf.range(d_model, dtype=tf.float32)[tf.newaxis, :],
        d_model=d_model)
    # apply sin to even index in the array
    sines = tf.math.sin(angle_rads[:, 0::2])
    # apply cos to odd index in the array
    cosines = tf.math.cos(angle_rads[:, 1::2])

    pos_encoding = tf.concat([sines, cosines], axis=-1)
    pos_encoding = pos_encoding[tf.newaxis, ...]
    return tf.cast(pos_encoding, tf.float32)

  def call(self, inputs):
    return inputs + self.pos_encoding[:, :tf.shape(inputs)[1], :]


def encoder_layer(units, d_model, num_heads, dropout, name="encoder_layer"):
  inputs = tf.keras.Input(shape=(None, d_model), name="inputs")
  padding_mask = tf.keras.Input(shape=(1, 1, None), name="padding_mask")

  attention = MultiHeadAttention(
      d_model, num_heads, name="attention")({
          'query': inputs,
          'key': inputs,
          'value': inputs,
          'mask': padding_mask
      })
  attention = tf.keras.layers.Dropout(rate=dropout)(attention)
  add_attention = tf.keras.layers.add([inputs,attention])
  attention = tf.keras.layers.LayerNormalization(epsilon=1e-6)(add_attention)

  outputs = tf.keras.layers.Dense(units=units, activation='relu')(attention)
  outputs = tf.keras.layers.Dense(units=d_model)(outputs)
  outputs = tf.keras.layers.Dropout(rate=dropout)(outputs)
  add_attention = tf.keras.layers.add([attention,outputs])
  outputs = tf.keras.layers.LayerNormalization(epsilon=1e-6)(add_attention)

  return tf.keras.Model(
      inputs=[inputs, padding_mask], outputs=outputs, name=name)


def encoder(vocab_size,
            num_layers,
            units,
            d_model,
            num_heads,
            dropout,
            name="encoder"):
  inputs = tf.keras.Input(shape=(None,), name="inputs")
  padding_mask = tf.keras.Input(shape=(1, 1, None), name="padding_mask")

  embeddings = tf.keras.layers.Embedding(vocab_size, d_model)(inputs)
  embeddings *= tf.keras.layers.Lambda(lambda d_model: tf.math.sqrt(tf.cast(d_model, tf.float32)))(d_model)
  embeddings = PositionalEncoding(vocab_size,d_model)(embeddings)

  outputs = tf.keras.layers.Dropout(rate=dropout)(embeddings)

  for i in range(num_layers):
    outputs = encoder_layer(
        units=units,
        d_model=d_model,
        num_heads=num_heads,
        dropout=dropout,
        name="encoder_layer_{}".format(i),
    )([outputs, padding_mask])

  return tf.keras.Model(
      inputs=[inputs, padding_mask], outputs=outputs, name=name)

    
def decoder_layer(units, d_model, num_heads, dropout, name="decoder_layer"):
  inputs = tf.keras.Input(shape=(None, d_model), name="inputs")
  enc_outputs = tf.keras.Input(shape=(None, d_model), name="encoder_outputs")
  look_ahead_mask = tf.keras.Input(
      shape=(1, None, None), name="look_ahead_mask")
  padding_mask = tf.keras.Input(shape=(1, 1, None), name='padding_mask')

  attention1 = MultiHeadAttention(
      d_model, num_heads, name="attention_1")(inputs={
          'query': inputs,
          'key': inputs,
          'value': inputs,
          'mask': look_ahead_mask
      })
  add_attention = tf.keras.layers.add([attention1,inputs])    
  attention1 = tf.keras.layers.LayerNormalization(epsilon=1e-6)(add_attention)

  attention2 = MultiHeadAttention(
      d_model, num_heads, name="attention_2")(inputs={
          'query': attention1,
          'key': enc_outputs,
          'value': enc_outputs,
          'mask': padding_mask
      })
  attention2 = tf.keras.layers.Dropout(rate=dropout)(attention2)
  add_attention = tf.keras.layers.add([attention2,attention1])
  attention2 = tf.keras.layers.LayerNormalization(epsilon=1e-6)(add_attention)

  outputs = tf.keras.layers.Dense(units=units, activation='relu')(attention2)
  outputs = tf.keras.layers.Dense(units=d_model)(outputs)
  outputs = tf.keras.layers.Dropout(rate=dropout)(outputs)
  add_attention = tf.keras.layers.add([outputs,attention2])
  outputs = tf.keras.layers.LayerNormalization(epsilon=1e-6)(add_attention)

  return tf.keras.Model(
      inputs=[inputs, enc_outputs, look_ahead_mask, padding_mask],
      outputs=outputs,
      name=name)


def decoder(vocab_size,
            num_layers,
            units,
            d_model,
            num_heads,
            dropout,
            name='decoder'):
  inputs = tf.keras.Input(shape=(None,), name='inputs')
  enc_outputs = tf.keras.Input(shape=(None, d_model), name='encoder_outputs')
  look_ahead_mask = tf.keras.Input(
      shape=(1, None, None), name='look_ahead_mask')
  padding_mask = tf.keras.Input(shape=(1, 1, None), name='padding_mask')
  
  embeddings = tf.keras.layers.Embedding(vocab_size, d_model)(inputs)
  embeddings *= tf.keras.layers.Lambda(lambda d_model: tf.math.sqrt(tf.cast(d_model, tf.float32)))(d_model)
  embeddings = PositionalEncoding(vocab_size, d_model)(embeddings)

  outputs = tf.keras.layers.Dropout(rate=dropout)(embeddings)

  for i in range(num_layers):
    outputs = decoder_layer(
        units=units,
        d_model=d_model,
        num_heads=num_heads,
        dropout=dropout,
        name='decoder_layer_{}'.format(i),
    )(inputs=[outputs, enc_outputs, look_ahead_mask, padding_mask])

  return tf.keras.Model(
      inputs=[inputs, enc_outputs, look_ahead_mask, padding_mask],
      outputs=outputs,
      name=name)



def transformer(vocab_size,
                num_layers,
                units,
                d_model,
                num_heads,
                dropout,
                name="transformer"):
  inputs = tf.keras.Input(shape=(None,), name="inputs")
  dec_inputs = tf.keras.Input(shape=(None,), name="dec_inputs")

  enc_padding_mask = tf.keras.layers.Lambda(
      create_padding_mask, output_shape=(1, 1, None),
      name='enc_padding_mask')(inputs)
  # mask the future tokens for decoder inputs at the 1st attention block
  look_ahead_mask = tf.keras.layers.Lambda(
      create_look_ahead_mask,
      output_shape=(1, None, None),
      name='look_ahead_mask')(dec_inputs)
  # mask the encoder outputs for the 2nd attention block
  dec_padding_mask = tf.keras.layers.Lambda(
      create_padding_mask, output_shape=(1, 1, None),
      name='dec_padding_mask')(inputs)

  enc_outputs = encoder(
      vocab_size=vocab_size,
      num_layers=num_layers,
      units=units,
      d_model=d_model,
      num_heads=num_heads,
      dropout=dropout,
  )(inputs=[inputs, enc_padding_mask])

  dec_outputs = decoder(
      vocab_size=vocab_size,
      num_layers=num_layers,
      units=units,
      d_model=d_model,
      num_heads=num_heads,
      dropout=dropout,
  )(inputs=[dec_inputs, enc_outputs, look_ahead_mask, dec_padding_mask])

  outputs = tf.keras.layers.Dense(units=vocab_size, name="outputs")(dec_outputs)

  return tf.keras.Model(inputs=[inputs, dec_inputs], outputs=outputs, name=name)















def loss_function(y_true, y_pred):
  y_true = tf.reshape(y_true, shape=(-1, MAX_LENGTH - 1))
  
  loss = tf.keras.losses.SparseCategoricalCrossentropy(
      from_logits=True, reduction='none')(y_true, y_pred)

  mask = tf.cast(tf.not_equal(y_true, 0), tf.float32)
  loss = tf.multiply(loss, mask)

  return tf.reduce_mean(loss)

class CustomSchedule(tf.keras.optimizers.schedules.LearningRateSchedule):

  def __init__(self, d_model, warmup_steps=4000):
    super(CustomSchedule, self).__init__()
    
    self.d_model = tf.constant(d_model,dtype=tf.float32)
    self.warmup_steps = warmup_steps
    
  def get_config(self):
        return {"d_model": self.d_model,"warmup_steps":self.warmup_steps}
    
  def __call__(self, step):
    arg1 = tf.math.rsqrt(step)
    arg2 = step * (self.warmup_steps**-1.5)

    return tf.math.multiply(tf.math.rsqrt(self.d_model), tf.math.minimum(arg1, arg2))

learning_rate = CustomSchedule(D_MODEL)

tf.keras.backend.clear_session()
optimizer = tf.keras.optimizers.Adam(learning_rate,beta_1=0.9, beta_2=0.98, epsilon=1e-9)


def accuracy(y_true, y_pred):
  # ensure labels have shape (batch_size, MAX_LENGTH - 1)
  y_true = tf.reshape(y_true, shape=(-1, MAX_LENGTH - 1))
  return tf.keras.metrics.sparse_categorical_accuracy(y_true, y_pred)


def evaluate(sentence):
  sentence = preprocess_sentence(sentence)

  sentence = tf.expand_dims(
      START_TOKEN + tokenizer.encode(sentence) + END_TOKEN, axis=0)

  output = tf.expand_dims(START_TOKEN, 0)

  for i in range(MAX_LENGTH):
    predictions = model(inputs=[sentence, output], training=False)

    # select the last word from the seq_len dimension
    predictions = predictions[:, -1:, :]
    predicted_id = tf.cast(tf.argmax(predictions, axis=-1), tf.int32)

    # return the result if the predicted_id is equal to the end token
    if tf.equal(predicted_id, END_TOKEN[0]):
      break

    # concatenated the predicted_id to the output which is given to the decoder
    # as its input.
    output = tf.concat([output, predicted_id], axis=-1)

  return tf.squeeze(output, axis=0)


def predict(sentence):
  prediction = evaluate(sentence)

  predicted_sentence = tokenizer.decode(
      [i for i in prediction if i < tokenizer.vocab_size])

  print('Input: {}'.format(sentence))
  print('Output: {}'.format(predicted_sentence))

  return predicted_sentence

# initialize and compile model within strategy scope
filepath = os.path.dirname('./Model/')

model = transformer(vocab_size=VOCAB_SIZE,num_layers=NUM_LAYERS,units=UNITS,d_model=D_MODEL,num_heads=NUM_HEADS,dropout=DROPOUT)

model.compile(optimizer=optimizer, loss=loss_function, metrics=[accuracy])

model.fit(dataset, epochs=1)


tf.keras.models.save_model(model,'botmodel.h5',filepath)

  #model.load_weights('my_checkpoint')
  #print('loaded')
  #loss, acc = model.evaluate(dataset, verbose=2)
  #print("Restored model, accuracy: {:5.2f}%".format(100 * acc))


while True:
    q = input('ask :')
    output = predict(q)
