### ISSUE TITLE
Missing Op DenseToDenseSetOperation in contrib makefile static build

### ISSUE THREAD

**Issue by samhodge** [tensorflow/tensorflow#28942]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux el6 and MacOS 10.13
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: na
- TensorFlow installed from (source or binary): source
- TensorFlow version: v1.13.1
- Python version: na
- Installed using virtualenv? pip?  na
- Bazel version (if compiling from source): 19.1
- GCC/Compiler version (if compiling from source): clang Xcode 9.4 and gcc 4.8.5
- CUDA/cuDNN version: na yet
- GPU model and memory: na yet

**Describe the problem**
With one of models derived from Materport RCNN

I get the following error during inference in C++ which doesn’t happen with dynamic linking to the bazel targets libtensorflow_cc.so and libtensorflow_framework.so

ERROR: Op type not registered 'DenseToDenseSetOperation' in binary running on creative2. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) tf.contrib.resampler should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

Creative2 is the clients machine name

Having a quick GitHub search it seems this op is a thing

https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/core/ops/set_ops.cc

So given that it is there in core I don’t know what to do to make sure it is initialised it is in the dynamic version of the same software

Sam
**Provide the exact sequence of commands / steps that you executed before running into the problem**

Build Tensorflow makefile contrib to build libtensorflow_core.a nsync.a and libprotobuf.a

Link load a model with the above mentioned Op

This doesn’t happen with libtensorflow_framework.so and libtensorflow_cc.so and identical inference code and model.

**Any other info / logs**

**Comment by samhodge** [comment]
I noticed this in the docs

The most common cause of breakages are files that have been added to the Bazel build scripts, but that the makefile isn't aware of. Typical symptoms of this include linker errors mentioning missing symbols or protobuf headers that aren't found. To address these problems, take a look at the *.txt files in tensorflow/contrib/makefile. If you have a new operator, you may need to add it to tf_op_files.txt, or for a new proto to tf_proto_files.txt.

I will check this and see if it resolves the issue.

**Comment by samhodge** [comment]
booya!

https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/contrib/makefile/tf_op_files.txt

doesnt contain 
tensorflow/core/ops/set_ops.cc

Problem solved by @samhodge 

Sorry for the traffic.

**Comment by ileniTudor** [comment]
Dear @samhodge ,
I have the same issue with Missing Op DenseToDenseSetOperation when loading a network started from matterport MaskRCNN. I followed your response:

> booya!
> 
> https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/contrib/makefile/tf_op_files.txt
> 
> doesnt contain
> tensorflow/core/ops/set_ops.cc
> 
> Problem solved by @samhodge
> 
> Sorry for the traffic.

but the error is still there. More specifically, I just added the file tensorflow/core/set_ops.cc at the end  tf_op_files.txt and recompiled using basel, by running build_all_ios.sh . Am I missing something?
Thank you!
