### ISSUE TITLE
build_pip_package fails with locally installed python3: script unsets LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by mhex** [tensorflow/tensorflow#2902]
build_pip_package fails here with

`ERROR: /path/to/src/tensorflow/tensorflow/contrib/session_bundle/example/BUILD:38:1: Executing genrule //tensorflow/contrib/session_bundle/example:half_plus_two failed: bash failed: error executing command`

caused by

`error while loading shared libraries: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory`

executing

`(cd path/to/execroot/tensorflow && \
  exec env - \
    PATH=somepath \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; rm -rf /tmp/half_plus_two; path_to/python3 bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two`

it looks like

`exec env -`

unsets LD_LIBRARY_PATH

and therefore python3 cannot find its libraries anymore

Installation of tensorflow 0.8 works

**Comment by martinwicke** [comment]
What version is this about? r0.9? master? If master, at which commit?

**Comment by martinwicke** [comment]
@nfiedel, we disabled this is in 0.9, and I thought this was fixed in master, but seems that maybe it isn't.

**Comment by mhex** [comment]
yes 0.9 master, sorry forgot to mention it.

commit is

commit bdc43730c9e6037c608adb91fe55d6c1a82879a8
Date:   Tue Jun 14 06:19:48 2016 +0100

**Comment by mhex** [comment]
still happens with a fresh cloned branch i.e.

commit b327647368117db19b42c6fd75d0aa67a66dbf26
Merge: b8652a2 7e32f92
Date:   Thu Jun 16 20:53:14 2016 -0700

**Comment by martinwicke** [comment]
Which version of bazel are you using?

**Comment by mhex** [comment]
we first had the issue with 0.2.2b but it also happens with the newest version 0.3.0

**Comment by Phhere** [comment]
Also happens with 70de76e696c21da617fd2e6435cf7fedab220db8 and bazel 0.3.0 for me

**Comment by gunan** [comment]
I think this issue is now resolved. Our continuous tests on py3 seem to be all working.
Please reopen if I am mistaken.
