### ISSUE TITLE
add_update in cross-replica mode is broken (BatchNormalization layer impossible to use)

### ISSUE THREAD

**Issue by galeone** [tensorflow/tensorflow#29481]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Archlinux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-3374-g9eb67b17bf 2.0.0-dev20190605
- Python version: 3.6
- CUDA/cuDNN version: 10
- GPU model and memory: 1080 Ti

**Describe the current behavior**

I expect to do a forward pass with a model with a BachNormalization layer in training mode, when using the `tf.distribuite.MirroredStrategy` but I can't, because it reises the following exception:

> RuntimeError: `add_update` was called in a cross-replica context. This is not expected. If you require this feature, please file an issue.

Why it is not expected?

**Describe the expected behavior**

It should work.
The commit that introduced this behavior is: https://github.com/tensorflow/tensorflow/commit/316cd57883166e6a0b4c2d0eaacebddad7675b39#diff-8eb7e20502209f082d0cb15119a50413

**Code to reproduce the issue**

```python
import tensorflow as tf

model = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(10),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(1),
    ]
)

strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    out = model(tf.zeros((1, 10)), training=True)
```

**Comment by achandraa** [comment]
I was able to reproduce the issue on Colab with TensorFlow version 2.0.0-dev20190605.

**Comment by luvwinnie** [comment]
does this have been resolved yet?

**Comment by XuChunqiao** [comment]
I met same question recently，does this have been resolved yet？

**Comment by davesc** [comment]
Has this been resolved?  I can't use tf.distribute.MirroredStrategy with BatchNormalization in a training loop

**Comment by omalleyt12** [comment]
Hi @galeone, when using custom training loops with DistributionStrategy you have to use `experimental_run_v2`, please see: https://www.tensorflow.org/guide/distribute_strategy#using_tfdistributestrategy_with_custom_training_loops

**Comment by galeone** [comment]
HI @omalleyt12 , I'm my tests it still continues to fail, even when using `experimental_run_v2`.
If the system has more then one GPU (and thus the distribution strategy can really distribute the computation) the same exception is raised even if I change the code in this way:


```python
import tensorflow as tf

strategy = tf.distribute.MirroredStrategy()
with strategy.scope():


  model = tf.keras.Sequential([
        tf.keras.layers.Dense(10),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(1),
    ])

  def forward():
    return model(tf.zeros((1, 10)), training=True)
    
  print(strategy.experimental_run_v2(forward, args=()))
```

**Comment by vmarkovtsev** [comment]
I hit the same problem when I use batch normalization, too.

```
File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 659, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/normalization.py", line 556, in _fused_batch_norm
    self.add_update(mean_update)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1113, in add_update
    '`add_update` was called in a cross-replica context. This is not '
RuntimeError: `add_update` was called in a cross-replica context. This is not expected. If you require this feature, please file an issue
```

The problem happens while `Model.build()`-s so there is no way to try `experimental_run_v2` for me.

**Comment by omalleyt12** [comment]
@galeone @vmarkovtsev this should be fixed in the latest nightly, could you please check and confirm?

**Comment by omalleyt12** [comment]
@vmarkovtsev if it's not fixed for your use case, could you provide a simple repro?

**Comment by vmarkovtsev** [comment]
I confirm that this issue is fixed now. Thank you @omalleyt12 !

**Comment by omalleyt12** [comment]
Thanks!

**Comment by 3fen** [comment]
@omalleyt12 I met the same problem in 2.0.0rc.

**Comment by omalleyt12** [comment]
@3fen can you share a simple reproduction that is failing?

**Comment by 3fen** [comment]
@omalleyt12  it is similary with the main thread.

```python
model = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(10),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dense(1),
    ]
)

strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    out = model(tf.zeros((1, 10)), training=True)
    print(out)
```

Outupt:
> RuntimeError: `add_update` was called in a cross-replica context. This is not expected. If you require this feature, please file an issue.

**Comment by omalleyt12** [comment]
@3fen , when using custom training loops with DistributionStrategy you have to use experimental_run_v2, please see: https://www.tensorflow.org/guide/distribute_strategy#using_tfdistributestrategy_with_custom_training_loops

**Comment by 3fen** [comment]
@omalleyt12 Got it, thanks for the confirmation.

**Comment by DAEHEESHIN** [comment]
I hit the same problem when I use batch normalization, too.
i am using tensorflow 2.0 b1..
![image](https://user-images.githubusercontent.com/5635674/64348747-afec0900-d030-11e9-9e45-6b3c4609ed4e.png)

**Comment by vmarkovtsev** [comment]
@DAEHEESHIN v2.0 b1 is ancient, we are discussing the current nightly here.

**Comment by gdj0nes** [comment]
I'm having the same issue as @vmarkovtsev using tf2 and tf-nightly when I use `tf.function` and `get_concrete_function`:

`tf.function(train_model.__call__, autograph=False).get_concrete_function(
                tf.TensorSpec([batch_size_per_replica, *flags_obj.image_dimension], tf.float32),
                ...
           )`

**Comment by omalleyt12** [comment]
@gdj0nes Could you share a larger code snippet that repros this?

**Comment by gdj0nes** [comment]
@omalleyt12 i'm working on making something I can share, just wanted to make sure there wasn't already a clear fix. It seems like it's an issue with setting the `training` parameter.

**Comment by gdj0nes** [comment]
@omalleyt12, here is an example snippet using tf-nightly:

```python
import tensorflow as tf
from tensorflow.keras import layers

class Model(tf.Module):

    def __init__(self):
        super().__init__()

        with self.name_scope:
            self.layers = [
                layers.Conv2D(10, (3, 3)),
                layers.BatchNormalization()
            ]

    def no_param_call(self, input):
        x = input
        for layer in self.layers:
            x = layer(x)

        return x


    def param_call(self, input):
        x = input
        for layer in self.layers:
            x = layer(x, training=True)

        return x


def app():
    strategy = tf.distribute.MirroredStrategy()
    image_dimension = []
    with strategy.scope():
        model = Model()
        no_param_forward_fn = tf.function(model.no_param_call, autograph=False).get_concrete_function(
                tf.TensorSpec([1, 64, 64, 3], tf.float32)
        )
        print('no param call succeeded')
        param_forward_fn = tf.function(model.param_call, autograph=False).get_concrete_function(
            tf.TensorSpec([1, 64, 64, 3], tf.float32)
        )
        print('param call succeeded')


if __name__ == '__main__':
    app()
```

Output:

```2019-10-28 13:20:34.214602: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-28 13:20:34.225201: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fbc6e390880 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2019-10-28 13:20:34.225217: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
no param call succeeded
Traceback (most recent call last):
  File "/Users/{{omitted}}/scratches/scratch_62.py", line 48, in <module>
    app()
  File "/Users/{{omitted}}/scratches/scratch_62.py", line 42, in app
    tf.TensorSpec([1, 64, 64, 3], tf.float32)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 902, in get_concrete_function
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2365, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2673, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2563, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 958, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/gareth/Library/Preferences/PyCharm2019.3/scratches/scratch_62.py", line 27, in param_call
    x = layer(x, training=True)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/keras/layers/normalization.py", line 695, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/keras/layers/normalization.py", line 592, in _fused_batch_norm
    self.add_update(mean_update)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/{{omitted}}lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1208, in add_update
    '`add_update` was called in a cross-replica context. This is not '
RuntimeError: `add_update` was called in a cross-replica context. This is not expected. If you require this feature, please file an issue.```

**Comment by vmarkovtsev** [comment]
Indeed, this issue has returned.

**Comment by vmarkovtsev** [comment]
I find this issue to be very tricky.

The core of the problem comes from creating the batchnorm layer with `training=True` under the strategy scope. If you look at the code, it checks whether `training` is `True` and indeed calls `add_update`. This comes out only when you try to subclass a Keras model.

I have found a workaround though: wrap your subclassed model in another one:

```python
my_model = Model(...)
tf.keras.Model(inputs=[tf.keras.layers.Input(shape=...)], outputs=my_model.call(training=True))
```

That wrapping gives an additional bonus of being able to `build()` and properly `summary()` the model.

**Comment by galeone** [comment]
I guess this issue should be re-opened, I'm facing again the same issue

**Comment by netw0rkf10w** [comment]
Same issue for me!

It only occurs if I use `tf.keras.callbacks.ModelCheckpoint`, no problem otherwise...

**Comment by guptapriya** [comment]
@omalleyt12 - are you looking into this?
@rchao could this one of the issues you've fixed recently with checkpointing?

**Comment by netw0rkf10w** [comment]
@guptapriya Thanks for reopening this.
For your information, this issue does not seems to occur for the `.h5` format, only the TF format is is affected, as pointed out in [my recent issue](https://github.com/tensorflow/tensorflow/issues/34127) (which is a duplicate of this one, sorry):

> Note: no error if we use `.h5` instead of TF checkpoint format. However, just a few hours ago, @karmel and @jvishnuvardhan [recommended me to use TF format](https://github.com/tensorflow/tensorflow/issues/34016) (because `.h5` can cause issues, okay fine). So, which one should I use finally? None is working? I am lost...

**Comment by omalleyt12** [comment]
@netw0rkf10w @vmarkovtsev  @galeone What tf version are you using? This should be fixed in the nightly

**Comment by rchao** [comment]
Recently we have submitted a few fixes related to using batch norm layer with tf.distribute strategies. If you could try with the nightly and let us know if it's fixed it'd be great.

**Comment by hassanhub** [comment]
I've updated my tf to tf-nightly (2.1.0-dev20200104) and this problem still exists.
Any idea?

**Comment by saikumarchalla** [comment]
@galeone @vmarkovtsev  @netw0rkf10w  Issue seems to be fixed in latest TF version. Please confirm and close the issue if it is resolved for you. Thanks!

**Comment by saikumarchalla** [comment]
Any updates regarding this issue? Thanks!

**Comment by saikumarchalla** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by taki0112** [comment]
In TF 2.1.0 the issue is not fixed... anybody help me ?
Is this issue fixed in TF 2.2 ?

**Comment by netw0rkf10w** [comment]
@taki0112 I don't understand. Why didn't you simply upgrade to TF 2.2 and see if it works for you?
