### ISSUE TITLE
Bug in exception handling of tf.histogram_fixed_width_bins 

### ISSUE THREAD

**Issue by jvishnuvardhan** [tensorflow/tensorflow#29661]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.0.0-beta0
- Python version: python3 from colab
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
when value range for  `tf.histogram_fixed_width_bins ` is `[0.0, 0.0], it outputs an index outside `nbins`. See the code below.

```
nbins = 5
value_range = [.0, .0]
new_values = [-1.0, 0.0, 1.5, 2.0, 5.0, 15]
indices = tf.histogram_fixed_width_bins(new_values, value_range, nbins=5)
print(indices)

```
Output is 
```
tf.Tensor([          0 -2147483648           4           4           4           4], shape=(6,), dtype=int32)
```

**Describe the expected behavior**
It should show indices as [0,0,4,4,4,4] and throw a warning saying that the range needs to be updated

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
See above

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achandraa** [comment]
Tried on Colab with TF version 2.0-beta and was able to replicate the issue.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/60c13c6f2c1cc4948add81e210f150c1/2-1-template.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/cf4dab2373adf64de686a77e94cad76c/tf-nightly.ipynb) i.e. 2.2.0-dev20200327. Please find the attached gist. Thanks!

**Comment by ymodak** [comment]
This is fixed with tf-nightly version '2.2.0-dev20200402'. Thanks!
```python
tf.Tensor([0 4 4 4 4 4], shape=(6,), dtype=int32)
```

**Comment by jvishnuvardhan** [comment]
It is working as expected in GPU. But, the error still persists with CPU. 
[Here](https://colab.research.google.com/gist/jvishnuvardhan/858ba13ef8b77cf63355c84bd398e026/tf-nightly.ipynb) is the gist with GPU and [here](https://colab.research.google.com/gist/jvishnuvardhan/4b80e167f59162e373f0fc5591d9c14d/tf-nightly.ipynb) with CPU. Thanks!

**Comment by yongtang** [comment]
Added a PR #38899 for the fix. In comparison with `tf.histogram_fixed_width` which throws out InvalidArgument in case value_range is not monotonous increasing (implemented in C++ kernel), I think `tf.histogram_fixed_width_bins` needs to apply the same restriction, as was specified in its docstring.
