### ISSUE TITLE
Navigation of docs has just become very difficult

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#297]
The new docs pages have been changed so that the left navigation pane no longer has collapsable entries. This seems like a step back in many ways, as the API pages are virtually impossible to navigate now.

**Comment by victorv** [comment]
On Safari and Chrome on Yosemite 10.5.5 the navigation panel becomes un-scrollable after selecting from the main panel.

**Comment by cesarsalgado** [comment]
In my computer, there are some sections in the menu that are hidden at the bottom of the screen. The scrollbar reaches the end before these sections entries can be displayed on the side menu.

**Comment by martinwicke** [comment]
We have fixed the bug @cesarsalgado found, it should appear soon.

**Comment by cesarsalgado** [comment]
The problem persists as can be seen in this screenshot: https://goo.gl/photos/h1fEJ2KiE4yZrHA36

**Comment by martinwicke** [comment]
Should be fixed now.

**Comment by martinwicke** [comment]
@cesarsalgado's issue is fixed. The accordion is still not done.

**Comment by girving** [comment]
@martinwicke, @danmane: Is this still an issue?

**Comment by cesarsalgado** [comment]
I am still having the same problem: https://goo.gl/photos/RfPszQCKECafxocQA

I can't see the Image Recognition sub-items.

**Comment by fxsuper** [comment]
Also the API documentation still does not have the accordion. It's just a long list of entries that's very hard to navigate.

**Comment by martinwicke** [comment]
@cesarsalgado What browser are  you using and on what OS? This works for me.

**Comment by cesarsalgado** [comment]
Operating System: Ubuntu 14.04 LTS
The picture in my last comment was taken under Firefox 42.

Now I tested on chrome Version 47.0.2526.73 (64-bit) and now I can scroll all the way to the bottom but the scroll bar disappear in the bottom of the screen: https://goo.gl/photos/DbTTZhEMXfD8gVXR8

**Comment by cesarsalgado** [comment]
My screen resolution is: 1366x768 (16:9)

**Comment by martinwicke** [comment]
We're working on backend changes, this will eventually be resolved by that work. Hang tight.

**Comment by alextp** [comment]
@martinwicke is this still being worked on?

**Comment by martinwicke** [comment]
Yes. Will be addressed in docs infrastructure move. Can be closed but I
left it open so signal we are aware that it sucks.

**Comment by martinwicke** [comment]
Reassigning for the honor of closing.

**Comment by gunan** [comment]
With the website move, this should be resolved.
@wollfg, I think we are now ready to close this issue.

**Comment by wolffg** [comment]
Docs navigation has accordions and twistdowns now for easier navigation.  I'm going to close this.
