### ISSUE TITLE
Many context switches / Many threads even if threading is limited

### ISSUE THREAD

**Issue by fhausmann** [tensorflow/tensorflow#29968]
**System information**
- Have I written custom code: No (https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/quickstart/beginner.ipynb)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux OpenSuse Leap 15.0
- TensorFlow installed from (source or binary): pip package tensorflow==2.0.0-beta1
- TensorFlow version (use command below): v2.0.0-beta0-16-g1d91213
- Python version: 3.7.3 
- GPU model and memory: CPU only

**Describe the current behavior**
If you limit the number of threads with tf.set_inter_op_parallelism_threads(NUM_THREADS) and tf.set_intra_op_parallelism_threads(NUM_THREADS) tensorflow creates a threadpool with more threads than NUM_THREADS and runs maximal NUM_THREADS causing high amount of context switches, which is delaying execution.

**Describe the expected behavior**
Create maximal NUM_THREADS and limit context switches.

**Code to reproduce the issue**
```python
from __future__ import absolute_import, division, print_function, unicode_literals
!pip install -q tensorflow==2.0.0-beta1
import tensorflow as tf
NUM_THREADS=2
tf.config.threading.set_inter_op_parallelism_threads(NUM_THREADS)
tf.config.threading.set_intra_op_parallelism_threads(NUM_THREADS)
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=100)
```

**Comment by gadagashwini** [comment]
@fhausmann I tried reproducing the issue above code but I receive the following error
`AttributeError: module 'tensorflow' has no attribute 'set_inter_op_parallelism_threads'`
Can you help us to reproduce the issue. Thanks!

**Comment by fhausmann** [comment]
Sorry, the two lines were incorrect. They should be:
tf.config.threading.set_inter_op_parallelism_threads(NUM_THREADS)
tf.config.threading.set_intra_op_parallelism_threads(NUM_THREADS)
I adjusted the example above.

**Comment by gadagashwini** [comment]
I am able to reproduce the issue with Tf 2.0.0.beta1 on colab.

**Comment by dynamicwebpaige** [comment]
Adding @tfboyd - should the number of threads be set to 1?

**Comment by tfboyd** [comment]
With TF 2.0 and GPU we have not needed to tough this.  Couple items.

1. Based on how the issue is written I am not sure of the problem other than guessing.  I do not see any timings for the delay of the execution or how we would verify the problem is fixed or exists.  Or something showing there are more 

2. Maybe this config is not being respected. tf.config "global" is new.  With the TF 1.0 method of passing config to the session, I would have tests to black box prove the values are set based on the resulting perf changes.

Adding penpornk from the CPU group.
@penpornk

**Comment by penpornk** [comment]
@fhausmann Could you please clarify how you observed the number of threads actually being used and that a lot of context switches happened? How many threads did you see?

TensorFlow has two thread pools: inter-op (how many ops can be run concurrently) and intra-op (a thread pool shared between all concurrent ops to execute tasks). The expected number of threads is #inter-threads + #intra-threads. 
* If you saw 4 threads instead of 2: This is expected and you should adjust NUM_THREADS.
* If you saw many more than 4 threads: The settings probably somehow didn't get through and I'll try to investigate.

**Comment by fhausmann** [comment]
@penpornk I saw 4 threads running like expected (htop) but both ps and pstree show me 20 threads, if I run the code above.
cat /proc/PID/status shows me then (at approx. epoch 7) the following:
Threads:	21
voluntary_ctxt_switches:	10277
nonvoluntary_ctxt_switches:	35

**Comment by penpornk** [comment]
@fhausmann Thank you! I was able to reproduce the issue. Will see what's going on.

**Comment by penpornk** [comment]
FYI @martijnvels

**Comment by jvishnuvardhan** [comment]
@fhausmann Is this still an issue? Can you check with `TF2.0` and let us know whether the issue persists with latest TF version. I tried both `!pip install tf-nightly` and `!pip install tensorflow==2.0.0`. 

[Here is the gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/f38f8b7f3c7adbc171814cb863b0de17/untitled539.ipynb) with `!pip install tf-nightly`. Thanks!

**Comment by fhausmann** [comment]
The issue is not resolved using both,  latest  TF2.0 and nightly. 
I still get 16-21 threads and > 38000 voluntary_ctxt_switches (at epoch 20)
I used 
```
import os 
pid = os.getpid()
with open("/proc/{}/status".format(pid)) as file:
    print(file.read())
```
after the execution of model.fit to look into these values.

**Comment by yuviabhi** [comment]
Issue still persists in **Tensorflow 2.0.0**
OS: Ubuntu 18.04

My Code : 
```
import tensorflow as tf
print(tf.__version__)
NUM_THREADS=2
tf.config.threading.set_inter_op_parallelism_threads(NUM_THREADS)
tf.config.threading.set_intra_op_parallelism_threads(NUM_THREADS)
```

![Screenshot from 2020-01-09 15-47-02](https://user-images.githubusercontent.com/14270453/72059195-8ea96b00-32f7-11ea-8070-aa7fb13251e6.png)

**Comment by Leslie-Fang** [comment]
Hi @penpornk 
I think it works....
I have tried this version(TF2.0): 99cb9fd68d1b8c6f0857c0775c366234537bacf5  
With a combination of OMP_NUM_THREADS, intra_threads and inter_threads
For example:
```
export OMP_NUM_THREADS=2
tf.config.threading.set_intra_op_parallelism_threads(2)
tf.config.threading.set_inter_op_parallelism_threads(1)
```
From the view of HTOP, I may see **more than 2 threads existing**, but actually **only 2 threads are running**. I bet the others threads are sleeping.
Although, _i don't know why there are more than 2 threads...._ May need your help to explain it....

BTW: From my perspective,  I think OMP_NUM_THREADS and intra_op_parallelism_threads should be at the same code level, but make effective in different op(Native TF or MKL version). _Also please correct me, if I am wrong..._

**Comment by nilskk** [comment]
was this fixed in a tensorflow 2.1 or 2.2?

**Comment by fhausmann** [comment]
@nilskk As to my knowledge it was not fixed up to now (TF 2.2.0 v2.2.0-rc4-8-g2b96f3662b).

**Comment by jlherren** [comment]
It must have something to do with the way TF was compiled.

My pip-installed TF 2.2.0 behaves correctly and as expected: when I use `set_{inter,intra}_op_parallelism_threads(1)` then it will use one busy core and 100% CPU. When I use my custom-built TF 2.2.0 following the [official build instructions](https://www.tensorflow.org/install/source), then it will use 600% CPU with 6 busy threads (and some other non-busy threads) despite the parallelism settings. My machine is a hexa-core, so it seems like it is auto-detecting instead of using what I specified.

**Comment by fhausmann** [comment]
@jlherren 
Hmm, from my point ( I was always using the pip version) it was always running only the correct number of threads, but created a lot more (which were all suspended and this slows down performance due to many context switches).

So the Issue was never about incorrect number of running, but created threads. So I guess your issue is a different one, but may connected.

**Comment by PouriaParhami** [comment]
Hi @Leslie-Fang 
it works for me, tnx.

**Comment by cjw85** [comment]
I'm experiencing something similar while running inference on a previously trained model. I'm using `tensorflow` 2.2.0 installed from PyPI. Using:

```
export OMP_NUM_THREADS=2
tf.config.threading.set_intra_op_parallelism_threads(2)
tf.config.threading.set_inter_op_parallelism_threads(1)
```

has no effect and I still see very many threads being produced and high CPU usage. I eventualy found something that does have an effect however:

```
export TF_NUM_INTEROP_THREADS=2
export TF_NUM_INTRAOP_THREADS=1
```

I then see only at most 200% CPU use and the process starting very many fewer threads.

**Comment by nick-youngblut** [comment]
I've tried:

```
tf.config.threading.set_intra_op_parallelism_threads(2)
tf.config.threading.set_inter_op_parallelism_threads(2)
os.environ['TF_NUM_INTEROP_THREADS'] = '2'
os.environ['TF_NUM_INTRAOP_THREADS'] = '2'
```

on `tensorflow  2.3.0` (conda-forge) Ubuntu 18.04, and `model.fit()` is trying to use all 80 threads on the server. I'm just getting started in really learning TF, but I can't even use it, since it hogs all shared cpu resources on the server. Maybe this is a sign to learn pytorch instead of TF...

**Comment by martijnvels** [comment]
The TF_NUM_INTEROP_THREADS and TF_NUM_INTRAOP_THREADS must be set before
the program starts, or at least before any TF code is run as they are
evaluated once on the first threadpool creation.

**Comment by nick-youngblut** [comment]
>The TF_NUM_INTEROP_THREADS and TF_NUM_INTRAOP_THREADS must be set before
the program starts, or at least before any TF code is run as they are
evaluated once on the first threadpool creation.

I did. My reprex is:

```
import os
import tensorflow as tf

tf.config.threading.set_intra_op_parallelism_threads(2)
tf.config.threading.set_inter_op_parallelism_threads(2)

os.environ['TF_NUM_INTEROP_THREADS'] = '2'
os.environ['TF_NUM_INTRAOP_THREADS'] = '2'

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
```

At least `torch.set_num_threads(1)` works correctly for me.

**Comment by jaidayal** [comment]
I too am running into this issue as of today, with tensorflow 2.2.0 and beyond. (tried 2.3 and 2.4)

**Comment by dnaveenr** [comment]
The following works for me with TensorFlow 2.3.1 :
The aim was to limit the CPU usage to a maximum of 1 CPU.
`
import os
import tensorflow as tf

num_threads = 1
# Maximum number of threads to use for OpenMP parallel regions.
os.environ["OMP_NUM_THREADS"] = "1"
# Without setting below 2 environment variables, it didn't work for me. Thanks to @cjw85 
os.environ["TF_NUM_INTRAOP_THREADS"] = "1"
os.environ["TF_NUM_INTEROP_THREADS"] = "1"

tf.config.threading.set_inter_op_parallelism_threads(
    num_threads
)
tf.config.threading.set_intra_op_parallelism_threads(
    num_threads
)
tf.config.set_soft_device_placement(True)
`
After using the above, the CPU usage was limited to 1 CPU, so this was tested with my GPU disabled using 
`os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
`

**Comment by fhausmann** [comment]
With the gist above (tf-nightly) I got: 
```
Threads:	20
voluntary_ctxt_switches:	38101
nonvoluntary_ctxt_switches:	29200
```
And limiting by using the enviroment variables:
 ```python
# Maximum number of threads to use for OpenMP parallel regions.
os.environ["OMP_NUM_THREADS"] = "1"
# Without setting below 2 environment variables, it didn't work for me. Thanks to @cjw85 
os.environ["TF_NUM_INTRAOP_THREADS"] = "1"
os.environ["TF_NUM_INTEROP_THREADS"] = "1"
```
I got:
```
Threads:	19
voluntary_ctxt_switches:	31513
nonvoluntary_ctxt_switches:	34667
```

So not really an improvement. I didn't checked the number of running threads, but this was always fine for me. 
But I cannot see any big improvement in the total number of threads.

I think several things get confused in this issue and I want to clarify this a bit:
- Tensorflow sometimes don't honor the setting and **runs** more threads than specified. This never happened to me.
- Tensorflow **creates** more threads than specified runs the correct number, which I think is probably not an issue for most people but can be annoying if a cluster spends a lot of CPU-time in context-switches.

**Comment by sushreebarsa** [comment]
Was able to reproduce this issue in TF 2.6.0-dev20210526,Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9dc8dcd65abf53afcef8a97d355b534e/untitled10.ipynb) ....Thanks !

**Comment by sachinprasadhs** [comment]
Can you cross check in the Linux system level information to check how many threads actually being utilized by passing your PID in below comment `ps -o nlwp <pid>` or `ps -o thcount <pid>`.

**Comment by fhausmann** [comment]
With the following settings:
```python
num_threads = 1

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["TF_NUM_INTRAOP_THREADS"] = "1"
os.environ["TF_NUM_INTEROP_THREADS"] = "1"

tf.config.threading.set_inter_op_parallelism_threads(num_threads)
tf.config.threading.set_intra_op_parallelism_threads(num_threads)

```
I still get the same results:

tensorflow==2.5.0
```
$ ps -o nlwp 191200
NLWP
  19
$ ps -o thcount 191200 
THCNT
   19
```
and after running:
```
$ cat /proc/191200/status
Threads:	16
voluntary_ctxt_switches:	22228
nonvoluntary_ctxt_switches:	2335

```


tf-nightly==2.6.0.dev20210623
```
$ ps -o nlwp 194592
NLWP
  23
$ ps -o thcount 194592
THCNT
   23
```
and after running:
```
$ cat /proc/194592/status
Threads:	16
voluntary_ctxt_switches:	22471
nonvoluntary_ctxt_switches:	2661
```

**Comment by kumariko** [comment]
Was able to reproduce this issue in TF 2.6 ,Please find the gist [**`here`**](https://colab.research.google.com/gist/kumariko/a705e35660b4008f31679f246e6e5267/untitled10.ipynb#scrollTo=Bf5MdeQ2IluD) . Thanks !

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by mihaimaruseac** [comment]
The issue was still active at least last year. It is unlikely it got resolved since then

**Comment by fhausmann** [comment]
Checked again with the TF nightly  (2.18.0-dev20240710)  the the gist from here:

> Was able to reproduce this issue in TF Nightly 2.12.0.dev20221215 ,Please find the gist [**`here`**](https://colab.research.google.com/gist/pjpratik/c95f59f11525254623b590a9b1198342/29968.ipynb) . Thanks !

After epoch 7 I got: 
```
Threads:	31
voluntary_ctxt_switches:	16479
nonvoluntary_ctxt_switches:	13637
```

So unfortunately it is not resolved yet.

**Comment by Venkat6871** [comment]
Hi @fhausmann ,
Thank you so much for filing this bug request! We truly appreciate your support. At the moment, this request is not prioritized and mark it for community contributions. If you would like to contribute on a fix, please feel free to fork the repository and submit a pull request in accordance with the TensorFlow [CONTRIBUTION GUIDELINES](https://www.tensorflow.org/community/contribute/code) and link this issue in your PR to ensure the maintainers can easily review and collaborate.To avoid duplicate work, please leave a comment here if you decide to take it on!
Thank you again for your interest and we look forward to seeing your contributions!

**Comment by Venkat6871** [comment]
Hi @fhausmann ,
We are closing this issue due to inactivity. If this is still relevant and you would like to work on it, please feel free to reopen the issue or submit a pull request referencing it.

Thank you for your understanding.
