### ISSUE TITLE
"ambiguous call to overloaded function" error during compiling tensorflow on Windows 

### ISSUE THREAD

**Issue by khazali** [tensorflow/tensorflow#30687]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version: 1.14.0
- Python version: 3.7
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.25.2
- GCC/Compiler version (if compiling from source): Visual Studio 2017/2019
- CUDA/cuDNN version:10.0/7 and 10.1/7
- GPU model and memory: Geforce GTX 1080, 8GB

**Describe the problem**
I get the following error during the compile:

.\tensorflow/stream_executor/kernel.h(534): error C2668: 'stream_executor::TypedKernel<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>::PackOneParam': ambiguous call to overloaded function
.\tensorflow/stream_executor/kernel.h(557): note: could be 'void stream_executor::TypedKernel<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>::PackOneParam<T>(stream_executor::KernelArgsArray<4> *,const T &,void *) const'
with
[
T=stream_executor::DeviceMemory<tensorflow::uint8>
]
.\tensorflow/stream_executor/kernel.h(532): note: or 'void stream_executor::TypedKernel<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>::PackOneParam<T,>(stream_executor::KernelArgsArray<4> *,const T &) const'
with
[
T=stream_executor::DeviceMemory<tensorflow::uint8>
]
.\tensorflow/stream_executor/kernel.h(534): note: while trying to match the argument list '(stream_executor::KernelArgsArray<4> *, const T)'
with
[
T=stream_executor::DeviceMemory<tensorflow::uint8>
]
.\tensorflow/stream_executor/kernel.h(528): note: see reference to function template instantiation 'void stream_executor::TypedKernel<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>::PackOneParam<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>(stream_executor::KernelArgsArray<4> *,const T &,const tensorflow::uint8 &,const tensorflow::uint64 &,const stream_executor::DeviceMemory<tensorflow::uint64> &) const' being compiled
with
[
T=stream_executor::DeviceMemory<tensorflow::uint8>
]
.\tensorflow/stream_executor/kernel.h(528): note: see reference to function template instantiation 'void stream_executor::TypedKernel<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>::PackOneParam<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>(stream_executor::KernelArgsArray<4> *,const T &,const tensorflow::uint8 &,const tensorflow::uint64 &,const stream_executor::DeviceMemory<tensorflow::uint64> &) const' being compiled
with
[
T=stream_executor::DeviceMemory<tensorflow::uint8>
]
.\tensorflow/stream_executor/kernel.h(527): note: while compiling class template member function 'void stream_executor::TypedKernel<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>::PackParams(stream_executor::KernelArgsArray<4> *,stream_executor::DeviceMemory<tensorflow::uint8> &,tensorflow::uint8 &,tensorflow::uint64 &,stream_executor::DeviceMemory<tensorflow::uint64> &) const'
.\tensorflow/stream_executor/stream_executor_pimpl.h(882): note: see reference to function template instantiation 'void stream_executor::TypedKernel<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>::PackParams(stream_executor::KernelArgsArray<4> *,stream_executor::DeviceMemory<tensorflow::uint8> &,tensorflow::uint8 &,tensorflow::uint64 &,stream_executor::DeviceMemory<tensorflow::uint64> &) const' being compiled
tensorflow/stream_executor/cuda/redzone_allocator.cc(269): note: see reference to class template instantiation 'stream_executor::TypedKernel<stream_executor::DeviceMemory<tensorflow::uint8>,tensorflow::uint8,tensorflow::uint64,stream_executor::DeviceMemory<tensorflow::uint64>>' being compiled

The error is found at kernel.h file: (https://github.com/tensorflow/tensorflow/blob/release_1.14.0/tensorflow/stream_executor/kernel.h

**Provide the exact sequence of commands / steps that you executed before running into the problem**
I did everything as explained in the tensorflow website.

**Any other info / logs**
I get the error whether I am compiling with CUDA 10.0 or 10.1, vs 2017 or vs 2019.

**Comment by anush-o** [comment]
@khazali ,
I could not open the link https://github.com/tensorflow/tensorflow/blob/release_1.14.0/tensorflow/stream_executor/kernel.
Can you please provide the working link. Thanks

**Comment by khazali** [comment]
@anush-o
I have to appologize, the link has been edited to:

https://github.com/tensorflow/tensorflow/blob/release_1.14.0/tensorflow/stream_executor/kernel.h

**Comment by gunan** [comment]
@chsigg to confirm, but I think this should be fixed at head?

**Comment by chsigg** [comment]
Yes, this has been fixed. Please let us know if you still see this issue.

**Comment by khazali** [comment]
Thanks for your considerations. However, I have compiled the master branch (since there was no change in release_1.14.0), and the error still persists. The compiler log can be accessed here:
https://github.com/khazali/TensorflowOutput/blob/master/Out.txt

**Comment by gunan** [comment]
In our continuous tests, for the last week I have never seen the issue recur.
https://source.cloud.google.com/results/invocations/c96c6321-edc4-4f0d-bbf3-c0da191c407f/log
The above is the most recent build log for TF at head.

Is it possible your client was not synced to head?

**Comment by khazali** [comment]
I have tested the updated master branch again, and the compiler output was the same.

**Comment by gunan** [comment]
We have a potential fix we are hoping it may address this.
We are hoping to push it tomorrow (Mountain View Daytime).

You may be able to try it out to see if that works.

**Comment by khazali** [comment]
Thanks a lot.

**Comment by gunan** [comment]
The potential fix is now merged.

**Comment by khazali** [comment]
It was compiled successfully with VS2019. Thank you.
