### ISSUE TITLE
AttributeError: '_TfDeviceCaptureOp' object has no attribute '_set_device_from_string'

### ISSUE THREAD

**Issue by pjspillai** [tensorflow/tensorflow#30728]
Tensorflow Version: 1.14.0
python3.6
Num of GPU's : 3

--- Sample keras code to reproduce this error ---
```
import tensorflow as tf
from keras.applications import Xception
from keras.utils import multi_gpu_model
import numpy as np

num_samples = 1000
height = 224
width = 224
num_classes = 1000

model = Xception(weights=None,
                     input_shape=(height, width, 3),
                     classes=num_classes)

gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
parallel_model = multi_gpu_model(model, gpus=2)
```

Error Message:
```

device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
device_string:  /device:GPU:0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/multi_gpu_utils.py", line 227, in multi_gpu_model
    outputs = model(inputs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 564, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 721, in run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/normalization.py", line 185, in call
    epsilon=self.epsilon)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 1858, in normalize_batch_in_training
    if not _has_nchw_support() and list(reduction_axes) == [0, 2, 3]:
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 291, in _has_nchw_support
    explicitly_on_cpu = _is_current_explicit_device('CPU')
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 266, in _is_current_explicit_device
    device = _get_current_tf_device()
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 247, in _get_current_tf_device
    g._apply_device_functions(op)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 4581, in _apply_device_functions
    op._set_device_from_string(device_string)
AttributeError: '_TfDeviceCaptureOp' object has no attribute '_set_device_from_string'
(arg: 2) 

```

**Comment by pjspillai** [comment]
Solved, It's a bug in tensorflow 1.14.0
When I downgraded to 1.13.1, it's back to normal :-/

**Comment by Arstanley** [comment]
Same Problem Here

**Comment by dorinionescu** [comment]
Can not downgrade to tensorflow-gpu 1.13.1 - please give me the exact version that works
`sudo -H python3 -m pip install tensorflu-gpu==1.3.1
Collecting tensorflu-gpu==1.3.1
  Could not find a version that satisfies the requirement tensorflu-gpu==1.3.1 (from versions: )
No matching distribution found for tensorflu-gpu==1.3.1
`
I tried a lot of TF versions - nothing works
Thank you
Dorin

**Comment by YoavRamon** [comment]
Any news regarding that problem?

**Comment by aaroey** [comment]
Hi @robieta, seems you recently made changes to _TfDeviceCaptureOp, would you mind to take a look?
Thanks.

**Comment by max-lifetrack** [comment]
If it helps, I got the same error message with another traceback.

AttributeErrorTraceback (most recent call last)
<ipython-input-26-8f80d72756c9> in <module>()
----> 1 model = multi_gpu_model(model,gpus=2)

/usr/local/lib/python2.7/dist-packages/keras/utils/training_utils.pyc in multi_gpu_model(model, gpus)
    173                 # Apply model on slice
    174                 # (creating a model replica on the target device).
--> 175                 outputs = model(inputs)
    176                 if not isinstance(outputs, list):
    177                     outputs = [outputs]

/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.pyc in __call__(self, inputs, **kwargs)
    455             # Actually call the layer,
    456             # collecting output(s), mask(s), and shape(s).
--> 457             output = self.call(inputs, **kwargs)
    458             output_mask = self.compute_mask(inputs, previous_mask)
    459 

/usr/local/lib/python2.7/dist-packages/keras/engine/network.pyc in call(self, inputs, mask)
    562             return self._output_tensor_cache[cache_key]
    563         else:
--> 564             output_tensors, _, _ = self.run_internal_graph(inputs, masks)
    565             return output_tensors
    566 

/usr/local/lib/python2.7/dist-packages/keras/engine/network.pyc in run_internal_graph(self, inputs, masks)
    719                                     kwargs['mask'] = computed_mask
    720                             output_tensors = to_list(
--> 721                                 layer.call(computed_tensor, **kwargs))
    722                             output_masks = layer.compute_mask(computed_tensor,
    723                                                               computed_mask)

/usr/local/lib/python2.7/dist-packages/keras/layers/normalization.pyc in call(self, inputs, training)
    183         normed_training, mean, variance = K.normalize_batch_in_training(
    184             inputs, self.gamma, self.beta, reduction_axes,
--> 185             epsilon=self.epsilon)
    186 
    187         if K.backend() != 'cntk':

/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.pyc in normalize_batch_in_training(x, gamma, beta, reduction_axes, epsilon)
   1856     """
   1857     if ndim(x) == 4 and list(reduction_axes) in [[0, 1, 2], [0, 2, 3]]:
-> 1858         if not _has_nchw_support() and list(reduction_axes) == [0, 2, 3]:
   1859             return _broadcast_normalize_batch_in_training(x, gamma, beta,
   1860                                                           reduction_axes,

/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.pyc in _has_nchw_support()
    289         bool: if the current scope device placement would support nchw
    290     """
--> 291     explicitly_on_cpu = _is_current_explicit_device('CPU')
    292     gpus_available = len(_get_available_gpus()) > 0
    293     return (not explicitly_on_cpu and gpus_available)

/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.pyc in _is_current_explicit_device(device_type)
    264     if device_type not in ['CPU', 'GPU']:
    265         raise ValueError('`device_type` should be either "CPU" or "GPU".')
--> 266     device = _get_current_tf_device()
    267     return (device is not None and device.device_type == device_type.upper())
    268 

/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.pyc in _get_current_tf_device()
    245     g = tf.get_default_graph()
    246     op = _TfDeviceCaptureOp()
--> 247     g._apply_device_functions(op)
    248     return op.device
    249 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.pyc in _apply_device_functions(self, op)
   4579       # strings, since identity checks are faster than equality checks.
   4580       if device_string is not prior_device_string:
-> 4581         op._set_device_from_string(device_string)
   4582         prior_device_string = device_string
   4583     op._device_code_locations = self._snapshot_device_function_stack_metadata()

AttributeError: '_TfDeviceCaptureOp' object has no attribute '_set_device_from_string'

**Comment by omalleyt12** [comment]
As a workaround, can you try `tf.distribute.MirroredStrategy()`? This is the recommended way going forward for multi-gpu training

**Comment by kalyan369** [comment]
Any update on this issues. I am still facing the issue when using multi gpu..

**Comment by bmongia** [comment]
Any updates on this issue? This bug is preventing me from upgrading to tf1.14.

**Comment by pvalienteverde** [comment]
> I'm having the same issue, downgrading to 1.13.1 solved it for me, please fix.

The same

**Comment by ashkan-software** [comment]
Make sure when you downgrade, you downgrade other `tensorflow` packages that you have installed:
if python 2:
```
pip install tensorflow==1.13.1
pip install tensorflow-gpu==1.13.1
```
If python 3:
```
pip3 install tensorflow==1.13.1
pip3 install tensorflow-gpu==1.13.1
```

**Comment by karolbadowski** [comment]
Even shorter code to reproduce the issue:
`from tensorflow import device`
`    with device('/gpu:0' if use_GPU else '/cpu:0'): [any Keras code that compiles a model]`

**Comment by rbavery** [comment]
@tuanzhangCS I installed keras from the master branch that has the PR you linked but I still get this error:

```
Traceback (most recent call last):
  File "run_cropmask.py", line 287, in <module>
    mode="training", config=config, model_dir=args.logs
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/cropmask/mrcnn/model.py", line 2025, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/cropmask/mrcnn/model.py", line 2345, in build
    model = ParallelModel(model, config.GPU_COUNT)
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/parallel_model.py", line 33, in __init__
    merged_outputs = self.make_parallel(keras_model, gpu_count)
  File "/data/home/ryan/work/CropMask_RCNN/cropmask/mrcnn/parallel_model.py", line 79, in make_parallel
    outputs = inner_model(inputs)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/engine/network.py", line 564, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/engine/network.py", line 721, in run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/cropmask/mrcnn/model.py", line 71, in call
    return super(self.__class__, self).call(inputs, training=training)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/layers/normalization.py", line 185, in call
    epsilon=self.epsilon)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 1858, in normalize_batch_in_training
    if not _has_nchw_support() and list(reduction_axes) == [0, 2, 3]:
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 291, in _has_nchw_support
    explicitly_on_cpu = _is_current_explicit_device('CPU')
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 266, in _is_current_explicit_device
    device = _get_current_tf_device()
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 247, in _get_current_tf_device
    g._apply_device_functions(op)
  File "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 4581, in _apply_device_functions
    op._set_device_from_string(device_string)
AttributeError: '_TfDeviceCaptureOp' object has no attribute '_set_device_from_string'

```

**Comment by tuanzhangCS** [comment]
@rbavery You can open the file "/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py" and check if there is the fix there. The reason for this error is that "class  _TfDeviceCaptureOp" which declared in "keras/backend/tensorflow_backend.py" has no func '_set_device_from_string', so we can just add it.
So I think you package of keras doesn't have the change of this fix PR. My way is merge the code by myself, only need to add three lines code all. It runs well.
why your keras doesn't have this fix, I guess you install keras by pip?

**Comment by robieta** [comment]
Indeed. The fix is in for keras-team/keras, but conda/pip installs won't pick it up until the next keras release. @fchollet Do you think it's worth making a 2.2.6? (I'm not sure how far out 2.3.0 is, and if this is breaking enough to warrant an intermediate release.)

**Comment by arianaa30** [comment]
Does it get fixed on TF 2.0?

**Comment by robieta** [comment]
With the release of keras-team/keras, this should be fixed in both keras and tf.keras.

**Comment by sunanlin13174** [comment]
> **@rbavery** You can open the file _**"/data/anaconda/envs/cropmask/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py"**_ and check if there is the fix there.
> The reason for this error is that _"class _TfDeviceCaptureOp"_ which declared in _"keras/backend/tensorflow_backend.py"_ has no function _'_set_device_from_string'_, so we can just add it.
> So I think your package of keras doesn't have the change of this fix PR. My way is merge the code by myself, only need to add three lines code all. It runs well.
> why your keras doesn't have this fix, I guess you install keras by pip?

name "tfdev" is not defined? where is the tfdev?

**Comment by tuanzhangCS** [comment]
@sunanlin13174 Have you added `from tensorflow.python.framework import device as tfdev` ? Make sure you added every line in **robieta**'s commit. By the way, the last version of keras still doesn't work?

**Comment by sunanlin13174** [comment]
> @sunanlin13174 Have you added `from tensorflow.python.framework import device as tfdev` ? Make sure you added every line in **robieta**'s commit. By the way, the last version of keras still doesn't work?

thanks very much,i upgraded keras to 2.3.0,and the issue solved. but i meet a new issue: "no model name control_flow_ops",so i modified keras.backend.__init__.py,add a code "from .load_backend import control_flow_ops" , but error:"cannot import name 'control_flow_ops' from 'keras.backend.load_backend' , tesorflow-gpu==1.14.0 , do you have a solution? thanks for reply!

**Comment by tuanzhangCS** [comment]
> 
> 
> > @sunanlin13174 Have you added `from tensorflow.python.framework import device as tfdev` ? Make sure you added every line in **robieta**'s commit. By the way, the last version of keras still doesn't work?
> 
> thanks very much,i upgraded keras to 2.3.0,and the issue solved. but i meet a new issue: "no model name control_flow_ops",so i modified keras.backend.**init**.py,add a code "from .load_backend import control_flow_ops" , but error:"cannot import name 'control_flow_ops' from 'keras.backend.load_backend' , tesorflow-gpu==1.14.0 , do you have a solution? thanks for reply!

Keras doesn't support `control_flow_ops` now. So, you need use it from tensorflow directly.

**Comment by sunanlin13174** [comment]
yes,i got it ,thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tuanzhangCS"<notifications@github.com&gt;; 
发送时间: 2019年10月28日(星期一) 晚上8:36
收件人: "tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;; 
抄送: "梧桐"<1317477457@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [tensorflow/tensorflow] AttributeError: &#39;_TfDeviceCaptureOp&#39; object has no attribute &#39;_set_device_from_string&#39; (#30728)



  
@sunanlin13174 Have you added from tensorflow.python.framework import device as tfdev ? Make sure you added every line in robieta's commit. By the way, the last version of keras still doesn't work?
  
thanks very much,i upgraded keras to 2.3.0,and the issue solved. but i meet a new issue: "no model name control_flow_ops",so i modified keras.backend.init.py,add a code "from .load_backend import control_flow_ops" , but error:"cannot import name 'control_flow_ops' from 'keras.backend.load_backend' , tesorflow-gpu==1.14.0 , do you have a solution? thanks for reply!
  
Keras doesn't support control_flow_ops now. So, you need use it from tensorflow directly.
