### ISSUE TITLE
[BUG] [TF 2.0 Keras] Pointwise Conv2D numerically inconsistent in keras model vs manual run

### ISSUE THREAD

**Issue by Kaynato** [tensorflow/tensorflow#30934]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Docker container**: 2.0.0b1-gpu-py3-jupyter
- **CUDA/cuDNN version**: CUDA 10.2
- **GPU model and memory**: GeForce GTX 1080
- **Exact command to reproduce**: See script below.

### Describe the problem
Wrapping an identical tf.nn.conv2d operation **that has ksize of (1, 1)** in a tf.keras.Model and calling the model, with or without predict, on identical data, produces different results.

The differences are small but accumulate through a deep network if many pointwise convs are used.

### Source code / logs

```
import tensorflow as tf
import numpy as np

np.random.seed(123)
pool = np.ones([32, 64, 64, 64], 'float32')
w1 = np.random.randn(1, 1, 64, 64).astype('float32')

# Manual convolution
conv1 = tf.nn.conv2d(pool, w1, [1, 1], padding='SAME').numpy()

# The same convolution op via keras model
tmp_input = tf.keras.Input(shape=[64, 64, 64], dtype='float32')
tmp_out = tf.nn.conv2d(tmp_input, w1, [1, 1], padding='SAME)

# .predict can also be removed
conv2 = tf.keras.Model(inputs=tmp_input, outputs=tmp_out).predict(pool)

# The individual error is small, but it compounds through a deep network.
print('Disagreement between manual and keras-model wrapped conv:', np.abs(conv1 - conv2).sum())
```

This script can be run in a fresh pull of the docker container.

**Comment by gadagashwini** [comment]
I tried executing the code on Colab and I could able to reproduce the issue with TF 2.0.0.beta1. Please see the gist of [Colab](https://colab.research.google.com/drive/1fJaDnYtOjFjNklmmecfIXUIp_vKOO8aj).Thanks!

**Comment by jvishnuvardhan** [comment]
@Kaynato I think this was resolved in `tf-nightly-2.0-preview==2.0.0.dev20190718`. Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/39386ed6c56b2c16b6466cb41bb29228/tf_30934.ipynb). I don't see any issues with tf-nightly-2.0. Thanks!

**Comment by Kaynato** [comment]
I updated to tf-nightly-gpu-2.0-preview 2.0.0.dev20190724 and the issue is still present.

I care mostly about this issue in the **gpu version** of tensorflow - in fact I have a feeling that the discrepancy has to do with how data is passed to and from the GPU.

**Comment by jvishnuvardhan** [comment]
@Kaynato Can you check my [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/af4efafb809c4558189b31a9463aa5a6/tf_30934.ipynb) and let me know what you think? When I ran the gist it results in `Disagreement between manual and keras-model wrapped conv: 0.0` which means it working as expected right?

Could you create a gist and share it with the results. Thanks!

**Comment by Kaynato** [comment]
This gist works, but I can't replicate the fix on my local machine even with the same version of tensorflow. Maybe it has to do with the drivers, but it's unclear.

Here is the script, with a print at the beginning to verify that the version is in fact tf.nightly-gpu-2.0-preview==2.0.0.dev20190718

```
import tensorflow as tf
import numpy as np

print('Tensorflow Version:', tf.__version__)

np.random.seed(123)
pool = np.ones([32, 64, 64, 64], 'float32')
w1 = np.random.randn(1, 1, 64, 64).astype('float32')

# Manual convolution
conv1 = tf.nn.conv2d(pool, w1, [1, 1], padding='SAME').numpy()

# The same convolution op via keras model
tmp_input = tf.keras.Input(shape=[64, 64, 64], dtype='float32')
tmp_out = tf.nn.conv2d(tmp_input, w1, [1, 1], padding='SAME)

# .predict can also be removed
conv2 = tf.keras.Model(inputs=tmp_input, outputs=tmp_out).predict(pool)

# The individual error is small, but it compounds through a deep network.
print('Disagreement between manual and keras-model wrapped conv:', np.abs(conv1 - conv2).sum())
```

Here is the output log I receive:

```
2019-07-25 14:59:44.966783: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-07-25 14:59:45.341260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:87:00.0
2019-07-25 14:59:45.343798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:88:00.0
2019-07-25 14:59:45.344169: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-07-25 14:59:45.346193: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-07-25 14:59:45.347898: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-07-25 14:59:45.348303: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-07-25 14:59:45.350655: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-07-25 14:59:45.352361: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-07-25 14:59:45.357594: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-07-25 14:59:45.364630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2019-07-25 14:59:45.365093: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-25 14:59:45.826040: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5ccd7c0 executing computations on platform CUDA. Devices:
2019-07-25 14:59:45.826109: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
2019-07-25 14:59:45.826125: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): GeForce GTX 1080, Compute Capability 6.1
2019-07-25 14:59:45.851060: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200005000 Hz
2019-07-25 14:59:45.855590: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5d44940 executing computations on platform Host. Devices:
2019-07-25 14:59:45.855631: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-25 14:59:46.043201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:87:00.0
2019-07-25 14:59:46.043856: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:88:00.0
2019-07-25 14:59:46.043903: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-07-25 14:59:46.043919: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-07-25 14:59:46.043932: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-07-25 14:59:46.043945: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-07-25 14:59:46.043957: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-07-25 14:59:46.043970: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-07-25 14:59:46.043984: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-07-25 14:59:46.046411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2019-07-25 14:59:46.046452: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-07-25 14:59:46.048207: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-25 14:59:46.048223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 
2019-07-25 14:59:46.048231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N Y 
2019-07-25 14:59:46.048237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   Y N 
2019-07-25 14:59:46.050196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7606 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:87:00.0, compute capability: 6.1)
2019-07-25 14:59:46.051497: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 7606 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080, pci bus id: 0000:88:00.0, compute capability: 6.1)
2019-07-25 14:59:49.843891: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-07-25 14:59:50.415257: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
Tensorflow Version: 2.0.0-dev20190724
Disagreement between manual and keras-model wrapped conv: 5.8203125
```

**Comment by jvishnuvardhan** [comment]
@Kaynato Thanks for your patience. Can you try with `!pip install tf-nightly-gpu-2.0-preview==2.0.0.dev20190724` which is what I used in my recent gist. Thanks!

**Comment by Kaynato** [comment]
Hello, thank you for your help. Though the gist works correctly in a colab instance, **the gist is not reproducible on the local machine despite both being clean installations and fresh container pulls.**

Either the issue is likely a **driver / hardware bug** and so at least should be made known (that perhaps some version of CUDA or CUDNN causes issues here, or that there is something else going on.

In either case, it is unexpected behavior.

To demonstrate that I am using the correct version of tensorflow, I recorded the procedure on the local machine and demonstrate that the inconsistency is still present.

[screencapture.zip](https://github.com/tensorflow/tensorflow/files/3437068/screencapture.zip)

The device information is the same as before and described in the more verbose log in my previous comment here.

**Comment by jvishnuvardhan** [comment]
@Kaynato I don't know what else we can do to find root-cause of this issue as we cannot access your local machine. But surely we can say this is not related to Tensorflow. May be downgrading to CUDA10.0 and test again might help i think. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
