### ISSUE TITLE
ImportError: cannot import name 'monitoring' from 'tensorflow.python.eager'

### ISSUE THREAD

**Issue by yichuxue** [tensorflow/tensorflow#31218]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): pip install tensorflow
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 7.4.0
- GPU model and memory: 1060 p100 6G

**Describe the current behavior**

> (base) anlly@anlly-Vostro-3668:~/tensorflow/tensorflow$ bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=/home/anlly/mobilenet/models-master/research/slim/flower_mobilenet_v1.pb \
--input_checkpoint=/home/anlly/mobilenet/models-master/research/slim/train_log/model.ckpt-100000 \
--input_binary=true \
--output_graph=/home/anlly/mobilenet/models-master/research/slim/flower_frozen_mobilenet_v1.pb \
--output_node_names=MobilenetV1/Predictions/Reshape_1
Traceback (most recent call last):
  File "/home/anlly/tensorflow/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/freeze_graph.py", line 57, in <module>
    from tensorflow.python.tools import saved_model_utils
  File "/home/anlly/tensorflow/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/tools/saved_model_utils.py", line 21, in <module>
    from tensorflow.contrib.saved_model.python.saved_model import reader
  File "/home/anlly/tensorflow/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/saved_model/__init__.py", line 27, in <module>
    from tensorflow.contrib.saved_model.python.saved_model.keras_saved_model import *
  File "/home/anlly/tensorflow/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/saved_model/python/__init__.py", line 27, in <module>
    from tensorflow.contrib.saved_model.python.saved_model import *
  File "/home/anlly/tensorflow/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/saved_model/python/saved_model/__init__.py", line 27, in <module>
    from tensorflow.contrib.saved_model.python.saved_model import keras_saved_model
  File "/home/anlly/tensorflow/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/contrib/saved_model/python/saved_model/keras_saved_model.py", line 44, in <module>
    from tensorflow_estimator.python.estimator import keras as estimator_keras_util
  File "/home/anlly/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "/home/anlly/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "/home/anlly/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/baseline.py", line 67, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/home/anlly/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 37, in <module>
    from tensorflow.python.eager import monitoring
ImportError: cannot import name 'monitoring' from 'tensorflow.python.eager' (/home/anlly/tensorflow/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/eager/__init__.py)

**Describe the expected behavior**
Combine into pb file.

**Code to reproduce the issue**
download https://github.com/tensorflow/tensorflow/archive/v1.13.1.zip
/home/anlly/mobilenet/models-master/research/slim
After training.

> ├── BUILD
├── data
├── datasets
├── deployment
├── download_and_convert_data.py
├── eval_image_classifier.py
├── export_inference_graph.py
├── export_inference_graph_test.py
├── flower_mobilenet_v1.pb
├── flowers
├── __init__.py
├── nets
├── preprocessing
├── README.md
├── scripts
├── setup.py
├── slim_walkthrough.ipynb
├── train_image_classifier.py
├── train_log
└── WORKSPACE

> $ cd /home/anlly/tensorflow/tensorflow
$ bazel build tensorflow/python/tools:freeze_graph
$ tree -L 1
├── ACKNOWLEDGMENTS
├── ADOPTERS.md
├── arm_compiler.BUILD
├── AUTHORS
├── bazel-bin -> /home/anlly/.cache/bazel/_bazel_anlly/4719d97187e55f4eec6999680f3515c6/execroot/org_tensorflow/bazel-out/k8-opt/bin
├── bazel-genfiles -> /home/anlly/.cache/bazel/_bazel_anlly/4719d97187e55f4eec6999680f3515c6/execroot/org_tensorflow/bazel-out/k8-opt/genfiles
├── bazel-out -> /home/anlly/.cache/bazel/_bazel_anlly/4719d97187e55f4eec6999680f3515c6/execroot/org_tensorflow/bazel-out
├── bazel-tensorflow -> /home/anlly/.cache/bazel/_bazel_anlly/4719d97187e55f4eec6999680f3515c6/execroot/org_tensorflow
├── bazel-testlogs -> /home/anlly/.cache/bazel/_bazel_anlly/4719d97187e55f4eec6999680f3515c6/execroot/org_tensorflow/bazel-out/k8-opt/testlogs

> ├── BUILD
├── CODE_OF_CONDUCT.md
├── CODEOWNERS
├── configure
├── configure.py
├── CONTRIBUTING.md
├── ISSUES.md
├── ISSUE_TEMPLATE.md
├── LICENSE
├── models.BUILD
├── README.md
├── RELEASE.md
├── SECURITY.md
├── tensorflow
├── third_party
├── tools
└── WORKSPACE

> $ bazel-bin/tensorflow/python/tools/freeze_graph \
--input_graph=/home/anlly/mobilenet/models-master/research/slim/flower_mobilenet_v1.pb \
--input_checkpoint=/home/anlly/mobilenet/models-master/research/slim/train_log/model.ckpt-100000 \
--input_binary=true \
--output_graph=/home/anlly/mobilenet/models-master/research/slim/flower_frozen_mobilenet_v1.pb \
--output_node_names=MobilenetV1/Predictions/Reshape_1

Then throw an error.
`
ImportError: cannot import name 'monitoring' from 'tensorflow.python.eager' 
`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by anush-o** [comment]
@yichuxue ,
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here.We are not able to find the exact code from the link given to reproduce the issue. Thanks!

**Comment by yichuxue** [comment]
@anush-o Thanks. The problem has been solved.
The reason is that the tensorflow version of training is not consistent with the tensorflow version of composing pb files. The final successful version:
`
Tensorflow = = 1.13.1
Tensorflow - gpu = = 1.13.1
Tensorflowjs = = 0.8.6
`

**Comment by anush-o** [comment]
Closing since the issue is resolved.Thanks!

**Comment by BenWiseman** [comment]
I have tf 1.13.1 and I still get this error. 

Honestly, it's this kind of bullshit that makes me hate Python.
