### ISSUE TITLE
PyCharm debugger automatically evaluates Tensor._shape and spams console

### ISSUE THREAD

**Issue by jannik-w** [tensorflow/tensorflow#31236]
**System information**
- OS Platform and Distribution: macOS 10.14.6
- TensorFlow version: 1.14.0
- Python version: 3.6.8

**Describe the current behavior**
When analyzing a tensor in eager-execution mode in the "Watches" of the PyCharm Debugger, the deprecated object Tensor._shape is automatically evaluated. This results in following warning in the console (two times for one evaluation). When evaluating many tensor, this substantially spams the console.

```console
W0801 15:29:42.581780 4505736640 ops.py:465] Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
```

**Describe the expected behavior**
Significant reduce in the amount of warnings, ideally to zero.

**Code to reproduce the issue**
```python
import tensorflow as tf

tf.compat.v1.enable_eager_execution()

import numpy as np

tensor_1 = tf.convert_to_tensor(np.ones((20, 20)))

print()  # set breakpoint here
```

**Comment by anush-o** [comment]
@jannik-w ,
Can you please try using different Python IDE and let us know your feedback.Thanks!

**Comment by jannik-w** [comment]
Hi @anush-o,

I think the problem emerges when a debugger of any IDE automatically evaluates all attributes of a tensor, including the private ones. So I am not sure what reproducing the problem in another IDE would accomplish.

There might be two ways to move forward:
(1) Remove either the warning or the deprecated attribute as the disadvantages outweigh the advantages for some users of one of the most popular IDEs.
(2) Somehow manage that the warning is not printed excessively.

**Comment by jannik-w** [comment]
@jvishnuvardhan
Yes, but I do not want to turn off warnings during debugging, because those can be helpful.

**Comment by Saduf2019** [comment]
@jannik-w Could you please confirm if the issue persist, i have tried this on anaconda and colab there is no issue.

**Comment by RoboChris1** [comment]
@mihaimaruseac I am running 2.1 and I am still getting the warning with logs off.

**Comment by jvishnuvardhan** [comment]
@jannik-w Can you check with `TF2.2` or `tf-nightly` and let us know if you notice the issue? 

Please close the issue if this was already resolved. Thanks!

**Comment by kevinashaw** [comment]
Running TF2.3.1 and still getting this message.  Using pycharm.

```
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.
WARNING:tensorflow:Tensor._shape is private, use Tensor.shape instead. Tensor._shape will eventually be removed.

```

**Comment by jvishnuvardhan** [comment]
@kevinashaw Can you please open a new issue with a simple standalone code to reproduce the issue? Thanks!

**Comment by patzm** [comment]
I am also getting this issue even with TensorFlow 2.4. It always happens when unfolding the a `tf.Tensor` instance in the _Variables_ view.
