### ISSUE TITLE
BaseCollectiveExecutor::StartAbort Out of range: warnings when fit model in graph mode (TF 2.0 Nightly)

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/tensorflow#31509]
**System information**
- OS Platform and Distribution : Windows 10
- TensorFlow installed from : Binary
- TensorFlow version : TF 2.0 Nightly GPU Preview
- Python version:3.6
- CUDA/cuDNN version: 10.1
- GPU model and memory: 960M

I have a very simple model that I have made by inheriting from tf.Keras.model, which I feed with a dataset i,e

model = MyModel(...)

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01, amsgrad=True),
                       loss=loss_fn,
                       run_eagerly=False)

dataset = tf.data.Dataset.from_tensor_slices((x, y))
dataset = dataset.shuffle(buffer_size=10000)
dataset = dataset.batch(batch_size=1000)

model.fit(dataset,
          epochs=100,
          verbose=0,
          callbacks=[LossAndErrorPrintingCallback()])

If I run this using TF 2.0 (beta), works perfectly fine i.e with run_eagerly=False. If I run it using TF nightly preview with run_eagerly=True, again fine. However if I try with run_eagerly=False using nightly preview I get a stream of the following warnings,

 2019-08-10 16:35:40.168418: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]

**Comment by oanush** [comment]
@oracle3001 ,
In order to expedite the trouble-shooting process, can you please provide complete code snippet to reproduce the issue reported here.Thanks!

**Comment by oracle3001** [comment]
Here is a minimal model that produces the same issue...

```
import tensorflow as tf
import tensorflow_graphics as tfg
from tensorflow.python.framework import ops
from tensorflow.python.ops import math_ops
import numpy as np


class MinimalModelTest(tf.keras.Model):

    def __init__(self,
                 control_vert_pos,
                 dtype=tf.float64):
        super(MinimalModelTest, self).__init__(dtype=dtype)
        self.t_y_spherical = tfg.math.math_helpers.cartesian_to_spherical_coordinates(control_vert_pos)
        self.n_control_verts = control_vert_pos.shape[0]
        self.t_y_radius = self.t_y_spherical[:, 0]
        self.av_radius = np.mean(self.t_y_radius.numpy())

        self.t_av_radius = tf.Variable(self.av_radius,
                                       name='t_av_radius',
                                       dtype=self.dtype,
                                       trainable=False)

        self.t_y_polar = tf.Variable(self.t_y_spherical[:, 1:3],
                                     name='t_y_polar',
                                     dtype=self.dtype,
                                     trainable=True)

    def build(self, input_shape):
        super(MinimalModelTest, self).build(input_shape)

    def spherical_to_cartesian_coordinates(self, point_spherical, name=None):
        r, theta, phi = tf.unstack(point_spherical, axis=-1)
        # r = asserts.assert_all_above(r, 0)
        tmp = r * tf.sin(theta)
        x = tmp * tf.cos(phi)
        y = tmp * tf.sin(phi)
        z = r * tf.cos(theta)
        return tf.stack((x, y, z), axis=-1)

    def loss_fn(self, y_true, y_pred):
        y_pred = ops.convert_to_tensor(y_pred)
        y_true = math_ops.cast(y_true, y_pred.dtype)
        return tf.reduce_mean(tf.square(y_true - y_pred))

    def call(self, inputs):
        t_radius = self.t_av_radius * tf.ones([self.n_control_verts, 1], dtype=self.dtype)
        t_cv_sphere_spherical = tf.concat([t_radius, self.t_y_polar], axis=-1)
        return self.spherical_to_cartesian_coordinates(t_cv_sphere_spherical)



n_points = 10
# generate_prototypes produce n 3d points that lie on a unit sphere
rand_sphere_points_start = np.asarray(generate_prototypes(n_points))
rand_sphere_points_target = np.asarray(generate_prototypes(n_points))

joint_sample_model = MinimalModelTest(
        control_vert_pos=rand_sphere_points_start)

optimizer = tf.optimizers.Adam(learning_rate=0.005, amsgrad=True)
joint_sample_model.compile(optimizer=optimizer,
              loss=[joint_sample_model.loss_fn],
              run_eagerly=False)

batch_size = n_points
dataset = tf.data.Dataset.from_tensor_slices((rand_sphere_points_start, rand_sphere_points_target))
dataset = dataset.batch(batch_size=batch_size)

joint_sample_model.fit(dataset,
          epochs=100,
          verbose=1)
```

**Comment by oanush** [comment]
@oracle3001 ,
When tried executing the given code, error `NameError: name 'generate_prototypes' is not defined` was faced.Thanks!

**Comment by oracle3001** [comment]
Sorry, yes it is just a function to create random points. Here is the missing functions.

```
def polar2cartesian(theta, phi):
    return (
        np.cos(theta) * np.sin(phi),
        np.sin(theta) * np.sin(phi),
        np.cos(phi)
    )

def generate_prototypes(n):
    """
        ref: "How to generate equidistributed points on the surface of a sphere" by Markus Deserno
        note that in the paper, {phi, theta} correspond to {theta, phi} in the rest of this code
        n is an approximate number. the number of returned points are smaller
    """
    a = 2.0*3.1415926/n
    d = np.sqrt(a)
    mtheta = int(round(0.5*3.1415926/d))
    dtheta = 0.5*3.1415926/mtheta
    dphi = a/dtheta

    lst = []
    for m in range(mtheta - 1):
        theta = 0.5*3.1415926 * (m + 0.5)/mtheta
        mphi = int(round(2.0*3.1415926*np.sin(theta)/dphi))
        for n in range(mphi):
            phi = 2.0*3.1415926*n/mphi
            lst.append(polar2cartesian(phi, theta))
    return lst
```

**Comment by ymodak** [comment]
This is fixed with latest version of tf nightly 2.0 build '2.0.0-dev20190906' . Thanks!
Replace  ```tf.optmizer``` with ```tf.keras.optimizer``` on line 64
```python
optimizer = tf.keras.optimizers.Adam(learning_rate=0.005, amsgrad=True)
```

**Comment by graffadev** [comment]
This bug seems still present as of 2.0.0 official release (as well as RC1)
I tried just now with the code snippet above. I have seen a similar problem in our code.

Any hint?

Thanks
Graffa

**Comment by anbasile** [comment]
Confirmed: please reopen this issue.

**Comment by rlewkowicz** [comment]
@ymodak  ^^

**Comment by npuichigo** [comment]
any update?

**Comment by faizanahemad** [comment]
Please look into this issue. The console output becomes a complete mess

**Comment by LaurentBerger** [comment]
Please this issue is not closed :

```
import numpy as np
import tensorflow as tf

x = np.array([1, 5, 8, 9 ,10, 15,13, 3,-2],np.float32)
y = np.array([-2,-5, -7, -12 ,-15, -5, -12,-10,-5],np.float32)
taille_lot = 2
num_epochs = 3
dataset = tf.data.Dataset.from_tensor_slices(( x , y ))
dataset = dataset.shuffle(5000).batch(taille_lot)
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1, kernel_initializer='uniform', activation='linear',input_shape=(1,)))
model.layers[0].set_weights([np.array([[7.3]],np.float32),np.array([5.5],np.float32)])
model.layers[0](np.array([[3]]))
model.compile(optimizer='sgd', loss='mse')
model.fit(dataset, epochs=num_epochs, verbose=1)
print(model.layers[0].get_weights())
```

Results 

```
Epoch 1/3
      5/Unknown - 0s 38ms/step - loss: 6054.71502019-11-19 22:10:42.931510: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
         [[{{node IteratorGetNext}}]]
5/5 [==============================] - 0s 44ms/step - loss: 6054.7150
Epoch 2/3
1/5 [=====>........................] - ETA: 0s - loss: 41151.96482019-11-19 22:10:42.971527: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
         [[{{node IteratorGetNext}}]]
5/5 [==============================] - 0s 9ms/step - loss: 23133.6308
Epoch 3/3
1/5 [=====>........................] - ETA: 0s - loss: 4397.38772019-11-19 22:10:43.028938: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
         [[{{node IteratorGetNext}}]]
5/5 [==============================] - 0s 9ms/step - loss: 1409.5287
[array([[-1.4536909]], dtype=float32), array([3.2347755], dtype=float32)]
>>>
```

**Comment by mmaaz60** [comment]
Hi, I am facing this issue while training tiny yolo on VOC2012 dataset using model.fit() method. Note that I am using repo https://github.com/zzh8829/yolov3-tf2 and using TF2.0 official release. Any suggestion to fix the error?

**Comment by grzelak-michal** [comment]
Hi, I also have got this problem. Model is learning normally, however console output is unreadable. after every epoch there is an error with message "BaseCollectiveExecutor::StartAbort Out of range: End of sequence".

**Comment by TylerGubala** [comment]
Same issue on fresh install

**Operating System**: Windows 10
**Python**: 3.7-64
**Tensorflow Package**: tensorflow-gpu
**GPU Hardware**: 1080Ti
**CUDA Lib**: 10.0
**cuDNN**: 7.6.5.32

**Comment by realiti4** [comment]
I'm having the same issue, I though I was doing something wrong at first loading numpy data to tf.data, but then it gave me same errors following this example 

https://www.tensorflow.org/tutorials/load_data/numpy

**Comment by hohl** [comment]
This bug still seems to be in the Tensorflow 2.0.0 release. I'm getting exactly that error messages multiple times when running the following tutorial project: https://www.tensorflow.org/tutorials/text/text_classification_rnn

The model seems to train and accuracy is increasing, so the warning doesn't seem to cause any harm besides messing up the shell.

**Operating System:** Ubuntu 18.04.3 LTS
**Python:** 3.7.5
**Tensorflow Package:** tensorflow-gpu@2.0.0
**CUDA Lib:** 10.0.130
**GPU Model and Memory:** GTX 1050 Ti, 4GB

**Comment by ThatAIGeek** [comment]
Getting same issue, would be nice to know the reason for it and how to fix it if possible.

**Comment by sebastienrichoz** [comment]
It seems fixed in tensorflow-gpu@2.1.0rc1 (https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0-rc1)

**Operating System:** Ubuntu 18.04
**Python:** 3.6.9
**Tensorflow:** tensorflow-gpu@2.1.0rc1
**CUDA:** 10.1.243
**CuDNN:** 7.6
**GPU:** Quadro RTX 5000
**NVidia driver:** 430.26

**Comment by paapu88** [comment]
Also facing this problem:
>Hi, I am facing this issue while training tiny yolo on VOC2012 dataset using model.fit() method. Note that I am using repo https://github.com/zzh8829/yolov3-tf2 and using TF2.0 official release. Any suggestion to fix the error?

Unfortunately 
> pip3 install --user tensorflow-gpu==2.1.0rc1

did not fix the error

**Comment by hohl** [comment]
The bug still seems to be in Tensorflow 2.1.0.

(I am now working on a different machine than the one I mentioned above. So it doesn't even seem to be specific to some setup. Different GPU, CPU, OS-Version, etc.)

*Operating System:* Ubuntu 19.10
*Python:* 3.7.5
*Tensorflow Package:* tensorflow@2.1.0
*CUDA Lib:* 10.1
*GPU Model and Memory:* RTX 2080 Super, 8GB

**Comment by Pyabecedarian** [comment]
I'm facing the same issue in Tensorflow 2.1.0.

After following all the steps in official tutorial https://tensorflow.google.cn/tutorials/load_data/csv,  I get the trained model and all stuff is fine. But the issue comes out each time when I try to evaluate the model on test_data:
  ` test_loss, test_accuracy = model.evaluate(test_data)`

**OS**:  Windows 10
**Python** :  3.7.6
**Tensorflow**:  2.1.0

**Comment by rmarru** [comment]
Based on https://github.com/keras-team/autokeras/issues/839#issuecomment-590097076:

Concerning a `model.fit`, setting `validation_steps` in case you are using `validation_data` or `steps_per_epoch` if your input `x` is a `tf.data dataset` solves this issue.

**Comment by Pyabecedarian** [comment]
> Based on [keras-team/autokeras#839 (comment)](https://github.com/keras-team/autokeras/issues/839#issuecomment-590097076):
> 
> Concerning a `model.fit`, setting `validation_steps` in case you are using `validation_data` or `steps_per_epoch` if your input `x` is a `tf.data dataset` solves this issue.
> 
> I have not tested a `model.evaluate` but following the same logic, I think you should set the `steps` parameter.

Thanks for your reply, that's the solution.

**Comment by markemus** [comment]
This bug still occurs when calling model.predict() on a tf.data.Dataset.from_generator(gen) dataset.

**Comment by Amanita-muscaria** [comment]
I'm getting it during the validation portion of `model.fit()`

**Comment by Tomiha** [comment]
Still present during validation indeed (or just before).

`W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
         [[{{node IteratorGetNext}}]]
2020-05-20 10:49:02.923506: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
         [[{{node IteratorGetNext}}]]
         [[IteratorGetNext/_6]]
2020-05-20 10:49:17.997026: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
         [[{{node IteratorGetNext}}]]
2020-05-20 10:49:17.997362: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
         [[{{node IteratorGetNext}}]]
         [[IteratorGetNext/_4]]`

**Comment by Amywang112** [comment]
Same here!
```
W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]
```

**Comment by adamp87** [comment]
In my case with TF-2.1, I load both train and validation dataset from a TFRecord file. E.g. tf.data.TFRecordDataset(filePath). This means, the tf.fit function has no chance to know the number of samples in the file. As @rmarru pointed out, if the params in the tf.fit function (_steps_per_epoch_, _validation_steps_) are set, then the function knows the number of elements and no warning should be seen.

If I dont set _steps_per_epoch_ and _validation_steps_, after the first epoch tf.fit will remember _steps_per_epoch_, but not  _validation_steps_. That means, from the second epoch I will receive less warnings, only for the validation.
