### ISSUE TITLE
"Init node weights/Assign doesn't exist in graph" happens when use convert in tflite

### ISSUE THREAD

**Issue by mmmmayi** [tensorflow/tensorflow#31609]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):
- TensorFlow version: Tensorflow nightly
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 7/10

**Describe the problem**
When I tried to convert a TensorFlow GraphDef into a TensorFlow Lite FlatBuffer from a tf.Session object, a error happend such like this:
`2019-08-14 16:01:23.946453: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-08-14 16:01:23.947157: E tensorflow/core/grappler/grappler_item_builder.cc:656] Init node weights/Assign doesn't exist in graph
`
and my code all showed below:

    def main(_):

      def loss_function(weight, logits, labels):
        labels = tf.one_hot(labels,4)
        labels = tf.cast(labels, tf.float32)
        first = tf.reduce_sum(tf.multiply(-labels, logits),1)
        second_0 = tf.add(tf.exp(logits[:,0]),tf.exp(logits[:,1]))
        second_1 = tf.add(tf.exp(logits[:,2]),tf.exp(logits[:,3]))
        log = tf.log(tf.add(second_1,second_0))
        weight = tf.transpose(tf.reduce_sum(tf.multiply(labels, weight),1))
        output = tf.multiply(weight,tf.add(first,log))

        return output

      def normalize(stft):
        stft_1 = numpy.empty([stft.shape[0],128,128])
        stft_2 = numpy.empty([stft_1.shape[0],stft_1.shape[1],stft_1.shape[2],1])
        for i in range(stft_1.shape[0]):
          image = Image.fromarray(stft[i,:,:])
          image = image.resize([128,128])
          stft_1[i,:,:] = numpy.array(image)

          min = numpy.min(stft_1[i,:,:])
          max = numpy.max(stft_1[i,:,:])
          stft_1[i,:,:] = (stft_1[i,:,:]-min)/(max-min)
          stft_2[i,:,:,:] = stft_1[i,:,:].reshape((stft_1.shape[1],stft_1.shape[2],1))
        return stft_2  
    # Get the data.
    
    stft_training, mfcc_training, labels_training = joblib.load(open(FLAGS.input, mode='rb'))
    stft_test, mfcc_test, labels_test = joblib.load(open(FLAGS.test, mode='rb'))

    stft_test = numpy.array(stft_test)
    mfcc_test = numpy.array(mfcc_test)
    labels_test = numpy.array(labels_test)
    stft_test = normalize(stft_test)
    mfcc_test = normalize(mfcc_test)

    stft_training = numpy.array(stft_training)
    mfcc_training = numpy.array(mfcc_training)
    labels_training = numpy.array(labels_training)
    stft_training = normalize(stft_training)
    mfcc_training = normalize(mfcc_training)

    stft_shape = stft_training.shape
    stft_shape = (None, stft_shape[1], stft_shape[2], 1)

    mfcc_shape = mfcc_training.shape
    mfcc_shape = (None, mfcc_shape[1], mfcc_shape[2], 1)

    labels_shape = labels_training.shape
    labels_shape = (None)

    stft_placeholder = tf.placeholder(stft_training.dtype, stft_shape)
    labels_placeholder = tf.placeholder(labels_training.dtype, labels_shape)
    mfcc_placeholder = tf.placeholder(mfcc_training.dtype, mfcc_shape)
    
    dataset_training = tf.data.Dataset.from_tensor_slices((stft_placeholder, mfcc_placeholder, labels_placeholder))
    dataset_training  = dataset_training.apply(
        tf.data.experimental.shuffle_and_repeat(len(stft_training), None))  
    dataset_training  = dataset_training.batch(BATCH_SIZE)
    dataset_training  = dataset_training.prefetch(1)
    iterator_training = dataset_training.make_initializable_iterator()
    next_element_training = iterator_training.get_next()
    num_epochs = FLAGS.epochs

      train_size = labels_training.shape[0]

      with tf.name_scope('input'):
        stft = tf.placeholder(
            name="stft",
            dtype=data_type(),
            shape=(BATCH_SIZE, IMAGE_HEIGHT, IMAGE_WEITH, NUM_CHANNELS))
        mfcc = tf.placeholder(
            name="mfcc",
            dtype=data_type(),
            shape=(BATCH_SIZE, IMAGE_HEIGHT, IMAGE_WEITH, NUM_CHANNELS))
        labels = tf.placeholder(tf.int64, shape=(BATCH_SIZE,))

      with tf.name_scope('test_input'):
        stft_t = tf.placeholder(
            data_type(),
            shape=(EVAL_BATCH_SIZE, IMAGE_HEIGHT, IMAGE_WEITH, NUM_CHANNELS))
        mfcc_t = tf.placeholder(
            data_type(),
            shape=(EVAL_BATCH_SIZE, IMAGE_HEIGHT, IMAGE_WEITH, NUM_CHANNELS))

      model = BRN()
      logits = model.forward(stft, mfcc)
      logits_ = tf.add(0.,logits,name="logits_")
      try:
        scalar_summary = tf.scalar_summary
        SummaryWrite = tf.train.SummaryWrite
        merge_summary = tf.merge_summary
      except:
        scalar_summary = tf.summary.scalar
        SummaryWrite = tf.summary.FileWriter
        merge_summary = tf.summary.merge
      with tf.name_scope('loss'):
        weights = [1.0, 1.7, 4.1, 5.7]
         mid = loss_function(weights, logits=logits, labels=labels)
        loss = tf.reduce_sum(mid)
    
        loss_summary = scalar_summary('loss', loss)
        regularizers = (tf.nn.l2_loss(model.conv1_weights) + tf.nn.l2_loss(model.conv2_weights) +
                    tf.nn.l2_loss(model.fc_weights) + tf.nn.l2_loss(model.fc_biases))

        batch = tf.Variable(0, dtype=data_type())
 
      with tf.name_scope('train'):

        optimizer = tf.train.AdamOptimizer(0.001).minimize(loss)
      train_prediction = tf.nn.softmax(logits)
      eval_prediction = tf.nn.softmax(model.forward(stft_t, mfcc_t))
      start_time = time.time()

      def eval_in_batches(stft_data, mfcc_data, sess, type):
        size = stft_data.shape[0]
        if size < EVAL_BATCH_SIZE:
          raise ValueError("batch size for evals larger than dataset: %d" % size)
        predictions = numpy.ndarray(shape=(size, NUM_LABELS), dtype=numpy.float32)
        for begin in xrange(0, size, EVAL_BATCH_SIZE):
          end = begin + EVAL_BATCH_SIZE
          if end <= size:
            if type == 'train':
              predictions[begin:end, :] = sess.run(
                  train_prediction,
                  feed_dict={stft: stft_data[begin:end, ...], mfcc: mfcc_data[begin:end, ...]})
            else: 
              predictions[begin:end, :] = sess.run(
                  eval_prediction,
                  feed_dict={stft_t: stft_data[begin:end, ...], mfcc_t: mfcc_data[begin:end, ...]})
          else:
            if type == 'train':
              batch_predictions = sess.run(
                  train_prediction,
                  feed_dict={stft: stft_data[-EVAL_BATCH_SIZE:, ...], mfcc: mfcc_data[-EVAL_BATCH_SIZE:, ...]})
            else:
               batch_predictions = sess.run(
                  eval_prediction,
                  feed_dict={stft_t: stft_data[-EVAL_BATCH_SIZE:, ...], mfcc_t: mfcc_data[-EVAL_BATCH_SIZE:, ...]})
            predictions[begin:, :] = batch_predictions[begin - size:, :]
        return predictions

      config = tf.ConfigProto()
      config.gpu_options.allow_growth = True  

      with tf.Session(config=config) as sess:
   
        tf.global_variables_initializer().run()

        merged = tf.summary.merge_all()
        writer = SummaryWrite(FLAGS.logs + 'train', sess.graph)
        sess.run(iterator_training.initializer, feed_dict={stft_placeholder:stft_training,
                          mfcc_placeholder:mfcc_training,
                         labels_placeholder:labels_training})

        for step in xrange(int(num_epochs * train_size) // BATCH_SIZE):

          batch_stft, batch_mfcc, batch_labels = sess.run(next_element_training)
  
          feed_dict = {stft: batch_stft,
                       mfcc: batch_mfcc,
                       labels: batch_labels}
          sess.run(optimizer, feed_dict=feed_dict)
          if step % EVAL_FREQUENCY == 0:

        summary, l = sess.run([merged, loss],
                                      feed_dict=feed_dict)
            writer.add_summary(summary, step)
            elapsed_time = time.time() - start_time
            start_time = time.time()
            rate, acc = error_rate(eval_in_batches(stft_training, mfcc_training, sess, 'train'), labels_training)
            acc_summary = scalar_summary('accuracy', acc)
            print('Step %d (epoch %.2f), Minibatch loss: %.3f, Minibatch error: %.1f%%, Accuracy:%.4f' %
              (step, float(step) * BATCH_SIZE / train_size,
              l,rate, acc))
            sys.stdout.flush()
            test_error, test_acc = error_rate(eval_in_batches(stft_test, mfcc_test, sess, 'test'), labels_test)
            print('Testset error: %.1f%%, Accuracy:%.4f' % (test_error, test_acc))

    converter = tf.lite.TFLiteConverter.from_session(sess, [stft,mfcc], [logits_])
    tflite_model = converter.convert()
    open("BRN.tflite", "wb").write(tflite_model)
        
    writer.close()

When I run the official demo of converting a TensorFlow GraphDef into a TensorFlow Lite FlatBuffer from a tf.Session object, the error also happens. Does that ok? I mean, can I use the weight trained in TensorFlow Lite? or the file doesn't save the weight?

**Comment by gadagashwini** [comment]
@mmmmayi, Please provide the complete code to reproduce the reported issue. Thanks!

**Comment by mmmmayi** [comment]
> @mmmmayi, Please provide the complete code to reproduce the reported issue. Thanks!

i have edited it and add up the whole useful code

**Comment by gadagashwini** [comment]
@mmmmayi I tried replicating the issue, looks like some entities are not defined `NameError: name 'joblib' is not defined`. Please help us reproduce the issue. Thanks!

**Comment by mmmmayi** [comment]
> @mmmmayi I tried replicating the issue, looks like some entities are not defined `NameError: name 'joblib' is not defined`. Please help us reproduce the issue. Thanks!

I'm so sorry, I misunderstand what you need, then you can find the whole code and database(wavelet_stft.p and wavelet_stft_test.p) in my google cloud: 
https://drive.google.com/open?id=1DfV7WPJymj66jJ13ds6javg3GSLPhwyr
but for your convenience,  you can also use the official demo, it caused the same error in my condition:
```
import tensorflow as tf

img = tf.placeholder(name="img", dtype=tf.float32, shape=(1, 64, 64, 3))
var = tf.get_variable(name="weights", dtype=tf.float32, shape=(1, 64, 64, 3))
val = img + var
out = tf.identity(val, name="out")

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  converter = tf.lite.TFLiteConverter.from_session(sess, [img], [out])
  tflite_model = converter.convert()
  open("converted_model.tflite", "wb").write(tflite_model)
```

**Comment by gadagashwini** [comment]
@mmmmayi, Thanks for providing the code.
I tried reproducing the issue on Colab with official demo code but i didn't receive any error. Please take a look at gist [here](https://colab.research.google.com/drive/1GYSh6qXCGzz4pOWU3Ht0a_raXYOfToKp). let us know. Thanks!

**Comment by mmmmayi** [comment]
> @mmmmayi, Thanks for providing the code.
> I tried reproducing the issue on Colab with official demo code but i didn't receive any error. Please take a look at gist [here](https://colab.research.google.com/drive/1GYSh6qXCGzz4pOWU3Ht0a_raXYOfToKp). let us know. Thanks!

Thanks for your reply, but when I try the error still exist, I don't know why. Here are the whole log:
``` 
(lite) mmmmayi@BICASL:~/Document/test$ python tflite_test.py
WARNING: Logging before flag parsing goes to stderr.
W0822 15:05:10.332202 140343267317568 module_wrapper.py:136] From /home/mmmmayi/.local/lib/python3.6/site-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-08-22 15:05:10.340097: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-08-22 15:05:10.345417: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-08-22 15:05:10.465133: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557d4cbf7c60 executing computations on platform CUDA. Devices:
2019-08-22 15:05:10.465156: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-08-22 15:05:10.484734: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3500000000 Hz
2019-08-22 15:05:10.485570: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557d4ccb8b70 executing computations on platform Host. Devices:
2019-08-22 15:05:10.485611: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-22 15:05:10.486958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:b3:00.0
2019-08-22 15:05:10.487298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 15:05:10.489793: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 15:05:10.491786: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 15:05:10.492278: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 15:05:10.495154: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 15:05:10.496298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 15:05:10.498792: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-22 15:05:10.500421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-08-22 15:05:10.500452: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 15:05:10.501338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 15:05:10.501348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-08-22 15:05:10.501354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-08-22 15:05:10.502606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6940 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:b3:00.0, compute capability: 6.1)
2019-08-22 15:05:10.824691: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2019-08-22 15:05:10.824793: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-08-22 15:05:10.826763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:b3:00.0
2019-08-22 15:05:10.826831: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 15:05:10.826863: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 15:05:10.826885: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 15:05:10.826905: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 15:05:10.826927: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 15:05:10.826947: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 15:05:10.826969: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-22 15:05:10.828266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-08-22 15:05:10.828291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 15:05:10.828297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-08-22 15:05:10.828303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-08-22 15:05:10.829652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6940 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:b3:00.0, compute capability: 6.1)
2019-08-22 15:05:10.831310: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-08-22 15:05:10.831328: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-08-22 15:05:10.831334: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
W0822 15:05:10.833272 140343267317568 deprecation.py:323] From /home/mmmmayi/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/util.py:249: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W0822 15:05:10.833422 140343267317568 deprecation.py:323] From /home/mmmmayi/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py:275: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2019-08-22 15:05:10.840123: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2019-08-22 15:05:10.840224: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-08-22 15:05:10.841963: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:b3:00.0
2019-08-22 15:05:10.842020: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 15:05:10.842043: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 15:05:10.842064: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 15:05:10.842083: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 15:05:10.842104: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 15:05:10.842123: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 15:05:10.842144: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-22 15:05:10.844217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-08-22 15:05:10.844260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 15:05:10.844276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-08-22 15:05:10.844289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-08-22 15:05:10.846621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6940 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:b3:00.0, compute capability: 6.1)
2019-08-22 15:05:10.847889: E tensorflow/core/grappler/grappler_item_builder.cc:656] Init node weights/Assign doesn't exist in graph
(lite) mmmmayi@BICASL:~/Document/test$ python tflite_test.py
WARNING: Logging before flag parsing goes to stderr.
W0822 15:07:51.153700 140406728853312 module_wrapper.py:136] From /home/mmmmayi/.local/lib/python3.6/site-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-08-22 15:07:51.162202: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2019-08-22 15:07:51.173639: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:b3:00.0
2019-08-22 15:07:51.173781: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 15:07:51.174777: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 15:07:51.175635: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 15:07:51.175847: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 15:07:51.176969: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 15:07:51.177846: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 15:07:51.180346: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-22 15:07:51.181777: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-08-22 15:07:51.182033: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-08-22 15:07:51.295496: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x557122a73a90 executing computations on platform CUDA. Devices:
2019-08-22 15:07:51.295533: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-08-22 15:07:51.316734: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3500000000 Hz
2019-08-22 15:07:51.317891: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55712309cbf0 executing computations on platform Host. Devices:
2019-08-22 15:07:51.317934: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-22 15:07:51.319601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:b3:00.0
2019-08-22 15:07:51.319669: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 15:07:51.319697: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 15:07:51.319722: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 15:07:51.319746: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 15:07:51.319770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 15:07:51.319793: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 15:07:51.319818: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-22 15:07:51.322084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-08-22 15:07:51.322145: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 15:07:51.324135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 15:07:51.324159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-08-22 15:07:51.324173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-08-22 15:07:51.326230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6940 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:b3:00.0, compute capability: 6.1)
2019-08-22 15:07:51.723521: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2019-08-22 15:07:51.723724: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-08-22 15:07:51.726067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:b3:00.0
2019-08-22 15:07:51.726138: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 15:07:51.726168: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 15:07:51.726195: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 15:07:51.726221: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 15:07:51.726247: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 15:07:51.726274: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 15:07:51.726300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-22 15:07:51.728298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-08-22 15:07:51.728319: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 15:07:51.728325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-08-22 15:07:51.728331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-08-22 15:07:51.729443: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6940 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:b3:00.0, compute capability: 6.1)
2019-08-22 15:07:51.730986: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-08-22 15:07:51.731002: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0.001ms.
2019-08-22 15:07:51.731007: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   function_optimizer: function_optimizer did nothing. time = 0ms.
W0822 15:07:51.733329 140406728853312 deprecation.py:323] From /home/mmmmayi/.local/lib/python3.6/site-packages/tensorflow_core/lite/python/util.py:249: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W0822 15:07:51.733462 140406728853312 deprecation.py:323] From /home/mmmmayi/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/graph_util_impl.py:275: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2019-08-22 15:07:51.738129: I tensorflow/core/grappler/devices.cc:55] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 1
2019-08-22 15:07:51.738175: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2019-08-22 15:07:51.739189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:b3:00.0
2019-08-22 15:07:51.739222: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2019-08-22 15:07:51.739231: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-08-22 15:07:51.739239: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2019-08-22 15:07:51.739248: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2019-08-22 15:07:51.739255: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2019-08-22 15:07:51.739263: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2019-08-22 15:07:51.739271: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-08-22 15:07:51.740303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-08-22 15:07:51.740323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-22 15:07:51.740328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2019-08-22 15:07:51.740333: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2019-08-22 15:07:51.741429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6940 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:b3:00.0, compute capability: 6.1)
2019-08-22 15:07:51.742438: E tensorflow/core/grappler/grappler_item_builder.cc:656] Init node weights/Assign doesn't exist in graph
```

**Comment by jvishnuvardhan** [comment]
@mmmmayi I couldn't reproduce the issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/ed91d93d0fa43a8a210881da87443b62/tf_31609_tflite.ipynb). 

1. Based on the error trace, you are running the code with `tensorflow-gpu` right? Can you try with 'tensorflow-cpu` only to see whether the issue caused due to any `cuda` related file. 

2. Can you run the gist provided here and see what you get as output?

Thanks!

**Comment by mmmmayi** [comment]
> @mmmmayi I couldn't reproduce the issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/ed91d93d0fa43a8a210881da87443b62/tf_31609_tflite.ipynb).
> 
> 1. Based on the error trace, you are running the code with `tensorflow-gpu` right? Can you try with 'tensorflow-cpu`only to see whether the issue caused due to any`cuda` related file.
> 2. Can you run the gist provided here and see what you get as output?
> 
> Thanks!

I think the

**Comment by mmmmayi** [comment]
> @mmmmayi I couldn't reproduce the issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/ed91d93d0fa43a8a210881da87443b62/tf_31609_tflite.ipynb).
> 
> 1. Based on the error trace, you are running the code with `tensorflow-gpu` right? Can you try with 'tensorflow-cpu`only to see whether the issue caused due to any`cuda` related file.
> 2. Can you run the gist provided here and see what you get as output?
> 
> Thanks!

**Comment by mmmmayi** [comment]
I think the problem is about get_variable, because if I use tf.placeholder to get var in the demo code, there isn't error, otherwise, the tf.get_variable leads to it

**Comment by mmmmayi** [comment]
> @mmmmayi I couldn't reproduce the issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/ed91d93d0fa43a8a210881da87443b62/tf_31609_tflite.ipynb).
> 
> 1. Based on the error trace, you are running the code with `tensorflow-gpu` right? Can you try with 'tensorflow-cpu`only to see whether the issue caused due to any`cuda` related file.
> 2. Can you run the gist provided here and see what you get as output?
> 
> Thanks!

it still exists when I use CPU, and you can get the output of it from the link(named converted_model3.tflite):
https://drive.google.com/drive/folders/1Ds8ihFsz9K5ZKPCS0FPQ2_qZBUOn3to3?usp=sharing

**Comment by jvishnuvardhan** [comment]
@mmmmayi 1. Did you ran the gist I created? Do you see any error?
2. Are you using `tf-nightly` right? Just a confirmation.   Thanks!

**Comment by michaelbenayoun** [comment]
@mmmmayi I am currently facing the same issue, have you found a solution ?
Thanks !

**Comment by DragonX081mk2** [comment]
> @mmmmayi I am currently facing the same issue, have you found a solution ?
> Thanks !

I just fixed this problem by using tf 1.13.1 but not tf 1.14...

**Comment by jvishnuvardhan** [comment]
@DragonX081mk2 Can you try `TF1.15.0rc3` and let us know whether the issue persists with the latest version. As `TF1.14` was not built properly, there were lot of issues when using it. Hence, TF team released new version `TF1.15`. Thanks!

**Comment by DragonX081mk2** [comment]
> @DragonX081mk2 Can you try `TF1.15.0rc3` and let us know whether the issue persists with the latest version. As `TF1.14` was not built properly, there were lot of issues when using it. Hence, TF team released new version `TF1.15`. Thanks!

Before trying 1.13.1, I have tried the 1.15.0 rc3, this problem existed too..

**Comment by mmmmayi** [comment]
> @mmmmayi I am currently facing the same issue, have you found a solution ?
> Thanks !

hi, actually I didn't figure it out, but it seems have no effect to the result, because I can still get the tflite model even with this error

**Comment by jvishnuvardhan** [comment]
@mmmmayi Can we close this issue? I don't see any error when I used `TF1.15.0`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/bc515f885097fc6fd01076a3859e7e5b/tf_31609_tflite.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!
