### ISSUE TITLE
[TF 2.0.0-rc0] Cannot find any 2.0.0 RC0 API references.

### ISSUE THREAD

**Issue by makercob** [tensorflow/tensorflow#31973]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 and macOS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0-rc0 (both GPU and CPU versions)
- Python version: 3.6.8

**Describe the current behavior**
Not a single reference to members of tensorflow can be found in IDE(PyCharm). 
However, programs run as expected.

**Describe the expected behavior**
References to members of tensorflow can be found.

<img width="602" alt="Screen Shot 2019-08-26 at 17 13 30" src="https://user-images.githubusercontent.com/6904036/63680285-e1412980-c825-11e9-89c5-8f8abc376275.png">

**Comment by calmisential** [comment]
@makercob Hello, friend! I have the same problem. I found PyCharm cannot find the tensorflow_2.0.0-rc0 API, but jupyter notebook and jupyter lab can. I'm also  puzzled by this problem.

**Comment by georgealexandruvlad** [comment]
Many others (including myself) reported the same problem in the following thread [https://github.com/tensorflow/tensorflow/issues/26502](url). The previous issue is closed so I will leave this here too hoping it has better coverage being an open issue.

**Comment by makercob** [comment]
@georgealexandruvlad uhmmm... PyCharm to blame? but 2.0.0b1 worked fine.

**Comment by georgealexandruvlad** [comment]
@makercob well, you're right. I'm just looking for a solution for large projects which can't be implemented in jupyter/google colab. As I stated in my comment in the other thread:

> If it is any workaround on this issue until a fix is released (from tensorflow team or PyCharm) I would be grateful to use it.

I only ask for a solution to get it working because there are lots of good new features in the new release. This could mean a solution from the tensorflow team if there are some steps to be followed in order to make it work with PyCharm or another IDE in which they know it is working properly.

**Comment by Efaq** [comment]
Is there any workaround for that, while it is not solved?

**Comment by makercob** [comment]
@georgealexandruvlad Could you please share a link to release notes of 2.0.0-rc0? I just can't find it anywhere. Thanks!

**Comment by georgealexandruvlad** [comment]
Sure. I think this should be what you're searching for: https://github.com/tensorflow/tensorflow/releases

**Comment by makercob** [comment]
@Efaq Any alternative to PyCharm? VS Code works not so well for me.

**Comment by Efaq** [comment]
@makercob I will try not to change, I have some preference for PyCharm. But in case it gets too annoying not to have the last version of TF, I will choose between VS and Spyder. **BUT** I don't even know if this would solve the issue :)

What issues have you had with VS Code? Could you get autocompletion?

**Comment by makercob** [comment]
@Efaq No autocompletion with VS Code either. :-/
Spoiled by PyCharm, not everything seems right to me in VS Code when working with Python. say, instant variable evaluation and numpy array inspection.

**Comment by shianiawhite** [comment]
> @makercob Hello, friend! I have the same problem. I found PyCharm cannot find the tensorflow_2.0.0-rc0 API, but jupyter notebook and jupyter lab can. I'm also puzzled by this problem.

Just a quick note about the general reason of why this happening. Jupyter dynamically figures out all the packages. PyCharm (for speed reasons) statically indexes everything. If things are only defined when dynamically run, PyCharm won't see them. Python packages are generally encouraged to have these things available statically. This explanation is slightly inaccurate, but close enough.

Unfortunately, in my case, I value PyCharm's capabilities and workflow far more than any improvements and fixes in the new TensorFlow releases. So this is a blocker on me upgrading.

**Comment by shianiawhite** [comment]
Also, as noted by others, this will not be a PyCharm specific issue. Many IDEs expect to be able to statically resolve the packages.

**Comment by deepgradient** [comment]
> Also, as noted by others, this will not be a PyCharm specific issue. Many IDEs expect to be able to statically resolve the packages.

Exactly, VScode has the same issue! :( why google use such goofy importing method in tensorflow?

**Comment by mihaimaruseac** [comment]
We needed a way to separate private internal APIs with no guarantees on stability with public stable(r) APIs so that code that works on Tensorflow x.y also works on Tensorflow x.{y+1} while evolving in private.

We also needed a way to suppot both a preview of 2.0 and 1.* at the same time.

But most of these needs will go away with the release of 2.0. Also, there is ongoing work to modularize TensorFlow and one of the components of that work is extracting the public API to a separate module. After that, autocomplete should work perfectly. See https://github.com/tensorflow/community/pull/77

**Comment by deepgradient** [comment]
> We needed a way to separate private internal APIs with no guarantees on stability with public stable(r) APIs so that code that works on Tensorflow x.y also works on Tensorflow x.{y+1} while evolving in private.
> 
> We also needed a way to suppot both a preview of 2.0 and 1.* at the same time.
> 
> But most of these needs will go away with the release of 2.0. Also, there is ongoing work to modularize TensorFlow and one of the components of that work is extracting the public API to a separate module. After that, autocomplete should work perfectly. See [tensorflow/community#77](https://github.com/tensorflow/community/pull/77)

Thanks for your clarification. I hope we can have everything perfect soon.
Do you have any idea as how long it may take to completely resolve this issue?

**Comment by mihaimaruseac** [comment]
Probably end of year

**Comment by annarev** [comment]
The fix for a large part of autocomplete has been submitted here: https://github.com/tensorflow/tensorflow/commit/386da9758dde5d278d646701a0769b931e564485 and should be in latest nightly. However, there are still some parts that don't work and we are looking into them.

**Comment by calmisential** [comment]
> 
> 
> The fix for a large part of autocomplete has been submitted here: [386da97](https://github.com/tensorflow/tensorflow/commit/386da9758dde5d278d646701a0769b931e564485) and should be in latest nightly. However, there are still some parts that don't work and we are looking into them.

Thanks for your work! Does this mean that the autocomplete problem will be solved when the next tensorflow-2.0 version (may be rc1) is released ?

**Comment by makercob** [comment]
@calmisential Nope. Spring is indeed pretty much flexible.

**Comment by egeozsoy** [comment]
A workaround which seems to work for now is importing as directly as possible. This means instead of 
`from tensorflow.keras import Model`
one has to do
`from tensorflow_core.python.keras.models import Model`

Instead of 
`import tensorflow as tf` and then
`tf.keras.optimizers.Adam()`

Use 
`from tensorflow_core.python.keras.optimizers import Adam`
and then just
`Adam()`

It makes it more cumbersome to import stuff, but at least autocomplete and other IDE features work

**Comment by RunOrVeith** [comment]
Is this fixed for you in rc1? I still have a similar problem.
`from tensorflow import keras` works
`from tensorflow.keras import layers` does not work.

**Comment by NiclasLaurenzChrist** [comment]
@RunOrVeith as mentioned the problem remains in rc1 (and will probably until the release of 2.0)

**Comment by RunOrVeith** [comment]
Ok I thought that might have changed because the release notes state 
`Fixes autocomplete for most TensorFlow API references by switching to use relative imports in API __init__.py files.`

**Comment by chuxi** [comment]
very annoying. 
I admire your work. But, the developing team should be more careful with such a big open project which would influence so many people's work. 

It is not good for tensorflow. Now I am using pyTorch instead.

**Comment by jubjamie** [comment]
> The fix for a large part of autocomplete has been submitted here: [386da97](https://github.com/tensorflow/tensorflow/commit/386da9758dde5d278d646701a0769b931e564485) and should be in latest nightly. However, there are still some parts that don't work and we are looking into them.

Just to confirm, this is no longer working in the nightly release is it?

**Comment by annarev** [comment]
Autocomplete has been fixed for `import tensorflow as tf` and `from tensorflow import keras` in rc1.
However, `from tensorflow.keras import layers` won't be fixed even in 2.0 final. It requires major changes to TensorFlow (renaming lite/ directory) to get it working. These changes are too big for this release since it only accepts critical cherrypicks.

Also, recommended way to import TensorFlow is `import tensorflow as tf`.

**Comment by jubjamie** [comment]
Just updated to rc1 and still have no success with `from tensorflow import keras` or `import tensorflow as tf`. This is gpu version if it makes a difference.
I've rebuilt all indices and caches etc. to eliminate a PyCharm issue. Changing interpreter back to 1.14 goes straight back to the intended functionality.

**Comment by georgesterpu** [comment]
Hi, I've been coding in TF 2.0 for the past few days and used this cheap workaround for my (momentarily) limited use case: install `tensorflow-gpu==2.0.0-beta1` alongside with `tensorflow==2.0.0-rc1`. But it's quite strange, better wait for a proper fix.

**Comment by Times125** [comment]
> Chinese to such interesting problem: He He. 呵呵

so lj u are

**Comment by RedTachyon** [comment]
This has been fixed for rc1 in the newest PyCharm EAP: https://blog.jetbrains.com/pycharm/2019/09/2019-3-eap-2

**Comment by Xovee** [comment]
> This has been fixed for rc1 in the newest PyCharm EAP: https://blog.jetbrains.com/pycharm/2019/09/2019-3-eap-2

It works, thx a lot.

**Comment by mihaimaruseac** [comment]
Closing as it has been fixed. Thanks for verifying.

**Comment by shianiawhite** [comment]
Just to note, although PyCharm is now correctly resolve TensorFlow, this solution does not solve the issue for other editors. There are others in this thread who have mentioned this issue also affects VS Code (and likely other editors).

(... but I use PyCharm, so I'm satisfied)

**Comment by mihaimaruseac** [comment]
In that case, reopening.

**Comment by speediedan** [comment]
While the workaround of importing tensorflow_core to access API functionality normally under tf.config (e.g.
```python
from tensorflow_core.python.framework import config as tfconfig
```
allows autocompletion to function (tf v2.0.0-rc2, pycharm EAP: 193.3519.27),  it does not allow me to use tf.config functionality due to the import error below:
```
ImportError: cannot import name 'module_util' from 'tensorflow.python.tools' (/opt/anaconda/envs/tf2rc/lib/python3.7/site-packages/tensorflow/python/tools/__init__.py)
```
Any suggestions on a temporary workaround for accessing tf.config functionality? Thanks very much in advance!!

**Comment by mihaimaruseac** [comment]
Importing directly from `tensorflow_core` is not supported and will result in your code being broken by future upgrades.

**Comment by speediedan** [comment]
Thanks Mihai, understood, I'm just looking for a temporary workaround to access tf.config, which isn't working with rc2. I think this is actually a separate issue and I'll create a separate ticket accordingly. Apologies for the confusion.

**Comment by ElPapi42** [comment]
This problem persist with Tensorflow 2.0 lastest release, using VS Code

**Comment by makercob** [comment]
@ElPapi42 PyCharm 2019.3 coming to rescue, probably in Nov.

**Comment by juhai** [comment]
I can reproduce this problem with tensorflow==1.15.0, using latest official PyCharm release (2019-2). Is the fix going to be applied to 1.X branch?

**Comment by soldier828** [comment]
> This problem persist with Tensorflow 2.0 lastest release, using VS Code
Yes, too mad with this issue

**Comment by arbellea** [comment]
Any timeline of a fix for this issue?

**Comment by episodeyang** [comment]
The fix is to use `import tensorflow.compat.v2 as tf` instead of the regular import.

**Comment by ElPapi42** [comment]
> The fix is to use `import tensorflow.compat.v2 as tf` instead of the regular import.

Not working for me :/

**Comment by davidhalter** [comment]
We're having discussions about tensorflow2 completions in Jedi. I proposed two solutions:

```
One way to fix this would be to just replace keras = _sys.modules["tensorflow.keras"] with from tensorflow import keras. This does essentially the same thing.

It's also nice to use something like:

import typing

if not typing.TYPE_CHECKING:
    keras = _sys.modules["tensorflow.keras"]

This only works in Python 3 (typing needs to be installed).
```

**Comment by lgeiger** [comment]
@davidhalter Thanks for helping debug this.

@mihaimaruseac I think I found a solution that get's rid of the problematic workarounds in #34629

**Comment by DanieleB89** [comment]
Why was this closed?
