### ISSUE TITLE
Simple `model.evaluate()` example floods output with `=` characters

### ISSUE THREAD

**Issue by Peque** [tensorflow/tensorflow#32286]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
  - **Fedora 30**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
  - **(binary): pip install tensorflow==2.0.0-rc0**
- TensorFlow version (use command below):
  - **v2.0.0-beta1-5101-gc75bb66 2.0.0-rc0**
- Python version:
  - **Python 3.7.4**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Running the code, I get an output flooded with hundreds of thousands of `=` characters when calling `model.evaluate()`.

```
Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 43us/sample - loss: 0.5010 - accuracy: 0.8228
Epoch 2/5
60000/60000 [==============================] - 2s 38us/sample - loss: 0.3766 - accuracy: 0.8639
Epoch 3/5
60000/60000 [==============================] - 2s 38us/sample - loss: 0.3408 - accuracy: 0.8753
Epoch 4/5
60000/60000 [==============================] - 2s 37us/sample - loss: 0.3155 - accuracy: 0.8839
Epoch 5/5
60000/60000 [==============================] - 2s 38us/sample - loss: 0.2980 - accuracy: 0.8903
10000/1 [==================================================================
===========================================================================
===========================================================================
===========================================================================
===========================================================================
===========================================================================
===========================================================================
===========================================================================
...
... Literally hundreds of thousands of `=` ...
...
===========================================================================
===========================================================================
===========================================================================
===========================================================================
===========================================================================
===========================================================================
===========================================] - 0s 26us/sample - loss: 0.2803 - accuracy: 0.8673

```

**Describe the expected behavior**

```
Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 43us/sample - loss: 0.5010 - accuracy: 0.8228
Epoch 2/5
60000/60000 [==============================] - 2s 38us/sample - loss: 0.3766 - accuracy: 0.8639
Epoch 3/5
60000/60000 [==============================] - 2s 38us/sample - loss: 0.3408 - accuracy: 0.8753
Epoch 4/5
60000/60000 [==============================] - 2s 37us/sample - loss: 0.3155 - accuracy: 0.8839
Epoch 5/5
60000/60000 [==============================] - 2s 38us/sample - loss: 0.2980 - accuracy: 0.8903
10000/10000 [==============================] - 0s 26us/sample - loss: 0.2803 - accuracy: 0.8673
```

**Code to reproduce the issue**

```python
import tensorflow as tf

mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
training_images = training_images / 255.0
test_images = test_images / 255.0
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(training_images, training_labels, epochs=5)

test_loss = model.evaluate(test_images, test_labels)
```

**Other info / logs**

Running this code in a Jupyter Notebook results in a performance penalty for the huge, unnecessary output.

**Comment by ymodak** [comment]
Perhaps you can use semi-verbose by setting ```verbose=2``` to avoid repeated logging of ```=```
[GitHub_Gist](https://colab.sandbox.google.com/gist/ymodak/da242ce544a5102fce8eddf002b9ef10/github_issue_32286.ipynb)
```python
test_loss = model.evaluate(test_images, test_labels, verbose=2
```

**Comment by Peque** [comment]
@ymodak Yeah, that is not a problem, I can set verbose to 0 as well, but I think it is a bug anyway. Note the `10000/1` in the progress bar, instead of `10000/10000`. I think that is unexpected. :wink:

**Comment by djshen** [comment]
same problem here
https://github.com/tensorflow/tensorflow/issues/32320#issuecomment-548883188

**Comment by jvishnuvardhan** [comment]
@Peque This has been resolved recently in 'tf-nightly` which is `2.1.0-dev20191108` that will be released in the future. I am closing this issue. Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/5ead8e4a4613f9bf58996093154d1290/untitled634.ipynb).

Please feel free to open the issue if it persists again. Thanks!

**Comment by warriorgiggles** [comment]
this issue still seems to still persist with the current tf-nightly - has anyone found a solution?

**Comment by jvishnuvardhan** [comment]
@warriorgiggles Can you please create a new issue with a simple standalone code to reproduce the issue? Thanks!
