### ISSUE TITLE
Environment variables PATH and LD_LIBRARY_PATH not being passed to Protobuf compiler

### ISSUE THREAD

**Issue by gbkedar** [tensorflow/tensorflow#3261]
With protobuf neither the PATH nor LD_LIBRARY_PATH are being passed and building tensorflow fails with:
```
(cd /home/gbkedar/.cache/bazel/_bazel_gbkedar/2cce0d25c048758b29b453d7b4e29b85/execroot/tensorflow && \
  exec env - \
  bazel-out/host/bin/external/protobuf/protoc '--cpp_out=bazel-out/local_linux-opt/genfiles/' -I. -Iexternal/protobuf/src -Ibazel-out/local_linux-opt/genfiles/external/protobuf/src tensorflow/core/example/example.proto tensorflow/core/example/example_parser_configuration.proto tensorflow/core/example/feature.proto tensorflow/core/framework/allocation_description.proto tensorflow/core/framework/attr_value.proto tensorflow/core/framework/cost_graph.proto tensorflow/core/framework/device_attributes.proto tensorflow/core/framework/function.proto tensorflow/core/framework/graph.proto tensorflow/core/framework/kernel_def.proto tensorflow/core/framework/log_memory.proto tensorflow/core/framework/op_def.proto tensorflow/core/framework/step_stats.proto tensorflow/core/framework/summary.proto tensorflow/core/framework/tensor.proto tensorflow/core/framework/tensor_description.proto tensorflow/core/framework/tensor_shape.proto tensorflow/core/framework/tensor_slice.proto tensorflow/core/framework/types.proto tensorflow/core/framework/variable.proto tensorflow/core/framework/versions.proto tensorflow/core/lib/core/error_codes.proto tensorflow/core/protobuf/config.proto tensorflow/core/protobuf/meta_graph.proto tensorflow/core/protobuf/named_tensor.proto tensorflow/core/protobuf/queue_runner.proto tensorflow/core/protobuf/saver.proto tensorflow/core/protobuf/tensorflow_server.proto tensorflow/core/util/event.proto tensorflow/core/util/memmapped_file_system.proto tensorflow/core/util/saved_tensor_slice.proto tensorflow/core/util/test_log.proto)
ERROR: /project/roysam/compiledLibs/tensorflow/tensorflow/core/BUILD:91:1: null failed: protoc failed: error executing command
  (cd /home/gbkedar/.cache/bazel/_bazel_gbkedar/2cce0d25c048758b29b453d7b4e29b85/execroot/tensorflow && \
  exec env - \
  bazel-out/host/bin/external/protobuf/protoc '--cpp_out=bazel-out/host/genfiles/' -I. -Iexternal/protobuf/src -Ibazel-out/host/genfiles/external/protobuf/src tensorflow/core/example/example.proto tensorflow/core/example/example_parser_configuration.proto tensorflow/core/example/feature.proto tensorflow/core/framework/allocation_description.proto tensorflow/core/framework/attr_value.proto tensorflow/core/framework/cost_graph.proto tensorflow/core/framework/device_attributes.proto tensorflow/core/framework/function.proto tensorflow/core/framework/graph.proto tensorflow/core/framework/kernel_def.proto tensorflow/core/framework/log_memory.proto tensorflow/core/framework/op_def.proto tensorflow/core/framework/step_stats.proto tensorflow/core/framework/summary.proto tensorflow/core/framework/tensor.proto tensorflow/core/framework/tensor_description.proto tensorflow/core/framework/tensor_shape.proto tensorflow/core/framework/tensor_slice.proto tensorflow/core/framework/types.proto tensorflow/core/framework/variable.proto tensorflow/core/framework/versions.proto tensorflow/core/lib/core/error_codes.proto tensorflow/core/protobuf/config.proto tensorflow/core/protobuf/meta_graph.proto tensorflow/core/protobuf/named_tensor.proto tensorflow/core/protobuf/queue_runner.proto tensorflow/core/protobuf/saver.proto tensorflow/core/protobuf/tensorflow_server.proto tensorflow/core/util/event.proto tensorflow/core/util/memmapped_file_system.proto tensorflow/core/util/saved_tensor_slice.proto tensorflow/core/util/test_log.proto): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/host/bin/external/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/external/protobuf/protoc)
bazel-out/host/bin/external/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by bazel-out/host/bin/external/protobuf/protoc)
bazel-out/host/bin/external/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bazel-out/host/bin/external/protobuf/protoc)
Target //tensorflow/cc:tutorials_example_trainer failed to build
```
Further, checking the dependencies of protoc shows that they are set correctly when it is compiled
```
ldd bazel-out/host/bin/external/protobuf/protoc
        linux-vdso.so.1 =>  (0x00007ffffadff000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b5195f33000)
        libstdc++.so.6 => /share/apps/gcc-4.9.2/lib64/libstdc++.so.6 (0x00002b5196150000)
        libgcc_s.so.1 => /share/apps/gcc-4.9.2/lib64/libgcc_s.so.1 (0x00002b5196463000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b5196679000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003e37c00000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b5196a0d000)
```

I have checked out and built the master of bazel. Previous to https://github.com/bazelbuild/bazel/commit/c9bc051f32b0d153110863e983749420200d000c other parts were being passed the PATH and not LD_LIBRARY_PATH. For example:
```
//third_party/gpus/cuda:cuda_check [action 'Executing genrule //third_party/gpus/cuda:cuda_check']
(cd /home/gbkedar/.cache/bazel/_bazel_gbkedar/2cce0d25c048758b29b453d7b4e29b85/execroot/tensorflow && \
  exec env - \
    PATH= ...... \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; OUTPUTDIR=`readlink -f bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/../../..`; cd `dirname third_party/gpus/cuda/cuda_config.sh`; OUTPUTDIR=$OUTPUTDIR ./cuda_config.sh --check;')
```
The commit adds LD_LIBRARY_PATH:
```
//third_party/gpus/cuda:cuda_check [action 'Executing genrule //third_party/gpus/cuda:cuda_check']
(cd /home/gbkedar/.cache/bazel/_bazel_gbkedar/2cce0d25c048758b29b453d7b4e29b85/execroot/tensorflow && \
  exec env - \
    LD_LIBRARY_PATH= ...... \
    PATH= ...... \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; OUTPUTDIR=`readlink -f bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/../../..`; cd `dirname third_party/gpus/cuda/cuda_config.sh`; OUTPUTDIR=$OUTPUTDIR ./cuda_config.sh --check;')
```
which solves some issues when gcc or python are not in the default path but not this one.

**Comment by gbkedar** [comment]
It looks like the macro tf_proto_library is defined here which is causing the error is defined [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/build_config.bzl).

**Comment by gbkedar** [comment]
It looks like the macro tf_proto_library which is causing the error  is defined [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/build_config.bzl).

**Comment by jmchen-g** [comment]
@martinwicke Could you take a look at this please?

**Comment by gbkedar** [comment]
Sorry, the close was a mistake

**Comment by martinwicke** [comment]
@damienmg is this something we can fix on our side or is that a problem in bazel?

**Comment by xsj0jsx** [comment]
I have sovled this problem by add `linker_flag: "-Wl,-rpath,you-local-gcc-lib-path"` to the `toolchain`section with `host_system_name: "local"` in the `third_party/gpus/crosstool/CROSSTOOL` file .

This problem is caused by `exec env -` ,which clear LD_LIBRARY_PATH, resulted protoc can't find you gcc lib

**Comment by damienmg** [comment]
@martinwicke @philwo recently added the LD_LIBRARY_PATH to the list of environment passed when using the default shell env (which the action might not, this is an option in genrule / skylark action). This should be fixed with Bazel at HEAD.

Also we have a more general principle approach to that, see http://www.bazel.io/docs/designs/2016/06/21/environment.html

So this is a problem in Bazel, and we fixed it but there might be some action to do when invoking protoc

**Comment by martinwicke** [comment]
Thanks @damienmg. I'll close this issue, and we should revisit it when the fix in bazel hits a release.

**Comment by greg1github** [comment]
Still not working for me.  I use bazel-0.4.0 and tensorflow-0.11.0.

I compiled bazel from the source, with CROSSTOOL modified so as to hard-code the library path

  linker_flag: "-Wl,-rpath,/home/sr1/greg.m/lib/gcc-4.9.4_built/lib64"

and this setup does have an effect on bazel itself, even when I clear env variables

env - ldd ~/bin/bazel
        linux-vdso.so.1 =>  (0x00007ffe8999e000)
        librt.so.1 => /lib64/librt.so.1 (0x000000347ee00000)
        libdl.so.2 => /lib64/libdl.so.2 (0x000000347e600000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x000000347e200000)
        **libstdc++.so.6** => /home/sr1/greg.m/lib/gcc-4.9.4_built/lib64/libstdc++.so.6 (0x00002ae1100c1000)
        libm.so.6 => /lib64/libm.so.6 (0x000000347ea00000)
        libgcc_s.so.1 => /home/sr1/greg.m/lib/gcc-4.9.4_built/lib64/libgcc_s.so.1 (0x00002ae1103d3000)
        libc.so.6 => /lib64/libc.so.6 (0x000000347de00000)
        /lib64/ld-linux-x86-64.so.2 (0x000000347d600000)

However, when I try to build tensorflow with that bazel binary, protoc complains about missing libraries

bazel build -c opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package
...
ERROR: /home/sr1/greg.m/lib/tensorflow-0.11.0/tensorflow/python/BUILD:1611:1: null failed: protoc failed: error executing command 
  (cd /scratch/greg.m/.cache/bazel/_bazel_greg.m/a9520ec1e3d4c7a317ca28043c7f63b1/execroot/tensorflow-0.11.0 && \
  exec env - \
  bazel-out/host/bin/external/protobuf/protoc '--python_out=bazel-out/local_linux-py3-opt/genfiles/' -I. -Iexternal/protobuf/python -Ibazel-out/local_linux-py3-opt/genfiles/external/protobuf/python tensorflow/python/training/checkpoint_state.proto): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

And I verified that the protoc indeed is missing the path to libstdc++.so.6 that we expect to see because of the linker_flag added to CROSSTOOL 

env - ldd bazel-out/host/bin/external/protobuf/protoc
bazel-out/host/bin/external/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by bazel-out/host/bin/external/protobuf/protoc)
bazel-out/host/bin/external/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by bazel-out/host/bin/external/protobuf/protoc)
bazel-out/host/bin/external/protobuf/protoc: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by bazel-out/host/bin/external/protobuf/protoc)
        linux-vdso.so.1 =>  (0x00007fffa0aa2000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ab8e7ec3000)
        **libstdc++.so.6** => /usr/lib64/libstdc++.so.6 (0x00002ab8e80e0000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002ab8e83e7000)
        libc.so.6 => /lib64/libc.so.6 (0x00002ab8e85fd000)
        /lib64/ld-linux-x86-64.so.2 (0x000000347d600000)
        libm.so.6 => /lib64/libm.so.6 (0x00002ab8e8991000)

**Comment by mukul1992** [comment]
I am also hitting the same issue where protoc complains about missing GLIBCXX_<versions> although more recent gcc (4.9.2) library path is added to LD_LIBRARY_PATH.
I am using bazel 0.4.1 for tensorflow 0.12.0-rc0 on CentOS 6.

**Comment by i3v** [comment]
I was able to overcome the `'GLIBCXX_3.4.20' not found` issue in a manner similar to what @xsj0jsx [suggested](https://github.com/tensorflow/tensorflow/issues/3261#issuecomment-234147379). You would probably need [these two lines](https://github.com/bazelbuild/bazel/issues/649#issuecomment-166710509), not one. However, you would probably have to [fix two more things](https://github.com/tensorflow/tensorflow/issues/110#issuecomment-265431453).

**Comment by yliu120** [comment]
> It looks like the macro tf_proto_library which is causing the error is defined here.

> Edit:
> The compiler is called from bazel-tensorflow/external/protobuf/protobuf.bzl
> There is a ctx.action call where we need to add env=ctx.configuration.default_shell_env to add the > paths. I haven't worked out where the file is created/downloaded.

@gbkedar 's comment is correct on this issue. Please read the PR I referenced above. In the meanwhile, there is an easy fix to this problem. Please read my protocol on building TensorFlow with a customized tool chain.

http://biophysics.med.jhmi.edu/~yliu120/tensorflow.html

(Search for configuration section) You can manually add the patch (same as my PR) after running ./configure
