### ISSUE TITLE
TensorBoard: gracefully handle deleted event files

### ISSUE THREAD

**Issue by akors** [tensorflow/tensorflow#3267]
Hi!

At the moment, TensorBoard at firstignores the deletion of folders and event files inside the log directory, and displays them as though they were there. Then at some later time (i can't tell what triggers it), it starts throwing exceptions, like

```
  File "bla/lib/python3.5/site-packages/tensorflow/python/platform/gfile.py", line 379, in ListDirectory
    files = os.listdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: 'bla/dataset-test/logs/watch/dbg/test'
```

However, sometimes a cleanup is required, and unused runs have to be deleted. This is not possible under the current version.

The workaround of restarting TensorBoard every time that a run is deleted is **very** unsatisfying, because loading a log directory with several (long) runs takes forever™.

Would it be possible to implement the handling of deleted session files and directories in TensorBoard?

**Comment by danmane** [comment]
This is fixed in the latest release.

**Comment by akors** [comment]
@danmane Is this head already pushed? I just tried with 8c10acb2039af47f3a2940281b3e056e9789a82d , and after I delete event files, I still get errors:

`ERROR:tensorflow:Unable to reload accumulator 'dbg_tcmalloc': [Errno 2] No such file or directory: '/fast/cavitylearn/dataset-test/logs/dbg_tcmalloc'
ERROR:tensorflow:Unable to reload accumulator 'dbg_tcmalloc/test': [Errno 2] No such file or directory: '/fast/cavitylearn/dataset-test/logs/dbg_tcmalloc/test'`

And the run still stays present in TensorBoard.

To put short, the behaviour is just like before. Is this intended? 

What I meant is that instead of showing errors when event files disappear, TensorBoard should drop (or mark as invalid) the runs that have disappeared.

**Comment by akors** [comment]
@danmane any update on this?

**Comment by drpngx** [comment]
Since the code has changed substantially since this issue was opened, it might be obsolete. Feel free to open a new github issue if the problem still persists in recent versions.

**Comment by akors** [comment]
```
WARNING:tensorflow:Deleting accumulator 'run1/test'
WARNING:tensorflow:Deleting accumulator 'run1'
WARNING:tensorflow:Deleting accumulator 'run2/test'
WARNING:tensorflow:Deleting accumulator 'run2'
```
Wonderful! This is indeed fixed. Thanks for the great work!
