### ISSUE TITLE
TF2 Stubs for intellisense; current way tf2 imports modules does not support intellisense

### ISSUE THREAD

**Issue by RensDimmendaal** [tensorflow/tensorflow#32982]
**System information**
- TensorFlow version (you are using): 2.0.0
- Are you willing to contribute it (Yes/No): Happy to help out

**Describe the feature and the current behavior/state.**
Intellisense does not work because of the way tf2 has import statements.

![image](https://user-images.githubusercontent.com/9828683/66023599-f7f83180-e4f1-11e9-83d0-fe931c4486f6.png)

**Will this change the current api? How?**

Add stubs.

**Who will benefit with this feature?**

Vscode users

**Any Other info.**

Discussed here: 
https://github.com/microsoft/python-language-server/issues/818#issuecomment-537143000

**Comment by gadagashwini** [comment]
@RensDimmendaal,
Could you please elaborate the issue. Thanks!

**Comment by RensDimmendaal** [comment]
Sure :-) Please note that I'm not an expert on this issue. I'm a tensorflow user who is inconvenienced by the issue and I thought I'd pass it along from the vscode thread to tensorflow when I saw that it was not something vscode could deal with by itself.

The end goal is intellisense support for tensorflow in the popular ide VSCode.
I believe the reason TF2 does not work with intellisense is that it's imports are "indirect" such as in the tensorflow.data.__init__. 

```
""`tf.data.Dataset` API for input pipelines.
See [Importing Data](https://tensorflow.org/guide/data) for an overview.
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# pylint: disable=unused-import
from tensorflow.python.data import experimental
from tensorflow.python.data.ops.dataset_ops import Dataset
from tensorflow.python.data.ops.dataset_ops import make_initializable_iterator
from tensorflow.python.data.ops.dataset_ops import make_one_shot_iterator
from tensorflow.python.data.ops.iterator_ops import Iterator
from tensorflow.python.data.ops.readers import FixedLengthRecordDataset
from tensorflow.python.data.ops.readers import TextLineDataset
from tensorflow.python.data.ops.readers import TFRecordDataset
# pylint: enable=unused-import
```

As discsussed in the vs code thread (https://github.com/microsoft/python-language-server/issues/818#issuecomment-537143000) one way around this would be by using stubs.

I guess this would be similar to pyspark stubs: https://pypi.org/project/pyspark-stubs/ and can be created with mypy's stubgen https://github.com/python/mypy/blob/master/mypy/stubgen.py.

**Comment by thomasjo** [comment]
Also see https://github.com/microsoft/python-language-server/issues/818#issuecomment-511495313, in which @alextp specifically asks @pkch about adding stubs for TF.

Note that this issue affects does not only affect VS Code, but also PyCharm and Atom. I'm guessing it'll also affect most Vim and Emacs plugins providing Python intellisense functionality using static type analysis.

**Comment by aKzenT** [comment]
It is extremely frustrating discovering the new Tensorflow 2.0 APIs without proper intellisense support in my IDEs. Please fix this!

**Comment by zhen8838** [comment]
Tensorflow 1.15 has the same problem.

**Comment by Mulns** [comment]
I've tried a simple solution for current situation (tf: 2.0, vscode:1.39.1) : 

1. Go to dir `/python3/site-packages/` and change the name of `/tensorflow/` to `/tensorflow_back`, then change the name of  `/tensorflow_core/` to `/tensorflow/` (only use core api)

2. Go to file `/tensorflow/__init__.py` (which was in `/tensorflow_core/` ), add the following codes:
`from .python.keras.api._v2 import keras`
`from tensorflow_estimator.python.estimator.api._v2 import estimator`

![results](https://user-images.githubusercontent.com/36128896/66695234-a457c600-ecf1-11e9-8d00-128625851c0b.jpg)

And this works!

**Comment by aKzenT** [comment]
@Mulns Thanks for this solution! I found a way to use your solution without having to modify the "site-packages" folder.

Just copy the "tensorflow_core" folder to another directory (e.g. C:\stubs) and then rename it there to "tensorflow" (C:\stubs\tensorflow). Adjust the __init__.py file as described above.

In your Visual Studio Code open your user settings.json and add the following setting:
`    "python.autoComplete.extraPaths": ["C:\\stubs"],
`

VS Code will use the specified path for auto-completion while your application will run with the original unmodified library.

**Comment by coolzhao** [comment]
@aKzenT Thanks for the solution, it's better to let the original TensorFlow remain untouched. But actually it's not necessary to add those two lines in the `__init__.py` if you add an autoComplete.extraPath in setting.json. I have tried that with the `__init__.py` unchanged, and it works too.

And I think what confuses IntelliSense is that when we `import tensorflow`(the proxy), it leads to tensorflow_core(the real one) in `./tensorflow/__init__.py`, but when you look into the `./tensorflow_core/__init__.py`, it goes back to the proxy name tensorflow. Which I think may confuse the IntelliSense.

So after we add an autoComplete.extraPath with a real tensorflow(the core but named as tensorflow), the IntelliSense can finally figure out the path to search.

**Comment by gadagashwini** [comment]
@RensDimmendaal, Looks like the issue is resolved. Can you please let us know if you are happy to close if no issue persists. Thanks!

**Comment by thomasjo** [comment]
@gadagashwini This issue is in no way resolved. 

The proposed workarounds listed above are only temporary hacks, nothing else. The underlying problem either needs to be resolved by changing/removing the dynamic module loading bits introduced in TF 2.0, or someone (arguably the TF team) needs to provide us with type stubs ([PEP 484](https://www.python.org/dev/peps/pep-0484/)).

**Comment by Colonel-C** [comment]
@coolzhao @aKzenT Thanks for your solution. 

@gadagashwini 
The issue should still remain open as this is a problem that everyone is encountering. Tensorflow intellisense is not working as it should.

**Comment by komodovaran** [comment]
@RensDimmendaal maybe the title should be changed, because as @thomasjo it affects other editors, including PyCharm. The above hack by @Mulns will likewise works for all editors.

**Comment by Flamefire** [comment]
@aKzenT I found an even better solution: A symlink which keeps everything up to date:

```
mkdir ~/.local/virtual-site-packages
ln -s ~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/tensorflow_core ~/.local/virtual-site-packages/tensorflow
```
Then use 
```
 "python.autoComplete.extraPaths": [
        "/home/<USER>/.local/virtual-site-packages"
    ],
```

**Comment by Crossady** [comment]
> @aKzenT I found an even better solution: A symlink which keeps everything up to date:
> 
> ```
> mkdir ~/.local/virtual-site-packages
> ln -s ~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/tensorflow_core ~/.local/virtual-site-packages/tensorflow
> ```
> 
> Then use
> 
> ```
>  "python.autoComplete.extraPaths": [
>         "/home/<USER>/.local/virtual-site-packages"
>     ],
> ```

This workaround also works for tensorflow 1.15, thank all you guys

**Comment by minhduc0711** [comment]
> @aKzenT I found an even better solution: A symlink which keeps everything up to date:
> 
> ```
> mkdir ~/.local/virtual-site-packages
> ln -s ~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/tensorflow_core ~/.local/virtual-site-packages/tensorflow
> ```
> 
> Then use
> 
> ```
>  "python.autoComplete.extraPaths": [
>         "/home/<USER>/.local/virtual-site-packages"
>     ],
> ```

Do we need to change the __init__.py in tensorflow_core as well?

**Comment by minhduc0711** [comment]
> @aKzenT I found an even better solution: A symlink which keeps everything up to date:
> 
> ```
> mkdir ~/.local/virtual-site-packages
> ln -s ~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/tensorflow_core ~/.local/virtual-site-packages/tensorflow
> ```
> 
> Then use
> 
> ```
>  "python.autoComplete.extraPaths": [
>         "/home/<USER>/.local/virtual-site-packages"
>     ],
> ```

This is not working for me on Ubuntu 18.04

**Comment by Flamefire** [comment]
Did you adjust your path to tensorflow in the `ln` command? This is not a C&P solution but needs to be adapted

**Comment by minhduc0711** [comment]
> Did you adjust your path to tensorflow in the `ln` command? This is not a C&P solution but needs to be adapted

I only followed your steps. What else need to be adjust?

**Comment by saamkhya** [comment]
> > @aKzenT I found an even better solution: A symlink which keeps everything up to date:
> > ```
> > mkdir ~/.local/virtual-site-packages
> > ln -s ~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/tensorflow_core ~/.local/virtual-site-packages/tensorflow
> > ```
> > 
> > 
> > Then use
> > ```
> >  "python.autoComplete.extraPaths": [
> >         "/home/<USER>/.local/virtual-site-packages"
> >     ],
> > ```
> 
> This workaround also works for tensorflow 1.15, thank all you guys

This is not working on tensorflow 2.0.0 and keras 2.2.4-tf. I installed tensorflow 2 using conda and created a symbolic link with the tensorflow_core folder located under my environment, and changed the extraPath in vscode. However, after importing "from tensorflow import keras" when I am trying to do keras.datasets. I don't see any autocompletion or suggestion, as well as for other keras modules such as keras.layers.

**Comment by pnetz** [comment]
I just changed the imports to their source location at tensorflow_core. Looks stable to use intra-release and can be switch after either Tensorflow or Code improve the situation?

`from tensorflow_core.python.keras.api import keras`

**Comment by Flamefire** [comment]
> from tensorflow_core.python.keras.api import keras

This won't work. At some point you get double-imports and crashes because TF modules (and others) `import tensorflow`, which aliases `tensorflow_core` without Python realizing -> double load -> boom

**Comment by xggIoU** [comment]
PyCharm 2019.3 EAP version worked! 
https://www.jetbrains.com/pycharm/nextversion/?_ga=2.221720863.623821984.1573808626-1607002874.1573808626

**Comment by pnetz** [comment]
> > from tensorflow_core.python.keras.api import keras
> 
> This won't work. At some point you get double-imports and crashes because TF modules (and others) `import tensorflow`, which aliases `tensorflow_core` without Python realizing -> double load -> boom

Currently I am just using tensorflow.keras and tensorflow root modules which work fine, but I will keep this in mind. Good to know, but I would like to avoid the fallback since it makes sharing the conda environment impossible without tweaking post-install.

**Comment by Mpic** [comment]
> 
> 
> > Did you adjust your path to tensorflow in the `ln` command? This is not a C&P solution but needs to be adapted
> 
> I only followed your steps. What else need to be adjust?
> 
> **Update**: Oh it doesn't work because my import were like this: `from tensorflow.keras import layers`. The example from above works just fine.

Could you please elaborate on what you use ? 

Is it 
```python
from tensorflow import keras
input = keras.layers.Input(...)
```
without the possibility to do `from tensorflow.keras import layers` to just use 
```python
from tensorflow import keras
from tensorflow.keras import layers
input = layers.Input(...)
```
? (Beginner here, just tipping my toe in grasping Python import mechanisms)

**Comment by ejar-ArriagaAsociados** [comment]
Any update?

**Comment by ejarkm** [comment]
Any updates?

**Comment by annarev** [comment]
Many issues have already been fixed before.
After this commit, everything should be fixed (it removed tensorflow_core/ directory, now we just have tensorflow/ directory in the pip package so structure is simpler):
https://github.com/tensorflow/tensorflow/commit/5c00e793c61860bbf26778cd4704313e867645be#diff-62ec18ff8bdd93adaff55160f27a7e09

Re-open this or a new bug if something still doesn't work in the new nightlies.

**Comment by kavinvin** [comment]
@annarev I've tried Tensorflow 2.2.0rc0 which includes 5c00e793c61860bbf26778cd4704313e867645be but Intellisense in VS Code still doesn't work, while 1.13.0 works perfectly fine.

**Comment by annarev** [comment]
Can you give an example of an import you are using that doesn't work?

**Comment by kavinvin** [comment]
This import cannot be resolved.
`from tensorflow.keras.utils import multi_gpu_model, plot_model, to_categorical`

By the way,
`import tensorflow as tf` works
`from tensorflow import keras` works
`from tensorflow.keras import losses` doesn't work for me. It can't find information of `losses` object.

**Comment by annarev** [comment]
The top one `from tensorflow.keras.utils import multi_gpu_model, plot_model, to_categorical` is a deeper import that indeed doesn't work now (it also doesn't work for me in 1.13.0).

Which VS Code version are you using? I tested `from tensorflow.keras import losses` in two versions of VS Code (1.14.1 and 1.43.0). It works in both for 2.2.0rc0 but not 1.13.0.

**Comment by kavinvin** [comment]
@annarev I'm using VS Code 1.43.1 on macOS. It's somehow working now in a very weird way.

If I have this single import in a file
```python
import tensorflow as tf

# Try to type tf.keras.layers.Conv1D here
```
I can use `tf.keras.` auto-suggestion normally.

But if I add a line of keras import from tensorflow
```python
import tensorflow as tf
from tensorflow import keras

# Try to type tf.keras.layers.Conv1D here
```
I can't use `tf.keras.` auto-suggestion anymore. I've tested on multiple conda environments which installed Tensorflow 2.2.0rc0 and had the same result.

Another thing is that I can't find suggestions for anything after `import tensorflow.keras.` statement.

**Comment by redeaglekiller** [comment]
hi I think i solved the problem on my pc. 

So it'll sound wired but..I think Windows defender was the problem.

I downloaded pycharm because I could not solve this problem, and I am intellisense addicted (lazy).
So the first time I started pycharm the program warns me that Windows defender could be a performance issue, and It asks to add the pycharm folders to the exclusion list. So I added the folders listed in pycharm and also the python folder too while I was at it.

Then I tried to open vs code again and....now it works, no errors at all, Intellisense working, pylint working.

Could someone try this out? Just put the folder where python is installed in the Windows Defender exclude list as folder.

But I can't figure out if this is the solution because the problem is also on macos

**Comment by redeaglekiller** [comment]
Nevermind....I installed the nightly version of tensorflow and It solved...

pip3 install tf-nightly

**Comment by Jaskaranbir** [comment]
In meantime, [Kite](https://kite.com/integrations/vs-code/) extension has been working quite well for me (its an AI-autocomplete extension, but the one that actually works and isnt 80% backspacing).

![image](https://user-images.githubusercontent.com/12961957/77613014-07d05b80-6f00-11ea-8022-ba0bab0fedc5.png)

Still get errors on actual imports, of course.

**Comment by mihaimaruseac** [comment]
In this case, can we close the issue as it has been solved?

**Comment by goldiegadde** [comment]
@redeaglekiller were you able to test with 2.2.0-rc3 and see if your issue is resolved ?

**Comment by RensDimmendaal** [comment]
It works in `tf-nightly`, closing this issue.

![image](https://user-images.githubusercontent.com/9828683/80068282-a7086300-853f-11ea-8352-37d61630b738.png)

**Comment by realdanielbyrne** [comment]
Interesting how things seem to get resolved without actual testing being involved.   Intellisense is still broken on vscode, 1.45.1, tf-nightly-2.3.0.dev20200516.

Intellisense error : {
	"resource": "./code/encoder_mlp.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "unresolved-import",
	"severity": 4,
	"message": "unresolved import 'tensorflow.keras'",
	"source": "Python",
	"startLineNumber": 9,
	"startColumn": 6,
	"endLineNumber": 9,
	"endColumn": 22
}

**Comment by mihaimaruseac** [comment]
@realdanielbyrne that looks like a recent breakage. Please open a new issue.

**Comment by tkkcc** [comment]
I am using `deoplete-jedi` and `tensorflow=1.15.0`. Changing `PYTHONPATH` works.
```sh
mkdir $HOME/.local/share/jedi-extra
ln -s $HOME/miniconda3/lib/python3.7/site-packages/tensorflow_core $HOME/.local/share/jedi-extra/tensorflow
export PYTHONPATH=$HOME/.local/share/jedi-extra
```

**Comment by tkkcc** [comment]
I am using `deoplete-jedi` and `tensorflow=1.15.0`. Changing `PYTHONPATH` works.
```
mkdir $HOME/.local/share/jedi-extra
ln -s $HOME/miniconda3/lib/python3.7/site-packages/tensorflow_core $HOME/.local/share/jedi-extra/tensorflow
export PYTHONPATH=$HOME/.local/share/jedi-extra
```
