### ISSUE TITLE
Cannot use dict base datasets with keras.Model.fit.

### ISSUE THREAD

**Issue by npuichigo** [tensorflow/tensorflow#33245]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.4
- CUDA/cuDNN version: 10.1
- GPU model and memory: 7.6.2

In order to make both dataset and keras model have good structures, I create a dataset and a vanilla model like this.
```python
# dataset is something like <BatchDataset shapes: ({input: (None, 100)}, {output: (None, 10)}), types: ({input: tf.float32}, {output: tf.float32})>

# subscale model is something like
class VanillaModel(Model):

  def __init__(self, num_units, **kwargs):
    super(VanillaModel, self).__init__(**kwargs)
    self.num_units = num_units

    # One linear projection layer.
    self.dense_proj = tf.keras.layers.Dense(num_units, activation='relu')

  def call(self, features):
    """Forward pass."""
    output = self.dense_proj(features['input'])
    return {
        'output': output
    }
```

When I use the dict based dataset (from tfds) with keras.Model.fit, the first call will cause expection as 
```python
# Compile model using dict with same keys.
model.compile('adam', {'output': 'mse'})

# The errors
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_utils.py", line 1248, in cast_if_floating_dtype_and_mismatch
    if target.dtype != out.dtype:
AttributeError: 'str' object has no attribute 'dtype'
```

I checked the code and found that, when dict is passed, iterating through `zip(targets, outputs)` will just get the keys of the dict, so the string keys have no dtyle.
(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_utils.py#L1246)
![image](https://user-images.githubusercontent.com/11533479/66652073-59916c00-ec67-11e9-8974-eda50bf98e18.png)

So how can I use dict based dataset and model with keras.Model.fit?

**Comment by gadagashwini** [comment]
@npuichigo, Will it be possible to provide the standalone code to replicate the reported issue. Thanks!

**Comment by gadagashwini** [comment]
@npuichigo, Any update on code. Thanks!

**Comment by npuichigo** [comment]
The problem is that, if our model and dataset return dictionaries, how can we compile and fit the model.

```python
import tensorflow as tf
import numpy as np

class VanillaModel(tf.keras.Model):

  def __init__(self, num_units, **kwargs):
    super(VanillaModel, self).__init__(**kwargs)
    self.num_units = num_units

    # One linear projection layer.
    self.dense_proj1 = tf.keras.layers.Dense(num_units, activation='relu')
    self.dense_proj2 = tf.keras.layers.Dense(num_units, activation='relu')

  def call(self, features):
    """Forward pass."""
    proj1_output = self.dense_proj1(features['input'])
    proj2_output = self.dense_proj2(features['input'])
    return {
        'proj1_output': proj1_output,
        'proj2_output': proj2_output
    }

input_tensor = np.random.normal(size=(50, 32)).astype(np.float32)
output_tensor1 = np.random.normal(size=(50, 16)).astype(np.float32)
output_tensor2 = np.random.normal(size=(50, 16)).astype(np.float32)

dataset = tf.data.Dataset.from_tensor_slices(({'input': input_tensor}, {'proj1_output': output_tensor1, 'proj2_output': output_tensor2}))
model = VanillaModel(16)

model.compile('adam', {'proj1_output': 'mse', 'proj2_output': 'mae'})
model.fit(dataset)
```

**Comment by npuichigo** [comment]
any updates?

**Comment by nareshr8** [comment]
I am facing the same issue when I am retrieving data from **TFRecords**.

**Comment by pavithrasv** [comment]
Assigning to Tom who will be working on this as part of ideal fit/compile change.

**Comment by omalleyt12** [comment]
For a quick workaround, note the Keras expects Datasets passed to `fit` to be of the form `(features, labels` or `(features, labels, sample_weights)`

Here's an example of grabbing MNIST from `tensorflow_datasets` and formatting it in the way Keras expects:

```python
import tensorflow as tf
import tensorflow_datasets as tfds

def convert_dataset(item):
    """Puts the mnist dataset in the format Keras expects, (features, labels)."""
    image = item['image']
    label = item['label']
    image = tf.dtypes.cast(image, 'float32') / 255.
    return image, label

mnist_data = tfds.load('mnist')
mnist_train, mnist_test = mnist_data['train'], mnist_data['test']
mnist_train = mnist_train.map(convert_dataset).shuffle(1000).batch(100).repeat()
mnist_test = mnist_test.map(convert_dataset).batch(100)

model.fit(mnist_train, epochs=10, validation_data=mnist_test)
```

**Comment by npuichigo** [comment]
@omalleyt12 That's true. But sometimes we have complicated models with multiple inputs and outputs, so it's more elegant if we can use dict based model and dataset.

**Comment by omalleyt12** [comment]
@npuichigo For those Models, each of `features` and `labels` can be a dictionary:

```python
ds = tf.data.Dataset.from_tensor_slices(
  ({'my_feature_1': ..., 'my_feature_2': ...}, {'my_label_1': ..., 'my_label_2': ...}))
```

**Comment by npuichigo** [comment]
@omalleyt12 So it looks like my example.
```
dataset = tf.data.Dataset.from_tensor_slices(({'input': input_tensor}, {'proj1_output': output_tensor1, 'proj2_output': output_tensor2}))
```
But it seems that keras restrict the input and output names to something like input_1, input_2, output_1 and so on. Can you give a correct example?

**Comment by nareshr8** [comment]
If I use ` tf.feature_column.categorical_column_with_vocabulary_list` I wasable to specify the column name in keras. But I faced the issue when I called `model_to_estimator` API to convert back to tensorflow model as the converted model was expecting inputs like `input1,input2,...` as you mentioned

**Comment by SunYanCN** [comment]
same problem

**Comment by Silmeria112** [comment]
I faced same issue. My workaround is not using the subclass way.  When I change to tf.keras.Model(inputs=...,outputs=...), the problem solved.

In fact I found there's quite some limitation on subclass model, and there's no good guidline about how to avoid these limitations.Hope tensorflow can improve the usability of subclass model. I really prefer subclass model than sequence model becuase that's the way how we can easily debug the model with eager.

**Comment by omalleyt12** [comment]
Thanks for the issue all! This is now fixed in the latest tf-nightlym you can use any arbitrary nested structure of data with subclassed Models.

Code below works (note I had to add a call to `dataset.batch`, this is needed to create batches of data when using `from_tensor_slices`):

```python
class VanillaModel(tf.keras.Model):

  def __init__(self, num_units, **kwargs):
    super(VanillaModel, self).__init__(**kwargs)
    self.num_units = num_units

    # One linear projection layer.
    self.dense_proj1 = tf.keras.layers.Dense(num_units, activation='relu')
    self.dense_proj2 = tf.keras.layers.Dense(num_units, activation='relu')

  def call(self, features):
    """Forward pass."""
    proj1_output = self.dense_proj1(features['input'])
    proj2_output = self.dense_proj2(features['input'])
    return {
        'proj1_output': proj1_output,
        'proj2_output': proj2_output
    }

input_tensor = np.random.normal(size=(50, 32)).astype(np.float32)
output_tensor1 = np.random.normal(size=(50, 16)).astype(np.float32)
output_tensor2 = np.random.normal(size=(50, 16)).astype(np.float32)

dataset = tf.data.Dataset.from_tensor_slices(({'input': input_tensor}, {'proj1_output': output_tensor1, 'proj2_output': output_tensor2}))
dataset = dataset.batch(10)  # This needs to be called to create batches of data.
model = VanillaModel(16)

model.compile('adam', {'proj1_output': 'mse', 'proj2_output': 'mae'})
model.fit(dataset)
```

**Comment by jgmakin** [comment]
@omalleyt12 
When eager execution is disabled, the code snippet you posted above still fails under version `2.2.0-dev20200501` with the same error (`AttributeError: 'str' object has no attribute 'dtype'`).

**Comment by omalleyt12** [comment]
@jgmakin Disabling eager execution is a v1 compatibility feature, in general we're only making critical security or regression fixes in the v1 compatibility code for tf.keras. I'd recommend migrating to the TF2 style

**Comment by jgmakin** [comment]
Ah, ok, thanks.  I tend to disable eager execution under the assumption that this improves performance, but perhaps that isn't the case anymore?

**Comment by omalleyt12** [comment]
@jgmakin When using `Model.fit`, everything runs inside a graph anyway (a `tf.function` graph) so performance should be good

For more, check out [this guide](https://www.tensorflow.org/guide/function)

**Comment by darwinharianto** [comment]
Hello, is there any way to do this too for validation_data?
I can't get it work for validation after every epoch end
