### ISSUE TITLE
LEAKY_RELU not supported in INT8 quantization

### ISSUE THREAD

**Issue by wuhy08** [tensorflow/tensorflow#33397]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.0

**Provide the text output from tflite_convert**

```
<ipython-input-54-6f97bfc97449> in <module>
----> 1 workflow(False, 10, 'int8', True, True)

<ipython-input-53-3889d2128b41> in workflow(dw, n_conv, dtype, v1, leaky)
     11     model.save(keras_file_name)
     12     if v1:
---> 13         tflite_model = convert2tflitev1(keras_file_name, qmode=dtype)
     14     else:
     15         tflite_model = convert2tflite(model, qmode=dtype)

<ipython-input-27-637084f295d5> in convert2tflitev1(model_file, qmode)
     19     elif qmode == 'float32':
     20         pass
---> 21     tflite_model = converter.convert()
     22 
     23     return tflite_model

~/miniconda3/envs/tf2-n-pytorch/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py in convert(self)
    991     if self._is_calibration_quantize():
    992       result = self._calibrate_quantize_model(result, inference_input_type,
--> 993                                               inference_output_type)
    994 
    995     return result

~/miniconda3/envs/tf2-n-pytorch/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py in _calibrate_quantize_model(self, result, inference_input_type, inference_output_type)
    237     return calibrate_quantize.calibrate_and_quantize(
    238         self.representative_dataset.input_gen, inference_input_type,
--> 239         inference_output_type, allow_float)
    240 
    241   def _get_base_converter_args(self):

~/miniconda3/envs/tf2-n-pytorch/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/calibrator.py in calibrate_and_quantize(self, dataset_gen, input_type, output_type, allow_float)
     76     return self._calibrator.QuantizeModel(
     77         np.dtype(input_type.as_numpy_dtype()).num,
---> 78         np.dtype(output_type.as_numpy_dtype()).num, allow_float)

~/miniconda3/envs/tf2-n-pytorch/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py in QuantizeModel(self, input_py_type, output_py_type, allow_float)
    113 
    114     def QuantizeModel(self, input_py_type, output_py_type, allow_float):
--> 115         return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, input_py_type, output_py_type, allow_float)
    116 CalibrationWrapper_swigregister = _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_swigregister
    117 CalibrationWrapper_swigregister(CalibrationWrapper)

RuntimeError: Quantization not yet supported for op: LEAKY_RELU
```

Also, please include a link to a GraphDef or the model if possible.

Model definition
```
def build_lrelu_model(n_layers):
    layer_list = []
    for idx in range(n_layers):
        conv_name = f'conv{idx}'
        if idx == 0:
            conv = layers.Conv2D(filters=32, 
                                 kernel_size=3, 
                                 padding='same', 
                                 name=conv_name, 
                                 input_shape=(28, 28, 3))
        else:
            conv = layers.Conv2D(filters=32, 
                                 kernel_size=3, 
                                 padding='same', 
                                 name=conv_name)
        bn = layers.BatchNormalization(name=f'bn{idx}')
        activation = layers.LeakyReLU(alpha=0.1, name=f'lrelu{idx}')
        layer_list.extend([conv, bn, activation])
    model = tf.keras.models.Sequential(layer_list)
    model.summary()
    return model
```

Conversion options:

```
        converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file(model_file)
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.uint8
        converter.inference_output_type = tf.uint8
```

**Any other info / logs**

I saw there were some PR about the implementation of Leaky_ReLU in tflite and quantization. But I still cannot get it to work. 

Ref PR: https://github.com/tensorflow/tensorflow/pull/27061

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by wuhy08** [comment]
BTW, I am not using `tflite_convert.py`

I am using `TFLiteConverter`, as shown in the code snippet above.

**Comment by wuhy08** [comment]
I am not sure if I am looking at the right place.

But the error might be thrown from here: https://github.com/tensorflow/tensorflow/blob/265126ca309d9e9502ab072f033308192d1367b0/tensorflow/lite/tools/optimize/quantize_model.cc#L590

which calls `operator_property.cc` ([link](https://github.com/tensorflow/tensorflow/blob/d08bf910b3ea5d8895a07553379436ad543f2da7/tensorflow/lite/tools/optimize/operator_property.cc)), where LEAKY_RELU and RESIZE_NEAREST_NEIGHBOUR are not defined.

**Comment by wuhy08** [comment]
Fixed in https://github.com/tensorflow/tensorflow/pull/36876

**Comment by cjtang** [comment]
Hi @wuhy08 

After adding Leaky_Relu into operator property, I can generate the INT8 model which include Leaky_Relu . But the int8 implementation of Leaky_Relu is still missing, right? When I called invoked() tflite model, it will return fail. Did you meet the same problem?

Error detail:
ValueError: Didn't find op for builtin opcode 'LEAKY_RELU' version '2'
Registration failed.

Thanks
Chunjue

**Comment by wuhy08** [comment]
Hi @cjtang 

There was a PR about Leaky_RELU_INT8 a while ago (https://github.com/tensorflow/tensorflow/pull/27061). I believe that part of code was never touched since nobody successfully quantized a Leaky_RELU op. Let me investigate a little.

**Comment by wuhy08** [comment]
It looks the error comes from this line:

https://github.com/tensorflow/tensorflow/blob/3a8c575c4efe57560f36670ddc028f6fc889060a/tensorflow/lite/core/api/op_resolver.cc#L41 

Will continue to investigate.

**Comment by wuhy08** [comment]
A PR is created for this issue: https://github.com/tensorflow/tensorflow/pull/37279. Will wait for approval.

**Comment by cjtang** [comment]
Great, I also added my version of INT8 Leaky_RELU implementation, but the result is always not good. Now I know that is because model doesn't restrict the same scale for input and output. Thank you for pointing that out. Let's wait for approval.

**Comment by wuhy08** [comment]
@cjtang 

The PR has just been merged. Expect a few days before it is in tf-nightly.

Thanks.
