### ISSUE TITLE
Tensorflow eager execution not working with tf.math.unsorted_segment_max, Gradient output is null

### ISSUE THREAD

**Issue by racinmat** [tensorflow/tensorflow#33425]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, Professional Edition
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary, installed using conda
- TensorFlow version (use command below): unknown, 1.14.0
- Python version: 3.7.3
- CUDA/cuDNN version: 10.0, 7.6
- GPU model and memory: T1000, 4GB VRAM

**Describe the current behavior**
When using tf.math.unsorted_segment_max with Tensorflow eager execution and Gradient Tape, the source code (see below) produces following error:
```
Traceback (most recent call last):
  File "C:/Projects/iotmap/py/segmented_max_error.py", line 80, in <module>
    grads = tape.gradient(loss_value, model.trainable_weights)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\backprop.py", line 980, in gradient
    unconnected_gradients=unconnected_gradients)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\imperative_grad.py", line 76, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\eager\backprop.py", line 137, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py", line 349, in _UnsortedSegmentMaxGrad
    return _UnsortedSegmentMinOrMaxGrad(op, grad)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py", line 326, in _UnsortedSegmentMinOrMaxGrad
    _GatherDropNegatives(op.outputs[0], op.inputs[1])
TypeError: 'NoneType' object is not subscriptable
```
Operations tf.math.segment_max, tf.math.segment_mean and tf.math.unsorted_segment_mean are working ok, though. 
I need the unsorted version because in more complex code bases, I a using several segmented aggregations and concatenating them, so I need to have fixed sizes.

**Describe the expected behavior**
It should work without throwing error.

**Code to reproduce the issue**
The code is here:
https://gist.github.com/racinmat/9a95cac7db36d5f0b6b33e9c35678ca2

**Other info / logs**
Exception thrown is mentioned above.

**Comment by ravikyram** [comment]
@racinmat 
I tried reproducing the issue with TF 1.14 on colab. However i am seeing the different error.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/2f6897da2b30cbaba0bdd43ec9a84aa3/untitled279.ipynb). Thanks!

**Comment by racinmat** [comment]
Yes, my bad, it is fixed now in the gist and produces the abovementioned error.

**Comment by ravikyram** [comment]
I have tried on colab with TF 1.14,1.15.0-rc3 and was able to reproduce the issue
Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/c69ad2af68dbb3ff0747b0d4ed0e7df4/untitled279.ipynb#scrollTo=YVFBL130Y2w7). Thanks!

**Comment by racinmat** [comment]
Just a small question, should this still have the awaiting response label?

**Comment by racinmat** [comment]
I see the issue is fixed in master, will there be a 1.X version with the fix released sometimes?

**Comment by peastman** [comment]
I'm seeing this same problem in TensorFlow 2.1.  My model uses `tf.math.unsorted_segment_max()`.  When I call `tape.gradient()` in eager mode I get the error

```
  File "/Users/peastman/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 1014, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/Users/peastman/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/imperative_grad.py", line 76, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/Users/peastman/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/eager/backprop.py", line 138, in _gradient_function
    return grad_fn(mock_op, *out_grads)
  File "/Users/peastman/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py", line 455, in _UnsortedSegmentMaxGrad
    return _UnsortedSegmentMinOrMaxGrad(op, grad)
  File "/Users/peastman/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py", line 432, in _UnsortedSegmentMinOrMaxGrad
    _GatherDropNegatives(op.outputs[0], op.inputs[1])
TypeError: 'NoneType' object is not subscriptable
```

Which versions is this supposed to be fixed in?

**Comment by racinmat** [comment]
The issue is still not resolved, @ravikyram  why has it been closed? The bug is still there.

**Comment by peastman** [comment]
Also, in TensorFlow 2.1 it appears this is no longer restricted to eager mode.  Even if I wrap the calculation in `tf.function` it still fails.  Can someone reopen this so it will get fixed?

**Comment by alextp** [comment]
Actually I cannot reproduce this against nightly TF, so I think it has been fixed since. Sorry for the noise.

**Comment by kyzhouhzau** [comment]
@ravikyram This problem still happened in tensorflow-gpu==2.0.0. But, it's ok in tensorflow-gpu==2.1.0.
