### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by soroush** [tensorflow/tensorflow#33528]
Hi

Following URL seems to be down:

https://mirror.bazel.build/github.com/pybind/pybind11/archive/v2.3.0.tar.gz

Bazel uses that to download pybind11 and for some unknown reason fallback link (https://github.com/pybind/pybind11/archive/v2.3.0.tar.gz) is never being used as an alternative. (Is that a fallback btw?)

Build logs:

```
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (192 packages loaded, 2655 targets configured)                              
INFO: Call stack for the definition of repository 'pybind11' which is a tf_http_archive (rule definition at /root/tensorflow-1.15.0/third_party/repo.bzl:124:19):                                                                                                                             
 - /root/tensorflow-1.15.0/tensorflow/workspace.bzl:925:5                                                                                      
 - /root/tensorflow-1.15.0/WORKSPACE:19:1                                                                                                      
ERROR: An error occurred during the fetch of repository 'pybind11':                                                                            
   java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/pybind/pybind11/archive/v2.3.0.tar.gz, https://github.com/pybind/pybind11/archive/v2.3.0.tar.gz] to /root/.cache/bazel/_bazel_root/a0cf5ef42c8f00571631f8815d38246b/external/pybind11/v2.3.0.tar.gz: All mirrors are down: [GET returned 404 Not Found, connect timed out]       
```                                                                           

Any workaround? 

**System information**
- OS Platform and Distribution: Ubuntu 19.10
- TensorFlow version: 1.15.0
- Python version: 3.7
- Bazel version: 0.26.1

**Comment by soroush** [comment]
It's not only me:
http://www.site24x7.com/public/t/results-1571487777422.html

**Comment by soroush** [comment]
There is also this one:

```
$ curl https://storage.googleapis.com/mirror.tensorflow.org/github.com/abseil/abseil-py/archive/pypi-v0.7.1.tar.gz

<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: mirror.tensorflow.org/github.com/abseil/abseil-py/archive/pypi-v0.7.1.tar.gz</Details></Error>% 
```
Is there something fundamentally broken about mirrors?

**Comment by mihaimaruseac** [comment]
Both should be fixed now.

**Comment by mihaimaruseac** [comment]
Oh, use http for mirror, not https. There is an issue with the SSL certificate that I haven't yet managed to work out. But since we already store checksums in workspace and that comes from GitHub via ssh/https there is not a high priority in fixing SSL for the mirror.

**Comment by soroush** [comment]
Nope. Still broken:

http://storage.googleapis.com/mirror.tensorflow.org/github.com/keras-team/keras-applications/archive/1.0.8.tar.gz

**Comment by soroush** [comment]
Did you mean: 
`sed -i 's/https:\/\/storage.googleapis.com\/mirror.tensorflow.org/http:\/\/storage.googleapis.com\/mirror.tensorflow.org/g' tensorflow/workspace.bzl`
?

DIdn't help either...

**Comment by mihaimaruseac** [comment]
I see both keras-applications 1.0.8 and abseil-py 0.7.1 at http://mirror.tensorflow.org/

**Comment by mihaimaruseac** [comment]
And clicking on the link in https://github.com/tensorflow/tensorflow/issues/33528#issuecomment-544151665 gives me the keras tarball to download

**Comment by soroush** [comment]
Now all links seem to work. I am not sure what happened:
```
$ curl https://storage.googleapis.com/mirror.tensorflow.org/github.com/abseil/abseil-py/archive/pypi-v0.7.1.tar.gz --output /tmp/pypi-v0.7.1.tar.gz > /dev/null 2>&1
$ sha256sum /tmp/pypi-v0.7.1.tar.gz
3d0f39e0920379ff1393de04b573bca3484d82a5f8b939e9e83b20b6106c9bbe  /tmp/pypi-v0.7.1.tar.gz
```

**Comment by mihaimaruseac** [comment]
Maybe some cache on the way? Glad to know it's solved in any case. Should we close?

**Comment by soroush** [comment]
It was a docker build, and no cache that I am aware of was involved... 
Yes please close the issue. Thank you.
