### ISSUE TITLE
ResizeBilinear op mismatch in TF2.0/TFLite

### ISSUE THREAD

**Issue by perfinion** [tensorflow/tensorflow#33691]
There have been changes in how ResizeBilinear works across the last few versions and its causing issues.

- Originally ResizeBilinear op (what you get with tf.image.resize) was completely wrong (see the weird shift below)
- This was made less-wrong with the align_corners=True param (defaults to False for compat which makes sense).
- None of these match OpenCV, align_corners is not completely terrible but still not right.
- for TF2.0 a newer version of the op was made that is really nice and matches OpenCV. PyTorch also matches this version too. The antialias=False (default) param only matters for downscaling. 
- The `tf.keras.layers.UpScaling2D` layer calls `tf.keras.backend.resize_images`
- In TF1.x, `tf.keras.backend.resize_images` called `tf.image.resize_bilinear` with default args, so got the broken op.
- After r1.14 was branched off master, `tf.keras.backed.resize_images` was changed to use the V2 op.
- TF2.0 was branched off master, so has the new good op
- TF1.15 was branched off master, so also has the new good op, but is backwards incompatible
- TOCO/TFLiteConverter forces any resize_bilinear to use the old broken resize op. In fact it forces align_corners=False without even looking at what the input model has.

TFLite needs to have the new op implemented, and TFLiteConverter needs to distinguish and error if the wrong op is used.

Reproducer:
```
#!/usr/bin/env python3

import cv2
import numpy as np
import tensorflow as tf
import tensorflow.compat.v1 as tf1
import tensorflow.compat.v2 as tf2

assert tf.version.VERSION == '2.0.0'
np.set_printoptions(precision=2, suppress=True)

start_shape = (2, 2)
resize_shape = (10, 10)
upsample_size = (resize_shape[0] // start_shape[0], resize_shape[1] // start_shape[1])

# A 2x2 image with diagonal corners = 5
a = np.ones((1, start_shape[0], start_shape[1], 1), dtype=np.float32)
a[0, 0, 0, 0] = 5.0
a[0, -1, -1, 0] = 5.0


b = tf.constant(a, dtype=tf.float32)
c = tf1.image.resize(b, resize_shape,
                     method=tf1.image.ResizeMethod.BILINEAR,
                     align_corners=False)
d = tf1.image.resize(b, resize_shape,
                     method=tf1.image.ResizeMethod.BILINEAR,
                     align_corners=True)

e = tf2.image.resize(b, resize_shape,
                     method=tf2.image.ResizeMethod.BILINEAR,
                     antialias=False)
f = tf2.image.resize(b, resize_shape,
                     method=tf2.image.ResizeMethod.BILINEAR,
                     antialias=True)

z = cv2.resize(a[0], resize_shape, interpolation=cv2.INTER_LINEAR)


print("Input: b")
print(b.numpy()[0, :, :, 0])

print("\nTensorflow: c, tf1 align corners False")
print(c.numpy()[0, :, :, 0])

print("\nTensorflow: d, tf1 align corners True")
print(d.numpy()[0, :, :, 0])

print("\nTensorflow: e, tf2 antialias False")
print(e.numpy()[0, :, :, 0])

print("\nTensorflow: f, tf2 antialias True")
print(f.numpy()[0, :, :, 0])

print("OpenCV:")
print(z)


# for TF2.0, the UpSampling2D layer uses tf2 antialias=False
input_layer = tf.keras.layers.Input(shape=(start_shape[0], start_shape[1], 1), batch_size=1)
x = tf.keras.layers.UpSampling2D(size=upsample_size, interpolation='bilinear')(input_layer)
model = tf.keras.models.Model(input_layer, x)

# Convert the model.
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the TensorFlow Lite model on random input data.
input_shape = input_details[0]['shape']
interpreter.set_tensor(input_details[0]['index'], a)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
tflite_results = interpreter.get_tensor(output_details[0]['index'])

# Test the TensorFlow model on random input data.
tf_results = model(b)

print("tflite results shape:", tflite_results.shape, "TF results shape:", tf_results.shape)
print("TFLite results:")
print(tflite_results[0, :, :, 0])

print("\nTF results:")
print(tf_results.numpy()[0, :, :, 0])

print("\ntf1 align_corners=False matches tflite:", np.allclose(c, tflite_results))
print("UpSampling2D: TF matches TFLite:", np.allclose(tf_results, tflite_results))
```

Output:

```
Input: b
[[5. 1.]
 [1. 5.]]

Tensorflow: c, tf1 align corners False
[[5.   4.2  3.4  2.6  1.8  1.   1.   1.   1.   1.  ]
 [4.2  3.72 3.24 2.76 2.28 1.8  1.8  1.8  1.8  1.8 ]
 [3.4  3.24 3.08 2.92 2.76 2.6  2.6  2.6  2.6  2.6 ]
 [2.6  2.76 2.92 3.08 3.24 3.4  3.4  3.4  3.4  3.4 ]
 [1.8  2.28 2.76 3.24 3.72 4.2  4.2  4.2  4.2  4.2 ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]]

Tensorflow: d, tf1 align corners True
[[5.   4.56 4.11 3.67 3.22 2.78 2.33 1.89 1.44 1.  ]
 [4.56 4.21 3.86 3.52 3.17 2.83 2.48 2.14 1.79 1.44]
 [4.11 3.86 3.62 3.37 3.12 2.88 2.63 2.38 2.14 1.89]
 [3.67 3.52 3.37 3.22 3.07 2.93 2.78 2.63 2.48 2.33]
 [3.22 3.17 3.12 3.07 3.02 2.98 2.93 2.88 2.83 2.78]
 [2.78 2.83 2.88 2.93 2.98 3.02 3.07 3.12 3.17 3.22]
 [2.33 2.48 2.63 2.78 2.93 3.07 3.22 3.37 3.52 3.67]
 [1.89 2.14 2.38 2.63 2.88 3.12 3.37 3.62 3.86 4.11]
 [1.44 1.79 2.14 2.48 2.83 3.17 3.52 3.86 4.21 4.56]
 [1.   1.44 1.89 2.33 2.78 3.22 3.67 4.11 4.56 5.  ]]

Tensorflow: e, tf2 antialias False
[[5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [4.2  4.2  4.2  3.72 3.24 2.76 2.28 1.8  1.8  1.8 ]
 [3.4  3.4  3.4  3.24 3.08 2.92 2.76 2.6  2.6  2.6 ]
 [2.6  2.6  2.6  2.76 2.92 3.08 3.24 3.4  3.4  3.4 ]
 [1.8  1.8  1.8  2.28 2.76 3.24 3.72 4.2  4.2  4.2 ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]]

Tensorflow: f, tf2 antialias True
[[5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [4.2  4.2  4.2  3.72 3.24 2.76 2.28 1.8  1.8  1.8 ]
 [3.4  3.4  3.4  3.24 3.08 2.92 2.76 2.6  2.6  2.6 ]
 [2.6  2.6  2.6  2.76 2.92 3.08 3.24 3.4  3.4  3.4 ]
 [1.8  1.8  1.8  2.28 2.76 3.24 3.72 4.2  4.2  4.2 ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]]
OpenCV:
[[5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [4.2  4.2  4.2  3.72 3.24 2.76 2.28 1.8  1.8  1.8 ]
 [3.4  3.4  3.4  3.24 3.08 2.92 2.76 2.6  2.6  2.6 ]
 [2.6  2.6  2.6  2.76 2.92 3.08 3.24 3.4  3.4  3.4 ]
 [1.8  1.8  1.8  2.28 2.76 3.24 3.72 4.2  4.2  4.2 ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]]
tflite results shape: (1, 10, 10, 1) TF results shape: (1, 10, 10, 1)
TFLite results:
[[5.   4.2  3.4  2.6  1.8  1.   1.   1.   1.   1.  ]
 [4.2  3.72 3.24 2.76 2.28 1.8  1.8  1.8  1.8  1.8 ]
 [3.4  3.24 3.08 2.92 2.76 2.6  2.6  2.6  2.6  2.6 ]
 [2.6  2.76 2.92 3.08 3.24 3.4  3.4  3.4  3.4  3.4 ]
 [1.8  2.28 2.76 3.24 3.72 4.2  4.2  4.2  4.2  4.2 ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]
 [1.   1.8  2.6  3.4  4.2  5.   5.   5.   5.   5.  ]]

TF results:
[[5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [5.   5.   5.   4.2  3.4  2.6  1.8  1.   1.   1.  ]
 [4.2  4.2  4.2  3.72 3.24 2.76 2.28 1.8  1.8  1.8 ]
 [3.4  3.4  3.4  3.24 3.08 2.92 2.76 2.6  2.6  2.6 ]
 [2.6  2.6  2.6  2.76 2.92 3.08 3.24 3.4  3.4  3.4 ]
 [1.8  1.8  1.8  2.28 2.76 3.24 3.72 4.2  4.2  4.2 ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]
 [1.   1.   1.   1.8  2.6  3.4  4.2  5.   5.   5.  ]]

tf1 align_corners=False matches tflite: True
UpSampling2D: TF matches TFLite: False
```

**Comment by angerson** [comment]
Assigned to @jdduke -- this is the bug I mentioned this morning.

**Comment by jdduke** [comment]
Great catch, and thanks for flagging! TFLite should be consistent with TF behavior here. We're investigating internally.

**Comment by perfinion** [comment]
@jdduke oh, its probably worth investigating how the resize bilinear op works in the android NNAPI and EdgeTPU and TFLite GPU and all those places too, I haven't looked at those yet so just throwing it out there first. It'll be complicated to sync all those up if they're different :(.

Also it'll be important to make sure TOCO throws an error if the op args dont match. My problem was that the model converted perfectly as far as i could tell but had silently swapped the op underneath so i didn't notice till later.

**Comment by jdduke** [comment]
Absolutely, our preference is to fail early (during conversion) rather than silently in buggy/unexpected ways at runtime. We'll be validating semantics for all of our various delegate backends as well.

**Comment by srjoglekar246** [comment]
Looks like the V2 op contains a [`half_pixel_centers`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py#L1335) parameter that our current converter (TOCO) doesn't really recognize. As a result, it just defaults to the `align_corners=False` behavior.

We have an experimental new converter that will flag this as an 'unrecognized' op. To enable it, please change the relevant part as follows:

```
converter = tf2.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True
tflite_model = converter.convert()
```

FWIW:
1. TFLite behavior is correct if you use the TF1.x version, even with align_corners=True. If you use TOCO and change `half_pixel_centers` to `align_corners` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py#L1335), things behave same as TF1.x :-).
2. In case you are intent on using the ResizeBilinear op from TF2, you could try using the [Select TF ops](https://www.tensorflow.org/lite/guide/ops_select) feature(In case you haven't already), at the expense of binary size.

In any case, we need to improve TFLite's builtin support for image-processing ops to being them closer to OpenCV :-). I will explore this further.

**Comment by perfinion** [comment]
@srjoglekar246 Thanks for looking into this!
In my case as a workaround using TFSelect would be the best for now since thats how i've trained the model. How do I make toco use the select-op instead of the regular builtin tflite-ops for only the resizeBilinear, all the other ops are good as-is and I can keep using. I've normally only seen TFSelect for ops that are missing. (i could hack TOCO and remove it from the list i suppose, but is there a better way?)

**Comment by srjoglekar246** [comment]
You could this:

```
converter = tf2.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf2.lite.OpsSet.TFLITE_BUILTINS,
                                       tf2.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
```

Since the new converter doesn't recognize that ResizeBilinear, it will only convert that one to the Select-TF version. However, note that Select-TF isn't available (currently) via the Python API, but you can verify the model works by using one of the [other APIs](https://www.tensorflow.org/lite/guide/ops_select#running_the_model).

**Comment by hgaiser** [comment]
Is there any update on this? I'm either trying to find a valid workaround or a fix. The solution provided by @srjoglekar246 would work, but I need to run my code using the Python API, so I can't use `SELECT_TF_OPS`.

**Comment by srjoglekar246** [comment]
We haven't pushed any changes yet, but this should be fixed by end of the year. Sorry for the delay!

**Comment by hgaiser** [comment]
Thank you for the response @srjoglekar246 . I take it there is no need for me to look into fixing this issue then? It is already fixed internally?

**Comment by srjoglekar246** [comment]
Not fixed, but on the way :-). We will most likely improve our kernel to match TensorFlow's behavior.

**Comment by ghop02** [comment]
Hi! Just wanted to mention that I just ran into this as well (I'm using `tf.keras.layers.Upsample2D` with `interpolation="bilinear"`)

I used workaround 1 from @srjoglekar246 's workaround.  Is there any update on the timeline for a more permanent fix?

Thanks!

**Comment by hgaiser** [comment]
@srjoglekar246 any idea if this has been fixed?

**Comment by srjoglekar246** [comment]
I have implemented the new version, its currently under review. This op and its code is used at multiple places in internal tests, so I had to ensure nothing was broken :-). This should go in within a week or so. Sorry about the delay!

**Comment by hgaiser** [comment]
That's good news, can't wait to try it out. Can you drop a comment when it reaches master? Then I can try it in one of the nightly builds.

**Comment by srjoglekar246** [comment]
Sure, np!

**Comment by hgaiser** [comment]
@srjoglekar246 I've seen a [commit](https://github.com/tensorflow/tensorflow/commit/0e805c551596362fbe8560b40b1abab419d2b949) by you in `master` that seems to affect this subject, is that the fix you were talking about? I tried the nightly from today but the issue still persists for me. Using tf-nightly, I have converted my model to tflite again (I don't think this was necessary?) and ran it on an image. I'm working on semantic segmentation and the segments are all shifted to the top left by some clearly noticeable amount of pixels. This was the case before and is still the case with tf-nightly. Am I doing something wrong? Or hasn't the fix for this issue reached `master` yet?

**Comment by srjoglekar246** [comment]
The latter :-). Since it affects a bunch of stuff, the review is taking time. I will ping back on this issue as soon as its in. Thanks for the patience!

**Comment by srjoglekar246** [comment]
This change has gone in to TensorFlow's master branch. @hgaiser May you confirm and close this issue if it works?

**Comment by hgaiser** [comment]
Awesome! Can't wait to try it ou. I will confirm it next Tuesday, but I can't close it because this is not my issue ;)

**Comment by hgaiser** [comment]
Awesome @srjoglekar246 , latest `tf-nightly` fixed my issue. Thank you!

**Comment by srjoglekar246** [comment]
Awesome!
