### ISSUE TITLE
Cannot Get Older Versions to Build

### ISSUE THREAD

**Issue by l0ophole** [tensorflow/tensorflow#33762]
**System information**
- Arch Linux
- TensorFlow installed from source
- TensorFlow version: 1.13.0
- Python version: 3.7
- Not Installed using virtualenv, pip or conda
- Bazel version: 0.25.3
- GCC/Compiler version: 9.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: RS880M (Mobility Radeon HD 4225/4250) (256MB)

I've been trying to build version 1.13.0 of tensorflow for the past two days. I need a build that was compiled with "-mno-avx" because my CPU does not support the AVX instruction set and tensorflow crashes when I run it. I need tensorflow for a project I'm trying to install.

I read that new versions of glibc conflict with the source code and that the source code must be patched to build with as newer version of glibc. I am getting errors about "gettid()" being ambiguous. I found reference to someone patching the source code and changing gettid() to sys_gettid(), but I cannot find the patch that was used.

I also tried changing the function calls manually in the ~/.cache/bazel directory but Bazel will not compile with the cached source code. It seems to redownload the source code before every build. 

The command that I used to start the build:
```
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

Error:
```
ERROR: /home/***/.cache/bazel/_bazel_***/06b70ca2a990d8a0456251480c3991dd/external/grpc/BUILD:507:1: C++ compilation of rule '@grpc//:gpr_base' failed (Exit 1)
                 external/grpc/src/core/lib/gpr/log_linux.cc:43:13: error: ambiguating new declaration of 'long int gettid()'
43 | static long gettid(void) { return syscall(__NR_gettid); }        |             ^~~~~~                                         
In file included from /usr/include/unistd.h:1170,                                   from external/grpc/src/core/lib/gpr/log_linux.cc:41:                                                                 
/usr/include/bits/unistd_ext.h:34:16: note: old declaration '__pid_t gettid()'                                                           
34 | extern __pid_t gettid (void) __THROW;                            |                ^~~~~~                                      
external/grpc/src/core/lib/gpr/log_linux.cc:43:13: warning: 'long int gettid()' defined but not used [-Wunused-function]                 
43 | static long gettid(void) { return syscall(__NR_gettid); }        |             ^~~~~~                                         
Target //tensorflow/tools/pip_package:build_pip_package failed to build                                                               
Use --verbose_failures to see the command lines of failed build steps.                                                                INFO: Elapsed time: 14263.127s, Critical Path: 457.22s
INFO: 4301 processes: 4301 local.
FAILED: Build did NOT complete successfully
```

![Screenshot_20191027-114439](https://user-images.githubusercontent.com/19521547/67638409-11eb2100-f8b2-11e9-8767-aed639721262.png)

**Comment by l0ophole** [comment]
```
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 12803.103s, Critical Path: 439.59s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 4414 processes: 4414 local.
INFO: Build completed successfully, 4757 total actions
```

I found a workaround. I downloaded the tarball for the version of grpc that the version of tensorflow that I'm compiling uses. I extracted the tarball to ~/grpc and manually changed gettid to sys_gettid in the source code. It was only three or four edits. 

I set up a local repository of grpc and added it to the tensorflow WORKSPACE file as a local_repository. I commented out the grpc repository in the tensorflow/workspace.bzl file.

WORKSPACE: (added to bottom of file)
```
local_repository(
    name = "grpc",                                                     
    path = "/home/loophole/grpc",
) 
```
tensorflow/workspace.bzl: (I had to change the sha256 hash and I removed the mirror.bazel.build mirror. That may not be necessary but I downloaded the file from the python.org mirror used the sha256 hash of that file, but I didn't check the hash of the one on bazel.build.)

EDIT: I'm having some weird formatting issue. Change the sha256 value to "fcaec9796c8cc3618899b4aeb62d1a4741830b682b2d8db502a05f9b93c08937" and comment out or delete the bazel.build mirror in "filegroup_external" with the name of "org_python_license"

These are the files that needed to have gettid changed to sys_gettid. First I used grep to see which files had gettid in them, then I used nano and pressed ctrl+w to search for gettid:
```
./src/core/lib/iomgr/ev_epollex_linux.cc
./grpc/src/core/lib/gpr/log_posix.cc
./grpc/src/core/lib/gpr/log_linux.cc
```

Make sure you get the version of Bazel that was tested with the version of tensorflow you want to compile. There's a table at the bottom of this page: https://www.tensorflow.org/install/source

I used this command to remove the previous version of Bazel:
```
rm -rf ~/.bazel ~/.bazelrc ~/.cache/bazel ~/bin/bazel
```
I installed Bazel with --user, so if you installed without that flag then you may also need to remove: (before installing another version of Bazel)
```
/usr/local/bin/bazel
```

**Comment by oanush** [comment]
@l0ophole ,
Hello,looks like the issue is resolved. kindly let us know if we can close the issue.Thanks!

**Comment by l0ophole** [comment]
@oanush well I was about to get it to build but it still crashes except instead of saying "Illegal instruction" it says "Segmentation fault"

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
