### ISSUE TITLE
Keras fails to combine predicted variable-sized sequences

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#34196]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.12.1-17764-gae26958 2.1.0-dev20191111
- Python version: Google Colab py3
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: Google Colab
- GPU model and memory: Google Colab

**Describe the current behavior**
Exception raised (from numpy concatenate) when predicting sequence labels with variable sequence length batches.

**Describe the expected behavior**
There should be no error, as in fit/evaluate methods work fine.

**Code to reproduce the issue**
https://colab.research.google.com/drive/1IPIkj5PlUWKCpuTm9NWM5BLO_suL5VI3

**Other info / logs**
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-e5e9890a3d75> in <module>()
----> 1 model.predict(get_dataset(labels=False))

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
    972         max_queue_size=max_queue_size,
    973         workers=workers,
--> 974         use_multiprocessing=use_multiprocessing)
    975 
    976   def reset_metrics(self):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in predict(self, model, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    496         model, ModeKeys.PREDICT, x=x, batch_size=batch_size, verbose=verbose,
    497         steps=steps, callbacks=callbacks, max_queue_size=max_queue_size,
--> 498         workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
    499 
    500 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in _model_iteration(self, model, mode, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    473               mode=mode,
    474               training_context=training_context,
--> 475               total_epochs=1)
    476           cbks.make_logs(model, epoch_logs, result, mode)
    477 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_v2.py in run_one_epoch(model, iterator, execution_function, dataset_size, batch_size, strategy, steps_per_epoch, num_samples, mode, training_context, total_epochs)
    185 
    186   # End of an epoch.
--> 187   aggregator.finalize()
    188   return aggregator.results
    189 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_utils.py in finalize(self)
    349   def finalize(self):
    350     for result in self.results:
--> 351       result.finalize()
    352     self.results = [i.results for i in self.results]
    353     self.results = nest.pack_sequence_as(self._structure, self.results)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_utils.py in finalize(self)
    187 
    188     else:
--> 189       self.results = np.concatenate(self.results, axis=0)
    190 
    191     if isinstance(self.results, ops.EagerTensor):

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 7 and the array at index 1 has size 9
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 ,2.1.0-dev20191111 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/19ccefa635122accffea177617bfc459/untitled358.ipynb). Thanks!

**Comment by shkarupa-alex** [comment]
Issue still here with tf-nightly, but exception stack changed
```python
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-16-e5e9890a3d75> in <module>()
----> 1 model.predict(get_dataset(labels=False))

11 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     92       raise ValueError('{} is not supported in multi-worker mode.'.format(
     93           method.__name__))
---> 94     return method(self, *args, **kwargs)
     95 
     96   return tf_decorator.make_decorator(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1394             callbacks.on_predict_batch_end(end_step, {'outputs': batch_outputs})
   1395       callbacks.on_predict_end()
-> 1396     all_outputs = nest.map_structure_up_to(batch_outputs, concat, outputs)
   1397     return tf_utils.to_numpy_or_python_type(all_outputs)
   1398 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py in map_structure_up_to(shallow_tree, func, *inputs, **kwargs)
   1129       lambda _, *values: func(*values),  # Discards the path arg.
   1130       *inputs,
-> 1131       **kwargs)
   1132 
   1133 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py in map_structure_with_tuple_paths_up_to(shallow_tree, func, *inputs, **kwargs)
   1225                     in _yield_flat_up_to(shallow_tree, inputs[0], is_seq)]
   1226   results = [func(*args, **kwargs) for args in zip(flat_path_list,
-> 1227                                                    *flat_value_lists)]
   1228   return pack_sequence_as(structure=shallow_tree, flat_sequence=results,
   1229                           expand_composites=expand_composites)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
   1224   flat_path_list = [path for path, _
   1225                     in _yield_flat_up_to(shallow_tree, inputs[0], is_seq)]
-> 1226   results = [func(*args, **kwargs) for args in zip(flat_path_list,
   1227                                                    *flat_value_lists)]
   1228   return pack_sequence_as(structure=shallow_tree, flat_sequence=results,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py in <lambda>(_, *values)
   1127   return map_structure_with_tuple_paths_up_to(
   1128       shallow_tree,
-> 1129       lambda _, *values: func(*values),  # Discards the path arg.
   1130       *inputs,
   1131       **kwargs)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in concat(tensors, axis)
   1882   if isinstance(tensors[0], ragged_tensor.RaggedTensor):
   1883     return ragged_concat_ops.concat(tensors, axis=axis)
-> 1884   return array_ops.concat(tensors, axis=axis)
   1885 
   1886 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    178     """Call target, and fall back on dispatchers if there is a TypeError."""
    179     try:
--> 180       return target(*args, **kwargs)
    181     except (TypeError, ValueError):
    182       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py in concat(values, axis, name)
   1628           dtype=dtypes.int32).get_shape().assert_has_rank(0)
   1629       return identity(values[0], name=name)
-> 1630   return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
   1631 
   1632 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py in concat_v2(values, axis, name)
   1196       return _result
   1197     except _core._NotOkStatusException as e:
-> 1198       _ops.raise_from_not_ok_status(e, name)
   1199     except _core._FallbackException:
   1200       pass

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6810   message = e.message + (" name: " + name if name is not None else "")
   6811   # pylint: disable=protected-access
-> 6812   six.raise_from(core._status_to_exception(e.code, message), None)
   6813   # pylint: enable=protected-access
   6814 

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [5,6,1] vs. shape[2] = [5,10,1] [Op:ConcatV2] name: concat
```

**Comment by amahendrakar** [comment]
@shkarupa-alex,
Seems like the error has been fixed in TF v2.2. I was able to run the code without any issues with TF v2.2, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a07d17dcda435b1b3dcb48730a27e8fa/34196-2-2.ipynb). Thanks!

**Comment by shkarupa-alex** [comment]
> @shkarupa-alex,
> Seems like the error has been fixed in stable version of TF v2.2. I was able to run the code without any issues with TF v2.2, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a07d17dcda435b1b3dcb48730a27e8fa/34196-2-2.ipynb). Thanks!

Nope.
Issue is still present in tf-nightly (see link to colab in issue head).

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3, nightly version(`2.4.0-dev20200728`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/f4fb7a0cbee6adca8d6525eb9eb434cd/untitled195.ipynb#scrollTo=b70Y0hpr4d6I).Thanks!

**Comment by omalleyt12** [comment]
@shkarupa-alex Thanks for the issue! In order to combine Tensors of different shapes, your Model will need to output RaggedTensors. You can do this by adding a Layer at the end of your Model to convert each Tensor to a RaggedTensor. The Dense layer currently at the end of the Model is outputting regular Tensors, and to concat these for `Model.predict`, only the 0-axis can have different shapes

**Comment by JapinderSandhu** [comment]
> @shkarupa-alex Thanks for the issue! In order to combine Tensors of different shapes, your Model will need to output RaggedTensors. You can do this by adding a Layer at the end of your Model to convert each Tensor to a RaggedTensor. The Dense layer currently at the end of the Model is outputting regular Tensors, and to concat these for `Model.predict`, only the 0-axis can have different shapes

how do you output a ragged tensor from your dense layer with Keras Tensorflow? 

ex. my last layer is: 

 model.add(TimeDistributed(Dense(2, activation='sigmoid')))

how do i specify this layer to output ragged?

**Comment by shkarupa-alex** [comment]
Dense layers don't support ragged tensors.
So, i wrote a small wrapper
```python
class MapFlat(layers.Wrapper):
    def __init__(self, layer, **kwargs):
        super().__init__(layer, **kwargs)
        self._supports_ragged_inputs = True

    def build(self, input_shape=None):
        super(MapFlat, self).build([None])

    def call(self, inputs, **kwargs):
        return tf.ragged.map_flat_values(self.layer, inputs)

    @shape_type_conversion
    def compute_output_shape(self, input_shape):
        return input_shape + self.layer.compute_output_shape([None])[1:]
```

Use it like so:
```python
model.add(WithRagged(Dense(2, activation='sigmoid')))
```

**Comment by JapinderSandhu** [comment]
> Dense layers don't support ragged tensors. So, i wrote a small wrapper
> 
> ```python
> class MapFlat(layers.Wrapper):
>     def __init__(self, layer, **kwargs):
>         super().__init__(layer, **kwargs)
>         self._supports_ragged_inputs = True
> 
>     def build(self, input_shape=None):
>         super(MapFlat, self).build([None])
> 
>     def call(self, inputs, **kwargs):
>         return tf.ragged.map_flat_values(self.layer, inputs)
> 
>     @shape_type_conversion
>     def compute_output_shape(self, input_shape):
>         return input_shape + self.layer.compute_output_shape([None])[1:]
> ```
> 
> Use it like so:
> 
> ```python
> model.add(WithRagged(Dense(2, activation='sigmoid')))
> ```
Thank you so much for creating this code example for me ! I really appreciate it. 

Unfortunately it did not run, WithRagged is undefined in this example, did you mean to use MapFlat instead like this? 

model.add(MapFlat(Dense(2, activation='sigmoid')))

if my model requires the use of TimeDistributed layer would this still work with a RaggedTensor?

```python
def action_model():

    model = keras.Sequential()

    model.add(Bidirectional(LSTM(101,return_sequences=True),input_shape=(None,101)))
    model.add(Bidirectional(LSTM(25,return_sequences=True)))
    model.add(TimeDistributed(Dense(20,activation='relu')))
    model.add(Dropout(0.4))
    model.add(TimeDistributed(Dense(16,activation='relu')))
    model.add(Dropout(0.4))
    model.add(TimeDistributed((MapFlat(Dense(2, activation='sigmoid')))))
```
I tried to run this model but got the following error:

```bash
Traceback (most recent call last):
  File "rnn-tf.py", line 133, in <module>
    model = action_model()
  File "rnn-tf.py", line 128, in action_model
    model.add(MapFlat(Dense(2, activation='sigmoid')))
  File "/opt/anaconda3/envs/nnml38/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/opt/anaconda3/envs/nnml38/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 223, in add
    output_tensor = layer(self.outputs[0])
  File "/opt/anaconda3/envs/nnml38/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/opt/anaconda3/envs/nnml38/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/opt/anaconda3/envs/nnml38/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/opt/anaconda3/envs/nnml38/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 862, in _infer_output_signature
    self._maybe_build(inputs)
  File "/opt/anaconda3/envs/nnml38/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2710, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "rnn-tf.py", line 109, in build
    super(MapFlat, self).build([None])
  File "/opt/anaconda3/envs/nnml38/lib/python3.8/site-packages/tensorflow/python/keras/layers/wrappers.py", line 59, in build
    self.layer.build(input_shape)
  File "/opt/anaconda3/envs/nnml38/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1182, in build
    raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
```

This whole issue is very bizarre because I am able to train my network using this model, with variable-sized sequences, but when it comes to model.predict there is a failure.

**Comment by shkarupa-alex** [comment]
Sorry, seems i posted wrong class. Here it is correct one:

```python
import tensorflow as tf
from keras import backend, layers
from keras.utils.generic_utils import has_arg, register_keras_serializable
from keras.utils.tf_utils import shape_type_conversion


class WithRagged(layers.Wrapper):
    """ Passes ragged tensor to layer that accepts only dense one.

    Arguments:
      layer: The `Layer` instance to be wrapped.
    """

    def __init__(self, layer, **kwargs):
        super(WithRagged, self).__init__(layer, **kwargs)
        self.input_spec = layer.input_spec
        self.supports_masking = layer.supports_masking
        self._supports_ragged_inputs = True

        if not isinstance(layer, layers.Layer):
            raise ValueError(
                'Please initialize `WithRagged` layer with a '
                '`Layer` instance. You passed: {input}'.format(input=layer))

    def build(self, input_shape=None):
        if not self.layer.built:
            self.layer.build(input_shape)

        self.input_spec = self.layer.input_spec

        zero = '' if self.layer.dtype == tf.string else 0
        self.masking_layer = layers.Masking(mask_value=zero)

        super(WithRagged, self).build()

    def call(self, inputs, **kwargs):
        layer_kwargs = {}
        for key in kwargs.keys():
            if has_arg(self.layer.call, key):
                layer_kwargs[key] = kwargs[key]

        inputs_dense, row_lengths = backend.convert_inputs_if_ragged(inputs)
        inputs_dense = self.masking_layer(inputs_dense)
        outputs_dense = self.layer.call(inputs_dense, **layer_kwargs)
        outputs = backend.maybe_convert_to_ragged(row_lengths is not None, outputs_dense, row_lengths)

        return outputs

    def compute_output_shape(self, input_shape):
        return self.layer.compute_output_shape(input_shape)

    def compute_mask(self, inputs, mask=None):
        return self.layer.compute_mask(inputs, mask)

    def get_config(self):
        return super(WithRagged, self).get_config()

```
