### ISSUE TITLE
conv_grad_ops.cc:623:46: error: invalid use of 'auto'

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#345]
I'm getting a compile error when trying to compile the `example_trainer` using gcc 4.8.1:

    $ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer  --verbose_failures 
    ____From Compiling tensorflow/core/kernels/conv_grad_ops.cc:
    tensorflow/core/kernels/conv_grad_ops.cc: In instantiation of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]
    ::__lambda3':
    tensorflow/core/kernels/conv_grad_ops.cc:621:22:   required from 'struct tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; 
    T = float]::__lambda3'
    tensorflow/core/kernels/conv_grad_ops.cc:632:7:   required from 'void tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T =
     float]'
    tensorflow/core/kernels/conv_grad_ops.cc:1265:1:   required from here
    tensorflow/core/kernels/conv_grad_ops.cc:621:56: error: use of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda3::__col_buffer_data' before deduction of 'auto'
                         &size_A](int64 start, int64 limit) {
                                                            ^
    tensorflow/core/kernels/conv_grad_ops.cc:621:56: error: use of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda3::__col_buffer_data' before deduction of 'auto'
    tensorflow/core/kernels/conv_grad_ops.cc:621:56: error: use of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda3::__input_data' before deduction of 'auto'
    tensorflow/core/kernels/conv_grad_ops.cc:621:56: error: use of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda3::__input_data' before deduction of 'auto'
    tensorflow/core/kernels/conv_grad_ops.cc:623:46: error: use of 'input_data' before deduction of 'auto'
               auto input_data_shard = input_data + shard_id * input_offset;
                                                  ^
    tensorflow/core/kernels/conv_grad_ops.cc:623:46: error: invalid use of 'auto'

**Comment by markusdr** [comment]
It seems the compile error was introduced recently. It goes away when I downgrade to an older version; this version was still OK:

    commit 011e9baccd343eb943d25014c4e8aec53eac396b
    Author: Vijay Vasudevan <vrv@google.com>
    Date:   Thu Nov 12 18:34:45 2015 -0800

**Comment by vrv** [comment]
Thanks, we're looking at it now...

**Comment by vrv** [comment]
This was fixed some time last week.

**Comment by arpitg1991** [comment]
I still see the issue: 

From Compiling tensorflow/core/kernels/conv_grad_ops.cc:
tensorflow/core/kernels/conv_grad_ops.cc: In instantiation of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda4':
tensorflow/core/kernels/conv_grad_ops.cc:705:22:   required from 'struct tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda4'
tensorflow/core/kernels/conv_grad_ops.cc:716:7:   required from 'void tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]'
tensorflow/core/kernels/conv_grad_ops.cc:1368:1:   required from here
tensorflow/core/kernels/conv_grad_ops.cc:705:56: error: use of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda4::__col_buffer_data' before deduction of 'auto'
                     &size_A](int64 start, int64 limit) {
                                                        ^
tensorflow/core/kernels/conv_grad_ops.cc:705:56: error: use of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda4::__col_buffer_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:705:56: error: use of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda4::__input_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:705:56: error: use of 'tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda4::__input_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:707:50: error: use of 'input_data' before deduction of 'auto'
           const T* input_data_shard = input_data + shard_id * input_offset;
                                                  ^
tensorflow/core/kernels/conv_grad_ops.cc:707:50: error: invalid use of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:707:63: error: cannot convert 'auto*' to 'const float*' in initialization
           const T* input_data_shard = input_data + shard_id * input_offset;
                                                               ^
tensorflow/core/kernels/conv_grad_ops.cc:708:47: error: use of 'col_buffer_data' before deduction of 'auto'
           T* col_data_shard = col_buffer_data + shard_id * size_A;
                                               ^
tensorflow/core/kernels/conv_grad_ops.cc:708:47: error: invalid use of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:708:60: error: cannot convert 'auto*' to 'float*' in initialization
           T* col_data_shard = col_buffer_data + shard_id * size_A;
                                                            ^
tensorflow/core/kernels/conv_grad_ops.cc: In instantiation of 'void tensorflow::Conv2DCustomBackpropFilterOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]':
tensorflow/core/kernels/conv_grad_ops.cc:1368:1:   required from here
tensorflow/core/kernels/conv_grad_ops.cc:702:20: error: invalid initialization of reference of type 'auto*&' from expression of type 'const float*'
       auto shard = [&input_data, &col_buffer_data, &in_depth, &input_rows,
                    ^
tensorflow/core/kernels/conv_grad_ops.cc:702:20: error: invalid initialization of reference of type 'auto*&' from expression of type 'float*'
tensorflow/core/kernels/conv_grad_ops.cc: In instantiation of 'tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0':
tensorflow/core/kernels/conv_grad_ops.cc:487:24:   required from 'struct tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0'
tensorflow/core/kernels/conv_grad_ops.cc:505:9:   required from 'void tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]'
tensorflow/core/kernels/conv_grad_ops.cc:1368:1:   required from here
tensorflow/core/kernels/conv_grad_ops.cc:487:58: error: use of 'tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0::__filter_data' before deduction of 'auto'
                       &size_C](int64 start, int64 limit) {
                                                          ^
tensorflow/core/kernels/conv_grad_ops.cc:487:58: error: use of 'tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0::__filter_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:487:58: error: use of 'tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0::__out_backprop_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:487:58: error: use of 'tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0::__out_backprop_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:487:58: error: use of 'tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0::__col_buffer_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:487:58: error: use of 'tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0::__col_buffer_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:487:58: error: use of 'tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0::__input_backprop_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:487:58: error: use of 'tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]::__lambda0::__input_backprop_data' before deduction of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:489:45: error: use of 'col_buffer_data' before deduction of 'auto'
             T* im2col_buf = col_buffer_data + shard_id * size_C;
                                             ^
tensorflow/core/kernels/conv_grad_ops.cc:489:45: error: invalid use of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:489:58: error: cannot convert 'auto*' to 'float*' in initialization
             T* im2col_buf = col_buffer_data + shard_id * size_C;
                                                          ^
tensorflow/core/kernels/conv_grad_ops.cc:490:49: error: use of 'input_backprop_data' before deduction of 'auto'
             T* input_data = input_backprop_data + shard_id * input_offset;
                                                 ^
tensorflow/core/kernels/conv_grad_ops.cc:490:49: error: invalid use of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:490:62: error: cannot convert 'auto*' to 'float*' in initialization
             T* input_data = input_backprop_data + shard_id * input_offset;
                                                              ^
tensorflow/core/kernels/conv_grad_ops.cc:491:51: error: use of 'out_backprop_data' before deduction of 'auto'
             const T* out_data = out_backprop_data + shard_id * output_offset;
                                                   ^
tensorflow/core/kernels/conv_grad_ops.cc:491:51: error: invalid use of 'auto'
tensorflow/core/kernels/conv_grad_ops.cc:491:64: error: cannot convert 'auto*' to 'const float*' in initialization
             const T* out_data = out_backprop_data + shard_id * output_offset;
                                                                ^
tensorflow/core/kernels/conv_grad_ops.cc:497:71: error: use of 'filter_data' before deduction of 'auto'
             ConstMatrixMap B(filter_data, filter_total_size, out_depth);
                                                                       ^
tensorflow/core/kernels/conv_grad_ops.cc:497:71: error: no matching function for call to 'Eigen::Map<const Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >::Map(auto*&, const int&, const int64&)'
tensorflow/core/kernels/conv_grad_ops.cc:497:71: note: candidates are:
In file included from third_party/eigen3/Eigen/Core:411:0,
                 from third_party/eigen3/unsupported/Eigen/CXX11/Core:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:14,
                 from ./tensorflow/core/public/tensor.h:19,
                 from ./tensorflow/core/framework/device_base.h:28,
                 from ./tensorflow/core/framework/op_kernel.h:24,
                 from ./tensorflow/core/framework/numeric_op.h:19,
                 from tensorflow/core/kernels/conv_grad_ops.cc:21:
third_party/eigen3/Eigen/src/Core/Map.h:170:12: note: Eigen::Map<MatrixType, MapOptions, StrideType>::Map(Eigen::Map<MatrixType, MapOptions, StrideType>::PointerArgType, Eigen::Map<MatrixType, MapOptions, StrideType>::Index, Eigen::Map<MatrixType, MapOptions, StrideType>::Index, const StrideType&) [with PlainObjectType = const Eigen::Matrix<float, -1, -1, 1, -1, -1>; int MapOptions = 0; StrideType = Eigen::Stride<0, 0>; Eigen::Map<MatrixType, MapOptions, StrideType>::PointerArgType = const float*; Eigen::Map<MatrixType, MapOptions, StrideType>::Index = long int]
     inline Map(PointerArgType dataPtr, Index nbRows, Index nbCols, const StrideType& a_stride = StrideType())
            ^
third_party/eigen3/Eigen/src/Core/Map.h:170:12: note:   no known conversion for argument 1 from 'auto*' to 'Eigen::Map<const Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >::PointerArgType {aka const float*}'
third_party/eigen3/Eigen/src/Core/Map.h:156:12: note: Eigen::Map<MatrixType, MapOptions, StrideType>::Map(Eigen::Map<MatrixType, MapOptions, StrideType>::PointerArgType, Eigen::Map<MatrixType, MapOptions, StrideType>::Index, const StrideType&) [with PlainObjectType = const Eigen::Matrix<float, -1, -1, 1, -1, -1>; int MapOptions = 0; StrideType = Eigen::Stride<0, 0>; Eigen::Map<MatrixType, MapOptions, StrideType>::PointerArgType = const float*; Eigen::Map<MatrixType, MapOptions, StrideType>::Index = long int]
     inline Map(PointerArgType dataPtr, Index a_size, const StrideType& a_stride = StrideType())
            ^
third_party/eigen3/Eigen/src/Core/Map.h:156:12: note:   no known conversion for argument 1 from 'auto*' to 'Eigen::Map<const Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >::PointerArgType {aka const float*}'
third_party/eigen3/Eigen/src/Core/Map.h:143:12: note: Eigen::Map<MatrixType, MapOptions, StrideType>::Map(Eigen::Map<MatrixType, MapOptions, StrideType>::PointerArgType, const StrideType&) [with PlainObjectType = const Eigen::Matrix<float, -1, -1, 1, -1, -1>; int MapOptions = 0; StrideType = Eigen::Stride<0, 0>; Eigen::Map<MatrixType, MapOptions, StrideType>::PointerArgType = const float*]
     inline Map(PointerArgType dataPtr, const StrideType& a_stride = StrideType())
            ^
third_party/eigen3/Eigen/src/Core/Map.h:143:12: note:   candidate expects 2 arguments, 3 provided
third_party/eigen3/Eigen/src/Core/Map.h:104:79: note: Eigen::Map<const Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >::Map(const Eigen::Map<const Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >&)
 template<typename PlainObjectType, int MapOptions, typename StrideType> class Map
                                                                               ^
third_party/eigen3/Eigen/src/Core/Map.h:104:79: note:   candidate expects 1 argument, 3 provided
tensorflow/core/kernels/conv_grad_ops.cc: In instantiation of 'void tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]':
tensorflow/core/kernels/conv_grad_ops.cc:1368:1:   required from here
tensorflow/core/kernels/conv_grad_ops.cc:481:22: error: invalid initialization of reference of type 'auto*&' from expression of type 'float*'
         auto shard = [&in_depth, &input_rows, &input_cols, &filter_rows,
                      ^
tensorflow/core/kernels/conv_grad_ops.cc:481:22: error: invalid initialization of reference of type 'auto*&' from expression of type 'float*'
tensorflow/core/kernels/conv_grad_ops.cc:481:22: error: invalid initialization of reference of type 'auto*&' from expression of type 'const float*'
tensorflow/core/kernels/conv_grad_ops.cc:481:22: error: invalid initialization of reference of type 'auto*&' from expression of type 'const float*'
In file included from ./tensorflow/core/framework/op_kernel.h:21:0,
                 from ./tensorflow/core/framework/numeric_op.h:19,
                 from tensorflow/core/kernels/conv_grad_ops.cc:21:
./tensorflow/core/framework/allocator.h: In member function 'virtual size_t tensorflow::Allocator::RequestedSize(void*)':
./tensorflow/core/framework/allocator.h:86:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
In file included from ./tensorflow/core/framework/op_kernel.h:24:0,
                 from ./tensorflow/core/framework/numeric_op.h:19,
                 from tensorflow/core/kernels/conv_grad_ops.cc:21:
./tensorflow/core/framework/device_base.h: In member function 'virtual tensorflow::Allocator* tensorflow::DeviceBase::GetAllocator(tensorflow::AllocatorAttributes)':
./tensorflow/core/framework/device_base.h:146:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
./tensorflow/core/framework/device_base.h: In member function 'virtual const tensorflow::DeviceAttributes& tensorflow::DeviceBase::attributes() const':
./tensorflow/core/framework/device_base.h:164:3: warning: control reaches end of non-void function [-Wreturn-type]
   }
   ^
ERROR: /home/local/ANT/arpgup/tensorflow/tensorflow/tensorflow.bzl:226:3: C++ compilation of rule '//tensorflow/core:kernels' failed: gcc failed: error executing command
  (cd /home/local/ANT/arpgup/.cache/bazel/_bazel_arpgup/1d518f226ad034073e38f75799c6eef6/tensorflow && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -iquote . -iquote bazel-out/local_linux-opt/genfiles -isystem tools/cpp/gcc3 -isystem google/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/google/protobuf/src -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/include -isystem third_party/eigen3 -isystem bazel-out/local_linux-opt/genfiles/third_party/eigen3 -pthread -fno-exceptions -DEIGEN_AVOID_STL_ARRAY -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernels/tensorflow/core/kernels/conv_grad_ops.pic.o' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernels/tensorflow/core/kernels/conv_grad_ops.pic.d -fPIC -c tensorflow/core/kernels/conv_grad_ops.cc -o bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernels/tensorflow/core/kernels/conv_grad_ops.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: gcc failed: error executing command
  (cd /home/local/ANT/arpgup/.cache/bazel/_bazel_arpgup/1d518f226ad034073e38f75799c6eef6/tensorflow && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games \
  /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -iquote . -iquote bazel-out/local_linux-opt/genfiles -isystem tools/cpp/gcc3 -isystem google/protobuf/src -isystem bazel-out/local_linux-opt/genfiles/google/protobuf/src -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-opt/genfiles/external/re2 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-opt/genfiles/third_party/gpus/cuda/include -isystem third_party/eigen3 -isystem bazel-out/local_linux-opt/genfiles/third_party/eigen3 -pthread -fno-exceptions -DEIGEN_AVOID_STL_ARRAY -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernels/tensorflow/core/kernels/conv_grad_ops.pic.o' -MD -MF bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernels/tensorflow/core/kernels/conv_grad_ops.pic.d -fPIC -c tensorflow/core/kernels/conv_grad_ops.cc -o bazel-out/local_linux-opt/bin/tensorflow/core/_objs/kernels/tensorflow/core/kernels/conv_grad_ops.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by peterbraden** [comment]
This is still an issue, I pulled from master today:

https://travis-ci.org/peterbraden/node-tensorflow/builds/108240579

```
external/eigen_archive/eigen-eigen-fa22401ededc/Eigen/src/Core/Map.h:88:79: note: Eigen::Map<const Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >::Map(const Eigen::Map<const Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >&)
 template<typename PlainObjectType, int MapOptions, typename StrideType> class Map
                                                                               ^
external/eigen_archive/eigen-eigen-fa22401ededc/Eigen/src/Core/Map.h:88:79: note:   candidate expects 1 argument, 3 provided
tensorflow/core/kernels/conv_grad_ops.cc: In instantiation of 'void tensorflow::Conv2DCustomBackpropInputOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = float]':
tensorflow/core/kernels/conv_grad_ops.cc:1422:1:   required from here
tensorflow/core/kernels/conv_grad_ops.cc:490:22: error: invalid initialization of reference of type 'auto*&' from expression of type 'float*'
         auto shard = [&in_depth, &input_rows, &input_cols, &filter_rows,
                      ^
tensorflow/core/kernels/conv_grad_ops.cc:490:22: error: invalid initialization of reference of type 'auto*&' from expression of type 'float*'
```
