### ISSUE TITLE
Docker Install instructions page is broken now that v2.0 is the latest image

### ISSUE THREAD

**Issue by PeteBlackerThe3rd** [tensorflow/tensorflow#34758]
##  URL(s) with the issue:
https://www.tensorflow.org/install/docker

## Documentation page with the issue:
https://www.tensorflow.org/install/docker

## Description of issue (what needs changing):
Since the latest docker builds are now tensorflow v2.x instead of v1.x the python example script on this page doesn't work out of the box. If the user copy and pastes the commands from this page they'll get a "AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'" error when trying to verify their docker container.
The python example script can be changing to this to fix it:

```
import tensorflow.compat.v1 as tf
tf.enable_eager_execution();
print(tf.reduce_sum(tf.random_normal([1000, 1000])))
```

A better alternative however would be to change it to a TF v2.0 native example.

**Comment by lamberta** [comment]
Thanks. Fixed in https://github.com/tensorflow/docs/pull/1261 and tensorflow/org will get updated next site push.

**Comment by PeteBlackerThe3rd** [comment]
The docker installation verification code is still broken. There is still a version 1.x API call in there. I've opened PR #1310 which fixes this.

**Comment by PeteBlackerThe3rd** [comment]
The docker installation verification code is still broken. There is still a version 1.x API call in there. I've opened PR #1310 which fixes this.
