### ISSUE TITLE
cuBLAS failure for large convolutions in V100 GPUs

### ISSUE THREAD

**Issue by CNugteren** [tensorflow/tensorflow#35032]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.15.0 or 2.0.0
- **Python version**: 3.7.3
- **CUDA/cuDNN version**: 10.0 and 7.6.4
- **GPU model and memory**: Tesla V100 with either 16GB or 32GB
- **Exact command to reproduce**: `python tf_v100_cublas_crash_tf1.py` (from the gist below)

### Describe the problem
If I run a large 1x1 convolution with FP16 on a Tesla V100, cuBLAS crashes with the following kind of message:
```
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas SGEMM launch failed : m=9584640, n=17, k=17
     [[node graph_final_part/conv/conv2d/Conv2D (defined at ~/.virtualenvs/tf/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
     [[ExpandDims_9/_3631]]
  (1) Internal: Blas SGEMM launch failed : m=9584640, n=17, k=17
     [[node graph_final_part/conv/conv2d/Conv2D (defined at ~/.virtualenvs/tf/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```
This comes from this place in the TF code:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/conv_ops.cc#L698

The root cause is such TensorFlow code for example:
```
conv_op = tf.layers.Conv2D(filters=17, kernel_size=(1, 1))
in_t = tf.ones(shape=(10, 1152, 832, 17), dtype=tf.float16)
```
It works again if I:
* Make the input tensor smaller
* Use FP32 instead of FP16
* Run on a CPU instead of the V100 GPU
* Use a GeForce Titan X GPU instead of a V100
* Use TF 1.14 on a V100 GPU (but not TF 1.15.0 or 2.0.0)

### Source code / logs

A small gist with a fully working example of only ~10 lines can be found here:
https://gist.github.com/CNugteren/c40f0f34f2af759b2d900223fefadbfd#file-tf_v100_cublas_crash_tf1-py (TF 1.15.0 version)
https://gist.github.com/CNugteren/c40f0f34f2af759b2d900223fefadbfd#file-tf_v100_cublas_crash_tf2-py (TF 2.0.0 version)

I even tried to mimic the cuBLAS call but that didn't crash, so it seems a TensorFlow bug rather than cuBLAS, unless I made a mistake of course:
https://gist.github.com/CNugteren/c40f0f34f2af759b2d900223fefadbfd#file-tf_v100_cublas_crash_mimic-cu

**Comment by gadagashwini** [comment]
Sample code snippet is working as expected on Colab with Tf 1.15 and Tf 2.0.
Please see the gist of [Tf 1.15](https://colab.sandbox.google.com/gist/gadagashwini/ac001417dc6c92becd9971be07f98456/untitled299.ipynb) and [Tf 2.0](https://colab.sandbox.google.com/gist/gadagashwini/0cbe3a109bb78b10a31e81f367cbfac8/untitled300.ipynb). Thanks!

**Comment by CNugteren** [comment]
@gadagashwini, sorry I don't have a Google account so I can't run that. But are you sure this is on a V100? If so, please share all the details of the nvidia drivers and cuda/cudnn setup that you are using.

**Comment by gadagashwini** [comment]
@CNugteren, Google Colab uses P100.

**Comment by CNugteren** [comment]
So please test it on a V100, that's where the bug is.

**Comment by sanjoy** [comment]
I wasn't able to reproduce this on a Titan-V.  Can enable [cuBLAS logging](https://docs.nvidia.com/cuda/cublas/index.html#cublasLoggerConfigure) and attach the generated log?  Maybe that will uncover a smoking gun.

**Comment by CNugteren** [comment]
OK good idea, I've done that now.

Running: python3 https://gist.github.com/CNugteren/c40f0f34f2af759b2d900223fefadbfd#file-tf_v100_cublas_crash_tf1-py

Results in regular output as follows:
[regular_output.txt](https://github.com/tensorflow/tensorflow/files/3966986/regular_output.txt)

And with CUBLAS_LOGINFO_DBG=1 set also this cuBLAS specific output:
[cublas_report.txt](https://github.com/tensorflow/tensorflow/files/3966990/cublas_report.txt)

**Comment by sanjoy** [comment]
I was able to reproduce this on a TitanV.  This fails with TF 2.0.0 but passes with tf-nightly (2.1.0-dev20191226).  It could have been a TF issue that got fixed or a CUDA issue that was fixed in 10.1 (2.0.0 uses CUDA 10, TF nightly uses CUDA 10.1).

I'm closing this for now, please reopen if there is something more for us to do here.

**Comment by CNugteren** [comment]
Thanks @sanjoy. Just for your information: I also tried with my own compiled version of TF 1.15.0 with the latest CUDA 10.1 and that didn't solve the issue, so I doubt that that changed it. But I'm glad it is fixed in TF 2.1. So that also means you won't backport this fix to the 1.x branch (e.g. 1.15.1)?

**Comment by sanjoy** [comment]
> So that also means you won't backport this fix to the 1.x branch (e.g. 1.15.1)?

I don't think there are any plans for a 1.15.1 release (CC @goldiegadde ).

And at this point I'm not even sure what change fixed this, given that you're saying it wasn't the CUDA upgrade.

**Comment by mmalahe** [comment]
Exeperienced this as well with a V100, NVIDIA drivers 418, CUDA 10.1 and 2.1.0rc2:
> tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found. (0) Internal: Blas GEMM launch failed : a.shape=(1000, 1024), b.shape=(1024, 3), m=1000, n=3, k=1024
> [[{{node mrcnn_class_logits/dense/MatMul}}]]
[[add_metric_2/Identity/_3667]] (1) Internal: Blas GEMM launch failed : a.shape=(1000, 1024), b.shape=(1024, 3), m=1000, n=3, k=1024
[[{{node mrcnn_class_logits/dense/MatMul}}]]

Was successful with an image based on today's nightly-gpu-py3 with digest 7cdb1957c9bf.
