### ISSUE TITLE
Failed to convert weights to 8 bit precision: "Quantize weights tool only supports tflite models with one subgraph" 

### ISSUE THREAD

**Issue by rutrilla** [tensorflow/tensorflow#35194]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab (GPU)
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 2.1.0-dev20191217 
- **Python version**: 3
- **Exact command to reproduce**:

```bash
!pip install tf-nightly
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout

model = Sequential()
model.add(GRU(100, activation='relu', return_sequences=False, input_shape=(128,2)))
model.add(Dropout(0.2))
model.add(Dense(11, activation='softmax'))

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.experimental_new_converter = True
tflite_model = converter.convert()
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_model_quant = converter.convert()
```

### Error message
```bash
E tensorflow/lite/tools/optimize/quantize_weights.cc:351] Quantize weights tool only supports tflite models with one subgraph.
```

### Describe the problem
First, I used the new converter (with the experimental flag converter.experimental_new_converter = True) to convert an RNN model from TensorFlow to TensorFlow Lite's flat buffer format, as suggested in the issue #32608.

This works correctly, but then when I try to perform a post-training weight quantization, I got an error saying that the quantize weights tool only supports tflite models with one subgraph. 

Is there a problem with my procedure? Or is that feature not yet supported? In that case, I would like to request this feature.

Thanks in advance for your help.

### Source code / logs
The attached file can be used to reproduce the error with a trained model (.h5). 
[GRU_1L.zip](https://github.com/tensorflow/tensorflow/files/3974453/GRU_1L.zip)

**Comment by AlexVaith** [comment]
I have a very similar setup, with LSTM layers.
I can convert the model with experimental set up and the inference works, but as soon as I try to do post training optimization in form of weight quantization, I get the same error.

**Comment by rutrilla** [comment]
Hey, is there any news on this issue? Thanks!

**Comment by PCerles** [comment]
I am also interested in quantizing a model with LSTM layers and am having this issue.

**Comment by AlexVaith** [comment]
I still get an error, when I try to convert a model with lstm layers into tf lite and use post training optimization in form of: 
```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = custom_generator
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                      tf.lite.OpsSet.SELECT_TF_OPS]
```
I get this error:
```
RuntimeError: Only models with a single subgraph are supported, model had 5 subgraphs
```
When I do not use optimizations, it works. 
I am using tf 2.1.0 and tf-nightly version from 10.02.2020

**Comment by BeWe11** [comment]
I get the same error when using `tf.scan` in one of my layers. tf.lite conversion works fine if I don't enable post-training quantization but crashes when I turn it on.

There are several issues around this error but its never mentioned whether this is an inherent limitation in the tf.lite converter or if there is a fix coming. Can somebody clarify this?

Thanks!

**Comment by BigBerny** [comment]
Same problem with TensorFlow 2.2.0rc1. Is there a way to bypass this?

**Comment by BeWe11** [comment]
I was able to quantize my model by setting
```python
converter.experimental_new_quantizer = True
```
Might be worth trying out this setting for your models as well.

**Comment by BigBerny** [comment]
> I was able to quantize my model by setting
> 
> ```python
> converter.experimental_new_quantizer = True
> ```
> 
> Might be worth trying out this setting for your models as well.

Doesn't work on my GRU

**Comment by BeWe11** [comment]
> > I was able to quantize my model by setting
> > ```python
> > converter.experimental_new_quantizer = True
> > ```
> > 
> > 
> > Might be worth trying out this setting for your models as well.
> 
> Doesn't work on my GRU

Ok, I have to add that this only works for me when using tf-nightly, maybe give that a try.

**Comment by BigBerny** [comment]
> > > I was able to quantize my model by setting
> > > ```python
> > > converter.experimental_new_quantizer = True
> > > ```
> > > 
> > > 
> > > Might be worth trying out this setting for your models as well.
> > 
> > 
> > Doesn't work on my GRU
> 
> Ok, I have to add that this only works for me when using tf-nightly, maybe give that a try.

It doesn't work with 2.2.0rc1 but it does work with the current nightly. 👍 At least I got no error but I didn't test yet if the output from the model is correct.

**Comment by AlbertoEsc** [comment]
Thanks a lot @Bewe11 and @BigBerny. The originally posted code (+ converter.optimizations = [tf.lite.Optimize.DEFAULT]) seems to be also working for me (tf_nightly-2.2.0.dev20200418-cp37-cp37m-manylinux2010_x86_64.whl).
However, I get an exception when I add a representative dataset (converter.representative_dataset = representative_dataset_gen), which is necessary to actually enable integer operations (https://www.tensorflow.org/lite/performance/post_training_quantization). This is the exception I get:
 `Traceback (most recent call last):
  File "installation_path/tensorflow/lite/python/optimize/calibrator.py", line 51, in __init__
    _calibration_wrapper.CalibrationWrapper(model_content))
TypeError: pybind11::init(): factory function returned nullptr`
If I remove the GRU, the network is quantized without any problem. 
@Bewe11 and @BigBerny, did you provide a representative dataset? did you experience this problem?

**Comment by LesterRe** [comment]
Same situation @AlbertoEsc.
I did some research and found that the mismatch of CUDA version might cause this problem. 
https://github.com/NVIDIA/TensorRT/issues/308. Though it didn't solve my problem, it may help you.

**Comment by MojoForPresident** [comment]
Hello, I'm having the same problem. I manage to convert and quantize the model by using tf-nightly and the new experimental setup, but only when not attempting to do full integer quantization as described in the [post-training quantization docs](https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization). In that case I run into the same issue as @AlbertoEsc described above.

Is there any news when this will be fixed? Is there a new workaround?

Thank you!

**Comment by salah-adi** [comment]
Hey there, I'm having the same problem when trying to convert the model with quantization. The model is able to convert without quantization just fine. I am using tf-nightly, but still get the following error: ConverterError: <unknown>:0: error: loc("lstm/lstm_cell/bias"): is not immutable, try running tf-saved-model-optimize-global-tensors to prove tensors are immutable.

Has anyone encountered this error, or know how to solve it?
Thanks!

**Comment by Saduf2019** [comment]
@rutrilla 
Please verify on later tf version and let us know of this is still an issue.

**Comment by raminmohammadi** [comment]
I still have the same issue. I am using tf_nightly version "2.6.0.dev2021050600". I am able to convert to tf_lite and Dynamic range quantization. However, i can not do full integer quantization. I get the following error:


WARNING:absl:Found untraced functions such as lstm_cell_1_layer_call_fn, lstm_cell_1_layer_call_and_return_conditional_losses, lstm_cell_2_layer_call_fn, lstm_cell_2_layer_call_and_return_conditional_losses, lstm_cell_1_layer_call_fn while saving (showing 5 of 10). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: /tmp/tmpa_b80fsa/assets
INFO:tensorflow:Assets written to: /tmp/tmpa_b80fsa/assets
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/ml_user/anaconda3/envs/tf_nightly/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py in __init__(self, model_content, custom_op_registerers_by_name, custom_op_registerers_by_func)
     70               model_content, custom_op_registerers_by_name,
---> 71               custom_op_registerers_by_func))
     72     except Exception as e:

ValueError: Only models with a single subgraph are supported, model had 5 subgraphs

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-244-edd7ac30c56e> in <module>()
      5 converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
      6                                       tf.lite.OpsSet.SELECT_TF_OPS]
----> 7 tflite_quant_model = converter.convert()

/home/ml_user/anaconda3/envs/tf_nightly/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in convert(self)
    969     self._increase_conversion_attempt_metric()
    970     self._save_conversion_params_metric({})
--> 971     saved_model_convert_result = self._convert_as_saved_model()
    972     if saved_model_convert_result:
    973       self._increase_conversion_success_metric(saved_model_convert_result)

/home/ml_user/anaconda3/envs/tf_nightly/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in _convert_as_saved_model(self)
    951         return super(TFLiteKerasModelConverterV2,
    952                      self).convert(meta_graph.graph_def, input_tensors,
--> 953                                    output_tensors)
    954     finally:
    955       shutil.rmtree(temp_dir, True)

/home/ml_user/anaconda3/envs/tf_nightly/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in convert(self, graph_def, input_tensors, output_tensors)
    774 
    775     result = self._apply_optimizations(
--> 776         result, quant_mode, quant_io=self.experimental_new_quantizer)
    777 
    778     return result

/home/ml_user/anaconda3/envs/tf_nightly/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in _apply_optimizations(self, model, quant_mode, quant_io)
    649         q_allow_float = quant_mode.is_allow_float()
    650         model = self._quantize(
--> 651             model, q_in_type, q_out_type, q_activations_type, q_allow_float)
    652 
    653       m_in_type = in_type if in_type else _dtypes.float32

/home/ml_user/anaconda3/envs/tf_nightly/lib/python3.6/site-packages/tensorflow/lite/python/lite.py in _quantize(self, result, input_type, output_type, activations_type, allow_float)
    485     calibrate_quantize = _calibrator.Calibrator(result,
    486                                                 custom_op_registerers_by_name,
--> 487                                                 custom_op_registerers_by_func)
    488     if self._experimental_calibrate_only or self.experimental_new_quantizer:
    489       calibrated = calibrate_quantize.calibrate(

/home/ml_user/anaconda3/envs/tf_nightly/lib/python3.6/site-packages/tensorflow/lite/python/optimize/calibrator.py in __init__(self, model_content, custom_op_registerers_by_name, custom_op_registerers_by_func)
     71               custom_op_registerers_by_func))
     72     except Exception as e:
---> 73       raise ValueError("Failed to parse the model: %s." % e)
     74     if not self._calibrator:
     75       raise ValueError("Failed to parse the model.")

ValueError: Failed to parse the model: Only models with a single subgraph are supported, model had 5 subgraphs.'

**Comment by AnastGerus** [comment]
I have a similar issue with LSTM layers in tf 2.7.0.dev20210706.
I can convert the model and it works, but only without integer post-training optimization, because I get the same error:
`Failed to parse the model: Only models with a single subgraph are supported, model had 4 subgraphs.`

Thanks

**Comment by daverim** [comment]
Hi @AnastGerus, we have fixed this issue since 
https://github.com/tensorflow/tensorflow/commit/cd5a9ad1338b01f5fd8ce64ed86ad09bf26468ee, could you try again with latest version of tf-nightly?

**Comment by BigBerny** [comment]
> Hi @AnastGerus, we have fixed this issue since
> [cd5a9ad](https://github.com/tensorflow/tensorflow/commit/cd5a9ad1338b01f5fd8ce64ed86ad09bf26468ee), could you try again with latest version of tf-nightly?

Is this also fixed for GRUs?

**Comment by AnastGerus** [comment]
Hi @daverim,
Yes, it works with the latest version of tf-nightly. Thank you!
But it still can't convert with integer post-training optimization, because of error:
`Failed to parse the model: Op FlexVarHandleOp missing inputs.`
My model is a basic LSTM layer that was converted by PyTorch - ONNX - TF path. So when I import the model to TF I can't fix the input shapes by hand. Could you please recommend to me the way to convert the model with integer optimization?
```
onnx_model = onnx.load(path_to_onnx)
model = prepare(onnx_model, 'CPU') 
model.export_graph(path)
```

**Comment by daverim** [comment]
@AnastGerus 

When you converting from onnx, could you try converting to a saved_model? And then using `converter.from_saved_model`?
You may need to add `converter.experimental_enable_resource_variables` as well.

Thanks,
David

**Comment by AnastGerus** [comment]
@daverim 

That is what I'm doing:

```
onnx_model = onnx.load(path_to_onnx)
model = prepare(onnx_model, 'CPU')
model.export_graph(path) 

converter = tf.lite.TFLiteConverter.from_saved_model(path)
converter.experimental_enable_resource_variables = True
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
  tf.lite.OpsSet.SELECT_TF_OPS
]

converter.optimizations = [tf.lite.Optimize.DEFAULT]

def representative_dataset():
    with open('dataset.p', 'rb') as fp:
        tensors_list = pickle.load(fp)
    for tensor in tensors_list:
        tensor = np.asarray(tensor, dtype = np.float32)
        h_tensor = np.zeros((1,1,512), dtype = np.float32)
        c_tensor = np.zeros((1,1,512), dtype = np.float32)
        yield [h_tensor, c_tensor, tensor]

converter.representative_dataset = representative_dataset
tflite_model = converter.convert()
```

And I get:
```
  File "...\lib\site-packages\tensorflow\lite\python\optimize\calibrator.py", line 78, in __init__
    raise ValueError("Failed to parse the model: %s." % e)
ValueError: Failed to parse the model: Op FlexVarHandleOp missing inputs.
```

I'm trying to do it with the simplest one LSTM layer, but it has the same issue.

Thanks,
Anastasiia

**Comment by daverim** [comment]
Hi @AnastGerus, it seems that the varhandle op is getting converted via
select_tf_ops. Do you require this? It seems that if you remove
select_tf_ops it should work. Otherwise, the calibrator is missing support
for FlexVarHandleOp, and needs a fix.

Please let me know if removing select tf ops is ok, and if not, will work
on a fix for the calibrator.

**Comment by AnastGerus** [comment]
Hi @daverim,
Unfortunately "select_tf_ops" can't be removed for LSTM, because (even without any optimizations) you will get an error:
```
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: AssignVariableOp, ReadVariableOp, VarHandleOp
Details:
	tf.AssignVariableOp(tensor<!tf.resource<tensor<2048xf32>>>, tensor<2048xf32>) -> ()
	tf.AssignVariableOp(tensor<!tf.resource<tensor<2048xf32>>>, tensor<2048xf32>) -> () : {device = ""}
	tf.AssignVariableOp(tensor<!tf.resource<tensor<?x?xf32>>>, tensor<1024x2048xf32>) -> () : {device = ""}
	tf.AssignVariableOp(tensor<!tf.resource<tensor<?x?xf32>>>, tensor<1x1xf32>) -> ()
	tf.ReadVariableOp(tensor<!tf.resource<tensor<2048xf32>>>) -> (tensor<2048xf32>) : {device = ""}
	tf.ReadVariableOp(tensor<!tf.resource<tensor<?x?xf32>>>) -> (tensor<?x?xf32>) : {device = ""}
	tf.VarHandleOp() -> (tensor<!tf.resource<tensor<2048xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_bias_lstm_7"}
	tf.VarHandleOp() -> (tensor<!tf.resource<tensor<?x?xf32>>>) : {allowed_devices = [], container = "", device = "", shared_name = "lstm_kernel_lstm_7"}
```
So I suppose it needs a fix in the calibrator.

But the possibility to remove "select_tf_ops" for LSTM also would be a good solution, because "select_tf_ops" makes TFLite library binary size increase drastically.

Thank you,
Anastasiia

**Comment by AnastGerus** [comment]
Hi again, @daverim 
In addition to my previous comment, I have reproduced this issue using only the Keras LSTM layer. _AssignVariableOp, ReadVariableOp, VarHandleOp_ are needed when you use `stateful=True` for LSTM layer (that is very important option for "infinite" data (e.g. audio stream)).

Could you please estimate how much time such a fix could take? Is it worth waiting?

Thanks,
Anastasiia
