### ISSUE TITLE
OutOfRangeError Unknown Error when extracting particular zip file

### ISSUE THREAD

**Issue by BrEr** [tensorflow/tensorflow#35630]
Please be aware this issue was originally posted in tensorflow/datasets but I got directed here as it seems that the issue is related to the GFile implementation:
https://github.com/tensorflow/datasets/issues/1337

**Short description**
When the download of imagenet_resized finished and tfds starts extracting/writing records, the program crashes.

You can reproduce this error by downloading the particular zip file manually and extracting it with tensorflow:

http://www.image-net.org/image/downsample/Imagenet32_train_npz.zip

**Environment information**
* Operating System: Windows 10
* Python version: 3.7
* tensorflow-datasets version: 1.3.2
* tensorflow-gpu version: 2.0.0

**Reproduction instructions**
Without TFDS:
```
import zipfile
import tensorflow.compat.v2 as tf

path = 'path/to/file.zip'
with tf.io.gfile.GFile(path, 'rb') as fobj:
  z = zipfile.ZipFile(fobj)
  for member in z.infolist():
    extract_file = z.open(member)
    print(member.filename)
```

With TFDS:

```
import tensorflow_datasets as tfds

imagenet_data, info = tfds.load(name="imagenet_resized/32x32", with_info=True, as_supervised=True)
```

**Link to logs**
```
Dl Size...: 100%|██████████| 3414/3414 [22:47<00:00,  2.60 MiB/s]



0 examples [00:00, ? examples/s]Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_datasets\core\file_format_adapter.py", line 199, in incomplete_dir
    yield tmp_dir
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_datasets\core\dataset_builder.py", line 333, in download_and_prepare
    download_config=download_config)
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_datasets\core\dataset_builder.py", line 1008, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_datasets\core\dataset_builder.py", line 871, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_datasets\core\dataset_builder.py", line 1033, in _prepare_split
    total=split_info.num_examples, leave=False):
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tqdm\_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_datasets\image\imagenet_resized.py", line 141, in _generate_examples
    for fname, fobj in archive:
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_datasets\core\download\extractor.py", line 179, in iter_zip
    z = zipfile.ZipFile(fobj)
  File "C:\Program Files\Python37\lib\zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python37\lib\zipfile.py", line 1288, in _RealGetContents
    endrec = _EndRecData(fp)
  File "C:\Program Files\Python37\lib\zipfile.py", line 259, in _EndRecData
    fpin.seek(0, 2)
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\lib\io\file_io.py", line 167, in seek
    offset += self.size()
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\lib\io\file_io.py", line 102, in size
    return stat(self.__name).length
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\lib\io\file_io.py", line 727, in stat
    return stat_v2(filename)
  File "C:\Users\[username]\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\lib\io\file_io.py", line 744, in stat_v2
    pywrap_tensorflow.Stat(compat.as_bytes(path), file_statistics)
tensorflow.python.framework.errors_impl.OutOfRangeError: C:\Users\[username]\tensorflow_datasets\downloads\image-net.org_image_downs_Image_train_npzlCJjN-zBsDCdn80BZxJ6qtyTFYcDX7y1OSUjXtuuxPw.zip; Unknown error

Process finished with exit code 1
```
**Expected behavior**
No error

**Comment by BrEr** [comment]
Per instructions from @Conchylicultor I redownloaded the file after which I got the same error. I also tried their minimal example which results in the same error:

```
path = 'C:\Users\[username]\tensorflow_datasets\downloads\image-net.org_image_downs_Image_train_npzlCJjN-zBsDCdn80BZxJ6qtyTFYcDX7y1OSUjXtuuxPw.zip'
with tf.io.gfile.GFile(path, 'rb') as fobj:
  z = zipfile.ZipFile(fobj)
  for member in z.infolist():
    extract_file = z.open(member)
    print(member.filename)
```

**Comment by BrEr** [comment]
Confirmed not be an issue on Ubuntu 18.04

**Comment by Conchylicultor** [comment]
@BrEr thanks for the update. It seems that this is not an issue with tfds.
Could you link the url of the zip file that make `tf.io.gfile` crash ?

**Comment by oanush** [comment]
@BrEr ,
Could you try instruction from @Conchylicultor  usage of tf.io.gfile ?thanks!

**Comment by BrEr** [comment]
> @BrEr ,
> Could you try instruction from @Conchylicultor usage of tf.io.gfile ?thanks!

I did try GFile:

https://github.com/tensorflow/tensorflow/issues/35630#issuecomment-571468035

**Comment by BrEr** [comment]
@Conchylicultor the url, as extracted from source is:

http://www.image-net.org/image/downsample/Imagenet32_train_npz.zip

found in:

https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/imagenet_resized.py

**Comment by BrEr** [comment]
Any updates on this? I still did not figure this issue out.

**Comment by gowthamkpr** [comment]
@BrEr The reason for the error is that The `txt` file was missing from the `setup.py`. Its been fixed in tfds-nightly. Please check it and confirm it. 

For more information, please take a look at the following [issue](https://github.com/tensorflow/datasets/issues/1304). Thanks!

**Comment by BrEr** [comment]
The issue described in the linked issue is different from what I am experiencing. It also does not fix the issue. 8x8 is working.

**Comment by Conchylicultor** [comment]
@gowthamkpr 
From what I understand of the issue, `tf.io.gfile` fails to extract the following file on windows. This seems unrelated to TFDS. I do not have access to windows so cannot reproduce the issue.

@BrEr You should update the issue description with better title/description. The current one makes it look like the issue is related to TFDS which it is not, so it's not surprising that TF team do not look at it.

Update your comment with the exact minimal reproductions instructions (where to download the file,...), informations on which TF version, OS, full stacktrace (pasted as gist),...
Do not mention TFDS if the bug can be reproduced with TF only. Try to keep instructions as minimal as possible. Something like:

Problem encounter:
...

System information:
...

Reproduction instruction:

Download: http://www.image-net.org/image/downsample/Imagenet32_train_npz.zip
```
import zipfile
import tensorflow.compat.v2 as tf

path = 'path/to/file.zip'
with tf.io.gfile.GFile(path, 'rb') as fobj:
  z = zipfile.ZipFile(fobj)
  for member in z.infolist():
    extract_file = z.open(member)
    print(member.filename)
```

**Comment by BrEr** [comment]
I filed this bug in Tensorflow because you asked me to in the original issue in TFDS .  https://github.com/tensorflow/datasets/issues/1337

I don't know if the issue is not related to TFDS, for me it only occurs with one specific dataset (Imagenet resized 32x32 and 64x64) using TFDS. I haven't been able to reproduce the issue in any other way.

I have updated the instruction a bit.

**Comment by Conchylicultor** [comment]
@BrEr Thanks for updating the description. Please also update the description to add the stracktrace that you get when running without TFDS.

> I don't know if the issue is not related to TFDS, for me it only occurs with one specific dataset (Imagenet resized 32x32 and 64x64) using TFDS. I haven't been able to reproduce the issue in any other way.

I though you were able to reproduce the issue by running the code snippet that you added. Could you confirm and add the full stacktrace that you're getting when you running the code ? If so, the code snippet do not depends on TFDS, so no change in TFDS will be able to solve this particular error.

**Comment by gowthamkpr** [comment]
@BrEr Can you please reply to @Conchylicultor comment above. Thanks!

**Comment by Xinihiko** [comment]
Changed the file extractor.py in line 131

```
    with tf.io.gfile.GFile(path_or_fobj, 'rb') as f_obj:
```
into 
```
    with open(path_or_fobj, 'rb') as f_obj:
```
which becomes
```
@contextlib.contextmanager
def _open_or_pass(path_or_fobj):
  if isinstance(path_or_fobj, six.string_types):
    with open(path_or_fobj, 'rb') as f_obj:
      yield f_obj
  else:
    yield path_or_fobj
```
and everything works by using 

```
import tensorflow_datasets as tfds

tfds.load('imagenet_resized/32x32')
```

**Comment by Conchylicultor** [comment]
@Xinihiko, thank you for the update. This seems to confirm this is a `tf.io.gfile` bug.

**Comment by csmcallister** [comment]
Chiming in because I am receiving this same `OutOfRangeError` on Windows 10 with:

```
import tensorflow_datasets as tfds
coco_data = tfds.load('coco/2017') 
```

The offending file is `tensorflow_datasets\downloads\images.cocodataset.org_zips_train2017aai7WOpfj5nSSHXyFBbeLp3tMXjpA_H3YD4oO54G2Sk.zip`.

I can provide the full traceback if you'd like, but it's the same as the one above and I'd rather not spam the issue.

**Comment by sachinprasadhs** [comment]
The above mentioned URL is not working, can you please update the URL.
