### ISSUE TITLE
`python': double free or corruption

### ISSUE THREAD

**Issue by Joshuaalbert** [tensorflow/tensorflow#36004]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
**Scientific Linux 7.7 (Nitrogen) 
Linux 3.10.0-1062.9.1.el7.x86_64** 
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below):
**v1.15.0-rc3-22-g590d6ee 1.15.0**
Same problem occurs with tf 1.14
- Python version:
**3.6**
- Bazel version (if compiling from source):
**NA**
- GCC/Compiler version (if compiling from source):
**4.8.5**
- CUDA/cuDNN version:
**NA, running on CPU**
- GPU model and memory:
**NA**

**Describe the current behavior**

I am using PBS to submit jobs to a homogeneous cluster. Each job is allocated up to 192GB memory, and the job itself uses only 50GB at peak. Each job is a loop that iteratively solves around 1000 Gaussian process regression problems using TF. In pseudo-code it is,
``` python
def job():
  N=1000
  for i in range(N):
    with tf.Session(graph=tf.Graph()) as sess:
      solve_gp_problem(sess, sess.graph)
      # around i ~ 300 we get `python': double free or corruption
      # but only in ~50% of the jobs that are submitted (with the exact same data)
```
Each Gaussian process problem creates its own graph and session, and lasts approximately 10 seconds. Then the graph and session are not referenced again (and should be garbage collected). The job uses no multiprocessing or threading outside of TF's inherent use. 

Approximately 50% of my jobs are abruptly failing with ``python': double free or corruption` and a long stack trace, after approximately 1/3 of the work is done. This happens also when I give the jobs the exact same input data.

**Describe the expected behavior**

Some memory is trying to be freed twice in tensorflow, which should not happen. 

**Code to reproduce the issue**
This error cannot be deterministically reproduced since it doesn't occur all of the time. However, it looks like this,
``` python
import tensorflow.compat.v1 as tf
def loss(x):
  return tf.reduce_sum(x ** 2)

def loss_and_grad(x):
  l = loss(x)
  return l, tf.gradients(l, [x])[0]

def build_loss_np(sess):
  x_pl = tf.placeholder(tf.float32)
  l_g = loss_and_grad(x_pl)
  def _loss(x):
    return sess.run(l_g, {x_pl: x})
  return _loss

from scipy.optimize import minimize
for i in range(1000):
  with tf.Session(graph=tf.Graph()) as sess:
    loss_func = build_loss_np(sess)
    # stand-in for GP hyper parameter optimisation and regression
    res = minimize(loss_func, [0], method='BFGS', jac=True)
```

**Other info / logs**
The only consistent thing I notice is that the failure usually occurs around the same point after about 300 loops. Therefore there would be 300 graphs and sessions created.
The code that performs the gaussian process regression is a solid code base called GPFlow.
[traceback.log](https://github.com/tensorflow/tensorflow/files/4079155/traceback.log)

**Comment by gowthamkpr** [comment]
@Joshuaalbert I tried running the code above in colab but ran into an error. Please take a look at it [here](https://colab.sandbox.google.com/gist/gowthamkpr/2cf51a1edacf960ff35581392bebd515/untitled277.ipynb) and let me know if you are facing the same issue. Thanks!

**Comment by Joshuaalbert** [comment]
I fixed the error in the colab. My bad, I placed the session in the wrong location.

**Comment by mihaimaruseac** [comment]
By "the error" do you mean the double free/corruption or just the error @gowthamkpr mentioned?

If the double free/corruption is fixed, can we close?

**Comment by gowthamkpr** [comment]
Yes This error has been fixed @mihaimaruseac I am closing this issue.

**Comment by Joshuaalbert** [comment]
@mihaimaruseac  @gowthamkpr please reopen this issue, as the problem is not resolved. The colab notebook that gow shared runs now that I fixed the code to do as I intended. But, please reread the issue report again. I said this is a non-deterministic problem. That is, it occurs in roughly 50% of jobs that I run, when they are run with identical input parameters.

**Comment by gowthamkpr** [comment]
@Joshuaalbert I don't see any changes in my colab notebook. Can you please share  your colab gist. Thanks!

**Comment by Joshuaalbert** [comment]
@gowthamkpr I updated the first post to show the correct code.

**Comment by gowthamkpr** [comment]
@Joshuaalbert I tried running it multiple times on colab but I didn't run into ``python': double free or corruption` error

**Comment by Joshuaalbert** [comment]
@gowthamkpr Indeed, this is non-deterministic. This problem requires thinking outside the normal MVCE box, and requires solving a puzzle by someone who really understands the TF system. The example that I provide (as stated in the issue) is the conceptual program. The clues that I can provide you are: 
 - it occurs about 50% of the time 
 - it does not occur right away, but after several hundred loops in the conceptual program
 - it will have created a session and graph each iteration of the loop, each of which should be garbage collected.
 - that a memory pointer is trying to be freed twice, which produces the error
 - it occurs on a cluster, where every node only has one job running on it
 - the job is containerized, yet the error does not occur on another cluster 

Questions:
 - How does tensorflow deal with garbage collection?
 - Is there some reason that different CPUs might cause problems with memory allocation/freeing?
 - If you look at the traceback, can you find any peculiar things?

**Comment by byronyi** [comment]
@Joshuaalbert It may because your OS is too old for latest NumPy.

Try `pip install --ignore-installed --no-binary=:all: numpy==1.16.2`.

**Comment by mihaimaruseac** [comment]
@Joshuaalbert if we cannot reproduce it we cannot provide a fix for it. The example you provide should be as complete as possible

**Comment by Joshuaalbert** [comment]
@byronyi I will try this now. The jobs take several hours to complete, so I should know in a few hours if this resolves the issue. I have to run a large batch to be certain.

@mihaimaruseac Not all computer problems are deterministic, yet that does not rule out attempting to resolve them. A good blog post on it is [this](https://www.tablix.org/~avian/blog/archives/2014/10/on_hunting_non_deterministic_bugs/), and an even better paper about it is [this](https://www.hindawi.com/journals/sp/2018/8939027/).

**Comment by mihaimaruseac** [comment]
I know that, but thank you for the links.

As some background, I'm working on creating better tools for debugging these issues. But don't have something usable at the moment.

**Comment by Joshuaalbert** [comment]
@mihaimaruseac That interesting. Would a real-time tool like [osquery](https://osquery.io/) be useful for logging things before they fail?

**Comment by Joshuaalbert** [comment]
@byronyi So it seems that did not work. Should numpy by 1.16.2 always for stability? Anyways, where next can I look?

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
