### ISSUE TITLE
 output 'tensorflow/core/kernels/_objs/reduction_ops_gpu/tensorflow/core/kernels/reduction_ops_half_mean_sum.cu.pic.o' was not created

### ISSUE THREAD

**Issue by vivien624** [tensorflow/tensorflow#36553]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Python version**:3.6.6
- **Bazel version (if compiling from source)**:0.11.1
- **GCC/Compiler version (if compiling from source)**:7.3.0
- **CUDA/cuDNN version**:CUDA10.0  , cuDNN 7
- **GPU model and memory**:GTX1050
- **Exact command to reproduce**:
```

### Describe the problem 
While I run the code '''' from https://github.com/VLOGroup/mri-variationalnetwork

I'm using Ubuntu18.04,
bazel 0.11.1
Cuda10.0
cuDNN7.4

I think some attributes not compile in the file " paramdefination.py"
```
def plt_act_function(x, phi):
    my_dpi = 96.
    fig = matplotlib.figure.Figure(figsize=(350/my_dpi, 250/my_dpi), dpi=my_dpi)
    ax = fig.add_subplot(1, 1, 1)
    images = []
    for s in range(phi.shape[0]):
        images_stage = []
        for i in range(phi.shape[1]):
            ax.clear()
            ax.plot(x, phi[s, i, :])
            if fig.canvas is None:
                FigureCanvasAgg(fig)
            fig.canvas.draw()
            img_data = np.fromstring(fig.canvas.tostring_rgb(), dtype=np.uint8, sep='')
            img_data = img_data.reshape(fig.canvas.get_width_height()[::-1] + (3,))
            images_stage.append(img_data)
        images.append(images_stage)
    return np.asarray(images)
```

This is the following issue:

2020-02-09 14:45:41.165513: W tensorflow/core/framework/op_kernel.cc:1198] Unknown: AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_rgb'
Traceback (most recent call last):
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_call
return fn(*args)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
status, run_metadata)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in exit
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_rgb'
[[Node: activation_plot/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](activation_plot/strided_slice/_371, activation_plot/Reshape_1/_373)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "train_mri_vn.py", line 315, in
coord.join(enqueue_threads_data)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 387, in join
six.reraise(*self._exc_info_to_raise)
File "/home/vivi/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
raise value
File "train_mri_vn.py", line 295, in
options=run_options, run_metadata=run_metadata)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
run_metadata_ptr)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
feed_dict_tensor, options, run_metadata)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1344, in _do_run
options, run_metadata)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1363, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_rgb'
[[Node: activation_plot/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](activation_plot/strided_slice/_371, activation_plot/Reshape_1/_373)]]

Caused by op 'activation_plot/PyFunc', defined at:
File "train_mri_vn.py", line 176, in
vn.paramdefinitions.add_activation_function_params(params, reg_config['activation1'])
File "/home/vivi/mri-variationalnetwork-master/vn/paramdefinitions.py", line 70, in add_activation_function_params
phi_img = tf.py_func(plt_act_function, [x_plt_tf[:, 0], phi_plt], tf.uint8)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 300, in py_func
func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in _internal_py_func
input=inp, token=token, Tout=Tout, name=name)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 93, in _py_func
"PyFunc", input=input, token=token, Tout=Tout, name=name)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
op_def=op_def)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
op_def=op_def)
File "/home/vivi/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in init
self._traceback = self._graph._extract_stack() # pylint: disable=protected-access

UnknownError (see above for traceback): AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_rgb'
[[Node: activation_plot/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](activation_plot/strided_slice/_371, activation_plot/Reshape_1/_373)]]

**Comment by gadagashwini** [comment]
@vivien624, Please provide the complete code to replicate the reported issue and also Tensorflow version that you are using. Thanks!

**Comment by gadagashwini** [comment]
@vivien624, Any update?

**Comment by vivien624** [comment]
I think I figured it out. Thank you very much.

gadagashwini <notifications@github.com> 于2020年2月17日周一 上午5:45写道：

**Comment by gadagashwini** [comment]
@vivien624, Glad that it resolved.

**Comment by cecilr14** [comment]
@vivien624, I am having the same issue. How did you resolve it? Thanks!

**Comment by 1lol** [comment]
> @vivien624, I am having the same issue. How did you resolve it? Thanks!
See this issue: https://github.com/tensorflow/tensorflow/issues/28796
and it was  resolved by https://github.com/tensorflow/tensorflow/commit/3c245f52912612ed9d8e20245ddb5de055680969

**Comment by vivien624** [comment]
See this issue: #28796
<https://github.com/tensorflow/tensorflow/issues/28796>
The comment from Tayseer-bme <https://github.com/Tayseer-bme> gives
solution:
https://github.com/tensorflow/tensorflow/issues/28796#issuecomment-496881881
and it was resolved by 3c245f5
<https://github.com/tensorflow/tensorflow/commit/3c245f52912612ed9d8e20245ddb5de055680969>

cecilr14 <notifications@github.com> 于2020年4月2日周四 下午12:06写道：

**Comment by cecilr14** [comment]
@vivien624, Thanks! Sadly, the above changes do not work for me. I am using Tensorflow's r1.8 branch which already has the commit 3c245f5 and am still getting the error:
'FigureCanvasBase' object has no attribute 'tostring_rgb
in paramdefinitions.py
