### ISSUE TITLE
ReduceLROnPlateau callback crashed when learning rate is of type tf.keras.optimizers.schedules

### ISSUE THREAD

**Issue by dd1923** [tensorflow/tensorflow#36612]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip3
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6

**Describe the current behavior**

When using tf.keras.callbacks.ReduceLROnPlateau in callbacks in model.fit(), it fails with an error if model.optimizer.lr is of type  tf.keras.optimizers.schedules. *. 

For example, one can use tf.keras.optimizers.schedules.ExponentialDecay in an optimizer. This would cause the following line to fail:

[https://github.com/tensorflow/tensorflow/blob/6dd3403a89f2f0f9a6219ba926091e203693ff9f/tensorflow/python/keras/callbacks.py#L2021](https://github.com/tensorflow/tensorflow/blob/6dd3403a89f2f0f9a6219ba926091e203693ff9f/tensorflow/python/keras/callbacks.py#L2021)

Above line assumes lr to be a float.

The error it gives in this case is :

TypeError: float() argument must be a string or a number, not 'ExponentialDecay' 

**Describe the expected behavior**

ReduceLROnPlateau should also work with learning rate whose type is of tf.keras.optimizers.schedules

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment]
@dd1923 

Will it be possible to share simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!

**Comment by dd1923** [comment]
@ravikyram Here is the [colab link](https://colab.research.google.com/drive/1bULTBS7TYFrSOtYbLoqaHj0zM0Tr2zU3).

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.1.0, 2.2.0-dev20200211 and was able to reproduce the issue. Thanks!

**Comment by dd1923** [comment]
Any updates?

**Comment by dd1923** [comment]
@jvishnuvardhan ?

**Comment by Demetrio92** [comment]
Same here. ReduceLRonPlateau does not play well with ExponentialDecay. Providing `lr` as a simple constant works. 

```python
tf.__version__
2.2.0

tf.keras.__version__
2.3.0-tf
```

**Comment by dd1923** [comment]
Doesn't look like anyone from tf team is interested in fixing any bugs. I have had a few others open for a long time now.

**Comment by Demetrio92** [comment]
@dd1923 it's open-source, so you can only complain if you have an MR fixing the bug, but no one reviews it. And even then, you have the liberty to fork the repo and maintain a better fork. 

Especially, this issue seems to be easily fixable with just python knowledge.

**Comment by jvishnuvardhan** [comment]
@dd1923 Extremely sorry for missing this issue. I could reproduce the issue with `TF2.2`. However, I ran your code with `tf-nightly` and I cannot reproduce the issue. The callback is working without any error. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f8a79e46abbbcb2b5aa25636d25f0433/reducelronplateau-bug.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
I am closing this issue as this was resolved in `tf-nightly`. If you want to use stable version, then please wait for some time. Stable `TF2.3` will be released in near future. Thanks!

**Comment by dcleres** [comment]
I update my Tensorflow version to `2.3.0`, However, the behavior still persists on my machine. I am trying to combine `tf.keras.optimizers.schedules.ExponentialDecay`with `tf.keras.callbacks.ReduceLROnPlateau` with no luck. Thank you for your help. 

Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Catalina 10.15.6
TensorFlow installed from (source or binary): pip3
TensorFlow version (use command below): 2.3.0
Python version: 3.7

**Comment by jvishnuvardhan** [comment]
@dcleres Can you please create a new issue with a simple standalone code to reproduce the issue? Thanks!
