### ISSUE TITLE
Is Tensorflow impossible to predict multiple steps?

### ISSUE THREAD

**Issue by Lay4U** [tensorflow/tensorflow#36808]
Thank you for reading. I'm not good at English. 

I am wondering how to predict and get future time series data after model training. I would like to get the values after N steps.

So, I used the time series in the Tensorflow tutorial to practice predicting the model.

```
a = y_val[-look_back:] 
for i in range(N-step prediction): #predict a new value n times.
    tmp = model.predict(a.reshape(-1, look_back, num_feature)) #predicted value     
    a = a[1:] #remove first     
    a = np.append(a, tmp) #insert predicted value
```
The results are predicted by linear graphs from nonlinear graphs as shown below.

![1](https://imgur.com/7tenqRd.png)

How can I get the actual, right solution? or Is Tessorflow impossible to predict multiple steps?

[full source](https://gist.github.com/Lay4U/96e0ba8d8c251046e89eae4bc5d40510)  (After the 25th line is my code.)

[epoch=100](https://gist.github.com/Lay4U/3c530649934af39a6c6e9884a8eb14fd)

**Comment by foxik** [comment]
You did not train the model (no `.fit` method is called).

**Comment by Lay4U** [comment]
> You did not train the model (no `.fit` method is called).



> You did not train the model (no `.fit` method is called).

Thank you. Updated the .fit call.

**Comment by gadagashwini** [comment]
@Lay4U, Are you happy to close this issue as it is resolved. Thanks!

**Comment by Lay4U** [comment]
> @Lay4U, Are you happy to close this issue as it is resolved. Thanks!

No.. The problem was updated and not solved. Still predict plots linear.

**Comment by foxik** [comment]
I am not part of official TF development team, but I believe this issue tracker should be used to report bugs or feature requests. In this case there seems to be nothing wrong with TF, but instead you would like to get help about TF -- there are better places where to get it, for example on https://stackoverflow.com.

BTW, you should probably not use `y_val_uni` on _input_, given it contains valid _outputs_, you should instead use one of `x_val_uni`. And after 100 steps where the model gets its own predictions (which are not particularly good) on input, the results are not very surprising.

**Comment by Lay4U** [comment]
> I am not part of official TF development team, but I believe this issue tracker should be used to report bugs or feature requests. In this case there seems to be nothing wrong with TF, but instead you would like to get help about TF -- there are better places where to get it, for example on https://stackoverflow.com.
> 
> BTW, you should probably not use `y_val_uni` on _input_, given it contains valid _outputs_, you should instead use one of `x_val_uni`. And after 100 steps where the model gets its own predictions (which are not particularly good) on input, the results are not very surprising.

Thank you for answer and when I use `x_val_uni` and after `20 steps` result is ![here](https://gist.github.com/Lay4U/4471f4ed9b80a615de42be54fdaaa4ed)

I think this method also not right how do you think?

**Comment by gowthamkpr** [comment]
@Lay4U Please go through this [tutorial](https://www.tensorflow.org/tutorials/structured_data/time_series). Closing this issue as it has been resolved. If you have any more questions and are related to bug/performance, build/install, docs or feature request related issues please create a new issue. If they are not related, please post them in stackoverflow. Thanks!
