### ISSUE TITLE
import tensorflow is very slow

### ISSUE THREAD

**Issue by hankcs** [tensorflow/tensorflow#37729]
<em>Please make sure that this is an issue related to performance of TensorFlow.
As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:performance_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04):  Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): binary
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: Python 3.6.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: 
CUDA Version: 10.1
cudnn-10.1
- GPU model and memory:
TITAN RTX
24190MiB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm thinking about using tensorflow 2.x for research. However, every time I import tf, it takes about 5 seconds.  `import tensorflow` is 10 times slower than`import torch`. 

**Describe the expected behavior**
I was expecting the two to be roughly the same level for a fresh import. I know these two libraries have their own design choices. But I'm just wondering is there any chance to speed up the import statement. As a researcher, I need to constantly debug and 5s is just not good.

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
from timeit import default_timer as timer
import os

print('import pytorch')
start = timer()
import torch

end = timer()
print('Elapsed time: ' + str(end - start))

print('import tensorflow')
start = timer()
import tensorflow

end = timer()
print('Elapsed time: ' + str(end - start))
```
**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
import pytorch
Elapsed time: 0.46338812075555325
import tensorflow
Elapsed time: 4.396180961281061
```

**Comment by hankcs** [comment]
The log to trace import `python3 -v -c 'import tensorflow' 2>&1 | ts '%H:%M:%.S' | grep 'import ' > log.txt` is attached below. 

[log.txt](https://github.com/tensorflow/tensorflow/files/4357125/log.txt)

**Comment by Saduf2019** [comment]
@hankcs 
i have executed your code in nightly and this is been fixed in nightly, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/630d50d7ee9c483d10ad99f23702129d/37729.ipynb)

**Comment by hankcs** [comment]
> @hankcs
> i have executed your code in nightly and this issue does not exist in nightly, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/630d50d7ee9c483d10ad99f23702129d/37729.ipynb)

Thank you for your reply. I'm still getting similar performance with tf-nightly. In colab pytorch got 0.2s but tf-nightly got 2s. I ran your gist too, the results are similar.

See https://colab.research.google.com/drive/1-NUqqa7W_6_rYP3r09uSm6pnYHQXtLoh

**Comment by jvishnuvardhan** [comment]
@hankcs I tried several time with `TF2.1` and `tf-nightly` and I could not reproduce the issue. Some time TF is faster and sometime Pytorch is faster but the difference is not much. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/1b4db6482cc71218451f1e4b7ed120cb/untitled36.ipynb). 

Output is as follows

```
import pytorch
Elapsed time: 2.196739539999996
import tensorflow
Elapsed time: 1.7435289440000048
```

I have a question. Are you importing it in `for` loop?. You can import once and run your code multiple times to debug. Thanks!

Please close the issue if this was resolved for you. Thanks!

**Comment by hankcs** [comment]
> I have a question. Are you importing it in for loop?. You can import once and run your code multiple times to debug. Thanks!

No, I'm importing only once. Redundant import takes no time.

I found some clues. If I terminate the colab session then execute your gist, pytorch takes 2 seconds and tf takes 1-4 seconds which shows they are on the same level. 
<img width="768" alt="hankcs com 2020-03-20 at 5 00 25 PM" src="https://user-images.githubusercontent.com/5326890/77205952-58912000-6acc-11ea-9a60-117b9cd7480b.png">
**However, if I restart the runtime, pytorch takes 0.2 second but tf still takes 2 seconds.**
<img width="322" alt="hankcs com 2020-03-20 at 5 01 01 PM" src="https://user-images.githubusercontent.com/5326890/77205999-6777d280-6acc-11ea-9968-a58b70cfa1c6.png">

These shows that pytorch can make use of cache in memory while tf somehow can not. If you restart the session (reboot the system), there is no cache then they perform the same.

**Comment by jvishnuvardhan** [comment]
@hankcs I ran the colab you shared and I got the similar results as I showed. Check the following output. 

```
import pytorch
Elapsed time: 2.00347342200007
import tensorflow
Elapsed time: 1.8452622999998312
```

**Comment by jvishnuvardhan** [comment]
@hankcs Can you please check the same in your local? Thanks!

**Comment by hankcs** [comment]
Sure, my local machine running 2.1.0 gives similar result to what I observe in colab.

```
import pytorch
Elapsed time: 0.45859437994658947
import tensorflow
2.1.0
Elapsed time: 4.311788005754352
```

I'll report tf-nightly later as I have some jobs running.

**Comment by mihaimaruseac** [comment]
```
(t) mihaimaruseac@ankh:/tmp/t$ pip install -q tensorflow torch
(t) mihaimaruseac@ankh:/tmp/t$ time python -c "import tensorflow"
2020-03-20 14:47:02.352581: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-20 14:47:02.352679: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-20 14:47:02.352694: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

real    0m8.390s
user    0m2.386s
sys     0m9.376s
(t) mihaimaruseac@ankh:/tmp/t$ time python -c "import tensorflow"
2020-03-20 14:47:18.194391: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-03-20 14:47:18.194475: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-03-20 14:47:18.194490: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

real    0m1.616s
user    0m3.429s
sys     0m3.624s
(t) mihaimaruseac@ankh:/tmp/t$ time python -c "import pytorch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pytorch'

real    0m0.066s
user    0m0.058s
sys     0m0.014s
(t) mihaimaruseac@ankh:/tmp/t$ time python -c "import torch"

real    0m7.498s
user    0m2.299s
sys     0m10.536s
(t) mihaimaruseac@ankh:/tmp/t$ time python -c "import torch"

real    0m0.547s
user    0m2.314s
sys     0m3.578s
```

There is indeed a slowdown in tf import but it looks like first import time is the same in both pytorch and TF.

We have an internal bug assigned for speeding up TF import

**Comment by hankcs** [comment]
Thank you. I'm grateful to know that tf teams are making efforts to address this issue. I'll promote tf in my research projects.

**Comment by epicmatthew21** [comment]
getting the same issue, any update?

**Comment by kozmaz87** [comment]
Also this seems to be a thing with caching by your operating system. On Windows the first time I load it by the time it imports may be 4 seconds+, which is unacceptable on an SSD on a Ryzen 9 computer. Then I close the interpreter and do it again, it imports in less than a second. This is why you fail to reproduce it in my humble opinion. Make sure you freshly restart your computer and run the test thereafter, also analyse the output of python -X importtime

**Comment by mihaimaruseac** [comment]
In my case the benchmarks were immediately after installing the pips, so they were not loaded in a cache.

For Windows, there is already a known issue regarding slow down to disk access when there are multiple files around https://github.com/microsoft/WSL/issues/4197

**Comment by zirui** [comment]
any update on this issue?
I have similar issue one my local mac machine:

```
import pytorch
Elapsed time: 0.302831451
import tensorflow
Elapsed time: 3.103030106
```

**System information**

* Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
* OS Platform and Distribution (e.g.,Linux Ubuntu 16.04):  macOS Big Sur version 11.01 
* TensorFlow installed from (source or binary): binary
* TensorFlow version (use command below):  2.3.1
* Python version: Python 3.7.1


and i test on a linux server, the result is similar(except that pytorch is slower)
```
import pytorch
Elapsed time: 1.786548773990944
import tensorflow
Elapsed time: 3.523564260045532
```

**System information**

* OS Platform and Distribution (e.g.,Linux Ubuntu 16.04):  Ubuntu 14.04.6 LTS
* TensorFlow installed from (source or binary): binary
* TensorFlow version (use command below):  1.15.4
* Python version: Python 3.6.5

**Comment by YashRunwal** [comment]
Hello guys,

Any updates? 

I am using a conda virtual environment.

`import tensorflow as tf` takes an absurd amount of time.

Note: I am using tensorflow cpu. 

What can be done to reduce this import time?

**Comment by MJimitater** [comment]
same issue, any updates?

**Comment by mohantym** [comment]
Was able to replicate the issue with TF v2.5 ,  Yes it takes more time when the program is loaded first time  , you might see the difference between first time and second time loading (less than a millisecond) ,  please find the [gist ](https://colab.research.google.com/gist/mohantym/601bd3691c224cf95894016bf3ceaefd/37729.ipynb)here ..Thanks!

**Comment by jvishnuvardhan** [comment]
@hankcs Looks like this was resolved in recent TF versions. I checked with `TF2.7` with CPU and GPU. [Here](https://colab.research.google.com/gist/jvishnuvardhan/5b8b89f8d3874e1df20d4dccde39b235/untitled36.ipynb) is a gist for reference. Thanks!

Results are very different where pytorch is 10x slower than TF. I am not sure whether this is something related to colab. Will check it on my local soon. Thanks!

```
# results with TF2.7 (CPU)
# import pytorch
# Elapsed time: 26.26447787500001
# import tensorflow
# Elapsed time: 2.672678635000011

# results with TF2.7 (GPU)
# import pytorch
# Elapsed time: 24.94221987399999
# import tensorflow
# Elapsed time: 2.79547692299991
```

**Comment by hankcs** [comment]
@jvishnuvardhan Thank for your efforts. Indeed tf2.6 has made significant improvements on its importing speed. Though it's still slower than torch1.10.

Tested on a MBP 2021 with M1 MAX

```
import tensorflow
Elapsed time: 1.139700959
import torch
Elapsed time: 0.383514875
```

Maybe macOS is just a rare case. I'm good with 1s importing time so I'll close this.

**Comment by vojtadavid** [comment]
It is still very slow. This was second run. Windows 11. 
` 
PS C:\Users\vojta> pip show tensorflow
Name: tensorflow
Version: 2.8.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\python39\lib\site-packages
Requires: gast, tensorflow-io-gcs-filesystem, keras, absl-py, grpcio, tf-estimator-nightly, wrapt, setuptools, astunparse, tensorboard, flatbuffers, opt-einsum, six, typing-extensions, keras-preprocessing, termcolor, protobuf, libclang, google-pasta, h5py, numpy
Required-by: tf-models-official, tensorflow-text
PS C:\Users\vojta> pip show tensorflow^C
PS C:\Users\vojta> python --version
Python 3.9.10
PS C:\Users\vojta> Measure-Command {python -c "import tensorflow"}
2022-03-03 20:47:27.191109: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-03-03 20:47:27.191369: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 3
Milliseconds      : 326
`

**Comment by kevinsuedmersen** [comment]
For me, it takes about 25 seconds to import tensorflow. Here is the output of `conda env export --no-builds`:
 ```yaml
 name: some_name
channels:
  - anaconda
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=20.2.0
  - backcall=0.2.0
  - bleach=3.2.1
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2021.5.30
  - cffi=1.15.0
  - colorama=0.4.4
  - debugpy=1.5.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - icu=58.2
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.18.1
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.9.2
  - libffi=3.4.2
  - libpng=1.6.37
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - nbconvert=5.5.0
  - nbformat=5.0.8
  - nest-asyncio=1.5.1
  - notebook=6.4.8
  - openssl=1.1.1m
  - packaging=20.4
  - pandoc=2.11
  - pandocfilters=1.5.0
  - parso=0.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - pycparser=2.20
  - pygments=2.7.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - python=3.10.0
  - python-dateutil=2.8.1
  - pywin32=302
  - pywinpty=2.0.2
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - sqlite=3.38.0
  - terminado=0.13.1
  - testpath=0.4.4
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - tzdata=2021e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - zipp=3.3.1
  - zlib=1.2.11
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - configobj==5.0.6
    - cycler==0.11.0
    - flatbuffers==2.0
    - fonttools==4.30.0
    - gast==0.5.3
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.44.0
    - h5py==3.6.0
    - idna==3.3
    - joblib==1.1.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.0
    - libclang==13.0.0
    - markdown==3.3.6
    - matplotlib==3.5.1
    - nltk==3.7
    - numpy==1.22.3
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - pandas==1.4.1
    - pillow==9.0.1
    - plotly==5.6.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytz==2021.3
    - regex==2022.3.15
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - six==1.16.0
    - tenacity==8.0.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.1.0
    - tqdm==4.63.0
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - werkzeug==2.0.3
    - wrapt==1.14.0
    - yellowbrick==1.4
prefix: C:\Users\my_username\Anaconda3\envs\some_name
```

**Comment by shixinlishixinli** [comment]
i also meet the same problem.  import tensorflow needs 1second.  
is there any solution to fix this  problem?

best
Lisa Shi

**Comment by Youjin1985** [comment]
It is still terribly slow
2.10 on linux

**Comment by RPGillespie6** [comment]
This issue happens all the time in GCP with 2.10. The very first `import tensorflow` is very slow (20+ seconds). The funny thing is, it doesn't seem to matter _where_ the first `import tensorflow` happens - it could even happen inside a docker container. But after that very first slow import, any subsequent imports (inside or outside docker container) are fast (1 second or less).

**Comment by wookayin** [comment]
Can we have this reopened and tracked somehow? I understand why the stalebot was added for such a large repository, but personally I don't like stale-bot closing and killing a long-wanted job suddenly... :|

**Comment by mohantym** [comment]
Hi @hankcs !
I just tested with 2.11 version and can see improvement in loading time w.r.to recurrent runs(1st , 2nd , 3rd).

1st run
```
import pytorch
Elapsed time: 2.934545137999976
import tensorflow
Elapsed time: 2.8405410590000884

```
2nd run
```
import pytorch
Elapsed time: 4.7490000042671454e-05
import tensorflow
Elapsed time: 4.4549999984155875e-05

```
3rd run 
```
import pytorch
Elapsed time: 4.4410000100469915e-05
import tensorflow
Elapsed time: 4.280999996808532e-05
```

Attached [gist](https://colab.sandbox.google.com/gist/mohantym/8413d11dd1d2544481f001a54cacabdf/git_37729.ipynb#scrollTo=U2UKsHlpp_yK) for reference.

Thank you!

**Comment by tomytsai1** [comment]
Thanks. Repeated the [gist](https://colab.research.google.com/gist/tomytsai1/c707355f8cf001b77a59f01d32d1ef80/tensorflow-import-speed.ipynb#scrollTo=QOcJDBJ2JtNb) test and it did show importing TensorFlow is slightly faster:
```
import pytorch
Elapsed time: 4.038670741000033
import tensorflow
2.11.0
Elapsed time: 3.876224701999945
```

**Comment by wookayin** [comment]
Should be active

**Comment by tomytsai1** [comment]
Ran the [gist](https://colab.sandbox.google.com/gist/tomytsai1/c707355f8cf001b77a59f01d32d1ef80/tensorflow-import-speed.ipynb#scrollTo=QOcJDBJ2JtNb) again and saw the same result that tensorflow is slightly faster to import than pytorch:
```
import pytorch
Elapsed time: 7.114853571999959
import tensorflow
2.9.2
Elapsed time: 6.9022292320000815
```

The result had some variations from run to run, but as far as the [original issue](https://github.com/tensorflow/tensorflow/issues/37729#issue-584716953) is concerned, the recent tensorflow version is definitely not much (10x) slower to import than pytorch as reported before and basically the two are on par at package loading.  Would suggest to close this ticket unless there is a new slowness issue.

**Comment by tomytsai1** [comment]
Will mark this (pytorch vs tensorflow import speed parity) as closed as the parity was matched.

At the same time, we do start to look into making TenosrFlow packages faster to import when not all modules are required and only the essential functions are needed, and hope it will bring us a easier-to-use package soon.
