### ISSUE TITLE
Error when trying to run on TPU - "Failed to connect to all addresses"

### ISSUE THREAD

**Issue by danieljannai** [tensorflow/tensorflow#39122]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, but it used to work. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.2.0-dev20200503
- Python version: 3.7.3

**Describe the current behavior**
Hi,
I'm trying to train a BERT-based model on a TPU (using TensorFlow models). It used to work perfectly a week ago, and I haven't changed my code since then, but now whenever I'm trying to run it (on a GCP VM instance connected to a TPU node) I get this:

```
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 196, in _create_device_dataset
    ds = _ReincarnatedPerDeviceGenerator(prototype_ds, incarnation_id)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py", line 181, in __init__
    **self._flat_structure)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2070, in generator_dataset
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 6810, in raise_from_not_ok_status
2020-05-03 15:47:19.234435: W tensorflow/core/distributed_runtime/eager/remote_tensor_handle_data.cc:76] Unable to destroy remote tensor handles. If you are running a tf.function, it usually indicates some op in the graph gets an error: failed to
 connect to all addresses
Additional GRPC error information:
{"created":"@1588520839.208445209","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3937,"referenced_errors":[{"created":"@1588520839.208443301","description":"f
ailed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: failed to connect to all addresses
Additional GRPC error information:
{"created":"@1588520839.208445209","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3937,"referenced_errors":[{"created":"@1588520839.208443301","description":"f
ailed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]} [Op:GeneratorDataset]
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py", line 2256, in async_wait
    context().sync_executors()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py", line 652, in sync_executors
    pywrap_tfe.TFE_ContextSyncExecutors(self._context_handle)
tensorflow.python.framework.errors_impl.UnavailableError: failed to connect to all addresses
Additional GRPC error information:
{"created":"@1588520839.208445209","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3937,"referenced_errors":[{"created":"@1588520839.208443301","description":"f
ailed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}
Exception ignored in: <function IteratorResourceDeleter.__del__ at 0x7f6cc39591e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 539, in __del__
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1224, in delete_iterator
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 6810, in raise_from_not_ok_status
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: failed to connect to all addresses
Additional GRPC error information:
{"created":"@1588520839.208445209","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3937,"referenced_errors":[{"created":"@1588520839.208443301","description":"f
ailed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]} [Op:DeleteIterator]
Exception ignored in: <function IteratorResourceDeleter.__del__ at 0x7f6cc39591e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 539, in __del__
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1224, in delete_iterator
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 6810, in raise_from_not_ok_status
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: failed to connect to all addresses
Additional GRPC error information:
{"created":"@1588520839.208445209","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3937,"referenced_errors":[{"created":"@1588520839.208443301","description":"f
ailed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]} [Op:DeleteIterator]
Exception ignored in: <function IteratorResourceDeleter.__del__ at 0x7f6cc39591e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 539, in __del__
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1224, in delete_iterator
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 6810, in raise_from_not_ok_status
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnavailableError: failed to connect to all addresses
Additional GRPC error information:
{"created":"@1588520839.208445209","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3937,"referenced_errors":[{"created":"@1588520839.208443301","description":"f
ailed to connect to all addresses","file":"third_party/grpc/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]} [Op:DeleteIterator]
2020-05-03 15:47:19.384278: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op 
ID: 144, Output num: 0
Additional GRPC error information:
{"created":"@1588520839.384194484","description":"Error received from peer ipv4:10.71.22.42:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handl
e: Op ID: 144, Output num: 0","grpc_status":3}
```

Any ideas about what could have happened?

**Comment by srihari-humbarwadi** [comment]
Possible duplicate of https://github.com/tensorflow/tensorflow/issues/39099

**Comment by ravikyram** [comment]
@danieljannai 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by danieljannai** [comment]
> @danieljannai
> 
> Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

Hi,
Unfortunately, I can't do that as my codebase is pretty big, but I can assure you that everything worked perfectly a week ago. I tried reverting to the tf-nightly version I used but it didn't help.

**Comment by danieljannai** [comment]
Solved here:
https://github.com/tensorflow/tensorflow/issues/39099

**Comment by fingoldo** [comment]
This bug is still there. I have tried many versions and combinations. When I create dataset using from_tensor_slices, it works fine (but only on small datasets. after that protobuf limitations come into play). But when I try from_generator, or when I'm trying to prepare dataset on th fly (by using tokenization inside of map), it's throwing "failed to connect to all addresses". I think TF team needs to do something with it.
