### ISSUE TITLE
Feature request: extend tf.select to broadcast a scalar condition

### ISSUE THREAD

**Issue by NeilGirdhar** [tensorflow/tensorflow#3945]
Consider allowing tensorflow.select to accept scalar conditions.  I.e., `tf.select(condition, t, e, name=None)` with `condition` a scalar, and `t`, `e` having the same shape.

**Comment by vrv** [comment]
I think that is perhaps better accomplished via tf.cond?  https://www.tensorflow.org/versions/r0.10/api_docs/python/control_flow_ops.html#cond

(The reason it is "better" is that, if implemented carefully, tf.cond doesn't evaluate both branches, whereas tf.select with this feature would always evaluate both branches).  Please comment if you disagree!

**Comment by NeilGirdhar** [comment]
Isn't `cond` done on the CPU?  I mean, even if the condition is a placeholder, cond has to copy the result of `pred` back to the CPU and then call either `fn1` or `fn2` — all on the CPU.  `select` seems better if everything is already on the GPU and needs to stay on the GPU.

**Comment by vrv** [comment]
That's a good point, and select does do some amount of broadcasting already (it can broadcast row-wise when it is a vector), so it seems reasonable to extend that all the way to the scalar case.

This probably isn't super high priority though, but would be a welcome improvement if someone in the community wanted to implement this, so marking this as contributions welcome.  In the mean time, you could probably use tf.tile to broadcast the scalar into a vector of the right length without the same penalty as the full broadcast.

**Comment by NeilGirdhar** [comment]
Thanks for reopening the issule, could you point me to where select is defined in the source?  My search for "def select" didn't find it.

**Comment by vrv** [comment]
You'd have to implement the change in math_ops.py _SelectShape to allow the new shape signature, math_ops.cc's ShapeFn to do the same, and then you'd have to edit cwise_op_select.cc and cwise_op_gpu_select.cu.cc to implement the new feature, and then probably cwise_ops_test.py to validate the change.

**Comment by NeilGirdhar** [comment]
Okay, thanks.  I may work around this for now using `expand_dims` on my condition.

**Comment by Mistobaan** [comment]
Taking a look at this. The additional case when the condition is just a scalar it will return either the full tensor from `t` or `e` based on the single value of `cond`, right?

**Comment by vrv** [comment]
Yup!

**Comment by albertz** [comment]
Can someone comment on the state here? This was reverted? Why?

What broadcasting is supposed to work?

E.g. I get the error:

`Dimension 2 in both shapes must be equal, but are 9001 and 1 for '.../Select' (op: 'Select') with input shapes: [?,?,1], [?,?,9001], [1,1,1]`

So the `cond` can not be broadcasted?

Even when I have `cond` in the correct shape, I still get the error:

`ValueError: Dimension 2 in both shapes must be equal, but are 9001 and 1 for '.../Select' (op: 'Select') with input shapes: [?,?,?], [?,?,9001], [1,1,1].`

So also `e` cannot be broadcasted?

What can be broadcasted?

**Comment by Mistobaan** [comment]
@drpngx Why was it reverted?

**Comment by drpngx** [comment]
What was reverted? I think it's still there. It may have been reverted temporarily. I spot checked some code https://github.com/Mistobaan/tensorflow/blob/master/tensorflow/core/ops/math_ops.cc#L943 and it's there.

**Comment by albertz** [comment]
Ok, the history of commits referenced in this issue suggests that something was reverted. This is a bit confusing.

Anyway, I think the broadcasting is still very much too limited. This feature request should also maybe be renamed to allow any broadcasting. I guess people would expect the straightforward behavior (which is the same in `numpy.where` I guess).

**Comment by drpngx** [comment]
Sounds good. Would someone be interested in implementing this? Maybe starting by replying on this thread with some snippets of test code to show all of the cases that need to be covered?

**Comment by NeilGirdhar** [comment]
@drpngx It looks like you reverted it in the tensorflow codebase.  (Of course it's still on Mistobaan's codebase.)  Am I misunderstanding?

**Comment by drpngx** [comment]
@NeilGirdhar yes it looks like it, but it was put back at a later stage AFAIK. What code are you looking at?

**Comment by NeilGirdhar** [comment]
I see now, you're right.

**Comment by balancap** [comment]
If I may, should `tf.select / where` not be able to support more general broadcasting? 
Ignoring the casting problem, it is completely equivalent to the operation `cond * t  + (1  - cond) * e` which supports much more general input shapes. For instance, I find it quite useful when `t` is a Tensor and `e` a scalar for performing a simple update of some values in the former.

**Comment by albertz** [comment]
Just wondering about the state here. Broadcasting in `tf.where` would really be useful.

**Comment by NeilGirdhar** [comment]
>  it is completely equivalent to the operation cond * t + (1 - cond) * e…

No, it's not.  Sometimes, one of `t` and `e` is `nan`, in which case your expression always returns `nan`.

**Comment by yongtang** [comment]
PR #15982 might be related.

**Comment by gunan** [comment]
Looks like the original issue reported is fixed. I will close this issue, but for broadcasting in where/select ops, if we still  need fixes please file a new issue.

**Comment by albertz** [comment]
No, this is still not fixed.
Related (or maybe duplicate): #9284
