### ISSUE TITLE
Simple keras model "predict" call fails inside py_function

### ISSUE THREAD

**Issue by areiner222** [tensorflow/tensorflow#39969]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes. Created a simple example for reproducibility. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: Python 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: CUDA 10.2 / cuDNN 7.6.5
- GPU model and memory: GeForce GTX 980 Ti / 6GB

**Describe the current behavior**

Using the 'predict' api for a keras model inside a py_function throws the following error:
`LookupError: No gradient defined for operation 'IteratorGetNext' (op type: IteratorGetNext)`

**Standalone code to reproduce the issue**

```
import numpy as np
import tensorflow as tf

inp = tf.keras.Input(shape=(5,))
out = tf.keras.layers.Dense(1)(inp)
model = tf.keras.Model(inp, out)

def outer_func(arr):
    def _func(x):
        res = model.predict(x)
        return res

    out = tf.py_function(
        _func,
        (arr,),
        tf.float32
    )
    return out

outer_func(np.random.rand(10, 5))
```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2 ,nightly version(`2.3.0-dev20200528`) and was able to reproduce the issue.Please, find the gist [here.](https://colab.sandbox.google.com/gist/ravikyram/b72b16e5ec0c4339658c43ba4f3fb1db/untitled932.ipynb)Thanks!

**Comment by karmel** [comment]
model.predict contains a lot of state-management and input processing logic that is not designed for this usecase. Can you try instead just calling the model? Eg:

```
def _func(x):
        res = model(x)
        return res
```

**Comment by areiner222** [comment]
I cannot unfortunately because I am using a third party library that wraps helper functions / class around the model.predict call. I'm using in a py_function because I'm including it in a tf.data.Dataset pipeline.

**Comment by ymodak** [comment]
This is fixed with latest tf-nightly.
See [gist](https://colab.research.google.com/gist/ymodak/d123012b1d690f653a078458f4174238/untitled9.ipynb)
Output:
```python
<tf.Tensor 'EagerPyFunc_1:0' shape=<unknown> dtype=float32>
```

**Comment by ahmedanis03** [comment]
@ymodak is still not fixed yet in 2.6.0 but worked at the nightly, do we have any estimation when this will be officially released?
