### ISSUE TITLE
For tf.keras.losses.categorical_hinge maximum op dtype missmatch using mixed_precision with float16

### ISSUE THREAD

**Issue by jadevaibhav** [tensorflow/tensorflow#39982]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

***Issue:***
     return math_ops.maximum(0., neg - pos + 1.)
    lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py:5740 maximum
        "Maximum", x=x, y=y, name=name)
    lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:506 _apply_op_helper
        inferred_from[input_arg.type_attr]))

    TypeError: Input 'y' of 'Maximum' Op has type float16 that does not match type float32 of argument 'x'.

***Plausible solution:***
   return math_ops.maximum( neg - pos + 1., 0.)
So that dtype is matched with calculated entity rather than other way.

**Comment by amahendrakar** [comment]
@jadevaibhav,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the TensorFlow version you are using. Thanks!

Also, please check [this thread](https://github.com/tensorflow/tensorflow/issues/34406) from a similar issue and let us know if it helps. Thanks!

**Comment by jadevaibhav** [comment]
@amahendrakar I have recreated the [bug and tested a way to fix this](https://drive.google.com/open?id=1BgfoS1_Co7DlKtMPYsJ-98vp4ctrVaPL). I have submitted the merge request. Thanks!

**Comment by jadevaibhav** [comment]
@amahendrakar ,
I checked the mentioned thread, it shows the error dtype missmatch for tf 2.0. It was same for me, but this issue is in 2.2.0. Sorry that I haven't mentioned this before.

**Comment by jadevaibhav** [comment]
[working link](https://colab.research.google.com/drive/1BgfoS1_Co7DlKtMPYsJ-98vp4ctrVaPL?authuser=1)

**Comment by reedwm** [comment]
Closing since I think this has been fixed by #39984 (let me know if I'm wrong)

**Comment by jadevaibhav** [comment]
I believe this issue persists in other loss functions as well. This is more of fundamental question: as per mixed precision, all computations are done in Float16, does that also include the loss calculations? Or only the forward and backward pass computations?

**Comment by reedwm** [comment]
I think most loss functions support float16, but let me know if you know of any that do not and I can fix them.

> This is more of fundamental question: as per mixed precision, all computations are done in Float16, does that also include the loss calculations? Or only the forward and backward pass computations?

By default, losses run in the same dtype as the output of the model, although this may be changed in the future to always run losses in float32. Most of the time, it is safe to run losses in float16, but a few cases require float32 for numeric stability. It is recommended to always run losses in float32 since it is difficult to tell whether you will encounter one of the few cases where the loss is numerically unstable in float16, and typically float32 losses have negligible impact on performance.
