### ISSUE TITLE
org.tensorflow:tensorflow-lite-gpu nightly build error vs 2.2.0

### ISSUE THREAD

**Issue by amitDaMan** [tensorflow/tensorflow#40056]
Im not even sure how reportable this bug is, since it is occurring on a nightly build (6/1/2020), Code was working on friday. 

However when I change from nightly build to 2.2.0, works just fine:
`fliteOptions.addDelegate(GpuDelegate()) 
`
but on nightly:
E/TestRunner: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6tflite3gpu2cl9Arguments11kArgsPrefixE" referenced by "/data/app/~~KImLgowMRYSuuZbqgdRMgw==/com.qualcomm.style-LOBlofHPnlpjAMuiEJPKFQ==/lib/arm64/libtensorflowlite_gpu_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)

trips it when it is loading the library 

The models used are the same models found in the style transfer android sample project, and I will link them in this post. 

Also, if there is a special procedure or contact for nightly build bugs, let me know. 

The models are quantized, which means it should fallback to the cpu, I think this is just a general linking build issue, rather than a gpu delegate problem. I will include the models for reproduce ability 

models:
[quantized_models.zip](https://github.com/tensorflow/tensorflow/files/4712477/quantized_models.zip)

**Comment by yefengjie** [comment]
I have meet the same problem.
`
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6tflite3gpu2cl9Arguments11kArgsPrefixE" referenced by "/data/app/com.ytmallapp-8FBD0MkjWXbICJ6ppEx-Mw==/lib/arm/libtensorflowlite_gpu_jni.so"...
2020-06-03 21:27:31.084 15529-16058/com.ytmallapp W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
2020-06-03 21:27:31.084 15529-16058/com.ytmallapp W/System.err:     at java.lang.System.loadLibrary(System.java:1657)
2020-06-03 21:27:31.084 15529-16058/com.ytmallapp W/System.err:     at org.tensorflow.lite.gpu.GpuDelegate.<clinit>(GpuDelegate.java:126)
`

**Comment by NikhilBartwal** [comment]
I have encountered the same problem with tflite gpu nightly 
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6tflite3gpu2cl9Arguments11kArgsPrefixE" referenced by "/data/app/com.at.nikhil.speciesai-yi_FcI_5AKGpV5FjG1HVTg==/lib/arm64/libtensorflowlite_gpu_jni.so"...

Code was working totally fine just few days back. However, when built with tflite 2.2.0, it worked like charm. 
The model is a standard keras CNN model.

**Comment by terryheo** [comment]
This is fixed now. You need to clear grade cache to download recent nightly aar file.

**Comment by mtngld** [comment]
Invalidated cache ("File" -> "Invalidate Caches/Restart") still seeing this issue when using GPU delegate.
