### ISSUE TITLE
save_model() fails with custom layer and SavedModel format

### ISSUE THREAD

**Issue by d-miketa** [tensorflow/tensorflow#40912]
- Have I written custom code: Yes
- OS Platform and Distribution: MacOS 10.15.5, running an official Docker image
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.6.9
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A
**Current behavior**
I have defined a custom Keras layer which acts as a learnable lookup table. The layer is functional and learns throughout training. I am able to save the Keras model using both `model.save('/path/to/dir')` and `model.save('/path/to/dir/model.h5')`.

However, `tf.keras.models.load_model('/path/to/dir')` fails whereas the H5 model seems to load properly with `tf.keras.models.load_model('/path/to/dir/model.h5', custom_objects = {"Lookup": Lookup})`. Passing `custom_objects` to the SavedModel call (without `.h5`) makes no difference.

You can see in the logs that the SavedModel loader doesn't know the lookup table's shape.

**Describe the expected behavior**
Both save/load implementations should work.

**Standalone code to reproduce the issue**

```
import tensorflow as tf

class Lookup(tf.keras.layers.Layer):
    def __init__(self, depth: int = 3, **kwargs):
        super().__init__(**kwargs)

        self.depth = depth
        self.texture = None

    def build(self, input_shape):
        lookup_shape = input_shape[1:-1] + [self.depth]

        self.lookup_table = self.add_weight('lookup_table', lookup_shape, 'float32',
                                       initializer='random_normal',
                                       trainable=True)
        super().build(input_shape)

    def call(self, inputs, **kwargs):
        entries = tf.gather_nd(params=self.lookup_table,
                                      indices=inputs,
                                      name='lookup_call')

        return entries

    def get_config(self):
        config = super().get_config()
        config.update({"depth": self.depth})
        return config
    
custom_objects = {"Lookup": Lookup}

lookup = Lookup()

x = tf.keras.Input(shape=(2,2), dtype='int32')
y = lookup(x)
model = tf.keras.Model(x, y)
model.compile()

model.save('/tmp/lookup_test')
loaded_model = tf.keras.models.load_model('/tmp/lookup_test', custom_objects=custom_objects)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
In  [1]:
Line 40:    loaded_model = tf.keras.models.load_model('/tf/external/model/lookup_test', custom_objects=custom_objects)

File /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py, in load_model:
Line 190:   return saved_model_load.load(filepath, compile)

File /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py, in load:
Line 116:   model = tf_load.load_internal(path, loader_cls=KerasObjectLoader)

File /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py, in load_internal:
Line 604:   export_dir)

File /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py, in __init__:
Line 188:   super(KerasObjectLoader, self).__init__(*args, **kwargs)

File /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py, in __init__:
Line 116:   meta_graph.graph_def.library))

File /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/function_deserialization.py, in load_function_def_library:
Line 311:   func_graph = function_def_lib.function_def_to_graph(copy)

File /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function_def_to_graph.py, in function_def_to_graph:
Line 63:    importer.import_graph_def_for_function(graph_def, name="")

File /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py, in import_graph_def_for_function:
Line 412:   graph_def, validate_colocation_constraints=False, name=name)

File /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py, in _import_graph_def_internal:
Line 501:   raise ValueError(str(e))

ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [?,2,2] and params shape: [] for '{{node lookup/lookup_call}} = ResourceGatherNd[Tindices=DT_INT32, _output_shapes=[[?,2]], dtype=DT_FLOAT](lookup_lookup_call_resource:0, inputs:0)' with input shapes: [], [?,2,2].
---------------------------------------------------------------------------
```

**Comment by Saduf2019** [comment]
@d-miketa 
I ran the above shared code, please let us know if it confirms your issue in [this gist](https://colab.research.google.com/gist/Saduf2019/ce787da4cbb70576093192a91dcb1ca0/untitled249.ipynb)

**Comment by d-miketa** [comment]
Thanks for sharing the Colab, that's the exact error I'm seeing at my end.

**Comment by Saduf2019** [comment]
@d-miketa 
Please refer to below links and let us know if it helps.
[link](https://stackoverflow.com/questions/44174566/tensorflow-error-when-indexing-a-4d-array-valueerror-shapes-must-be-equal-rank) [link1](https://github.com/broadinstitute/keras-rcnn/issues/171)

**Comment by d-miketa** [comment]
No, those don't (directly) apply to my issue, which arises when _loading_ the model. It works perfectly fine before the save/load cycle.

**Comment by jvishnuvardhan** [comment]
@d-miketa Looks like this was resolved in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/3275621021abd75da56ca3482ffd9753/untitled249.ipynb) a gist for your reference.

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by d-miketa** [comment]
> @d-miketa Looks like this was resolved in recent `tf-nightly`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/3275621021abd75da56ca3482ffd9753/untitled249.ipynb) a gist for your reference.
> 
> Please verify once and close the issue if this was resolved for you. Thanks!

Yes, it works! Wonderful, thank you – I'll just wait for 2.3 then. :)

**Comment by jvcrnc** [comment]
Can this issue be reopened?
With TF 2.6 I'm experiencing exactly the same problem.
Thie issue can be reproduced with the code of the first post.
Also with tf-nightly the issue is still there.

ValueError: indices.shape[-1] must be <= params.rank, but saw indices shape: [?,2,2] and params shape: [] for '{{node lookup/lookup_call}} = ResourceGatherNd[Tindices=DT_INT32, _output_shapes=[[?,2]], dtype=DT_FLOAT](lookup_lookup_call_resource:0, inputs:0)' with input shapes: [], [?,2,2].
