### ISSUE TITLE
Contrib metric `metric_ops.streaming_auc` type error within function

### ISSUE THREAD

**Issue by craymichael** [tensorflow/tensorflow#4175]
### Environment info

Version 0.10.0rc0
Ubuntu

I'm using a `RandomForest` Estimator and am feeding it `tf.contrib.metrics.streaming_auc` and it fails.
### What other attempted solutions have you tried?

Modifying source to convert both inputs to float using `tf.to_float`. It worked, but still an issue.
### Logs or other output that would be helpful

```
Traceback (most recent call last):
  File "main.py", line 284, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 219, in main
    eval_steps=1
  File "/home/user/Documents/tensorflow/cross_validation/evaluate.py", line 45, in evaluate
    metrics=metrics
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 356, in evaluate
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 630, in _evaluate_model
    eval_dict = self._get_eval_ops(features, targets, metrics)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/random_forest.py", line 205, in _get_eval_ops
    result[name] = metric(predictions, labels)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 795, in streaming_auc
    fp_update_op) = _tp_fn_tn_fp(predictions, labels, thresholds, ignore_mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 667, in _tp_fn_tn_fp
    (thresh_tiled)),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 845, in greater
    result = _op_def_lib.apply_op("Greater", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 468, in apply_op
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Greater' Op has type float32 that does not match type int64 of argument 'x'.
```

**Comment by gilberthendry** [comment]
The RandomForest Estimator currently only supports passing one of ['sigmoid_entropy', 'softmax_entropy', 'accuracy', 'r2', 'predictions'] in the accuracy_metric argument of the constructor to use for evaluation. If passing streaming_auc in the metrics argument of evaluate() worked with casted inputs, that's great, but I would be wary that it's giving you the right results.  We pass class probabilities and one-hot labels to the metric, which not all metrics are expecting. For instance, streaming_accuracy is expecting predictions, so we wrap it in a function that performs an argmax. 

We have an action item to improve the compatibility of the underlying random forest implementation with the tf.learn wrapper, so thanks for pointing this out so it can be included.

**Comment by craymichael** [comment]
Oops let me clarify something; I modified the source of the Estimator so that when get_eval_ops is called it passes the Predictions and Label (using argmax for both, label post one-hot) instead of the probabilities so other metrics could be used. Just remembered I did that earlier and forgot before I posted this. The AUC I've been receiving has been accurate after modification.

Shouldn't the AUC metric not fail if I'm passing in solely the predictions and labels as tf.int32 with the default threshold value?

**Comment by gilberthendry** [comment]
Ah ok.  AUC itself shouldn't fail with the same type of inputs, is that what you're seeing?  Can you replicate without RandomForest estimator?

**Comment by craymichael** [comment]
Yeah it shouldn't and yes it fails for me when using any Estimator when I specify `{'auc': streaming_auc}` as a desired metric. LinearEstimator traceback:

```
Traceback (most recent call last):
  File "main.py", line 308, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 239, in main
    eval_steps=1
  File "/usr/local/lib/tensorflow/heartwood/cross_validation/evaluate.py", line 45, in evaluate
    metrics=metrics
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 356, in evaluate
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 630, in _evaluate_model
    eval_dict = self._get_eval_ops(features, targets, metrics)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/linear.py", line 204, in _get_eval_ops
    metrics)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 454, in _get_eval_ops
    return self._target_column.get_eval_ops(features, logits, targets, metrics)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/target_column.py", line 288, in get_eval_ops
    self.get_weight_tensor(features)))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/target_column.py", line 371, in _run_metrics
    result[name] = metric(predictions, targets)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 802, in streaming_auc
    fp_update_op) = _tp_fn_tn_fp(predictions, labels, thresholds, ignore_mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/metrics/python/ops/metric_ops.py", line 673, in _tp_fn_tn_fp
    thresh_tiled),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 845, in greater
    result = _op_def_lib.apply_op("Greater", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 468, in apply_op
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Greater' Op has type float32 that does not match type int64 of argument 'x'.
```

**Comment by buptjz** [comment]
I got the same error when using wide and deep model
`    validation_metrics = {
        # "streaming_auc": tf.contrib.metrics.streaming_auc,
        "precision": tf.contrib.metrics.streaming_precision
    }

    # ValidationMonitors rely on saved checkpoints to perform evaluation operations
    validation_monitor = tf.contrib.learn.monitors.ValidationMonitor(
        input_fn=lambda: input_fn(test_file_list),
        every_n_steps=FLAGS.validation_steps,
        metrics=validation_metrics
    )

    m.fit(input_fn=lambda: input_fn(train_file_list),
          max_steps=FLAGS.train_steps,
          monitors=[validation_monitor])`

**Comment by craymichael** [comment]
It appears this has been fixed in newer versions (past r0.10), so if you don't feel like upgrading you can fix it by changing the function `_tp_fn_tn_fp` in `tensorflow/contrib/metrics/python/ops/metric_ops.py` (doesn't require rebuilding, of course) as follows.
### Original
```
def _tp_fn_tn_fp(predictions, labels, thresholds, ignore_mask=None):
  ...
  pred_tiled = math_ops.cast(
      math_ops.greater(
          array_ops.tile(
              array_ops.transpose(predictions), [num_thresholds, 1]),
          thresh_tiled),
      dtype=dtypes.int32)
```
### Modified
```
def _tp_fn_tn_fp(predictions, labels, thresholds, ignore_mask=None):
  ...
  pred_tiled = math_ops.cast(
      math_ops.greater(
          math_ops.to_float(array_ops.tile(
              array_ops.transpose(predictions), [num_thresholds, 1])),
          math_ops.to_float(thresh_tiled)),
      dtype=dtypes.int32)
```

**Comment by m15i** [comment]
Still getting this error. In r0.12, the original is not as above, but is:

`  pred_is_pos = math_ops.greater(
      array_ops.tile(array_ops.transpose(predictions_2d), [num_thresholds, 1]),
      thresh_tiled)
  pred_is_neg = math_ops.logical_not(pred_is_pos)`
