### ISSUE TITLE
Missing "model" in visualize.py script: tflite model AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model' 

### ISSUE THREAD

**Issue by OmriTreidel** [tensorflow/tensorflow#41846]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.4.0
- Python version: 3.8.1
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"` v1.12.1-37714-gac84c5eb81 2.4.0

**I followed the [instructions](https://www.tensorflow.org/lite/guide/faq#how_do_i_inspect_a_tflite_file) in order to inspect a tflite file. Compilation and installation of the python whl was successful. pip freeze shows 
tensorflow @ file:///tmp/tensorflow_pkg/tensorflow-2.4.0-cp38-cp38-linux_x86_64.whl. Starting the python consul and importing tensorflow works as expected. 

However, running 

python visualize.py foo.tflite foo.html

results in a an error

Traceback (most recent call last):
  File "visualize.py", line 517, in <module>
    main(sys.argv)
  File "visualize.py", line 513, in main
    CreateHtmlFile(tflite_input, html_output)
  File "visualize.py", line 429, in CreateHtmlFile
    data = CreateDictFromFlatbuffer(file_data)
  File "visualize.py", line 414, in CreateDictFromFlatbuffer
    model_obj = schema_fb.Model.GetRootAsModel(buffer_data, 0)
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'

In addition, 

bazel run //tensorflow/lite/tools:visualize model.tflite visualized_model.html

results in a similar error

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=153
INFO: Reading rc options for 'run' from /home/omri/src/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/omri/src/tensorflow/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'run' from /home/omri/src/tensorflow/.tf_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/home/omri/.pyenv/versions/tf_src/bin/python3 --action_env PYTHON_LIB_PATH=/home/omri/.pyenv/versions/tf_src/lib/python3.8/site-packages --python_path=/home/omri/.pyenv/versions/tf_src/bin/python3 --config=xla --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /home/omri/src/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/omri/src/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/omri/src/tensorflow/.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:linux in file /home/omri/src/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/omri/src/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/lite/tools:visualize (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tensorflow/lite/tools:visualize up-to-date:
  bazel-bin/tensorflow/lite/tools/visualize
INFO: Elapsed time: 0.132s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tensorflow/lite/tools/visualize /home/omri/Downloads/mobilenet_thin_openpose_opt_fullint_tf1.tflite /home/omri/DownINFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/home/omri/.cache/bazel/_bazel_omri/a9e9b87cb64d67149db4f28645a2ba4b/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 517, in <module>
    main(sys.argv)
  File "/home/omri/.cache/bazel/_bazel_omri/a9e9b87cb64d67149db4f28645a2ba4b/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 513, in main
    CreateHtmlFile(tflite_input, html_output)
  File "/home/omri/.cache/bazel/_bazel_omri/a9e9b87cb64d67149db4f28645a2ba4b/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 429, in CreateHtmlFile
    data = CreateDictFromFlatbuffer(file_data)
  File "/home/omri/.cache/bazel/_bazel_omri/a9e9b87cb64d67149db4f28645a2ba4b/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/lite/tools/visualize.runfiles/org_tensorflow/tensorflow/lite/tools/visualize.py", line 414, in CreateDictFromFlatbuffer
    model_obj = schema_fb.Model.GetRootAsModel(buffer_data, 0)
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'

Finally, starting the python consul and trying to import `Model` from  'tensorflow.lite.python.schema_py_generated' results in the same error

~/src/tensorflow/tensorflow/lite/tools$ python
Python 3.8.1 (default, Mar  5 2020, 13:14:49) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.lite.python import schema_py_generated
>>> schema_py_generated.Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'

**

**The script should generate an HTML file**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@OmriTreidel 
Please provide simple stand alone code to replicate the issue or if possible share colab gist with the error to analyse.

**Comment by OmriTreidel** [comment]
@Saduf2019 The error can be reproduced by a single import 2 lines mentioned above

```
from tensorflow.lite.python import schema_py_generated
schema_py_generated.Model
```

or alternatively by using bazel run in the terminal

```
bazel run //tensorflow/lite/tools:visualize model.tflite visualized_model.html
``` 

both result in the same error

AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'


What else should I provide ?

**Comment by sujaybabruwad** [comment]
I am also facing the same issue. Any update on this ? 
Kindly help @jvishnuvardhan

**Comment by terryheo** [comment]
I can reproduce the issue. Investigating...

**Comment by Fruiter** [comment]
Seems this's because 'schema_py_generated.py' is empty. By changing https://github.com/tensorflow/tensorflow/blob/9544dfa6063e37afd7aa35aa33e8622734acc69b/third_party/flatbuffers/build_defs.bzl#L373 from

>  "sed 's/from flatbuffers.compat import import_numpy/import numpy as np' |" +

to 

>  "sed 's/from flatbuffers.compat import import_numpy/import numpy as np/g' |" +

should fix the issue

**Comment by terryheo** [comment]
@Fruiter I have "AttributeError: module 'flatbuffers' has no attribute 'encode'" error with the change.
Am I missing something?

**Comment by Fruiter** [comment]
> @Fruiter I have "AttributeError: module 'flatbuffers' has no attribute 'encode'" error with the change.
> Am I missing something?

Not sure. I tested by 'bazel build //tensorflow/lite/python:schema_py' then replaced the empty schema_py_generated.py. And I didn't test the 'visualize' use case. But I have tested with tflite model conversion logic which has the same error without the fix.

**Comment by jdduke** [comment]
@lu-wang-g can you advise?

**Comment by lu-wang-g** [comment]
It seems to be related to a recent change on FlatBuffer bazel rules. @MeghnaNatraj could you please double check the case?

**Comment by MeghnaNatraj** [comment]
Looking into this now. I was able to reproduce the error. Will post an update when I find a fix.

**Comment by MeghnaNatraj** [comment]
Marking the issue as closed as it has been fixed. Feel free to re-open it if the issue is still unresolved.

**Comment by YANxu-666** [comment]
F:\anaconda3\Lib\site-packages\tensorflow\lite\pythonschema_py_generated.py      There is no code, it is empty.   
how to solve this problem？

**Comment by MeghnaNatraj** [comment]
@YANxu-666 what TF version are you using? Could you installing`tf-nightly` and try again?

**Comment by YANxu-666** [comment]
> @ YANxu-666您使用的是什么TF版本？您可以安装并重`tf-nightly`试吗？



> @ YANxu-666您使用的是什么TF版本？您可以安装并重`tf-nightly`试吗？

tensrflow 2.4.0

**Comment by YANxu-666** [comment]
> @ YANxu-666您使用的是什么TF版本？您可以安装并重`tf-nightly`试吗？

tensorflow2.4.0  .I am also facing the same issue. Any update on this ?

**Comment by YANxu-666** [comment]
I am also facing the same issue. Any update on this ?

**Comment by keesschollaart81** [comment]
Ran into this issue on Windows (maybe that ^^ bazel find/sed script does not run on Windows?). Created a new virtualenv in WSL2 (Ubuntu 18.04) and installed the same requirements.txt including `tf-nightly==2.5.0.dev20201115`. There the `schema_py_generated.py` was not empty... Because I wanted to continue on Windows, I copied the generated code to the empty file in my Windows environment and now it works like a charm. Hope it helps you (to fix it 😉 )?

**Comment by YANxu-666** [comment]
> 在Windows上遇到此问题（也许^^ bazel查找/ sed脚本不能在Windows上运行？）。在WSL2（Ubuntu 18.04）中创建了一个新的virtualenv，并安装了相同的requirements.txt，其中包括`tf-nightly==2.5.0.dev20201115`。那里`schema_py_generated.py`不是空的……因为我想在Windows上继续，所以我将生成的代码复制到Windows环境中的空文件中，现在它就像一个超级按钮一样工作。希望对您有帮助（修复它）😉 ）？
I am running on Windows,and I downloaded all the files in the tensorflow directory to my computer.I don't know which file directory the schema_py_generated.py is in.
Can you send me the code of schema_py_generated.py?
  thanks

**Comment by YANxu-666** [comment]
> 在Windows上遇到此问题（也许^^ bazel查找/ sed脚本不能在Windows上运行？）。在WSL2（Ubuntu 18.04）中创建了一个新的virtualenv，并安装了相同的requirements.txt，其中包括`tf-nightly==2.5.0.dev20201115`。那里`schema_py_generated.py`不是空的……因为我想在Windows上继续，所以我将生成的代码复制到Windows环境中的空文件中，现在它就像一个超级按钮一样工作。希望对您有帮助（修复它）😉 ）？
I found schema_py_generated.py but it is empty
Can you send me the code of schema_py_generated.py?
I really need it

**Comment by MeghnaNatraj** [comment]
@YANxu-666 This issue should be fixed with the latest TF code (tf-nightly). Could you try with that let us know if it works?

Install it using pip as follows: 
```
pip install tf-nightly
```

(you need to restart your runtime if you are using [https://colab.research.google.com])

**Comment by hhass** [comment]
> Ran into this issue on Windows (maybe that ^^ bazel find/sed script does not run on Windows?). Created a new virtualenv in WSL2 (Ubuntu 18.04) and installed the same requirements.txt including `tf-nightly==2.5.0.dev20201115`. There the `schema_py_generated.py` was not empty... Because I wanted to continue on Windows, I copied the generated code to the empty file in my Windows environment and now it works like a charm. Hope it helps you (to fix it 😉 )?

On Windows, i still get empty scheme_py_generated.py
Tested it with clean pip installs of tf-nightly 2.5.0.dev20201116 and fresh released v2.4.0-rc2

**Comment by MeghnaNatraj** [comment]
@hhass is it possible to post an end-to-end colab where I can reproduce this issue?

**Comment by ChowderII** [comment]
Hi! I am encountering the same problem, my version of tensorflow is : tf_nightly-2.5.0.dev20201202. 

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/brackman/Documents/Tensorflow/models/research/object_detection/ssd_mobilenet_quant/convertion.py", line 39, in <module>
    tflite_model = converter.convert()
  File "C:\Users\brackman\Anaconda3\envs\tf-nightly\lib\site-packages\tensorflow\lite\python\lite.py", line 767, in convert
    result = _modify_model_io_type(result, **flags_modify_model_io_type)
  File "C:\Users\brackman\Anaconda3\envs\tf-nightly\lib\site-packages\tensorflow\lite\python\util.py", line 853, in modify_model_io_type
    model_object = _convert_model_from_bytearray_to_object(model)
  File "C:\Users\brackman\Anaconda3\envs\tf-nightly\lib\site-packages\tensorflow\lite\python\util.py", line 579, in _convert_model_from_bytearray_to_object
    model_object = schema_fb.Model.GetRootAsModel(model_bytearray, 0)
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'
```

I am trying to quantize the SSD_MobileNetV2. Let me know if you need my code for review. Thank you!

**Comment by MeghnaNatraj** [comment]
@ChowderII Yes, please do post an end-to-end [colab notebook](https://colab.research.google.com] so I can reproduce the issue for debugging.

**Comment by MeghnaNatraj** [comment]
@ChowderII If you can upload all your data (model and images) to GoogleDrive, mount it & run your colab to verify the error,  and finally share that folder (ensure it has with read permissions for everyone), it would make it very easy for us to debug it. 

Here's a Github issue where a user did this, and it enabled us to debug the issue quickly - https://github.com/tensorflow/tensorflow/issues/41840
