### ISSUE TITLE
Tensorflow is BROKE .... 

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#42084]
Stuck here, tf-nightly is not compatible with CUDA 11.0 and the latest code is broke....

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): One line ?
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): Latest as of this second
- Python version: 3.8.2
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11.00
- GPU model and memory: RTX 2070

```
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf

2020-08-06 00:18:35.042260: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxxx/.virtualenvs/tensorflowgpu/lib/python3.8/site-packages/tensorflow/__init__.py", line 433, in <module>
    _ll.load_library(_main_dir)
  File "/home/xxxx/.virtualenvs/tensorflowgpu/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 154, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /home/xxxxx/.local/lib/python3.8/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
>>> 
```

**Comment by summa-code** [comment]
If it is not bug what is ? it used to work two days ago....

**Comment by ravikyram** [comment]
@summa-code 
Please take a look at the [tested build configuration](https://www.tensorflow.org/install/source#gpu) and try building TensorFlow with CUDA 10.1, and check if it works. Thanks!

**Comment by summa-code** [comment]
No i am not doing for 10.1, because this used to work for 11.0, something is wrong in recent code.

**Comment by mihaimaruseac** [comment]
@summa-code just to get some context: did you manage to build a tf-nightly with CUDA 11 before and now it is broken? Can you run a bisect to identify which nightly has the first failure? We can take it from there.

We don't have build nightly with CUDA 11 ourselves, so we can only support CUDA 11 at this time on a best effort basis. 

There is work being done to switch nightly to CUDA 11 soon, though. Hence, the above bisection can also help there

Thank you

**Comment by mihaimaruseac** [comment]
Oh, I see you're building from source and the failure is recent. Can you please try a `git bisect`?

**Comment by summa-code** [comment]
i did git clone into a new directory and built... I am still surprised that it is still broke.

import tensorflow as tf

libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

**Comment by mihaimaruseac** [comment]
Can you post the command you are compiling with? And the output of `git log -n4 --format=oneline`?

Our dashboard shows builds as being green at the moment

**Comment by summa-code** [comment]
Ok, the build that i had on 4th of Aug works, but the ones i built after that all have this problem. And i have only enabled CUDA in configuration, not enabling Tensorrt, as i am suspecting that it had some algorithms not implemented. I have only enabled NUMA for the bazel compile command. I will see if linking Tensorrt makes any difference.

**Comment by summa-code** [comment]
Hope that timeline helped ?

**Comment by mihaimaruseac** [comment]
Still need the command used to build (from a fresh clone and a `bazel clean --expunge`) as well as the output of the `git log` command posted above. `bazel --version` also helps.

**Comment by summa-code** [comment]
@mihaimaruseac I have rebuilt the system, after i installed 10.x and tested, it reported the same problem. So some other library was messed up by Nvidia update, Damn Nvidia...Now the build looks good and works fine, i will keep digging. Thanks for your follow up. A good weekend worth of work. :-)

**Comment by DjangoPeng** [comment]
Also incompatible with CUDA 10.2.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000001:00:00.0 Off |                    0 |
| N/A   27C    P0    24W / 250W |      0MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```


@summa-code

**Comment by mihaimaruseac** [comment]
@DjangoPeng NVIDIA says CUDA 10.2 and CUDA 10.1 are compatible. We will skip CUDA 10.2 and go for CUDA 11.

**Comment by DjangoPeng** [comment]
emm. 

So I'd better upgrade to CUDA 11?

**Comment by foxik** [comment]
The original crash is in fact caused by #42978 and has been fixed by #45399.

**Comment by danielgrebe** [comment]
@foxik I have been having the exact same problem as OP. I applied patch #45399 and I still get the same error.

**Comment by foxik** [comment]
@danielgrebe Could you post the error happening during `import tensorflow as tf`, please?

**Comment by danielgrebe** [comment]
This is the error that I get when I compile tensorflow with Cuda 11.1 and CuDNN 8.
I have tried the following branches and gotten this same error:

- r2.4
- r2.4 with patch #45399 applied
- HEAD (2020-12-14)
- tf-nightly (2020-12-15)

This is the only tensorflow that I have on my system. Everytime that I install, I make sure to uninstall tf as well.

I have not tried with any other version of Cuda, as Cuda 11.1 (and 11.2 as of yesterday) is the only version supported on Debian 10. I have tried, without success to install ubuntu packages.

The next step I plan on trying is building without Cuda to see if I get the same error, but on my system it take 4-5 hours to build, so testing different configs takes a while.

```
2020-12-16 17:50:23.477409: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
/usr/local/lib/python3.8/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "./fashion_MNIST.py", line 6, in <module>
    import tensorflow as tf
  File "/home/tiberius/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 435, in <module>
    _ll.load_library(_main_dir)
  File "/home/tiberius/.local/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 153, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
```

**Comment by DjangoPeng** [comment]
@summa-code  @ mihaimaruseac

It seems like the issue should be reopened.

**Comment by mihaimaruseac** [comment]
It's better to open a new issue and post the full details.
