### ISSUE TITLE
saving a large kersa model through exception

### ISSUE THREAD

**Issue by bsaravi** [tensorflow/tensorflow#42142]
**saving checkpoint or tf.kersa.models.save_model in non eager mode throws the following exception:
I am using Ubuntu 18 and tried different versions of tensorflow (1.15,2.2,2.4, nightly built) the exceptiong ramdomly changed and complain about different variables ** 
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable voxelnet/rpn/deconv3/deconv3-BatchNorm2d-0/beta from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/voxelnet/rpn/deconv3/deconv3-BatchNorm2d-0/beta/N10tensorflow3VarE does not exist.
	 [[{{node voxelnet/rpn/deconv3/deconv3-BatchNorm2d-0/beta/Read/ReadVariableOp}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 632, in <module>
    train(cfgPath,modelPath) 
  File "train.py", line 566, in train
    raise e
  File "train.py", line 391, in train
    save_path = manager.save()
  File "/home/babak/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/checkpoint_management.py", line 807, in save
    save_path = self._checkpoint.write(prefix)
  File "/home/babak/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1543, in write
    output = self._saver.save(file_prefix=file_prefix, session=session)
  File "/home/babak/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1216, in save
    return session.run(save_path, feed_dict=feed_dict)
  File "/home/babak/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
  File "/home/babak/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/babak/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/babak/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable voxelnet/rpn/deconv3/deconv3-BatchNorm2d-0/beta from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/voxelnet/rpn/deconv3/deconv3-BatchNorm2d-0/beta/N10tensorflow3VarE does not exist.
	 [[node voxelnet/rpn/deconv3/deconv3-BatchNorm2d-0/beta/Read/ReadVariableOp (defined at /home/babak/pp/tfpp/models/voxelnet.py:303) ]]

   **My code sample**
   with sess.as_default():
        with graph.as_default():     
                init = tf.global_variables_initializer()                
                sess.run(init)                                              
                
                model_dir = pathlib.Path(model_dir)  
                
                result_path = model_dir / result_name
                    
                config = pipeline_pb2.TrainEvalPipelineConfig()    
                with open(config_path, "r") as f:
                    proto_str = f.read()
                    text_format.Merge(proto_str, config)
            
                #nput_cfg = config.eval_input_reader
                input_cfg = config.train_input_reader
                model_cfg = config.model.second
                train_cfg = config.train_config
                class_names = list(input_cfg.class_names)
                center_limit_range = model_cfg.post_center_limit_range
                
                voxel_generator = voxel_builder.build(model_cfg.voxel_generator)
                bv_range = voxel_generator.point_cloud_range[[0, 1, 3, 4]]
                box_coder = box_coder_builder.build(model_cfg.box_coder)
                target_assigner_cfg = model_cfg.target_assigner
                target_assigner = target_assigner_builder.build(target_assigner_cfg,    
                                                               bv_range, box_coder)
                
                
                net = voxelnet_builder.build(model_cfg, voxel_generator, target_assigner,sess)
                
             
                optimizer_cfg = train_cfg.optimizer
                
                dataset = input_reader_builder.build(
                    input_cfg,
                    model_cfg,
                    training=True,
                    voxel_generator=voxel_generator,
                    target_assigner=target_assigner)    
                eval_dataset = input_reader_builder.build(
                    input_cfg,
                    model_cfg,
                    training=False,
                    voxel_generator=voxel_generator,
                    target_assigner=target_assigner)
                
                def _worker_init_fn(worker_id):
                    time_seed = np.array(time.time(), dtype=np.int32)
                    np.random.seed(time_seed + worker_id)
                    print(f"WORKER {worker_id} seed:", np.random.get_state()[1][0])
                    
                dataloader = DataLoader(
                    dataset,
                    batch_size=input_cfg.batch_size,
                    shuffle=False, #True,
                    #num_workers= input_cfg.num_workers,
                    num_workers= 0,
                    pin_memory=False,
                    collate_fn=merge_second_batch)
                    #worker_init_fn=_worker_init_fn)
                
                eval_dataloader = DataLoader(
                    eval_dataset,
                    batch_size=input_cfg.batch_size,
                    shuffle=False,
                    #num_workers=input_cfg.num_workers,
                    num_workers=0,
                    pin_memory=False,
                    collate_fn=merge_second_batch)
                
            
                if train_cfg.enable_mixed_precision:
                    float_dtype = tf.float16
                else:
                    float_dtype = tf.float32
            
                #data_iter = iter(dataloader)
            
                ######################
                # TRAINING
                ######################
                log_path = 'log.txt'
                logf = open(log_path, 'a')
                logf.write(proto_str)
                logf.write("\n")
                summary_dir = model_dir / 'summary'
                summary_dir.mkdir(parents=True, exist_ok=True)
                writer = SummaryWriter(str(summary_dir))
            
                total_step_elapsed = 0
                #remain_steps = train_cfg.steps - net.get_global_step()
                t = time.time()
                ckpt_start_time = t
            
                total_loop = train_cfg.steps // train_cfg.steps_per_eval + 1
               
                clear_metrics_every_epoch = train_cfg.clear_metrics_every_epoch
            
                if train_cfg.steps % train_cfg.steps_per_eval == 0:
                    total_loop -= 1
                
                initial_learning_rate = 
                optimizer_cfg.adam_optimizer.learning_rate.exponential_decay_learning_rate.initial_learning_rate
                decay_steps = optimizer_cfg.adam_optimizer.learning_rate.exponential_decay_learning_rate.decay_steps
                decay_factor = optimizer_cfg.adam_optimizer.learning_rate.exponential_decay_learning_rate.decay_factor
                staircase = optimizer_cfg.adam_optimizer.learning_rate.exponential_decay_learning_rate.staircase
             
                loss_norm_type_dict = {
                        0: LossNormType.NormByNumExamples,
                        1: LossNormType.NormByNumPositives,
                        2: LossNormType.NormByNumPosNeg,
                    }
                
                loss_norm_type = loss_norm_type_dict[model_cfg.loss_norm_type]
                    
                losses = losses_builder.build(model_cfg.loss)
                encode_rad_error_by_sin = model_cfg.encode_rad_error_by_sin
                cls_loss_ftor, loc_loss_ftor, cls_weight, loc_weight, _ = losses
                pos_cls_weight = model_cfg.pos_class_weight
                neg_cls_weight = model_cfg.neg_class_weight
                direction_loss_weight = model_cfg.direction_loss_weight    
                box_code_size=target_assigner.box_coder.code_size
                
                ppLoss = PPLoss(
                    num_class=1,
                    cls_loss_weight=cls_weight,
                    loc_loss_weight=loc_weight,
                    pos_cls_weight=pos_cls_weight,
                    neg_cls_weight=neg_cls_weight,
                    direction_loss_weight=direction_loss_weight,
                    loss_norm_type=loss_norm_type,
                    encode_rad_error_by_sin=encode_rad_error_by_sin,
                    loc_loss_ftor=loc_loss_ftor,
                    cls_loss_ftor=cls_loss_ftor,
                    box_code_size=box_code_size,
                    use_direction_classifier=model_cfg.use_direction_classifier)
                
                         
                try:  
                    global_step = tf.Variable(0, trainable=False)                    
                    lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(initial_learning_rate, decay_steps=decay_steps, 
                   decay_rate=decay_factor,staircase=staircase)
                    optimizer = Adam(learning_rate=lr_schedule)    
                    ckpt = tf.train.Checkpoint(step=tf.Variable(1),model=net)##optimizer=optimizer)#, model=model)        
                    manager = tf.train.CheckpointManager(ckpt, "./tf_ckpts", max_to_keep=3)      
                    ckpt.restore(manager.latest_checkpoint)
                    if manager.latest_checkpoint:
                        print("Restored from {}".format(manager.latest_checkpoint))
                    else:
                        print("Initializing from scratch.")
                    
                    initv = tf.global_variables_initializer()
                    sess.run(initv)
                    
                    for _ in range(total_loop):
                        if total_step_elapsed + train_cfg.steps_per_eval > train_cfg.steps:
                            steps = train_cfg.steps % train_cfg.steps_per_eval
                        else:
                            steps = train_cfg.steps_per_eval
                        for step in range(steps):
                     
                            example = next(iter(dataloader))
                                                      
                            example_tf = example_convert_to_tf(example, float_dtype)
            
                            batch_size = example["anchors"].shape[0]
                            
                            with tf.GradientTape() as tape:
                                ret_dict = net(example_tf,training=True)
                                loss_value = ppLoss.call(example_tf, ret_dict)
                                
                            gradients = tape.gradient(loss_value["loss"], net.trainable_weights)
                            
                            optimizer.apply_gradients(zip(gradients, net.trainable_weights))
                            
                            print("step {} is done!".format(step))
                            global_step.assign_add(1)
                            if step % 10 == 0 and step != 0:                            
                                    save_path = manager.save()
                                    print("Saved checkpoint for step {}: {}".format(step, save_path))
                                    #print("Saving Model for step {}".format(step))
                                    #print("loss {:1.2f}".format(loss_value["loss"])) 
                                    #net._set_inputs(example_tf)
                                    #net.save('./PPModels/ppModel'+str(step),save_format='tf')
                   except Exception as e:
                
                    logf.close()
                    raise e        
            
    logf.close()

**Comment by amahendrakar** [comment]
@bsaravi,
I was not able to reproduce the issue from the given code. 

Could you please provide the complete code or share the `.py/.ipynb` file you are running along with the dataset? Thanks!

**Comment by bsaravi** [comment]
Thanks for your reply.
Please look at the zip file the code. the dataset are too huge too upload I have pickled 6 batch which will you the error.
Please run:
python bugTrain.py
Let me know if you need anything elese
Thanks again for you help.
babak
[tfbug1.zip](https://github.com/tensorflow/tensorflow/files/5052049/tfbug1.zip)

**Comment by amahendrakar** [comment]
@bsaravi,
On running the `bugTrain.py` file, I am facing an error stating `ModuleNotFoundError: No module named 'fire'`.

Commenting out that line throws the error `subprocess.CalledProcessError: Command 'python3 -m pybind11 --includes' returned non-zero exit status 1.`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/e969cb328cab44d46437f813bb6c1b6b/42142.ipynb). 

Also, the example you have given is fairly complex and it is hard for us to pinpoint the source of the error. Can you remove the dependencies and get the example down to the simplest possible repro so that it will be easy for us to debug the error. Thanks!

**Comment by bsaravi** [comment]
I have corrected the errors you can see the exception on running the files
I just uploaded. The error happened when there is quite complex model
please let me know if you need anything else.
Thanks,
Babak

https://colab.research.google.com/gist/amahendrakar/e969cb328cab44d46437f813bb6c1b6b/42142.ipynb#scrollTo=uG0ovu-Bmawc&uniqifier=1

**Comment by amahendrakar** [comment]
@bsaravi,
I am still facing the same error. Could you please share the updated code/files again?

Alternatively, you can run your code on Google colab and share the notebook with us. Thanks!

**Comment by amahendrakar** [comment]
Also, please take a look at [this similar](https://github.com/tensorflow/tensorflow/issues/28287) issue and let us know if it helps. Thanks!

**Comment by bsaravi** [comment]
I saw this before it does not help.  I tried to minimize the code. please see the attachment. 
I have traced the issue inside the tensorflow as well. The issue is, Checkpoint reads the graph in graph_view.py and create the save operation and sent it to the session to be run.  session can not retrieve the value of the nodes with the names came from graph before the should be a prefix mismatch in the nodes naming.

[tfbug.zip](https://github.com/tensorflow/tensorflow/files/5068991/tfbug.zip)
.

**Comment by bsaravi** [comment]
Hi Abhilash,
   Do you have any update?
Thanks,
Babak

**Comment by amahendrakar** [comment]
> [tfbug.zip](https://github.com/tensorflow/tensorflow/files/5068991/tfbug.zip)

@bsaravi,
On running the `bugTrain.py` from the zip file, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory: './configs/pointpillars/car/xyres_16.proto'`.

Please provide all the dependencies to run the code. Alternatively, you can run your code on [Google Colab](https://colab.research.google.com/notebook#create=true&language=python3) and share the notebook with us. Thanks!

**Comment by bsaravi** [comment]
I guess you are running outside the code folder. Paths are relative to the
root of the code. you need to cd to the code root.
if you unzip in tfbug forest do a cd tfbug
thanks,
Babak

**Comment by bsaravi** [comment]
I modified the code on Colab.  you can see the exception:
https://colab.research.google.com/gist/amahendrakar/3aef973b381de4aee79055579585f319/42142.ipynb
Thanks,
Babak

**Comment by bsaravi** [comment]
Is there any update on this?

**Comment by bsaravi** [comment]
Is there any update on this? 
This bug shows up even in very small network like the following code with or without subclass the keras layers:

import tensorflow.compat.v1 as tf
from tensorflow.compat.v1.keras import layers,Model
from tensorflow.compat.v1.keras.models import Sequential
from tensorflow.compat.v1.keras.backend import set_session
"""
class TModel(Model):
   def __init__(self):
      super(TModel, self).__init__()
      self.layer = Sequential(
          [
              layers.Dense(2, activation="relu", name="layer1"),
              layers.Dense(3, activation="relu", name="layer2"),
              layers.Dense(4, name="layer3"),
          ]
      )
   def call(self,inp):
      return self.layer(inp)
  
"""
model = Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)

sess = tf.Session()#config=tf_config)
graph = tf.get_default_graph()

set_session(sess)
with sess.as_default():
   with graph.as_default():
      #model = TModel()
      x = tf.ones((3, 3))
      y = model(x)
      model.save("./m1")

**Comment by nikitamaia** [comment]
Hi @bsaravi, in TF2 the preferred way to use graph mode is with `tf.function` and not `tf.Session`. The recommendation in this case would be to migrate to TF2 syntax instead of using `tf.Session`. Is there a specific reason you need to still use TF1 syntax?

**Comment by bsaravi** [comment]
Thanks Nikita for your reply.
   When I submitted the bug 6 month ago. I was using openvino 2020.4 which
does not support TF2 and I found a work around for this issue. but openvino
2021 is supporting TF2.
Best,
Babak

**Comment by nikitamaia** [comment]
Ah makes sense, sorry for the late response here! Closing this issue now since you found a work around and V2 syntax is preferred.
