### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python'

### ISSUE THREAD

**Issue by nicolas-gervais** [tensorflow/tensorflow#42233]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.3
- Python version: 3.7.7
- Installed using virtualenv? pip? conda?: Neither `pip` or `conda` worked
- CUDA/cuDNN version: 10.1, V10.1.243
- GPU model and memory: Nvidia GeForce 960M Notebook

**Describe the problem**

I get this when I import tensorflow:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\nicol\AppData\Roaming\Python\Python37\site-packages\tensorflow\__init__.py", line 41, in <module>
>     from tensorflow.python.tools import module_util as _module_util
> ModuleNotFoundError: No module named 'tensorflow.python'

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
conda create -n tf python=3.7
pip install tensorflow
python
```
```
import tensorflow
```

**Any other info / logs**

If I run `help('modules')` in Python, I get:

> Failed to import TensorFlow. Please note that TensorFlow is not installed by default when you install Gin-Config. This is so that users can decide whether to install the GPU-enabled TensorFlow package. To use Gin-Config, please install the most recent version of TensorFlow, by following instructions at https://tensorflow.org/install.

**Comment by Saduf2019** [comment]
@nicolas-gervais 
Request you to uninstall python and tensorflow .Please, install it again and see if the problem still persists.(You need a 64-bit version of Python and in your case are using a 32-bit version)
Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019.

I don't think Tensorflow support 32 bit architecture.Please, refer the issue #32315

Please, follow the instructions from [here](https://www.tensorflow.org/install/source_windows)..Thanks!

Please refer to these issues with similar error:
#34722  [link](https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip)

**Comment by nicolas-gervais** [comment]
@Saduf2019 

Hello and thanks for the response. May I ask what leads you to believe that my Python is 32bit? I have been using Tensorflow for a long time with no problem. I've been using RNNs more than usual and that's when the problem started. Now the problem is generalized to all my environments (venv, conda) and reinstalling hasn't worked. 

I will still do everything you listed to be absolutely sure.

**Comment by nicolas-gervais** [comment]
> Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
> Type "help", "copyright", "credits" or "license" for more information.

```
>>> import sys
>>> sys.version
```

> '3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]'

**Comment by nicolas-gervais** [comment]
So I deleted this folder:
```
C:\Users\nicol\AppData\Roaming\Python\Python37
```
And everything fell into place, after a few days of not being able to do my work. For now, I guess it works...

**Comment by nicolas-gervais** [comment]
So I deleted this folder:
```
C:\Users\nicol\AppData\Roaming\Python\Python37
```
And everything fell into place, after a few days of not being able to do my work. For now, I guess it works...

**Comment by Saduf2019** [comment]
@nicolas-gervais 
Thank you for your update,glad the issue is resolved.

**Comment by Rishav8989** [comment]
still not working I've updated my TensorFlow to version 2.9.0
