### ISSUE TITLE
tf.convert_to_tensor and tf.constant ignoring tf.device

### ISSUE THREAD

**Issue by jacksonloper** [tensorflow/tensorflow#42242]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/device

## Description of issue (what needs changing):

At least on 2.3.0, it seems to me that 
```
import numpy.random as npr
import tensorflow as tf
with tf.device("GPU"):
  A=tf.convert_to_tensor(npr.randn(500))
```
will create an eager tensor `A` on the CPU device (it will not allocate ram on the gpu).  This is counter-intuitive to someone who has only read the doc as it is written.  My understanding is that this happens because tf.convert_to_tensor isn't an op, and tf.device only deals with ops.  

### Clear description

The doc is pretty short now, and I don't think it would hurt to add a little remark, something like this:

*Note* -- `tf.convert_to_tensor` does not create an op.  As such, it ignores the contexts created by tf.device.  To ensure a given tensor is assigned memory on a particular device, one can wrap convert_to_tensor inside a `tf.identity` op.

Thoughts?

**Comment by ravikyram** [comment]
@jacksonloper 

Can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by jacksonloper** [comment]
I don't think there's really an issue with the code per se, it's a doc
issue.  But how about this?

Given current docs, one would expect: A.device (from post, above) to be GPU

Actually: A.device is CPU

Solution: make it clear in the docs why this is the case

Does that help?

**Comment by jvishnuvardhan** [comment]
@jacksonloper Currently there is some description [here](https://www.tensorflow.org/guide/gpu). You can set the device placement for any op. You can also check some useful info [here](https://www.tensorflow.org/guide/variable).

Setting `set_log_device_placement` will place the ops on the specified device.
import tensorflow as tf
tf.debugging.set_log_device_placement(True)
import numpy.random as npr
with tf.device('/GPU:0'):
  A=tf.convert_to_tensor(npr.randn(500))
  B=tf.convert_to_tensor(npr.randn(500))

C = tf.add(A, B)
print(C)

If you set [`set_soft_device_placement`](https://www.tensorflow.org/api_docs/python/tf/config/set_soft_device_placement) along with `set_log_device_placement`, then if the specified device is not present, then the code silently place them in the available device. Thanks!

If you plan to update any document, then please feel free to create a PR for updating the doc. Thanks!

**Comment by jacksonloper** [comment]
I'm not exactly sure why you're referring me to those docs -- I'm quite familiar with the docs you mention.  I'm well-aware that running tf.Variable or tf.constant inside a tf.device("GPU") block will allocate it on the GPU.  The thing is that **running tf.convert_to_tensor inside a tf.device("GPU") block does not allocate ram on the GPU**.  And that is surprising to the uninitiated. 

So the proposal is to clarify this with a remark on the tf.device page.  

Does that make sense?  Or am I missing something here?  Happy to put in a PR, just want to make sure this is crystal clear.

**Comment by MarkDaoust** [comment]
Yes. I see your point.

Even with soft device placement turned off a constant in a `with tf.device("GPU"):` still reports it's device as CPU.

Whatever is happening here it's a little more subtle than "`convert_to_tensor` does not create an op." since it creates `tf.constant` op.

If you capture the tf.Graph you see the "const" op with it's device set to GPU:

```
import numpy.random as npr
import tensorflow as tf
tf.config.set_soft_device_placement(False)
tf.debugging.set_log_device_placement(True)
with tf.Graph().as_default() as g:
  with tf.device("GPU"):
    Ag=tf.convert_to_tensor(npr.randn(2)) 
    Bg = Ag + 1
print(g.as_graph_def())
print()
```

```
node {
  name: "Const"
  op: "Const"
  device: "/device:GPU:*"
  attr {
    key: "dtype"
    value {
      type: DT_DOUBLE
    }
  }
...
```

As you said identity does copy the tensor to the device:
```
with tf.device("GPU"):
  A=tf.convert_to_tensor(npr.randn(2))
  B = tf.identity(A)

print(A.device)
print(B.device)
print()
```

```
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0
```

So I do agree that this is surprising.

**Comment by jacksonloper** [comment]
Lol so much for me being "well-aware" that tf.constant respects tf.device.  I didn't even check, like a fool!

Well that is kind of interesting.  I guess it's a bug then, not a doc issue?

**Comment by MarkDaoust** [comment]
+@jaingaurav

This looks like a bug to me. Gaurav do you know more about what's going on here? Can you help triage?

**Comment by jaingaurav** [comment]
So is the concern that `tf.convert_to_tensor` doesn't create a GPU tensor even with soft placement turned off? I think this was intentional right?

@ccrusius: Could you confirm that all the behaviors above are as intended? Perhaps we just need to clarify the docs a bit further.

**Comment by MarkDaoust** [comment]
Yes, exactly. 

It's fine if it's intentional, but we couldn't find any doc describing this behavior. It would be good to know for sure:

1. That this is intentional.
2. Why.

**Comment by ccrusius** [comment]
Yes, the behaviors are as intended. The documentation for `tf.constant` mentions it always creates host tensors, and that `tf.identity` will create tensors in the specified devices.

I agree the behavior can be confusing, and we need better documentation here. In particular, `convert_to_tensor` makes no mention of this behavior.

**Comment by miguelusque** [comment]
Hi,

I have gone through this thread and, somehow, I do not fully understand the rationale behind the design approach of always creating the tensor into host memory, when invoking `tf.convert_to_tensor()`.

If the remaining ops are being executed in device memory, why do not allocate the Tensor in device memory when a GPU is available.

I faced this behaviour when creating a snippet code to showcase how to interact TensorFlow tensors with JAX and CuPy libraries. None of them accept DLPack objects hosted in host memory.

The following code fails:
> src = tf.convert_to_tensor([[1, 2], [3, 4]])
> dst = cp.fromDlpack(tf.experimental.dlpack.to_dlpack(src)) 

Could you please reconsider allocating those tensors in host/device memory depending if a GPU device is present?

Thanks!

Regards,
Miguel

**Comment by mohantym** [comment]
Hi @jacksonloper !

I think this issue has been resolved in 2.8.2 version . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/2829b521d66c28309ca190c1c6a284ff/git_42242.ipynb#scrollTo=lgYpWWNWhpg-) for reference. 
Could you let us know from your end.

Thank you!

**Comment by miguelusque** [comment]
Hi, I would say this issue is still relevant. The bug I mentioned in my original comment is still present.

I have just tried it with 22.09 version of TF2. Please see below the bug I am facing:

Could you please re-open this issue? Thanks!

> root@1994a2ae8d40:/workspace# python3
> Python 3.8.10 (default, Jun 22 2022, 20:18:18)
> [GCC 9.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import tensorflow as tf
> >>> import cupy as cp
> >>> tf.__version__
> '2.9.1'
> >>> cp.__version__
> '11.0.0'
> >>> src = tf.convert_to_tensor([[1, 2], [3, 4]])
> 2022-10-06 09:59:57.941880: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2022-10-06 09:59:59.165192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1553] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14622 MB memory:  -> device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:89:00.0, compute capability: 7.0
> 2022-10-06 09:59:59.166338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1553] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 14622 MB memory:  -> device: 1, name: Tesla V100-SXM2-16GB, pci bus id: 0000:8a:00.0, compute capability: 7.0
> >>> dst = cp.from_dlpack(tf.experimental.dlpack.to_dlpack(src))
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "cupy/_core/dlpack.pyx", line 336, in cupy._core.dlpack.from_dlpack
>   File "cupy/_core/dlpack.pyx", line 366, in cupy._core.dlpack.from_dlpack
>   File "cupy/_core/dlpack.pyx", line 261, in cupy._core.dlpack._dlpack_to_cupy_array
>   File "cupy/_core/dlpack.pyx", line 179, in cupy._core.dlpack.DLPackMemory.__init__
> RuntimeError: CuPy is built against CUDA, different from the backend that backs the incoming DLPack tensor
