### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by twinkle055** [tensorflow/tensorflow#42724]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 8
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
TensorFlow installed from (source or binary):
TensorFlow version: 2.3.0
Python version: 3.8.3
Installed using virtualenv? pip? conda?: conda
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from source): N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Provide the exact sequence of commands / steps that you executed before running into the problem : Just ran a file with import tensorflow on python

C:\Users\User\.conda\envs\tensor\pythonw.exe F:/Tech_With_Tim/tensorEnv/test.py
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/Tech_With_Tim/tensorEnv/test.py", line 1, in <module>
    import tensorflow
  File "C:\Users\User\.conda\envs\tensor\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\User\.conda\envs\tensor\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\User\.conda\envs\tensor\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\User\.conda\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\User\.conda\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\tensor\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1

**Comment by amahendrakar** [comment]
@twinkle055,
In order to expedite the trouble-shooting process, please fill in the below details

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
- Provide the exact sequence of commands / steps that you executed before running into the problem

Also if you are using Anaconda environment, please submit a new issue from [this link](https://github.com/ContinuumIO/anaconda-issues/issues), as these issues are tracked in the Anaconda repo. Thanks!

**Comment by twinkle055** [comment]
My issue was solved.
I downgraded my tensorflow because my tensorflow version was not compatible with python 3.7.
I used the command - pip install tensorflow==1.2.0
and also, the command - pip install keras==2.2.4
This resolved my issue.

**Comment by aminanderian** [comment]
i have same issue, 
python v 3.8.5
pip and conda
windows 10

that's not fixed and pip install tensorflow==1.2.0 is not avalable,
can you help me ?!

**Comment by aminanderian** [comment]
i tried to use 

> pip install tensorflow==2.2.0

 but that was not useful ...

**Comment by twinkle055** [comment]
> i have same issue,
> python v 3.8.5
> pip and conda
> windows 10
> 
> that's not fixed and pip install tensorflow==1.2.0 is not avalable,
> can you help me ?!

@aminanderian That is because... python 3.8.5 is not compatible with renditions 1.2.0
I would suggest downgrading your python to 3.7.9 or any version in context to 3.7

**Comment by aminanderian** [comment]
> > i have same issue,
> > python v 3.8.5
> > pip and conda
> > windows 10
> > that's not fixed and pip install tensorflow==1.2.0 is not avalable,
> > can you help me ?!
> 
> @aminanderian That is because... python 3.8.5 is not compatible with tensorflow 1.2.0
> I would suggest downgrading your python to 3.7.9 or any version in context to 3.7

thanks, but I dwongrade it to 3.7.9 and tried it again it gave me this error:
ERROR: Could not find a version that satisfies the requirement tensorflow==1.2.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.2.0

**Comment by twinkle055** [comment]
> > > i have same issue,
> > > python v 3.8.5
> > > pip and conda
> > > windows 10
> > > that's not fixed and pip install tensorflow==1.2.0 is not avalable,
> > > can you help me ?!
> > 
> > 
> > @aminanderian That is because... python 3.8.5 is not compatible with tensorflow 1.2.0
> > I would suggest downgrading your python to 3.7.9 or any version in context to 3.7
> 
> thanks, but I dwongrade it to 3.7.9 and tried it again it gave me this error:
> ERROR: Could not find a version that satisfies the requirement tensorflow==1.2.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
> ERROR: No matching distribution found for tensorflow==1.2.0

Ok, then
Install tensorflow 1.14.0
pip install tensorflow==1.14.0

**Comment by aminanderian** [comment]
> > > > i have same issue,
> > > > python v 3.8.5
> > > > pip and conda
> > > > windows 10
> > > > that's not fixed and pip install tensorflow==1.2.0 is not avalable,
> > > > can you help me ?!
> > > 
> > > 
> > > @aminanderian That is because... python 3.8.5 is not compatible with tensorflow 1.2.0
> > > I would suggest downgrading your python to 3.7.9 or any version in context to 3.7
> > 
> > 
> > thanks, but I dwongrade it to 3.7.9 and tried it again it gave me this error:
> > ERROR: Could not find a version that satisfies the requirement tensorflow==1.2.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 1.15.3, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
> > ERROR: No matching distribution found for tensorflow==1.2.0
> 
> Ok, then
> Install tensorflow 1.14.0
> pip install tensorflow==1.14.0

Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import tensorflow

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.





I have it again ...

**Comment by aminanderian** [comment]
I test the consule with import numpy to know if system has any other error that numpy was ok,
you know what's the main error !?

**Comment by twinkle055** [comment]
Check this
[https://github.com/tensorflow/tensorflow/issues/23683#issuecomment-510718458](url)

**Comment by aminanderian** [comment]
thanks

**Comment by amahendrakar** [comment]
> My issue was solved.
> I downgraded my tensorflow because my tensorflow version was not compatible with python 3.7.
> I used the command - pip install tensorflow==1.2.0
> and also, the command - pip install keras==2.2.4
> This resolved my issue.

@twinkle055,
Please feel free to close the issue if resolved. Thanks!

**Comment by amahendrakar** [comment]
@aminanderian,
Could you please submit a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!
