### ISSUE TITLE
typo in tutorials/mnist/beginners/index.html

### ISSUE THREAD

**Issue by infotek** [tensorflow/tensorflow#4329]
https://www.tensorflow.org/versions/r0.10/tutorials/mnist/beginners/index.html

"East entry in the tensor is a pixel intensity between 0 and 1, for a particular pixel in a particular image."

 should probably be "Each entry...".

Sorry if this is an inappropriate forum to draw attention to this.  There was not corrections contact.

**Comment by ivmarkp** [comment]
I see this typo was fixed 24 days ago [[commit](https://github.com/tensorflow/tensorflow/commit/e144b79a4e740c550f4866bfa33b1b4ff8790e8b)]. I wonder why the change is not reflected yet on the concerned webpage?

**Comment by DjangoPeng** [comment]
@andydavis1 You can close the issus.
I have checked the `master branch`, and the typo has been fixed by the commit which @ivmarkp referenced. The reason why it still exists is that the `tensorflow.org` show you the tutorial of `r0.10 branch` . So, when the next version(maybe v0.11), the problem will be fixed automatically.
