### ISSUE TITLE
Cannot convert CenterNet+KeyPoints Model Zoo tf2 models to tflite

### ISSUE THREAD

**Issue by twkx** [tensorflow/tensorflow#43495]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4 LTS
- TensorFlow installed from (source or binary): binary (tf-nightly)
- TensorFlow version (use command below): 2.4.0-dev20200907
- Python version: 3.6.9
- CUDA/cuDNN version: 11.0/8.0

**Describe the current behavior**

When I try to convert a model from TensorFlow 2 Detection Model Zoo into a tflite version, I get some error.

[EDIT] This is only the case for models using CenterNet AND KeyPoints. All other models are OK

**Describe the expected behavior**

Convertion is successfull

**Standalone code to reproduce the issue**

Download "CenterNet Resnet50 V1 FPN Keypoints 512x512" from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

Uncompress the archive

Run "tflite_convert --saved_model_dir=centernet_resnet50_v1_fpn_512x512_kpts_coco17_tpu-8/saved_model --output_file=model.tflite"

I got the following error:

loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): error: requires element_shape to be 1D tensor during TF Lite transformation pass
loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
Traceback (most recent call last):
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 199, in toco_convert_protos
    enable_mlir_converter)
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/lite/python/wrap_toco.py", line 38, in wrapped_toco_convert
    enable_mlir_converter)
Exception: <unknown>:0: error: loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): requires element_shape to be 1D tensor during TF Lite transformation pass
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): see current operation: %456 = "tf.TensorListReserve"(%67, %77) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf.variant<tensor<*xf32>>>
<unknown>:0: error: loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): see current operation: %456 = "tf.TensorListReserve"(%67, %77) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf.variant<tensor<*xf32>>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/biroute/.local/bin/tflite_convert", line 8, in <module>
    sys.exit(main())
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 640, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/biroute/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/biroute/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 623, in run_main
    _convert_tf2_model(tflite_flags)
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 239, in _convert_tf2_model
    tflite_model = converter.convert()
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 726, in convert
    output_tensors)
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 643, in convert
    **converter_kwargs)
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 573, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/biroute/.local/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 202, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): requires element_shape to be 1D tensor during TF Lite transformation pass
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): see current operation: %456 = "tf.TensorListReserve"(%67, %77) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf.variant<tensor<*xf32>>>
<unknown>:0: error: loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: note: loc(callsite(callsite("map/TensorArrayV2_2@__inference___call___13919" at "StatefulPartitionedCall@__inference_signature_wrapper_15800") at "StatefulPartitionedCall")): see current operation: %456 = "tf.TensorListReserve"(%67, %77) {device = ""} : (tensor<i32>, tensor<i32>) -> tensor<!tf.variant<tensor<*xf32>>>

**Comment by abattery** [comment]
Sorry for encountering this issue. Current TFLite MLIR converter is able to handle 1-D TensorLists only. After loading saved model, you might need to specify input shapes of the model to make the TensorLists proper shapes in Python.

**Comment by twkx** [comment]
@abattery Thanks for your quick answer.

I tried the following code, and it gives exactly the same previous error (which is normal):

    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
    tflite_model = converter.convert()
    open("model.tflite", "wb").write(tflite_model)

then I modified it as you requested, but I now have a different error:

    saved_model = tf.saved_model.load("centernet_resnet50_v1_fpn_512x512_kpts_coco17_tpu-8/saved_model")
    concrete_func = saved_model.signatures["serving_default"]
    concrete_func.inputs[0].set_shape([1, 128, 128, 3])
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
    tflite_model = converter.convert()
    open("model.tflite", "wb").write(tflite_model)

020-09-24 09:36:47.818409: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:315] Ignored output_format.
2020-09-24 09:36:47.818448: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:318] Ignored drop_control_dependency.
loc("Func/StatefulPartitionedCall/input/_0"): error: requires all operands and results to have compatible element types
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 196, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "/usr/local/lib/python3.8/site-packages/tensorflow/lite/python/wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x128x128x3x!tf.quint8>) -> tensor<1x128x128x3xui8>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_model.py", line 13, in <module>
    main()
  File "export_model.py", line 9, in main
    tflite_model = converter.convert()
  File "/usr/local/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 1135, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/usr/local/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 960, in convert
    return super(TFLiteFrozenGraphConverterV2,
  File "/usr/local/lib/python3.8/site-packages/tensorflow/lite/python/lite.py", line 641, in convert
    result = _toco_convert_impl(
  File "/usr/local/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 594, in toco_convert_impl
    data = toco_convert_protos(
  File "/usr/local/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 202, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
<unknown>:0: note: loc("Func/StatefulPartitionedCall/input/_0"): see current operation: %1 = "tf.Identity"(%arg0) {device = ""} : (tensor<1x128x128x3x!tf.quint8>) -> tensor<1x128x128x3xui8>

**Comment by twkx** [comment]
still crashing with tf-nightly-2.4.0.dev20200930

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/09d4c59e95cf33664294291c9d9e3647/43495.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/4305e4aacd3fef25bef156da96c0617b/43495-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by twkx** [comment]
Hi,

I have made a simple test: I have downloaded every models in "TensorFlow 2 Detection Model Zoo" and tried to convert them with tflite_convert.

It appears that only 4 models failed to convert:

centernet_hg104_1024x1024_kpts_coco17_tpu-32
centernet_hg104_512x512_kpts_coco17_tpu-32
centernet_resnet50_v1_fpn_512x512_kpts_coco17_tpu-8
centernet_resnet50_v2_512x512_kpts_coco17_tpu-8

The common point in those models is that they are the ones using both centernet AND keypoints.

I hope it will give you some clues to investigate...

**Comment by twkx** [comment]
Hi TensorFlow Team,

It seems that the bug was on the side of object_detection library.

It has been fixed in commit baacb20:
https://github.com/tensorflow/models/commit/baacb20d15066935e4a23c09b1c1a6843331172f#diff-ee421de3daf8a640c16b7f6f5a5d3399d28ded3a5c073b9ee10e5e2a88b7e94f

I have trained and exported successfully a centernet with keypoints model with the new object_detection library and it's now ok.

As long as the models in Model Zoo will be trained again with new object_detection framework, they will be ok too!

Thanks for your support

**Comment by orihash** [comment]
> Hi TensorFlow Team,
> 
> It seems that the bug was on the side of object_detection library.
> 
> It has been fixed in commit baacb20:
> [tensorflow/models@baacb20#diff-ee421de3daf8a640c16b7f6f5a5d3399d28ded3a5c073b9ee10e5e2a88b7e94f](https://github.com/tensorflow/models/commit/baacb20d15066935e4a23c09b1c1a6843331172f#diff-ee421de3daf8a640c16b7f6f5a5d3399d28ded3a5c073b9ee10e5e2a88b7e94f)
> 
> I have trained and exported successfully a centernet with keypoints model with the new object_detection library and it's now ok.
> 
> As long as the models in Model Zoo will be trained again with new object_detection framework, they will be ok too!
> 
> Thanks for your support

Hey, can you please tell me how to convert this model to tflite because I still can not do it ?

**Comment by ArditHalimi** [comment]
> Hi TensorFlow Team,
> 
> It seems that the bug was on the side of object_detection library.
> 
> It has been fixed in commit baacb20:
> [tensorflow/models@baacb20#diff-ee421de3daf8a640c16b7f6f5a5d3399d28ded3a5c073b9ee10e5e2a88b7e94f](https://github.com/tensorflow/models/commit/baacb20d15066935e4a23c09b1c1a6843331172f#diff-ee421de3daf8a640c16b7f6f5a5d3399d28ded3a5c073b9ee10e5e2a88b7e94f)
> 
> I have trained and exported successfully a centernet with keypoints model with the new object_detection library and it's now ok.
> 
> As long as the models in Model Zoo will be trained again with new object_detection framework, they will be ok too!
> 
> Thanks for your support

Hello @twkx,

I have the same issue as you, can you give some more detailed information on how you fixed this issue?
I have checked out to the commit "baacb20" but it has not fixed my issue!

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_tflite_tf2.py", line 13, in <module>
    tflite_model = converter.convert()
  File "/home/ardit/repos/solaborate/Solaborate.ML/solaborate_packages/model_training/tf_env/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 1135, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/home/ardit/repos/solaborate/Solaborate.ML/solaborate_packages/model_training/tf_env/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 961, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/home/ardit/repos/solaborate/Solaborate.ML/solaborate_packages/model_training/tf_env/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 644, in convert
    **converter_kwargs)
  File "/home/ardit/repos/solaborate/Solaborate.ML/solaborate_packages/model_training/tf_env/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 613, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/ardit/repos/solaborate/Solaborate.ML/solaborate_packages/model_training/tf_env/lib/python3.6/site-packages/tensorflow/lite/python/convert.py", line 216, in toco_convert_protos
    raise ConverterError(str(e))
tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc("Func/StatefulPartitionedCall/input/_0"): requires all operands and results to have compatible element types
```

**Comment by karimnosseir** [comment]
Hi Everyone,

We have a change in progress to fix this from our side too.
To explain the problem,
Your model has input with TF type QUINT8, TFLite doesn't understands this type, since this type lacks all quantization information that TFLite relies on.

So instead, if you can update your model to use UINT8 instead then it should work.

We are working to include this change inside the converter if we saw it, so we can handle these cases without users need to change the model.

Thanks

**Comment by orihash** [comment]
Can give me a detailed explanation on how can I update my model to use UINT8, because im getting this error:
ValueError: Unsupported tf.dtype <dtype: 'quint8'>

**Comment by MeghnaNatraj** [comment]
The model "CenterNet Resnet50 V1 FPN Keypoints 512x512" from [tf2_detection_zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md) has a flex op: 'GatherV2' and that's the reason it cannot be converted to a TFLite model (without setting the right flags).

However, the error message is a bit misleading. The input tensor is "uint8" and not "quint8". The actual error, i.e, the presence of a Flex or Select TF op shows up if we update the model's input shape, save it, and then use this model.

**1. UNSUCCESSFUL CONVERSION**
```
# RUN ONCE (Update the model)
model = tf.saved_model.load(model_dir)
concrete_func = model.signatures['serving_default']
concrete_func.inputs[0].set_shape([1, 512, 512, 3])
tf.saved_model.save(model, model_dir)
# RUN REPEATEDLY (Convert the model)
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, signature_keys=['serving_default'])
tflite_model = converter.convert()
```
ERROR:
```
.
.
google3.third_party.tensorflow.lite.python.convert.ConverterError: <unknown>:0: error: loc(callsite(callsite(callsite("GatherV2@__inference___call___40671" at "StatefulPartitionedCall@__inference_restored_function_body_69773") at "StatefulPartitionedCall@__inference_signature_wrapper_70526") at "StatefulPartitionedCall")): 'tf.GatherV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite(callsite("GatherV2_1@__inference___call___40671" at "StatefulPartitionedCall@__inference_restored_function_body_69773") at "StatefulPartitionedCall@__inference_signature_wrapper_70526") at "StatefulPartitionedCall")): 'tf.GatherV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: loc("cond/GatherV2_3@__inference_cond_true_13295_36597"): 'tf.GatherV2' op is neither a custom op nor a flex op
<unknown>:0: error: loc("cond/GatherV2_4@__inference_cond_true_13295_36597"): 'tf.GatherV2' op is neither a custom op nor a flex op
<unknown>:0: error: loc("cond/GatherV2_5@__inference_cond_true_13295_36597"): 'tf.GatherV2' op is neither a custom op nor a flex op
<unknown>:0: error: loc("cond/GatherV2_7@__inference_cond_true_13295_36597"): 'tf.GatherV2' op is neither a custom op nor a flex op
<unknown>:0: error: loc("cond/GatherV2_6@__inference_cond_true_13295_36597"): 'tf.GatherV2' op is neither a custom op nor a flex op
<unknown>:0: error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: GatherV2
Details:
	tf.GatherV2 {batch_dims = 1 : i64, device = ""}
	tf.GatherV2 {batch_dims = 2 : i64, device = ""}
```



**2. SUCCESSFUL CONVERSION**
To successfully convert this model, run the following code by setting the correct converter flags :

```
# RUN ONCE (Update the model)
model = tf.saved_model.load(model_dir)
concrete_func = model.signatures['serving_default']
concrete_func.inputs[0].set_shape([1, 512, 512, 3])
tf.saved_model.save(model, model_dir)
# RUN REPEATEDLY (Convert the model)
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, signature_keys=['serving_default'])
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
```

**Comment by kirienkomaxym** [comment]
@MeghnaNatraj can you please specify which kind of saved model you use here:
 
> model = tf.saved_model.load(model_dir)
> converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, signature_keys=['serving_default'])

Ive used both .pb model that were created by exporter_main_v2.py and export_tflite_graph_tf2.py, in the first case the model has wrong input shape of 'shape': array([1, 1, 1, 3], dtype=int32). And for the second exported I got huge accuracy drop, the detection scores are about 0.0001 each.

While the inference graph created by exporter_main_v2.py and runs via tf works satisfactorily. Ive also tryied model quantization steps, no matter what I got low scores while using centernet architectures converted to the tflite.

**Comment by MeghnaNatraj** [comment]
@kirienkomaxym  The files you are referring to are unrelated to this issue. With regards to the [this comment above](https://github.com/tensorflow/tensorflow/issues/43495#issuecomment-764702064) I used model "CenterNet Resnet50 V1 FPN Keypoints 512x512" from [tf2_detection_zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). The direct link the models is [CenterNet Resnet50 V1 FPN Keypoints 512x512](http://download.tensorflow.org/models/object_detection/tf2/20200711/centernet_resnet50_v1_fpn_512x512_kpts_coco17_tpu-8.tar.gz)

The `model_dir` is initialized to the path to the downloaded model. eg: `model_dir=/path/to/CenterNet_Resnet50_V1_FPN_Keypoints_512x512_model_dir` after it has been unzipped/uncompressed.

You can update the input shape as shown in [this comment above](https://github.com/tensorflow/tensorflow/issues/43495#issuecomment-764702064). You need to verify if the inference using the TF model, TF float model are accurate before proceeding to [post training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization).

**Comment by MeghnaNatraj** [comment]
UPDATE:

With the latest TF Nightly build, conversion works directly without having to update the model

```
# Install TF Nightly (latest TF version which is ongoing development)
# TODO: Restart your runtime after running the following command
!pip install tf-nightly

# Import commands
import tensorflow as tf

# Convert the TF model to TF Lite model
# TODO: Update the path to the model as given below
model_dir = "centernet_resnet50_v1_fpn_512x512_kpts_coco17_tpu-8/saved_model"
converter = tf.lite.TFLiteConverter.from_saved_model(model_dir, signature_keys=['serving_default'])
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
```

*Note: The model 'tf.ConcatV2' op which is not available in TFLite but it is defined in TF. See instructions: https://www.tensorflow.org/lite/guide/ops_select, which provides details on how you can run inference on this model.*

**Comment by VirVisha** [comment]
@MeghnaNatraj I have followed the steps as stated above. Unable to set the tensor, i am getting message ValueError: Cannot set tensor: Dimension mismatch. Got 562 but expected 1 for dimension 1 of input 0., while using the Interpreter

**Comment by VirVisha** [comment]
ON inspecting input details following is being displayed
print(input_details)

[{'name': 'serving_default_input_tensor:0', 'index': 0, 'shape': array([1, 1, 1, 3], dtype=int32), 'shape_signature': array([ 1, -1, -1,  3], dtype=int32), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

print(output_details)
[{'name': 'StatefulPartitionedCall:7', 'index': 46005, 'shape': array([    1, 49104,     1], dtype=int32), 'shape_signature': array([    1, 49104,     1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:4', 'index': 46120, 'shape': array([1, 1], dtype=int32), 'shape_signature': array([ 1, -1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:6', 'index': 45988, 'shape': array([    1, 49104,     4], dtype=int32), 'shape_signature': array([    1, 49104,     4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:5', 'index': 46103, 'shape': array([1], dtype=int32), 'shape_signature': array([1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:1', 'index': 46191, 'shape': array([1, 1, 1], dtype=int32), 'shape_signature': array([ 1, -1, -1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:2', 'index': 46173, 'shape': array([1, 1], dtype=int32), 'shape_signature': array([ 1, -1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:3', 'index': 46156, 'shape': array([1, 1, 1], dtype=int32), 'shape_signature': array([ 1, -1, -1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'StatefulPartitionedCall:0', 'index': 46138, 'shape': array([1, 1], dtype=int32), 'shape_signature': array([ 1, -1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

**Comment by VirVisha** [comment]
Following is the link to the google colab file https://colab.research.google.com/drive/1dpJ05nLl-stqu8lC9P4mwoIEbBmyxFBU#scrollTo=7jf7RQ98iY4i

Can anyone guide me in resolving the issue...

**Comment by MeghnaNatraj** [comment]
@VirVisha is it possible to provide access to the [colab](https://colab.research.google.com/drive/1dpJ05nLl-stqu8lC9P4mwoIEbBmyxFBU#scrollTo=7jf7RQ98iY4i)? (enable view permission for everyone)

**Comment by VirVisha** [comment]
Done the same the link is https://drive.google.com/file/d/1dpJ05nLl-stqu8lC9P4mwoIEbBmyxFBU/view?usp=sharing

**Comment by abattery** [comment]
Suggestion: better to file a new post instead of discussing on the closed post in order to keep each issue focused.

**Comment by VirVisha** [comment]
I have done the same at this link https://github.com/tensorflow/tensorflow/issues/50301

**Comment by abattery** [comment]
Then, let's move on the discussion at the new post #50301.
