### ISSUE TITLE
InvalidArgumentError with `Conv1D` which has the same `dilation_rate` as the batch size, using `tf.keras.Model.fit`, on TPU

### ISSUE THREAD

**Issue by Hiroshiba** [tensorflow/tensorflow#43690]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6.9
- Accelerator: TPU

**Describe the current behavior**
When I optimized `Conv1D`, which has the same `dilation_rate` as the batch size, using `tf.keras.Model.fit`, I encountered the following error.

```
InvalidArgumentError: 9 root error(s) found.
  (0) Invalid argument: {{function_node __inference_train_function_5549}} Compilation failure: Reshape's input dynamic dimension is decomposed into multiple output dynamic dimensions, but the constraint is ambiguous and XLA can't infer the output dimension %reshape.40 = f32[8,8,2047,128]{3,2,1,0} reshape(f32[<=64,2047,128]{2,1,0} %reshape.39), metadata={op_type="BatchToSpaceND" op_name="dilated_conv1d_1/conv1d_1/conv1d/BatchToSpaceND"}. Constraint: multiple_of: 8, stride: 1
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_4759666286058538557/_4}}]]
	 [[tpu_compile_succeeded_assert/_4759666286058538557/_4/_197]]
  (1) Invalid argument: {{function_node __inference_train_function_5549}} Compilation failure: Reshape's input dynamic dimension is decomposed into multiple output dynamic dimensions, but the constraint is ambiguous and XLA can't infer the output dimension %reshape.40 = f32[8,8,2047,128]{3,2,1,0} reshape(f32[<=64,2047,128]{2,1,0} %reshape.39), metadata={op_type="BatchToSpaceND" op_name="dilated_conv1d_1/conv1d_1/conv1d/BatchToSpaceND"}. Constraint: multiple_of: 8, stride: 1
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_4759666286058538557/_4}}]]
	 [[tpu_compile_succeeded_assert/_4759666286058538557/_4/_157]]
  (2) Invalid argument: {{function_node __inference_train_function_5549}} Compilation failure: Reshape's input dynamic dimension is decomposed into multiple output dynamic dimensions, but the constraint is ambiguous and XLA can't infer the output dimension %reshape.40 = f32[8,8,2047,128]{3,2,1,0} reshape(f32[<=64,2047,128]{2,1,0} %reshape.39), metadata={op_type="BatchToSpaceND" op_name="dilated_conv1d_1/conv1d_1/conv1d/BatchToSpaceND"}. Constraint: multiple_of: 8, stride: 1
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_4759666286058538557/_4}}]]
	 [[tpu_compile_succeeded_assert/_4759666286058538557/_4/_137]]
  (3) ...
```
This error does not occur if I forward using `strategy.run`.
A detailed error log is attached below.

**Describe the expected behavior**
I want to optimize it without errors.

**Standalone code to reproduce the issue**
Colab https://colab.research.google.com/drive/1W-eM2EwzYSMhHyN4GDUd22nKSLrrka3v?usp=sharing
gist https://gist.github.com/Hiroshiba/9c1914dbf57228204a4ed1f661168d36

**Other info / logs** Include any logs or source code that would be helpful to
<details>

```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-5-5265a4b37c17> in <module>()
     13     steps_per_epoch=5,
     14     epochs=1,
---> 15     shuffle=False,
     16 )

14 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
    106   def _method_wrapper(self, *args, **kwargs):
    107     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
--> 108       return method(self, *args, **kwargs)
    109 
    110     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1101               logs = tmp_logs  # No error, now safe to assign to logs.
   1102               end_step = step + data_handler.step_increment
-> 1103               callbacks.on_train_batch_end(end_step, logs)
   1104         epoch_logs = copy.copy(logs)
   1105 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in on_train_batch_end(self, batch, logs)
    438     """
    439     if self._should_call_train_batch_hooks:
--> 440       self._call_batch_hook(ModeKeys.TRAIN, 'end', batch, logs=logs)
    441 
    442   def on_test_batch_begin(self, batch, logs=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in _call_batch_hook(self, mode, hook, batch, logs)
    287       self._call_batch_begin_hook(mode, batch, logs)
    288     elif hook == 'end':
--> 289       self._call_batch_end_hook(mode, batch, logs)
    290     else:
    291       raise ValueError('Unrecognized hook: {}'.format(hook))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in _call_batch_end_hook(self, mode, batch, logs)
    307       batch_time = time.time() - self._batch_start_time
    308 
--> 309     self._call_batch_hook_helper(hook_name, batch, logs)
    310 
    311     if self._check_timing:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in _call_batch_hook_helper(self, hook_name, batch, logs)
    340       hook = getattr(callback, hook_name)
    341       if getattr(callback, '_supports_tf_logs', False):
--> 342         hook(batch, logs)
    343       else:
    344         if numpy_logs is None:  # Only convert once.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in on_train_batch_end(self, batch, logs)
    959 
    960   def on_train_batch_end(self, batch, logs=None):
--> 961     self._batch_update_progbar(batch, logs)
    962 
    963   def on_test_batch_end(self, batch, logs=None):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py in _batch_update_progbar(self, batch, logs)
   1014     if self.verbose == 1:
   1015       # Only block async when verbose = 1.
-> 1016       logs = tf_utils.to_numpy_or_python_type(logs)
   1017       self.progbar.update(self.seen, list(logs.items()), finalize=False)
   1018 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/tf_utils.py in to_numpy_or_python_type(tensors)
    535     return t  # Don't turn ragged or sparse tensors to NumPy.
    536 
--> 537   return nest.map_structure(_to_single_numpy_or_python_type, tensors)
    538 
    539 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py in map_structure(func, *structure, **kwargs)
    633 
    634   return pack_sequence_as(
--> 635       structure[0], [func(*x) for x in entries],
    636       expand_composites=expand_composites)
    637 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/nest.py in <listcomp>(.0)
    633 
    634   return pack_sequence_as(
--> 635       structure[0], [func(*x) for x in entries],
    636       expand_composites=expand_composites)
    637 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/tf_utils.py in _to_single_numpy_or_python_type(t)
    531   def _to_single_numpy_or_python_type(t):
    532     if isinstance(t, ops.Tensor):
--> 533       x = t.numpy()
    534       return x.item() if np.ndim(x) == 0 else x
    535     return t  # Don't turn ragged or sparse tensors to NumPy.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in numpy(self)
   1061     """
   1062     # TODO(slebedev): Consider avoiding a copy for non-CPU or remote tensors.
-> 1063     maybe_arr = self._numpy()  # pylint: disable=protected-access
   1064     return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr
   1065 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1029       return self._numpy_internal()
   1030     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1031       six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
   1032 
   1033   @property

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: 9 root error(s) found.
  (0) Invalid argument: {{function_node __inference_train_function_5549}} Compilation failure: Reshape's input dynamic dimension is decomposed into multiple output dynamic dimensions, but the constraint is ambiguous and XLA can't infer the output dimension %reshape.40 = f32[8,8,2047,128]{3,2,1,0} reshape(f32[<=64,2047,128]{2,1,0} %reshape.39), metadata={op_type="BatchToSpaceND" op_name="dilated_conv1d_1/conv1d_1/conv1d/BatchToSpaceND"}. Constraint: multiple_of: 8, stride: 1
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_4759666286058538557/_4}}]]
	 [[tpu_compile_succeeded_assert/_4759666286058538557/_4/_197]]
  (1) Invalid argument: {{function_node __inference_train_function_5549}} Compilation failure: Reshape's input dynamic dimension is decomposed into multiple output dynamic dimensions, but the constraint is ambiguous and XLA can't infer the output dimension %reshape.40 = f32[8,8,2047,128]{3,2,1,0} reshape(f32[<=64,2047,128]{2,1,0} %reshape.39), metadata={op_type="BatchToSpaceND" op_name="dilated_conv1d_1/conv1d_1/conv1d/BatchToSpaceND"}. Constraint: multiple_of: 8, stride: 1
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_4759666286058538557/_4}}]]
	 [[tpu_compile_succeeded_assert/_4759666286058538557/_4/_157]]
  (2) Invalid argument: {{function_node __inference_train_function_5549}} Compilation failure: Reshape's input dynamic dimension is decomposed into multiple output dynamic dimensions, but the constraint is ambiguous and XLA can't infer the output dimension %reshape.40 = f32[8,8,2047,128]{3,2,1,0} reshape(f32[<=64,2047,128]{2,1,0} %reshape.39), metadata={op_type="BatchToSpaceND" op_name="dilated_conv1d_1/conv1d_1/conv1d/BatchToSpaceND"}. Constraint: multiple_of: 8, stride: 1
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_4759666286058538557/_4}}]]
	 [[tpu_compile_succeeded_assert/_4759666286058538557/_4/_137]]
  (3) Invalid argument: {{function_node __inference_train_function_5549}} Compilation failure: Reshape's input dynamic dimension is decomposed into multiple output dynamic dimensions, but the constraint is ambiguous and XLA can't infer the output dimension %reshape.40 = f32[8,8,2047,128]{3,2,1,0} reshape(f32[<=64,2047,128]{2,1,0} %reshape.39), metadata={op_type="BatchToSpaceND" op_name="dilated_conv1d_1/conv1d_1/conv1d/BatchToSpaceND"}. Constraint: multiple_of: 8, stride: 1
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_4759666286058538557/_4}}]]
	 [[tpu_compile_succeeded_assert/_4759666286058538557/_4/_187]]
  (4) Invalid argument: {{function_node __inference_train_function_5549}} Compilation failure: Reshape's input dynamic dimension is decomposed into multiple output dynamic dimensions, but the constraint is ambiguous and XLA can't infer the output dimension %reshape.40 = f32[8,8,2047,128]{3,2,1,0} reshape(f32[<=64,2047,128]{2,1,0} %reshape.39), metadata={op_type="BatchToSpaceND" op_name="dilated_conv1d_1/conv1d_1/conv1d/BatchToSpaceND"}. Constraint: multiple_of: 8, stride: 1
	TPU compilation failed
	 [[{{ ... [truncated]
```

</details>

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.3 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/09a9efcf14b3111df6a41add407b2a4d/untitled408.ipynb).However i am seeing different error message in TF nightly versions(`2.4.0-dev20200930`).Please find the gist [here.](https://colab.research.google.com/gist/ravikyram/9e5e9c9a9d8f5835890ec4b14fda32f5/untitled409.ipynb).Thanks!

**Comment by saeta** [comment]
Removing assignment as I'm no longer working on Python TensorFlow. Sorry!

**Comment by yunxing** [comment]
BatchToSpaceND is not longer called on TPU. I think we should fix this gist reported by @ravikyram first: https://colab.research.google.com/gist/ravikyram/9e5e9c9a9d8f5835890ec4b14fda32f5/untitled409.ipynb Is there anyone from TF team can help?

**Comment by jhseu** [comment]
That error is most likely due to a version mismatch between the TF client and the backend. Let's check back in after the next TensorFlow release when it's on Cloud TPUs.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/adccbe43b6b16976bab8a00287641888/43690.ipynb). Thanks!

**Comment by evanatyourservice** [comment]
I'm getting this error right now with 2.5.0 and functional API

```
out = layers.Conv1D(dil_channels, 2, padding="causal", dilation_rate=d, use_bias=False, kernel_initializer=initializer)(x)
```

How is this error so old please fix... I moved back to TF to use TPUs but it's 90% errors and two weeks of wasted time, I'm going back to pytorch. Sorry for the complaining, but TF with TPU has been impossible to work with in all aspects and I'm at my wits' end when after finally dropping down to the functional API, something you'd think should be simple and work well, it turns out you can't use dilation != 1 in conv layers. It's 2021. What's your answer, move to JAX? JAX tells me to train a model in tensorflow in order to save it for production lol... how does deepmind get anything done?

**Comment by rxsang** [comment]
Hi @sachinprasadhs, the problem should have been fixed by @yunxing. Could you try TF nightly?

**Comment by Saduf2019** [comment]
@rxsang 
I am able to replicate the issue on tf [2.6 as well], please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e5d80e3f840a4231194db960c92b14b0/untitled627.ipynb)

**Comment by i7p9h9** [comment]
Any updates here? Conv1D with delation still not working. I tryed tf2.6 and tf-nightly [2.7.0.dev20210831-cp37-cp37m-manylinux2010_x86_64]

**Comment by i7p9h9** [comment]
> @rxsang
> I am able to replicate the issue on tf [2.6 as well], please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e5d80e3f840a4231194db960c92b14b0/untitled627.ipynb)

Hello, I found the temporary solution:
You should to set drop_remainder to "True" to fix the size of batch.

> `dataset = tf.data.Dataset.from_tensor_slices(data).shuffle(buffer_size=batch_size).repeat().batch(batch_size, **drop_remainder=True**)`

**Comment by mohantym** [comment]
Hi @Hiroshiba !
We are checking to see whether you still need help in this issue . Did you check with above [suggestion](https://github.com/tensorflow/tensorflow/issues/43690#issuecomment-911569137) yet? Thanks!

**Comment by Hiroshiba** [comment]
I don't know, but let's close it!
