### ISSUE TITLE
Go installation error

### ISSUE THREAD

**Issue by fedyfausto** [tensorflow/tensorflow#43847]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 32
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.3.0
- Python version:3.8.5
- Installed using virtualenv? pip? conda?: pip
- CUDA/cuDNN version: 11.0
- GPU model and memory: 1660 gtx super (6GB)
- GO version: 1.15.2

Hello i'm trying to install the tensorflow go version to build a little application. So i installed the C library (2.3.0 version tested with classic hello.c example) and after that i run the following command:

`go get github.com/tensorflow/tensorflow/tensorflow/go`

but after this one i get this error:

```bash
go: found github.com/tensorflow/tensorflow/tensorflow/go in github.com/tensorflow/tensorflow v2.3.1+incompatible
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
../../../../golang/gopath/pkg/mod/github.com/tensorflow/tensorflow@v2.3.1+incompatible/tensorflow/go/saved_model.go:25:2: module github.com/tensorflow/tensorflow@latest found (v2.3.1+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto
```

could tou help me?

Go ENVS:
```bash
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/fedyfausto/.cache/go-build"
GOENV="/home/fedyfausto/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/fedyfausto/golang/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/fedyfausto/golang/gopath"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/fedyfausto/golang/latest/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/fedyfausto/golang/latest/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/fedyfausto/Lavoro/Project/go_predictor_2/project_name/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build398631669=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by Saduf2019** [comment]
@fedyfausto 
Please refer to this issue with same error and let us know :#41808 #34580 #39307

**Comment by fedyfausto** [comment]
The issue is the same but seems does not be resolved yet

**Comment by fedyfausto** [comment]
i tryied to re-install all but seems some files miss (the file `for_core_protos_go_proto`)

**Comment by fedyfausto** [comment]
The C library seems work:
```bash
[fedyfausto@desktop-fisso-fedyfausto-fedora Scrivania]$ gcc hello_tf.c -ltensorflow -o hello_tf
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 851 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 1959 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2329 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2517 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2732 (>= sh_info of 2)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2733 (>= sh_info of 2)
[fedyfausto@desktop-fisso-fedyfausto-fedora Scrivania]$ ./hello_tf 
Hello from TensorFlow C library version 2.3.0
```

**Comment by Saduf2019** [comment]
> The C library seems work:
> 
> ```shell
> [fedyfausto@desktop-fisso-fedyfausto-fedora Scrivania]$ gcc hello_tf.c -ltensorflow -o hello_tf
> /usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 851 (>= sh_info of 2)
> /usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 1959 (>= sh_info of 2)
> /usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2329 (>= sh_info of 2)
> /usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2517 (>= sh_info of 2)
> /usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2732 (>= sh_info of 2)
> /usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2733 (>= sh_info of 2)
> [fedyfausto@desktop-fisso-fedyfausto-fedora Scrivania]$ ./hello_tf 
> Hello from TensorFlow C library version 2.3.0
> ```

Do you mean the issue is resolved.

**Comment by ddumbugie** [comment]
@Saduf2019 I've met same problem, too.

The C library of v2.3.0 works well.

Go version of tensorflow@v2.3.0 or v2.3.1 does not work in **go mod** environment.

**Comment by ololosha228** [comment]
Same problem.

OS ubuntu/amd64
Tensorflow v2.3.1
Golang v1.15.1

This issue is **STILL NOT SOLVED**. All of us can't say that this trouble is fixed until [this guide](https://www.tensorflow.org/install/lang_go) will be done step by step without any errors or warnings.

**Comment by ololosha228** [comment]
@advaitjain @gunan @hawkinsp @qlzh727 anyone?

**Comment by gunan** [comment]
@jhseu may be able to help, I do not think anyone else investigated go packages.

**Comment by ololosha228** [comment]
fuck, i accidentally delete /usr/local cause i tried to solve this issue by the hands, lol :laughing: :laughing: :laughing:. Thanks nvidia and tensorflow developers to create simple deb packages that are "just works"

**Comment by shravanshetty1** [comment]
Having the same issue as op

**Comment by kep-w** [comment]
Having the same issue, after go generate github.com/tensorflow/tensorflow/tensorflow/go/op
cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
	${GOPATH}/src/github.com/tensorflow/tensorflow/tensorflow/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (vendor tree)
	/usr/local/Cellar/go/1.15/libexec/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
	${GOPATH}/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
In the core dir only two dirs:
![Uploading 图片.png…]()

**Comment by shravanshetty1** [comment]
https://github.com/owulveryck/onnx-go i found this - if you want to use a machine learning model, get its onnx version and you can use the linked repo. Its only for using models, you cant train them. This helped me so hope it helps someone who reads this.

**Comment by ololosha228** [comment]
@fedyfausto @Saduf2019 @gowthamkpr  have you found any solutions? 

Perhaps, we need to create custom bindings for tensorflow, cuz usually google fixing their bugs to much time.

**Comment by fedyfausto** [comment]
After a lot of try and errors i finally found a little solution:
I installed the last version of TensorFlow C library (2.30.) from BINARY. After that i installed the GO VERSION of tensorflow 2.1.0 and it seems work, so there is some bug in 2.3.0 of go version (anyway the go runs 2.3.0 c libray so it is fine).

Now i'm facing to another problem, how could i compile a single solution within tensorflow library to distribuite the final solution?

**Comment by ololosha228** [comment]
@fedyfausto i could cooperate with you to fix this problem (cuz i realy need working ml framework on go), so if yo want, text me on email or telegram, links in my profile.

**Comment by fedyfausto** [comment]
I will contact you! (Telegram maybe is the perfect solution @fedyfausto)

Dott. Federico Fausto Santoro





Il giorno 20 ott 2020, alle ore 15:58, Richard Cooper <notifications@github.com> ha scritto:

﻿

@fedyfausto<https://github.com/fedyfausto> i could cooperate with you to fix this problem (cuz i realy need working ml framework on go), so if yo want, text me on email or telegram, links in my profile.

**Comment by kep-w** [comment]
I solved this problem by changing the TensorFlow version to 1.13.
Download the corresponding version of TensorFlow, and then go generate $GOPATH/src/......
At the same time, you need to modify the tensorflow version of require in go.mod
`require github.com/tensorflow/tensorflow v1.13.2`

**Comment by ololosha228** [comment]
@kep-w all participants here are already decided that tensorflow 1.13 is works well, **but latest version is v2.3.1!!!** Also, 2.* versions are mentioned in official guide, so this is not a solution actually.

**Comment by wamuir** [comment]
@fedyfausto @ololosha228 @kep-w @shravanshetty1 

I've placed a working Dockerfile for Go 1.15 and TensorFlow 2.3.1 at https://github.com/wamuir/golang-tf . I hope this helps.

**Comment by ololosha228** [comment]
@wamuir thanks a lot! i'll try to experiment with your image, and leave a feedback in your repo (or here, idk)

**Comment by kevin2018pg** [comment]
Having the same problem，

**Comment by Saduf2019** [comment]
@fedyfausto 
Do you still face the issue, could you please try with the latest tf version and update us.

**Comment by ptxmac** [comment]
Yes this is still a problem. tensorflow/go can only be used with bazel, or by building a localversion and putting it in vendor.

For anyone else struck here, @galeone is maintaining a fork with the propobuf files compiled: https://github.com/galeone/tensorflow (He also have a wrapper for making it even easier to use tensorflow in go: https://github.com/galeone/tfgo )

**Comment by quenbyako** [comment]
@Saduf2019 i copy that, tried to rerun "getting started" guide to install and use tensorflow in go, and still lots a lot of problems


To be honest, i prefer to recommend any user who read this comment, use galeone packages cause... Well, they work, at least...

**Comment by wamuir** [comment]
Here's a summary for anyone who wants this summarized:  **you cannot use `go get` to obtain a functional copy of `github.com/tensorflow/tensorflow/tensorflow/go`**.  This is because the package relies on compiled protocol buffers, but compiled protobufs cannot be checked into this git repo (see #44655).  Previously, it was fairly straightforward to obtain a working installation by cloning the Tensorflow repo into `${GOPATH}/src` and then using `go generate`  to compile the buffers, but recent Go module changes and the deprecation of GOPATH have all but made this approach impossible (despite what the [Install Guide](https://github.com/tensorflow/tensorflow/blob/3691bc286f4ac0aad8c1cf611b692a22e7eef22a/tensorflow/go/README.md) in this repo would have you believe!).

Things that flat out won't work:
1. Using `go get github.com/tensorflow/tensorflow/tensorflow/go`
2. Following the [current installation guide in this repo](https://github.com/tensorflow/tensorflow/blob/3691bc286f4ac0aad8c1cf611b692a22e7eef22a/tensorflow/go/README.md), which needs an update

You can still use tensorflow/go.  A few solutions that may work for you:
1. Clone the Tensorflow repo, generate the protocol buffers locally and then use go mod's replace directive: instructions are in SIG Build's [Golang Install Guide](https://github.com/tensorflow/build/blob/master/golang_install_guide/README.md) 
2. Switch to a fork that includes the generated protocol buffers, such as https://github.com/galeone/tensorflow from @galeone
3. Use Docker images that have Go, the TF shared libs and tensorflow/go installed, such as https://github.com/wamuir/golang-tf
4. Soon, hopefully, build with Bazel; a PR is at #50934
