### ISSUE TITLE
ByteBuffer is not a valid flatbuffer model

### ISSUE THREAD

**Issue by ssuwal** [tensorflow/tensorflow#44472]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): *Ubuntu 18.04.5 LTS [Google Colab]*
- TensorFlow installed from (source or binary): *nightly*
- TensorFlow version (or github SHA if from source): *2.5.0-dev20201029*

**Command used to run the converter or code if you’re using the Python API**
I am trying to covert custom efficientdet d2 object detection model that I trained for Android.
I successfully trained it and also was able to convert it to tflite by using various github issue threads.
I followed this [colab file](https://colab.research.google.com/gist/ravikyram/c2832e117a14c172c75146275381a8fc/untitled282.ipynb#scrollTo=U8oeT58f3qmr) to convert and was able to convert also used `tf_convert` and was able to convert

```bash
# did ran this after running export_tflite_graph_tf2.py
tflite_convert --saved_model_dir /content/model_nightly/saved_model --output_file /content/tflite-conversion.tflite
```
and also
```python
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model('/content/model_nightly/saved_model/',signature_keys=['serving_default'])
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

with tf.io.gfile.GFile('/content/model.tflite', 'wb') as f:
  f.write(tflite_model)

```

**The output from the converter invocation**
**from command 1**
```
W1030 22:40:38.686931 139654416934784 function_deserialization.py:416] Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
W1030 22:40:38.687373 139654416934784 function_deserialization.py:416] Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
W1030 22:40:38.687821 139654416934784 function_deserialization.py:416] Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
2020-10-30 22:40:56.738889: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored output_format.
2020-10-30 22:40:56.738961: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:319] Ignored drop_control_dependency.
2020-10-30 22:40:56.738973: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:325] Ignored change_concat_input_ranges.
2020-10-30 22:40:56.740050: I tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: /content/model_graph_100K_nightly/saved_model
2020-10-30 22:40:57.034144: I tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
2020-10-30 22:40:57.034227: I tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: /content/model_graph_100K_nightly/saved_model
2020-10-30 22:40:57.034311: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-10-30 22:40:57.901184: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2020-10-30 22:40:58.067181: I tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
2020-10-30 22:40:58.215865: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2300000000 Hz
2020-10-30 22:41:00.181931: I tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: /content/model_graph_100K_nightly/saved_model
2020-10-30 22:41:01.017615: I tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 4277564 microseconds.
2020-10-30 22:41:04.164837: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:194] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2020-10-30 22:41:06.474280: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Exception ignored in: <bound method Buckets.__del__ of <tensorflow.python.eager.monitoring.ExponentialBuckets object at 0x7f037e83e798>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/monitoring.py", line 407, in __del__
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'
```

**from command 2**
```
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
WARNING:absl:Importing a function (__inference_EfficientDet-D2_layer_call_and_return_conditional_losses_131625) with ops with custom gradients. Will likely fail if a gradient is requested.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
- While using it in the android application from the repository [here](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/README.md), I get the following error.
```
E/tensorflow: CameraActivity: Exception!
    java.lang.RuntimeException: java.lang.IllegalArgumentException: ByteBuffer is not a valid flatbuffer model
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:153)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:99)
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:200)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: ByteBuffer is not a valid flatbuffer model
        at org.tensorflow.lite.NativeInterpreterWrapper.createModelWithBuffer(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:62)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:277)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.create(TFLiteObjectDetectionAPIModel.java:148)
        at org.tensorflow.lite.examples.detection.DetectorActivity.onPreviewSizeChosen(DetectorActivity.java:99) 
        at org.tensorflow.lite.examples.detection.CameraActivity.onPreviewFrame(CameraActivity.java:200) 
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1221) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```
I am trying to do this for my college project.

**Comment by lintian06** [comment]
Hi Santosh,

You used SELECT_TF_OPS in the conversion, so in the app, it is necessary to add the dependency to gradle as well. Please check the instructions [here](https://www.tensorflow.org/lite/guide/ops_select). 

```
dependencies {
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    // This dependency adds the necessary TF op support.
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
}
```

BTW, only for [EfficientNet-**Lite** version](https://tfhub.dev/tensorflow/lite-model/efficientnet/lite0/fp32/2), they do not require SELECT_TF_OPS.

**Comment by MCR-Student** [comment]
I also have the dependency added and am getting this error.

**Comment by lintian06** [comment]
Hi Santosh and MCR,

Looks like there were failures of EfficientDet model in conversion, and then the interpreter cannot load the model file correctly.

I am not sure about the detail of EfficientDet you used. Can you provide more information? BTW, is there any EfficientDet lite model that you can find from the repo?

Thanks!

**Comment by Saduf2019** [comment]
@ssuwal 
Please provide complete code or if possible share a colab gist with the issue faced.

**Comment by ssuwal** [comment]
Sorry for delayed reply here. To give more info on what I am doing is, I have trained object detection model with Efficient Det D2 from Model Zoo. The model seems to be exported successfully. Only TFLite export doesn't work on current stable version so I tried beta version as someone was successful in doing that, I have linked the file in the main issue.
I have tried different ways of exporting as mentioned above and here is the link to the gist.
[Gist TFlite Export](https://colab.research.google.com/gist/ssuwal/e12af11e3570a0228d71acbdc3b6ad42/tf-nightly-tflite.ipynb)

Also, linking the page in example android tflite object detection example where this is consumed
[Function Loading TFLite](https://github.com/tensorflow/examples/blob/47307e16aee169aca8265032bf7ab420b715b808/lite/examples/object_detection/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L94)

Let me know if you require more info.

**Comment by karimnosseir** [comment]
I don't think this is related to the converter.
I think this is similar to 
https://github.com/tensorflow/tensorflow/issues/44192
which should be fixed already

**Comment by ssuwal** [comment]
@karimnosseir 
I am still having the same problem here is the github gist, please ignore the last code box.
[Github Gist](https://colab.research.google.com/gist/ssuwal/0b48560597b305860d52393c00df8c86/tf-nightly-tflite.ipynb)
I did pull latest nightly available
- TensorFlow version (or github SHA if from source): 2.5.0-dev20201203

**Comment by karimnosseir** [comment]
@ssuwal That doesn't look the same problem earlier. I see
"
failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Size {device = ""}
"

TFLite doesn't support tf.Size op natively, you can use TF SELECT which enables fallback to TF for unsupported Op.
See the guide
https://www.tensorflow.org/lite/guide/ops_select

**Comment by ssuwal** [comment]
@karimnosseir 
Thanks for the quick reply here,
I was never able to get that last code block in the gist get to work, if you see the previous gist, it also fails with same error.
sorry if this mislead the issue.
My main concern is still the same, I have a custom model trained and able to convert to tflite using current nightly version, however the android sample application give the Bytebuffer is not valid flatbuffer error. I hope this clear things up.

Is there a way to check what is wrong with the tflite, or why is the bytebuffer not a valid flatbuffer?

**Comment by karimnosseir** [comment]
@ssuwal I see, the gist confused me. Can you please paste the Java sample code ? Also, can you run it in python for example or fails also ?

**Comment by ssuwal** [comment]
```java
  /** Memory-map the model file in Assets. */
  private static MappedByteBuffer loadModelFile(AssetManager assets, String modelFilename)
      throws IOException {
    AssetFileDescriptor fileDescriptor = assets.openFd(modelFilename);
    FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
    FileChannel fileChannel = inputStream.getChannel();
    long startOffset = fileDescriptor.getStartOffset();
    long declaredLength = fileDescriptor.getDeclaredLength();
    return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
  }
```
this is the code in the sample example, I haven't tried to load tflite in python, I will try that post update as soon as I can.
Also here is the file with the java code [Load Model](https://github.com/tensorflow/examples/blob/47307e16aee169aca8265032bf7ab420b715b808/lite/examples/object_detection/android/lib_interpreter/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L94)

**Comment by ssuwal** [comment]
```python
# tf.__version__ = 2.5.0-dev20201028
# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="./tflite-models/noops-model.tflite")

# interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.resize_tensor_input(input_details[0]['index'], (1, 1008, 756, 3))
interpreter.allocate_tensors()

img = cv2.imread('./assets/dataset_test_old/JPEGImages/IMG_0644.jpg')
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# img_rgb = cv2.resize(img_rgb, (300, 300), cv2.INTER_AREA)
img_rgb = img_rgb.reshape([1, 1008, 756, 3])
interpreter.set_tensor(input_details[0]['index'], img_rgb)
interpreter.invoke()
de_boxes = interpreter.get_tensor(output_details[0]['index'])[0]
det_classes = interpreter.get_tensor(output_details[1]['index'])[0]
det_scores = interpreter.get_tensor(output_details[2]['index'])[0]
num_det = interpreter.get_tensor(output_details[3]['index'])[0]
```
I loaded the tflite model using above code and worked without any errors. Let me know if you need anything else from me.

**Comment by ssuwal** [comment]
This issue has be stagnant for 3 months now, any feed back or updates would be great.
Let me know if you anything is needed from my side to resolve this issue or assist in any way.

**Comment by iyaselerehoboth** [comment]
Am also having this issue as well

**Comment by xiliangt** [comment]
Am also having this issue as well

**Comment by StudentGGG** [comment]
It seems that I get that error only when I load the module on a separate thread and only for some devices.

**Comment by mohantym** [comment]
Hi @ssuwal !
We are checking to see whether you still need help in this issue . Could you save the model as mentioned in this [comment ](https://github.com/tensorflow/tensorflow/issues/40166#issuecomment-854686488)before the lite conversion and let us know.
Thank you!
