### ISSUE TITLE
Errors when loading a model having keras.Lambda

### ISSUE THREAD

**Issue by rpytel1** [tensorflow/tensorflow#45180]
**System information**
- Linux Ubuntu 16.04
- TensorFlow 2.3.0
- Python version: 3.6

## Problem description
While creating function for model creation using Functional API I noticed an interesting behaviour on how the graph is saved and loaded when you use keras.layers.Lambda as one of the layers. 

Currently, tf2 makes it impossible to change batch_size within the model definition, so let's say you have multiple images and you want to make a decision based on these images from different points. 

E.g. You have 10 different shots from the camera (always the same point of view for corresponding shots) and you want to decide whether a phone is damaged. 

### Current behaviour
When creating model within the scope of notebook within it is saved it is possible to save model (`keras.save_model()`) and load it (`keras.load_model()`) in a different notebook. 

When extracting a function to another file (let's say model.py) and performing the same scope: create->train->`keras.save_model()` and then loading the model in a different notebook, model throws errors. 

### Expected behaviour 
Working saving and loading for a model defined in a different location. I also tried that with model subclassing and I am almost certain that it also does not work. 

### Reproduced problem with a proposed solution
https://colab.research.google.com/drive/16LfnXVFHs9jNTOm0FUGjjnwAUczmOYdC?usp=sharing

## Proposed solution/ My workaround
From what I found the issue occurs partly because of keras.layers.Lambda is saving bytecode of the inner function. As the function is simple Python lambda not using any 3rd party functions it is only needed to focus on serialization and override module value of the function: 
```python
def _serialize_function_to_config(self, inputs, allow_raw=False):
    if isinstance(inputs, python_types.LambdaType):
      output = generic_utils.func_dump(inputs)
      output_type = 'lambda'
      module = inputs.__module__
    elif callable(inputs):
      output = inputs.__name__
      output_type = 'function'
      module = inputs.__module__
    elif allow_raw:
      output = inputs
      output_type = 'raw'
      module = None
    else:
      raise ValueError(
          'Invalid input for serialization, type: %s ' % type(inputs))

    return output, output_type, module
```

by subclassing:
```python
class SafeSaveLambda(keras.layers.Lambda):
    def _serialize_function_to_config(self, inputs, allow_raw=False):
        output, output_type, module = super()._serialize_function_to_config(inputs, allow_raw)
        
        return output, output_type, "__main__"
```
and using SafeSaveLambda in place of ``keras.layers.Lambda``. Solution and investigation are available in GoogleColab.

**Comment by Saduf2019** [comment]
@rpytel1 
Unable to access the colab shared, please share colab with access and issue reported.

**Comment by rpytel1** [comment]
@Saduf2019 
I have changed permissions and checked with incognito if I may access the notebook and it worked.

**Comment by Saduf2019** [comment]
I am able to replicate this on [tf 2.4](https://colab.research.google.com/gist/Saduf2019/f1c124e221c876ea2c6a19147514aaca/untitled483.ipynb) and as reported on [tf 2.3](https://colab.research.google.com/gist/Saduf2019/b6ae6c4127e0013c0a4358010d14da91/untitled483.ipynb) and [nightly](https://colab.research.google.com/gist/Saduf2019/d1508e252364618225b895700960e74b/untitled483.ipynb)

**Comment by rpytel1** [comment]
@ymodak any update on a suggested fix or better workaround?

**Comment by Saduf2019** [comment]
@rpytel1 
This is fixed on latest tf, can you refer to [this gist](https://colab.research.google.com/gist/Saduf2019/2c47e0eddc42065670e63ceb3536fa78/untitled594.ipynb) and update.

**Comment by rpytel1** [comment]
Hi all, 
Sorry for the late response. The problem remains in the newest tf-nightly. @Saduf2019, your collab has mistakes as it is only restarting Keras session which is only removing TensorFlow objects and clears the GPU memory, while all python imports or custom defined functions are still in the memory. Here it is crucial to restart the runtime machine (in Jupyter it is called restarting kernel) to simulate few notebooks in one. The problem occurs when we do the following: 
1. We create a model using Functional API in one file (let's say ``create_model.py``) in one notebook (let's say ``train_model.ipynb``  and train it and save it.
2. We load a model in a different notebook (let's say in ``test_model..ipynb``).

Please find an example with code here: 
https://colab.research.google.com/drive/1B2hETw6NJN-F51F3taUIKjdSnRPJbQRU?usp=sharing

**Comment by mohantym** [comment]
Hi @rpytel1 ! 
We are checking to see whether you still need help in this issue . Have you tried this issue in latest version TF 2.7 yet? Thanks!
