### ISSUE TITLE
"error: 'tf.Conv2D' op is neither a custom op nor a flex op" when converting a basic MNIST network

### ISSUE THREAD

**Issue by CPA872** [tensorflow/tensorflow#45252]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux, Ubuntu 20.04
- TensorFlow installed from (source or binary): binary from pip3 install tensorflow
- TensorFlow version (or github SHA if from source): 2.3.1 and tf-nightly 2.5.0-dev20201128

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
import tensorflow as tf
from tensorflow import keras

print(tf.__version__)

model = keras.models.load_model("mnist.h5")
# tf.saved_model.save(model, "new_mnist")

converter = tf.lite.TFLiteConverter.from_keras_model(model)

# converter = tf.lite.TFLiteConverter.from_saved_model("mnist.h5")
converter.optimizations = [tf.lite.Optimize.DEFAULT]

num_calibration_steps = 10

def representative_dataset_gen():
  for _ in range(num_calibration_steps):
    # Get sample input data as a numpy array in a method of your choosing.
    yield [input]
    
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()

open("quantized.tflite", "wb").write(tflite_quant_model)
# Copy and paste here the exact command
```

**The output from the converter invocation**

```
# Copy and paste the output here.   (Full log is attached at the end)
cx872@T460p:~/Desktop/temp$ python3 quantize.py 
2020-11-28 15:28:02.571351: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-11-28 15:28:02.571375: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-11-28 15:28:03.736827: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-11-28 15:28:03.736848: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-11-28 15:28:03.736865: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (T460p): /proc/driver/nvidia/version does not exist
2020-11-28 15:28:03.737083: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-28 15:28:03.762679: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2599990000 Hz
2020-11-28 15:28:03.763178: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4878980 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-28 15:28:03.763205: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
2020-11-28 15:28:03.973359: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From /home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/tracking.py:111: Layer.updates (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
2020-11-28 15:28:04.369274: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2020-11-28 15:28:04.369473: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-11-28 15:28:04.374144: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: graph_to_optimize
2020-11-28 15:28:04.374171: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0.003ms.
2020-11-28 15:28:04.374181: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 0ms.
2020-11-28 15:28:04.398758: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
2020-11-28 15:28:04.398813: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
loc(callsite("sequential/conv2d/Conv2D"("/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py":1073:0) at callsite("/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py":1167:0 at callsite("/home/cx872/.local/lib/python3.8/site-packages/tensorflow/lite/python/lite.py":804:0 at "quantize.py":23:0)))): error: 'tf.Conv2D' op is neither a custom op nor a flex op
loc(callsite("sequential/conv2d_1/Conv2D"("/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py":1073:0) at callsite("/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py":1167:0 at callsite("/home/cx872/.local/lib/python3.8/site-packages/tensorflow/lite/python/lite.py":804:0 at "quantize.py":23:0)))): error: 'tf.Conv2D' op is neither a custom op nor a flex op
loc(callsite("sequential/conv2d_2/Conv2D"("/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py":1073:0) at callsite("/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py":1167:0 at callsite("/home/cx872/.local/lib/python3.8/site-packages/tensorflow/lite/python/lite.py":804:0 at "quantize.py":23:0)))): error: 'tf.Conv2D' op is neither a custom op nor a flex op
error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Conv2D {data_format = "NCHW", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
Traceback (most recent call last):
  File "/home/cx872/.local/lib/python3.8/site-packages/tensorflow/lite/python/convert.py", line 196, in toco_convert_protos
    model_str = wrap_toco.wrapped_toco_convert(model_flags_str,
  File "/home/cx872/.local/lib/python3.8/site-packages/tensorflow/lite/python/wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: /home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:1073:0: error: 'tf.Conv2D' op is neither a custom op nor a flex op
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:1167:0: note: called from
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/lite/python/lite.py:804:0: note: called from
quantize.py:23:0: note: called from
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:1073:0: note: see current operation: %0 = "tf.Conv2D"(%arg0, %cst) {data_format = "NCHW", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true} : (tensor<?x1x28x28xf32>, tensor<3x3x1x4xf32>) -> tensor<?x4x26x26xf32>
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:1073:0: error: 'tf.Conv2D' op is neither a custom op nor a flex op
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:1167:0: note: called from
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/lite/python/lite.py:804:0: note: called from
quantize.py:23:0: note: called from
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:1073:0: note: see current operation: %2 = "tf.Conv2D"(%1, %cst_0) {data_format = "NCHW", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true} : (tensor<?x4x26x26xf32>, tensor<3x3x4x4xf32>) -> tensor<?x4x24x24xf32>
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:1073:0: error: 'tf.Conv2D' op is neither a custom op nor a flex op
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:1167:0: note: called from
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/lite/python/lite.py:804:0: note: called from
quantize.py:23:0: note: called from
/home/cx872/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py:1073:0: note: see current operation: %4 = "tf.Conv2D"(%3, %cst_1) {data_format = "NCHW", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true} : (tensor<?x4x24x24xf32>, tensor<3x3x4x4xf32>) -> tensor<?x4x22x22xf32>
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
	tf.Conv2D {data_format = "NCHW", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true}
<unknown>:0: note: see current operation: "func"() ( {
^bb0(%arg0: tensor<?x1x28x28xf32>):  // no predecessors
  %cst = "std.constant"() {value = dense<[[[[0.0649565831, -0.0746282786, 0.162961558, 0.0248589013]], [[-0.200302526, -0.296956897, -0.191993952, 0.220391616]], [[-0.239433467, 0.189716026, -0.311748624, 0.0287476946]]], [[[0.161856413, 0.14310281, 0.234080926, 0.183344632]], [[-0.0514137745, -0.209035754, -0.103884049, 0.158034727]], [[0.193658769, -0.0461433418, 0.327664047, -0.0481641293]]], [[[0.0117518231, 3.49453388E-4, -0.232930154, -0.24110195]], [[0.134880558, 0.145225272, 0.0606381223, 0.157407314]], [[-0.0305803325, -0.0580686741, -0.210291281, -1.786370e-01]]]]> : tensor<3x3x1x4xf32>} : () -> tensor<3x3x1x4xf32>
  %cst_0 = "std.constant"() {value = dense<"0x246BA8BCE77820BE3ED7853ED4B554BD4EC87D3E204B0D3D6F2A883E3EE48C3D16D285BEF12B14BD519BEABDEF5E0DBD338DBCBDE90A0E3E999006BE4312993D9BFC22BDB9C0BD3D29AD97BEF97BE53D66BB98BD88E1783E8A50393EBBA648BE7B81A13CB9D46CBEB74C5B3E93CAAEBD04965DBE4FBEAD3D8279103DC15460BD2E503A3C867E10BE45275ABEEA3303BE1AA21A3E8AB858BE91E1D93DE4B185BCA5ED8DBEBB99A83D623B6DBDDB1A7B3C4A93653DDFC1013E75D25CBE934A6CBC6E48133E83671EBE5BF1013D6DCF8CBD844862BEE79AA13EC8806BBE06A623BE02164D3B2A95E43DD7E6843C49857D3EF202B2BD7873B7BE068EB2BD06E264BDBB6B243DEA4AA5BD28B1803EDF99AE3DAD55A7BDA1BC17BEDC55933EC1C3CDBD55DFF23DBCD6DDBD3412E6BDA3A471BDB4EAAFBD06B582BDC60CB0BE1FDEB43D5CCF4BBC2300523E7E86803E8969ED3D718C25BE6094373E555D6A3E2AE034BD7E7E2A3D92E3CABD188D95BECB4FCF3C0CEE2EBE91CAA9BE085C8F3ED8B81BBEBE85913E95A4B4BD5937E4BD284C333E4C1E5BBDAD9A7ABC3D2425BD6B0DE33D2E251DBE49AC923E785F903DD0E247BD4639033E626897BEECE708BC6D803A3ED3F9093E700C48BE938BC2BDB65061BDFEC42C3E53EB353BA75E0F3E39749E3C3C3F9E3D61CD243EB8688ABE0724C73D818E9BBC1366A5BEB0D903BEA71BB13B918C323C49E4353E6FABF33D871B743EDDEF0BBCDA56E9BC1629603D92B76A3EC6CEFABD2092EEBDB0629DBC1AE468BEED54E13DFEEE2CBDCAB957BE37C0FFBC"> : tensor<3x3x4x4xf32>} : () -> tensor<3x3x4x4xf32>
  %cst_1 = "std.constant"() {value = dense<"0x6C8307BED9C6833D1EF6B9BE24D236BE24CCC8BD350DB33D1CD3A53DC392D2BD6B81AA3DF53DBCBD19550E3DC69422BC1F9686BE743FF1BC581808BE723E15BD5917E9BDB12A683C0FEEAFBEC192C4BBA881F3BCB8FF7FBE74FA063E8FFBE7BD5727AD3C012EDFBE82FB303D7E64923D391B49BE569BA7BD6C4FB1BDCC09BE3C4488993D078E03BFA8A5F43C1F65BFBDBE8C263E438998BD551AF53D6E4FBABD398069BE90D9863DA99E03BF22FE0D3C8984E9BD921D54BE1FE1343EAF04363EF79618BD3975C9BD6FE32EBE099BA2BEF717C3BD77AF16BE0810E4BD9FBDE5BCB3BDB1BDB24AF23A19009BBE4EC58D3E0AD125BECADB273E33D91F3E56C489BDD87DB73D48D55BBEA7089DBE13B1C4BC50990E3D75A0173EA137A83EF18756BEFCA212BE504710BE9968C8BE5E858ABEE50F4EBD08EA0DBDE8F803BE4D9017BEE151E5BC80E61E3E5E19BCBD77EF1CBE1DA7B13DC209A8BD72FDDFBD71A0D7BD4C14103ECEE162BE4B05783DBEF02A3D8B49C1BC460EA4BC80C977BE09F09CBD62754C3DF12585BD4708243EC9C5543EB1952FBEE2E7B2BECE570A3EDDE9DE3D28C5AA3D8B329B3D7C8462BCE647E43D5FE10B3E5F47DC3D2DA6773DDFE493BE1111793C85ADF0BD56A055BC6D6D913D50A694BC3B4702BE4698373D02B983BE7DEDD9BC9F4012BEC26F103D53000F3E51B704BEFAE88F3D9136783C4683EEBD26141E3E23F0013DF5C1E0BD91A232BDA4EC14BCDBFA8ABEC0E506BE50223BBEF810323E559D983C9E8F573EB53FB3BE5C156A3D2D64BC3D631959BD046EB13D"> : tensor<3x3x4x4xf32>} : () -> tensor<3x3x4x4xf32>
  %cst_2 = "std.constant"() {value = dense<[0.0515903942, 0.674950719, 1.961430e-03, -0.249269262, 0.172605708, -0.0643907487, 0.0460773893, 0.245695099, -0.507323146, -0.116961144]> : tensor<10xf32>} : () -> tensor<10xf32>
  %cst_3 = "std.constant"() {value = dense<[-1, 1936]> : tensor<2xi32>} : () -> tensor<2xi32>
  %cst_4 = "std.constant"() {value = dense<"0x4BA6EFBC1D3EE5BCC63F83BC0A188BBD0E055C3D1BC2853B9C074EBCF42E07BD2F21193DB9AC443D842D453D27C931BC3EDF7E3D58647F3D33F419BDF336A63D6511E63C8A4E593D01ACBB3C3607B93D2C5B2BBD52099F3C6844D93D334FEBBCD3A71D3DF321333CF847A43C5CC9863CC5B8FC3CE8B9653CD0006BBC0BA2D03CA7814A3CDCACAB3C91B9873DFCBD93BC394EC23DB9AC02BDCD5F703BAA1EEBBCE1F35A3D40ACAF3D2EDF993DA0AF223D27E1A0BD18978E3DC88BCF3B9269B73D397B443DF363E63C134BB83C624E9BBC493C92BD8EA6E3BC230A43BD08C75EBC2EBF87BD5FB7903C25E0D93C1431D33D96E6823D3F07E83D73E0A43BB59BED3D32C0D43D10AAB73DAB01DDBC39D1EB3D717AA4BB3002893DBC2E5D3C461C913B966E8ABD9F85DDBC99668D3D0A152B3DE5E0093D6629A43D3F39FBBC6045763D03C3723DB816AE3CAD5E65BDD2AC60BBBAE709BDFD1E31BB4AA3B33DB502793D97D63E3ECC9A143D20088E3D7ABBB5BDFF0D02BD865AF93C35EEC53C473F36BDBA79693DA2FC773B1241D33C4E49BC3C859896BDA1D8E7BCCD9B153C1EE20EBCB502FC3CE7C3CABD76413D3B9E936B3DCC64E9BCF5A9EC3D096D963CF535E83D9945CFBCC7DB06BED9F0D1BD033F08BE3EFCA3BD05044CBD288E693D574BE6BD56C076BDA7B9ACBD483831BBF3BA74BD2676D4BD1DAC053CAF08263C40A5A53C20CFA83C7BC00CBD22F5933D84BF173EE2A18A3C6735BE3B6E9982BD81E6623B929544BE1F53E93BF6FAEC3CA16CEE3DB10E04BE8358783D316910BE23873EBEA1D524BE50CF70BE62AD02BE32FC32BECB5101BC7B0F42BDBFD8F93C11883C3D907278BC8805F


The rest is similar hex values like the above.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
This is a basic MNIST model in keras format. Model summary is listed below.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 4, 26, 26)         36        
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 4, 24, 24)         144       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 22, 22)         144       
_________________________________________________________________
flatten (Flatten)            (None, 1936)              0         
_________________________________________________________________
dense (Dense)                (None, 10)                19370     
=================================================================
Total params: 19,694
Trainable params: 19,694
Non-trainable params: 0
_________________________________________________________________

https://drive.google.com/file/d/12HM4mRhYnN-CZuqk1zEwRWkIyQr0RTUC/view?usp=sharing
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:

The converter prompts `tf.Conv2D` is not supported. But I think this op is written in your allowlist for sure. 

**Any other info / logs**
[error with tf 2.3.1.log](https://github.com/tensorflow/tensorflow/files/5611223/error.with.tf.2.3.1.log)

Running on tf-nightly build 2.5.0-dev20201128 throws an error as well, but the error message is different. I tried this in Google Colab.
```
AttributeError                            Traceback (most recent call last)
<ipython-input-3-ec82a6e4977e> in <module>()
     23 converter.inference_input_type = tf.int8  # or tf.uint8
     24 converter.inference_output_type = tf.int8  # or tf.uint8
---> 25 tflite_quant_model = converter.convert()
     26 
     27 open("quantized.tflite", "wb").write(tflite_quant_model)

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self)
    893 
    894     return super(TFLiteKerasModelConverterV2,
--> 895                  self).convert(graph_def, input_tensors, output_tensors)
    896 
    897 

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in convert(self, graph_def, input_tensors, output_tensors)
    651     calibrate_and_quantize, flags = quant_mode.quantizer_flags()
    652     if calibrate_and_quantize:
--> 653       result = self._calibrate_quantize_model(result, **flags)
    654 
    655     flags_modify_model_io_type = quant_mode.flags_modify_model_io_type(

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/lite.py in _calibrate_quantize_model(self, result, inference_input_type, inference_output_type, activations_type, allow_float)
    479       return calibrate_quantize.calibrate_and_quantize(
    480           self.representative_dataset.input_gen, inference_input_type,
--> 481           inference_output_type, allow_float, activations_type)
    482 
    483   def _is_unknown_shapes_allowed(self):

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/optimize/calibrator.py in calibrate_and_quantize(self, dataset_gen, input_type, output_type, allow_float, activations_type, resize_input)
     95         initialized = True
     96         if resize_input:
---> 97           self._calibrator.Prepare([list(s.shape) for s in sample])
     98         else:
     99           self._calibrator.Prepare()

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/optimize/calibrator.py in <listcomp>(.0)
     95         initialized = True
     96         if resize_input:
---> 97           self._calibrator.Prepare([list(s.shape) for s in sample])
     98         else:
     99           self._calibrator.Prepare()

AttributeError: 'function' object has no attribute 'shape'
```

**Comment by ravikyram** [comment]
@CPA872 

Please, share mnist.h5 file. It helps me to reproduce the issue.

Please, grant me the access to below link

https://drive.google.com/file/d/12HM4mRhYnN-CZuqk1zEwRWkIyQr0RTUC/view?usp=sharing

Thanks!

**Comment by CPA872** [comment]
Sorry I forgot to change the access settings.
https://drive.google.com/file/d/12HM4mRhYnN-CZuqk1zEwRWkIyQr0RTUC/view?usp=sharing
It should work now.

**Comment by CPA872** [comment]
This issue is resolved for me. I did not add `converter.target_spec.supported_types = [tf.int8]` to specify my target quantization.

Maybe you can update this tutorial page since it makes people think int8 quantization is enabled by default without the above line. By following the example code on this page, one would reproduce the error I had described in this issue. 

https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only

Thanks!

**Comment by jvishnuvardhan** [comment]
@CPA872 Can you please share a gist. I tried your code and still see same error even after adding `converter.target_spec.supported_types = [tf.int8]`. Can you please check my [gist here](https://colab.research.google.com/gist/jvishnuvardhan/3ff1900656a695bea20c17c43d1f6d79/untitled.ipynb) and let me know what I am missing.

Once I can find a root-cause, I can update the doc. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Thanks!
