### ISSUE TITLE
Whl package not building due with a issue with sed - MacOS 11

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#45434]
**System information**
- OS Platform and Distribution: Mac OS 11.0.1 Big Sur
- TensorFlow installed from (source or binary): Source - git
- TensorFlow version: 2.4.0-rc4
- Python version: 3.8.6 (macports)
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): Apple clang version 12.0.0 (clang-1200.0.32.27) XCode 12.2
- CUDA/cuDNN version: No
- GPU model and memory: AMD Radeon Pro 555X - 4GB

**Describe the problem**
Tensorflow compiles correctly. However, when using the command:

`bazel-bin/tensorflow/tools/pip_package/build_pip_package`

the whl package is not produced and rather the following error is shown:

`sed: /var/folders/y4/85hx48054tbd2y04jkf3l6880000gn/T/tmp.XXXXXXXXXX.Ty6dzcrU/tensorflow/__init__.py: in-place editing only works for regular files`

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. Compile from source as indicated in the tensorflow manual. 
2. Run the command to build the whl package:

`bazel-bin/tensorflow/tools/pip_package/build_pip_package ..`

**Any other info / logs**
This error is not present in MacOS 10.15. All proceed as it should

**Comment by feranick** [comment]
When replacing sed with gsed (from macports) in the following:

`bazel-bin/tensorflow/tools/pip_package/build_pip_package`

in line 219:

`gsed -i'.original' -e 's/.python.keras.api._v1/tensorflow/g' ${TMPDIR}/tensorflow/__init__.py`

and line 222:
    `gsed -i'.original' -e 's/.python.keras.api._v2/tensorflow/g' ${TMPDIR}/tensorflow/__init__.py`
  
the whl package is produced correctly.

**Comment by ravikyram** [comment]
@feranick 

Glad to know issue was resolved. Please, close this issue as your issue was resolved. Thanks!

**Comment by feranick** [comment]
Well, the issue is only partially resolved, as the solution requires the use of a non standard feature (i.e. gsed from mackports). I think it would be wise to add a note on the "known issues" for others to follow...

**Comment by ravikyram** [comment]
@feranick 

Are you willing to contribute PR for this?
Thanks!

**Comment by feranick** [comment]
How about something like this:

When compiling from source in MacOS 11 Big Sur, a known issue with the command `sed` in MacOS prevents the creation of a wheel package. As a workaround, gsed from macports can be used instead. These are the required steps:
1. Install gsed from macports: 
`sudo port install gsed`
2. After compilation is successfully completed, edit lines 219 and 222 in:
`bazel-bin/tensorflow/tools/pip_package/build_pip_package`
to replace `sed`with `gsed`. 
3. Run the package maker script:
`bazel-bin/tensorflow/tools/pip_package/build_pip_package`

**Comment by mihaimaruseac** [comment]
I think #46147 fixes this
