### ISSUE TITLE
Wheel out of date

### ISSUE THREAD

**Issue by masakistan** [tensorflow/tensorflow#457]
The wheel used for installing via pip for Tensorflow is out of date and is missing parts needed for the tutorials.

I've built from source successfully, but is very difficult to do on a machine that I don't have root access to. An updated wheel would make it much easier to do a user install of Tensorflow.

**Comment by vrv** [comment]
Yes, we are about to build the 0.6.0 packages that should work with all the tutorials at HEAD.  Closing because we're building them now...

**Comment by daikazoku** [comment]
I'm not sure if I understand. On the website there is a 0.6.0 wheel in the instructions,  but when I go to run the pretrained inception-v3 model, I don't find the imagenet directory:

```
(d)[nani@nande cat]$ pip show tensorflow
---
Metadata-Version: 2.0
Name: tensorflow
Version: 0.6.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.com/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/nani/Desktop/cat/d/lib/python2.7/site-packages
Requires: six, protobuf, wheel, numpy


(d)[nani@nande cat]$ ls d/lib/python2.7/site-packages/tensorflow/models/image/
cifar10  __init__.py  __init__.pyc  mnist
```

**Comment by martinwicke** [comment]
Can you download the wheel again? I think this is fixed by now, but I want
to make sure.

**Comment by romanukyan** [comment]
imagenet model is still missing for me on Mac OS using virtualenv.

**Comment by ebrevdo** [comment]
When you pip install --upgrade, also use --no-cache-dir
