### ISSUE TITLE
Illegal instruction (core dumped) in a CPU with AVX support

### ISSUE THREAD

**Issue by cserpell** [tensorflow/tensorflow#45744]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Linux Ubuntu 20.10
- TensorFlow installed from (source or binary): pip, tensorflow-2.4.0-cp38-cp38-manylinux2010_x86_64.whl
- TensorFlow version (use command below): tensorflow-2.4.0-cp38-cp38-manylinux2010_x86_64.whl
- Python version: 3.8.6
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

I was using tensorflow 2 without any issue until a few days ago. I installed it using pip in a new virtualenv environment and now it throws illegal instruction error. My CPU is an i5-3230M, which, according to /proc/cpuinfo supports AVX, so it seems not related to #19584 .

My CPU (according to `/proc/cpuinfo`):
model name      : Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

System:
```
$ uname -a
Linux e431 5.8.0-33-generic #36-Ubuntu SMP Wed Dec 9 09:14:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the expected behavior**
The import should work and not give the `Illegal instruction (core dumped)` error.

**Standalone code to reproduce the issue**

```
$ python3 --version
Python 3.8.6
$ python3 -m venv test
$ . test/bin/activate
$ pip install --upgrade pip
Collecting pip
  Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-20.3.3
$ pip install tensorflow
Collecting tensorflow
  Using cached tensorflow-2.4.0-cp38-cp38-manylinux2010_x86_64.whl (394.8 MB)
Collecting gast==0.3.3
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Collecting absl-py~=0.10
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
Collecting astunparse~=1.6.3
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers~=1.12.0
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting google-pasta~=0.2
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting grpcio~=1.32.0
  Using cached grpcio-1.32.0-cp38-cp38-manylinux2014_x86_64.whl (3.8 MB)
Collecting h5py~=2.10.0
  Using cached h5py-2.10.0-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)
Collecting keras-preprocessing~=1.1.2
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting numpy~=1.19.2
  Using cached numpy-1.19.4-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Collecting opt-einsum~=3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting protobuf>=3.9.2
  Using cached protobuf-3.14.0-cp38-cp38-manylinux1_x86_64.whl (1.0 MB)
Collecting six~=1.15.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting tensorboard~=2.4
  Using cached tensorboard-2.4.0-py3-none-any.whl (10.6 MB)
Requirement already satisfied: setuptools>=41.0.0 in ./test/lib/python3.8/site-packages (from tensorboard~=2.4->tensorflow) (44.0.0)
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.24.0-py2.py3-none-any.whl (114 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.0-py3-none-any.whl (12 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.2-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.3-py3-none-any.whl (96 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting requests<3,>=2.21.0
  Using cached requests-2.25.0-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.6-py3-none-any.whl (47 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.7.0-py3-none-any.whl (779 kB)
Collecting tensorflow-estimator<2.5.0,>=2.4.0rc0
  Using cached tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
Collecting termcolor~=1.1.0
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Collecting typing-extensions~=3.7.4
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting wheel~=0.35
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting wrapt~=1.12.1
  Using cached wrapt-1.12.1.tar.gz (27 kB)
Using legacy 'setup.py install' for termcolor, since package 'wheel' is not installed.
Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
Installing collected packages: urllib3, pyasn1, idna, chardet, certifi, six, rsa, requests, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, google-auth, wheel, werkzeug, tensorboard-plugin-wit, protobuf, numpy, markdown, grpcio, google-auth-oauthlib, absl-py, wrapt, typing-extensions, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, h5py, google-pasta, gast, flatbuffers, astunparse, tensorflow
    Running setup.py install for wrapt ... done
    Running setup.py install for termcolor ... done
Successfully installed absl-py-0.11.0 astunparse-1.6.3 cachetools-4.2.0 certifi-2020.12.5 chardet-3.0.4 flatbuffers-1.12 gast-0.3.3 google-auth-1.24.0 google-auth-oauthlib-0.4.2 google-pasta-0.2.0 grpcio-1.32.0 h5py-2.10.0 idna-2.10 keras-preprocessing-1.1.2 markdown-3.3.3 numpy-1.19.4 oauthlib-3.1.0 opt-einsum-3.3.0 protobuf-3.14.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.25.0 requests-oauthlib-1.3.0 rsa-4.6 six-1.15.0 tensorboard-2.4.0 tensorboard-plugin-wit-1.7.0 tensorflow-2.4.0 tensorflow-estimator-2.4.0 termcolor-1.1.0 typing-extensions-3.7.4.3 urllib3-1.26.2 werkzeug-1.0.1 wheel-0.36.2 wrapt-1.12.1
$ python --version
Python 3.8.6
$ python
Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Illegal instruction (core dumped)
```

**Other info / logs**

**Comment by cserpell** [comment]
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/5703406/tf_env.txt)

**Comment by cserpell** [comment]
Here I attach the output of running an interactive python shell with `python -W all -d -v -X dev` just to import tensorflow.
[py_output.txt](https://github.com/tensorflow/tensorflow/files/5705940/py_output.txt)

**Comment by amahendrakar** [comment]
@cserpell,
Could you please create a new virtual environment and check if you are facing the same issue in that as well? Thanks!

**Comment by cserpell** [comment]
Sure, I already did it in a new virtualenv, but here it goes again in a brand new one.

[new_output.txt](https://github.com/tensorflow/tensorflow/files/5709622/new_output.txt)

**Comment by necromuralist** [comment]
I am having the same problem (also on Ubuntu 20.10, also installed through pip). Whenever I import tensorflow and python crashes and I look in journalctl I see something like this:

`Dec 17 19:30:06 erebus kernel: traps: python[193520] trap invalid opcode ip:7fd16f267c48 sp:7ffd11713f50 error:0 in libtensorflow_framework.so.2[7fd16e4e0000+1c55000]`

**Comment by wingman-jr-addon** [comment]
I also see the same issue on an older server after upgrading to 2.4.0. Crashes consistently at same place while importing tensorflow according to `dmesg`.
```
 8996.519179] traps: python3[2587] trap invalid opcode ip:7f19106a8c48 sp:7ffc8d486220 error:0 in libtensorflow_framework.so.2[7f190f921000+1c55000]
```

Here's one of the cores from `/proc/cpuinfo`, should have AVX:
```
processor       : 0                                                                                                                                                                             
vendor_id       : GenuineIntel                                                                                                                                                                  
cpu family      : 6                                                                                                                                                                             
model           : 45                                                                                                                                                                            
model name      : Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz                                                                                                                                      
stepping        : 7                                                                                                                                                                             
microcode       : 0x71a                                                                                                                                                                         
cpu MHz         : 1199.954                                                                                                                                                                      
cache size      : 20480 KB                                                                                                                                                                      
physical id     : 0                                                                                                                                                                             
siblings        : 16                                                                                                                                                                            
core id         : 0                                                                                                                                                                             
cpu cores       : 8                                                                                                                                                                             
apicid          : 0                                                                                                                                                                             
initial apicid  : 0                                                                                                                                                                             
fpu             : yes                                                                                                                                                                           
fpu_exception   : yes                                                                                                                                                                           
cpuid level     : 13                                                                                                                                                                            
wp              : yes                                                                                                                                                                           
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon
 pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer 
aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d                                                    
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit                                                                                            
bogomips        : 5199.91                                                                                                                                                                       
clflush size    : 64                                                                                                                                                                            
cache_alignment : 64                                                                                                                                                                            
address sizes   : 46 bits physical, 48 bits virtual                                                                                                                                             
power management:                                                                                                                                                                               
```
This is running Ubuntu 18.04.4 LTS.

**Comment by cserpell** [comment]
@necromuralist did you check AVX support on your CPU? Otherwise, please check #19584

**Comment by cserpell** [comment]
Same error for me in `dmesg`:
```
traps: python[434569] trap invalid opcode ip:7fb785029c48 sp:7ffd15a859a0 error:0 in libtensorflow_framework.so.2[7fb7842a2000+1c55000]
```

**Comment by alex-orange** [comment]
Just to pile on, same problem here, 2.4.0 doesn't work, 2.3.0 and earlier do. CPU supports AVX:

```processor	: 31
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
stepping	: 7
microcode	: 0x718
cpu MHz		: 1197.138
cache size	: 20480 KB
physical id	: 1
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 47
initial apicid	: 47
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 4395.39
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

**Comment by alex-orange** [comment]
Couple of things to add though:

1. For me it's a problem with a debian/sid container, not Ubuntu (I assume this is not distro related)
2. I don't see how this is in any way a build/install issue. We aren't building it and it installs fine. It isn't until use time (import) that things fail.

**Comment by necromuralist** [comment]
@cserpell 

If I do `sudo lscpu | grep avx` I get:
` fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonst
op_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave **avx** f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit 
wdt fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold`

(asterixes added)  I get `avx` entries when I grep `/proc/cpuinfo` as well, which I assumed meant that I have AVX support.

**Comment by moorugi98** [comment]
I think I also have the same problem as @alex-orange. 2.4 results in illegal instruction error, whereas 2.3 works. Well, the GPU doesn't work since my CUDA version is incompatible with 2.3 but at least tensorflow works. 

`flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
`

**Comment by necromuralist** [comment]
I just tried the nightly build of tensorflow and it doesn't crash. I used the [nvidia-container ](https://github.com/NVIDIA/nvidia-docker) to get the toolkit and tried to install the latest release of tensorflow via both pip and the [tensorflow-container](https://www.tensorflow.org/install/docker) and both still crashed the python interpreter, but when I did `pip install tf-nightly` it didn't crash the interpreter, but it also couldn't find the nvidia libraries since they're in the container, but I just ran 

`docker run --gpus all -it tensorflow/tensorflow:nightly-gpu bash`

And imported tensorflow into a python intepreter with no errors. Unfortunately in experimenting to get to that state I crashed my server and had to re-install ubuntu so I don't have anything on it to test whether tensorflow actually runs, but it seems promising.

**Comment by alex-orange** [comment]
@necromuralist Sadly I don't think that's progress. #44668 seems to suggest this problem was introduced when nightly was split off to make the release candidate (or whatever the exact process is). Also worth mentioning #45872 and #45866 seem to be the exact same bug.

Adding more info: #45866 seems to suggest that this might be a problem with processors supporting AVX but not AVX2. Is it possible that this requirement got bumped (perhaps by accident)?

**Comment by alex-orange** [comment]
I've just tried building from source with:

    bazel build --config=avx_linux //tensorflow/tools/pip_package:build_pip_package

and the resulting binary works fine. Is it possible someone is building the packages with --config=opt or --config=avx2_linux by accident?

**Comment by moorugi98** [comment]
@alex-orange Is it somehow possible that you share your custom-built package or does everyone need to build for themselves at the moment?

**Comment by alex-orange** [comment]
@moorugi98 Sure, here's my setup: https://gitlab.flux.utah.edu/alex_orange/tensorflow-2.4.0-build . That includes the Dockerfile I use for my build environment and the command history for building and testing. Not exactly perfect but you should be able to figure out how to make your own build (and the maintainers can hopefully use this to get an idea of what's different from the official build).

**Comment by alex-orange** [comment]
Didn't say it very well, but that repo also includes the binary.

**Comment by mihaimaruseac** [comment]
It seems we accidentally built the official wheels using AVX2. Now we are during holiday period so not many people are present but we will revisit this situation in January and issue a patch which either will build using only AVX or will contain release notes updates that from 2.4 onwards AVX2 is required.

I don't know yet which path will be taken. Nor do I know why we got to use AVX2.

**Comment by wingman-jr-addon** [comment]
Thank you for taking the time over the holidays to look into this.

Unsurprisingly I'd like to request keeping in support for the older CPU's, but it appears that I may be 1 out of only 10 or so people on the internet experiencing issues. However, I guess I'd be curious what the Tensorflow project's stance is on the CPU backend (assuming that might be what is driving AVX2).
As  a user, I've seen it as primarily the last resort or "the thing that loads when I need TF as a dependency but not for training". As such I appreciate small advances in speed but have always assumed it would prioritize maximum compatibility first due to its unique position. To that end, it's jarring to hear that my CPU rather than my GPU would potentially be the limiting factor; similarly odd that I would not be able to train small multi-layer dense neural nets due to my CPU being too old.

Thank you for your time and consideration in this matter; I'll be watching for the eventual outcome.

**Comment by foxik** [comment]
Personally I also vote for avoiding requiring AVX2 -- models requiring a lot of computation should use an accelerator anyway, and I value the broad application of the PyPI tensorflow CPU backend more.

**Comment by mihaimaruseac** [comment]
The main issue is that TF is huge, having a lot of code and gets changes submitted from O(hundreds) people but only O(tens) people look at open source and only a team of O(1) sets up the CI infrastructure. So we'll have these accidental slips in the future too, though hopefully we can prevent them in CI.

**Comment by SaschaHeyer** [comment]
Any updates on that topic?

**Comment by mihaimaruseac** [comment]
People started coming up into the office, we're just getting started working on this. Apologies for the delay

**Comment by mihaimaruseac** [comment]
It seems it affects all release builds due to new CPU VMs used during release process. Trying to see if `-march=native` is the culprit.

**Comment by mihaimaruseac** [comment]
We found the culprit, working on a fix and then we will do a patch release on `r2.4`. Not certain on the timeline, but probably will be at least a few weeks as we're gathering other regressions on the 2.4 release.

**Comment by mihaimaruseac** [comment]
And it has been released. Please test it to see that the issue has been fixed

**Comment by cserpell** [comment]
It is working now. Many thanks for your hard work, I really appreciate it.

**Comment by InnocentCow** [comment]
> We should have the patched 2.4.1 release done by the end of the week

I'm using Tensorflow 2.4.1, Python 3.6 and I'm still getting 
`Illegal instruction (core dumpted)`
when I run 
`import tensorflow`
I'm using a Anaconda venv

**Comment by InnocentCow** [comment]
> And it has been released. Please test it to see that the issue has been fixed

I'm using Tensorflow 2.4.1, Python 3.6 and I'm still getting
`Illegal instruction (core dumpted)`
when I run
`import tensorflow`
I'm using a Anaconda venv

**Comment by mihaimaruseac** [comment]
@InnocentCow does your CPU support AVX? This issue is for AVX2.

**Comment by byronyi** [comment]
> > And it has been released. Please test it to see that the issue has been fixed
> 
> I'm using Tensorflow 2.4.1, Python 3.6 and I'm still getting
> `Illegal instruction (core dumpted)`
> when I run
> `import tensorflow`
> I'm using a Anaconda venv
> *edit:
> Same goes when I'm using Tensorflow 2.3.1

Try `import tensorflow as tf; print(tf.version.VERSION)`

**Comment by InnocentCow** [comment]
> > > And it has been released. Please test it to see that the issue has been fixed
> > 
> > 
> > I'm using Tensorflow 2.4.1, Python 3.6 and I'm still getting
> > `Illegal instruction (core dumpted)`
> > when I run
> > `import tensorflow`
> > I'm using a Anaconda venv
> > *edit:
> > Same goes when I'm using Tensorflow 2.3.1
> 
> Try `import tensorflow as tf; print(tf.version.VERSION)`

Tried this, still same error

**Comment by InnocentCow** [comment]
> @InnocentCow does your CPU support AVX? This issue is for AVX2.

I have an Intel Celeron N3550, and from what I've found it does support AVX

**Comment by InnocentCow** [comment]
Nevermind, I get 
`Illegal instruction (core dumped)`
as well when I only
`import keras`
So I guess TensorFlow is not the problem here

**Comment by byronyi** [comment]
Never mind, happy hacking!

**Comment by bykvaadm** [comment]
have same issue, installed 2.4.1 version, but it didn't help.
Compiled 2.4.1 version from sources and it did the trick.

**Comment by ngsteven97** [comment]
> have same issue, installed 2.4.1 version, but it didn't help.
> Compiled 2.4.1 version from sources and it did the trick.

I'm trying to install 2.4.1 onto my Jetson Nano, and I'm having the illegal instructions error, can you help me with compiling it from sources? I am a complete noob when it comes to Linux and python and stuff!

**Comment by bykvaadm** [comment]
> I'm trying to install 2.4.1 onto my Jetson Nano, and I'm having the illegal instructions error, can you help me with compiling it from sources? I am a complete noob when it comes to Linux and python and stuff!

https://www.tensorflow.org/install/source

**Comment by mihaimaruseac** [comment]
CPUs with no AVX support are no longer supported by the default package. You have to compile from source or use a cloud version of TF (via Google Colab for example).
