### ISSUE TITLE
MHLO/LHLO Fusion lower

### ISSUE THREAD

**Issue by feiyuvl** [tensorflow/tensorflow#45820]
It seems mhlo-fusion op is unable to legalize to lhlo， and lhlo-fusion op is also unable to lower to linalg  dialect. Is there any plan to support the fusion op lower? Linalg fusion on tensor is not perfect for multi-output elemwise ops. Following is a  example
```
// CHECK-LABEL: func @multi_outputs_same_2
func @multi_outputs_same_2(%arg0: tensor<?x?xf32>, %arg1: tensor<?x?xf32>) -> (tensor<?x?xf32>, tensor<?x?xf32>, tensor<?x?xf32>) {
  %0 = "mhlo.abs"(%arg0) : (tensor<?x?xf32>) -> tensor<?x?xf32>
  %1 = "mhlo.abs"(%arg1) : (tensor<?x?xf32>) -> tensor<?x?xf32>
  %2 = "mhlo.add"(%0, %1) : (tensor<?x?xf32>, tensor<?x?xf32>) -> tensor<?x?xf32>
  %3 = "mhlo.abs"(%0) : (tensor<?x?xf32>) -> tensor<?x?xf32>
  %4 = "mhlo.abs"(%1) : (tensor<?x?xf32>) -> tensor<?x?xf32>
  // CHECK: %[[RET:.*]]:3 = "mhlo.fusion"
  // CHECK-NEXT: mhlo.abs
  // CHECK-NEXT: mhlo.abs
  // CHECK-NEXT: mhlo.add
  // CHECK-NEXT: mhlo.abs
  // CHECK-NEXT: mhlo.abs
  // CHECK-NEXT: mhlo.return
  return %2, %3, %4 : tensor<?x?xf32>, tensor<?x?xf32>, tensor<?x?xf32>
}
```
with command`mlir-hlo-opt ./lhlo-test.mlir -hlo-legalize-to-linalg -linalg-bufferize -convert-linalg-to-affine-loops`，get the following result
```
#map0 = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<() -> (0)>
#map2 = affine_map<()[s0] -> (s0)>
module {
  func @multi_outputs_same_2(%arg0: tensor<?x?xf32>, %arg1: tensor<?x?xf32>) -> (tensor<?x?xf32>, tensor<?x?xf32>, tensor<?x?xf32>) {
    %c0 = constant 0 : index
    %c1 = constant 1 : index
    %0 = tensor_to_memref %arg0 : memref<?x?xf32>
    %1 = dim %arg0, %c0 : tensor<?x?xf32>
    %2 = dim %arg0, %c1 : tensor<?x?xf32>
    %3 = alloc(%1, %2) : memref<?x?xf32>
    %4 = dim %0, %c0 : memref<?x?xf32>
    %5 = dim %0, %c1 : memref<?x?xf32>
    affine.for %arg2 = 0 to %4 {
      affine.for %arg3 = 0 to %5 {
        %18 = affine.load %0[%arg2, %arg3] : memref<?x?xf32>
        %19 = absf %18 : f32
        affine.store %19, %3[%arg2, %arg3] : memref<?x?xf32>
      }
    }
    %6 = tensor_to_memref %arg1 : memref<?x?xf32>
    %7 = dim %arg1, %c0 : tensor<?x?xf32>
    %8 = dim %arg1, %c1 : tensor<?x?xf32>
    %9 = alloc(%7, %8) : memref<?x?xf32>
    %10 = dim %6, %c0 : memref<?x?xf32>
    %11 = dim %6, %c1 : memref<?x?xf32>
    affine.for %arg2 = 0 to %10 {
      affine.for %arg3 = 0 to %11 {
        %18 = affine.load %6[%arg2, %arg3] : memref<?x?xf32>
        %19 = absf %18 : f32
        affine.store %19, %9[%arg2, %arg3] : memref<?x?xf32>
      }
    }
    %12 = alloc(%1, %2) : memref<?x?xf32>
    affine.for %arg2 = 0 to %1 {
      affine.for %arg3 = 0 to %2 {
        %18 = affine.load %3[%arg2, %arg3] : memref<?x?xf32>
        %19 = affine.load %9[%arg2, %arg3] : memref<?x?xf32>
        %20 = addf %18, %19 : f32
        affine.store %20, %12[%arg2, %arg3] : memref<?x?xf32>
      }
    }
    %13 = tensor_load %12 : memref<?x?xf32>
    %14 = alloc(%1, %2) : memref<?x?xf32>
    affine.for %arg2 = 0 to %1 {
      affine.for %arg3 = 0 to %2 {
        %18 = affine.load %3[%arg2, %arg3] : memref<?x?xf32>
        %19 = absf %18 : f32
        affine.store %19, %14[%arg2, %arg3] : memref<?x?xf32>
      }
    }
    %15 = tensor_load %14 : memref<?x?xf32>
    %16 = alloc(%7, %8) : memref<?x?xf32>
    affine.for %arg2 = 0 to %7 {
      affine.for %arg3 = 0 to %8 {
        %18 = affine.load %9[%arg2, %arg3] : memref<?x?xf32>
        %19 = absf %18 : f32
        affine.store %19, %16[%arg2, %arg3] : memref<?x?xf32>
      }
    }
    %17 = tensor_load %16 : memref<?x?xf32>
    return %13, %15, %17 : tensor<?x?xf32>, tensor<?x?xf32>, tensor<?x?xf32>
  }
}

```

I expect one affine nest,  but it get three affine nests. Will mhlo-fusion lowering solve this problem, or is there any other way to fuse the three for loops into one?

**Comment by feiyuvl** [comment]
@sherhut hi , can you give me some help on this question?

**Comment by sherhut** [comment]
If you want to fuse on tensors, you can use `-linalg-fusion-for-tensor-ops` from mlir directly. This would go before the `-linalg-bufferize`. See https://github.com/llvm/llvm-project/blob/main/mlir/test/Dialect/Linalg/fusion-tensor.mlir for an example.

For fusion on buffers, you can use `-lho-fuse-linalg` as shown in the example at https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/compiler/mlir/hlo/tests/lhlo-fuse-linalg.mlir. This would go after the `-linalg-bufferize`. 

Both of these passes work at the LinAlg level and combine the `linalg.generic` operations that come out of the lowering of the `mhlo` operations into a single `linalg.generic`. The version on buffers also does tiling. These fused operations are then mapped to a single `affine.for` nest.

@bondhugula might have input on how to do loop fusion at the affine level but that likely is not what you want here.

As you also mention the `fusion` operation from the `mhlo` and `lmhlo` dialects: These operations are meant to guide fusion. The two passes I have mentioned above are greedy in the sense that they will fuse all operations in the region that are fusible. The idea behind the `fusion` operation is to first group operations that you want fused, then have a pass that fuses them (and drops the fusion operation once it only contains a single operation).

There is no ready to use fusion pass for this available at the moment and you would need to write your own.

**Comment by bondhugula** [comment]
@feiyuvl  I notice that you have dynamic shapes. The affine loop fusion pass currently works with constant loop bounds - not hard to extend it though. If you replace your dynamic sizes with static ones just to try it out, the `-affine-loop-fusion` will fuse your whole test case into a single affine loop nest. Try:
```
tf-opt -hlo-legalize-to-lhlo -lhlo-legalize-to-linalg -convert-linalg-to-affine-loops -lhlo-legalize-to-affine -canonicalize -affine-loop-fusion
```
your input is transformed to:

```
 affine.for %arg2 = 0 to 1024 {
      affine.for %arg3 = 0 to 1024 {
        %5 = affine.load %arg0[%arg2, %arg3] : memref<1024x1024xf32>
        %6 = absf %5 : f32
        affine.store %6, %0[0, 0] : memref<1x1xf32>
        %7 = affine.load %arg1[%arg2, %arg3] : memref<1024x1024xf32>
        %8 = absf %7 : f32
        affine.store %8, %1[0, 0] : memref<1x1xf32>
        %9 = affine.load %0[0, 0] : memref<1x1xf32>
        %10 = affine.load %1[0, 0] : memref<1x1xf32>
        %11 = addf %9, %10 : f32
        affine.store %11, %2[%arg2, %arg3] : memref<1024x1024xf32>
        %12 = affine.load %0[0, 0] : memref<1x1xf32>
        %13 = absf %12 : f32
        affine.store %13, %3[%arg2, %arg3] : memref<1024x1024xf32>
        %14 = affine.load %1[0, 0] : memref<1x1xf32>
        %15 = absf %14 : f32
        affine.store %15, %4[%arg2, %arg3] : memref<1024x1024xf32>
      }
    }
```

You may want to always run `-memref-dataflow-opt` on the output of fusion (it'll fwd the stores to the loads), and you'll get:

```
  %0 = alloc() : memref<1024x1024xf32>
    %1 = alloc() : memref<1024x1024xf32>
    %2 = alloc() : memref<1024x1024xf32>
    affine.for %arg2 = 0 to 1024 {
      affine.for %arg3 = 0 to 1024 {
        %3 = affine.load %arg0[%arg2, %arg3] : memref<1024x1024xf32>
        %4 = absf %3 : f32
        %5 = affine.load %arg1[%arg2, %arg3] : memref<1024x1024xf32>
        %6 = absf %5 : f32
        %7 = addf %4, %6 : f32
        affine.store %7, %0[%arg2, %arg3] : memref<1024x1024xf32>
        %8 = absf %4 : f32
        affine.store %8, %1[%arg2, %arg3] : memref<1024x1024xf32>
        %9 = absf %6 : f32
        affine.store %9, %2[%arg2, %arg3] : memref<1024x1024xf32>
      }
    }
```

I'm sure this is close to the output you (or anyone else :-)) would expect given the original input.

**Comment by feiyuvl** [comment]
@sherhut @bondhugula Thank you for your replies. @bondhugula  Loop fusion works for static shapes, however  is there a scheduler to support dynamic shapes?

**Comment by bondhugula** [comment]
> @sherhut @bondhugula Thank you for your replies. @bondhugula Loop fusion works for static shapes, however is there a scheduler to support dynamic shapes?

`scheduler`? Did you mean a plan to support it? This has come up several times (in posts on the MLIR/LLVM discourse channel and with @dcaballe as well) but I think but no one is working actively on it. So, contributions are welcome here.

**Comment by dcaballe** [comment]
>  I think no one is working actively on it.

We did some internal hacks to understand if the core affine fusion algorithm was ready for dynamic shapes and we were able to have some loops fused. I think the code is not reusable, though, but I'll check. Other than that, we are not working on adding support for it right now but I'll be happy to help with the reviews if someone is interested. 

> not perfect for multi-output elemwise ops

Currently, there are also some limitations in affine fusion wrt multi-producer loops. However, we are introducing proper support for them here: https://reviews.llvm.org/D92876. Hopefully, we can land this soon :)

**Comment by feiyuvl** [comment]
@bondhugula @dcaballe thx，for the above example with static shapes,, if i add -buffer-results-to-out-params, it will still produce multiple affine loop. By the way, it seems very diffcult to implement memory plan pass in mlir  which is common in traditional deep learning framework.

**Comment by bondhugula** [comment]
> @bondhugula @dcaballe thx，for the above example with static shapes,, if i add -buffer-results-to-out-params, it will still produce multiple affine loop. 

This issue might go away with Diego's patch that will soon be committed (linked in Diego's post above).

> By the way, it seems very diffcult to implement memory plan pass in mlir which is common in traditional deep learning 

It's not clear to me what this means - it looks unrelated to the fusion issue in discussion here.

**Comment by sherhut** [comment]
> By the way, it seems very diffcult to implement memory plan pass in mlir which is common in traditional deep learning framework.

Can you elaborate on this? I would be interested in understanding this better.

**Comment by dcaballe** [comment]
I just committed the fusion patch. Please, give it a try and let me know if it doesn't work. Thanks!

**Comment by feiyuvl** [comment]
@dcaballe Thank you, I have tried the new version. For static shape, it handles multi-output well using affine-loop-fusion, but still fails when using -linalg-fusion-for-tensor-ops after the -hlo-legalize-to-linalg pass. 
@sherhut What I mean is memory sharing between different tensors,  which is simliar to register allocation. onnx-mlir has implemented a simple version in this pr https://github.com/onnx/onnx-mlir/pull/346

**Comment by dcaballe** [comment]
> @dcaballe Thank you, I have tried the new version. For static shape, it handles multi-output well using affine-loop-fusion, but still fails when using -linalg-fusion-for-tensor-ops after the -hlo-legalize-to-linalg pass.

Good to hear. Yeah, my patch only covered affine loop fusion.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
