### ISSUE TITLE
NotFoundError: '_MklMatMul'

### ISSUE THREAD

**Issue by CalebEverett** [tensorflow/tensorflow#45963]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): 
 No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
c0-deeplearning-tf2-2-4-tpu-v20201215-debian-10
Description
Google, Deep Learning Image: TensorFlow 2.4, m60 TPU, A debian-10 Linux based image with TensorFlow 2.4 pre-installed.
Location
asia (Asia Pacific), eu (European Union), us (United States)
Labels
release : m60
Creation time
Dec 16, 2020, 5:10:12 PM UTC-08:00
Family
tf2-2-4-tpu-debian-10
Encryption type
Google managed

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
After initializing the tpu - I'm using version 2.4 on the tpu as well, tf.matmul doesn't work anymore.

I'm initializing the tpu with:

```
def get_strategy():

    try:
        tpu = tf.distribute.cluster_resolver.TPUClusterResolver('tpu-3')
        print('Running on TPU ', tpu.master())
    except:
        tpu = None

    if tpu:
        tf.config.experimental_connect_to_cluster(tpu)
        tf.tpu.experimental.initialize_tpu_system(tpu)
        strategy = tf.distribute.TPUStrategy(tpu)
    
    else:
        strategy = tf.distribute.get_strategy()
        for d in tf.config.list_physical_devices():
            print(d)
            
    return strategy

strategy = get_strategy()
```

Here is the full error:

```
NotFoundError: '_MklMatMul' is neither a type of a primitive operation nor a name of a function registered in binary running on n-1f5a3a66-w-0. Make sure the operation or function is registered in the binary running in this process.
```

It works fine on the cpu before the tpu is initialized.

**Comment by CalebEverett** [comment]
Reverting to 2.2 works

**Comment by amahendrakar** [comment]
@CalebEverett,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by amahendrakar** [comment]
Also, please go through [this comment](https://github.com/tensorflow/tensorflow/issues/45317#issuecomment-738273941) from similar issue #45317 and let us know if it helps. Thanks!

**Comment by CalebEverett** [comment]
1. Create a GCP VM - from the console I selected a linux deeplearning image and then the debian 10 one optimized for tpu. Here is the source image: `c0-deeplearning-tf2-2-4-tpu-v20201215-debian-10`
2. Create a v3-8 tpu with version 2.4.0 of the software installed
3. Import tensorflow and run a tf.matmul calculation:
```
import tensorflow as tf
tf.matmul(tf.ones((4,4)), tf.ones((4,4)))


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]], dtype=float32)>
```
Initialize tpu
```
    try:
        tpu = tf.distribute.cluster_resolver.TPUClusterResolver('tpu-3')
        print('Running on TPU ', tpu.master())
    except:
        tpu = None

    if tpu:
        tf.config.experimental_connect_to_cluster(tpu)
        tf.tpu.experimental.initialize_tpu_system(tpu)
        strategy = tf.distribute.TPUStrategy(tpu)
    
    else:
        strategy = tf.distribute.get_strategy()
        for d in tf.config.list_physical_devices():
            print(d)


Running on TPU  grpc://10.211.162.226:8470
INFO:tensorflow:Initializing the TPU system: tpu-3
INFO:tensorflow:Initializing the TPU system: tpu-3
INFO:tensorflow:Clearing out eager caches
INFO:tensorflow:Clearing out eager caches
INFO:tensorflow:Finished initializing TPU system.
INFO:tensorflow:Finished initializing TPU system.
INFO:tensorflow:Found TPU system:
INFO:tensorflow:Found TPU system:
INFO:tensorflow:*** Num TPU Cores: 8
INFO:tensorflow:*** Num TPU Cores: 8
INFO:tensorflow:*** Num TPU Workers: 1
INFO:tensorflow:*** Num TPU Workers: 1
INFO:tensorflow:*** Num TPU Cores Per Worker: 8
INFO:tensorflow:*** Num TPU Cores Per Worker: 8
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)
```

4. Run the tf.matmul calculation again
```
tf.matmul(tf.ones((4,4)), tf.ones((4,4)))

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/opt/conda/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/opt/conda/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in __repr__(self)
   1015   def __repr__(self):
   1016     return "<tf.Tensor: shape=%s, dtype=%s, numpy=%s>" % (
-> 1017         self.shape, self.dtype.name, numpy_text(self, is_repr=True))
   1018 
   1019   def __len__(self):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in shape(self)
   1173         # `_tensor_shape` is declared and defined in the definition of
   1174         # `EagerTensor`, in C.
-> 1175         self._tensor_shape = tensor_shape.TensorShape(self._shape_tuple())
   1176       except core._NotOkStatusException as e:
   1177         six.raise_from(core._status_to_exception(e.code, e.message), None)

NotFoundError: '_MklMatMul' is neither a type of a primitive operation nor a name of a function registered in binary running on n-1f5a3a66-w-0. Make sure the operation or function is registered in the binary running in this process.
```

**Comment by amahendrakar** [comment]
@CalebEverett,
I was able to run the code without any issues on TF v2.4, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/76ddd34f8853e0025d174121e2b7650d/45963.ipynb).

Could you please try running the code in a new virtual environment and check if you are facing the same error. Thanks!

**Comment by CalebEverett** [comment]
That looks like its working - thank you.

**Comment by amahendrakar** [comment]
@CalebEverett,
Thank you for the update. Closing the issue as it is resolved. Please feel free to re-open if necessary.

**Comment by shigabeev** [comment]
Problem still persists and it lies in the image provided by Google Cloud itself. The solution is to always be defensive to any pre-installed tensorflow distribution and install one manually.

Quick fix is:
`pip install --upgrade --force-reinstall tensorflow`
