### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by cswhjiang** [tensorflow/tensorflow#4649]
Build failed with 
```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```
,but
 ```
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
```
 works. Any suggestions? Thanks

Here are the error messages:

```
ERROR: /data1/wenhaojiang/.cache/bazel/_bazel_wenhaojiang/4d6dbdb415b7bb548255a6ccf48e22e6/external/protobuf/BUILD:73:1: undeclared inclusion(s) in rule '@protobuf//:protobuf_lite':
this rule is missing dependency declarations for the following files included by 'external/protobuf/src/google/protobuf/stubs/once.cc':
  '/include/c++/4.8.2/string'
  '/include/c++/4.8.2/x86_64-redhat-linux/bits/c++config.h'
  '/include/c++/4.8.2/x86_64-redhat-linux/bits/os_defines.h'
  '/include/c++/4.8.2/x86_64-redhat-linux/bits/cpu_defines.h'
  '/include/c++/4.8.2/bits/stringfwd.h'
  '/include/c++/4.8.2/bits/memoryfwd.h'
  '/include/c++/4.8.2/bits/char_traits.h'
  '/include/c++/4.8.2/bits/stl_algobase.h'
  '/include/c++/4.8.2/bits/functexcept.h'
  '/include/c++/4.8.2/bits/exception_defines.h'
  '/include/c++/4.8.2/bits/cpp_type_traits.h'
  '/include/c++/4.8.2/ext/type_traits.h'
  '/include/c++/4.8.2/ext/numeric_traits.h'
  '/include/c++/4.8.2/bits/stl_pair.h'
  '/include/c++/4.8.2/bits/move.h'
  '/include/c++/4.8.2/bits/concept_check.h'
  '/include/c++/4.8.2/type_traits'
  '/include/c++/4.8.2/bits/stl_iterator_base_types.h'
  '/include/c++/4.8.2/bits/stl_iterator_base_funcs.h'
  '/include/c++/4.8.2/debug/debug.h'
  '/include/c++/4.8.2/bits/stl_iterator.h'
  '/include/c++/4.8.2/bits/postypes.h'
  '/include/c++/4.8.2/cwchar'
  '/lib/gcc/x86_64-redhat-linux/4.8.2/include/stdarg.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.2/include/stddef.h'
  '/include/c++/4.8.2/cstdint'
  '/lib/gcc/x86_64-redhat-linux/4.8.2/include/stdint.h'
  '/include/c++/4.8.2/bits/allocator.h'
  '/include/c++/4.8.2/x86_64-redhat-linux/bits/c++allocator.h'
  '/include/c++/4.8.2/ext/new_allocator.h'
  '/include/c++/4.8.2/new'
  '/include/c++/4.8.2/exception'
  '/include/c++/4.8.2/bits/atomic_lockfree_defines.h'
  '/include/c++/4.8.2/bits/exception_ptr.h'
  '/include/c++/4.8.2/bits/nested_exception.h'
  '/include/c++/4.8.2/bits/localefwd.h'
  '/include/c++/4.8.2/x86_64-redhat-linux/bits/c++locale.h'
  '/include/c++/4.8.2/clocale'
  '/include/c++/4.8.2/iosfwd'
  '/include/c++/4.8.2/cctype'
  '/include/c++/4.8.2/bits/ostream_insert.h'
  '/include/c++/4.8.2/bits/cxxabi_forced.h'
  '/include/c++/4.8.2/bits/stl_function.h'
  '/include/c++/4.8.2/backward/binders.h'
  '/include/c++/4.8.2/bits/range_access.h'
  '/include/c++/4.8.2/bits/basic_string.h'
  '/include/c++/4.8.2/ext/atomicity.h'
  '/include/c++/4.8.2/x86_64-redhat-linux/bits/gthr.h'
  '/include/c++/4.8.2/x86_64-redhat-linux/bits/gthr-default.h'
  '/include/c++/4.8.2/x86_64-redhat-linux/bits/atomic_word.h'
  '/include/c++/4.8.2/initializer_list'
  '/include/c++/4.8.2/ext/string_conversions.h'
  '/include/c++/4.8.2/cstdlib'
  '/include/c++/4.8.2/cstdio'
  '/include/c++/4.8.2/cerrno'
  '/include/c++/4.8.2/bits/functional_hash.h'
  '/include/c++/4.8.2/bits/hash_bytes.h'
  '/include/c++/4.8.2/bits/basic_string.tcc'
  '/include/c++/4.8.2/cstddef'
  '/lib/gcc/x86_64-redhat-linux/4.8.2/include/limits.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.2/include/syslimits.h'
  '/include/c++/4.8.2/utility'
  '/include/c++/4.8.2/bits/stl_relops.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.151s, Critical Path: 0.87s
```

CUDA 7.5
gcc -v
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)
```

bazel version
```
Build label: 0.3.1-jdk7
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:07:03 2016 (1469783223)
Build timestamp: 1469783223
```

output of `echo | gcc -E -xc++ - -v`:
```
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.2-20140120/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC)
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /usr/libexec/gcc/x86_64-redhat-linux/4.8.2/cc1plus -E -quiet -v -D_GNU_SOURCE - -mtune=generic -march=x86-64
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.8.2/include-fixed"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../../x86_64-redhat-linux/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../../include/c++/4.8.2
 /usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../../include/c++/4.8.2/x86_64-redhat-linux
 /usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../../include/c++/4.8.2/backward
 /usr/lib/gcc/x86_64-redhat-linux/4.8.2/include
 /usr/local/include
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 1 "<command-line>" 2
# 1 "<stdin>"
COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.2/:/usr/lib/gcc/x86_64-redhat-linux/
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.2/:/usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.2/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
```

**Comment by kadafax** [comment]
Same here also on centos 7. And I've tried with gcc 4.9 from SCL with same (bad) result.
Cuda 7.5 (/usr/local/cuda-7.5)
Cudnn 5.1.3 (which is installed in my home folder, as tell to th configure script)

**Comment by tatatodd** [comment]
@cswhjiang @kadafax take a look at #3985 and let me know if that fixes things.

**Comment by cswhjiang** [comment]
thanks. The problem was solved by use `/usr/bin/gcc` instead of `/bin/gcc` in `./configure`

**Comment by kadafax** [comment]
Still failling:

Centos 7
$ gcc --version
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
$ bazel version
Build label: 0.3.1-2016-10-05 (@27cd7f6)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Oct 5 14:02:43 2016 (1475676163)
Build timestamp: 1475676163
Build timestamp as int: 1475676163

CUDA 7.5 (/usr/local/cuda-7.5)
CUDNN 5.1.3 (in my home folder)
---------

./configure:

> [kadafax@GPUNODE1 tensorflow]$ ./configure
> /home/kadafax/corner/tarballs/tensorflow /home/kadafax/corner/tarballs/tensorflow
> Please specify the location of python. [Default is /bin/python]:
> Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
> No Google Cloud Platform support will be enabled for TensorFlow
> Do you wish to build TensorFlow with Hadoop File System support? [y/N]
> No Hadoop File System support will be enabled for TensorFlow
> Found possible Python library paths:
>   /usr/lib/python2.7/site-packages
>   /usr/lib64/python2.7/site-packages
> Please input the desired Python library path to use.  Default is [/usr/lib/python2.7/site-packages]
> 
> /usr/lib/python2.7/site-packages
> Do you wish to build TensorFlow with GPU support? [y/N] Y
> GPU support will be enabled for TensorFlow
> Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/lib64/ccache/gcc]: /usr/bin/gcc
> Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
> Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/local/cuda-7.5
> Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1.3
> Please specify the location where cuDNN 5.1.3 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda-7.5]: /home/kadafax/corner
> Please specify a list of comma-separated Cuda compute capabilities you want to build with.
> You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
> Please note that each additional compute capability significantly increases your build time and binary size.
> [Default is: "3.5,5.2"]: 3.7,3.5
> Extracting Bazel installation...
> Killed non-responsive server process (pid=1228)
> ............
> INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
> .........
> INFO: All external dependencies fetched successfully.
> Configuration finished

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package:

> ERROR: /home/kadafax/corner/tarballs/tensorflow/tensorflow/stream_executor/BUILD:5:1: C++ compilation of rule '//tensorflow/stream_executor:stream_executor' failed: crosstool_wrapper_dr
> iver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -
> Wunused-but-set-parameter ... (remaining 114 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
> tensorflow/stream_executor/cuda/cuda_dnn.cc: In instantiation of 'cudnnStatus_t perftools::gputools::cuda::dynload::DynLoadShim__cudnnSetRNNDescriptor::operator()(perftools::gputools::cuda::CUDAExecutor
> *, Args ...) [with Args = {cudnnRNNStruct*, int, int, cudnnDropoutStruct*, cudnnRNNInputMode_t, cudnnDirectionMode_t, cudnnRNNMode_t, cudnnDataType_t}]':
> tensorflow/stream_executor/cuda/cuda_dnn.cc:1005:50:   required from here
> tensorflow/stream_executor/cuda/cuda_dnn.cc:166:38: error: invalid conversion from 'cudnnDropoutStruct*' to 'int' [-fpermissive]

**Comment by tatatodd** [comment]
@kadafax that looks like a different problem.  Here's how to look for similar issues:

https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Atensorflow%2Fmodels+repo%3Atensorflow%2Ftensorflow+crosstool_wrapper_driver_is_not_gcc

In particular, #4705 and #4105 seem related.  You can try running bazel clean and fetch after ./configure, and see if that fixes things.  Details in the referenced issues.

**Comment by kadafax** [comment]
OK thanks. Got it working.

For the records:
- tell the configure.sh script to use /usr/bin/gcc 
- put cuda 7.5 and cudnn 5.1.3 in the same folder (can be in $HOME)
- export CC=/usr/bin/gcc
- modify third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl by adding the following line:
    +cpu_compiler_flags.append('-fno-use-linker-plugin')
      return subprocess.call([CPU_COMPILER] + cpu_compiler_flags)

**Comment by tatatodd** [comment]
Cool, glad it's working.  Closing this out, but feel free to comment or file a new issue if you run into other problems.
