### ISSUE TITLE
bazel 0.1.2  undeclared inclusions fixes needed in BUILD files

### ISSUE THREAD

**Issue by GregBowyer** [tensorflow/tensorflow#469]
Started out with this error

```
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $ bazel build --verbose_failures -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
INFO: Found 1 target...
INFO: From Compiling external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.cc:
src/main/tools/namespace-sandbox.c:633: execvp(argv[0], argv): No such file or directory
ERROR: /tmp/gbowyer/.cache/bazel/_bazel_gbowyer/d132132edbbae685571ab9488dabc906/external/gemmlowp/BUILD:77:1: C++ compilation of rule '@gemmlowp//:eight_bit_int_gemm' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /tmp/gbowyer/.cache/bazel/_bazel_gbowyer/d132132edbbae685571ab9488dabc906/tensorflow && \
  exec env - \
    PATH=/opt/java/jdk1.8.0_31/bin:/tmp/gbowyer/dbpedia-thing/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-7.0/bin:/usr/local/cuda-7.0/bin:/sbin:/usr/sbin:/tmp/gbowyer/.scripts:/sbin:/usr/sbin:/tmp/gbowyer/pkg/bin:/tmp/gbowyer/.scripts:/tmp/gbowyer/pkgs/bin \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote external/gemmlowp -iquote bazel-out/local_linux-opt/genfiles/external/gemmlowp -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.o' -MD -MF bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.d -c external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.cc -o bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.o): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /tmp/gbowyer/.cache/bazel/_bazel_gbowyer/d132132edbbae685571ab9488dabc906/tensorflow && \
  exec env - \
    PATH=/opt/java/jdk1.8.0_31/bin:/tmp/gbowyer/dbpedia-thing/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-7.0/bin:/usr/local/cuda-7.0/bin:/sbin:/usr/sbin:/tmp/gbowyer/.scripts:/sbin:/usr/sbin:/tmp/gbowyer/pkg/bin:/tmp/gbowyer/.scripts:/tmp/gbowyer/pkgs/bin \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote external/gemmlowp -iquote bazel-out/local_linux-opt/genfiles/external/gemmlowp -iquote external/bazel_tools -iquote bazel-out/local_linux-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.o' -MD -MF bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.d -c external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.cc -o bazel-out/local_linux-opt/bin/external/gemmlowp/_objs/eight_bit_int_gemm/external/gemmlowp/eight_bit_int_gemm/eight_bit_int_gemm.o).
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 1.907s, Critical Path: 1.27s
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $ third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc
gcc: fatal error: no input files
compilation terminated.
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $
```

---

Suggestion from Vijay Vasudevan is to use different bazel build params

> Can you try building with --spawn_strategy=standalone ?  After talking with the bazel folks it looks like the sandbox for some reason doesn't have the crosstool wrapper in the right location, so running in standalone mode might work better.

---

That yields this error
```
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $ bazel build --verbose_failures -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer --spawn_strategy=standalone
INFO: Found 1 target...
ERROR: /tmp/gbowyer/tensorflow/tensorflow/stream_executor/BUILD:5:1: undeclared inclusion(s) in rule '//tensorflow/stream_executor:stream_executor':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cuda_platform_id.cc':
  '/tmp/gbowyer/tensorflow/tensorflow/stream_executor/cuda/cuda_platform_id.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 2.893s, Critical Path: 2.64s
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $ bazel build --verbose_failures -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --spawn_strategy=standalone
INFO: Found 1 target...
ERROR: /tmp/gbowyer/tensorflow/tensorflow/core/BUILD:272:1: undeclared inclusion(s) in rule '//tensorflow/core:gpu_kernels':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/aggregate_ops_gpu.cu.cc':
  '/tmp/gbowyer/tensorflow/tensorflow/core/framework/tensor_types.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 38.609s, Critical Path: 37.67s
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $
```

---
Evgeny Shaliov notes that
> nvcc --version should return 6.5.* but CUDA toolkit should be installed 7.0. 
>
> I posted https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/jRkkvsB1iWA.
> Also pay attention what gcc version you use.
> 
> Best regards,
> Evgeny.

---

Vijay Vasudevan also remarks
> Yikes! :(
>
> What version of bazel do you happen to be using? 

And asks to move this to github issues, so here we are :P

**Comment by GregBowyer** [comment]
```sh
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(env)gbowyer@compute-10-3-61-179 ~/tensorflow $ bazel --version
Unknown Bazel startup option: '--version'.
  For more info, run 'blaze help startup_options'.
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $ bazel version
...............
Build label: head (@53f4076)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 9 16:34:56 2015 (1449678896)
Build timestamp: 1449678896
Build timestamp as int: 1449678896
(env)gbowyer@compute-10-3-61-179 ~/tensorflow $
```

I am going to see if changing bazel and nvcc helps, I will start with bazel first as I dont relish the idea of deploying older nvcc compilers.

**Comment by vrv** [comment]
Yeah, I think this is a bazel or tensorflow BUILD issue, not an nvcc one.

Can you try using bazel 0.1.1 or bazel 0.1.2?

@damienmg in case he has some ideas, since I can't reproduce this at HEAD with bazel 0.1.1

**Comment by dmitrychervov** [comment]
I'm not sure how related this is, but I had one of the abovementioned issues, "undeclared inclusions in rule ..stream_executor", with another GPU (K80), and downgrading from Bazel 0.1.2 to Bazel 0.1.1 helped.

**Comment by damienmg** [comment]
The include error should have been fixed with my changes but I may have missed some targets. We don't test all tensorflow targets on ci.bazel.io (we don't have GPU). The corresponding headers should be added in the TensorFlow's build files.

**Comment by vrv** [comment]
Thanks @damienmg, I'll try to get the fix in today.

**Comment by wchan** [comment]
can confirm this bug, just git cloned fresh from the tree using blaze 0.1.2, downgrading to blaze 0.1.1 fixes the problem.

**Comment by vrv** [comment]
I can't seem to reproduce this, either on my mac or on my linux machine, both pulling tensorflow from HEAD and installing bazel fresh from bazel.io for 0.1.2.

William: by any chance would you have time to figure out what the necessary changes are?  I'd be happy to integrate them.

**Comment by vrv** [comment]
Nevermind, it's the GPU only targets that are messed up.  no wonder.

**Comment by vrv** [comment]
okay, sort of fixed in https://github.com/tensorflow/tensorflow/commit/a4cefca9f40ae6cfe366b6187d07e5199aa74895

--standalone argument is still required.  Seems like it needs to be addressed by bazel team at https://github.com/bazelbuild/bazel/issues/698

**Comment by GregBowyer** [comment]
That fix seems to have cured it thanks

**Comment by gillhofer** [comment]
There may be a similar bug which still exists. Platform arch-linux
```
./configure
bazel build --jobs 2 --config=cuda --verbose_failures --spawn_strategy=standalone -c opt //tensorflow/tools/pip_package:build_pip_package
```

```
ERROR: $PARENT_DIR/src/tensorflow/tensorflow/stream_executor/BUILD:5:1: undeclared inclusion(s) in rule '//tensorflow/stream_executor:stream_executor':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cuda_dnn.cc':
  '/opt/cuda/include/cuda_runtime.h'
  '/opt/cuda/include/host_config.h'
  '/opt/cuda/include/builtin_types.h'
  '/opt/cuda/include/device_types.h'
  '/opt/cuda/include/host_defines.h'
  '/opt/cuda/include/driver_types.h'
  '/opt/cuda/include/surface_types.h'
  '/opt/cuda/include/texture_types.h'
  '/opt/cuda/include/vector_types.h'
  '/opt/cuda/include/channel_descriptor.h'
  '/opt/cuda/include/cuda_runtime_api.h'
  '/opt/cuda/include/cuda_device_runtime_api.h'
  '/opt/cuda/include/driver_functions.h'
  '/opt/cuda/include/vector_functions.h'
  '/opt/cuda/include/vector_functions.hpp'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by damienmg** [comment]
@lberki has a fix for this.

**Comment by vrv** [comment]
@damienmg: is this a fix to our BUILD rules?  We might have to update our jenkins gpu pip builder to 0.1.2 I guess.

@jendap: do you know which bazel we're using there?

**Comment by jendap** [comment]
@vrv it it not a problem in tensorflow BUILD files. It is in bazel (android rules). I have added you to cc on the fix @lberki has created.

It is happening with bazel 0.1.2 release which you can download from github (and bazel.io). IT was also happening on release 0.1.3 branch a couple of days ago. But we have a fix for it now. Just release it and we are good.

**Comment by jendap** [comment]
Actually I'm not sure about this GPU issue. We were talking with bazel team about something with android and 0.1.2 but it may be the same thing. I have tried myself 0.1.2 with android only. Not gpu yet. I will try it next week.

**Comment by frankyjuang** [comment]
I have a similar problem on Arch Linux, too.
Running
```
bazel build -c opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package
```
This error occurs
```
ERROR: /home/test/tensorflow/tensorflow/core/BUILD:213:1: undeclared inclusion(s) in rule '//tensorflow/core:gpu_runtime':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/common_runtime/gpu/gpu_device_factory.cc':
  '/opt/cuda/include/cuda_runtime.h'
  '/opt/cuda/include/host_config.h'
  '/opt/cuda/include/builtin_types.h'
  '/opt/cuda/include/device_types.h'
  '/opt/cuda/include/host_defines.h'
  '/opt/cuda/include/driver_types.h'
  '/opt/cuda/include/surface_types.h'
  '/opt/cuda/include/texture_types.h'
  '/opt/cuda/include/vector_types.h'
  '/opt/cuda/include/channel_descriptor.h'
  '/opt/cuda/include/cuda_runtime_api.h'
  '/opt/cuda/include/cuda_device_runtime_api.h'
  '/opt/cuda/include/driver_functions.h'
  '/opt/cuda/include/vector_functions.h'
  '/opt/cuda/include/vector_functions.hpp'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
Is there yet any solutions?

**Comment by wchan** [comment]
@frankyjuang, did u try downgrading bazel to 0.1.1?

**Comment by frankyjuang** [comment]
@wchan, downgrading to 0.1.1 works!!! Thanks a lot.

@gillhofer, Arch linux 4.3.3 with CUDA 7.0, gcc/g++ 4.9.3 and bazel 0.1.1 works. You can give it a try. Btw, I have nvidia gtx 660, so setting compute capability to 3.0 with
`$ TF_UNOFFICIAL_SETTING=1 ./configure` is needed.

**Comment by damienmg** [comment]
The include issue is due to https://github.com/bazelbuild/bazel/issues/714 (tl;dr: current workaround is to have a longer path for /opt/cuda).

**Comment by damienmg** [comment]
Note that today Bazel's release 0.1.3 should fix that error.

**Comment by frankyjuang** [comment]
@damienmg I tried the 0.1.3. However, this bug still exists...Any ideas?
Arch Linux with gcc 4.9.3
```
$ bazel build -c opt --config=cuda --verbose_failures --spawn_strategy=standalone //tensorflow/cc:tutorials_example_trainer
ERROR: /home/test/tensorflow/tensorflow/stream_executor/BUILD:5:1: undeclared inclusion(s) in rule '//tensorflow/stream_executor:stream_executor':
this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cuda_rng.cc':
  '/opt/cuda/include/cuda_runtime.h'
  '/opt/cuda/include/host_config.h'
  '/opt/cuda/include/builtin_types.h'
  '/opt/cuda/include/device_types.h'
  '/opt/cuda/include/driver_types.h'
  '/opt/cuda/include/surface_types.h'
  '/opt/cuda/include/texture_types.h'
  '/opt/cuda/include/vector_types.h'
  '/opt/cuda/include/channel_descriptor.h'
  '/opt/cuda/include/cuda_runtime_api.h'
  '/opt/cuda/include/host_defines.h'
  '/opt/cuda/include/cuda_device_runtime_api.h'
  '/opt/cuda/include/driver_functions.h'
  '/opt/cuda/include/vector_functions.h'
  '/opt/cuda/include/vector_functions.hpp'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
INFO: Elapsed time: 84.234s, Critical Path: 80.07s
```

**Comment by damienmg** [comment]
So the problem is that 0.1.3 fix the problem in our CROSSTOOL file. here the problems are in TensorFlow's cuda support.

The fix in Bazel was https://github.com/bazelbuild/bazel/commit/763f1397155fc7c12e1f1071a1bc942f91b867c4
So applying the same change to third_party/gpus/crosstool/CROSSTOOL should work, that is 
adding `unfiltered_cxx_flag: "-fno-canonical-system-headers` at https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/CROSSTOOL#L110

Hope that helps!

**Comment by frankyjuang** [comment]
@damienmg ,yes it works! thanks. But I encounter another problem with `crosstool_wrapper_driver_is_not_gcc`. I had tried bazel 0.1.0, 0.1.1, 0.1.2, 0.1.3. It just can't work...
```
ERROR: /home/test/tensorflow/tensorflow/python/BUILD:71:1: C++ compilation of rule '//tensorflow/python:py_func_lib' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/test/.cache/bazel/_bazel_test/3a51eda24c560ebddf29b66b8fa0460e/tensorflow && \
  exec env - \
    INTERCEPT_LOCALLY_EXECUTABLE=1 \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-ndk:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/test/bazel/output \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-py3-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-py3-opt/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-5651786d5e59 -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive/eigen-eigen-5651786d5e59 -isystem third_party/py/numpy/numpy_include -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/py/numpy/numpy_include -isystem util/python/python_include -isystem bazel-out/local_linux-py3-opt/genfiles/util/python/python_include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.o' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.d -fPIC -c tensorflow/python/lib/core/py_func.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: crosstool_wrapper_driver_is_not_gcc failed: error executing command                                                                                       (cd /home/test/.cache/bazel/_bazel_test/3a51eda24c560ebddf29b66b8fa0460e/tensorflow && \                                                                                      exec env - \                                                                                                                                                                    INTERCEPT_LOCALLY_EXECUTABLE=1 \                                                                                                                                              PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-ndk:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/test/bazel/output \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-py3-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-py3-opt/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-5651786d5e59 -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive/eigen-eigen-5651786d5e59 -isystem third_party/py/numpy/numpy_include -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/py/numpy/numpy_include -isystem util/python/python_include -isystem bazel-out/local_linux-py3-opt/genfiles/util/python/python_include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.o' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.d -fPIC -c tensorflow/python/lib/core/py_func.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 170.105s, Critical Path: 121.60s
```

**Comment by damienmg** [comment]
You should see the error from the script itself a few lines before the ERROR: line.

**Comment by vrv** [comment]
Fixed in the above commit, we believe.

**Comment by pragmascript** [comment]
i have a similar issue compiling current master with bazel 2 compute capability 3.0 and cuda 7.5 :
```
ERROR: /home/pragma/tensorflow/tensorflow/core/kernels/BUILD:685:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:conv_ops':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/conv_ops.cc':
  '/home/pragma/tensorflow/tensorflow/core/common_runtime/gpu_device_context.h'
  '/home/pragma/tensorflow/tensorflow/core/common_runtime/device.h'
  '/home/pragma/tensorflow/tensorflow/core/graph/graph.h'
  '/home/pragma/tensorflow/tensorflow/core/graph/edgeset.h'
  '/home/pragma/tensorflow/tensorflow/core/graph/types.h'.
In file included from external/eigen_archive/eigen-eigen-ed4c9730b545/unsupported/Eigen/CXX11/Core:35:0,
                 from external/eigen_archive/eigen-eigen-ed4c9730b545/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/framework/types.h:23,
                 from ./tensorflow/core/framework/type_traits.h:22,
                 from ./tensorflow/core/framework/allocator.h:25,
                 from ./tensorflow/core/framework/op_kernel.h:22,
                 from ./tensorflow/core/framework/numeric_op.h:19,
                 from tensorflow/core/kernels/conv_ops.cc:22:
external/eigen_archive/eigen-eigen-ed4c9730b545/unsupported/Eigen/CXX11/src/Core/util/EmulateArray.h: In static member function 'static void Eigen::internal::TensorExecutor<Expression, Eigen::ThreadPoolDevice, Vectorizable>::run(const Expression&, const Eigen::ThreadPoolDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 2, 1, long int>, 16>, const Eigen::TensorContractionOp<const Eigen::array<Eigen::IndexPair<long int>, 1ul>, const Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long int>, 16>, const Eigen::TensorMap<Eigen::Tensor<const float, 2, 1, long int>, 16> > >; bool Vectorizable = true]':
external/eigen_archive/eigen-eigen-ed4c9730b545/unsupported/Eigen/CXX11/src/Core/util/EmulateArray.h:24:67: warning: array subscript is above array bounds [-Warray-bounds]
   EIGEN_STRONG_INLINE T& operator[] (size_t index) { return values[index]; }
                                                                   ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 138.998s, Critical Path: 137.36s

```

**Comment by vrv** [comment]
Yep, the build is broken at the moment -- we have a fix we're trying to push through.

**Comment by esd100** [comment]
Similar problem ... C++ compilation of rule '//tensorflow/stream_executor:stream_executor' failed: gcc failed: error executing command

**Comment by noisychannel** [comment]
FYI : I was able to build the GPU pip package using the changes listed in this install script : https://github.com/noisychannel/tensorflow_install/blob/master/tf_install.sh

Specifically, check the function fix_tf which makes changes in third_party/gpus/crosstool/CROSSTOOL, tensorflow/tensorflow.bzl and tensorflow/stream_executor/BUILD.
