### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects when using multiprocessing

### ISSUE THREAD

**Issue by asokraju** [tensorflow/tensorflow#46917]
Information:

```
Tensorflow version 2.1.0
Python 3.7
```
The minimal example to reproduce the error:

```
import tensorflow as tf
from tensorflow import keras
import numpy as np


from multiprocessing import Pool
from multiprocessing.dummy import Pool as ThreadPool
from functools import partial

def simple_model():
    model = keras.models.Sequential([
        keras.layers.Dense(units = 10, input_shape = [1]),
        keras.layers.Dense(units = 1, activation = 'sigmoid')
    ])
    model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
    return model

def clone_model(model):
    model_clone = tf.keras.models.clone_model(model)
    model_clone.set_weights(model.get_weights())
    return model_clone

def work(model, seq):
    return model.predict(seq)
    
def worker(model, n = 4):
    seqences = np.arange(0,100).reshape(n, -1)
    pool = Pool()
    # model_list = [clone_model(model) for _ in range(n)]
    # results = pool.map(work, zip(model_list,seqences))
    partial_work = partial(work, model=model)
    results = pool.map(partial_work, seqences)
    pool.close()
    pool.join()
    
    return np.reshape(results, (-1, ))



if __name__ == '__main__':
    model = simple_model()
    out = worker(model, n=4)
    print(out)
```

gives the following error trace:
```
Traceback (most recent call last):
  File "c:/****/test4.py", line 43, in <module>
    out = worker(model, n=4)
  File "c:/****/test4.py", line 33, in worker
    results = pool.map(partial_work, seqences)
  File "C:\***\anaconda3\envs\tf-gpu\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\***\anaconda3\envs\tf-gpu\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\***\anaconda3\envs\tf-gpu\lib\multiprocessing\pool.py", line 431, in _handle_tasks
    put(task)
  File "C:\***\anaconda3\envs\tf-gpu\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\***\anaconda3\envs\tf-gpu\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects
```

**Comment by amahendrakar** [comment]
@asokraju,
This issue has already been addressed by a member of the TensorFlow team.

Please take a look at this comment from similar issue [#46316](https://github.com/tensorflow/tensorflow/issues/46316#issuecomment-760339753) for more information. 

> Keras models are not multiprocessing-safe. I recommend simply creating multiple independent copies of your model for use in each process.

Thanks!

**Comment by asokraju** [comment]
Hi, I made independent copies of each.
```
def clone_model(model):
    model_clone = tf.keras.models.clone_model(model)
    model_clone.set_weights(model.get_weights())
    return model_clone
```
But the error still persists.

**Comment by asokraju** [comment]
I cloned the list of these models for each process. But the error still remains the same. Full code and the error trace.
```
import tensorflow as tf
from tensorflow import keras
import numpy as np


from multiprocessing import Pool
from multiprocessing.dummy import Pool as ThreadPool
from functools import partial

def simple_model():
    model = keras.models.Sequential([
        keras.layers.Dense(units = 10, input_shape = [1]),
        keras.layers.Dense(units = 1, activation = 'sigmoid')
    ])
    model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
    return model

def clone_model(model):
    model_clone = tf.keras.models.clone_model(model)
    model_clone.set_weights(model.get_weights())
    return model_clone

def work(model, seq):
    return model.predict(seq)

def worker(model, n = 4):
    seqences = np.arange(0,100).reshape(n, -1)
    pool = Pool()
    model_list = [clone_model(model) for _ in range(n)]
    results = pool.map(work, zip(model_list,seqences))
    # partial_work = partial(work, model=model)
    # results = pool.map(partial_work, seqences)
    pool.close()
    pool.join()
    
    return np.reshape(results, (-1, ))



if __name__ == '__main__':
    model = simple_model()
    out = worker(model, n=4)
    print(out)

```

Error trace:
  ```
File "c:/Users/***/Documents/GitHub/COVID-NSF/test4.py", line 42, in <module>
    out = worker(model, n=4)
  File "c:/Users/****/Documents/GitHub/COVID-NSF/test4.py", line 30, in worker
    results = pool.map(work, zip(model_list,seqences))
  File "C:\Users\****\anaconda3\envs\tf-gpu\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\****\anaconda3\envs\tf-gpu\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "C:\Users\***\anaconda3\envs\tf-gpu\lib\multiprocessing\pool.py", line 431, in _handle_tasks
    put(task)
  File "C:\Users\***\anaconda3\envs\tf-gpu\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\***\anaconda3\envs\tf-gpu\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

```

The root cause of the error might be different.

**Comment by asokraju** [comment]
Alternatively, I have tried saving the model and loading it to multiple independent copies. It still does not work

```
def load_model(model_savepath):
    return tf.keras.models.load_model(model_savepath)

def worker(model, n = 4):
    seqences = np.arange(0,100).reshape(n, -1)
    pool = Pool()
    model_savepath = './simple_model.h5'
    model.save(model_savepath)
    model_list = [load_model(model_savepath) for _ in range(n)]
    # model_list = [clone_model(model) for _ in range(n)]
    results = pool.map(work, zip(model_list,seqences))
    # partial_work = partial(work, model=model)
    # results = pool.map(partial_work, seqences)
    pool.close()
    pool.join()
    
    return np.reshape(results, (-1, ))

```

**Comment by asokraju** [comment]
I asked the question here. @amahendrakar following your suggestion I modified the code such that the code sends the path of the model, rather than the model itself, to the child processes. Below is the working code
```

import tensorflow as tf
from tensorflow import keras
import numpy as np


# from multiprocessing import Pool
from multiprocessing.dummy import Pool as ThreadPool
from pathos.multiprocessing import ProcessingPool as Pool
from functools import partial
import time

def simple_model():
    model = keras.models.Sequential([
        keras.layers.Dense(units = 10, input_shape = [1]),
        keras.layers.Dense(units = 1, activation = 'sigmoid')
    ])
    model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
    return model

def clone_model(model):
    model_clone = tf.keras.models.clone_model(model)
    model_clone.set_weights(model.get_weights())
    model_clone.build((None, 1))
    model_clone.compile(optimizer = 'sgd', loss = 'mean_squared_error')
    return model_clone

def work(model, seq):
    return model.predict(seq)

def work_new(seq):
    model_savepath = './simple_model.h5'
    model = tf.keras.models.load_model(model_savepath)
    return model.predict(seq)

def load_model(model_savepath):
    return tf.keras.models.load_model(model_savepath)

def worker(model, n = 4):
    seqences = np.arange(0,10*n).reshape(n, -1)
    pool = Pool()
    model_savepath = './simple_model.h5'
    model.save(model_savepath)
    # model_list = [load_model(model_savepath) for _ in range(n)]
    # model_list = [clone_model(model) for _ in range(n)]
    # results = pool.map(work, zip(model_list,seqences))
    # path_list = [[model_savepath] for _ in range(n)]
    # print(np.shape(path_list), np.shape(seqences))
    # work_new_partial = partial(work_new, path=model_savepath)
    results = pool.map(work_new,  seqences)
    # partial_work = partial(work, model=model)
    # results = pool.map(partial_work, seqences)
    pool.close()
    pool.join()
    # print(t1-t0)
    return np.reshape(results, (-1, ))



if __name__ == '__main__':

    model = simple_model()
    t0 = time.perf_counter()
    out = worker(model, n=40)
    t1 = time.perf_counter()

    # print(out)
    print(f"time taken {t1 - t0}")
```

**Comment by asokraju** [comment]
When I was running the above code in windows using anaconda, the code works fine ( I checked with every 2.x version). However, when I try it on ubuntu it gives me an issue. I reported here: https://github.com/tensorflow/tensorflow/issues/47275

The package I am using in anaconda windows are:

```
name: tf-gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.11.0=py37haa95532_0
  - aiohttp=3.6.3=py37he774522_0
  - astor=0.8.1=py37_0
  - async-timeout=3.0.1=py37_0
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37he774522_1000
  - ca-certificates=2021.1.19=haa95532_0
  - cachetools=4.1.1=py_0
  - certifi=2020.12.5=py37haa95532_0
  - cffi=1.14.3=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - colorama=0.4.4=py_0
  - cryptography=3.1.1=py37h7a1dbc1_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cudnn=7.6.5=cuda10.1_0
  - cycler=0.10.0=py37_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.3.3=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - freetype=2.10.4=hd328e21_0
  - gast=0.2.2=py37_0
  - google-auth=1.23.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.31.0=py37he7da953_0
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.2=py37_0
  - jinja2=2.11.2=py_0
  - joblib=0.17.0=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab_pygments=0.1.2=py_0
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.3.0=py37hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.13.0.1=h200bbdf_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.2=hf4a77e7_3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.2=py37_0
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py37hba9282a_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.2.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - multidict=4.7.6=py37he774522_1
  - multiprocess=0.70.11.1=py37hcc03f2d_1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.8=py_0
  - notebook=5.7.4=py37_0
  - numpy=1.19.2=py37hadc3359_0
  - numpy-base=1.19.2=py37ha3acd2a_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1i=h2bbff1b_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.4=py_0
  - pandas=1.1.3=py37ha925a31_0
  - pandoc=2.11=h9490d1a_0
  - pathos=0.2.7=pyhd3deb0d_0
  - pickleshare=0.7.5=py37_1001
  - pillow=8.0.1=py37h4fa10fc_0
  - pip=20.2.4=py37haa95532_0
  - pox=0.2.9=pyhd3deb0d_0
  - ppft=1.6.6.3=pyhd3deb0d_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - protobuf=3.13.0.1=py37ha925a31_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pygments=2.7.2=pyhd3eb1b0_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - pyrsistent=0.17.3=py37he774522_0
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.3.1=py37he774522_1
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scikit-learn=0.23.2=py37h47e9c7a_0
  - scipy=1.5.2=py37h9439919_0
  - seaborn=0.11.0=py_0
  - send2trash=1.5.0=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - tensorboard=2.3.0=pyh4dce500_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.1.0=gpu_py37h7db9008_0
  - tensorflow-base=2.1.0=gpu_py37h55f5790_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - tensorflow-gpu=2.1.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - terminado=0.9.1=py37_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=he774522_0
  - tornado=5.1.1=py37hfa6e2cd_0
  - tqdm=4.56.0=pyhd3eb1b0_0
  - urllib3=1.25.11=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=py_0
  - werkzeug=0.16.1=py_0
  - wheel=0.35.1=py_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py37he774522_1
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yarl=1.6.2=py37he774522_0
  - zeromq=4.3.2=ha925a31_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - cloudpickle==1.6.0
    - future==0.18.2
    - gym==0.17.3
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - json5==0.9.5
    - jupyterlab==2.2.9
    - jupyterlab-server==1.2.0
    - nest-asyncio==1.4.2
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pyglet==1.5.0
    - pywin32==228
    - pyzmq==19.0.2
    - setuptools==50.3.2
    - traitlets==4.3.3
    - webencodings==0.5.1
prefix: C:\Users\kkris\anaconda3\envs\tf-gpu

```
