### ISSUE TITLE
Failed to deploy custom Tensorflow lite select ops .aar to Android

### ISSUE THREAD

**Issue by barrypitman** [tensorflow/tensorflow#46989]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Huawei P30 Lite
- TensorFlow installed from (source or binary): Source
- TensorFlow version: master - 2.4.1+
- Python version: 3.6.9
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CUDA/cuDNN version:
- GPU model and memory:

I have followed the instructions here: https://www.tensorflow.org/lite/guide/build_android and here: https://www.tensorflow.org/lite/guide/reduce_binary_size to build custom versions of tensorflow-lite.aar and tensorflow-lite-select-tf-ops.aar. However, when I try to run the model on Android, I get this error:

```
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
      java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6tflite3ops6custom38Register_TFLITE_DETECTION_POST_PROCESSEv" referenced by "/data/app/com.example.myapplication-2NF_GHdjAnMJHFkmSCcPvw==/lib/arm64/libtensorflowlite_jni.so"...
        at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:80)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:26)
```

This appears to be happening before loading the model, it seems to be a linking issue, though I have just build the two .aar files from source.

Steps followed:

I'm using Docker to build the aar files. I downloaded the Docker file from [here](https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/dockerfiles/tflite-android.Dockerfile) and ran:
`docker build . -t tflite-builder -f tflite-android.Dockerfile`
followed by:
`docker run -it -v "local_dir":/host_dir tflite-builder bash`

Inside the docker container, I ran:
`curl -o build_aar_with_docker.sh   https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/lite/tools/build_aar_with_docker.sh &&   chmod +x build_aar_with_docker.sh`

followed by:
`echo y | /bin/bash build_aar_with_docker.sh --input_models=/host_dir/my_model.tflite   --target_archs=arm64-v8a,armeabi-v7a   --checkpoint=master `

My model is defined (here)[https://github.com/barrypitman/tensorflow_LPRnet] and uses 1 custom op - ctc_beam_search_decoder. 

After several hours, the build finished with this message:
```
INFO: Analyzed target //tmp:tensorflow-lite-select-tf-ops (308 packages loaded, 33657 targets configured).
INFO: Found 1 target...
Target //tmp:tensorflow-lite-select-tf-ops up-to-date:
  bazel-bin/tmp/tensorflow-lite-select-tf-ops.aar
INFO: Elapsed time: 35622.438s, Critical Path: 3942.80s
INFO: 14237 processes: 861 internal, 13376 local.
INFO: Build completed successfully, 14237 total actions
Output can be found here:
tensorflow-lite.aar
tensorflow-lite-select-tf-ops.aar
```

I copied the tensorflow-lite.aar and tensorflow-lite-select-tf-ops.aar files into a sample Android application (attached), and I got the above-mentioned error:
```
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
      java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6tflite3ops6custom38Register_TFLITE_DETECTION_POST_PROCESSEv" referenced by "/data/app/com.example.myapplication-2NF_GHdjAnMJHFkmSCcPvw==/lib/arm64/libtensorflowlite_jni.so"...
```

I've tried generating the tensorflow-lite-select-tf-ops.aar file against the 2.4.0 and 2.4.1 branches, but I'm getting similar errors. This issue appears to be similar to [45153](https://github.com/tensorflow/tensorflow/issues/45153). 

I built the two .aar files against the following tensorflow commit:
```
root@8eb4e1fb67bf:/tensorflow_src# git rev-parse HEAD
6ac306c372287e522168da6931fd751203915d46
```

I've attached the two .aar files as well as the demo Android app. I haven't included the model, because the app is crashing before trying to load the model.
[tensorflow-lite-master-20210207-docker.zip](https://github.com/tensorflow/tensorflow/files/5939881/tensorflow-lite-master-20210207-docker.zip)
[AndroidHelloWorld.zip](https://github.com/tensorflow/tensorflow/files/5939884/AndroidHelloWorld.zip)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ojj11** [comment]
Copy & pasting my comment from 45153 in case this solves your problem too: I found that I had to add `build --config=monolithic` to `.bazelrc` to avoid the `_ZNK6google8protobuf7Message11GetTypeNameEv` error.

**Comment by farmaker47** [comment]
@ojj11 Please point where exactly is .bazelrc file??

**Comment by farmaker47** [comment]
@ojj11 Is this the file? https://github.com/tensorflow/tensorflow/blob/master/.bazelrc
Please point out in what line do we have to insert your suggestion?

**Comment by barrypitman** [comment]
> Copy & pasting my comment from 45153 in case this solves your problem too: I found that I had to add `build --config=monolithic` to `.bazelrc` to avoid the `_ZNK6google8protobuf7Message11GetTypeNameEv` error.

Thank you - this has helped, I added the option as you suggested, `echo -n "build --config=monolithic" >> /tensorflow_src/.bazelrc`

My original issue - 
```dlopen failed: cannot locate symbol "_ZN6tflite3ops6custom38Register_TFLITE_DETECTION_POST_PROCESSEv" referenced by "/data/app/com.example.myapplication-2NF_GHdjAnMJHFkmSCcPvw==/lib/arm64/libtensorflowlite_jni.so"```. 
is still happening. This happens when I try to use both the custom `tensorflow-lite.aar` (1.3MB) and `tensorflow-lite-select-tf-ops.aar` (4.4MB) files. It seems that the built libtensorflowlite_jni.so is missing some dependencies, even when built using the monolithic option.

However, if I try to use the custom `tensorflow-lite-select-tf-ops.aar` file with the vanilla `tensorflow-lite-2.4.0.aar` that I downloaded from e.g. jcenter, then its working. Thanks for the suggestion!

**Comment by miaout17** [comment]
Update: I sent a pull request to update `build_aar.sh`. If you're using this script, you should no longer require the `build --config=monolithic` change in `.bazelrc`.

**Comment by thaink** [comment]
> > Copy & pasting my comment from 45153 in case this solves your problem too: I found that I had to add `build --config=monolithic` to `.bazelrc` to avoid the `_ZNK6google8protobuf7Message11GetTypeNameEv` error.
> 
> Thank you - this has helped, I added the option as you suggested, `echo -n "build --config=monolithic" >> /tensorflow_src/.bazelrc`
> 
> My original issue -
> `dlopen failed: cannot locate symbol "_ZN6tflite3ops6custom38Register_TFLITE_DETECTION_POST_PROCESSEv" referenced by "/data/app/com.example.myapplication-2NF_GHdjAnMJHFkmSCcPvw==/lib/arm64/libtensorflowlite_jni.so"`.
> is still happening. This happens when I try to use both the custom `tensorflow-lite.aar` (1.3MB) and `tensorflow-lite-select-tf-ops.aar` (4.4MB) files. It seems that the built libtensorflowlite_jni.so is missing some dependencies, even when built using the monolithic option.
> 
> However, if I try to use the custom `tensorflow-lite-select-tf-ops.aar` file with the vanilla `tensorflow-lite-2.4.0.aar` that I downloaded from e.g. jcenter, then its working. Thanks for the suggestion!

Can you share the model? I took a look at your model in AndroidHelloWorld.zip. But the model does not contain DetectionPostProcess custom op.

**Comment by thaink** [comment]
Commit fc85b2000383b09cbe40e3f2565f0b0c1a1cee53 should fix this error.

**Comment by barrypitman** [comment]
Thank you @thaink , I can confirm that the custom build is working using both the custom tensorflow-lite.aar and tensorflow-lite-select-tf-ops.aar files.

**Comment by malik-anhar** [comment]
Hi @thaink , I am still getting this error after adding ```implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'``` dependency on my android project. The following are the error logs:
```
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: Node number 65 (FlexSize) failed to prepare.
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: Node number 65 (FlexSize) failed to prepare.
04-14 09:18:33.912 8903-8903/com.example.posm W/System.err: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before infer
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(Native Method)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:204)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:378)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.yolo.Yolo.predict(Yolo.java:71)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.POSM.predict(POSM.java:45)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.MainActivity.run_posm(MainActivity.java:110)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.MainActivity.lambda$onCreate$1$MainActivity(MainActivity.java:75)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.example.posm.-$$Lambda$MainActivity$w2a9VvlIKLLPHcyHZBUHuFlJhQA.onClick(lambda)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at android.view.View.performClick(View.java:4640)
04-14 09:18:33.942 8903-8903/com.example.posm W/System.err:     at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.view.View$PerformClick.run(View.java:19431)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.os.Looper.loop(Looper.java:146)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5598)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
04-14 09:18:33.952 8903-8903/com.example.posm W/System.err:     at dalvik.system.NativeStart.main(Native Method)
04-14 09:18:33.952 8903-8903/com.example.posm E/ERROR: Exception java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 65 (FlexSize) failed to prepare.
    
    Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
    Node number 65 (FlexSize) failed to prepare.
    
    Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before infer
```
The error happened in Android Kitkat 4.4 (API 19), but on my Android 10 (API 29) and Android 5.0 (API 21) it working correctly. Am I missing something?

**Comment by thaink** [comment]
@malik-anhar Can you file a new issue and cc me?
Your issue is different that this one.
