### ISSUE TITLE
XLA experimental_compile=True fails inside tf.data.Dataset

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#47599]
The `experimental_compile=True` option for `tf.function` works outside of a tf.data Dataset, but fails once I try to map it over a dataset.

```python
import tensorflow as tf

def log10(x):
    numerator = tf.math.log(x)
    denominator = tf.math.log(tf.constant(10, dtype=numerator.dtype))
    return numerator / denominator

@tf.function(experimental_compile=True)
def drc(
    inputs,
    threshold=-36.0,
    release_time=80.0,
    ratio=8.0,
    makeup_gain=0.0,
    sample_rate=44100,
):
    # downmix
    buffer = tf.reduce_mean(inputs, axis=1, keepdims=True)
    alpha_release = tf.exp(-1 / (0.001 * sample_rate * release_time))

    y_prev = tf.constant([0.0], dtype=tf.float32)
    length = tf.shape(inputs)[0]
    c = tf.TensorArray(
        dtype=tf.float32,
        size=length,
        element_shape=[1,]
    )

    for i in tf.range(length):
        if tf.abs(buffer[i]) < 0.000001:
            x_g = tf.constant([-120.0], dtype=tf.float32)
        else:
            x_g = tf.multiply(20.0, log10(tf.abs(buffer[i])))

        if x_g > threshold:
            y_g = tf.add(threshold, tf.divide(tf.subtract(buffer[i], threshold), ratio))
        else:
            y_g = x_g

        x_l = tf.subtract(x_g, y_g)

        y_l = tf.add(
            tf.multiply(alpha_release, y_prev), tf.multiply(tf.subtract(1.0, alpha_release), x_l)
        )
        y_l = tf.math.pow(10.0, (makeup_gain - y_l) / 20.0)
        c = c.write(i, y_l)
        y_prev = y_l

    out = c.stack()
    return tf.stack([signal[:, 0] * tf.squeeze(out), signal[:, 1] * tf.squeeze(out)], axis=-1)

signal = tf.random.normal((100000, 2), dtype=tf.float32)
out_tf = drc(signal)  # works

ds = tf.data.Dataset.from_tensor_slices([signal])
ds = ds.map(drc).batch(5)
for b in ds:
  print(b)  # Fails
```
I get the following error:

```
InvalidArgumentError: Function invoked by the following node is not compilable: {{node PartitionedCall}} = PartitionedCall[Tin=[DT_FLOAT, DT_FLOAT], Tout=[DT_FLOAT], _XlaHasReferenceVars=false, _XlaMustCompile=true, _collective_manager_ids=[], _input_hostmem=[], _read_only_resource_inputs=[], config="", config_proto="\n\007\n\003CPU\020\001\n\007\n\003GPU\020\0002\002J\0008\001\202\001\000", executor_type="", f=__inference_drc_250598[], _device="/job:localhost/replica:0/task:0/device:CPU:0"](args_0, unknown).
Uncompilable nodes:
PartitionedCall: could not instantiate call: '__inference_drc_250598'
	Stacktrace:
		Node: PartitionedCall, function: 

	 [[PartitionedCall]] [Op:MakeIterator]
```

It works as expected if I set experimental_compile to False. I'm using tensorflow 2.4.0.

**Comment by Saduf2019** [comment]
@lminer 
I ran the code shared and face a different error,please find the [gist here](https://colab.research.google.com/gist/Saduf2019/ed83ba0196042a2cef91f31ec5754f9e/untitled559.ipynb) and share all dependencies such that we can replicate the error reported.

you may also refer to these links and let us know if it helps, [link](https://github.com/tensorflow/tensorflow/issues/47211#issuecomment-783603301), #39852

**Comment by lminer** [comment]
@Saduf2019 sorry there was a function missing. Just added it.

**Comment by Saduf2019** [comment]
@lminer
Glad the issue is resolved, can you please move this to closed status.

**Comment by lminer** [comment]
@Saduf2019 it is not resolved. The error is exactly as I reported it. I just needed to add that function to get the correct error.

**Comment by Saduf2019** [comment]
I ama ble to replicate this in tf 2.3, tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b55da8652e148ea3f3998f9158b20149/untitled560.ipynb).

**Comment by lminer** [comment]
@aaudiber any idea on how to fix this?

**Comment by aaudiber** [comment]
Sorry, not familiar with experimental_compile. Reassigning to @cheshire who may have more insight about what causes the error.

**Comment by cheshire** [comment]
Seems the custom cache used by tf.data does not work with jit-compiled functions. Tracking internally in b/183061735

**Comment by lminer** [comment]
@cheshire  is there any workaround?

**Comment by cheshire** [comment]
Actually this works with latest tf-nightly. Just checked using the colab link above.

**Comment by cheshire** [comment]
Closing as "fixed in nightly".
