### ISSUE TITLE
 Error printed when calling tf.data.experimental.load

### ISSUE THREAD

**Issue by TimCargan** [tensorflow/tensorflow#48704]
**System information**
- OS Platform:  WSL2 Linux Ubuntu 20.04
- TensorFlow version: 2.5.0-rc1
- Python version: 3.9
- CUDA/cuDNN version: 11.2 
- GPU model and memory: RTX 3090

**Describe the current behavior**

When calling ` tf.data.experimental.load` the bellow error is printed, however, the dataset appears to load without issue

`Unimplemented: Cannot merge options for dataset of type LoadDataset, because the dataset does not implement 'InputDatasets'.`

**Describe the expected behavior**

No error message should be printed

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

ds = tf.data.Dataset.from_tensor_slices([1, 2, 3])
for i in ds:
    print(i)

tf.data.experimental.save(ds, "/mnt/d/load_issue.dataset", compression="GZIP")
load_ds = tf.data.experimental.load("/mnt/d/load_issue.dataset", compression="GZIP")

for e in load_ds:
    print(e)
```

**Comment by bhack** [comment]
It is solved on master. Can you try with `pip install tf-nightly-cpu`? Thanks

**Comment by TimCargan** [comment]
@bhack, ahh looks like It's fixed in the nightly builds. I will close the issue!

**Comment by jamesmishra** [comment]
Did the fix actually land in the TensorFlow 2.5.0 stable?

I'm still experiencing this error message with TensorFlow. It looks like [the commit solving the problem](https://github.com/tensorflow/tensorflow/commit/d96b20aa303b9a90d407cd80b94288626bd8e22e) missed the v2.5.0 release and landed in v2.6.0-rc0.

Would it be possible to cherry-pick the commit into a patch release for the 2.5.x branch?

**Comment by bhack** [comment]
Patch releases are only for security issues.
