### ISSUE TITLE
TensorRT Converter *Core Dumped*

### ISSUE THREAD

**Issue by tdrvlad** [tensorflow/tensorflow#50417]
**System information**
`tensorflow:2.5.0-gpu` base Docker container

**Describe the current behavior**
Execution is aborted (attached image)
<img width="603" alt="Capture" src="https://user-images.githubusercontent.com/45488144/123081935-2be25b80-d427-11eb-8952-2afa8e5475c2.PNG">

**Describe the expected behavior**
Performed a successful model conversion 2 weeks ago with the same script.

**Standalone code to reproduce the issue**
```
        converter = trt.TrtGraphConverterV2(
            input_saved_model_dir = self.model_dir)
        converter.convert()

        saved_model_dir_trt = os.path.join(self.model_dir, self.model_id + '_trt')
        converter.save(saved_model_dir_trt)
```

**Comment by sanjoy** [comment]
@pkanwar23 is this the same `LD_LIBRARY_PATH` issue we've seen elsewhere?

**Comment by pkanwar23** [comment]
Yes- same issue. This should be fixed soon.

**Comment by rpytel1** [comment]
@pkanwar23 Any update on that, bc for my recently downloaded image it was still not working.
It works for image: ``nvcr.io/nvidia/tensorflow:21.07-tf2-py3`` while it crashes for:
- ``tensorflow/tensorflow:2.5.0-gpu-jupyter``
- ``tensorflow/tensorflow:2.5.1-gpu-jupyter``
- ``tensorflow/tensorflow:2.6.0-gpu-jupyter``

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
