### ISSUE TITLE
Grappler error when Softmax input has a variable dimension

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/tensorflow#50575]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: 2.5.0
- Python version: 3.6.9
- CUDA/cuDNN version: 11.2/8.1.0
- GPU model and memory: NVIDIA Quadro P620 (4GB)

**Describe the current behavior**

The grappler pass is logging an error when Softmax is used in a `tf.function` with one or more variable dimensions (e.g. a variable batch size). This log started appearing in TensorFlow 2.5.

It does not seem to cause issues when running the model, but it might indicate a bug in the grappler implementation.

**Describe the expected behavior**

This operation should not produce any warning or error.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? No
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

```python
import tensorflow as tf

input_signature = (tf.TensorSpec([None, 20], tf.float32),)
softmax = tf.function(tf.nn.softmax, input_signature=input_signature)
softmax(tf.random.uniform([2, 20]))
```

**Other info / logs**

The code above logs the following error:

> `2021-07-02 07:34:12.478300: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "GPU" vendor: "NVIDIA" model: "Quadro P620" frequency: 1442 num_cores: 4 environment { key: "architecture" value: "6.1" } environment { key: "cuda" value: "11020" } environment { key: "cudnn" value: "8100" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 524288 shared_memory_size_per_multiprocessor: 98304 memory_size: 3092316160 bandwidth: 96128000 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }`

**Comment by saikumarchalla** [comment]
@guillaumekln  The code snippet doesn't logging any warnings and resulting the output as expected on colab with TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/37906ae3ba15f17d11ad5ced51062a4d/untitled107.ipynb).Thanks!

**Comment by guillaumekln** [comment]
Google Colab discards the C++ logs by default. You can run the code this way to see the logs:

> `!python3 -c 'import tensorflow as tf; input_signature = (tf.TensorSpec([None, 20], tf.float32),); softmax = tf.function(tf.nn.softmax, input_signature=input_signature); softmax(tf.random.uniform([2, 20]))'`

Also make sure to enable the GPU backend in your Colab session. Here's the [gist](https://colab.research.google.com/drive/18tXO7yY3rg7EagyK9weHbl4v1bZH38cv) (see the last line in the log).

**Comment by Ghostvv** [comment]
I experience the same error when using models with attention

**Comment by Saduf2019** [comment]
@guillaumekln 
I ran the code shared by you on gpu, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/e9d8127e49e51eff41b739551769cfd4/untitled616.ipynb).

**Comment by guillaumekln** [comment]
Please see this comment to make the C++ log visible: https://github.com/tensorflow/tensorflow/issues/50575#issuecomment-875291904. It links to a [gist](https://colab.research.google.com/drive/18tXO7yY3rg7EagyK9weHbl4v1bZH38cv) that contains the full log output.

**Comment by guillaumekln** [comment]
@jvishnuvardhan Do you need additional information?

**Comment by fperezgamonal** [comment]
Hello,

I get the same warning in my code (input shape to Softmax is `None, 4` as I have 4 output classes). 
![image](https://user-images.githubusercontent.com/19503950/132494782-b21aea07-0510-4de9-9cda-9c815c7d5c83.png)

I can also reproduce it by running the Google Colab mentioned before:
```
2021-09-08 10:31:23.096121: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-08 10:31:23.753820: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-08 10:31:23.754712: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-08 10:31:23.756322: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-08 10:31:23.757138: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-08 10:31:23.757957: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-08 10:31:28.734107: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-08 10:31:28.735007: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-08 10:31:28.735830: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-08 10:31:28.736521: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2021-09-08 10:31:28.736725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10819 MB memory:  -> device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7
2021-09-08 10:31:28.844194: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2021-09-08 10:31:28.936181: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla K80" frequency: 823 num_cores: 13 environment { key: "architecture" value: "3.7" } environment { key: "cuda" value: "11000" } environment { key: "cudnn" value: "8004" } num_registers: 131072 l1_cache_size: 16384 l2_cache_size: 1572864 shared_memory_size_per_multiprocessor: 114688 memory_size: 11345264640 bandwidth: 240480000 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }
```

Being a warning, do we know if we should worry about it?

Thanks for the help!

**Comment by ailton-felix** [comment]
Hello, 

any news about Softmax `warning`? I'm curious if it affects a model's performance. I also got the warning after upgrading the tensorflow version from 2.2 to 2.6

```2021-10-05 13:25:23.086323: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "CPU" vendor: "GenuineIntel" model: "110" frequency: 2499 num_cores: 4 environment { key: "cpu_instruction_set" value: "AVX SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2" } environment { key: "eigen" value: "3.3.90" } l1_cache_size: 32768 l2_cache_size: 262144 l3_cache_size: 3145728 memory_size: 268435456 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }```

thanks for listening

**Comment by guillaumekln** [comment]
The warning still exists in TensorFlow 2.7.

**Comment by ballings** [comment]
I have the same warning.

```import tensorflow as tf
tf.__version__
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.cifar100.load_data()
# x_train.shape
## (50000, 32, 32, 3)

X_train = X_train / 255.0
X_test = X_test / 255.0


inputs = tf.keras.layers.Input(shape = (32,32,3))
#dropout
dropout1 = tf.keras.layers.Dropout(rate = 0.2)(inputs)
cnn1 = tf.keras.layers.Conv2D(filters=96,kernel_size = 3, strides = 1, padding = "same", activation = "relu",kernel_regularizer=tf.keras.regularizers.L2(l2=0.001))(dropout1)
cnn2 = tf.keras.layers.Conv2D(filters=96,kernel_size = 3, strides = 1, padding = "same", activation = "relu",kernel_regularizer=tf.keras.regularizers.L2(l2=0.001))(cnn1)
cnn3 = tf.keras.layers.Conv2D(filters=96,kernel_size = 3, strides = 2, padding = "same", activation = "relu",kernel_regularizer=tf.keras.regularizers.L2(l2=0.001))(cnn2)
#add dropout
dropout2 = tf.keras.layers.Dropout(rate = 0.5)(cnn3)
cnn4 = tf.keras.layers.Conv2D(filters=192,kernel_size = 3, strides = 1, padding = "same", activation = "relu",kernel_regularizer=tf.keras.regularizers.L2(l2=0.001))(dropout2)
cnn5 = tf.keras.layers.Conv2D(filters=192,kernel_size = 3, strides = 1, padding = "same", activation = "relu",kernel_regularizer=tf.keras.regularizers.L2(l2=0.001))(cnn4)
cnn6 = tf.keras.layers.Conv2D(filters=192,kernel_size = 3, strides = 2, padding = "same", activation = "relu",kernel_regularizer=tf.keras.regularizers.L2(l2=0.001))(cnn5)
#add dropout
dropout3 = tf.keras.layers.Dropout(rate = 0.5)(cnn6)
cnn7 = tf.keras.layers.Conv2D(filters=192,kernel_size = 3, strides = 1, padding = "valid", activation = "relu",kernel_regularizer=tf.keras.regularizers.L2(l2=0.001))(dropout3)
cnn8 = tf.keras.layers.Conv2D(filters=192,kernel_size = 1, strides = 1, padding = "same", activation = "relu",kernel_regularizer=tf.keras.regularizers.L2(l2=0.001))(cnn7)
cnn9 = tf.keras.layers.Conv2D(filters=100,kernel_size = 1, strides = 1, padding = "same", activation = "relu",kernel_regularizer=tf.keras.regularizers.L2(l2=0.001))(cnn8)
# global averaging per feature map over 6 × 6 spatial dimensions
glavpool = tf.keras.layers.GlobalAvgPool2D()(cnn9)
# 100-way softmax
outputs = tf.keras.layers.Activation('softmax')(glavpool)


model = tf.keras.Model(inputs = inputs, outputs = outputs)

#Compile model
model.compile(loss = tf.keras.losses.SparseCategoricalCrossentropy(), 
              optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001)) #change loss function

#Fit model
model.fit(x=X_train,y=y_train, batch_size=128, epochs=1) 
Epoch 1/5
2021-12-07 20:21:05.693838: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8100
391/391 [==============================] - 14s 29ms/step - loss: 4.6683
Epoch 2/5
391/391 [==============================] - 11s 28ms/step - loss: 4.6052
Epoch 3/5
391/391 [==============================] - 11s 28ms/step - loss: 4.6052
Epoch 4/5
391/391 [==============================] - 11s 28ms/step - loss: 4.6052
Epoch 5/5
391/391 [==============================] - 11s 29ms/step - loss: 4.6052

#train
yhat = model.predict(X_train[0:128])
2021-12-07 20:22:38.215807: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "GPU" vendor: "NVIDIA" model: "GeForce GTX 1080 Ti" frequency: 1582 num_cores: 28 environment { key: "architecture" value: "6.1" } environment { key: "cuda" value: "11020" } environment { key: "cudnn" value: "8100" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 2883584 shared_memory_size_per_multiprocessor: 98304 memory_size: 10919215104 bandwidth: 484440000 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }
```
As you can see, the loss also gets stuck from epoch 2 onwards. Also the output is a constant (not shown here). This only happens when run on GPU. Python 3.7.12, tried with tf 2.3, 2.4, 2.7.0, CUDA/cuDNN version: 11.2/8.1.0, GeForce GTX 1080 Ti, Ubuntu 18.04.6.

**Comment by shubham0204** [comment]
I have implemented a NMT model with attention mechanism ( Luong style ) and it shows the warning,

```
 op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla T4" frequency: 1590 num_cores: 40 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "11010" } environment { key: "cudnn" value: "8005" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 65536 memory_size: 14465892352 bandwidth: 320064000 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }
2022-01-21 04:33:52.446453: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla T4" frequency: 1590 num_cores: 40 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "11010" } environment { key: "cudnn" value: "8005" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 65536 memory_size: 14465892352 bandwidth: 320064000 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }
2022-01-21 04:33:52.446923: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla T4" frequency: 1590 num_cores: 40 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "11010" } environment { key: "cudnn" value: "8005" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 65536 memory_size: 14465892352 bandwidth: 320064000 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }
2022-01-21 04:33:52.447400: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Softmax" attr { key: "T" value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla T4" frequency: 1590 num_cores: 40 environment { key: "architecture" value: "7.5" } environment { key: "cuda" value: "11010" } environment { key: "cudnn" value: "8005" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 4194304 shared_memory_size_per_multiprocessor: 65536 memory_size: 14465892352 bandwidth: 320064000 } outputs { dtype: DT_FLOAT shape { unknown_rank: true } }
```

at every training step. I'm getting this warning in Google Colab, with TensorFlow 2.7.

**Comment by philipperemy** [comment]
Same warning in here with softmax.

**Comment by gozi1123** [comment]
also, this warning appears for me as well. TF 2.6

**Comment by MahdiRahbar** [comment]
I have the same problem. I get the following warning, and sometimes the program stops after that:

```
W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Softmax" attr { key: "T"
value { type: DT_FLOAT } } inputs { dtype: DT_FLOAT shape { unknown_rank: true } } device { type: "GPU" vendor: "NVIDIA" model: 
Tesla V100-SXM2-16GB" frequency: 1530 num_cores: 80 environment { key: "architecture" value: "7.0" } environment { key: 
cuda" value: "11020" } environment { key: "cudnn" value: "8100" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 
291456 shared_memory_size_per_multiprocessor: 98304 memory_size: 15346958336 bandwidth: 898048000 } outputs { dtype: 
T_FLOAT shape { unknown_rank: true } }
```

Does anyone know what the problem can be? How can I solve the problem?

**Comment by guillaumekln** [comment]
Hi @jvishnuvardhan, what's the status of this issue? Can it be assigned to a TensorFlow developer working on the grappler implementation?

**Comment by neqkir** [comment]
Hi, same error/warning on AMD GPUs 

![image](https://user-images.githubusercontent.com/89974426/155928912-e4ab8830-f0cf-47f8-b1b0-29fe808c1303.png)

AFAIK batch size is fixed to 64 in my code.

**Comment by ICEJM1020** [comment]
HI, same error in CPU training. It only appears in model with attention.

![image](https://user-images.githubusercontent.com/38009758/179806688-4058b8d8-b068-4dac-b699-76d710d81a8f.png)

But it seems only lead to cannot estimate the training time.

**Comment by kkb0115-exem-ai** [comment]
Same error/warning on TITAN V. I also want to know the status of this issue. ![image](https://user-images.githubusercontent.com/95392859/180675828-c0fdb736-96a0-483c-ab0c-0b750f4a320b.png)

**Comment by Seioch** [comment]
I am also having this issue. I'm training a model using Attention. I'm running Ubuntu 20.04, Python 3.8.10, TF 2.5.3, NVIDIA GTX 1080 ti. 

![image](https://user-images.githubusercontent.com/3291031/181793250-9b8bcf49-0144-414b-86f4-f240c4cc61e8.png)

**Comment by tilakrayal** [comment]
@guillaumekln,
I was not able to find the above mentioned warning with softmax on tensorflow v2.11.0-dev20220822. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3dcd7398f93cb8b6693d50ed2b900009/untitled52100.ipynb) and let us know if the issue still persists. Thank you!

**Comment by guillaumekln** [comment]
It seems this was fixed in TensorFlow 2.8. The initial code snippet no longer shows a warning.

@tilakrayal Feel free to close this issue.

**Comment by tilakrayal** [comment]
@guillaumekln,
Thank you for the update. As per the users [comment](https://github.com/tensorflow/tensorflow/issues/50575#issuecomment-1229939765) this issue was fixed in tensorflow **v2.8** and marking the issue as closed. Thank you!

**Comment by krishnanNuance** [comment]
I am seeing this issue in an ONNX to TF exported model. https://github.com/onnx/onnx-tensorflow/issues/1044.What is the possible workaround?

**Comment by fperezgamonal** [comment]
I think this issue is still present at least in the C++ API in Windows 10 with TensorFlow 2.9.2 (build from source, obviously). I haven't observed any degraded performance in our internal tests, so I'll just leave this here so others can know about it.

**Comment by dalalkrish** [comment]
Is this just a warning or the does this affect the performance of the model. I'm seeing the similar warning message while using Attention layer on GPUs while doing Hyper-Parameter tuning using Keras-Tuner. Can someone please clarify that? Thank you!
