### ISSUE TITLE
TFLite conversion of LSTM model does not work with multiple batch size

### ISSUE THREAD

**Issue by kpei** [tensorflow/tensorflow#50598]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Kaggle Notebook (standard ubuntu)
- TensorFlow installed from (source or binary): Pip install tensorflow==2.5.0
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7
- CUDA/cuDNN version: CPU Only
- GPU model and memory: CPU Only

**Describe the current behavior**

I trained (on gpu) and saving an LSTM model in keras and converted it to tflite. 
```
model = Sequential()
model.add(Masking(mask_value=-1, input_shape=(n_timesteps, n_features))) # This layer is used in the final model
model.add(LSTM(64, input_shape=(n_timesteps,n_features))) # This layer is used in the final model
model.add(RepeatVector(n_timesteps))
model.add(LSTM(64, return_sequences=True))
model.add(TimeDistributed(Dense(n_features)))
optimizer = Adam(learning_rate=0.001, epsilon=1e-04)
model.compile(optimizer= optimizer, loss='mse')
model.fit(x_train, x_train, epochs=1000, verbose=2)

# Saving
encoder = Model(inputs=model.inputs, outputs=model.layers[1].output)
encoder.save('encoder.h5')
```
![image](https://user-images.githubusercontent.com/5482978/124398609-6ff91a00-dccb-11eb-81e2-55bdaecc8b1f.png)

Using both experimental and non-experimental converter, I was able to convert the model to tflite where the shape signature is (-1, X, Y) where the first dimension is batch size.

```
from tensorflow.keras.models import load_model
encoder = load_model('encoder.h5')

# Following code from https://www.tensorflow.org/lite/convert/rnn
run_model = tf.function(lambda x: encoder(x))
BATCH_SIZE = None
STEPS = 6952
INPUT_SIZE = 20
concrete_func = run_model.get_concrete_function(tf.TensorSpec([BATCH_SIZE, STEPS, INPUT_SIZE], encoder.inputs[0].dtype))
encoder.save('/encoder', save_format="tf", signatures=concrete_func)
```

Saving the model as tflite:
```
converter = tf.lite.TFLiteConverter.from_saved_model('/encoder')
converter.experimental_new_converter = True
tflite_model = converter.convert()
with open('encoder.tflite', 'wb') as f:
  f.write(tflite_model)
```

Now when I use the model:
```
interpreter = tf.lite.Interpreter(model_path='encoder.tflite')
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
data = np.vstack([a,a]).astype(np.float32) # Shape: (2, 6952, 20)
interpreter.resize_tensor_input(input_details[0]['index'], data .shape) # Shape: (2, 6952, 20)
interpreter.resize_tensor_input(output_details[0]['index'], (data .shape[0], 64)) # Shape: (2, 64)
interpreter.allocate_tensors()
interpreter.set_tensor(input_details[0]['index'], data )
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
```

I get the following error on invoke:
```
RuntimeError: tensorflow/lite/kernels/concatenation.cc:80 t->dims->data[d] != t0->dims->data[d] (2 != 1)Node number 26 (CONCATENATION) failed to prepare.
Node number 28 (WHILE) failed to invoke.
```

**Describe the expected behavior**

An output of size (2,64)

Related issues that I've looked at https://github.com/tensorflow/tensorflow/issues/34620 https://github.com/tensorflow/tensorflow/issues/24607 https://github.com/tensorflow/tensorflow/issues/37012

**Comment by renjie-liu** [comment]
Currently the fusion only works if the input shape is fixed, can you try to set the batch_size to 1? thanks!

**Comment by abattery** [comment]
In my memory, the masking related issue has been fixed at the tf-nightly.

**Comment by kpei** [comment]
> Currently the fusion only works if the input shape is fixed, can you try to set the batch_size to 1? thanks!

Hi i am still relatively new to tf.  What do you mean by fusion? Also i would like to use dynamic batch size and not fixed input size of 1.

**Comment by kpei** [comment]
> In my memory, the masking related issue has been fixed at the tf-nightly.

Is there a way for me to see which layer that the issue with fixed input size occurs on? The error messages indicate node 33 and 28 so i assumed that is the index of the list when you call `get_tensor_details()` but it doesn't seem to be correct in terms of output information.
