### ISSUE TITLE
TensorFlow Lite android compiling failed on Docker

### ISSUE THREAD

**Issue by DannyIsFunny** [tensorflow/tensorflow#50644]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
I compile tensorflow lite in android mode according to the online guide: https://www.tensorflow.org/lite/guide/build_android

- the docker file is provided by tflite 
    - https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/dockerfiles/tflite-android.Dockerfile

-  I entered into docker container but tflite compiling failed.
   - jdk version: 1.8
   - command : `bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain   //tensorflow/lite/java:tensorflow-lite`

![image](https://user-images.githubusercontent.com/45189361/124571996-dbcdb500-de7a-11eb-8190-1d498580b2fb.png)

**Describe the problem**
- related issue [#50644 ]

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by terryheo** [comment]
@thaink could you check this?

**Comment by thaink** [comment]
It is fixed in commit 27551046f5c49939c508ed7a7c33cb6724aa747c.
Could you sync to the master HEAD and try again?

**Comment by DannyIsFunny** [comment]
after [2755104](https://github.com/tensorflow/tensorflow/commit/27551046f5c49939c508ed7a7c33cb6724aa747c) is merged , compiling still failed
![image](https://user-images.githubusercontent.com/45189361/124853053-d3d75780-dfd7-11eb-866c-10a92889bd62.png)

**Comment by thaink** [comment]
Did you build the docker again?
Can you upload the docker build log?

**Comment by DannyIsFunny** [comment]
The docker image is built successfully.
I mean that I can't compile Tensorflow-Lite successfully in this docker image.

- Compiling is according to this [guide](https://www.tensorflow.org/lite/guide/build_android#build_tensorflow_lite_locally)
   - Compiling command: `bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain   //tensorflow/lite/java:tensorflow-lite`
   - error message:
![image](https://user-images.githubusercontent.com/45189361/125035541-84bb2080-e0c4-11eb-984f-9408495dda67.png)

**Comment by thaink** [comment]
You need to install the sdk using the command `android update sdk` and run ./configure.
It is described in the guide.
