### ISSUE TITLE
TFLite: XNNPACK delegate failed to delegate FULLY_CONNECTED node

### ISSUE THREAD

**Issue by GPhilo** [tensorflow/tensorflow#52653]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): Source for inference, Binary for model generation
- TensorFlow version (use command below): r2.6.0 (from git tag) for the inference code.  2.4.1 for model generation.
- Python version: 3.8.5 (model generation side only)
- Bazel version (if compiling from source): N/A, I'm building TFLite via CMake
- GCC/Compiler version (if compiling from source): MSVC 19.29.30136.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
When loading the attached MobileNet model via the TFLite C API, the XNNPACK delegate fails with the following output:

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
ERROR: failed to delegate FULLY_CONNECTED node #67
ERROR: Node number 83 (TfLiteXNNPackDelegate) failed to prepare.
```

**Describe the expected behavior**
The model loads correctly.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing): -

**Standalone code to reproduce the issue**

Model file: [model.fp32.tflite.zip](https://github.com/tensorflow/tensorflow/files/7409553/model.fp32.tflite.zip)

### Model generation (if not using the attached tflite model):

```python
import tensorflow as tf
from pathlib import Path
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
  base_model = tf.keras.applications.mobilenet_v2.MobileNetV2(
        input_shape=(224,224,3), alpha=1.0, weights='imagenet',
        classes=6, include_top=False, pooling='avg')
  output = tf.keras.layers.Dense(6, name='logits', dtype='float32')(base_model.output)
  model = tf.keras.Model(base_model.inputs, output)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
Path('model.fp32.tflite').write_bytes(tflite_model)
```

### Model loading in Cpp

```cpp
#include <tensorflow/lite/c/c_api.h>
#include <tensorflow/lite/delegates/xnnpack/xnnpack_delegate.h>

int main()
{
    auto m_model = TfLiteModelCreateFromFile("model.fp32.tflite");
    auto m_options = TfLiteInterpreterOptionsCreate();
    TfLiteXNNPackDelegateOptions opt = TfLiteXNNPackDelegateOptionsDefault();
    auto m_xnnpack_delegate = TfLiteXNNPackDelegateCreate(&opt);
    TfLiteInterpreterOptionsAddDelegate(m_options, m_xnnpack_delegate);
    auto m_interpreter = TfLiteInterpreterCreate(m_model, m_options); // This returns nullptr and prints error messages in the console
}
```

**Comment by GPhilo** [comment]
Working on this, I found the source of the issue: `converter.optimizations = [tf.lite.Optimize.DEFAULT]` does something to the graph that breaks the model for XNNPACK. Exporting the very same model without that line generates a model that is loaded correctly in the delegate.

**Comment by sachinprasadhs** [comment]
Hi, refer [this](https://www.tensorflow.org/lite/performance/post_training_quantization#dynamic_range_quantization) and let me know if this helps, Thanks!

**Comment by GPhilo** [comment]
@sachinprasadhs It does not, as I already came to the conclusion that this is the source of the problem I show above. There is no mention on the linked page about XNNPACK (or it not supporting models with dynamic range quantization enabled), nor were the error messages produced during execution mentioning anything connected to quantization being the problem.

**Comment by sachinprasadhs** [comment]
If your issue is resolved by removing` converter.optimizations = [tf.lite.Optimize.DEFAULT] `, could you please close this issue. Thanks

**Comment by Maratyszcza** [comment]
@GPhilo: this was fixed in 29d64ea02d00ac97a05d4aa6cd373e78fde3bc74

**Comment by GPhilo** [comment]
@sachinprasadhs no, the issue *is* the undocumented side effects of applying the optimisation to a model.
I found out myself that "don't apply the default optimisations" prevents the error from happening. Unfortunately, it also increases the model size massively (around 4x, since the weights are not quantises anymore).

So, again, the issue that needs addressing is either an undocumented incompatibility between the default optimisations and the xnnpack delegate, in which case please document it, or a bug in the dequantisation of the weights when loading a model with the xnnpack delegate, in which case that should probably be fixed by someone who knows how that code works internally.

@Maratyszcza could you elaborate on the fix? The linked commit only adds a check and an error, which more than a fix seems a "we don't support this". If that's the case, could you clarify exactly what is that is not supported? Quoting the documentation for the default optimisation options found here: https://www.tensorflow.org/lite/performance/post_training_quantization

"At inference, weights are converted from 8-bits of precision to floating point and computed using floating-point kernels."

So, as far as I understand it, the optimisation should only help towards reducing the model size (since the same kernels are used after de-quantization at inference time). So, assuming the model is dequantised correctly, shouldn't it work the same way as a "pure" floating point model works, with respect to delegates?

**Comment by GPhilo** [comment]
@Maratyszcza Thanks for the clarification, but then I still don't understand the descripton of the optimisation options I quoted above (putting it here again with the whole context and adding with proper formatting):

> The simplest form of post-training quantization statically quantizes only the weights from floating point to integer, which has 8-bits of precision. At inference, weights are converted from 8-bits of precision to floating point and computed using floating-point kernels.

This line coms from [here](https://www.tensorflow.org/lite/performance/post_training_quantization#dynamic_range_quantization). The way I read it, this is just a (lossy) operation to compress down the weights, which is then undone at runtime, because "weights are converted from 8-bits of precision to floating point **and computed using floating-point kernels**".

That said, the operator is not a fully-connected with floating-point I/O, bias and INT8 weights: it is a fully fp32 fully-connected operator whose weights have not yet been converted back to fp32.

**Comment by Maratyszcza** [comment]
TFLite has convolution kernels which directly consume `INT8` weights and do conversion to floating-point just before doing the computations. XNNPACK doesn't include such kernels, so it requires that weights are unpacked into FP32 in advance. You can achieve it by inserting `DEQUANTIZE` operator to unpack `INT8` weights of the `FULLY_CONNECTED` operator into floating-point.

**Comment by GPhilo** [comment]
Thank you for the additional information.

Taking a deeper look at the xnnpack_delegate.c you linked in your first comment, I noticed that between r2.6 and the current master [the handling of kTfLiteInt8 tensors has been geatly extended](https://github.com/tensorflow/tensorflow/blob/8a2a4c3ca06a622989823c7dfa58e01044244935/tensorflow/lite/delegates/xnnpack/xnnpack_delegate.cc#L233). Building from the current master branch, I can load the quantized model correctly and it seems to work as expected, so I'll close the issue because it seems to be solved in the upcoming r2.7.

**Comment by christian-steinmeyer** [comment]
Hey!
I think I'm running into a similar problem.

I have a tiny dummy model:
```py
    img = tf.keras.layers.Input((40, 320, 1), name='img')
    x = tf.keras.layers.Conv2D(32, (3, 3), padding='same')(img)
    x = tf.keras.layers.Dense(24, activation='softmax', name="output")(x)
    model = tf.keras.Model(inputs=[img], outputs=x)
```
which I'm converting to tflite:
```py
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [
        tf.lite.Optimize.EXPERIMENTAL_SPARSITY,  # sparsity optimization for xnnpack acceleration
    ]
    tflite_model = converter.convert()
```
before saving and then on the c++ side I'm trying to apply the xnnpack delegate:
```cpp
    auto m_model = TfLiteModelCreateFromFile("<PATH_TO_FILE>.tflite");
    auto m_options = TfLiteInterpreterOptionsCreate();
    TfLiteXNNPackDelegateOptions opt = TfLiteXNNPackDelegateOptionsDefault();
    auto m_xnnpack_delegate = TfLiteXNNPackDelegateCreate(&opt);
    TfLiteInterpreterOptionsAddDelegate(m_options, m_xnnpack_delegate);
    auto m_interpreter = TfLiteInterpreterCreate(m_model, m_options); // This returns nullptr and prints error messages in the console
```
