### ISSUE TITLE
Code completion of Keras Moudle no longer work since 2.6

### ISSUE THREAD

**Issue by elda27** [tensorflow/tensorflow#53271]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 20H2
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1/
- Python version: 3.8.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version:  N/A
- GPU model and memory: N/A

**Describe the current behavior**
Code completion is no longer work for `tf.keras` on the VSCode. since TensorFlow 2.6.
![image](https://user-images.githubusercontent.com/6873761/144241798-4239b2ac-39b4-4c96-98ca-7c89918900e1.png)

**Describe the expected behavior**
Code completion is work for `tf.keras` on the VSCode until TensorFlow 2.5.
![image](https://user-images.githubusercontent.com/6873761/144241133-3a2f04f8-3513-491e-8a43-243666c4d164.png)

A related issue found #52031.
The cause of this problem is lazy import of Keras.
A similar problem exists in TensorFlow Probability.

One solution is to prepare a stub file, but that is a lot of work.
Are you aware that this problem is a VSCode/Pylance problem?

**[Contributing](https://www.tensorflow.org/community/contribute)**
- Do you want to contribute a PR? (yes/no): yes, but I don't have a solution.
- Briefly describe your candidate solution(if contributing): N/A.

**Comment by markorakita** [comment]
It also doesn't work in PyCharm, I opened issue here #53144

At first I was using Visual Studio to write tensorflow python code, but then I switched to PyCharm because code completion was broken and I thought it was Visual Studio issue. Now I see that writing tensorflow keras code is absolutely broken in every major IDE.

I can't believe so few people are complaining about this, what IDE are other people using to write tensorflow code, notepad++? :D

**Comment by mihaimaruseac** [comment]
> I can't believe so few people are complaining about this, what IDE are other people using to write tensorflow code, notepad++? :D
Vim :P

But coming back to the issue, I think this is due to the keras moving to a separate repository. Probably the solution would also come from there.

**Comment by elda27** [comment]
> But coming back to the issue, I think this is due to the keras moving to a separate repository. Probably the solution would also come from there.

I think so.
And also currently Keras is not work code completion too.
This is very similarly with this issue.

**Comment by cpuimage** [comment]
@elda27 try my solution.
 https://github.com/tensorflow/tensorflow/issues/53144#issuecomment-985179600

**Comment by elda27** [comment]
@cpuimage 
Thanks.
A module completion such as `from tensorflow.keras import ~` is works good.
But `tf.keras.~` is not work code completions.

Can you work completion about `tf.keras.~` on the PyCharm.
My VSCode is not work code completion after changes.

Maybe PyCharm is more intelligence.

**Comment by cpuimage** [comment]
@elda27  yes,it work.
after modify the  [site-packages\tensorflow_init_.py] 
then write code like:

```
import tensorflow as tf
from tensorflow.keras import layers 

tf.keras.~ # it work good.
```

**Comment by elda27** [comment]
@cpuimage Oh nice! maybe my work is something wrong.
I will read again your posts.

By the way, I found good feature in PEP563.
https://www.python.org/dev/peps/pep-0563/#runtime-annotation-resolution-and-type-checking

There are example code in the document.

```python
import typing

if typing.TYPE_CHECKING:
    import expensive_mod

def a_func(arg: expensive_mod.SomeClass) -> None:
    a_var: expensive_mod.SomeClass = arg
    ...
```

This code is work good in the VSCode. (I'm not check on the PyCharm)
``` python
import typing
if typing.TYPE_CHECKING:
  from tensorflow import keras
else:
  _keras_module = "keras.api._v2.keras"
  keras = _LazyLoader("keras", globals(), _keras_module)
  _module_dir = _module_util.get_parent_dir_for_name(_keras_module)
  if _module_dir:
    _current_module.__path__ = [_module_dir] + _current_module.__path__
  setattr(_current_module, "keras", keras)
```

**Comment by cpuimage** [comment]
> @cpuimage Oh nice! maybe my work is something wrong. I will read again your posts.
> 
> By the way, I found good feature in PEP563. https://www.python.org/dev/peps/pep-0563/#runtime-annotation-resolution-and-type-checking
> 
> There are example code in the document.
> 
> ```python
> import typing
> 
> if typing.TYPE_CHECKING:
>     import expensive_mod
> 
> def a_func(arg: expensive_mod.SomeClass) -> None:
>     a_var: expensive_mod.SomeClass = arg
>     ...
> ```
> 
> This code is work good in the VSCode. (I'm not check on the PyCharm)
> 
> ```python
> import typing
> if typing.TYPE_CHECKING:
>   from tensorflow import keras
> else:
>   _keras_module = "keras.api._v2.keras"
>   keras = _LazyLoader("keras", globals(), _keras_module)
>   _module_dir = _module_util.get_parent_dir_for_name(_keras_module)
>   if _module_dir:
>     _current_module.__path__ = [_module_dir] + _current_module.__path__
>   setattr(_current_module, "keras", keras)
> ```

good job. it work good in PyCharm.

**Comment by elda27** [comment]
@cpuimage Thanks! I haven't been successful your suggestion yet. Maybe VSCode has something difference with PyCharm.
@sanatmpa1 Can you review my solution and please tell us to any one is better for TensorFlow?

**Comment by sanatmpa1** [comment]
@elda27,

As @mihaimaruseac pointed out in this [comment](https://github.com/tensorflow/tensorflow/issues/53271#issuecomment-983828570), it may be due to keras being moved to a different repo. 
Can you please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) Thanks!

**Comment by elda27** [comment]
@sanatmpa1 This change apply the `tensorflow/__init__.py`.
I guess the issue for tensorflow-team.

**Comment by bermeitinger-b** [comment]
This is still happening with 2.8.0, 2.8.1, and 2.9.0.

**Comment by alkatar21** [comment]
This issue is solved in #54104 and released at least in tf-nightly and is also more or less a dublicate of #56231 and #53144 and could be closed as it is now hopefully fully resolved with #56231? @qlzh727

**Comment by qlzh727** [comment]
Let's just use #56231 to track the overall IDE auto-complete issue.

**Comment by alkatar21** [comment]
@elda27  No, the autocompletion mentioned in this issue is fixed in nightly, so probably in v2.10. You can currently fix it in your installation by doing what is done in #54104 locally.

**Comment by elda27** [comment]
@alkatar21 Thanks! I await next release.

**Comment by hilanzy** [comment]
@alkatar21 The issue still happened on v2.10.0 
![image](https://user-images.githubusercontent.com/106568143/188835585-81f4c7b1-398f-4217-827c-4abce7dc0f82.png)

**Comment by hilanzy** [comment]
However tf.keras is OK.
![image](https://user-images.githubusercontent.com/106568143/188838094-fab08be4-b1a5-4fe5-b11e-203801256c7d.png)
So, why is that?

**Comment by hilanzy** [comment]
I try to modify tensorflow.__init__.py
before:
------
if _typing.TYPE_CHECKING:
  from tensorflow_estimator.python.estimator.api._v2 import estimator as estimator
  from keras.api._v2.keras import keras
  from keras.api._v2.keras import losses
  from keras.api._v2.keras import metrics
  from keras.api._v2.keras import optimizers
  from keras.api._v2.keras import initializers
now:
------
if _typing.TYPE_CHECKING:
  from tensorflow_estimator.python.estimator.api._v2 import estimator as estimator
  import keras.api._v2.keras as keras
  from keras.api._v2.keras import losses
  from keras.api._v2.keras import metrics
  from keras.api._v2.keras import optimizers
  from keras.api._v2.keras import initializers
------
And it's work for me.
![image](https://user-images.githubusercontent.com/106568143/188842572-40796155-992e-4c34-8e4c-44d5d0f71198.png)

So, why is that?
TF: 2.10.0
Python: 3.8.13 by miniconda
os: ubuntu20.04.5 LTS  (GNU/Linux 5.4.0-125-generic x86_64)
vscode:v1.71.0

**Comment by mihaimaruseac** [comment]
TF's APIs should be used via `tf.`. So `tf.keras.*` is legitimate, `keras.*` not so much.

**Comment by hilanzy** [comment]
> TF's APIs should be used via `tf.`. So `tf.keras.*` is legitimate, `keras.*` not so much.

@mihaimaruseac ,Thanks for you reply, So why it can run successful but dont support autocompletion.
And why tf tutorials show  a  code  `from tensorflow.keras import Model` ,`from tensorflow.keras.layers import Dense, Flatten, Conv2D`etc. as you know it's also has the same issue, but the tutorials insist do that.
[https://tensorflow.google.cn/tutorials/quickstart/advanced](url)

**Comment by hilanzy** [comment]
> TF's APIs should be used via `tf.`. So `tf.keras.*` is legitimate, `keras.*` not so much.

And you can see the code `from tensorflow.keras import *` is on every official examples almost. Whatever tensorflow or keras.  like this.[https://keras.io/examples/vision/image_classification_from_scratch/](url)
So, via `tf.*` to use tensorflow or keras sounds not make sence.

**Comment by qlzh727** [comment]
Thanks for the information.

Based on my rough knowledge for auto completion, I think the issue probably caused by difference between package/directory/module.

Most of the IDE will try to auto complete by the package tree structure, so if there is a directory with __init__ under tensorflow call "keras", then it will resolve correctly when you do "from tensorflow.keras.xxxx import yyy". This was working before 2.7 since Keras was part of the Tensorflow PIP package.

Note that the "import tensorflow as tf; tf.keras.xxx.yyy" is resolved differently. `tf.keras` is firstly resolved into the logic in the tensorflow/__init__.py, and then the keras becomes the "keras.apis._v2.keras", which resolved correctly to the keras PIP package. 

Before TF 2.7, I think the we did some manual mimic for the keras APIs to tensorflow/keras folder from tensorflow/python/keras/apis, so that it the package level auto completion works, but that is not the case anymore after 2.7 since the keras is a standalone package. 

As a quick test on my local, I manually created a symlink under `venv/lib/python3.10/site-packages/tensorflow` by `ln -s ../keras/api/_v2/keras/ keras` (assuming you have tensorflow and keras pip package installed properly), and then the IDE can resolve the package level auto completion correctly.

I am not sure if this fix can be applied to TF direclty, since the symlink is not well supported on windows, and might be in different location if the package is installed differently.

**Comment by qlzh727** [comment]
Having said that, all the import should always work, since the auto complete and python import works differently. Tensorflow has extra logic in the tensorflow/__init__.py to ensure all the public API are populated correctly via the _api folder, instead of directly using the directory structure.

**Comment by hilanzy** [comment]
> Thanks for the information.
> 
> Based on my rough knowledge for auto completion, I think the issue probably caused by difference between package/directory/module.
> 
> Most of the IDE will try to auto complete by the package tree structure, so if there is a directory with **init** under tensorflow call "keras", then it will resolve correctly when you do "from tensorflow.keras.xxxx import yyy". This was working before 2.7 since Keras was part of the Tensorflow PIP package.
> 
> Note that the "import tensorflow as tf; tf.keras.xxx.yyy" is resolved differently. `tf.keras` is firstly resolved into the logic in the tensorflow/**init**.py, and then the keras becomes the "keras.apis._v2.keras", which resolved correctly to the keras PIP package.
> 
> Before TF 2.7, I think the we did some manual mimic for the keras APIs to tensorflow/keras folder from tensorflow/python/keras/apis, so that it the package level auto completion works, but that is not the case anymore after 2.7 since the keras is a standalone package.
> 
> As a quick test on my local, I manually created a symlink under `venv/lib/python3.10/site-packages/tensorflow` by `ln -s ../keras/api/_v2/keras/ keras` (assuming you have tensorflow and keras pip package installed properly), and then the IDE can resolve the package level auto completion correctly.
> 
> I am not sure if this fix can be applied to TF direclty, since the symlink is not well supported on windows, and might be in different location if the package is installed differently.

Thanks for you reply, It's really very useful for me, and this fix is work on my local. But I dont think this is perfect way to solve this issue(maybe now), cos it seems I need do that every time when I was upgrade or reinstall tensorflow. As I konw, tf.keras is the recommended api by TF2, but it is inconvenient to use, I think we shouldn't do any additional operation once we do pip install tensorflow. So, is there will have a better way to solve this issue in the future version?
