### ISSUE TITLE
Cross compiling TFLite with XNNPACK=ON for ARM with CMake

### ISSUE THREAD

**Issue by TimRoadley** [tensorflow/tensorflow#53545]
**System information**
- Linux Ubuntu 20.04
- TensorFlow r2.8 (and master at the time of writing, being Dec 26th 2021)
- CMake 3.16.3
- gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf (as per [this](https://www.tensorflow.org/lite/guide/build_cmake_arm#download_toolchain_2) toolchain recommendation)

**Describe the problem**
I want to cross compile tensorflow lite (with xnnpack=on) for arm using cmake. 

The build fails unless I force xnnpack to off.  I'm using the steps stated in the following articles:

- https://www.tensorflow.org/lite/guide/build_cmake
- https://www.tensorflow.org/lite/guide/build_arm
- https://www.tensorflow.org/lite/guide/build_cmake_arm

**Provide the exact sequence of commands / steps that you executed before running into the problem**

- Install clean Ubuntu 20.04 and latest updates

- Install Prerequisites 
```
sudo apt-get install curl git cmake
```

- Install Toolchain (as per [this](https://www.tensorflow.org/lite/guide/build_cmake_arm#download_toolchain_2))
```
curl -LO https://storage.googleapis.com/mirror.tensorflow.org/developer.arm.com/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz
mkdir -p ${HOME}/toolchains
tar xvf gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz -C ${HOME}/toolchains
```

- Clone Tensorflow (as per [this](https://www.tensorflow.org/lite/guide/build_cmake#step_2_clone_tensorflow_repository))
```
git clone https://github.com/tensorflow/tensorflow.git ${HOME}/tensorflow_src
mkdir ${HOME}/tflite_build && cd ${HOME}/tflite_build
```

- Run CMake (as per [this](https://www.tensorflow.org/lite/guide/build_cmake_arm#run_cmake_2)) noting that this defaults to using -DTFLITE_ENABLE_XNNPACK=ON
```
ARMCC_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations"
ARMCC_PREFIX=${HOME}/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
cmake -DCMAKE_C_COMPILER=${ARMCC_PREFIX}gcc \
 -DCMAKE_CXX_COMPILER=${ARMCC_PREFIX}g++ \
 -DCMAKE_C_FLAGS="${ARMCC_FLAGS}" \
 -DCMAKE_CXX_FLAGS="${ARMCC_FLAGS}" \
 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -DCMAKE_SYSTEM_NAME=Linux \
 -DCMAKE_SYSTEM_PROCESSOR=armv7 \
  ../tensorflow_src/tensorflow/lite/
```

- Build (as per [this](https://www.tensorflow.org/lite/guide/build_cmake#step_5_build_tensorflow_lite))
```
cmake --build . -j
```

**Any other info / logs**
This build crashes around halfway through as per the output below. I can make it work by adding -DTFLITE_ENABLE_XNNPACK=OFF, however that will disable XNNPACK and considerably slow down inference time.  My ARM hardware has the NEON capabilitiy, so really need this XNNPACK compile to work. Thanks in  advance!

**Build Output**
```
[ 57%] Building C object _deps/xnnpack-build/CMakeFiles/XNNPACK.dir/src/f32-ibilinear/gen/neonfma-c8.c.o
cd /home/tim/tflite_build/_deps/xnnpack-build && /home/tim/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_MPL2_ONLY -DFXDIV_USE_INLINE_ASSEMBLY=0 -DNOMINMAX=1 -DPTHREADPOOL_NO_DEPRECATED_API=1 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_SPARSE=1 -DXNN_LOG_LEVEL=0 -I/home/tim/tflite_build/xnnpack/include -I/home/tim/tflite_build/xnnpack/src -I/home/tim/tflite_build/clog/deps/clog/include -I/home/tim/tflite_build/cpuinfo/include -I/home/tim/tflite_build/pthreadpool-source/include -I/home/tim/tflite_build/FXdiv-source/include -I/home/tim/tflite_build/FP16-source/include  -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -O3 -DNDEBUG -fPIC   -Wno-psabi -pthread -std=gnu99  -marm  -march=armv7-a -mfpu=neon-vfpv4  -O2  -o CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/1x8s4-minmax-neonfma.c.o   -c /home/tim/tflite_build/xnnpack/src/f32-gemm/gen/1x8s4-minmax-neonfma.c
cd /home/tim/tflite_build/_deps/xnnpack-build && /home/tim/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_MPL2_ONLY -DFXDIV_USE_INLINE_ASSEMBLY=0 -DNOMINMAX=1 -DPTHREADPOOL_NO_DEPRECATED_API=1 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_SPARSE=1 -DXNN_LOG_LEVEL=0 -I/home/tim/tflite_build/xnnpack/include -I/home/tim/tflite_build/xnnpack/src -I/home/tim/tflite_build/clog/deps/clog/include -I/home/tim/tflite_build/cpuinfo/include -I/home/tim/tflite_build/pthreadpool-source/include -I/home/tim/tflite_build/FXdiv-source/include -I/home/tim/tflite_build/FP16-source/include  -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -O3 -DNDEBUG -fPIC   -Wno-psabi -pthread -std=gnu99  -marm  -march=armv7-a -mfpu=neon-vfpv4  -O2  -o CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/6x8s4-minmax-neonfma.c.o   -c /home/tim/tflite_build/xnnpack/src/f32-gemm/gen/6x8s4-minmax-neonfma.c
cd /home/tim/tflite_build/_deps/xnnpack-build && /home/tim/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_MPL2_ONLY -DFXDIV_USE_INLINE_ASSEMBLY=0 -DNOMINMAX=1 -DPTHREADPOOL_NO_DEPRECATED_API=1 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_SPARSE=1 -DXNN_LOG_LEVEL=0 -I/home/tim/tflite_build/xnnpack/include -I/home/tim/tflite_build/xnnpack/src -I/home/tim/tflite_build/clog/deps/clog/include -I/home/tim/tflite_build/cpuinfo/include -I/home/tim/tflite_build/pthreadpool-source/include -I/home/tim/tflite_build/FXdiv-source/include -I/home/tim/tflite_build/FP16-source/include  -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -O3 -DNDEBUG -fPIC   -Wno-psabi -pthread -std=gnu99  -marm  -march=armv7-a -mfpu=neon-vfpv4  -O2  -o CMakeFiles/XNNPACK.dir/src/f32-ibilinear-chw/gen/neonfma-p8.c.o   -c /home/tim/tflite_build/xnnpack/src/f32-ibilinear-chw/gen/neonfma-p8.c
/home/tim/tflite_build/xnnpack/src/f16-f32-vcvt/gen/vcvt-neonfp16-x16.c: In function ‘xnn_f16_f32_vcvt_ukernel__neonfp16_x16’:
cd /home/tim/tflite_build/_deps/xnnpack-build && /home/tim/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_MPL2_ONLY -DFXDIV_USE_INLINE_ASSEMBLY=0 -DNOMINMAX=1 -DPTHREADPOOL_NO_DEPRECATED_API=1 -DXNN_ENABLE_ASSEMBLY=1 -DXNN_ENABLE_MEMOPT=1 -DXNN_ENABLE_SPARSE=1 -DXNN_LOG_LEVEL=0 -I/home/tim/tflite_build/xnnpack/include -I/home/tim/tflite_build/xnnpack/src -I/home/tim/tflite_build/clog/deps/clog/include -I/home/tim/tflite_build/cpuinfo/include -I/home/tim/tflite_build/pthreadpool-source/include -I/home/tim/tflite_build/FXdiv-source/include -I/home/tim/tflite_build/FP16-source/include  -march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -O3 -DNDEBUG -fPIC   -Wno-psabi -pthread -std=gnu99  -marm  -march=armv7-a -mfpu=neon-vfpv4  -O2  -o CMakeFiles/XNNPACK.dir/src/f32-ibilinear/gen/neonfma-c8.c.o   -c /home/tim/tflite_build/xnnpack/src/f32-ibilinear/gen/neonfma-c8.c
/home/tim/tflite_build/xnnpack/src/f16-f32-vcvt/gen/vcvt-neonfp16-x16.c:31:11: error: unknown type name ‘float16x8_t’
     const float16x8_t vh0 = vreinterpretq_f16_u16(vld1q_u16(i)); i += 8;

```

**Comment by Saduf2019** [comment]
@TimRoadley 
Could you please try on stable version and let s know if this is still an issue, could you please try on 2.6/2.7 and let us know.

**Comment by Maratyszcza** [comment]
Should be fixed with 6fcfc7c8a6d46b63e4e2febb1774f9f0865bd2f2

**Comment by MirLeo** [comment]
I am still having the same issue as @TimRoadley, would you please share if/how you managed to resolve this?
