### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by Ghedeon** [tensorflow/tensorflow#5432]
Hi,

I'm trying to build from master branch and getting this error during the `./configure` step:
```
ERROR: /home/ghedeon/tf/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@iron_input//': Error downloading from https://github.com/polymerelements/iron-input/archive/1.0.10.tar.gz to /home/ghedeon/.cache/bazel/_bazel_ghedeon/dad96730576e51486fd99d150d1fdbd2/external/iron_input: Error downloading https://github.com/polymerelements/iron-input/archive/1.0.10.tar.gz to /home/ghedeon/.cache/bazel/_bazel_ghedeon/dad96730576e51486fd99d150d1fdbd2/external/iron_input/1.0.10.tar.gz: Timed out connecting to https://github.com/polymerelements/iron-input/archive/1.0.10.tar.gz : connect timed out and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: /home/ghedeon/tf/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@iron_input//': Error downloading from https://github.com/polymerelements/iron-input/archive/1.0.10.tar.gz to /home/ghedeon/.cache/bazel/_bazel_ghedeon/dad96730576e51486fd99d150d1fdbd2/external/iron_input: Error downloading https://github.com/polymerelements/iron-input/archive/1.0.10.tar.gz to /home/ghedeon/.cache/bazel/_bazel_ghedeon/dad96730576e51486fd99d150d1fdbd2/external/iron_input/1.0.10.tar.gz: Timed out connecting to https://github.com/polymerelements/iron-input/archive/1.0.10.tar.gz : connect timed out and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
```

tf master/9d04588
Bazel 0.4.0
CUDA 7.5
cuDNN 5.0
python 3.5.2

**Comment by aselle** [comment]
see if you can wget https://github.com/polymerelements/iron-input/archive/1.0.10.tar.gz
if so, try starting from a new sandbox or clean expunging bazel.
you did not specify what platform you are using as well. Thanks!

**Comment by Ghedeon** [comment]
Platform is Arch Linux (4.8.6-1, GeForce GTX 960M), Virtualenv installation, so, no sandboxes..
 
Wget works just fine and looks like it has nothing to do with that specific package. It's just extremely flaky and fails all the time on different packages either with `time out` either with `no route to host`. It's not the best connection (~100Mbps), but I believe it should be enough. Is there any way to increase timeouts for `.configure`?

**Comment by aselle** [comment]
@jart do you have any ideas?

**Comment by jart** [comment]
Thank you for bringing this to our attention. We're aware of reliability issues with downloading dependencies, but right now we're predicting it's somewhere between 99% and 99.9% reliable. If it's less reliable than that, then chances are the issue might be with your internet connection or configuration. We recommend reaching out to your service provider, or reaching out to Stack Overflow to see if they can help you troubleshoot.

**Comment by Ghedeon** [comment]
https://github.com/tensorflow/tensorflow/issues/5080
https://github.com/tensorflow/tensorflow/issues/5029#issuecomment-254769127

**Comment by jart** [comment]
#5029 was due to the user configuring an HTTP proxy that didn't exist. #5080 is the same as yours, but the error is also due to GitHub.

If you're confident your Internet is OK, then this could just be issues with GitHub's service. According to their [status site](https://status.github.com/graphs/past_month) the service availability for GitHub was 98.7% the past thirty days, which is worse than I thought.

In the near future I'm going to be adding a feature to Bazel fixing https://github.com/bazelbuild/bazel/issues/1814 which will allow us to mirror all the files TensorFlow downloads, so a dependent server going down won't break builds.

If you still think this is an issue in Bazel, and can make a case for that with technical details, then I would recommend filing a bug against them.

**Comment by jart** [comment]
I just did a lot of work to improve Bazel's downloader. A change is going to be pushed soon adding super reliability.

**Comment by jart** [comment]
This has been fixed by https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d. Try using Bazel at HEAD. A new Bazel will be cut in a few days. As soon as that happens, the TensorFlow repository will be updated to use multiple mirrors for each external file.

**Comment by brb1901** [comment]
Just as a heads-up: this or a similar issue still caused problems for me, when using ./configure before building TensorFlow (1.0) from source. On a Ubuntu 16.04 machine with reliable internet connection, CUDA 8.0, CuDNN 5.1, and apparently after @jart's bazel fix that includes multiple mirrors.

It seems to me to be some bazel timeout issue, where the timeout happens perhaps too quickly for some files. In my case configure couldn't download the swig-3.0.8.tar.gz file and ended with:

BUILD:2275:1: every rule of type _py_wrap_cc implicitly depends upon the target '@swig//:swig', but this target could not be found because of: no such package '@swig//': Error downloading [http://bazel-mirror.storage.googleapis.com/ufpr.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz, http://ufpr.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz, http://pilotfiber.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz] to /home/bram/.cache/bazel/_bazel_bram/f835375b14587b3eef360885d19162a0/external/swig/swig-3.0.8.tar.gz: All mirrors are down: [].
ERROR: Evaluation of query "deps((//tensorflow/... - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure.

I had no problems downloading the file with wget. It took a considerable number of seconds to make the connection though (although, like I said, my internet connection is solid -- but in Europe); which is why I suspect bazel timeouts a bit too quickly in some cases. It would be nice if this were easily configurable.

In the end I used the workaround suggested by sunil3590 on Aug 1, 2016 as described here: https://github.com/bazelbuild/bazel/issues/587 . Basically downloading the file yourself, using `python -m SimpleHTTPServer 8000` to host it locally, and adapt workspace.bzl to download that file from that local host instead of from the original, remote sites. That worked but isn't pretty.
