### ISSUE TITLE
Tensorflow not detecting GPU RTX 2070

### ISSUE THREAD

**Issue by Cheeseboy8020** [tensorflow/tensorflow#54416]
I am trying to get tensorflow to detect my RTX 2070. I am using Ubuntu with the nvidia-510 drivers. Pytorch is detecting the GPU but tensorflow is not detecting it. I tried reinstalling my drivers and trying the nightly version. I also followed the GPU instructions on the website and tried to install it wtih conda.

I am getting those errors when starting Tensorflow:

```
2022-02-16 22:23:08.039986: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:987] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-16 22:23:08.042291: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2022-02-16 22:23:08.042658: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

This is my nvidia-smi output:
![image](https://user-images.githubusercontent.com/68305035/154398647-3fdee35a-5758-40f4-8724-d68b5efd1075.png)

I am using this code to detect the GPU:
```
import tensorflow as tf
tf.config.list_physical_devices()
```

This is what my usr/local looks like:
![image](https://user-images.githubusercontent.com/68305035/154398885-eb990fdf-1327-4251-9754-08e977f48418.png)

**Comment by ngam** [comment]
Where did you install tensorflow from (pip, conda, elsewhere)? And what's the output of `echo $LD_LIBRARY_PATH` and `echo $PATH`?

**Comment by Cheeseboy8020** [comment]
I installed it with the instructions on the website and I also installed it with the conda instructions [here](https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/). echo $LD_LIBRARY_PATH is blank and echo $PATH gives me this:
```
/home/aneesh/miniconda3/bin:/home/aneesh/miniconda3/condabin:/home/aneesh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by tilakrayal** [comment]
@Cheeseboy8020 ,
Can you please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/52988) with the similar error.It helps.
In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem

**Comment by Cheeseboy8020** [comment]
OS: Ubuntu 21.10
TensorFlow installed from: Binary
Tensorflow Version: 2.8.0 Release & 2.9.0 Nightly
Python version: 3.10.0
Installed using: pip & conda
CUDA: Installed 11.0 but nvidia-smi shows 11.6
GPU: RTX 2070 8GB

**Comment by ngam** [comment]
> I installed it with the instructions on the website and I also installed it with the conda instructions [here](https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/). echo $LD_LIBRARY_PATH is blank and echo $PATH gives me this:
> 
> ```
> /home/aneesh/miniconda3/bin:/home/aneesh/miniconda3/condabin:/home/aneesh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> ```

Due to a recent change, you will need to expose the cuda libs via LD_LIBRARY_PATH and put the appropriate compilers (e.g. ptxas) on PATH if needed (though this latter part doesn't necessarily affect the gpu discovery per se).

**Comment by Cheeseboy8020** [comment]
I fixed by trying all the solutions that were provided. That didn't work so I deleted all my nvidia drivers and cuda drivers. Then I installed the cuda driver first with the runfile and I didn't include the nvidia driver in the install. Then I installed the nvidia driver. I used cuda 11.6 and nvidia driver 510.

**Comment by ngam** [comment]
Still not working?

Could you please try to install all from conda-forge to see if that helps?
