### ISSUE TITLE
tensorflow cannot import name 'dtensor'

### ISSUE THREAD

**Issue by wangzy0327** [tensorflow/tensorflow#56298]
### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

tf 2.6.0

### Custom Code

No

### OS Platform and Distribution

Linux 

### Mobile device

CentOS Linux release 7.9.2009 (Core)

### Python version

3.6

### Bazel version

4.2

### GCC/Compiler version

9.3

### CUDA/cuDNN version

11.2

### GPU model and memory

d

### Current Behaviour?

```shell
A bug happened!

import tensorflow as tf
print(tf.__version__)
help(tf.keras)
```

### Standalone code to reproduce the issue

```shell
/home/wzy/anaconda3/envs/tensorflow-2.6/bin/python
2.6.0
cannot import name 'dtensor'
```

### Relevant log output

```shell
/home/wzy/anaconda3/envs/tensorflow-2.6/bin/python
2.6.0
cannot import name 'dtensor'
```

**Comment by sushreebarsa** [comment]
@wangzy0327 I tried to replicate the issue on colab using TF v2.8.0 and faced a different output as below:
```
2.8.0
Help on package keras.api._v2.keras in keras.api._v2:

NAME
    keras.api._v2.keras - Public API for tf.keras namespace.

PACKAGE CONTENTS
    __internal__ (package)
    activations (package)
    applications (package)
    backend (package)
    callbacks (package)
    constraints (package)
    datasets (package)
    estimator (package)
    experimental (package)
    initializers (package)
    layers (package)
    losses (package)
    metrics (package)
    mixed_precision (package)
    models (package)
    optimizers (package)
    premade (package)
    preprocessing (package)
    regularizers (package)
    utils (package)
    wrappers (package)

VERSION
    2.8.0

FILE
    /usr/local/lib/python3.7/dist-packages/keras/api/_v2/keras/__init__.py


```
 Could you have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/c16574ea7b2012392181afc78cea52d0/56298.ipynb) and confirm the same?
Thank you!

**Comment by wangzy0327** [comment]
Thx. I found the problem may be my python environment.The python version is python3.6 which maybe cannot support tensorflow 2.x

**Comment by sushreebarsa** [comment]
@wangzy0327 Thank you for the update!
Could you use the compatible python version with the latest TF version and follow the details [here](https://www.tensorflow.org/install/source). Please move this issue to closed status if it is resolved?
Thank you!

**Comment by wangzy0327** [comment]
Yes,Thank you resolve the problem.

**Comment by sushreebarsa** [comment]
@wangzy0327 
Thank you for your update, glad its working fine for you, kindly move this issue to closed status as it is resolved.
Thank you!

**Comment by qlzh727** [comment]
dtensor API is only available at tf 2.9 or later, so it is expected to fail in tf 2.6.

**Comment by zahraMRTZ** [comment]
> dtensor API is only available at tf 2.9 or later, so it is expected to fail in tf 2.6.

I try tf 2.10, but still persist this issue.
Actually, I have win10, virtual environment with python3.9.13 and I tried tf 2.10 and tf 2.13 and every time that I run my code get this error
```ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental' (C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\_api\v2\compat\v2\experimental\__init__.py)
```
