### ISSUE TITLE
An error occurred during the fetch of repository 'llvm-project':

### ISSUE THREAD

**Issue by danielgusland** [tensorflow/tensorflow#56540]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.4.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### Bazel version

3.1.0

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

11.6/8

### GPU model and memory

RTX3080

### Current Behaviour?

```shell
Bazel-build code fails when trying to retrieve llvm source code. 

Download from primary fails with 404: 
https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz

Download from secondary fails with 504:
https://github.com/llvm/llvm-project/archive/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz
```

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/tensorflow/archive/v2.4.1.tar.gz
```

### Relevant log output

```shell
ERROR: An error occurred during the fetch of repository 'llvm-project':
   java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz, https://github.com/llvm/llvm-project/archive/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz] to /home/dgu/.cache/bazel/_bazel_dgu/bbb96d26b2548d6cbb28158a8986fc7d/external/llvm-project/f402e682d0ef5598eeffc9a21a691b03e602ff58.tar.gz: Read timed out
```
</details>

**Comment by nSircombe** [comment]
I've also seen this today on builds of the 2.9.1 branch and master. A simple `wget` times out too...
```
wget https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz
--2022-06-22 20:52:40--  https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/llvm/llvm-project/tar.gz/1cb299165c859533e22f2ed05eb2abd5071544df [following]
--2022-06-22 20:52:41--  https://codeload.github.com/llvm/llvm-project/tar.gz/1cb299165c859533e22f2ed05eb2abd5071544df
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 504 Gateway Timeout
Retrying.

--2022-06-22 20:54:43--  (try: 2)  https://codeload.github.com/llvm/llvm-project/tar.gz/1cb299165c859533e22f2ed05eb2abd5071544df
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 504 Gateway Timeout
Retrying.

--2022-06-22 20:56:45--  (try: 3)  https://codeload.github.com/llvm/llvm-project/tar.gz/1cb299165c859533e22f2ed05eb2abd5071544df
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response...
...etc...
```
I suspect this is a GitHub issue? 
No trouble getting to the GitHub llvm/llvm-project page though.

**Comment by humblebeee** [comment]
I'm also affected by this!

```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz failed: class java.io.IOException Read timed out
ERROR: An error occurred during the fetch of repository 'llvm-raw':
   Traceback (most recent call last):
	File "/mnt/Backup/Applications/Development/tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /home/username/.cache/bazel/_bazel_username/64b0952aa88675c4d81c032149f130ce/external/llvm-raw/temp8760388878851899350/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
ERROR: /mnt/Backup/Applications/Development/tensorflow/WORKSPACE:11:14: fetching _tf_http_archive rule //external:llvm-raw: Traceback (most recent call last):
	File "/mnt/Backup/Applications/Development/tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /home/username/.cache/bazel/_bazel_username/64b0952aa88675c4d81c032149f130ce/external/llvm-raw/temp8760388878851899350/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
```

**Comment by gadagashwini** [comment]
Hi @danielgusland, Clear the cache by calling `bazel clean –expunge`
Command prompt must be `Run as Admin` for the bazel build of TensorFlow to be successful. Thank you!

**Comment by benbarsdell** [comment]
Same issue here. Note that the .zip version of the same URL works, so this does look like a GitHub issue.
I haven't tried it, but changing this line to .zip should work around it:
https://github.com/tensorflow/tensorflow/blob/master/third_party/llvm/workspace.bzl#L16

**Comment by danielgusland** [comment]
> Hi @danielgusland, Clear the cache by calling `bazel clean –expunge` Command prompt must be `Run as Admin` for the bazel build of TensorFlow to be successful. Thank you!

Thank you for the response.

Unfortunately, neither clean or run as admin helps in this case. 
As mentioned by @nSircombe mentions; a simple wget times out too. 

Most likely a github server issue, but all their status flags are green.

**Comment by benbarsdell** [comment]
Clarifying my earlier comment, here is a patch that can be used to work around this issue:
```
diff --git a/third_party/llvm/workspace.bzl b/third_party/llvm/workspace.bzl
index 82d0f71ccbd..6a5cd8e61b5 100644
--- a/third_party/llvm/workspace.bzl
+++ b/third_party/llvm/workspace.bzl
@@ -5,15 +5,14 @@ load("//third_party:repo.bzl", "tf_http_archive")
 def repo(name):
     """Imports LLVM."""
     LLVM_COMMIT = "1cb299165c859533e22f2ed05eb2abd5071544df"
-    LLVM_SHA256 = "5a19ab6de4b0089fff456c0bc406b37ba5f95c76026e6bec294ec28dc28e4cb9"
+    LLVM_SHA256 = "10937113be5c7c551cffd7accf426e35b9071cac3251cb2b711076bdda0e98ea"
 
     tf_http_archive(
         name = name,
         sha256 = LLVM_SHA256,
         strip_prefix = "llvm-project-{commit}".format(commit = LLVM_COMMIT),
         urls = [
-            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/{commit}.tar.gz".format(commit = LLVM_COMMIT),
-            "https://github.com/llvm/llvm-project/archive/{commit}.tar.gz".format(commit = LLVM_COMMIT),
+            "https://github.com/llvm/llvm-project/archive/{commit}.zip".format(commit = LLVM_COMMIT),
         ],
         build_file = "//third_party/llvm:llvm.BUILD",
         patch_file = ["//third_party/llvm:macos_build_fix.patch"],
```

**Comment by humblebeee** [comment]
> Clarifying my earlier comment, here is a patch that can be used to work around this issue:
> 

Thank you for the workaround! I did get a similar warning but my build now running :
```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/11b2812d64e49bab9b6c489f79067fc94e69db9f.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

**Comment by nSircombe** [comment]
Thanks @benbarsdell, that work around has my build working again. 
I found the same issue on a build off of the r2.9 branch, which is a different archive, but a similar fix works there too.

**Comment by Arnold1** [comment]
@aseaday still see - I changed the LLVM_SHA256 according to your info:
```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

more infos here:
https://github.com/google/yggdrasil-decision-forests/issues/23

**Comment by aseaday** [comment]
> 

I think the 404 error was caused by simply there is no mirror on bazel or googleapis.

**Comment by Arnold1** [comment]
you mean its a transient warning/error?

**Comment by npanpaliya** [comment]
We (Open-CE team)  are also facing the same problem since yesterday. I can't build TF 2.8 and TF 2.9.1 due to this. .zip format is being downloaded but not .tar.gz format. The recent commits of llvm-project are being downloaded in .tar.gz format.
I'd raised these two issues - 
1. https://github.com/llvm/llvm-project/issues/56177
2. https://support.github.com/ticket/personal/0/1681014

Patching workspacebzl file as mentioned in one of the comments works. This issue is seen even with tensorflow-text and tensorflow-serving builds.

**Comment by nSircombe** [comment]
The latest update to the commit hash in `third_party/llvm/workspace.bzl` - https://github.com/tensorflow/tensorflow/commit/c1b086bfce8ef6bd67082be3f1e70b835ad00236 now tries to download a tarball that _does_ exist, so the fixup shouldn't be needed for nightly builds anymore (for now at least!)
However, that still leaves the 2.9 release branch broken - will this branch be re-opened and patched to pickup the .zip?

**Comment by ratan-prasad** [comment]
We are also facing the issue with 2.9 release branch. Patching workspacebzl file as mentioned in one of the comments works.

**Comment by npanpaliya** [comment]
The tars are fixed by Github. I could download both the commits of llvm-project in the form of .tar.gz.

**Comment by danielgusland** [comment]
As @npanpaliya noted, the tars are fixed. Closing issue.

**Comment by H-s-O** [comment]
The .tar.gz downloads are still not completely fixed; I get random download failures, then starts working again when retrying a few minutes later.

**Comment by npanpaliya** [comment]
Yes, I too see it intermittently. But Github support confirmed that llvm project was unstable last weekend and they have fixed it.
