### ISSUE TITLE
TF fails to build on CPU when compiled with "-march=skylake-avx512" flag

### ISSUE THREAD

**Issue by bhavani-subramanian** [tensorflow/tensorflow#56731]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9.12

### Bazel version

5.1.1

### GCC/Compiler version

9.3.0

### Current Behaviour?

```shell
Starting from 74059203de9c21ca26b27ea7609d49b3c87f2c19 commit, TF fails to build when compiled with `--copt=-march=skylake=avx512` flag on Cascade Lake (CLX) CPU systems or higher. The compilation succeeds when this flag is not passed.
```

### Standalone code to reproduce the issue

```shell
Command-line to trigger the build failure (on 74059203de9c21ca26b27ea7609d49b3c87f2c19 or newer commit):
bazel build --copt="-O3" --copt=-march=skylake-avx512 -c opt //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorContraction.h:250:5: error: ambiguous template instantiation for 'struct EigenForTFLite::internal::gemm_pack_rhs<float, long int, EigenForTFLite::internal::TensorContractionSubMapper<float, long int, 0, EigenForTFLite::TensorEvaluator<const EigenForTFLite::TensorReshapingOp<const EigenForTFLite::DSizes<long int, 2>, const EigenForTFLite::TensorImagePatchOp<-1, -1, const EigenForTFLite::TensorMap<EigenForTFLite::Tensor<const float, 4, 1, long int>, 16> > >, EigenForTFLite::ThreadPoolDevice>, std::array<long int, 1>, std::array<long int, 1>, 16, true, false, 0, EigenForTFLite::MakePointer>, 8, 0, false, false>' 
  250 |     RhsPacker()(*rhsBlock, data_mapper, depth, cols); 
      |     ^~~~~~~~~~~
```
</details>

**Comment by bhavani-subramanian** [comment]
Tagging @cantonios and @penpornk to take a look at this issue.

**Comment by cantonios** [comment]
@bhavani-subramanian can you try hacking this at the top of `tensorflow/core/kernels/eigen_spatial_convolutions.h`, before including Eigen's `Tensor` header?
```
// Hack to disable breaking AVX512 special GemmKernel.
// There is a conflicting specialization there causing build breakages.
#define GEMM_KERNEL_H disabled
```

I *think* this should solve it temporarily to unblock you, but I'm having trouble actually building this on our end.

**Comment by agramesh1** [comment]
@cantonios thank for the quick response. We tried the change, it looks like it is still failing with ambiguous template instantiation error.
```
./tensorflow/core/kernels/eigen_contraction_kernel.h:665:9: error: ambiguous template instantiation for 'struct Eigen::internal::gemm_pack_rhs<float, long int, Eigen::internal::TensorContractionSubMapper<float, long int, 0, Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<const Eigen::DSizes<long int, 2>, const Eigen::TensorImagePatchOp<-1, -1, const Eigen::TensorMap<Eigen::Tensor<const float, 4, 1, long int>, 16, Eigen::MakePointer> > >, Eigen::ThreadPoolDevice>, Eigen::array<long int, 1>, Eigen::array<long int, 1>, 16, true, true, 0, Eigen::MakePointer>, 8, 0, false, false>'
         EigenRhsPacker()(rhsBlock->packed_data, data_mapper, depth, cols);     \
         ^~~~~~~~~~~~~~~~
```

**Comment by agramesh1** [comment]
@cantonios the https://github.com/tensorflow/tensorflow/commit/a92b70238d9defce6f977fe104e1e8d3c87b89f4 fixes the issue, TF builds with AVX512. Thanks.
