### ISSUE TITLE
max_pool3d output shape is more undefined than input shape

### ISSUE THREAD

**Issue by dm0** [tensorflow/tensorflow#5807]
It looks like `tf.nn.max_pool3d` returns wrong output shape:

```
tf.nn.max_pool3d(tf.placeholder(tf.float32, [None, None, 100, 100, 1]), [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], 'VALID')
```

returns following tensor: 
`<tf.Tensor 'MaxPool3D_6:0' shape=(?, ?, ?, ?, 1) dtype=float32>`

I believe that dimensions 2 and 3 (counting from 0) should not be undefined.

In similar situation `tf.nn.max_pool` returns correct result.

```
tf.nn.max_pool(tf.placeholder(tf.float32, [None, None, 100, 1]), [1, 1, 1, 1], [1, 1, 1, 1], 'VALID')
```
produces: 
`<tf.Tensor 'MaxPool_3:0' shape=(?, ?, 100, 1) dtype=float32>`

### Environment info
Operating System: Linux
Tensorflow version: v0.11.0 (282823b877f173e6a33bbc9d4b9ad7dd8413ada6), built from sources with bazel 0.4.0

**Comment by prb12** [comment]
@vrv Shape function problem with max_pool_3d?

**Comment by vrv** [comment]
Probably: https://github.com/tensorflow/tensorflow/blob/61a099fda0dbb91e99c83436da0af20ca991ed9e/tensorflow/core/framework/common_shape_fns.cc#L560  I think we can just remove that if statement and it'll work.  I'll send a PR later today.

**Comment by vrv** [comment]
I made the change internally today, should be fixed on the next internal push.

**Comment by prb12** [comment]
@vrv Thanks for the rapid fix!

@dm0 Please reopen if this doesn't solve your problem.

**Comment by vrv** [comment]
the next push should close the bug automatically when it's available.  leaving open until then.
