### ISSUE TITLE
Conv2d with bfloat16: Incompatible type conversion requested to type 'float32' for AutoCastVariable which is casted to type 'bfloat16'

### ISSUE THREAD

**Issue by yufang67** [tensorflow/tensorflow#58347]
### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

CentOS 7.9.2009

### Python version

3.8.10

### CUDA/cuDNN version

11.7/8

### Current Behaviour?

```shell
In eager mode, obtain error on calling the layer.
In graph mode, run correctly. (use disable_eager_execution(), suggest in https://github.com/tensorflow/tensorflow/issues/57411)

Expected behaviour: 
is there a way to use conv2d layer with bfloat16 also in the eager mode ?
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import mixed_precision
#from tensorflow.python.framework.ops import disable_eager_execution
#disable_eager_execution()

policy = mixed_precision.Policy('mixed_bfloat16')
mixed_precision.set_global_policy(policy)

input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
layer = tf.keras.layers.Conv2D(2, 3, activation='relu', input_shape=input_shape[1:])
y = layer(x)
print(y.dtype, layer.dtype)
```

### Relevant log output

```shell
2022-10-27 17:31:17.863689: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-27 17:31:18.234594: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 78715 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0001:00:00.0, compute capability: 8.0
Traceback (most recent call last):
  File "test_bfloat16.py", line 35, in <module>
    y = layer(x)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/mixed_precision/autocast_variable.py", line 140, in _dense_var_to_tensor
    raise ValueError(
ValueError: Exception encountered when calling layer "conv2d" (type Conv2D).

Incompatible type conversion requested to type 'float32' for AutoCastVariable which is casted to type 'bfloat16'

Call arguments received by layer "conv2d" (type Conv2D):
  • inputs=tf.Tensor(shape=(4, 28, 28, 3), dtype=bfloat16)
```

**Comment by tilakrayal** [comment]
@yufang67,
This issue was resolved on tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/09ffac66f42b89708ef5efbdfa362c11/untitled718.ipynb). Also please take a look at this comment from the [issue1](https://github.com/tensorflow/tensorflow/issues/55738) and [issue2](https://github.com/tensorflow/tensorflow/issues/56680#issuecomment-1233728566) for the reference. Thank you!

**Comment by yufang67** [comment]
Thanks @tilakrayal for the response. it works with tf-nightly. i have 2 follow-up questions:
1. it seems that the LSTM still does not work with bfloat16 in eager mode. Will it be supported in the future ?
2. with mixed_bfloat16, Dense layer and Conv2D seems running on CPU. It will be less performant than mixed_float16 running on GPU ?

**Comment by yufang67** [comment]
Thanks @tilakrayal for the responds. It works with tf-nightly. I have 2 follow-up questions:
1. with tf-nightly and mixed_bfloat16, i obtained 
- I tensorflow/core/common_runtime/placer.cc:114] Conv2D: (Conv2D): /job:localhost/replica:0/task:0/device:CPU:0
- I tensorflow/core/common_runtime/placer.cc:114] BiasAdd: (BiasAdd): /job:localhost/replica:0/task:0/device:CPU:0
- I tensorflow/core/common_runtime/placer.cc:114] Relu: (Relu): /job:localhost/replica:0/task:0/device:CPU:0
It means the conv2D run on cpu, is that correct ? how is the performance compared to use mixed_float16 on GPU? what happened if the CUP does not support bfloat16 ?
2. It seems LSTM still does not support bfloat16. will it be supported in the future ?

**Comment by tilakrayal** [comment]
@yufang67,
Glad the issue was resolved on tf-nightly version. As the workaround for the bfloat16, please try to execute the code with below comments.
**from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()**

Also please move this issue to closed status and feel free to open a new feature request. Thank you!

**Comment by yufang67** [comment]
@tilakrayal yes, on graph mode it also works on 2.9.1. it does not support on eager mode yet, right?

**Comment by tilakrayal** [comment]
@yufang67,
As mentioned above, please try to disable the eager execution for the bfloat16 and  please move this issue to closed status and feel free to open a new feature request for the lstm and fbloat16. Thank you!

**Comment by yufang67** [comment]
Hi @tilakrayal, 
i didn't think this issue is resolved, because when you check the my original questions, i have already tried disable eager execution. 
For short, my question is how i can run bfloat16 in multiGPU training in eager mode ?
If you want i can close this one and open a new one just by changing the title.
thanks

**Comment by tilakrayal** [comment]
@yufang67,
From the [gist](https://colab.research.google.com/gist/tilakrayal/09ffac66f42b89708ef5efbdfa362c11/untitled718.ipynb) attached, the above issue got fixed in the nightly version. For **LSTM support bfloat16** feel free to open a new feature request from [here](https://github.com/tensorflow/tensorflow/issues/new) which helps us to track the issue easily. Thank you!

**Comment by yufang67** [comment]
Is there new update on this ticket ? 
from the previous tests:
if use eager mode, the ops run on CPU.
if use graph mode, the ops run on GPU.
if there is a way to run on GPU with mixed_bfloat16 on eager mode?

thanks,
