### ISSUE TITLE
TensorArray failure with automatic gradient computation for nested scan/map_fn/fold

### ISSUE THREAD

**Issue by trubin** [tensorflow/tensorflow#593]
I drew up this simple example to show that nested While gradient computation fails in the python interface (as the gradContext for the forwardContext of the second input of the Add op is None). Toggling the comment demonstrates the issue is not with all control flow graphs.

```python
import tensorflow as tf
from tensorflow.python.ops import control_flow_ops

OUTER_LOOP_MAX = 5
INNER_LOOP_MAX = 3

inner = tf.placeholder("float32", [1, INNER_LOOP_MAX])
outer = tf.placeholder("float32", [1, OUTER_LOOP_MAX])

X = tf.Variable(tf.zeros([1], dtype="float32"))

max = tf.constant(1)

def outer_cond_func(c1, outer_acc, outer_array):
    return tf.less(c1, OUTER_LOOP_MAX)


def outer_body_func(c1, outer_acc, outer_array):
    concat = tf.concat(0, [[0], tf.expand_dims(c1, 0)])
    slice = tf.slice(outer_array, concat, [1, 1])
    outer_num = tf.reduce_sum(slice)

    def inner_cond_func(c2, inner_acc, inner_array):
        return tf.less(c2, INNER_LOOP_MAX)

    def inner_body_func(c2, inner_acc, inner_array):
        concat2 = tf.concat(0, [[0], tf.expand_dims(c2, 0)])
        inner_num = tf.reduce_sum(tf.slice(inner_array, concat2, [1,1]))
        inner_acc += inner_num * outer_num * X

        c2 += 1
        return c2, inner_acc, inner_array

    _, inside_summed_products, _ = control_flow_ops.While(inner_cond_func, inner_body_func, [tf.constant(0), tf.constant(0.0), inner])

    def true_func():
        return 2*outer_num

    def false_func():
        return 3*outer_num

    cond_num = control_flow_ops.cond(tf.less(c1,max),true_func, false_func)
    outer_acc = tf.add(outer_acc, inside_summed_products)
    # outer_acc = tf.add(outer_acc, cond_num)
    c1 += 1
    return c1, outer_acc, outer_array

_, value, _ = control_flow_ops.While(outer_cond_func, outer_body_func, [tf.constant(0), tf.constant(0.0), outer])
control_flow_ops.switch()

loss = value * X
train_op = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(loss)

sess = tf.Session()
init = tf.initialize_all_variables()
sess.run(init)

for i in xrange(1, 10):
    feed_dict = {inner: [[1.0, 2.0, 3.0]], outer: [[4.0, 5.0, 6.0, 7.0, 8.0]]}
    print sess.run([train_op, loss], feed_dict=feed_dict)
```

**Comment by arcecio** [comment]
+1

**Comment by ebrevdo** [comment]
Thank you for reporting this issue.

While is not a documented feature, partly because of issues like this.  We
will work on it but make no promises as to when it'll be ready.

**Comment by trubin** [comment]
Cool. I'm happy to help work on it. Vijay suggested I post the bug in case you guys were changing things there, just so you knew I was doing it. I'm still having trouble getting my dev environment set up (being able to just test the python changes without bazel recompiling all the c++ every time I make a small change to the python code), but hopefully I'll get that resolved soon.

**Comment by ebrevdo** [comment]
You should be able to rerun your python test directly from bazel-bin
between changes (the underlying code should be symlinked to the source
code) without rerunning bazel test ....

**Comment by trubin** [comment]
Thanks, I have got it working in my debugger, though I have to manually edit the auto generated bazel test file because even though I make changes to kernel_tests/control_flow_ops_test.py before i run "bazel test //tensorflow/python:control_flow_ops_py_test", the generated file in bazel-bin/tensorflow/python/control_flow_ops_py_test.runfiles/tensorflow/python/kernel_tests/control_flow_ops_test.py doesn't include my changes (this seems to be the only file that isn't a symlink). Maybe this is a different bug?

**Comment by trubin** [comment]
I believe the bug is caused by the following logic:

When computing a gradient (gradients.py::gradients() function), the has_control_flow bool is set to true when there is an "Exit" op anywhere in the subgraph under consideration (comes from _PendingCount()). Obviously this is true for a nested while. As we visit all the ops in the subgraph in reverse order [op being iterated in a queue of ops] , op is told that it is in a GradWhileContext through the function control_flow_ops.EnterGradWhileContext(op) (this is the only place in the code that function is called). EnterGradWhileContext creates a grad_ctxt for op's control_flow_context assuming that the control_flow_context is a WhileContext. 

So far so good. The issue is that in a nested While, presumably the output of the inner while will be used as the input to some node used in returning the output of the outer While, so the op associated with the op of the inner while output tensor will not have made it into the queue of ops before the tensor is needed as an input, and so will never have EnterGradWhileContext called on it. 

I modifying EnterGradWhileContext to search down the tree of input ops/output tensors so that a grad_ctxt is created and entered recursively for all ops to be used, and then similarly the whole tree exited when ExitGradWhileContext is called on an op.

Not sure who might be able to let me know if this is a good idea or not?

**Comment by trubin** [comment]
I see that this is significantly more complicated than just entering a GradWhileContext for each input as the frame has to be the same when the Executor tries to run the kernels. Currently focusing on the forwardAccumulator of historical values for a given context to see if I can get the frames to match up.

**Comment by alrojo** [comment]
@trubin are you still working on this?

**Comment by ebrevdo** [comment]
This should have been fixed at head.

**Comment by trubin** [comment]
I am still getting the error in 0.7.1. See the following test that demonstrates the error:

import tensorflow as tf
from tensorflow.python.ops import control_flow_ops

OUTER_LOOP_MAX = 5
INNER_LOOP_MAX = 3

inner = tf.placeholder("float32", [INNER_LOOP_MAX])
outer = tf.placeholder("float32", [OUTER_LOOP_MAX])

X = tf.Variable(tf.zeros([1], dtype="float32"))


def outer_cond_func(c1, outer_acc, outer_array):
    return tf.less(c1, OUTER_LOOP_MAX)


def outer_body_func(c1, outer_acc, outer_array):
    slice = tf.slice(outer_array, tf.expand_dims(c1, 0), [1])
    outer_num = tf.reduce_sum(slice)

    def inner_cond_func(c2, inner_acc, inner_array):
        return tf.less(c2, INNER_LOOP_MAX)

    def inner_body_func(c2, inner_acc, inner_array):
        inner_num = tf.reduce_sum(tf.slice(inner_array, tf.expand_dims(c2, 0), [1]))
        inner_acc += inner_num * outer_num * X

        c2 += 1
        return c2, inner_acc, inner_array

    _, inside_summed_products, _ = control_flow_ops.While(inner_cond_func, inner_body_func, [tf.constant(0), tf.constant(0.0), inner])

    outer_acc = tf.add(outer_acc, inside_summed_products)
    c1 += 1
    return c1, outer_acc, outer_array

_, value, __ = control_flow_ops.While(outer_cond_func, outer_body_func, [tf.constant(0), tf.constant(0.0), outer])

loss = value * X
train_op = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(loss)

sess = tf.Session()
init = tf.initialize_all_variables()
sess.run(init)

for i in xrange(1, 10):
    feed_dict = {inner: [1.0, 2.0, 3.0], outer: [4.0, 5.0, 6.0, 7.0, 8.0]}
    print sess.run([train_op, loss], feed_dict=feed_dict)

**Comment by trubin** [comment]
To be a little clearer, the error happens at graph construction time (see below). I'd be really excited to help solve this bug, but the last time I went down this path it turned out major changes were being made to the entire ControlFlow infrastructure. Could you let me know if that's the case again? 

Thanks,
Tyler

Traceback (most recent call last):
  File "/home/tyler/code/Sphere/SideProjects/TKGVS/test.py", line 40, in <module>
    train_op = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 190, in minimize
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 241, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients.py", line 481, in gradients
    in_grads = _AsList(grad_fn(op, *out_grads))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_grad.py", line 365, in _MulGrad
    return (array_ops.reshape(math_ops.reduce_sum(grad * y, rx), sx),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 502, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 829, in mul
    return _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2104, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1133, in __init__
    self._control_flow_context.AddOp(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1286, in AddOp
    self._AddOpInternal(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1307, in _AddOpInternal
    self.AddValue(x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1244, in AddValue
    real_val = grad_ctxt.grad_state.GetRealValue(val)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 655, in GetRealValue
    h_value = cur_grad_state.AddForwardAccumulator(cur_value)
AttributeError: 'NoneType' object has no attribute 'AddForwardAccumulator'

**Comment by yuanbyu** [comment]
Yes, we made some major changes to support nested loops.  There is no pending major changes in the pipeline for now.  You are welcome to take a look at this problem.

**Comment by ebrevdo** [comment]
(I do suggest trying to get a PR in in the next couple of weeks, though)

**Comment by trubin** [comment]
Hey all, sorry I haven't been able to get to this until now. @yuanbyu from the todos in the code it looks like you might have been involved in writing control_flow_ops.py. I'm looking at the function GetRealValue , and I'm a little confused by this code (line 635-636 of control_flow_ops.py in 7003b76)  :

          if self._outer_grad_state:
            cur_grad_state = cur_grad_state.outer_grad_state

It would appear that you are verifying that self._outer_grad_state is not None in the if block, but then attempting to access cur_grad_state.outer_grade_state, so maybe the check should be that cur_grad_state.outer_grad_state is not None?

**Comment by sherjilozair** [comment]
Tensorflow is still not able to handle backprop over nested scans.

@yuanbyu @ebrevdo, any updates on this?

**Comment by ebrevdo** [comment]
This is a known limitation :(

This will require some revamping of the TensorArray and a bit of additional
work, to make it happen.  No ETA right now.

**Comment by cesc-park** [comment]
+1
Still not able to handle backprop over nested while loops.

**Comment by ucabmrn** [comment]
+1, this functionality would be super useful for some stuff I am working on.

**Comment by ebrevdo** [comment]
ACT only requires a while_loop inside the rnncell, not a scan, and does not require TensorArray except in the outer dynamic_rnn call. You should be able to implement it without running into this bug.

**Comment by ebrevdo** [comment]
Still no eta for fixing nested scan.

**Comment by ucabmrn** [comment]
@ebrevdo, thanks for your hints - I have created a SO for a question I have regarding this; your TF wisdom would be gratefully received. 
http://stackoverflow.com/questions/37822097/using-tensorarrays-in-the-context-of-a-while-loop-to-accumulate-values

**Comment by ebrevdo** [comment]
nested functional ops should now work (or at least the change will be pushed to github w/in the next week).  reopen if you're still having a problem after the next push.

**Comment by trubin** [comment]
You guys rock, thanks.

**Comment by ucabmrn** [comment]
Sweet. Cheers!

**Comment by stilda** [comment]
Hi, I use r0.9 version but still have an error when use nested map_fn and a variable involved in calculations of inner function.

The error is 

tensorflow.python.framework.errors.InvalidArgumentError: Input 0 of node gradients/map/while/map/TensorArrayPack_grad/TensorArrayGrad/TensorArrayGrad was passed string from gradients/map/while/map/TensorArrayPack_grad/TensorArrayGrad/TensorArrayGrad/StackPop:0 incompatible with expected string_ref.

The code is
`import tensorflow as tf

def inner_loop(t):
	def fn(n): return n + var # using var here leads to the error.
	return tf.map_fn(fn=fn, elems=t, parallel_iterations=1)

def outer_loop(input):
	def fn(n): return inner_loop(n) #if I would return inner_loop(n)+var here no errors appear.
	return tf.map_fn(fn=fn, elems=input, parallel_iterations=1)

with tf.Session() as sess:
	var = tf.Variable(tf.constant(1.0))
	input = tf.to_float(tf.convert_to_tensor([[1,2],[3,4],[5,6]]))
	res = outer_loop(input)
	optimizer = tf.train.AdamOptimizer(learning_rate=0.001)
	trainOperation = optimizer.minimize(tf.reduce_mean(tf.square(res)))

	sess.run(tf.initialize_all_variables())
	sess.run(trainOperation)`

Am I missing something?

**Comment by msevrens** [comment]
This appears to still be an issue

**Comment by ebrevdo** [comment]
Fix should be available w/in a week or so.

**Comment by yuanbyu** [comment]
A possible fix should be available in the next push.

**Comment by msevrens** [comment]
👍

**Comment by shengc** [comment]
This issue still persists, and it is already 2018. Shouldn't this be given high priority to work on ? Without nested higher order function, mini batch program won't be possible for a number of algorithms to be implemented in TensorFlow.

**Comment by ebrevdo** [comment]
@shengc please open a bug with details about what version of TF you're using and a minimal reproducible example, and we'll look into it.

**Comment by shengc** [comment]
@ebrevdo opened issue here: https://github.com/tensorflow/tensorflow/issues/17555
