### ISSUE TITLE
Segfault when running tensorflow.python.ops.gen_string_ops.string_format

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59387]
### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Segmentation fault when feeding the following input combinations.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_string_ops
try:
  arg_0_0_tensor = tf.cast(tf.random.uniform([100, 100], minval=0, maxval=2, dtype=tf.int32), dtype=tf.bool)
  arg_0_0 = tf.identity(arg_0_0_tensor)
  arg_0 = [arg_0_0,]
  template = "{}"
  placeholder = ""
  summarize = False
  out = gen_string_ops.string_format(arg_0,template=template,placeholder=placeholder,summarize=summarize,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-21 19:56:19.403127: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-21 19:56:20.109647: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/
2023-01-21 19:56:20.109849: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/:/home/nimashiri/anaconda3/envs/cuda11.2/lib/
2023-01-21 19:56:20.109858: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-01-21 19:56:20.744012: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 19:56:20.749087: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 19:56:20.749223: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 19:56:20.749553: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-21 19:56:20.750231: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 19:56:20.750354: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 19:56:20.750461: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 19:56:21.186117: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 19:56:21.186259: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 19:56:21.186365: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-21 19:56:21.186458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4238 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
Segmentation fault

```
```

**Comment by synandi** [comment]
@nimashiri 
You are sending invalid inputs to the API. Please note that the summarize attribute takes an integer value and prints the first and last summarized entries of each tensor when formatting the tensor summaries. Please find the gist  of working code [here](https://colab.sandbox.google.com/gist/synandi/f0ae81b576e97b44877b3114ec03d76c/59387.ipynb). Thank you!

**Comment by nimashiri** [comment]
> @nimashiri You are sending invalid inputs to the API. Please note that the summarize attribute takes an integer value and prints the first and last summarized entries of each tensor when formatting the tensor summaries. Please find the gist of working code [here](https://colab.sandbox.google.com/gist/synandi/f0ae81b576e97b44877b3114ec03d76c/59387.ipynb). Thank you!

I am fuzz testing tensorflow backend.

**Comment by synandi** [comment]
@nimashiri, In tf-nightly, the above code is not causing Segfault. The summarize argument is considering False as 0 and True as 1 and producing valid outputs. Please find the gist [here](https://colab.sandbox.google.com/gist/synandi/9baf0328bf3aa26f572cc2a2438558ff/59387_tf-nightly.ipynb). Thank you!

**Comment by nimashiri** [comment]
> @nimashiri, In tf-nightly, the above code is not causing Segfault. The summarize argument is considering False as 0 and True as 1 and producing valid outputs. Please find the gist [here](https://colab.sandbox.google.com/gist/synandi/9baf0328bf3aa26f572cc2a2438558ff/59387_tf-nightly.ipynb). Thank you!

Would you please run on TF-2.11 and confirm if you get segfaults?

**Comment by mihaimaruseac** [comment]
If nightly does not show it it means it got resolved based on a report coming from elsewhere. On the next release, if the report is from external researcher, they will get credit.

**Comment by synandi** [comment]
@nimashiri, 
When run on TF v2.11 the kernel is crashing with warnings, please refer to the image below 
![image](https://user-images.githubusercontent.com/98147397/216002631-0c2c61ec-6e12-49c4-9b4c-7d8239cfde35.png)

The above code is generating the expected output when using tf-nightly version 2.12.0.dev20230127. Please find the output below;

**Output:**
```
tf.Tensor(b'{}', shape=(), dtype=string)
```
Thank you!

**Comment by mihaimaruseac** [comment]
It means the issue has been fixed. Most likely by https://github.com/tensorflow/tensorflow/commit/6d423b8bcc9aa9f5554dc988c1c16d038b508df1

Closing this as resolved.

**Comment by dmc1778** [comment]
> It means the issue has been fixed. Most likely by [6d423b8](https://github.com/tensorflow/tensorflow/commit/6d423b8bcc9aa9f5554dc988c1c16d038b508df1)
> 
> Closing this as resolved.

I am still getting segfault and Abort with the following test case:

```
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_string_ops
try:
  arg_0_0_tensor = tf.cast(tf.random.uniform([10], minval=0, maxval=2, dtype=tf.int32), dtype=tf.bool)
  arg_0_0 = tf.identity(arg_0_0_tensor)
  arg_0 = [arg_0_0,]
  template = "{}"
  placeholder = "{}"
  summarize = 0.0
  out = gen_string_ops.string_format(arg_0,template=template,placeholder=placeholder,summarize=summarize,)
except Exception as e:
  print("Error:"+str(e))

```

Output:

```
2023-08-13 01:17:37.272600: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-08-13 01:17:38.161562: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:17:38.183248: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:17:38.183441: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:17:38.183987: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-13 01:17:38.184613: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:17:38.184759: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:17:38.184884: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:17:38.237798: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:17:38.237990: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:17:38.238127: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-08-13 01:17:38.238236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2530 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
Segmentation fault

```
