### ISSUE TITLE
[Windows] TensorBoard doesn't work

### ISSUE THREAD

**Issue by wkcw** [tensorflow/tensorflow#5983]
I installed the tensorflow for windows with
`pip install --upgrade --ignore-installed https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl`
(I added the '--ignore-installed', for the official one didn't work on my pc)

Then I tried some code and ran tensorboard, however the browser shows nothing 
When running with '--debug' there appears some 404.
I also tried tensorboard on mac os, it worked well, so the problem is not caused by the .tfevent file
I've read through a bunch of related issues, and found that maybe the pip install didn't install tensorflow completely. And I searched the tensorflow file and did not found some certain files appears in mac os tensorflow, such as 'paper-toolkit'

**Comment by ytorii** [comment]
Have you tried `pip install tensorflow` as [this post](https://developers.googleblog.com/2016/11/tensorflow-0-12-adds-support-for-windows.html) says?

**Comment by Carmezim** [comment]
@wkcw If you have Python 3.5 64-bit installed (from python.org or anaconda) you only need:
`pip install tensorflow`
And for GPU use:
`pip install tensorflow-gpu`
The latter require CUDA 8.0 and cudnn 5.1.

**Comment by aaronzs** [comment]
check [this](https://github.com/tensorflow/tensorflow/pull/5844)

**Comment by mrry** [comment]
As @aaronzs observes, TensorBoard currently doesn't work on Windows. #5844 could work, but the TensorBoard team is changing the way they handle external packages, so a different approach might be necessary.

@danmane Do you have an estimate of when this will be ready?

**Comment by mrry** [comment]
We just merged #5844, which adds TensorBoard support to the master branch. #6020 will add support to the r0.12 branch, and it should appear in the final release.

**Comment by drasmuss** [comment]
I am still getting this issue after `pip` installing the latest version (`0.12.0-rc0`).  Did this make it into the release?

**Comment by mrry** [comment]
@drasmuss We haven't made a new release since the #5844 was merged. You can either build it yourself, download a [nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/), or wait a few more days until we have a new release candidate.

**Comment by mrry** [comment]
I'm closing this for now, since the fix is in. At present, only nightly builds have the fix, but they should be in the imminent `0.12.0rc1` release as well.

**Comment by helenahan2015** [comment]
@mrry In Tensorflow protal, there is a command with 0.12.0rc1 version for Windows. 
![image](https://cloud.githubusercontent.com/assets/16149289/21174325/7804e11c-c217-11e6-97cd-82610917d196.png)
But it can't be executed because there is still only 0.12.0rc0 version for Windows in https://storage.googleapis.com/tensorflow/ 
![image](https://cloud.githubusercontent.com/assets/16149289/21174362/a8026aa6-c217-11e6-834b-55ef19a3029c.png)
May I know when the 0.12.0rc1 version will be available for Windows system?

**Comment by emodark** [comment]
I have the problem of the tensorboard cannot show the event data in windows10, 64-bit, tensorflow-gpu-.12.0rc1; it can be solved by making the "tensorborad.exe" and the event file in the same disk.

**Comment by mrry** [comment]
@emodark: This is a known issue with TensorBoard, because it uses the `:` character in its flags in a way that's incompatible with Windows paths. See #7856 for more discussion and a potential workaround.

**Comment by hipoglucido** [comment]
Which is the current state? is it already possible to run tensorflow on windows?

**Comment by mrry** [comment]
Yes, we have been publishing packages for TensorFlow (including TensorBoard) since the final release of version 0.12. AFAIK, the issue with Windows-style paths is still an open issue (see #7856) but there is a workaround that involves specifying a run name.

**Comment by hipoglucido** [comment]
Thanks for the fast response @mrry and for the work. Could you elaborate a bit more on that workaround you mention please?

**Comment by mrry** [comment]
Here's a [link](https://github.com/tensorflow/tensorflow/issues/7856#issuecomment-282617523) to the explanation.

**Comment by chihuahua** [comment]
Lets continue discussion of this issue within tensorflow/tensorboard#42. We have moved TensorBoard to a new repo outside of tensorflow/tensorflow.
