### ISSUE TITLE
Different prediction result for tf.learn QuickStart?

### ISSUE THREAD

**Issue by jacktang** [tensorflow/tensorflow#6119]
Hello,

Today I upgrade tensorflow package and read the [tutorials from the beginning](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/tutorials/tflearn/index.md).And find the result of classifier prediction is different, it is `[1, 1]`. I remember that the old version tf run out `[1, 2]`. So what's the problem?

The OS is OSX EI Capitan, and tensoflow is 0.12.0-rc0

``` 
$ `python -c "import tensorflow; print(tensorflow.__version__)"`
-bash: 0.12.0-rc0: command not found
```

If I turn on the INFO log level, the log lists below:
```
$ python iris_classifier.py
WARNING:tensorflow:From /Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:315 in fit.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:315 in fit.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:315 in fit.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with batch_size is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:TensorFlow's V1 checkpoint format has been deprecated.
WARNING:tensorflow:Consider switching to the more efficient V2 format:
WARNING:tensorflow:   `tf.train.Saver(write_version=tf.train.SaverDef.V2)`
WARNING:tensorflow:now on by default.
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:TensorFlow's V1 checkpoint format has been deprecated.
WARNING:tensorflow:Consider switching to the more efficient V2 format:
WARNING:tensorflow:   `tf.train.Saver(write_version=tf.train.SaverDef.V2)`
WARNING:tensorflow:now on by default.
WARNING:tensorflow:*******************************************************
WARNING:tensorflow:From /Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:323 in evaluate.: calling evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:323 in evaluate.: calling evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:323 in evaluate.: calling evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with batch_size is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Accuracy: 0.966667
WARNING:tensorflow:From /Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:348 in predict.: calling predict (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:348 in predict.: calling predict (from tensorflow.contrib.learn.python.learn.estimators.estimator) with batch_size is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
WARNING:tensorflow:From /Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py:348 in predict.: calling predict (from tensorflow.contrib.learn.python.learn.estimators.estimator) with as_iterable is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
Predictions: [1, 1]
```

**Comment by JerryX2014** [comment]
same issue with Linux server ( CentOS Linux release 7.2.1511 (Core) ) 
tensorflow version 0.12.0

I got the correct predictions [1,2] of my first run, but my following runs were all [1,1]...

**Comment by jackzzj** [comment]
same problem .. still no solution ?

**Comment by agriasgg** [comment]
Make sure you delete any pre-existing models. Assuming this is the iris tutorial take a look at 

``classifier = tf.contrib.learn.DNNClassifier(feature_columns=feature_columns,
                                            hidden_units=[10, 20, 10],
                                            n_classes=3,
                                            model_dir="/tmp/iris_model")
``

If you don't delete the files in ``model_dir="/tmp/iris_model"`` you will be modifying the old model rather than creating a new one.

**Comment by jacktang** [comment]
Update to tensorflow 0.12.1. It seems fixed.

**Comment by DanielTakeshi** [comment]
Also, does anyone have a way to get rid of the error messages? The API is deprecated and tf.contrib.learn keeps changing so it's a bit hard to keep track of API updates.

**Comment by XRayCheng** [comment]
I made a fix version of this here. Using the custom pipe lines.
https://github.com/XRayCheng/tensorflow_iris_fix

**Comment by tatatodd** [comment]
Looks like @jacktang said this was fixed in 0.12.1, and @XRayCheng has a fix.

I'm closing this out.  Feel free to file issues for new problems you may run in to!

**Comment by lukeed** [comment]
With v1.1.0, this issue still occurs. The first output is `[1,2]` and all subsequent runs are `[1,1]` until I destroy the `tmp` model.

@XRayCheng's "fix" is not actually a fix -- README still forewarns that all non-fresh runs will produce `[1,1]`.

Some kind of clarification would be nice. 😞 Picking up TF for the first time, and it's pretty rough when the main documentation examples aren't replicated locally.

**Comment by agriasgg** [comment]
@lukeed You've already found the solution. After you run the model once, it will be trained and stored in the tmp folder. If you do not delete the tmp folder you are retraining an existing model rather than doing one from scratch. It makes sense that it would have different results

**Comment by lukeed** [comment]
@agriasgg Thanks! But if that's truly the case, then that should be included as a note, imo. I was under the assumption that the model was _only_ looking at the same CSV data every time, which means it should have arrived to `[1,2]` every time. 

Nowhere in the example documentation did it say that every run was going to affect the subsequent outputs.
