### ISSUE TITLE
Building TFLite for Android with CMake cannot find -lpthread

### ISSUE THREAD

**Issue by lhchg** [tensorflow/tensorflow#62799]
**Issue type**
Build/Install

**Have you reproduced the bug with TensorFlow Nightly?**
Yes

**Source**
source

**TensorFlow version**
2.15

**Custom code**
Yes

**OS platform and distribution**
Ubuntu 22.04

**Mobile device**
No response

**Python version**
No response

**Bazel version**
No response

**GCC/compiler version**
cmake version 3.28.0-rc4

**CUDA/cuDNN version**
No response

**GPU model and memory**
No response

**Current behavior?**
Building label_image with CMake with GPU delegate 

**Standalone code to reproduce the issue**
```
cmake -DCMAKE_TOOLCHAIN_FILE=${android-ndk-r22}/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM="26" -DTFLITE_ENABLE_GPU=ON -DCMAKE_BUILD_TYPE=Debug ../tensorflow-2.15.0/tensorflow/lite/

make label_image -j32
```

**Relevant log output**
```
[ 60%] Built target absl_flags_reflection
[ 60%] Built target absl_status
[ 60%] Built target absl_flags
[ 95%] Built target tensorflow-lite
[ 95%] Linking CXX executable label_image
ld: error: unable to find library -lpthread
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [examples/label_image/CMakeFiles/label_image.dir/build.make:424: examples/label_image/label_image] Error 1
make[2]: *** [CMakeFiles/Makefile2:7481: examples/label_image/CMakeFiles/label_image.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:7488: examples/label_image/CMakeFiles/label_image.dir/rule] Error 2
make: *** [Makefile:2522: label_image] Error 2
```

**Comment by LakshmiKalaKadali** [comment]
Hi @lhchg,

Please try with the commit [00122c2](https://github.com/tensorflow/tensorflow/commit/00122c2341466bc1af8aab6e7f0cb607829a40bd).

Thank You

**Comment by poltomo** [comment]
I fixed it by just removing ```-lpthread``` from 
CMakeFiles/tensorflowlite_c.dir/link.txt

**Comment by ashwini778** [comment]
@LakshmiKalaKadali 

Tried this commit.
I am still facing the same issue.
