### ISSUE TITLE
TensorBoard's graph tab doesn't render in Firefox

### ISSUE THREAD

**Issue by MarkDaoust** [tensorflow/tensorflow#650]
TensorBoard's graph tab works fine in Chrome and Safari, but does not render in Firefox.

[A few other people have reported this issue](https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!topic/discuss/Lc7Y_6UEFOM).

**Comment by jaelim** [comment]
I also had an issue of producing a graph in Firefox. I hope they support the Firefox in Linux (I use Ubuntu) in near future.

**Comment by frankyjuang** [comment]
Most prople has this problem with firefox or safari. However, I am using **chromium 47.0**...
![image](https://cloud.githubusercontent.com/assets/6175880/12097756/72574918-b358-11e5-9ee7-285a6d05deb5.png)

**Comment by dsmilkov** [comment]
Fixed with 1c579361cd1e088dd5e05a394b1561a73e3667ba. The commit is very large since it bundled many changes, but the important change is in minimap.ts. Feel free to reopen if you ran into this change again. You won't see this fix before the next release unless you rebuild TensorBoard yourself following the instructions in the https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md

**Comment by MarkDaoust** [comment]
Great. It's working over here.

**Comment by frankyjuang** [comment]
@dsmilkov I built the latest version, however, the problem still exists. There's no error messages, only a warning in chrome console: 
```/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.```.
Btw, I adjusted a bit code in `google/protobuf/src/google/protobuf/io/coded_stream.h : 611`:
```
static const int kDefaultTotalBytesLimit = 256 << 20;  // 64MB
```
in order to load my large tensorflow log file. But I don't think this will cause problem.
I use Chrome 47.0. 
![image](https://cloud.githubusercontent.com/assets/6175880/12357264/e1120726-bbe1-11e5-8f6e-ad8e9df921c5.png)

**Comment by dsmilkov** [comment]
@frankyjuang The issue you are having might be unrelated to this issue, since you are already using Chrome and not Firefox. Can you share your log directory with us? You can gzip it and ideally attach it here to this issue, or email it to dsmilkov@gmail.com.

**Comment by frankyjuang** [comment]
Here is it. [Large log file](https://drive.google.com/file/d/0B7ldj0upUtbdNmNIcU81YUpBbVk/view?usp=sharing)
It is actually the image model inception v3. All  I have done is write the graph to this file. Thanks

**Comment by jaelim** [comment]
@dsmilkov Could you please explain where this directory (tensorflow/tensorboard) that the instructions in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md instructs you to do 3 installations? Is it in /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard, or the source (i.e. git clone) that you downloaded to your home directory?

**Comment by danmane** [comment]
You should only need to do those installations if you want to rebuild the frontend from source, in which case you would do this in the source (ie git clone) directory. 
For just running TensorBoard as a user, none of those commands are necessary.
