### ISSUE TITLE
Tensorboard stopped showing runs names

### ISSUE THREAD

**Issue by yuvval** [tensorflow/tensorflow#7039]
Hi,

Tensorboard stopped showing runs names.
I can still filter (blindly) and see the curves, but there are no names of the runs to filter.

Any idea on how to fix that?
TF is installed under anaconda.

It worked with no issues until 2 weeks ago. I got back to the project today and this issue occurred.
I tried reinstalling 0.11, or even installing the latest 0.12.1 (under conda-forge), but the issue hasn't solved.

I also tried (with no luck)
```
cd /home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/
python tensorboard.py --logdir=path/to/log
```

Attached is a screenshot, and below (the technical details) is the TB console output. Note that under TF12.1 there are no errors on the console output, but the issue still happens.

![screenshot from 2017-01-24 17 58 30](https://cloud.githubusercontent.com/assets/5911675/22257868/016e4ac2-e268-11e6-83a9-7e3b33ce5eae.png)

Thanks

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/1421
https://github.com/tensorflow/tensorflow/issues/5341

### Environment info
Operating System:
Ubuntu

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally                                    │······················
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally                                     │······················
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally                                     │······················
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally                                    │······················
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally                                    │······················
0.11.0rc0 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

```

$ tensorboard --port=8008 --logdir="./"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Starting TensorBoard 29 on port 8008
(You can navigate to http://XXXXXXXXXXXXXX:8008)
127.0.0.1 - - [24/Jan/2017 18:51:19] "GET / HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js' on path /home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/webcomponentsjs/webcomponents-lite.min.js
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/dist/bazel-html-imports.html' on path /home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/dist/bazel-html-imports.html
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/external/dist/bazel-html-imports.html' on path /home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/external/dist/bazel-html-imports.html
127.0.0.1 - - [24/Jan/2017 18:51:19] code 404, message Not Found
127.0.0.1 - - [24/Jan/2017 18:51:19] "GET /dist/bazel-html-imports.html HTTP/1.1" 404 -
127.0.0.1 - - [24/Jan/2017 18:51:19] "GET /dist/tf-tensorboard.html HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2017 18:51:19] "GET /lib/css/global.css HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2017 18:51:19] "GET /webcomponentsjs/webcomponents-lite.min.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/polymer/polymer.html' on path /home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/polymer/polymer.html
127.0.0.1 - - [24/Jan/2017 18:51:19] "GET /polymer/polymer.html HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/d3/d3.js' on path /home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/d3/d3.js
127.0.0.1 - - [24/Jan/2017 18:51:19] "GET /d3/d3.js HTTP/1.1" 200 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/plottable/plottable.js' on path /home/gamir/yuval/anaconda2/envs/tf_011/lib/python2.7/site-packages/tensorflow/tensorboard/plottable/plottable.js
127.0.0.1 - - [24/Jan/2017 18:51:20] "GET /plottable/plottable.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2017 18:51:20] "GET /data/runs HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2017 18:51:20] "GET /data/runs HTTP/1.1" 200 -
WARNING:tensorflow:Found more than one graph event per run. Overwriting the graph with the newest event.
WARNING:tensorflow:Detected out of order event.step likely caused by a TensorFlow restart. Purging expired events from Tensorboard display between the previous step: -1 (timestamp: -1) and current step: 20084 (timestamp: 1482950339.25). Removing 12 scalars, 23 histograms, 23 compressed histograms, 0 images, and 0 audio.

```

**Comment by drpngx** [comment]
@dandelionmane is that intentional?

**Comment by dandelionmane** [comment]
I suspect this is a screen resolution / zoom issue. The UI elements on the top left are fixed size, and the remainder goes to the run names. 

Can you try pressing (ctrl + -) or decreasing the zoom level in the browser, and report if that fixes it?

**Comment by yuvval** [comment]
Embarrassingly (for me) you were right :)
It happens with a 100% zoom, reducing the zoom to 75%, shows the list of runs. Any idea how to still show it with 100% zoom?

**Comment by dandelionmane** [comment]
@yuvval Try changing the resolution on the display. Or you can submit a pull request that reduces the space needed by the UI on the left :)

**Comment by yuvval** [comment]
@dandelionmane Thanks. I don't have permissions to change the resolution on that machine, nor knowledge of UI syntax to make a PR :)
