### ISSUE TITLE
OutOfRangeError/Early EOF on file read in Windows Server 2012

### ISSUE THREAD

**Issue by mawah** [tensorflow/tensorflow#7306]
Hi folks,

I am finding that tensorflow code snippets which ran on Windows 10 are failing on Windows Server 2012/NTFS. In particular, anytime I try to load a file (with `tf.gfile.Open`, `tf.gfile.FastGFile`, or `tf.contrib.slim.assign_from_checkpoint_fn`), I encounter an "out of range" error.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I found [Git issue #6791 (Contrib support for Windows) ](https://github.com/tensorflow/tensorflow/issues/6791) where it was suggested that the fault lies with contrib packages. However, the code sample I provide below displays the problem without using any contrib imports.

### Environment info
Operating System: Windows Server 2012 R2

Installed version of CUDA and cuDNN: N/A
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed: [tensorflow-0.12.1-cp35-cp35m-win_amd64.whl](https://pypi.python.org/packages/64/a3/0054a3329579de44d557f491adbcaf8127809a7992bc46af80f0a589e29b/tensorflow-0.12.1-cp35-cp35m-win_amd64.whl)
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. **0.12.1**

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
with tf.Graph().as_default():
        with tf.Session('') as sess:
                image_data = tf.gfile.FastGFile(filepath_to_image, 'r').read()
---------------------------------------------------------------------------
OutOfRangeError                           Traceback (most recent call last)
<ipython-input-11-a7847d42df75> in <module>()
      1 with tf.Graph().as_default():
      2     with tf.Session('') as sess:
----> 3         image_data = tf.gfile.FastGFile(training_filenames[0], 'r').read()
C:\Anaconda\envs\py35\lib\site-packages\tensorflow\python\lib\io\file_io.py in read(self, n)
    110       else:
    111         length = n
--> 112       return pywrap_tensorflow.ReadFromStream(self._read_buf, length, status)
    113 
    114   def seek(self, position):
C:\Anaconda\envs\py35\lib\contextlib.py in __exit__(self, type, value, traceback)
     64         if type is None:
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:
     68                 return
C:\Anaconda\envs\py35\lib\site-packages\tensorflow\python\framework\errors_impl.py in raise_exception_on_not_ok_status()
    467           None, None,
    468           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 469           pywrap_tensorflow.TF_GetCode(status))
    470   finally:
    471     pywrap_tensorflow.TF_DeleteStatus(status)
OutOfRangeError: reached end of file
```

A similar error is encountered when reading a text file, and a more complicated DataLossError occurs when trying to load a model from a checkpoint (but the trace includes references to "out of range" errors, so I assume the same underlying problem is responsible).

The same code snippet gives no error and returns the image byte data when run on the same version of Tensorflow on Windows 10 (also NTFS).

### What other attempted solutions have you tried?

I can workaround this problem for images and text files by using native Python to read the files. However, I really need to use tensorflow built-ins to e.g. read a trained model from a checkpoint.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

See above for output of MWE.

Thanks very much for your help!

**Comment by girving** [comment]
@mrry Do we support Windows Server 2012/NTFS?

**Comment by mrry** [comment]
I doubt the issue is related to a specific release of Windows, but it could be a bug in the `file_io.py` library, which AFAIK doesn't distinguish between text and binary files (modes "r" versus "rb"), and I think this can invalidate file length checks.

@rohan100jain Can you take a look at this?
@mawah Can you share a minimal text file that reproduces this problem on Windows?

**Comment by mawah** [comment]
Sure thing @mrry -- the following generates a text file and shows the error thrown:
```
import tensorflow as tf

with open('labels.txt', 'w') as f:
    f.write('0:0\n1:1\n')
    
with tf.gfile.Open('labels.txt', 'r') as f:
    lines = f.read()
---------------------------------------------------------------------------
OutOfRangeError                           Traceback (most recent call last)
<ipython-input-2-3660054b17bb> in <module>()
      5 
      6 with tf.gfile.Open('labels.txt', 'r') as f:
----> 7     lines = f.read()

C:\Anaconda\envs\py35\lib\site-packages\tensorflow\python\lib\io\file_io.py in read(self, n)
    110       else:
    111         length = n
--> 112       return pywrap_tensorflow.ReadFromStream(self._read_buf, length, status)
    113 
    114   def seek(self, position):

C:\Anaconda\envs\py35\lib\contextlib.py in __exit__(self, type, value, traceback)
     64         if type is None:
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:
     68                 return

C:\Anaconda\envs\py35\lib\site-packages\tensorflow\python\framework\errors_impl.py in raise_exception_on_not_ok_status()
    467           None, None,
    468           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 469           pywrap_tensorflow.TF_GetCode(status))
    470   finally:
    471     pywrap_tensorflow.TF_DeleteStatus(status)

OutOfRangeError: reached end of file
```

**Comment by chadland** [comment]
Did you manage to resolve this issue? I am facing the same problem on Windows Server 2012.

**Comment by mawah** [comment]
Sorry @chadland, no progress yet. Not sure if @rohan100jain or @mrry need more information to repro the problem?

**Comment by chadland** [comment]
Thanks for letting me know @mawah

**Comment by mrry** [comment]
Unfortunately I don't have easy access to a Windows Server 2012 box, so I haven't been able to reproduce the problem you are seeing. There is no obvious platform dependence in the `file_io` library that would explain different behavior on Windows Server 2012 and Windows 10.

@rohan100jain, since you wrote that library, can you suggest what steps could be useful to debug this further?

@mawah, based on my high-level understanding of the file system code, the problem stems from a mismatch between the length of the file (as reported by [`file_io.stat()`](https://github.com/tensorflow/tensorflow/blob/1bbb52426bd4f8046400731100b11e9ca767d303/tensorflow/python/lib/io/file_io.py#L470)) and the number of bytes that can be read from the file. When I ran your program, `labels.txt` is 10 bytes on disk (presumably because the `\n` becomes `\r\n`), and the string read back in has length 10 (and contains the added `\r` characters). Since you have access to both platforms, can you try to identify where the mismatch creeps in?

**Comment by mawah** [comment]
Thanks @mrry,

I also get a length of "10" using `file_io.stat()` on both Windows 10 and Windows Server 2012 with the code snippet below:
```
import tensorflow as tf
from tensorflow.python.lib.io.file_io import stat
with open('labels.txt', 'w') as f:
    f.write('0:0\n1:1\n')
stat('labels.txt').length
```
Evidently the problem lies elsewhere. I'm not sure where to find the definition of `pywrap_tensorflow`, which I would have examined next...thought it would be defined under the `[site-packages]\tensorflow\python` directory, but I'm having trouble locating it.

**Comment by mrry** [comment]
Thanks for checking that. Does the file also have size 10 if you `dir` it at the command prompt?

Can you also try printing each individual character of that file, using code like the following:

```python
import tensorflow as tf

with tf.gfile.Open('labels.txt', 'r') as f:
    print(f.tell())  # I'd expect this to print zero, but who knows?
    for _ in range(10):
        print(f.read(n=1))
```

I'd expect this to crash with an error when it eventually goes beyond the end of the file, but it would be interesting to learn where this happens....

**Comment by mawah** [comment]
Thanks again @mrry. This certainly cleared up something for me. The following fails (regardless of whether the filepath is relative or absolute, and I did double-check that the file is still present):
```
import tensorflow as tf
with tf.gfile.Open('labels.txt', 'r') as f:
    print(type(f))
    print(f.tell())
---------------------------------------------------------------------------
<class 'tensorflow.python.platform.gfile.GFile'>
AttributeError                            Traceback (most recent call last)
<ipython-input-6-f2213a8e47cc> in <module>()
      3 
      4 with tf.gfile.Open('labels.txt', 'r') as f:
----> 5     print(f.tell())

C:\Anaconda\envs\py35\lib\site-packages\tensorflow\python\lib\io\file_io.py in tell(self)
    140       raise errors.PermissionDeniedError(None, None,
    141                                          "File isn't open for reading")
--> 142     return self._read_buf.Tell()
    143 
    144   def __enter__(self):

AttributeError: 'NoneType' object has no attribute 'Tell'
```
...which fully explains the origin of the OutOfRangeError on attempting to read from the file. (Unsurprisingly, I got that error again if I simply tried to read from `f` one character at a time.)

Any idea why `tf.gfile.Open()` would return an object of class `tensorflow.python.platform.gfile.GFile` and `_read_check_passed` set to true, but still have `_read_buf=None`?

**Comment by rohan100jain** [comment]
Okay so one bug clearly is that the tell() method (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/io/file_io.py#L147) needs to do a _preread_check() and not just check for _read_check_passed. That should fix the problem with Tell().

It should look like...

def tell(self):
    """Returns the current position in the file."""
    self._preread_check()
    return self._read_buf.Tell()

I'll send out that fix.

This still doesn't solve the problem that you experienced earlier (I think).. I agree with @mrry that the file sizes somehow are the culprit...

FYI the pywrap_tensorflow method comes from file_io.i (SWIG wrapping the c++ interface).

The C++ implementation is in core/platform/env.cc core/platform/file_system.cc. Hopefully this might help you debug more if you want to dig into it further. 

When you read it one byte at a time.. where did it crash?

**Comment by mawah** [comment]
Hi @rohan100jain and @mrry ,
I added a call to `f._preread_check()`. Even so, looks like the `for` loop crashes while trying to read the first byte:
```
import tensorflow as tf
with tf.gfile.Open('labels.txt', 'r') as f:
    f._preread_check()
    print('Result of f.tell(): {}'.format(f.tell()))
    for _ in range(10):
        print(f.read(n=1))
```
Output:
```
Result of f.tell(): 0
---------------------------------------------------------------------------
OutOfRangeError                           Traceback (most recent call last)
<ipython-input-15-ae33091a7083> in <module>()
      5     print('Result of f.tell(): {}'.format(f.tell()))
      6     for _ in range(10):
----> 7         print(f.read(n=1))

C:\Anaconda\envs\py35\lib\site-packages\tensorflow\python\lib\io\file_io.py in read(self, n)
    110       else:
    111         length = n
--> 112       return pywrap_tensorflow.ReadFromStream(self._read_buf, length, status)
    113 
    114   def seek(self, position):

C:\Anaconda\envs\py35\lib\contextlib.py in __exit__(self, type, value, traceback)
     64         if type is None:
     65             try:
---> 66                 next(self.gen)
     67             except StopIteration:
     68                 return

C:\Anaconda\envs\py35\lib\site-packages\tensorflow\python\framework\errors_impl.py in raise_exception_on_not_ok_status()
    467           None, None,
    468           compat.as_text(pywrap_tensorflow.TF_Message(status)),
--> 469           pywrap_tensorflow.TF_GetCode(status))
    470   finally:
    471     pywrap_tensorflow.TF_DeleteStatus(status)

OutOfRangeError: reached end of file
```

**Comment by smartdolphin** [comment]
The same error occurs in window 7 64bit. 

Output:
    mnist = input_data.read_data_sets("./MNIST_DATA", one_hot=True)
  File "C:\Users\LEE\Documents\Visual Studio 2015\Projects\PythonApplication1\deepLearning\input_data.py", line 196, in read_data_sets
    train_images = extract_images(local_file)
  File "C:\Users\LEE\Documents\Visual Studio 2015\Projects\PythonApplication1\deepLearning\input_data.py", line 64, in extract_images
    buf = bytestream.read(rows * cols * num_images)
  File "H:\Util\Anaconda3\lib\gzip.py", line 274, in read
    return self._buffer.read(size)
  File "H:\Util\Anaconda3\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "H:\Util\Anaconda3\lib\gzip.py", line 467, in read
    buf = self._fp.read(io.DEFAULT_BUFFER_SIZE)
  File "H:\Util\Anaconda3\lib\gzip.py", line 82, in read
    return self.file.read(size)
  File "H:\Util\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 112, in read
    return pywrap_tensorflow.ReadFromStream(self._read_buf, length, status)
  File "H:\Util\Anaconda3\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "H:\Util\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: reached end of file

**Comment by mawah** [comment]
@mrry and @rohan100jain, if limited access to a Windows environment prevents you from investigating this, I could set up a low-performance Azure VM with my monthly personal MSDN credits. (Couldn't run it all month, but certainly long enough for you to have a look.) You can reach me at mawah at microsoft if interested.

**Comment by guschmue** [comment]
I remember seeing above gzip trace above back in October and there was some discussion about eof semantic in ReadFromStream(). Just tried my old test app again and it fails, but seem to work linux. I can debug this a little ... might take a day or 2 before I get to it,

**Comment by guschmue** [comment]
spend some time on this: 
@smartdolphin I can reproduce the same exception on 0.12.1 but on 1.0 this is gone.  Could you update to 1.0 (pip install --upgrade tensorflow) and see if this works for you?
@mawah, I can't reproduce your problem. I'll send you some email if we can debug this in your setup.

**Comment by mawah** [comment]
Hi folks, the error was resolved by upgrading to Tensorflow 1.0.0 (which has been released in the meantime). Closing this issue.

**Comment by omshanti** [comment]
Problem still exists in Windows 10
AttributeError                            Traceback (most recent call last)
<ipython-input-6-415a7deab32c> in <module>()
      1 with tf.gfile.GFile("train.x.txt", "r") as f:
----> 2     print(f.tell())  # I'd expect this to print zero, but who knows?
      3     for _ in range(10):
      4         print(f.read(n=1))

c:\program files\python35\lib\site-packages\tensorflow\python\lib\io\file_io.py in tell(self)
    140       raise errors.PermissionDeniedError(None, None,
    141                                          "File isn't open for reading")
--> 142     return self._read_buf.Tell()
    143 
    144   def __enter__(self):

AttributeError: 'NoneType' object has no attribute 'Tell'

**Comment by omshanti** [comment]
Issue still exists in Windows 10, Tensorflow 1.0.1

AttributeError                            Traceback (most recent call last)
<ipython-input-6-415a7deab32c> in <module>()
      1 with tf.gfile.GFile("train.x.txt", "r") as f:
----> 2     print(f.tell())  # I'd expect this to print zero, but who knows?
      3     for _ in range(10):
      4         print(f.read(n=1))

c:\program files\python35\lib\site-packages\tensorflow\python\lib\io\file_io.py in tell(self)
    140       raise errors.PermissionDeniedError(None, None,
    141                                          "File isn't open for reading")
--> 142     return self._read_buf.Tell()
    143 
    144   def __enter__(self):

AttributeError: 'NoneType' object has no attribute 'Tell'

**Comment by mrry** [comment]
@oldmonk101 This bug (`tell()` raising an `AttributeError` if called before `read()` or `write()`) was present in all versions of TensorFlow up to 1.0.1, but is fixed in 1.1. Upgrading to the 1.1 release candidate or nightly version will fix the problem.

**Comment by oldmonk101** [comment]
Tried Tensorflow 1.1.0-rc0 - problem is fixed.
