### ISSUE TITLE
ImportError: No module named '_pywrap_tensorflow'   Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by WahabZia** [tensorflow/tensorflow#8385]
Apologies  for the inappropriate description i am actually very new to Machine learning  my

TF version is 1.0.1
Python version is 3.5.2 
OS windows 8 64bit and 
**Native pip**  
as recommended on tensor flow.org
https://www.python.org/downloads/release/python-352/

The problem ocured  at this simple import command  

**import tensorflow as tf**

### What other attempted solutions have you tried?
None

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

C:\Users\test\Desktop>>python firstp.py
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\importlib\__ini
t__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\importlib\__ini
t__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\test\Desktop\firstp.py", line 1, in <module>
    import tensorflow as tf
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\importlib\__ini
t__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\site-packages\t
ensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "C:\Users\test\AppData\Local\Programs\Python\Python35\lib\importlib\__ini
t__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow'

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_st
arted/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by MicaelCarvalho** [comment]
Please fill the template for new issues, with information about OS, TF version, python version etc. It is very hard to diagnose a problem without the information required on the template (made to be filled, not erased). And check your installation of tensorflow, these errors look like a bad installation.

**Comment by Carmezim** [comment]
@WahabZia Sorry you faced issues trying to run TF. If you installed for GPU support I need you to:
1. Check if your CUDA and cuDNN directories are properly set on your `PATH`. 
2. After that if the issue persists install the [Visual C++ Redistributable 2015 x64](https://www.microsoft.com/en-us/download/details.aspx?id=53587) as `MSVCP140.DLL` may be missing in your system.

**Comment by WahabZia** [comment]
Thanks @Carmezim for your kind reply i am using the  CPU-only version of TensorFlow . What should i do

**Comment by Carmezim** [comment]
@WahabZia If you are using Python.org distribution and receiving this error is very likely `MSVCP140.DLL` is not installed in your system. 
So as I provided on step 2, please try installing Visual C++ Redistributable linked above, uninstall then install TF again and let us know if you had progress on it.

**Comment by WahabZia** [comment]
Thanks @Carmezim for the help i have found the dll from the DLL Files 
https://www.dll-files.com/msvcp140.dll.html 
The import issue is resolved 

I also used this command 

C:\> pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_amd64.whl 

From this thread
http://stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso

before placing the DLL in System32

And now i am facing this issue  when i am sort of trying  to  validate my installation. 

>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') fo
r unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_t
ype: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"')
 for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for
unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_ty
pe: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"')
for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"'
) for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') fo
r unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') fo
r unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"
') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "C
PU"') for unknown op: UpdateFertileSlots
b'Hello, TensorFlow!'
>>>


**Thanks alot for the help**

**Comment by WahabZia** [comment]
Both of the problems are resolved . Thanks gentelmen for the help . The issue was occurring because of  missing MSVCP140.DLL

**Comment by imamol555** [comment]
I am also facing the same problem(2nd one). I have installed  Visual C++ Redistributable but still facing this issue. Please help me out.

**Comment by imamol555** [comment]
@WahabZia  plz help

**Comment by WahabZia** [comment]
Hello @imamol555  sorry for the late reply can you please share the logs .  So  that i  can the reason for the problem .  Sorry  again for the late reply i didn't check git account for a couple of days .

**Comment by krishnaputhran** [comment]
@WahabZia plz help. You mentioned that you also faced issue 2nd, but probably forgot to mention how you addressed it. As you requested the logs are as shown below. This is same as you mentioned before

Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>>
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
b'Hello, TensorFlow!'
>>>

appreciate if you can help to resolve this.

**Comment by Carmezim** [comment]
@krishnaputhran If you look up the comments you'll see his issue was due missing the `MSVCP140.DLL`. You can solve it by downloading the [Visual C++ Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53587).

But some users had this problem after install with `pip install tensorflow` because of a bug on the wheel and to solve it uninstall TensorFlow, download this [nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/124/) choosing the right version, CPU or GPU, and install with this wheel.

**Comment by krishnaputhran** [comment]
@Carmezim thanks for your immediate response and I appreciate that. Yes my issue is solved now. I had to do the following as mentioned above.
1. The "import tensorflow as tf" is solved my installing the [Visual C++ Redistributable.](https://www.microsoft.com/en-us/download/details.aspx?id=53587). Make sure in your System32 or C:\Windows\SysWOW64 has the msvcp140.dll 
2. To get rid off the second issue as mentioned above, upgrade your Tensorflow to the latest nightly build [nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/124/)

**Comment by cfuxiang** [comment]
Indeed, `pip3 install --upgrade tensorflow-gpu` seems to be causing the issue (tested on Win 10), despite installing the Visual C++ Redistributable. Installing via the following command solves the problem: pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_amd64.whl

**Comment by dwiggles** [comment]
That solved it for me, too. Thanks.

**Comment by iamxbg** [comment]
I use cuDNN6.0 for cuda8.0. then I see there's version 5.0 for cuda8.0 too in your question !!!
thank for your tip!

**Comment by iamxbg** [comment]
I use cuda8.0 with cuDNN 6.0 , got the same error-message!
then I change cuda8.0 with cuDNN 5.1 ,  it works !
thank for your tip.

**Comment by Moondra** [comment]
@Carmezim   Hi, I"m having the same error as above **(Windows 7, pip3.6, tensorflow1.2 rc,)** .  I seem to have  MS Visual c++ compiler,  Visual c++ build tools, and Visual Studio 2015 installed and If search files (in the search bar) , Windows is able to find  msvcp140.dll. 

As for CUDA Path I see


```
System variables
------------------

variable
------------
 CUDA_PATH     C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
 CUDA_PATH_V8_0   C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
```


Is my CUDA_PATH okay? 

Thank you.

**Comment by Carmezim** [comment]
@Moondra Which error specifically, could you please provide the log? If `MSVCP140.DLL` is in your `%PATH%`. How did you install TensorFlow 1.2?
If you're getting  `missing DLL` error this [script](https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c) may be useful. Just download and run it and it will help you assess the culprit.

**Comment by Moondra** [comment]
@Carmezim

I installed the rc version of Tensorflow like this:

`pip3.6 install tensorflow-gpu==1.2.0rc2`

 Here is my traceback error:

```
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\pywrap_tensorflow_internal.py", line 18,
    return importlib.import_module(mname)
  File "C:\Users\Moondra\AppData\Local\Programs\P
line 126, in import_module
    return _bootstrap._gcd_import(name[level:], p
  File "<frozen importlib._bootstrap>", line 978,
  File "<frozen importlib._bootstrap>", line 961,
  File "<frozen importlib._bootstrap>", line 950,
  File "<frozen importlib._bootstrap>", line 648,
  File "<frozen importlib._bootstrap>", line 560,
  File "<frozen importlib._bootstrap_external>",
  File "<frozen importlib._bootstrap>", line 205,
ImportError: DLL load failed: The specified modul

During handling of the above exception, another e

Traceback (most recent call last):
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\pywrap_tensorflow.py", line 41, in <modul
    from tensorflow.python.pywrap_tensorflow_inte
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\pywrap_tensorflow_internal.py", line 21,
    _pywrap_tensorflow_internal = swig_import_hel
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\pywrap_tensorflow_internal.py", line 20,
    return importlib.import_module('_pywrap_tenso
  File "C:\Users\Moondra\AppData\Local\Programs\P
line 126, in import_module
    return _bootstrap._gcd_import(name[level:], p
ModuleNotFoundError: No module named '_pywrap_ten

During handling of the above exception, another e

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Moondra\AppData\Local\Programs\P
\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorfl
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\pywrap_tensorflow.py", line 52, in <modul
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\pywrap_tensorflow_internal.py", line 18,
    return importlib.import_module(mname)
  File "C:\Users\Moondra\AppData\Local\Programs\P
line 126, in import_module
    return _bootstrap._gcd_import(name[level:], p
  File "<frozen importlib._bootstrap>", line 978,
  File "<frozen importlib._bootstrap>", line 961,
  File "<frozen importlib._bootstrap>", line 950,
  File "<frozen importlib._bootstrap>", line 648,
  File "<frozen importlib._bootstrap>", line 560,
  File "<frozen importlib._bootstrap_external>",
  File "<frozen importlib._bootstrap>", line 205,
ImportError: DLL load failed: The specified modul

During handling of the above exception, another e

Traceback (most recent call last):
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\pywrap_tensorflow.py", line 41, in <modul
    from tensorflow.python.pywrap_tensorflow_inte
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\pywrap_tensorflow_internal.py", line 21,
    _pywrap_tensorflow_internal = swig_import_hel
  File "C:\Users\Moondra\AppData\Local\Programs\P
\python\pywrap_tensorflow_internal.py", line 20,
    return importlib.import_module('_pywrap_tenso
  File "C:\Users\Moondra\AppData\Local\Programs\P
line 126, in import_module
    return _bootstrap._gcd_import(name[level:], p
ModuleNotFoundError: No module named '_pywrap_ten


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_so

for some common reasons and solutions.  Include t
above this error message when asking for help.
```




My Path variable looks like this:

`C:\Program Files  (x86)\Tesseract-OCR\;C:\Users\Moondra\Anaconda_related\Anaconda\geckodriver.exe;C:\Users\Moondra\AppData\Local\Programs\Python\Python36;C:\Users\Moondra\Cygwin\bin;C:\Users\Moondra\Anaconda_related\Anaconda;C:\Users\Moondra\Anaconda_related\Anaconda\Scripts;C:\Users\Moondra\Anaconda_related\Anaconda\Library\bin;C:\Users\Moondra\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Moondra\AppData\Local\Programs\Python\Python35\;C:\Users\Moondra\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Moondra\AppData\Local\Programs\Python\Python36\;C:\Users\Moondra\AppData\Local\Programs\Python\Python35\Scripts;C:\Users\Moondra\AppData\Local\Programs\Python\Launcher\`




"Make sure cuDNN is also properly installed (the cuDNN files directory is in your %PATH%)"


I don't think I have this installed. I'm assuming this is separate from CUDA? I've installed NVDIA CUDA but is this a separate install? Thank you.

**Comment by Carmezim** [comment]
@Moondra that's most likely the problem. cuDNN is a separate library required to run TensorFlow with GPU support. Until next release cuDNN 5.1 is the compatible version on Windows (on next release it will be 6.0).

**Comment by Moondra** [comment]
@Carmezim  Okay, so I've downloaded cuDNN 5.1 (Version 8.0), and unzipped. There seems to be no exe file, so I just put the folder somewhere and created a path to the `cudnn64_5.dll`  file located within the folder. 

 `C:\Nvidia_CUDL\cuda\bin\cudnn64_5.dll`    (This is the path I've created in the path variable)
Is the file I'm supposed to create a path to?
However,  I still seem to be presented with the error. 

Thank you.

**Comment by Carmezim** [comment]
@Moondra You can find the instruction to install cuDNN on NVIDIA's website. Usually the content of the cuDNN zip matches the folders inside CUDA's directory (include, lib64 etc), so you could basically extract/copy them there. 
Try downloading the script I provided above made by @mrry and run it locally. You will have a better assessment of the reason why you're receiving these errors.

**Comment by Moondra** [comment]
@Carmezim  I finally got it! Yeah you are supposed to insert the contents into the CUDA directory.
(I was also missing a third path variable)

This blog was REALLY useful in showing how to install to install all the necessary drivers for tensorflow. 
https://nitishmutha.github.io/tensorflow/2017/01/22/TensorFlow-with-gpu-for-windows.html

I  suggest you guys add it your docs or official website as I think it will save you guys a lot of time from dealing with newcomers like me.


Thank you so much for all of your help.

**Comment by cfuxiang** [comment]
Why not create a test case for it? It will be great for future releases. :)

**Comment by Carmezim** [comment]
@Moondra Nice you got it working. Thanks for the feedback, TF team will appreciate. I think in this case though it does not make sense as is supposed for users to take care of that themselves e.g. follow official docs already available from NVIDIA and kind of out of TF range to make sure third party libraries are installed properly by users, so IMO it's out of TF's responsibility. For instance you also notice they don't teach you how to install Python or which dist. etc.

**Comment by Moondra** [comment]
@Carmezim   Yeah I suppose you are right. Nvidia's docs were pretty confusing though;

The whole Visual Studio project and linker etc were instructions were really confusing.  Maybe I should email them. 

`WINDOWS

    Add <installpath> to the PATH environment variable.

    In your Visual Studio project properties, add <installpath> to the Include Directories 
    and Library Directories lists and add cudnn.lib to Linker->Input->Additional Dependencies.`


Anyway, thank you so much for working with me until I got it working.  I really appreciate it.

**Comment by Carmezim** [comment]
@Moondra yeah, NVIDIA docs can be a bit confusing for a beginner but again, IMO their docs are not up to TF. Glad you got it working!

**Comment by hadamschek** [comment]
Hi Caremzim,

thank you for providing your script. I used it, got the following response:
![image](https://user-images.githubusercontent.com/29492654/27243811-3c6b626e-52d3-11e7-87f3-cf724085a2d1.png)

If I just try to import, I get this
![image](https://user-images.githubusercontent.com/29492654/27243853-6f699122-52d3-11e7-95a4-121bc7908c40.png)

I have intalled cuda 7.5 with cudnn 5 on windows server 2012 r2. MS redistributable 2015 also installed.
Thanks a lot,

Blg

**Comment by Carmezim** [comment]
@hadamschek Hi, that is not my script but you can thank @mrry for kindly create it :)
Your error is due your CUDA version. If you refer to TensorFlow docs you will notice only CUDA 8.0 is supported on Windows. If you install it with cuDNN 5.1 for CUDA 8.0 you might solve this issue. Also I don't really know about Windows Server but you OS needs to be 64-bit as well as Python. Let me know if you face any further issues.

**Comment by cfuxiang** [comment]
@hadamschek Just curious, how did you install the gpu version? e.g via standard pip install or using the nightly build? If you are using the standard pip install for gpu, it is not stable. If you have not tried the nightly build, perhaps you can install it with its latest stable version.

**Comment by abhigoku10** [comment]
@Carmezim @krishnaputhran  hi guys i have read through each of your guys comments and followed yet i am having an issues while doing import tensorflow as tf i am trying to do this on window 10 below is log 
Python 3.5.3 |Continuum Analytics, Inc.| (default, May 15 2017, 10:43:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Anaconda3.5\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 919, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Anaconda3.5\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Anaconda3.5\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 919, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Anaconda3.5\envs\tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Anaconda3.5\envs\tensorflow\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


Please hELP
tHANK yOU

**Comment by Carmezim** [comment]
@abhigoku10 Please try running the script again and it will point you what may be causing this. It may be you didn't install CUDA and cuDNN correctly adding their directories to your `%PATH%` but as you are using a Python Anaconda distribution a common cause is you don't have `MSVC140.DLL` installed in your system which you can get downloading the [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53587).

**Comment by abhigoku10** [comment]
@Carmezim  Thanks for the tips, i uninstalled everything and followed the steps again, then i found out the cudnn dlls i have downloaded was of different, now everything is working fine i am able to import and run the code. Appreciate the help tq

**Comment by furyjack** [comment]
@Carmezim  just installed tensorflow-gpu version from pip.The specs are as follows:
cuda v8.0
cudnn 7.0
also MSVCP140.DLL is in the path

the following error is occurring when importing tensorflow

>>> import tensorflow as tf
Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_inter
nal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "F:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_inter
nal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_inter
nal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "F:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <mod
ule>
    from tensorflow.python import *
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49,
in <module>
    from tensorflow.python import pywrap_tensorflow
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_inter
nal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "F:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py",
line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_inter
nal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_inter
nal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "F:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

**Comment by furyjack** [comment]
@Carmezim Any help would be appreciated

**Comment by Carmezim** [comment]
@furyjack could you try running this [script](https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c) to see what can be going wrong? I'm not following TF on Windows it's been a while.

**Comment by furyjack** [comment]
@Carmezim i ran the script this was the output of it

(root) C:\Users\Admin\Desktop>python tensorflow_self_check.py
ERROR: Failed to import the TensorFlow module.

- Python version is 3.5.

- TensorFlow is installed at: F:\Anaconda3\lib\site-packages\tensorflow

- Could not load 'cudart64_80.dll'. The GPU version of TensorFlow
  requires that this DLL be installed in a directory that is named in
  your %PATH% environment variable. Download and install CUDA 8.0 from
  this URL: https://developer.nvidia.com/cuda-toolkit

- Could not load 'cudnn64_5.dll'. The GPU version of TensorFlow
  requires that this DLL be installed in a directory that is named in
  your %PATH% environment variable. Note that installing cuDNN is a
  separate step from installing CUDA, and it is often found in a
  different directory from the CUDA DLLs. You may install the
  necessary DLL by downloading cuDNN 5.1 from this URL:
  https://developer.nvidia.com/cudnn

- Could not find cuDNN.

My path variables
CUDA_HOME : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
CUDA_PATH : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
CUDA_PATH_V8_0: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

and in my path variable i have
1)C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\extras\CUPTI\libx64
2)C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

**Comment by furyjack** [comment]
@Carmezim Thanks i found out the problems 
1)path variables should have a extra \bin at the end
2)the cuda version should have been 6
3)in path variable there should be have been and extra C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\cuda\bin

**Comment by viveky444** [comment]
- Python version is 3.6.

- TensorFlow is installed at: C:\python36\lib\site-packages\tensorflow

- Could not load 'nvcuda.dll'. The GPU version of TensorFlow requires that
  this DLL be installed in a directory that is named in your %PATH%
  environment variable. Typically it is installed in 'C:\Windows\System32'.
  If it is not present, ensure that you have a CUDA-capable GPU with the
  correct driver installed.

- Could not find cuDNN 6.

  The GPU version of TensorFlow requires that the correct cuDNN DLL be installed
  in a directory that is named in your %PATH% environment variable. Note that
  installing cuDNN is a separate step from installing CUDA, and it is often
  found in a different directory from the CUDA DLLs. The correct version of
  cuDNN depends on your version of TensorFlow:
  
  * TensorFlow 1.2.1 or earlier requires cuDNN 5.1. ('cudnn64_5.dll')
  * TensorFlow 1.3 or later requires cuDNN 6. ('cudnn64_6.dll')
    
  You may install the necessary DLL by downloading cuDNN from this URL:
  https://developer.nvidia.com/cudnn

what to do

**Comment by viveky444** [comment]
what is the matter here
ERROR: Failed to import the TensorFlow module.

- Python version is 3.6.

- TensorFlow is installed at: C:\python36\lib\site-packages\tensorflow

- Could not load 'nvcuda.dll'. The GPU version of TensorFlow requires that
  this DLL be installed in a directory that is named in your %PATH%
  environment variable. Typically it is installed in 'C:\Windows\System32'.
  If it is not present, ensure that you have a CUDA-capable GPU with the
  correct driver installed.

**Comment by furyjack** [comment]
@viveky444 
I wrote an article about this.
[Link to article](https://medium.com/@lakshaytaneja26/https-medium-com-lakshaytaneja26-installing-tensorflow-on-windows-e577edfacade).Hope this helps.

**Comment by bottino** [comment]
@Carmezim Your script helped me fix my problem (not posted here), thank you very much!

**Comment by Carmezim** [comment]
@bottino happy you fixed your problem :)
just for the record though the script is by @mrry so kudos to him 😄, and indeed it's a very handy tool

**Comment by marisuki** [comment]
Maybe there is another solution if you have tried such solutions above and still not config like me, you can install a older vision of tensorflow since the latest vision of it may have some problems, and i used : "pip install https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.2.0-cp35-cp35m-win_amd64.whl " and solve it.

**Comment by DjangoPeng** [comment]
@Carmezim 
I have built tensorflow v1.4-rc1 from source. It looks like all is well until I run the TensorFlow python scripts. I checked the directory `site-packages/tensorflow/python/` and found that there is no `_pywrap_tensorflow.so` file. 

OS: CentOS 7.3
Anaconda Version: 4.3.30

**Comment by Carmezim** [comment]
@DjangoPeng I've never really dealt with TF on 
CentOS but if you could provide the logs if I cannot, others may help. What scripts do you refer?

**Comment by narendra-7638** [comment]
Somebody please help me with this problem:

Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helpe
r
    return importlib.import_module(mname)
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\importlib\__i
nit__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialisation routin
e failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helpe
r
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\importlib\__i
nit__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\site-packages
\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helpe
r
    return importlib.import_module(mname)
  File "C:\Users\Neeraj\AppData\Local\Programs\Python\Python36\lib\importlib\__i
nit__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialisation routin
e failed.

During handling of the above exception, another exception occurred:

**Comment by Carmezim** [comment]
@narendra-7638 Hi, could you try running [this script](https://gist.github.com/mrry/ee5dbcfdd045fa48a27d56664411d41c) locally and see what it indicates?

**Comment by SanaAnsari-SA** [comment]
Hi Carmezim, I m facing the same issue for installing TF for CPU-only version. I guess i don't need to install CUDA for CPU-only version. I tried using the following
`pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu /tensorflow-1.6.0-cp35-cp35m-win_amd64.whl`

But getting the following error

`tensorflow-1.6.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.`

Please help. I have downloaded CUDNN-9.1 but i still feel that i don't need it for CPU-only version, SO haven't installed it yet.
I have the MSVC140.DLL in System32 folder. Also added it in PATH environmental variable.

Also I was working on the previous version of tensorflow i.e 1.5.0 and everything worked fine. This problem started wen I upgraded to the latest version 1.6.0 just to avoid warnings

Python : 3.6.4 installed from python.org for 64bit executable
Tensorflow : 1.6.0 using command  "pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.6.0-cp36-cp36m-win_amd64.whl"
System Windows 7 64-bit
Native pip

Please revert asap.. Thanking you in anticipation

here is the trace stack

>>> import tensorflow
Traceback (most recent call last):
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Software-Installations\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "D:\Software-Installations\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tensorflow
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Software-Installations\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Software-Installations\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "D:\Software-Installations\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Comment by avi121212** [comment]
Hi Ive got the same problem and ive tried all the solutions i can find but i still get the same result  

D:\Avinaash\Downloads\models-master\models\research>python object_detection/builders/model_builder_test.py
Traceback (most recent call last):
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 18, in <module>
    import tensorflow as tf
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\python\__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Avinaash\AppData\Local\Programs\Python\Python35\lib\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named '_pywrap_tensorflow'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by jayasimhasai** [comment]
Use python3.5 version it solves all the problems. I spent almost weeks on these errors.

**Comment by hemangjoshi37a** [comment]
> @WahabZia Sorry you faced issues trying to run TF. If you installed for GPU support I need you to:
> 
> 1. Check if your `%CUDA_HOME%` is properly set and CUDA and cuDNN DLLs directories are in your `PATH`.
> 2. After that if the issue persists install the [Visual C++ Redistributable 2015 x64](https://www.microsoft.com/en-us/download/details.aspx?id=53587) as `MSVCP140.DLL` may be missing in your system.
> 
> Thanks for filling the issue and feel free to ask any questions or doubts you may still have about TensorFlow.

When I try to install using [this install](https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe) it gives me error that  

> `Another versionof this product is already installed. Installation of this version can not continue. To configure ....bla bla bla`

**Comment by gauravshimpi** [comment]
Hello,

i have the Visual C++ Redistributable 2015 x64 as well as DLL (msvp..) file too....
i am using tensorflow for the first time on windows 10
when i m running the following statement in python 
import tensorflow as tf 
==============================================================
it gives the following error
==============================================================
import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Gaurav Shimpi\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
======================================================
Please assist :(

**Comment by TomMaullin** [comment]
I have the same issue as @hemangjoshi37a . I seem to have `Visual C++ Redistributable 2017 x64` installed. I do not wish to uninstall it but there is no way to install 2015 without uninstalling it as far as I can see. Please advise on what should be done here.

**Comment by hemangjoshi37a** [comment]
@TomMaullin okay bro. Thank for the help.

**Comment by nsa-123** [comment]
I am also facing the same error.

python --version gave
`Python 3.7.0`

Tensorflow version is 

(0.12.0)

I have already installed Microsoft Visual C++ Redistribution (x64) 9.0.30729.17/.6161 / .21022 /(x86) 30729.17/ (x86) 30729.6161

 Microsoft Visual C++ Redistribution2015-2019  (x64)  14.25.28508
 Microsoft Visual C++ Redistribution2015-2019  (x64)  14.31.31103

I have included path to all dlls of python to environment variable path.

OS is Win 7 Ultimate.

When I do 
`import tensorflow as tf`

 I get following error
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
     17         try:
---> 18             fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
     19         except ImportError:

h:\python installed\lib\imp.py in find_module(name, path)
    296     else:
--> 297         raise ImportError(_ERR_MSG.format(name), name=name)
    298 

ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
h:\python installed\lib\site-packages\tensorflow\python\__init__.py in <module>
     53     # use `dlopen()` for dynamic loading.
---> 54     from tensorflow.python import pywrap_tensorflow
     55 except ImportError:

h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>
     27             return _mod
---> 28     _pywrap_tensorflow = swig_import_helper()
     29     del swig_import_helper

h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in swig_import_helper()
     19         except ImportError:
---> 20             import _pywrap_tensorflow
     21             return _pywrap_tensorflow

ModuleNotFoundError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-4234dfe0332e> in <module>
----> 1 import tensorflow as tf
      2 from tensorflow.keras.utils import to_categorical

h:\python installed\lib\site-packages\tensorflow\__init__.py in <module>
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

h:\python installed\lib\site-packages\tensorflow\python\__init__.py in <module>
     58 please exit the tensorflow source tree, and relaunch your python interpreter
     59 from there.""" % traceback.format_exc()
---> 60   raise ImportError(msg)
     61 
     62 # Protocol buffers

ImportError: Traceback (most recent call last):
  File "h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "h:\python installed\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "h:\python installed\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "h:\python installed\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ModuleNotFoundError: No module named '_pywrap_tensorflow'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.`
