### ISSUE TITLE
Reload Button in Tensorboard 1.1rc1 Resets Chart Scales

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8994]
In tensorboard 1.1rc1, hitting the "reload button",  ![image](https://cloud.githubusercontent.com/assets/51059/24721828/7f66e63a-1a0f-11e7-9942-15d4609e0e46.png), causes the scaling on the charts to reset. That was not the case in 1.0.1.

For example if I zoom in here:
![image](https://cloud.githubusercontent.com/assets/51059/24721857/9772cd7a-1a0f-11e7-8e4a-3f6535df7edb.png)
to:
![image](https://cloud.githubusercontent.com/assets/51059/24721867/9cedb1a2-1a0f-11e7-9a0d-24d57648d242.png)
this zoom is lost.

**Comment by asimshankar** [comment]
@dandelionmane @jart : Any ideas?

**Comment by taion** [comment]
The same scale reset happens when checking and unchecking runs.

**Comment by dandelionmane** [comment]
Acknowledged

**Comment by cancan101** [comment]
Any chance this will fixed before final 1.1 release?

**Comment by cancan101** [comment]
@dandelionmane It looks like TF 1.1 is shipping. Did this get fixed?

**Comment by taion** [comment]
This appears to still happen in TF 1.1.

**Comment by taion** [comment]
Any update on this? This isn't a performance bug – it's a usability issue.

**Comment by cancan101** [comment]
@dandelionmane any chance this is fixed in 1.2.0?

**Comment by taion** [comment]
This is still happening in 1.2.0-rc0. Is this changed behavior intentional?

**Comment by wchargin** [comment]
Looks like Chi migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/36, so I'm closing it. Please feel free to continue discussion there.
