### ISSUE TITLE
Error on Windows when installed in a virtualenv that has a non-ASCII character in the path

### ISSUE THREAD

**Issue by marczellm** [tensorflow/tensorflow#9481]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64
- **TensorFlow installed from (source or binary)**: binary from PyPI
- **TensorFlow version (use command below)**: 1.1.0
- **Exact command to reproduce**:

      from tensorflow.contrib.rnn.python.ops.gru_ops import *

### Describe the problem
I encountered this when importing keras but it's reproducible with the command above. My virtualenv is in a folder that has an accented character in its name (see the log below). If I install TensorFlow globally, it works.

### Source code / logs
```
D:\Marci\Programozás\algorimp\test>venv\scripts\python -c "from tensorflow.contrib.rnn.python.ops.gru_ops import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\__init__.py", line 26, in <module>
    from tensorflow.contrib import crf
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\crf\__init__.py", line 32, in <module>
    from tensorflow.contrib.crf.python.ops.crf import _lengths_to_masks
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\crf\python\ops\crf.py", line 44, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 80, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\rnn\python\ops\gru_ops.py", line 32, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\util\loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\python\framework\load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\rnn\python\ops\_gru_ops.dll not found
```

**Comment by aselle** [comment]
@mrry, it looks like we pass to TF_LoadLibrary C api which takes char*, so maybe if we get it utf-8 in python and then at the very last moment in windows/env.cc  convert it to a `LPWSTR` with `MultiByteToWideChar` and use `LoadLibraryExW` instead of `LoadLibraryEx` it might not be terrible to get this working.

**Comment by mrry** [comment]
Sounds like a fine idea, but I'm not going to have time to work on it. Opening this up as "Contributions Welcome".

**Comment by Awelski** [comment]
I have got a similar issue like marczellm. 

- Operating system: Windows 10
- Tensorflow version: tensorflow-gpu 1.1.0 (pip installation, in python 3.5.3 environment)
- IDE: PyCharm

Although I got tensorflow installed, the following command throws an error:

`from tensorflow.examples.tutorials.mnist import mnist`

Error:

> "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\python.exe" "C:/Users/Raphaël Baur/PycharmProjects/untitled8/y.py"
Traceback (most recent call last):
  File "C:/Users/Raphaël Baur/PycharmProjects/untitled8/y.py", line 1, in <module>
    from tensorflow.examples.tutorials.mnist import mnist
  File "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\examples\tutorials\mnist\__init__.py", line 21, in <module>
    from tensorflow.examples.tutorials.mnist import input_data
  File "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\examples\tutorials\mnist\input_data.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets.mnist import read_data_sets
  File "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\__init__.py", line 26, in <module>
    from tensorflow.contrib import crf
  File "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\crf\__init__.py", line 32, in <module>
    from tensorflow.contrib.crf.python.ops.crf import _lengths_to_masks
  File "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\crf\python\ops\crf.py", line 44, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell
  File "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 80, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\rnn\python\ops\gru_ops.py", line 32, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\util\loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
**tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\rnn\python\ops\_gru_ops.dll not found**

> Process finished with exit code 1

So somehow "_gru_ops.dll" is not found, altough it is located in the indicated directory (output from my terminal):

> C:\Users\Raphaël Baur\AppData\Local\Programs\Python\Python35\Lib\site-packages\tensorflow\contrib\rnn\python\ops>ls
> __init__.py  
> __gru_ops.dll_ (here)  
> core_rnn.py       
> core_rnn_cell_impl.py  
> gru_ops.py   
> rnn.py
> __pycache__  
> _lstm_ops.dll  
> core_rnn_cell.py  
> fused_rnn_cell.py      
> lstm_ops.py  
> rnn_cell.py

**Comment by marczellm** [comment]
The only solution is to install both Python and Tensorflow in a directory that does not have ä or other non-ASCII characters in the path.

**Comment by mrry** [comment]
It would be great to fix this problem, but I'll first need to clarify what API guarantees we make about character set. 

@girving: Does the fact that we use of `'utf-8'` as the default encoding in `compat.as_bytes()` imply that we should treat all user-provided strings as UTF-8 encoded? Do you know if we do anything special on Linux?

@guschmue: Have you run into this problem with the Windows port? My reading of the API is that we can switch all calls to `CreateFileA()` (etc.) to `CreateFileW()` by using `MultiByteToWideChar()` to translate incoming `std::string` values into the necessary `LPCWSTR` argument. However, I tend to assume that handling Unicode properly is "more complicated than you'd think", so it would be great to get a second opinion!

**Comment by girving** [comment]
Yes, we treat all user provided `bytes` objects as UTF-8 encoded, and `compat.as_bytes()` will produce UTF-8 encoded `bytes` data regardless of the encoding of the input string.

**Comment by guschmue** [comment]
MultiByteToWideChar and CreateFileW (and related calls) sounds about right. Should be straight forward for doing the system call. Guess the complication comes with calls like FindFirstFile ... we'd need to convert the results as well but all of this should be contained in windows_file_system.cc

**Comment by Awelski** [comment]
Installing it in a different directory worked! Thank you! @marczellm

**Comment by joshua-xia** [comment]
Path locale encoding problem, anybody still working on this issue?

**Comment by hectorlxm** [comment]
I'll work on this

**Comment by guschmue** [comment]
talked to @hectorlxm ... he has the fix and is adding some unit tests before sending pr.

**Comment by yongtang** [comment]
I think this issue is fixed through PR #11562.

**Comment by Jatik** [comment]
I don't have ANY non-ascii symbols in the path but still have this error.

**Comment by MohammedPUD** [comment]
@Jatik  Did find a solution for that? I just bumped into the same issue!

**Comment by MohammedPUD** [comment]
And here is the error message with the path in it. I also verified that the file lies there.

NotFoundError: D:\Anaconda3\lib\site-packages\tensorflow\contrib\rnn\python\ops\_gru_ops.dll not found

**Comment by mrry** [comment]
The original problem in this issue was fixed in #11562. @MohammedPUD It sounds like you are facing a different problem. Please create a new issue and answer all of the questions in the template.
