### ISSUE TITLE
Tensor flow cannot be imported properly in windows

### ISSUE THREAD

**Issue by harishjmhss** [tensorflow/tensorflow#9516]
I have installed CPU version of Tensor flow in my laptop using the command line using pip install.

OS: Windows 8.1 64 bit Python 3.5.1

But, when I tried importing it in the python 3.5.1 it throws the following error message.

> import _pywrap_tensorflow ImportError: No module named '_pywrap_tensorflow' Error importing tensorflow. Unless you are using bazel, you should not try to import tensorflow from its source directory; please exit the tensorflow source tree, and relaunch your python interpreter from there.

 I have tried getting answers in Stackoverflow, but no hope. I have even tried changing the directories but nothing works.
I am new to python. Please help me to solve this issue !!

**Comment by GG9** [comment]
you can try install tensorflow 1.0.1.

**Comment by Carmezim** [comment]
@harishjmhss thank you for reporting your issue. This error can derive from a couple of reasons and for better help you solve the problem please fill out all the information on the Issue template (OS, Python distribution, the entire log and steps you used to install TensorFlow etc). Without that it's hard to assess and debug what is happening. 
Thanks!

**Comment by harishjmhss** [comment]
I am using Windows 8.1 - 64 bit - Python 3.5.1 distribution downloaded from python.Org
 
I have installed using the command

> pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_amd64.whl


I just entered this code and the installation works well without any interruption. But when I am trying to import the tensorflow from the python software, the problem occurs.I have installed Microsoft Visual C++ 2015 Redistribute Update 3 also. But still not working !!

**Comment by miendinh** [comment]
Hi
I got the same issue when I try install tensorflow in windows  : 
`pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_amd64.whl`

`tensorflow-1.0.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.
`
I use windows 7x64 and python 3.6.1

**Comment by Carmezim** [comment]
Could you try upgrading to TensorFlow's latest realease, `1.1`? Do you have a clone of TF repository locally?

**Comment by harishjmhss** [comment]
I have updated tensorflow but I don't know whether it is 1.1...

The entire stack trace is as follows: 

Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

>>> import tensorflow  as tf

Traceback (most recent call last):
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Program Files (x86)\python\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tensorflow  as tf
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\python\__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow', [dirname(__file__)])
  File "C:\Program Files (x86)\python\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\python\__init__.py", line 54, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Program Files (x86)\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named '_pywrap_tensorflow'


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
>>>

**Comment by andydavis1** [comment]
Please check common install issues:
https://www.tensorflow.org/install/install_windows#common_installation_problems
http://stackoverflow.com/questions/42011070/on-windows-running-import-tensorflow-generates-no-module-named-pywrap-tenso

**Comment by harishjmhss** [comment]
Problems are solved !!

I have uninstalled Python 3.5.1 and Installed Python 3.5.2, there is no problem in integrating with tensorflow and 3.5.2. Python 3.6.1 is also not supporting tensorflow.

So use 3.5.2 and install tensorflow for ease working.

**Comment by akkaman007** [comment]
I have installed the python 3.5.2 but i am still facing the same problem

**Comment by OmarKhanGithub** [comment]
I Installed python 3.5.2 and it fixed the problem after I made it the default, which I did by removing my 3.6.2 in control panel and adding the new python file location to the PATH in environment variables

**Comment by tarunnbansal** [comment]
its not working on my system installed with python version 3.7.0

I have already tried uninstalling and instaliing again from ..googleapis.. link using pip command

`pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_amd64.whl`

**Comment by oxanderv** [comment]
> gracias que funcionó solo instale 3.5.2 python e instale tensorflow ...
> 
yes, I'm installing python 3.5.2 and I followed this link.:

https://medium.com/intel-student-ambassadors/installing-tensorflow-on-windows-with-anaconda-af6fa6280a4b 

work to me..

**Comment by Anusha-K11** [comment]
1.Download Python 3.5.2 (3.5.2 only!!)
2.In command prompt : pip install tensorflow 
(ignore this --Cache entry deserialization failed, entry ignored)
3.:python
4.>>import tensorflow as tf (
if no error then successfully installed
5.>>print(tf.__version__) 
(use double underscore above)
![Screenshot (205)](https://user-images.githubusercontent.com/48626909/59749961-9fcb5580-929b-11e9-88de-7debe7c02f0d.png)
)
