### ISSUE TITLE
[bug] Distributed FIFOQueue dequeue duplicate data

### ISSUE THREAD

**Issue by mig23** [tensorflow/tensorflow#9536]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 14.04 
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.0.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0 5.1
- **GPU model and memory**:
Pascal TitanX 
- **Exact command to reproduce**:
https://gist.github.com/lispc/27c9f4fe935abade5de90c18276e1742

### Describe the problem
In distributed tensorflow, if I do multiple dequeue from a remote FIFOQueue, duplicate results will be popped. For example, 1 2 3 4 5 were pushed into the FIFOQueue, then the popped results may be 1 1 2 3 4 4 5. Is it a bug? Or designed feature?
The code is posted above. Logs is also in that gist.

**Comment by ppwwyyxx** [comment]
This is a bug fixed in 1.1.
#7038

**Comment by andydavis1** [comment]
Please re-open if upgrading to 1.1 does not solve the problem.
