### ISSUE TITLE
Missing image in https://www.tensorflow.org/api_docs/python/tf/gather

### ISSUE THREAD

**Issue by jlebar** [tensorflow/tensorflow#9709]
### System information
n/a

### Describe the problem

https://www.tensorflow.org/api_docs/python/tf/gather includes an image, https://www.tensorflow.org/api_docs/images/Gather.png, but this does not exist.  Gather.png doesn't seem to exist anywhere in the TF repository.

**Comment by kemaswill** [comment]
I think this has already be fixed by this commit: https://github.com/tensorflow/tensorflow/commit/7c3ad6569611aac36fd2527030bf98fb8756919f
Seems that the tensorflow.org does not update.

**Comment by jlebar** [comment]
Hi, the website still appears not to have been updated, and so the issue I reported still manifests.

Can we leave this open until the website is updated?  Or if there's a bug for the fact that we don't update the website frequently enough, I'd be OK dup'ing this to that one.

**Comment by drpngx** [comment]
Sure.

@wolffg @martinwicke on tensorflow.org refresh rate.

**Comment by yifeif** [comment]
Website has been updated. Closing this.
