### ISSUE TITLE
`tf.linalg.lu_solve` returns inconsistent output from CPU vs GPU

### ISSUE THREAD

**Issue by jiren-the-gray** [tensorflow/tensorflow#98345]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.21.0-dev20250801

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 24.04

### Python version

3.12

### Current behavior?

When running `tf.linalg.lu_solve` with a `float64` tesnor of large (but not overflowing) values, CPU and GPU returns wildly different values.

Also reproducible with Tensorflow `2.19.0`, please take a look at the [gist](https://colab.research.google.com/gist/jiren-the-gray/d9e7de1423286e756a272e7a3d263a74/tf_playground.ipynb).

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

print("TensorFlow version:", tf.__version__)	# TensorFlow version: 2.21.0-dev20250801

rng = np.random.default_rng(957)

lower_upper = tf.constant(rng.uniform(-9223372036854772000., -9223372036854771000., size=(3, 3)), dtype=tf.float64)
perm = tf.constant(rng.uniform(0., 0., size=(3,)), dtype=tf.int64)
rhs = tf.constant(rng.uniform(-100., 100., size=(3, 3)), dtype=tf.float64)
validate_args = True
name = "constant"

with tf.device("/CPU:0"):
        result = tf.linalg.lu_solve(
            lower_upper=lower_upper,
            perm=perm,
            rhs=rhs,
            validate_args=validate_args,
            name=name
        )
        print("Result (CPU):\n", result.numpy()[0, 2])

with tf.device("/GPU:0"):
        result = tf.linalg.lu_solve(
            lower_upper=lower_upper,
            perm=perm,
            rhs=rhs,
            validate_args=validate_args,
            name=name
        )
        print("Result (GPU):\n", result.numpy()[0, 2])
```

### Relevant log output

```shell
...
TensorFlow version: 2.21.0-dev20250801
...
Result (CPU):
 -0.0
Result (GPU):
 -47201.82360354644
```

**Comment by Aaraviitkgp** [comment]
hello @jiren-the-gray I tried to produce the error locally but it is coming fine for me.

<img width="963" height="136" alt="Image" src="https://github.com/user-attachments/assets/459e7928-640f-44ff-9853-34336a88b8f5" />

**Comment by jiren-the-gray** [comment]
@Aaraviitkgp Could you add this line before printing the GPU result?

```python
print("GPU available:", tf.config.list_physical_devices('GPU'))
```

I suspect the tensorflow you have installed can not access the GPU, because even with other input values where the inconsistency is not as big (and acceptable), the values are not equal to the extent of this precision as you are showing here, leading me to think that both executions took place on the CPU.

**Comment by Aaraviitkgp** [comment]
@jiren-the-gray you are right about it

**Comment by Venkat6871** [comment]
I was able to reproduce the issue on Colab using TensorFlow 2.18.0 and 2.19.0 with GPU enabled. Here i am providing colab [gist](https://colab.sandbox.google.com/gist/Venkat6871/defbd70c7060fefc1f3acf748003b1b6/98345_tf-2-18-0-2-19-0-v-gpu.ipynb) for reference.

Thank you!

**Comment by Venkat6871** [comment]
Hi @jiren-the-gray,
Sorry for the delay, and thanks for your patience.
This was fixed in TensorFlow 2.21. We generally do not backport fixes to older releases unless they are security-related or high severity, so the fix is only available starting from 2.21.

Please upgrade to the latest Tensorflow nightly version and let us know if you still see the issue.

Thank you!

**Comment by jiren-the-gray** [comment]
Hi @Venkat6871 , I can still reproduce it on `tf-nightly` (Tensorflow `2.21.0-dev20260127`). Please see this [gist](https://colab.research.google.com/gist/jiren-the-gray/90a65607cfc6d9f98ad0aff80087996a/tf-linalg-lu_solve_bug.ipynb).

**Comment by Venkat6871** [comment]
Hi @jiren-the-gray, thanks for the detailed repro.

To help us better understand the impact, could you share a bit more context on:
- how this was originally encountered (real model/workload vs synthetic test),
- whether `inf` or very large values are expected in your inputs, and
- whether this behavior is blocking training or inference in practice?

This will help us determine whether this is a numerical stability limitation or something that needs further action.

Thanks!
